Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2019-10, with the labels that each got.

#316 Change nationalities text fields to be dropdowns
  app/helpers/view_helper.rb
  app/views/candidate_interface/personal_details/edit.html.erb
  config/locales/application_form.yml
  spec/helpers/view_helper_spec.rb
  spec/system/candidate_interface/candidate_entering_personal_details_spec.rb
Labels: Candidate

#322 Create a temporary ApplicationChoice for demo purposes
  app/models/candidate.rb
  spec/system/candidate_interface/candidate_viewing_application_spec.rb
Labels: Candidate

#325 Properly implement the "unsubmitted" status
  app/models/application_choice.rb
  app/services/application_state_change.rb
  app/services/vendor_api/single_application_presenter.rb
  config/locales/en.yml
  db/migrate/20191015153328_dont_allow_null_for_status.rb
  db/schema.rb
  docs/states.png
  spec/factories.rb
  spec/models/application_choice_spec.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
  spec/requests/vendor_api/post_reject_application_spec.rb
  spec/services/application_state_change_spec.rb
Labels: Core

#314 Complete personal details section
  app/controllers/candidate_interface/application_form_controller.rb
  app/controllers/candidate_interface/personal_details_controller.rb
  app/frontend/styles/_task-list.scss
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/application_form/show.html.erb
  app/views/candidate_interface/personal_details/show.html.erb
  config/routes.rb
  spec/factories.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/system/candidate_interface/candidate_entering_personal_details_spec.rb
Labels: Candidate

#319 Add autocomplete for nationality fields
  app/frontend/packs/application.js
  app/frontend/styles/application.scss
  package.json
  yarn.lock
Labels: Candidate

#323 Add Provider and Course models
  app/controllers/provider_interface/application_choices_controller.rb
  app/controllers/vendor_api/applications_controller.rb
  app/models/application_choice.rb
  app/models/candidate.rb
  app/models/course.rb
  app/models/provider.rb
  app/services/generate_test_data.rb
  app/services/provider_interface/application_choice_presenter.rb
  app/services/vendor_api/single_application_presenter.rb
  db/migrate/20191015090226_create_providers.rb
  db/migrate/20191015090847_create_courses.rb
  db/migrate/20191015101437_add_course_and_site_to_application_choice.rb
  db/migrate/20191015102947_remove_fields_from_application_choice.rb
  db/schema.rb
  docs/domain-model.png
  docs/states.png
  spec/factories.rb
  spec/models/application_choice_spec.rb
  spec/requests/vendor_api/get_multiple_applications_spec.rb
  spec/requests/vendor_api/get_single_application_spec.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
  spec/services/generate_test_data_spec.rb
  spec/system/provider_interface/see_applications_spec.rb
  spec/system/support_interface/manage_applications_spec.rb
Labels: Core

#335 Update nationalities to use ISO code
  .rubocop.yml
  app/helpers/view_helper.rb
  app/models/candidate_interface/personal_details_form.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  config/initializers/nationalities.rb
  spec/factories.rb
  spec/helpers/view_helper_spec.rb
  spec/models/candidate_interface/personal_details_form_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
Labels: Core

#327 Make english_main_language not default to false when it's nil
  app/models/candidate_interface/personal_details_form.rb
  spec/models/candidate_interface/personal_details_form_spec.rb
Labels: Candidate

#338 Check that users are signed in on personal details forms
  app/controllers/candidate_interface/application_form_controller.rb
  app/controllers/candidate_interface/application_review_controller.rb
  app/controllers/candidate_interface/applying_controller.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/sign_in_controller.rb
  app/controllers/candidate_interface/sign_up_controller.rb
  app/controllers/candidate_interface/start_page_controller.rb
  spec/system/candidate_interface/candidate_entering_personal_details_spec.rb
Labels: Candidate

#341 Link to the application form if the user is signed in
  app/helpers/application_helper.rb
  spec/system/candidate_interface/candidate_account_spec.rb
Labels: Candidate

#336 Connect API tokens to providers
  app/controllers/support_interface/api_tokens_controller.rb
  app/controllers/vendor_api/applications_controller.rb
  app/controllers/vendor_api/decisions_controller.rb
  app/controllers/vendor_api/test_data_controller.rb
  app/controllers/vendor_api/vendor_api_controller.rb
  app/models/provider.rb
  app/models/vendor_api_token.rb
  app/services/generate_test_data.rb
  app/views/support_interface/api_tokens/index.html.erb
  config/vendor-api-0.5.0.yml
  db/migrate/20191016153741_add_provider_to_vendor_api_tokens.rb
  db/schema.rb
  docs/domain-model.png
  lib/tasks/generate_test_data.rake
  spec/models/vendor_api_token_spec.rb
  spec/requests/vendor_api/api_authentication_spec.rb
  spec/requests/vendor_api/get_multiple_applications_spec.rb
  spec/requests/vendor_api/get_single_application_spec.rb
  spec/requests/vendor_api/post_conditions_met_spec.rb
  spec/requests/vendor_api/post_confirm_enrolment_spec.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
  spec/requests/vendor_api/post_reject_application_spec.rb
  spec/services/generate_test_data_spec.rb
  spec/support/vendor_api/vendor_api_spec_helpers.rb
  spec/system/support_interface/api_tokens_spec.rb
Labels: ProVendor

#342 Fix saving both other languages spoken and English language qualifications
  app/models/candidate_interface/personal_details_form.rb
  spec/models/candidate_interface/personal_details_form_spec.rb
Labels: Core

#334 Review and submit application page
  app/controllers/candidate_interface/application_form_controller.rb
  app/controllers/candidate_interface/application_review_controller.rb
  app/services/submit_application.rb
  app/views/candidate_interface/application_form/review.html.erb
  app/views/candidate_interface/application_form/submit_show.html.erb
  app/views/candidate_interface/application_form/submit_success.html.erb
  app/views/candidate_interface/application_review/show.html.erb
  app/views/candidate_interface/sign_in/new.html.erb
  app/views/candidate_interface/sign_up/new.html.erb
  config/locales/authentication.yml
  config/locales/en.yml
  config/locales/review_application.yml
  config/locales/submit_application.yml
  config/locales/submit_application_success.yml
  config/routes.rb
  spec/services/submit_application_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/support/test_helpers/sign_up.rb
  spec/system/candidate_interface/candidate_account_spec.rb
  spec/system/candidate_interface/candidate_entering_personal_details_spec.rb
  spec/system/candidate_interface/candidate_reviewing_application_spec.rb
  spec/system/candidate_interface/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/candidate_viewing_application_spec.rb
Labels: Candidate

#351 Allow users to provide additional information via a free text box when application submission
  app/controllers/candidate_interface/application_form_controller.rb
  app/models/candidate_interface/further_information_form.rb
  app/views/candidate_interface/application_form/submit_show.html.erb
  config/locales/application_form.yml
  db/migrate/20191021122607_add_further_information_fields_to_application_form.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/models/candidate_interface/further_information_form_spec.rb
  spec/system/candidate_interface/candidate_submitting_application_spec.rb
Labels: Candidate

#346 Add Site and CourseOption models
  app/models/application_choice.rb
  app/models/candidate.rb
  app/models/course.rb
  app/models/course_option.rb
  app/models/provider.rb
  app/models/site.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/generate_test_data.rb
  config/vendor-api-0.5.0.yml
  db/migrate/20191016140605_create_sites.rb
  db/migrate/20191016140945_create_course_options.rb
  db/migrate/20191017113254_alter_application_choices_to_reference_course_options.rb
  db/migrate/20191018101658_add_courses_level.rb
  db/migrate/20191022080206_add_courses_start_date.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/models/application_choice_spec.rb
  spec/models/course_option_spec.rb
  spec/models/course_spec.rb
  spec/models/site_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/requests/vendor_api/get_multiple_applications_spec.rb
  spec/requests/vendor_api/get_single_application_spec.rb
  spec/requests/vendor_api/post_conditions_met_spec.rb
  spec/requests/vendor_api/post_confirm_enrolment_spec.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
  spec/requests/vendor_api/post_reject_application_spec.rb
  spec/support/test_helpers/course_option_helpers.rb
  spec/support/vendor_api/vendor_api_spec_helpers.rb
  spec/system/provider_interface/see_applications_spec.rb
Labels: Core

#349 Hide personal details SummaryCardComponent if incomplete
  app/components/personal_details_review_component.html.erb
  app/components/personal_details_review_component.rb
  app/controllers/candidate_interface/application_form_controller.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/views/candidate_interface/application_form/review.html.erb
  app/views/candidate_interface/personal_details/show.html.erb
  spec/components/personal_details_review_component_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
Labels: Candidate

#345 Add accessibility statement page
  app/controllers/accessibility_controller.rb
  app/views/accessibility/show.html.erb
  app/views/layouts/application.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/user_viewing_accessibility_statement_spec.rb
Labels: Candidate

#368 Render accessibility statement from markdown
  Gemfile
  Gemfile.lock
  app/controllers/accessibility_controller.rb
  app/controllers/content_controller.rb
  app/frontend/styles/_styled-content.scss
  app/frontend/styles/application.scss
  app/views/accessibility/show.html.erb
  app/views/content/accessibility.md
  app/views/content/rendered_markdown_template.html.erb
  config/routes.rb
Labels: Candidate

#382 Add validation to contact details
  Gemfile
  Gemfile.lock
  app/components/application_complete_content_component.html.erb
  app/models/candidate_interface/contact_details_form.rb
  app/validators/phone_number_validator.rb
  app/validators/postcode_validator.rb
  app/views/candidate_interface/application_form/submit_show.html.erb
  app/views/candidate_interface/contact_details/address/edit.html.erb
  app/views/candidate_interface/contact_details/base/edit.html.erb
  app/views/candidate_interface/contact_details/review/show.html.erb
  app/views/candidate_interface/personal_details/edit.html.erb
  config/locales/application_form.yml
  spec/models/candidate_interface/contact_details_form_spec.rb
  spec/system/candidate_interface/candidate_entering_contact_details_spec.rb
  spec/validators/phone_number_validator_spec.rb
  spec/validators/postcode_validator_spec.rb
Labels: Candidate

#385 Add editing, completed label and review of contact details
  app/components/contact_details_review_component.html.erb
  app/components/contact_details_review_component.rb
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/candidate_interface/contact_details/base_controller.rb
  app/controllers/candidate_interface/contact_details/review_controller.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/application_form/review.html.erb
  app/views/candidate_interface/application_form/show.html.erb
  app/views/candidate_interface/contact_details/review/show.html.erb
  spec/components/contact_details_review_component_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_contact_details_spec.rb
  spec/system/candidate_interface/candidate_reviewing_application_spec.rb
  spec/system/candidate_interface/candidate_submitting_application_spec.rb
Labels: Candidate

#389 Create ApplicationExperience model and table
  app/models/application_experience.rb
  app/models/application_form.rb
  app/models/application_volunteering_experience.rb
  app/models/application_work_experience.rb
  db/migrate/20191025141802_create_application_experience.rb
  db/schema.rb
  docs/domain-model.png
Labels: Core

#391 Production Deployment
  Dockerfile
  azure-pipelines-deploy-template.yml
  azure-pipelines.yml
  azure/template.json
  config/environments/production.rb
  docker-compose.azure.yml
Labels: DevOps

#378 Add audit trail
  Gemfile
  Gemfile.lock
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/vendor_api/decisions_controller.rb
  app/controllers/vendor_api/vendor_api_controller.rb
  app/models/application_choice.rb
  app/models/application_form.rb
  app/models/vendor_api_user.rb
  config/initializers/audited.rb
  db/migrate/20191022145559_install_audited.rb
  db/migrate/20191023154827_create_vendor_api_users.rb
  db/migrate/20191028105220_rename_vendor_api_users_user_id.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/models/application_choice_spec.rb
  spec/models/application_form_spec.rb
  spec/models/vendor_api_user_spec.rb
  spec/requests/candidate_interface/audit_trail_spec.rb
  spec/requests/vendor_api/audit_trail_spec.rb
  spec/support/vendor_api/vendor_api_spec_helpers.rb
Labels: Core, ProVendor

#374 Synchronise the API with the prototype
  app/models/application_experience.rb
  app/models/candidate_interface/further_information_form.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/generate_test_data.rb
  config/initializers/faker.rb
  config/vendor-api-0.5.0.yml
  db/migrate/20191024085938_rename_application_form_further_information_and_remove_boolean.rb
  db/migrate/20191024103914_add_disability_disclosure_to_application_form.rb
  db/migrate/20191024142841_add_residency_status_to_application_form.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/models/candidate_interface/further_information_form_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/requests/vendor_api/get_multiple_applications_spec.rb
Labels: ProVendor

#393 Add ApplicationQualification table with models using a `level` enum
  app/models/application_form.rb
  app/models/application_qualification.rb
  db/migrate/20191028115549_create_application_qualification.rb
  db/schema.rb
  docs/domain-model.png
  spec/models/application_qualification_spec.rb
Labels: Core

#390 Introduce cucumber for specification by example around the application business rules
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Makefile
  Rakefile
  azure-pipelines.yml
  config/cucumber.yml
  features/step_definitions/application_steps.rb
  features/successful_application_statuses.feature
  features/support/env.rb
  lib/tasks/cucumber.rake
  script/cucumber
Labels: Core

#376 Track API requests
  .env.example
  Gemfile
  Gemfile.lock
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/vendor_api/vendor_api_controller.rb
  app/lib/logstash_logging.rb
  azure/template.json
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  db/schema.rb
  docker-compose.azure.yml
  docs/domain-model.png
Labels: Core

#388 Avoid duplicate codes for courses and sites
  app/models/course.rb
  app/services/generate_test_data.rb
  spec/services/generate_test_data_spec.rb
Labels: Core
