Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2020-06, with the labels that each got.

#2187 Add health check test post deployment
  health-check-template.yml
  swap-staging-production-template.yml
Labels: DevOps

#2198 Remove enrolment section from offer_accepted email
  app/views/provider_mailer/offer_accepted.text.erb
Labels: ProVendor

#2204 Add manage_organisations provider permission column
  db/migrate/20200603153852_add_manage_organisations_permission.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#2203 Lower RBD time limit to 20 days after 1st July 2020
  app/components/candidate_interface/referee_guidance_component.html.erb
  app/components/candidate_interface/referee_guidance_component.rb
  app/lib/time_limit_config.rb
  app/mailers/candidate_mailer.rb
  app/mailers/provider_mailer.rb
  app/views/candidate_mailer/application_submitted.text.erb
  app/views/provider_mailer/chase_provider_decision.text.erb
  spec/components/candidate_interface/referee_guidance_component_spec.rb
  spec/mailers/provider_mailer_spec.rb
  spec/services/time_limit_calculator_spec.rb
  spec/support/test_helpers/mailer_setup_helper.rb
  spec/system/provider_interface/provider_receives_email_when_an_application_is_getting_close_to_the_reject_by_default_date_spec.rb
Labels: Candidate

#2197 Refactor reference safeguarding attributes
  app/components/provider_interface/reference_with_feedback_component.rb
  app/components/referee_interface/reference_review_component.rb
  app/controllers/referee_interface/reference_controller.rb
  app/lib/test_applications.rb
  app/models/application_reference.rb
  app/models/referee_interface/reference_safeguarding_form.rb
  app/services/submit_application.rb
  db/migrate/20200527170532_backfill_application_references_safeguarding_concerns_status.rb
  features/step_definitions/application_steps.rb
  spec/components/provider_interface/reference_with_feedback_component_spec.rb
  spec/components/referee_interface/reference_review_component_spec.rb
Labels: Candidate

#2196 Content changes to speed up the reference process
  app/components/candidate_interface/additional_referees_start_component.html.erb
  app/components/candidate_interface/additional_referees_start_component.rb
  app/components/candidate_interface/referee_guidance_component.html.erb
  app/components/candidate_interface/referee_guidance_component.rb
  app/components/candidate_interface/referees_review_component.html.erb
  app/components/candidate_interface/referees_review_component.rb
  app/controllers/candidate_interface/referees_controller.rb
  app/lib/time_limit_config.rb
  app/views/candidate_interface/application_form/edit_by_support.html.erb
  app/views/candidate_interface/application_form/submit_success.html.erb
  app/views/candidate_interface/referees/confirm_cancel.html.erb
  config/locales/application_form.yml
  spec/components/candidate_interface/additional_referees_start_component_spec.rb
  spec/components/candidate_interface/referee_guidance_component_spec.rb
  spec/components/candidate_interface/referees_review_component_spec.rb
  spec/lib/time_limit_config_spec.rb
  spec/system/candidate_interface/candidate_cancels_a_reference_spec.rb
  spec/system/candidate_interface/candidate_replaces_reference_after_applying_again_spec.rb
Labels: Candidate

#2211 Update candidate application submitted email content
  app/views/candidate_mailer/application_submitted.text.erb
Labels: Candidate, Content

#2213 Update referee content for email bounced and reference refused emails
  app/views/candidate_mailer/new_referee_request.text.erb
  config/locales/candidate_mailer.yml
  spec/mailers/candidate_mailer_referee_mails_spec.rb
Labels: Candidate, Content

#2216 Update referee and candidate chaser emails content
  app/mailers/candidate_mailer.rb
  app/mailers/referee_mailer.rb
  app/views/candidate_mailer/chase_reference_again.text.erb
  app/views/candidate_mailer/chase_references_again.text.erb
  app/views/referee_mailer/reference_request_chase_again_email.html.erb
  app/views/referee_mailer/reference_request_chaser_email.text.erb
  app/views/referee_mailer/reference_request_email.text.erb
  app/workers/send_additional_reference_chase_email_to_both_parties_worker.rb
  config/clock.rb
  config/locales/application_states.yml
  config/locales/candidate_mailer.yml
  config/locales/chaser_emails.yml
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/mailers/previews/referee_mailer_preview.rb
  spec/mailers/referee_mailer_spec.rb
  spec/support_specs/clockwork_spec.rb
  spec/system/candidate_interface/candidate_needs_to_provide_new_referee_spec.rb
  spec/system/candidate_interface/candidate_needs_to_provide_two_new_referees_spec.rb
  spec/system/referee_interface/referee_does_not_respond_spec.rb
  spec/workers/send_additional_reference_chase_email_to_both_parties_worker_spec.rb
Labels: Candidate, Content

#2220 Migration to add withdrawn boolean to courses
  db/migrate/20200605131701_add_withdrawn_boolean_to_course.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#2219 Add phase to application export CSV
  app/services/support_interface/application_choices_export.rb
  spec/services/application_choices_export_spec.rb
  spec/services/support_interface/application_choices_export_spec.rb
Labels: Support

#2199 Adding a note updates the ApplicationChoice's updated_at
  app/models/note.rb
  spec/models/note_spec.rb
Labels: ProVendor

#2189 Fix font size and spacing on applications appearing in provider application index
  app/components/provider_interface/application_card_component.html.erb
  app/frontend/styles/_application-card.scss
  app/frontend/styles/_notes.scss
Labels: ProVendor

#2201 Show a useful error when API clients try to make offers to a closed course
  app/controllers/vendor_api/decisions_controller.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
Labels: ProVendor

#2236 Update incorrect content in referee review component
  app/components/candidate_interface/referees_review_component.rb
  spec/components/candidate_interface/referees_review_component_spec.rb
Labels: Candidate

#2238 Small follow up content tweaks for chaser emails
  app/components/candidate_interface/additional_referees_start_component.rb
  app/mailers/referee_mailer.rb
  app/views/candidate_mailer/new_referee_request.text.erb
  app/views/referee_mailer/reference_request_chase_again_email.html.erb
  config/locales/candidate_mailer.yml
  spec/components/candidate_interface/additional_referees_start_component_spec.rb
  spec/mailers/candidate_mailer_referee_mails_spec.rb
  spec/mailers/previews/referee_mailer_preview.rb
  spec/mailers/referee_mailer_spec.rb
Labels: Candidate

#2229 Fix Withdrawn by us and Rejected filters
  app/models/application_choice.rb
  app/services/filter_application_choices_for_providers.rb
  spec/models/application_choice_spec.rb
  spec/services/provider_interface/filter_application_choices_for_providers_spec.rb
  spec/system/provider_interface/provider_applications_filter_spec.rb
Labels: ProVendor

#2237 Add replace course choice banner
  app/components/candidate_interface/new_course_choice_needed_banner_component.html.erb
  app/components/candidate_interface/new_course_choice_needed_banner_component.rb
  app/models/application_form.rb
  app/models/course_option.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/application_form/complete.html.erb
  spec/components/candidate_interface/new_course_choice_needed_banner_component_spec.rb
  spec/models/application_form_spec.rb
  spec/models/course_option_spec.rb
  spec/system/candidate_interface/course_selection/candidate_can_replace_full_or_withdrawn_course_choices_spec.rb
Labels: Candidate

#2241 Refactor course option validation in ChangeOffer and MakeOffer
  app/controllers/provider_interface/decisions_controller.rb
  app/controllers/provider_interface/offer_changes_controller.rb
  app/controllers/vendor_api/decisions_controller.rb
  app/lib/test_applications.rb
  app/models/provider_interface/change_offer_form.rb
  app/services/change_offer.rb
  app/services/make_an_offer.rb
  app/views/provider_interface/decisions/confirm_offer.html.erb
  app/views/provider_interface/decisions/new_offer.html.erb
  config/locales/en.yml
  spec/requests/provider_interface/audit_trail_spec.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
  spec/services/change_offer_spec.rb
  spec/services/make_an_offer_spec.rb
Labels: ProVendor

#2244 Allow candidate to select a course choice to replace
  app/components/candidate_interface/new_course_choice_needed_banner_component.html.erb
  app/controllers/candidate_interface/course_choices/replace_choice_controller.rb
  app/models/candidate_interface/pick_choice_to_replace_form.rb
  app/views/candidate_interface/course_choices/replace_choice/choose_option.html.erb
  app/views/candidate_interface/course_choices/replace_choice/pick_choice_to_replace.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/models/candidate_interface/pick_choice_to_replace_form_spec.rb
  spec/system/candidate_interface/course_selection/candidate_can_replace_full_or_withdrawn_course_choices_spec.rb
Labels: Candidate

#2242 Send email to candidate when course fills while awaiting references
  app/mailers/candidate_mailer.rb
  app/models/application_choice.rb
  app/models/chaser_sent.rb
  app/services/feature_flag.rb
  app/services/get_application_choices_with_newly_unavailable_courses.rb
  app/services/reason_course_not_available.rb
  app/views/candidate_mailer/course_unavailable_course_full.text.erb
  app/views/candidate_mailer/course_unavailable_course_withdrawn.text.erb
  app/views/candidate_mailer/course_unavailable_location_full.text.erb
  app/views/candidate_mailer/course_unavailable_study_mode_full.text.erb
  app/workers/send_course_full_notifications_worker.rb
  config/clock.rb
  config/locales/candidate_mailer.yml
  spec/factories.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/get_application_choices_with_newly_unavailable_courses_spec.rb
  spec/system/support_interface/docs_spec.rb
  spec/workers/send_course_full_notifications_worker_spec.rb
Labels: Candidate

#2247 Filters on small screens js
  app/frontend/packs/application.js
  app/frontend/packs/provider-filter.js
  app/frontend/styles/_filter.scss
  app/frontend/styles/_provider.scss
  app/frontend/styles/application.scss
  app/views/provider_interface/application_choices/index.html.erb
  config/webpack/environment.js
  config/webpacker.yml
  package.json
  yarn.lock
Labels: ProVendor

#2232 Upgrade to Ruby 2.7
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  app/models/validation_error.rb
Labels: Core, ruby

#2255 Switch test data to more complex providers
  app/lib/test_applications.rb
  app/workers/generate_test_applications.rb
  lib/tasks/local_dev.rake
Labels: ProVendor

#2253 Remove the safeguarding question from the referee questionnaire
  app/controllers/referee_interface/questionnaire_form.rb
  app/controllers/referee_interface/reference_controller.rb
  app/views/referee_interface/reference/confirmation.html.erb
  spec/models/referee_interface/questionnaire_form_spec.rb
Labels: Candidate

#2265 Fix mailer previews
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/mailers/previews/provider_mailer_preview.rb
  spec/mailers/previews/referee_mailer_preview.rb
Labels: Core

#2264 Add structured_rejection_reasons column to application_choice table
  db/migrate/20200612105651_add_structured_rejection_reasons_to_application_choices.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#2260 Make pagination align with application cards
  app/components/header_component.html.erb
  app/frontend/styles/_filter.scss
  app/views/provider_interface/application_choices/index.html.erb
Labels: ProVendor

#2261 Complete the replace course choice flow for location
  app/components/candidate_interface/course_option_review_component.html.erb
  app/components/candidate_interface/course_option_review_component.rb
  app/controllers/candidate_interface/course_choices/replace_choice_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/base_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/decision_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/review_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/site_selection_controller.rb
  app/models/application_form.rb
  app/models/candidate_interface/pick_replacement_action_form.rb
  app/models/candidate_interface/pick_site_form.rb
  app/views/candidate_interface/course_choices/replace_choice/choose_option.html.erb
  app/views/candidate_interface/course_choices/replace_choices/base/pick_choice_to_replace.html.erb
  app/views/candidate_interface/course_choices/replace_choices/decision/choose_action.html.erb
  app/views/candidate_interface/course_choices/replace_choices/decision/contact_support.html.erb
  app/views/candidate_interface/course_choices/replace_choices/review/confirm_choice.html.erb
  app/views/candidate_interface/course_choices/replace_choices/site_selection/replace_location.html.erb
  app/views/candidate_interface/course_choices/shared/_site_fields.html.erb
  app/views/candidate_interface/course_choices/site_selection/new.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/candidate_interface/course_option_review_component_spec.rb
  spec/models/candidate_interface/pick_replacement_action_form_spec.rb
  spec/system/candidate_interface/course_selection/candidate_can_replace_full_or_withdrawn_course_choices_spec.rb
Labels: Candidate

#2262 Fix menu collapse on small screens
  app/components/header_component.html.erb
  app/components/provider_interface/header_component.html.erb
Labels: ProVendor

#2256 Content update to micro site
  app/views/provider_interface/start_page/show.html.erb
  public/provider/respond.png
Labels: ProVendor

#2267 optimise Dockerfile
  .dockerignore
  Dockerfile
  docker-compose.override.yml
  docker-compose.yml
  spec/azure/configuration_spec.rb
Labels: DevOps

#2258 Fix typo in email name
  app/mailers/provider_mailer.rb
  app/services/withdraw_application.rb
  app/views/provider_mailer/application_withdrawn.text.erb
  config/locales/application_states.yml
  config/locales/provider_notifications.yml
  spec/mailers/previews/provider_mailer_preview.rb
  spec/mailers/provider_mailer_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: ProVendor

#2202 Add organisations index and details pages
  app/controllers/provider_interface/organisations_controller.rb
  app/controllers/provider_interface/provider_relationship_permissions_controller.rb
  app/models/navigation_items.rb
  app/models/provider.rb
  app/models/provider_user.rb
  app/views/provider_interface/organisations/_check_icon.html.erb
  app/views/provider_interface/organisations/_permissions_list.html.erb
  app/views/provider_interface/organisations/index.html.erb
  app/views/provider_interface/organisations/show.html.erb
  app/views/provider_interface/provider_relationship_permissions/success.html.erb
  config/routes.rb
  spec/models/provider_spec.rb
  spec/models/provider_user_spec.rb
  spec/requests/provider_interface/see_organisations_pages_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
Labels: ProVendor

#2275 Silence Redis deprecation warnings in worker logs
  config/initializers/redis.rb
Labels: Core

#2281 Add new course flow link to the course full emails
  app/views/candidate_mailer/course_unavailable_course_full.text.erb
  app/views/candidate_mailer/course_unavailable_course_withdrawn.text.erb
  app/views/candidate_mailer/course_unavailable_location_full.text.erb
  app/views/candidate_mailer/course_unavailable_study_mode_full.text.erb
  spec/mailers/candidate_mailer_spec.rb
Labels: Candidate

#2283 Do not try to delete invalid course_options which are part of offers
  app/services/sync_provider_from_find.rb
  spec/services/sync_provider_from_find_spec.rb
Labels: Core

#2277 Remove spec assertions that were false and only passed by accident
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: Core

#2248 Enforce make_decisions user permission if feature flag is on
  app/controllers/provider_interface/application_choices_controller.rb
  app/controllers/provider_interface/decisions_controller.rb
  app/controllers/provider_interface/offer_changes_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/models/provider.rb
  app/services/change_offer.rb
  app/services/provider_authorisation.rb
  app/views/provider_interface/application_choices/_application_choice_header.html.erb
  app/views/provider_interface/permission_error.html.erb
  spec/factories.rb
  spec/requests/provider_interface/audit_trail_spec.rb
  spec/services/change_offer_spec.rb
  spec/services/make_an_offer_spec.rb
  spec/services/provider_authorisation_spec.rb
  spec/support/test_helpers/provider_user_permissions_helper.rb
  spec/system/provider_interface/provider_changes_an_offer_spec.rb
  spec/system/provider_interface/provider_makes_an_offer_spec.rb
  spec/system/provider_interface/provider_makes_changes_before_offer_spec.rb
  spec/system/provider_interface/provider_responds_to_application_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: ProVendor

#2294 Generate TAD performance reports
  .rubocop.yml
  app/controllers/support_interface/performance_controller.rb
  app/lib/test_applications.rb
  app/services/support_interface/tad_provider_stats_export.rb
  app/views/support_interface/performance/index.html.erb
  config/initializers/inflector.rb
  config/routes.rb
  spec/services/support_interface/tad_provider_stats_export_spec.rb
  spec/system/support_interface/tad_provider_performance_spec.rb
Labels: Support

#2293 publish rspec test results even on test run failure
  .gitignore
  Gemfile
  Gemfile.lock
  Makefile
  azure-pipelines.yml
  rspec-job-template.yml
  run-rspec-test-template.yml
  spec/spec_helper.rb
Labels: DevOps

#2302 Add make_decisions checkboxes to provider pages for managing organisations
  app/controllers/provider_interface/provider_relationship_permissions_controller.rb
  app/views/provider_interface/organisations/_permissions_list.html.erb
  app/views/provider_interface/provider_relationship_permissions/_provider_permissions.html.erb
  app/views/provider_interface/provider_relationship_permissions/confirm.html.erb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
  app/views/provider_interface/provider_relationship_permissions/success.html.erb
  spec/system/provider_interface/manage_provider_relationship_permissions_spec.rb
Labels: ProVendor

#2310 Add missing path helper delegation to PickCourseOption service
  app/services/candidate_interface/pick_course_option.rb
Labels: Candidate

#2274 Add conditional logic for radio buttons and content n the replace course choice flow
  app/components/candidate_interface/replacement_action_component.html.erb
  app/components/candidate_interface/replacement_action_component.rb
  app/controllers/candidate_interface/course_choices/replace_choices/decision_controller.rb
  app/models/course_option.rb
  app/views/candidate_interface/course_choices/replace_choices/decision/choose_action.html.erb
  spec/components/candidate_interface/replacement_action_component_spec.rb
  spec/models/course_option_spec.rb
Labels: Candidate

#2276 Add replace study mode and keep course flow
  app/controllers/candidate_interface/course_choices/replace_choices/decision_controller.rb
  app/models/application_form.rb
  spec/system/candidate_interface/course_selection/candidate_can_replace_full_or_withdrawn_course_choices_spec.rb
Labels: Candidate

#2285 Add cancel choice and withdraw application to replace choice
  app/components/candidate_interface/apply_again_banner_component.html.erb
  app/components/candidate_interface/apply_again_banner_component.rb
  app/components/candidate_interface/new_course_choice_needed_banner_component.rb
  app/components/candidate_interface/replacement_action_component.html.erb
  app/controllers/candidate_interface/course_choices/replace_choices/cancel_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/decision_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/review_controller.rb
  app/models/application_form.rb
  app/views/candidate_interface/application_form/complete.html.erb
  app/views/candidate_interface/course_choices/replace_choices/cancel/confirm_cancel.html.erb
  app/views/candidate_interface/course_choices/replace_choices/cancel/confirm_withdraw.html.erb
  app/views/candidate_interface/course_choices/replace_choices/decision/contact_support.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/candidate_interface/apply_again_banner_component_spec.rb
  spec/models/application_form_spec.rb
  spec/system/candidate_interface/candidate_removes_a_full_or_withdrawn_course_choice_post_submission_spec.rb
  spec/system/candidate_interface/course_selection/candidate_can_replace_full_or_withdrawn_course_choices_spec.rb
Labels: Candidate

#2305 Split degrees controller wrap-up
  app/components/candidate_interface/degrees_review_component.html.erb
  app/components/candidate_interface/degrees_review_component.rb
  app/controllers/candidate_interface/degrees/base_controller.rb
  app/controllers/candidate_interface/degrees/destroy_controller.rb
  app/controllers/candidate_interface/degrees/grade_controller.rb
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/controllers/candidate_interface/degrees/review_controller.rb
  app/controllers/candidate_interface/degrees/subject_controller.rb
  app/controllers/candidate_interface/degrees/type_controller.rb
  app/controllers/candidate_interface/degrees/year_controller.rb
  app/forms/candidate_interface/degree_form.rb
  app/views/candidate_interface/degrees/destroy/confirm_destroy.html.erb
  config/locales/application_form.yml
  config/routes.rb
  spec/components/candidate_interface/degrees_review_component_spec.rb
  spec/support/active_record_relation_stub.rb
Labels: Candidate

#2303 Remove manual deployment sign in check for staging
  docs/deployment_checklist.md
Labels: Core

#2231 Provider user needing to set organisation permissions sets them on first login
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/provider_interface/provider_relationship_permissions_controller.rb
  app/forms/provider_interface/provider_relationship_permissions_form.rb
  app/models/provider_user.rb
  app/services/provider_authorisation.rb
  app/views/provider_interface/provider_relationship_permissions/setup.html.erb
  app/views/provider_interface/provider_relationship_permissions/success.html.erb
  config/routes.rb
  spec/forms/provider_interface/provider_relationship_permissions_form_spec.rb
  spec/models/provider_user_spec.rb
  spec/requests/provider_interface/provider_relationship_permissions_request_spec.rb
  spec/requests/provider_interface/provider_relationship_permissions_setup_spec.rb
  spec/services/provider_authorisation_spec.rb
  spec/system/provider_interface/manage_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
  spec/system/provider_interface/setup_provider_relationship_permissions_spec.rb
Labels: ProVendor

#2306 Show logs when running under Foreman
  config/environments/development.rb
  config/initializers/okcomputer.rb
Labels: Core

#2308 Fix a bug in the TAD performance report
  app/lib/test_applications.rb
  app/services/application_state_change.rb
  app/services/support_interface/tad_provider_stats_export.rb
  spec/services/support_interface/tad_provider_stats_export_spec.rb
Labels: ProVendor

#2301 Create document with lessons learned
  README.md
  docs/lessons-learned.md
Labels: Core

#2324 Set last_signed_in_at on a candidate when generating test applications
  app/lib/test_applications.rb
  spec/lib/test_applications_spec.rb
Labels: Candidate

#2287 Stop emails from sandbox
  app/components/provider_interface/email_log_row_component.html.erb
  app/components/provider_interface/email_log_row_component.rb
  app/components/sub_navigation_component.html.erb
  app/controllers/provider_interface/application_choices_controller.rb
  app/views/api_docs/pages/release_notes.md
  app/views/provider_interface/application_choices/emails.html.erb
  config/initializers/mail_interceptors.rb
  config/routes.rb
  lib/sandbox_interceptor.rb
  spec/lib/sandbox_interceptor_spec.rb
  spec/requests/provider_interface/email_log_spec.rb
  spec/system/provider_interface/sandbox_emails_spec.rb
Labels: ProVendor, Sandbox

#2315 Refactor provider UI to rely on #can_make_offer?
  app/controllers/provider_interface/decisions_controller.rb
  app/controllers/provider_interface/offer_changes_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/provider_interface/sessions_controller.rb
  app/services/provider_authorisation.rb
  app/views/provider_interface/permission_error.html.erb
  spec/services/provider_authorisation_spec.rb
  spec/support/test_helpers/provider_relationship_permissions_helper.rb
  spec/support/test_helpers/provider_user_permissions_helper.rb
  spec/system/provider_interface/provider_cannot_respond_to_application_spec.rb
  spec/system/provider_interface/provider_responds_to_application_spec.rb
Labels: ProVendor

#2334 rename image name in makefile
  Makefile
Labels: DevOps

#2325 Course choices link should redirect to the course choices review path
  app/components/candidate_interface/application_form_course_choices_component.rb
  spec/components/candidate_interface/application_form_course_choices_component_spec.rb
Labels: Candidate

#2337 Fix first login 'Access Denied' bug when other org setups are pending
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/provider_interface/provider_relationship_permissions_controller.rb
  app/views/provider_interface/provider_relationship_permissions/setup.html.erb
  spec/requests/provider_interface/provider_relationship_permissions_setup_spec.rb
Labels: ProVendor

#2327 Add withdrawal feedback column to application choice
  db/migrate/20200623080554_add_withdrawal_feedback_to_application_choice.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#2329 SyncProviderFromFind can work on providers from different recruitment cycles
  app/models/find_api/provider.rb
  app/services/sync_all_providers_from_find.rb
  app/services/sync_provider_from_find.rb
  spec/services/sync_provider_from_find_spec.rb
  spec/support/test_helpers/find_api_helper.rb
  spec/system/sync_provider_from_find/site_is_deleted_spec.rb
  spec/system/sync_provider_from_find/study_mode_changes_spec.rb
Labels: End of cycle

#2330 Include recruitment_cycle_year in the unique index on courses
  app/models/course.rb
  db/migrate/20200623104452_change_index_on_course_uniqueness.rb
  db/schema.rb
  docs/domain-model.png
  spec/models/course_spec.rb
Labels: End of cycle

#2332 pipeline to build a base docker image with gem node installed for reducing main CI build times
  .github/workflows/run-gems-node-modules-build.yml
  Dockerfile
  azure-pipelines.yml
  build-gems-node-modules-pipeline.yml
  docker-compose.azure.yml
Labels: DevOps

#2347 Sync 2021 courses when the feature flag is on
  app/models/course.rb
  app/services/sync_all_providers_from_find.rb
  app/services/sync_provider_from_find.rb
  spec/models/course_spec.rb
  spec/services/sync_provider_from_find_spec.rb
Labels: End of cycle

#2333 Add summer recruitment banner and feature flag to provider_interface
  app/services/feature_flag.rb
  app/views/provider_interface/application_choices/index.html.erb
  app/views/provider_interface/start_page/show.html.erb
Labels: ProVendor

#2349 Move pending DSA query into ProviderSetup service
  app/controllers/provider_interface/content_controller.rb
  app/controllers/provider_interface/provider_agreements_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/provider_interface/sessions_controller.rb
  app/controllers/provider_interface/start_page_controller.rb
  app/services/get_pending_data_sharing_agreements_for_provider_user.rb
  app/services/provider_setup.rb
  spec/services/get_pending_data_sharing_agreements_for_provider_user_spec.rb
  spec/services/provider_setup_spec.rb
Labels: ProVendor, Provider onboarding

#2346 Cancel running build and retrigger
  azure-pipelines.yml
  build-gems-node-modules-pipeline.yml
Labels: DevOps

#2366 use job attempt suffix for test artifacts
  azure-pipelines.yml
  rspec-job-template.yml
Labels: DevOps

#2364 Bug fix - candidates can submit incomplete 'other' qualifications
  app/components/candidate_interface/other_qualifications_review_component.html.erb
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/models/application_qualification.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/application_form/_review.html.erb
  config/locales/review_application.yml
  spec/components/candidate_interface/other_qualifications_review_component_spec.rb
  spec/models/application_qualification_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#2355 Add withdrawal feedback questionnaire
  app/controllers/candidate_interface/decisions_controller.rb
  app/forms/candidate_interface/withdrawal_feedback_form.rb
  app/models/candidate_interface/withdrawal_questionnaire.rb
  app/views/candidate_interface/decisions/feedback.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/forms/candidate_interface/withdrawal_feedback_form_spec.rb
  spec/system/candidate_interface/candidate_withdraws_spec.rb
Labels: Candidate

#2375 Update content suggesting choosing a course first
  app/views/candidate_interface/application_form/before_you_start.html.erb
Labels: Candidate

#2368 rename image name to apply-for-teacher-training
  Makefile
  azure-pipelines-release.yml
  azure-pipelines.yml
  docker-compose.yml
Labels: DevOps

#2373 Update degree subject form to use HESA data
  app/controllers/candidate_interface/degrees/subject_controller.rb
  app/frontend/packs/application.js
  app/frontend/packs/degree-subject-autocomplete.js
  app/lib/hesa/subject.rb
  app/models/candidate_interface/degree_subject_form.rb
  app/views/candidate_interface/degrees/subject/_form_fields.html.erb
  config/initializers/hesa_degree_subjects.rb
  spec/factories.rb
  spec/forms/candidate_interface/degree_subject_form_spec.rb
  spec/lib/hesa/subject_spec.rb
Labels: Candidate

#2374 Content no conditions
  app/components/provider_interface/conditions_component.rb
Labels: ProVendor

#2386 Correctly display interview preferences and training with disability
  app/components/interview_preferences_component.rb
  app/components/provider_interface/training_with_disability_component.rb
  spec/components/interview_preferences_component_spec.rb
  spec/components/provider_interface/training_with_disability_component_spec.rb
Labels: ProVendor

#2376 Remove extra h1 on authentication support fallback page
  app/views/support_interface/sessions/authentication_fallback.html.erb
Labels: Support

#2389 Update degree institution form to use HESA data
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/frontend/packs/application.js
  app/frontend/packs/degree-institution-autocomplete.js
  app/lib/hesa/institution.rb
  app/models/candidate_interface/degree_institution_form.rb
  app/views/candidate_interface/degrees/institution/_form_fields.html.erb
  config/initializers/hesa_degree_institutions.rb
  spec/forms/candidate_interface/degree_institution_form_spec.rb
  spec/lib/hesa/institution_spec.rb
Labels: Candidate

#2387 Candidate see the before you start page (pick a course) when applying again
  app/controllers/candidate_interface/application_form_controller.rb
  spec/system/candidate_interface/candidate_can_see_their_rejection_reasons_on_apply_again_spec.rb
  spec/system/candidate_interface/candidate_replaces_reference_after_applying_again_spec.rb
  spec/system/candidate_interface/candidate_with_unsuccessful_application_applies_again_spec.rb
Labels: Candidate

#2391 Only assign valid permissions for providers
  app/forms/provider_interface/provider_user_form.rb
  spec/forms/provider_interface/provider_user_form_spec.rb
Labels: ProVendor

#2393 Tweaks to updated start page content
  app/views/candidate_interface/start_page/show.html.erb
Labels: Core

#2394 Add right to work and study columns to application form
  db/migrate/20200630072856_add_right_to_work_or_study_columns_to_application_form.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#2395 Add international candidates feature flag
  app/services/feature_flag.rb
Labels: Candidate

#2388 Explicitly assign permissions from pairing
  app/controllers/provider_interface/organisations_controller.rb
  app/models/provider_interface/provider_relationship_permissions_pair.rb
  app/views/provider_interface/organisations/show.html.erb
  spec/models/provider_interface/provider_relationship_permissions_pair_spec.rb
Labels: ProVendor

#2398 remove pentest references
  README.md
  docs/deployment.md
  docs/new-environment.md
Labels: DevOps

#2372 [RFC] Simplify post-deployment checks
  docs/deployment.md
  docs/deployment_checklist.md
Labels: DevOps

#2363 Change the way we pass in offer conditions
  app/controllers/provider_interface/decisions_controller.rb
  app/views/provider_interface/decisions/confirm_offer.html.erb
  spec/requests/provider_interface/audit_trail_spec.rb
Labels: ProVendor

#2381 Replace course no longer available on Apply, but on UCAS
  app/components/candidate_interface/replacement_action_component.html.erb
  app/components/candidate_interface/replacement_action_component.rb
  app/controllers/candidate_interface/course_choices/replace_choices/decision_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/ucas_controller.rb
  app/models/application_form.rb
  app/views/candidate_interface/course_choices/replace_choices/ucas/with_course.html.erb
  spec/components/candidate_interface/new_course_choice_needed_banner_component_spec.rb
  spec/components/candidate_interface/replacement_action_component_spec.rb
  spec/models/application_form_spec.rb
  spec/system/candidate_interface/course_selection/candidate_can_replace_full_or_withdrawn_course_choices_spec.rb
Labels: Candidate

#2369 Set flash message when updating org permissions
  app/controllers/provider_interface/provider_relationship_permissions_controller.rb
  app/forms/provider_interface/provider_relationship_permissions_form.rb
  app/frontend/styles/_banner.scss
  app/views/provider_interface/_check_icon.html.erb
  app/views/provider_interface/organisations/_permissions_list.html.erb
  app/views/provider_interface/provider_relationship_permissions/_provider_permissions.html.erb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
  app/views/provider_interface/provider_relationship_permissions/setup.html.erb
  spec/system/provider_interface/manage_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
  spec/system/provider_interface/setup_provider_relationship_permissions_spec.rb
Labels: ProVendor

#2404 Give dev-provider and dev-support names
  lib/tasks/local_dev.rake
Labels: Core

#2300 Rename AccreditedBodyPermissions to RatifyingProviderPermissions
  app/controllers/provider_interface/provider_relationship_permissions_controller.rb
  app/forms/provider_interface/provider_relationship_permissions_form.rb
  app/models/provider.rb
  app/models/provider_interface/accredited_body_permissions.rb
  app/models/provider_interface/provider_relationship_permissions.rb
  app/models/provider_interface/provider_relationship_permissions_pair.rb
  app/models/provider_interface/training_provider_permissions.rb
  app/models/provider_relationship_permissions.rb
  app/models/provider_relationship_permissions_pair.rb
  app/models/ratifying_provider_permissions.rb
  app/models/training_provider_permissions.rb
  app/services/provider_authorisation.rb
  app/services/provider_setup.rb
  app/services/sync_provider_from_find.rb
  app/views/provider_interface/provider_relationship_permissions/confirm.html.erb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
  spec/factories.rb
  spec/forms/provider_interface/provider_relationship_permissions_form_spec.rb
  spec/models/provider_relationship_permissions_pair_spec.rb
  spec/models/provider_spec.rb
  spec/requests/provider_interface/provider_relationship_permissions_request_spec.rb
  spec/requests/provider_interface/see_organisations_pages_spec.rb
  spec/services/provider_authorisation_spec.rb
  spec/services/provider_setup_spec.rb
  spec/services/sync_provider_from_find_spec.rb
  spec/support/test_helpers/provider_relationship_permissions_helper.rb
  spec/system/provider_interface/manage_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
  spec/system/provider_interface/setup_provider_relationship_permissions_spec.rb
Labels: ProVendor
