Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2020-11, with the labels that each got.

#3300 authenticate with DockerHub
  azure/containers.json
  azure/pipelines/templates/deploy.yml
  azure/template.json
Labels: DevOps

#3278 Decoupled references - edit email address for failed request
  app/components/candidate_interface/decoupled_references_review_component.html.erb
  app/components/candidate_interface/decoupled_references_review_component.rb
  app/components/candidate_interface/reference_history_component.rb
  app/controllers/candidate_interface/decoupled_references/retry_request_controller.rb
  app/forms/candidate_interface/reference/retry_request_form.rb
  app/models/reference_history.rb
  app/views/candidate_interface/decoupled_references/retry_request/new.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/routes.rb
  spec/components/candidate_interface/decoupled_references_review_component_spec.rb
  spec/components/candidate_interface/reference_history_component_spec.rb
  spec/models/reference_history_spec.rb
  spec/system/candidate_interface/decoupled_references/candidate_requests_a_reference_spec.rb
Labels: Candidate

#3292 Invariant check for unauthorised application edits
  app/workers/detect_invariants.rb
  spec/workers/detect_invariants_spec.rb
Labels: Candidate

#3290 Remove code to ordinalise the application reference
  app/models/application_reference.rb
  spec/models/application_reference_spec.rb
Labels: Candidate

#3305 Don’t send MissingProvider exceptions to Sentry
  app/controllers/provider_interface/provider_interface_controller.rb
  spec/requests/provider_interface/account_creation_in_progress_spec.rb
Labels: ProVendor

#3286 Regenerate application choice state diagram
  docs/states.png
Labels: Core

#3303 Use govuk_markdown gem to render markdown
  Gemfile
  Gemfile.lock
  app/controllers/api_docs/pages_controller.rb
  app/helpers/content_helper.rb
  app/helpers/markdown_helper.rb
  app/lib/govuk/markdown_renderer.rb
  app/views/api_docs/pages/rendered_markdown_template.html.erb
  app/views/api_docs/reference/_operation.html.erb
  app/views/api_docs/reference/_properties_list.html.erb
  app/views/api_docs/reference/_schema.html.erb
  app/views/api_docs/reference/reference.html.erb
  app/views/candidate_interface/content/rendered_markdown_template.html.erb
  app/views/provider_interface/content/rendered_markdown_template.html.erb
  spec/lib/govuk/markdown_renderer_spec.rb
Labels: Core

#3307 Set correct subject in GCSE::Science::GradeController
  app/controllers/candidate_interface/gcse/science/grade_controller.rb
Labels: Candidate

#3283 Additions to the performance dashboard
  app/models/performance_statistics.rb
  app/views/integrations/performance_dashboard/dashboard.html.erb
  config/locales/application_states.yml
  spec/models/performance_statistics_spec.rb
Labels: Support

#3306 Add action_taken column to UCAS matches table
  db/migrate/20201102152042_add_action_taken_to_ucas_matches.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#3299 Add diversity information to org-org permissions diagram
  app/presenters/support_interface/provider_relationships_diagram.rb
  spec/system/support_interface/viewing_provider_permissions_spec.rb
Labels: Support

#3309 Remove ‘Sign in’ link in signed out candidate and support headers
  app/helpers/navigation_items.rb
  spec/system/candidate_interface/candidate_account_spec.rb
  spec/system/candidate_interface/candidate_signs_in_without_account_spec.rb
  spec/system/candidate_interface/candidate_tries_to_reuse_magic_link_spec.rb
Labels: Candidate, Support

#3312 Redirect back to reference review page if reference not found
  app/controllers/candidate_interface/references/base_controller.rb
  app/controllers/candidate_interface/references/candidate_name_controller.rb
  app/controllers/candidate_interface/references/email_address_controller.rb
  app/controllers/candidate_interface/references/name_controller.rb
  app/controllers/candidate_interface/references/relationship_controller.rb
  app/controllers/candidate_interface/references/review_controller.rb
  app/controllers/candidate_interface/references/type_controller.rb
  spec/system/candidate_interface/references/candidate_adds_a_new_reference_spec.rb
Labels: Candidate

#3302 Update brakeman config to include UnscopedFind check
  app/controllers/candidate_interface/other_qualifications/type_controller.rb
  brakeman.yml
  config/brakeman.ignore
  docs/brakeman.md
Labels: Core

#3311 Add test to check University of Boltons courses behaviour of signed in candidates arriving from Find
  spec/system/candidate_interface/candidate_arrives_from_find_with_a_course_only_open_on_apply_spec.rb
Labels: Candidate

#3316 Add a service to handle adding a course after application submission
  app/services/support_interface/add_course_choice_after_submission.rb
  spec/services/support_interface/add_course_choice_after_submission_spec.rb
Labels: Core

#3318 Add automatic attribution to audited changes in console
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/lib/hosting_environment.rb
  config/initializers/console.rb
Labels: Core

#3322 Refactor work history and volunteering review components and localisation strings
  app/components/candidate_interface/volunteering_review_component.html.erb
  app/components/candidate_interface/volunteering_review_component.rb
  app/components/candidate_interface/work_history_review_component.html.erb
  app/components/candidate_interface/work_history_review_component.rb
  app/components/summary_card_header_component.html.erb
  app/components/summary_card_header_component.rb
  app/views/candidate_interface/volunteering/destroy/confirm_destroy.html.erb
  app/views/candidate_interface/work_history/break/confirm_destroy.html.erb
  app/views/candidate_interface/work_history/breaks/edit.html.erb
  app/views/candidate_interface/work_history/destroy/confirm_destroy.html.erb
  app/views/candidate_interface/work_history/edit/_form.html.erb
  app/views/candidate_interface/work_history/edit/new.html.erb
  app/views/candidate_interface/work_history/length/show.html.erb
  app/views/candidate_interface/work_history/review/show.html.erb
  config/locales/application_form.yml
  spec/components/candidate_interface/volunteering_review_component_spec.rb
  spec/components/candidate_interface/work_history_review_component_spec.rb
  spec/components/summary_card_header_component_spec.rb
  spec/system/candidate_interface/candidate_edits_or_deletes_volunteering_section_after_competing_the_section_spec.rb
  spec/system/candidate_interface/candidate_edits_work_history_after_completing_the_section_spec.rb
  spec/system/candidate_interface/candidate_entering_volunteering_and_school_experience_spec.rb
  spec/system/candidate_interface/candidate_entering_work_history_spec.rb
Labels: Candidate, Content

#3294 Add deferred offer reminder email
  app/controllers/support_interface/tasks_controller.rb
  app/mailers/candidate_mailer.rb
  app/queries/get_deferred_application_choices_for_current_cycle.rb
  app/services/send_deferred_offer_reminder_email_to_candidate.rb
  app/views/candidate_mailer/deferred_offer_reminder.text.erb
  app/views/support_interface/tasks/index.html.erb
  app/workers/send_deferred_offer_reminder_email_to_candidates_worker.rb
  config/locales/application_states.yml
  config/locales/candidate_mailer.yml
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/workers/send_deferred_offer_reminder_email_to_candidates_worker_spec.rb
Labels: Core

#3295 Add filtering to UCAS matches page
  app/components/support_interface/ucas_matches_table_component.html.erb
  app/components/support_interface/ucas_matches_table_component.rb
  app/controllers/support_interface/ucas_matches_controller.rb
  app/models/support_interface/ucas_matches_filter.rb
  app/views/support_interface/candidates/_candidates_navigation.html.erb
  app/views/support_interface/ucas_matches/index.html.erb
  app/views/support_interface/ucas_matches/show.html.erb
  spec/components/support_interface/ucas_matches_table_component_spec.rb
  spec/system/support_interface/ucas_matches_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: ProVendor, Support

#3289 Update copy for deferred offer notification email
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/changed_offer.text.erb
  app/views/candidate_mailer/deferred_offer.text.erb
  config/locales/candidate_mailer.yml
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
Labels: Candidate

#3315 Add autocomplete for Other UK qualifications
  app/frontend/packs/application-candidate.js
  app/frontend/packs/other-uk-qualifications-autocomplete.js
  app/views/candidate_interface/other_qualifications/type/_shared_form.html.erb
  config/initializers/qualifications/other_uk.rb
Labels: Candidate

#3324 Add nil check for DoB in work history export
  app/services/support_interface/unexplained_breaks_in_work_history_export.rb
Labels: Support

#3308 Add permissions data for active provider users export
  app/models/data_export.rb
  app/services/support_interface/active_provider_user_permissions_export.rb
  spec/factories.rb
  spec/services/support_interface/active_provider_user_permissions_export_spec.rb
Labels: ProVendor

#3334 Update ApplicationQualification table
  db/migrate/20201104150602_remove_subject_area_from_application_qualifications.rb
  db/migrate/20201104151036_add_grades_to_application_qualifications.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3332 If the candidate has no references redirect from the references review pages to the start page
  app/controllers/candidate_interface/references/review_controller.rb
  spec/system/candidate_interface/references/review_references_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#3335 Update content when asking for candidate’s name in references flow
  app/views/candidate_interface/references/candidate_name/new.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  spec/system/candidate_interface/references/candidate_requests_a_reference_spec.rb
Labels: Candidate, Content

#3336 Remove hypenation from full time and part time
  app/components/candidate_interface/work_history_review_component.rb
  app/components/work_history_item_component.rb
  app/models/application_work_experience.rb
  app/services/reason_course_not_available.rb
  config/locales/application_form.yml
  spec/components/summary_list_component_spec.rb
  spec/components/work_history_component_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_edits_work_history_after_completing_the_section_spec.rb
  spec/system/candidate_interface/candidate_entering_work_history_breaks_spec.rb
  spec/system/candidate_interface/candidate_entering_work_history_spec.rb
  spec/system/candidate_interface/candidate_submits_application_with_full_course_study_mode_spec.rb
  spec/system/provider_interface/provider_changes_an_offer_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: Candidate

#3328 Stop syncing providers and courses for the 2020 recruitment cycle
  app/services/find_sync/sync_all_providers_from_find.rb
  spec/components/support_interface/applications_table_component_spec.rb
  spec/services/candidate_interface/hesa_code_backfill_spec.rb
  spec/support/dates.rb
  spec/support/test_helpers/find_api_helper.rb
  spec/system/candidate_interface/references/candidate_views_reference_history_spec.rb
  spec/system/find_sync/syncing_providers_spec.rb
  spec/system/provider_interface/provider_applications_filter_spec.rb
  spec/system/support_interface/cycle_switching_spec.rb
  spec/system/support_interface/provider_sync_courses_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: Core

#3338 Refactor all authorisation calls to populate errors array
  app/controllers/provider_interface/provider_users_controller.rb
  app/services/make_decisions_authorisation.rb
  app/services/provider_authorisation.rb
  app/services/provider_interface/save_provider_user_service.rb
Labels: ProVendor

#3341 Various fixes to pages in references flow
  app/components/candidate_interface/references_review_component.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/references/candidate_name/new.html.erb
  app/views/candidate_interface/references/email_address/_shared_form.html.erb
  app/views/candidate_interface/references/email_address/edit.html.erb
  app/views/candidate_interface/references/email_address/new.html.erb
  app/views/candidate_interface/references/name/_shared_form.html.erb
  app/views/candidate_interface/references/name/edit.html.erb
  app/views/candidate_interface/references/name/new.html.erb
  app/views/candidate_interface/references/relationship/_shared_form.html.erb
  app/views/candidate_interface/references/relationship/edit.html.erb
  app/views/candidate_interface/references/relationship/new.html.erb
  app/views/candidate_interface/references/reminder/new.html.erb
  app/views/candidate_interface/references/request/new.html.erb
  app/views/candidate_interface/references/request/start.html.erb
  app/views/candidate_interface/references/retry_request/new.html.erb
  app/views/candidate_interface/references/review/confirm_cancel.html.erb
  app/views/candidate_interface/references/review/confirm_destroy_referee.html.erb
  app/views/candidate_interface/references/review/confirm_destroy_reference.html.erb
  app/views/candidate_interface/references/review/confirm_destroy_reference_request.html.erb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/references/review/unsubmitted.html.erb
  app/views/candidate_interface/references/type/_shared_form.html.erb
  app/views/candidate_interface/references/type/edit.html.erb
  app/views/candidate_interface/references/type/new.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
Labels: Candidate

#3331 Specify node and yarn versions
  .nvmrc
  README.md
  app.json
  package.json
Labels: Core

#3346 Various fixes to pages in references flow (part 2)
  app/controllers/candidate_interface/references/request_controller.rb
  app/views/candidate_interface/references/reminder/new.html.erb
  app/views/candidate_interface/references/request/new.html.erb
  app/views/candidate_interface/references/request/start.html.erb
  app/views/candidate_interface/references/retry_request/new.html.erb
  app/views/candidate_interface/references/review/confirm_cancel.html.erb
  app/views/candidate_interface/references/review/confirm_destroy_referee.html.erb
  app/views/candidate_interface/references/review/confirm_destroy_reference.html.erb
  app/views/candidate_interface/references/review/confirm_destroy_reference_request.html.erb
  app/views/candidate_interface/references/review/unsubmitted.html.erb
  app/views/candidate_interface/references/type/_shared_form.html.erb
  app/views/candidate_interface/references/type/edit.html.erb
  app/views/candidate_interface/references/type/new.html.erb
  config/locales/application_form.yml
  config/routes.rb
Labels: Candidate

#3351 Fix error in error tracking
  app/controllers/candidate_interface/references/relationship_controller.rb
Labels: Candidate

#3353 Remove request feedback from support interface and survey emails
  app/controllers/support_interface/survey_emails_controller.rb
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/survey_chaser_email.text.erb
  app/views/candidate_mailer/survey_email.text.erb
  app/views/support_interface/application_forms/_request_feedback.html.erb
  app/views/support_interface/application_forms/show.html.erb
  app/views/support_interface/survey_emails/show.html.erb
  config/locales/candidate_mailer.yml
  config/locales/survey_emails.yml
  config/routes.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/system/support_interface/docs_spec.rb
  spec/system/support_interface/send_survey_email_to_candidate_spec.rb
Labels: Candidate

#3339 Update to App Form Presenter to flow back to add new
  app/controllers/candidate_interface/volunteering/destroy_controller.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  config/locales/application_form.yml
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/system/candidate_interface/candidate_edits_or_deletes_volunteering_section_after_competing_the_section_spec.rb
Labels: Candidate

#3355 Update PIM doc
  docs/pim-guide.md
Labels: Core

#3354 Use govuk_submit helper from form builder
  app/views/candidate_interface/application_choices/confirm_destroy.html.erb
  app/views/candidate_interface/decisions/decline.html.erb
  app/views/candidate_interface/decisions/feedback.html.erb
  app/views/candidate_interface/degrees/destroy/confirm_destroy.html.erb
  app/views/candidate_interface/gcse/english/grade/edit.html.erb
  app/views/candidate_interface/gcse/grade/edit.html.erb
  app/views/candidate_interface/gcse/institution_country/edit.html.erb
  app/views/candidate_interface/gcse/maths/grade/edit.html.erb
  app/views/candidate_interface/gcse/naric_reference/edit.html.erb
  app/views/candidate_interface/gcse/science/grade/edit.html.erb
  app/views/candidate_interface/gcse/type/edit.html.erb
  app/views/candidate_interface/gcse/year/edit.html.erb
  app/views/candidate_interface/other_qualifications/destroy/confirm_destroy.html.erb
  app/views/candidate_interface/sign_in/new.html.erb
  app/views/candidate_interface/volunteering/destroy/confirm_destroy.html.erb
  app/views/candidate_interface/work_history/break/confirm_destroy.html.erb
  app/views/candidate_interface/work_history/destroy/confirm_destroy.html.erb
  app/views/provider_interface/conditions/confirm_update.html.erb
  app/views/provider_interface/provider_users/confirm_remove.html.erb
  app/views/provider_interface/provider_users/show.html.erb
  app/views/provider_interface/reconfirm_deferred_offers/check.html.erb
  app/views/provider_interface/reconfirm_deferred_offers/conditions.html.erb
  app/views/provider_interface/sessions/authentication_fallback.html.erb
  app/views/support_interface/sessions/authentication_fallback.html.erb
  app/views/support_interface/support_users/confirm_destroy.html.erb
  app/views/support_interface/support_users/confirm_restore.html.erb
  app/views/support_interface/tasks/confirm_cancel_applications_at_end_of_cycle.html.erb
  app/views/support_interface/tasks/confirm_delete_test_applications.html.erb
  app/views/support_interface/ucas_matches/show.html.erb
Labels: Core

#3273 Explain lack of safeguarding access to provider users
  app/components/provider_interface/permissions_debug_comment_component.html.erb
  app/components/provider_interface/permissions_debug_comment_component.rb
  app/components/provider_interface/safeguarding_declaration_component.html.erb
  app/components/provider_interface/safeguarding_declaration_component.rb
  app/lib/create_example_provider_users_with_permissions.rb
  app/services/provider_authorisation.rb
  app/services/provider_authorisation_analysis.rb
  app/views/support_interface/docs/setup_local_dev_data_again.html.erb
  config/locales/safeguarding.yml
  lib/tasks/local_dev.rake
  spec/components/previews/provider_interface/safeguarding_declaration_component_preview.rb
  spec/components/provider_interface/safeguarding_declaration_component_spec.rb
  spec/services/provider_authorisation_analysis_spec.rb
  spec/system/provider_interface/manage_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: ProVendor

#3356 Add sandbox feature component
  app/components/sandbox_feature_component.html.erb
  app/components/sandbox_feature_component.rb
  app/frontend/styles/_status-box.scss
  app/views/candidate_interface/course_choices/course_selection/new.html.erb
  app/views/candidate_interface/course_choices/provider_selection/new.html.erb
  app/views/candidate_interface/references/email_address/_shared_form.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  spec/components/sandbox_feature_component_spec.rb
Labels: Core

#3357 Trigger smoke tests using workflow_dispatch event
  azure/pipelines/templates/deploy.yml
Labels: Core, DevOps

#3368 Add emojis to all Slack messages
  app/lib/state_change_notifier.rb
  spec/lib/state_change_notifier_spec.rb
Labels: Core

#3365 Don’t show ‘No results found’ message when suggesting values
  app/frontend/packs/helpers.js
Labels: Candidate

#3221 Record that initial emails regarding dual application were sent
  app/controllers/support_interface/ucas_matches_controller.rb
  app/models/ucas_match.rb
  app/views/support_interface/ucas_matches/show.html.erb
  config/routes.rb
  spec/models/ucas_match_spec.rb
  spec/system/support_interface/ucas_matches_spec.rb
Labels: ProVendor

#3366 Merge Slack message for application submission
  app/lib/state_change_notifier.rb
  app/services/send_application_to_provider.rb
  app/services/submit_application.rb
  spec/lib/state_change_notifier_spec.rb
  spec/services/send_application_to_provider_spec.rb
  spec/system/candidate_interface/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/references/submitting_an_application_spec.rb
Labels: Core

#3367 Remove reference related Slack messages
  app/services/cancel_referee.rb
  app/services/candidate_interface/send_reference_reminder.rb
  app/services/submit_reference.rb
  spec/services/cancel_referee_spec.rb
  spec/services/candidate_interface/send_reference_reminder_spec.rb
Labels: Candidate

#3343 Add export for provider access controls
  app/models/data_export.rb
  app/services/support_interface/provider_access_controls_export.rb
  app/services/support_interface/provider_access_controls_stats.rb
  spec/factories.rb
  spec/services/support_interface/provider_access_controls_export_spec.rb
  spec/services/support_interface/provider_access_controls_stats_spec.rb
Labels: Support

#3344 Add a start_date attribute to the API Course object
  app/presenters/vendor_api/single_application_presenter.rb
  app/views/api_docs/pages/release_notes.md
  config/vendor-api-v1.yml
  spec/requests/vendor_api/post_make_an_offer_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: ProVendor

#3376 Add reject_by_default_feedback_sent_at to ApplicationChoice
  db/migrate/20201110114210_add_reject_by_default_feedback_sent_at_to_application_choices.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#3345 Add the ApplicationFeedback table
  db/migrate/20201105145325_add_application_feedback_table.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3378 Add feedback prompts - Non-JS solution
  app/components/candidate_interface/application_feedback_component.html.erb
  app/components/candidate_interface/application_feedback_component.rb
  app/controllers/candidate_interface/application_feedback_controller.rb
  app/forms/candidate_interface/application_feedback_form.rb
  app/frontend/styles/_feedback.scss
  app/frontend/styles/application.scss
  app/models/application_feedback.rb
  app/models/application_form.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/application_feedback/edit.html.erb
  app/views/candidate_interface/application_feedback/thank_you.html.erb
  app/views/candidate_interface/references/base/start.html.erb
  app/views/candidate_interface/references/candidate_name/new.html.erb
  app/views/candidate_interface/references/email_address/edit.html.erb
  app/views/candidate_interface/references/email_address/new.html.erb
  app/views/candidate_interface/references/name/edit.html.erb
  app/views/candidate_interface/references/name/new.html.erb
  app/views/candidate_interface/references/relationship/edit.html.erb
  app/views/candidate_interface/references/relationship/new.html.erb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/references/review/unsubmitted.html.erb
  app/views/candidate_interface/references/type/edit.html.erb
  app/views/candidate_interface/references/type/new.html.erb
  config/locales/application_feedback_component.yml
  config/locales/application_form.yml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20201110185731_add_id_in_params_to_application_feedback_table.rb
  db/schema.rb
  spec/components/candidate_interface/application_feedback_component_spec.rb
  spec/factories.rb
  spec/forms/candidate_interface/application_feedback_form_spec.rb
  spec/system/candidate_interface/candidate_provides_feedback_throughout_the_application_process_spec.rb
Labels: Candidate

#3382 Remove International Address Feature flag and refactor specs
  app/components/candidate_interface/contact_details_review_component.rb
  app/controllers/candidate_interface/contact_details/address_type_controller.rb
  app/controllers/candidate_interface/contact_details/base_controller.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/feature_flag.rb
  spec/components/candidate_interface/contact_details_review_component_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_contact_details_spec.rb
  spec/system/candidate_interface/international/candidate_entering_contact_details_without_international_addresses_spec.rb
  spec/system/candidate_interface/international/international_candidate_submitting_application_spec.rb
Labels: Candidate

#3387 Revise flow for degree grades
  app/components/candidate_interface/degrees_review_component.rb
  app/controllers/candidate_interface/degrees/base_controller.rb
  app/controllers/candidate_interface/degrees/completion_status_controller.rb
  app/controllers/candidate_interface/degrees/grade_controller.rb
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/controllers/candidate_interface/degrees/naric_statement_controller.rb
  app/forms/candidate_interface/degree_completion_status_form.rb
  app/forms/candidate_interface/degree_grade_form.rb
  app/models/application_qualification.rb
  app/views/candidate_interface/degrees/completion_status/_form_fields.html.erb
  app/views/candidate_interface/degrees/completion_status/edit.html.erb
  app/views/candidate_interface/degrees/completion_status/new.html.erb
  app/views/candidate_interface/degrees/grade/_form_fields.html.erb
  app/views/candidate_interface/degrees/grade/edit.html.erb
  app/views/candidate_interface/degrees/grade/new.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/routes.rb
  spec/components/candidate_interface/degrees_review_component_spec.rb
  spec/forms/candidate_interface/degree_completion_status_form_spec.rb
  spec/forms/candidate_interface/degree_grade_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_degree_with_predicted_grade_spec.rb
  spec/system/candidate_interface/candidate_entering_degrees_spec.rb
  spec/system/candidate_interface/international/candidate_entering_international_degrees_spec.rb
Labels: Candidate

#3372 Only allow sign-ups from education.gov.uk emails addresses on qa etc.
  app/controllers/candidate_interface/sign_up_controller.rb
  app/forms/candidate_interface/sign_up_form.rb
  app/lib/hosting_environment.rb
  app/views/candidate_interface/sign_up/external_sign_up_forbidden.html.erb
  config/locales/authentication.yml
  config/locales/en.yml
  config/routes.rb
  spec/forms/candidate_interface/sign_up_form_spec.rb
  spec/lib/hosting_environment_spec.rb
  spec/system/candidate_interface/candidate_signs_up_to_test_environment_without_dfe_email_address_spec.rb
Labels: Candidate

#3041 Stop candidates being able to create incomplete other qualifications
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/controllers/candidate_interface/other_qualifications/destroy_controller.rb
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/controllers/candidate_interface/other_qualifications/type_controller.rb
  app/forms/candidate_interface/other_qualification_form.rb
  app/forms/candidate_interface/other_qualification_type_form.rb
  app/forms/candidate_interface/other_qualification_wizard.rb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  app/views/candidate_interface/other_qualifications/details/edit.html.erb
  app/views/candidate_interface/other_qualifications/details/new.html.erb
  app/views/candidate_interface/other_qualifications/type/edit.html.erb
  app/views/candidate_interface/other_qualifications/type/new.html.erb
  config/locales/application_form.yml
  config/routes.rb
  db/schema.rb
  spec/forms/candidate_interface/other_qualification_form_spec.rb
  spec/forms/candidate_interface/other_qualification_type_form_spec.rb
  spec/forms/candidate_interface/other_qualification_wizard_spec.rb
  spec/system/candidate_interface/candidate_entering_other_qualification_spec.rb
  spec/system/candidate_interface/international/international_candidate_enters_their_other_qualification_spec.rb
Labels: Candidate

#3371 Remove remaining instances of styled content container
  app/components/state_event_explanation_component.html.erb
  app/components/state_explanation_component.html.erb
  app/components/when_emails_are_sent_component.html.erb
  app/frontend/styles/_code.scss
  app/frontend/styles/_list.scss
  app/frontend/styles/_styled-content.scss
  app/frontend/styles/application.scss
  app/views/provider_interface/provider_agreements/data_sharing_agreement.html.erb
  app/views/support_interface/data_exports/new.html.erb
  app/views/support_interface/tasks/confirm_cancel_applications_at_end_of_cycle.html.erb
  app/views/support_interface/tasks/confirm_delete_test_applications.html.erb
  app/views/support_interface/tasks/index.html.erb
Labels: Core

#3396 Update diversity info and permission guidance text
  app/components/provider_interface/diversity_information_component.rb
  config/locales/provider_relationship_permissions.yml
  spec/components/provider_interface/diversity_information_component_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: ProVendor

#3400 Filter UCAS matches by Action needed
  app/models/support_interface/ucas_matches_filter.rb
  spec/system/support_interface/ucas_matches_spec.rb
Labels: ProVendor

#3391 Add details of offered course and original course to export
  app/services/support_interface/offer_conditions_export.rb
  spec/services/support_interface/offer_conditions_export_spec.rb
Labels: ProVendor

#3390 Change type of rejection reasons column
  db/migrate/20201111112518_change_application_choices_structured_rejection_reasons_column_type.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#3398 Add candidate_id to submitted app choices export
  app/services/support_interface/application_choices_export.rb
  spec/services/support_interface/application_choices_export_spec.rb
Labels: Core

#3399 Add Application status to Equality & Diversity data export
  app/services/support_interface/equality_and_diversity_export.rb
  spec/services/support_interface/equality_and_diversity_export_spec.rb
Labels: Core

#3379 Fix test data generation for oracle
  app/lib/test_applications.rb
  app/services/end_of_cycle_timetable.rb
  spec/lib/test_applications_spec.rb
Labels: ProVendor

#3394 Make sure autoselect is disabled on autocompletes using showAllValues option
  app/frontend/packs/api-token-autocomplete.js
  app/frontend/packs/country-autocomplete.js
  app/frontend/packs/courses-autocomplete.js
  app/frontend/packs/gcse-grade-autocomplete.js
  app/frontend/packs/ielts-band-score-autocomplete.js
  app/frontend/packs/nationality-autocomplete.js
  app/frontend/packs/providers-autocomplete.js
Labels: Candidate

#3403 Update Application Feedback prompts to use the updated design
  app/components/candidate_interface/application_feedback_component.html.erb
  app/components/candidate_interface/application_feedback_component.rb
  app/controllers/candidate_interface/application_feedback_controller.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/degrees/base_controller.rb
  app/controllers/candidate_interface/degrees/destroy_controller.rb
  app/controllers/candidate_interface/gcse/details_controller.rb
  app/controllers/candidate_interface/gcse/english/grade_controller.rb
  app/controllers/candidate_interface/gcse/maths/grade_controller.rb
  app/controllers/candidate_interface/gcse/review_controller.rb
  app/controllers/candidate_interface/gcse/science/grade_controller.rb
  app/controllers/candidate_interface/other_qualifications/base_controller.rb
  app/controllers/candidate_interface/other_qualifications/destroy_controller.rb
  app/controllers/candidate_interface/personal_statement/becoming_a_teacher_controller.rb
  app/controllers/candidate_interface/personal_statement/subject_knowledge_controller.rb
  app/controllers/candidate_interface/references/base_controller.rb
  app/forms/candidate_interface/application_feedback_form.rb
  app/frontend/styles/_feedback.scss
  app/models/application_feedback.rb
  app/views/candidate_interface/application_feedback/new.html.erb
  app/views/candidate_interface/application_feedback/thank_you.html.erb
  app/views/candidate_interface/references/base/start.html.erb
  app/views/candidate_interface/references/candidate_name/new.html.erb
  app/views/candidate_interface/references/email_address/edit.html.erb
  app/views/candidate_interface/references/email_address/new.html.erb
  app/views/candidate_interface/references/name/edit.html.erb
  app/views/candidate_interface/references/name/new.html.erb
  app/views/candidate_interface/references/relationship/edit.html.erb
  app/views/candidate_interface/references/relationship/new.html.erb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/references/review/unsubmitted.html.erb
  app/views/candidate_interface/references/type/edit.html.erb
  app/views/candidate_interface/references/type/new.html.erb
  app/views/layouts/base.html.erb
  config/locales/application_feedback_component.yml
  config/locales/application_form.yml
  config/routes.rb
  db/migrate/20201113114518_remove_unused_application_feedback_columns.rb
  db/schema.rb
  docs/domain-model.png
  spec/components/candidate_interface/application_feedback_component_spec.rb
  spec/factories.rb
  spec/forms/candidate_interface/application_feedback_form_spec.rb
  spec/system/candidate_interface/candidate_provides_feedback_throughout_the_application_process_spec.rb
  spec/system/candidate_interface/candidate_provides_feedback_while_completing_their_application_spec.rb
Labels: Candidate

#3369 Move orgs and users to the "Your account" page
  app/controllers/provider_interface/profile_controller.rb
  app/helpers/navigation_items.rb
  app/views/provider_interface/account/show.html.erb
  app/views/provider_interface/organisations/index.html.erb
  app/views/provider_interface/organisations/show.html.erb
  app/views/provider_interface/profile/show.html.erb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/success.html.erb
  app/views/provider_interface/provider_users/index.html.erb
  app/views/provider_interface/provider_users/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/models/navigation_items_spec.rb
  spec/system/provider_interface/account_page_spec.rb
  spec/system/provider_interface/manage_provider_user_permissions_spec.rb
  spec/system/provider_interface/manage_provider_user_providers_spec.rb
  spec/system/provider_interface/provider_invites_user_with_new_wizard_spec.rb
  spec/system/provider_interface/providers_can_view_managed_users_spec.rb
  spec/system/provider_interface/removing_provider_user_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
  spec/system/provider_interface/setup_provider_relationship_permissions_spec.rb
Labels: ProVendor

#3409 Amend HESAITTData disability field documentation
  app/views/api_docs/pages/release_notes.md
  config/vendor-api-v1.yml
Labels: ProVendor

#3408 Add data export for feedback provided by candidates while completing the application form
  app/models/application_feedback.rb
  app/models/data_export.rb
  app/services/support_interface/candidate_application_feedback_export.rb
  app/views/candidate_interface/application_feedback/new.html.erb
  spec/services/support_interface/candidate_application_feedback_export_spec.rb
Labels: Support

#3397 Degree Flow Refactorings
  app/controllers/candidate_interface/degrees/completion_status_controller.rb
  app/controllers/candidate_interface/degrees/grade_controller.rb
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/controllers/candidate_interface/degrees/naric_statement_controller.rb
  app/controllers/candidate_interface/degrees/subject_controller.rb
  app/controllers/candidate_interface/degrees/type_controller.rb
  app/controllers/candidate_interface/degrees/year_controller.rb
  app/forms/candidate_interface/degree_completion_status_form.rb
  app/forms/candidate_interface/degree_grade_form.rb
  app/forms/candidate_interface/degree_institution_form.rb
  app/forms/candidate_interface/degree_naric_statement_form.rb
  app/forms/candidate_interface/degree_subject_form.rb
  app/forms/candidate_interface/degree_type_form.rb
  app/forms/candidate_interface/degree_year_form.rb
  spec/forms/candidate_interface/degree_completion_status_form_spec.rb
  spec/forms/candidate_interface/degree_grade_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_becoming_a_teacher_spec.rb
  spec/system/candidate_interface/candidate_deletes_and_adds_other_qualifications_after_completing_the_section_spec.rb
  spec/system/candidate_interface/candidate_edits_course_choices_spec.rb
  spec/system/candidate_interface/candidate_edits_or_deletes_volunteering_section_after_competing_the_section_spec.rb
  spec/system/candidate_interface/candidate_edits_work_history_after_completing_the_section_spec.rb
  spec/system/candidate_interface/candidate_entering_degrees_spec.rb
  spec/system/candidate_interface/candidate_entering_disability_info_spec.rb
  spec/system/candidate_interface/candidate_entering_equality_and_diversity_information_spec.rb
  spec/system/candidate_interface/candidate_entering_gcse_spec.rb
  spec/system/candidate_interface/candidate_entering_interview_preferences_spec.rb
  spec/system/candidate_interface/candidate_entering_other_qualification_spec.rb
  spec/system/candidate_interface/candidate_entering_personal_details_spec.rb
  spec/system/candidate_interface/candidate_entering_subject_knowledge_spec.rb
  spec/system/candidate_interface/candidate_entering_suitability_to_work_with_children_spec.rb
  spec/system/candidate_interface/candidate_entering_volunteering_and_school_experience_spec.rb
  spec/system/candidate_interface/candidate_entering_work_history_breaks_spec.rb
  spec/system/candidate_interface/candidate_entering_work_history_not_worked_spec.rb
  spec/system/candidate_interface/candidate_entering_work_history_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/add_other_qualification_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/change_qualification_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/your_ielts_results_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/your_toefl_result_spec.rb
  spec/system/candidate_interface/international/candidate_entering_international_degrees_spec.rb
  spec/system/candidate_interface/international/international_candidate_enters_their_other_qualification_spec.rb
  spec/system/candidate_interface/international/international_candidate_enters_their_personal_details_spec.rb
  spec/system/candidate_interface/references/review_references_spec.rb
Labels: Candidate

#3412 Slack: consolidate offer-accepted message, comma off thousands
  app/lib/state_change_notifier.rb
  app/lib/test_applications.rb
  app/services/accept_offer.rb
  app/workers/generate_test_applications.rb
  spec/lib/state_change_notifier_spec.rb
  spec/system/candidate_interface/candidate_accepts_offer_spec.rb
Labels: Core

#3407 Send slack notifications with a number of matches which need action
  app/services/ucas_matching/process_matching_data.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: ProVendor

#3411 Update export to include more detailed information about org permissions
  app/services/support_interface/provider_access_controls_export.rb
  app/services/support_interface/provider_access_controls_stats.rb
  spec/services/support_interface/provider_access_controls_export_spec.rb
  spec/services/support_interface/provider_access_controls_stats_spec.rb
Labels: ProVendor

#3389 Cancel references for cancelled test applications
  app/lib/test_applications.rb
  spec/workers/generate_test_applications_spec.rb
Labels: Core

#3349 Allow user to enter multiple Science GCSEs
  app/components/candidate_interface/gcse_grade_guidance_component.html.erb
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/controllers/candidate_interface/gcse/science/grade_controller.rb
  app/forms/candidate_interface/science_gcse_grade_form.rb
  app/models/application_form.rb
  app/models/application_qualification.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/gcse/science/grade/awards_edit.html.erb
  app/views/candidate_interface/gcse/science/grade/edit.html.erb
  app/views/referee_interface/reference/safeguarding.html.erb
  config/locales/application_form.yml
  config/locales/gcse_details.yml
  spec/components/candidate_interface/gcse_grade_guidance_component_spec.rb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/forms/candidate_interface/science_gcse_grade_form_spec.rb
  spec/system/candidate_interface/candidate_entering_gcse_science_award_spec.rb
  spec/system/candidate_interface/candidate_entering_gcse_science_spec.rb
Labels: Candidate

#3430 Fix backlinks in the accept, decline and withdraw offer pages
  app/views/candidate_interface/decisions/accept.html.erb
  app/views/candidate_interface/decisions/decline.html.erb
  app/views/candidate_interface/decisions/withdraw.html.erb
Labels: Bug bash 🐞🔨, Candidate

#3406 Add provider contact details to UCAS match
  app/components/support_interface/ucas_match_table_component.html.erb
  app/components/support_interface/ucas_match_table_component.rb
  spec/components/support_interface/ucas_match_table_component_spec.rb
Labels: ProVendor

#3435 Remove ‘dumb’ quotes
  app/components/interview_preferences_component.html.erb
  app/components/provider_interface/safeguarding_declaration_component.html.erb
  app/components/volunteering_history_component.html.erb
  app/services/ucas_matching/process_matching_data.rb
  app/views/candidate_interface/submitted_application_form/start_apply_again.html.erb
  app/views/provider_interface/applications_exports/new.html.erb
  app/views/provider_interface/provider_agreements/success.html.erb
  app/views/provider_interface/provider_users_invitations/check.html.erb
  config/vendor-api-v1.yml
  spec/components/candidate_interface/english_foreign_language/no_efl_qualification_review_component_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_with_missing_qualification_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_spec.rb
  spec/system/candidate_interface/entering_details/declare_no_qualification_spec.rb
  spec/system/candidate_interface/entering_details/international_candidate_enters_their_personal_details_spec.rb
  spec/system/candidate_interface/submitting/candidate_submitting_application_spec.rb
  spec/system/provider_interface/export_applications_spec.rb
  spec/system/provider_interface/provider_accepts_data_sharing_agreement_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: Core

#3431 Add autocomplete to Other Qualifications grades
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/frontend/packs/application-candidate.js
  app/frontend/packs/other-qualifications-grade-autocomplete.js
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  app/views/candidate_interface/other_qualifications/details/edit.html.erb
  app/views/candidate_interface/other_qualifications/details/new.html.erb
  config/initializers/qualifications/other_uk.rb
Labels: Candidate

#3340 Multiple English GCSEs
  app/components/candidate_interface/gcse_grade_guidance_component.html.erb
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/controllers/candidate_interface/gcse/english/grade_controller.rb
  app/forms/candidate_interface/english_gcse_grade_form.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/gcse/english/grade/edit.html.erb
  app/views/candidate_interface/gcse/english/grade/multiple_gcse_edit.html.erb
  config/locales/application_form.yml
  config/locales/gcse_details.yml
  spec/components/candidate_interface/gcse_grade_guidance_component_spec.rb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/forms/candidate_interface/english_gcse_grade_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_english_gcse_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
Labels: Candidate

#3439 Correct conditional field label text and sizing for qualification types
  app/views/candidate_interface/degrees/type/_form_fields.html.erb
  app/views/candidate_interface/other_qualifications/type/_shared_form.html.erb
  config/locales/application_form.yml
Labels: Candidate

#3443 Update content for reference start page
  app/views/candidate_interface/references/base/start.html.erb
Labels: Candidate

#3442 Add GCSE subject autocomplete
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  config/initializers/qualifications/gcse.rb
  spec/system/candidate_interface/entering_details/candidate_entering_other_qualification_spec.rb
Labels: Candidate

#3434 Increase pagination from 15 to 30 items per page
  app/controllers/provider_interface/application_choices_controller.rb
  app/controllers/support_interface/candidates_controller.rb
  app/controllers/support_interface/email_log_controller.rb
  app/controllers/support_interface/provider_users_controller.rb
  app/controllers/support_interface/providers_controller.rb
  app/controllers/support_interface/ucas_matches_controller.rb
  app/controllers/support_interface/vendor_api_requests_controller.rb
  app/models/support_interface/applications_filter.rb
  spec/system/provider_interface/provider_applications_pagination_spec.rb
Labels: ProVendor

#3438 Change copy for Criminal convictions and professional misconduct
  config/locales/safeguarding.yml
  spec/components/provider_interface/safeguarding_declaration_component_spec.rb
  spec/components/support_interface/safeguarding_issues_component_spec.rb
Labels: ProVendor

#3422 Do not include diversity information in HESA export if user does not have permission to view it
  app/controllers/provider_interface/applications_exports_controller.rb
  app/services/provider_interface/hesa_data_export.rb
  app/views/provider_interface/applications_exports/new.html.erb
  spec/services/provider_interface/hesa_data_export_spec.rb
  spec/system/provider_interface/export_applications_spec.rb
Labels: ProVendor

#3415 Add GCSE Science Triple Award grades to Vendor API
  app/presenters/vendor_api/single_application_presenter.rb
  app/views/api_docs/pages/release_notes.md
  config/vendor-api-v1.yml
  spec/presenters/vendor_api/single_application_presenter_spec.rb
Labels: ProVendor

#3445 Support users can edit application phone numbers
  app/components/personal_details_component.rb
  app/components/provider_interface/personal_details_component.html.erb
  app/components/provider_interface/personal_details_component.rb
  app/components/support_interface/personal_details_component.html.erb
  app/components/support_interface/personal_details_component.rb
  app/controllers/support_interface/application_forms/applicant_details_controller.rb
  app/forms/support_interface/application_forms/edit_applicant_details_form.rb
  app/models/application_form.rb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/support_interface/application_forms/applicant_details/edit.html.erb
  app/views/support_interface/application_forms/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/provider_interface/personal_details_component_spec.rb
  spec/components/support_interface/personal_details_component_spec.rb
  spec/models/application_form_spec.rb
  spec/system/support_interface/editing_applicant_details_spec.rb
Labels: Support

#3392 Resolve dual applications flow
  app/components/support_interface/ucas_match_action_component.html.erb
  app/components/support_interface/ucas_match_action_component.rb
  app/controllers/support_interface/ucas_matches_controller.rb
  app/models/ucas_match.rb
  app/views/support_interface/ucas_matches/show.html.erb
  config/routes.rb
  spec/components/support_interface/ucas_match_action_component_spec.rb
  spec/models/ucas_match_spec.rb
  spec/system/support_interface/ucas_matches_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: ProVendor

#3454 Add Slack notification for RBD feedback
  app/services/save_and_send_reject_by_default_feedback.rb
  spec/services/save_and_send_reject_by_default_feedback_spec.rb
Labels: ProVendor

#3449 Update guidance around 5 years work history
  app/forms/candidate_interface/work_explanation_form.rb
  app/views/candidate_interface/work_history/explanation/show.html.erb
  app/views/candidate_interface/work_history/length/show.html.erb
  config/locales/application_form.yml
  spec/factories.rb
  spec/forms/candidate_interface/work_explanation_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/entering_details/candidate_edits_work_history_after_completing_the_section_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_work_history_breaks_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_work_history_spec.rb
Labels: Candidate

#3455 Amend UCAS matches "Action needed" flag
  app/models/ucas_match.rb
  spec/models/ucas_match_spec.rb
Labels: ProVendor

#3446 Support: Redirect sign in page to candidates page if already signed in
  app/controllers/support_interface/sessions_controller.rb
  config/routes.rb
  spec/system/support_interface/authentication_spec.rb
Labels: Support

#3456 Refactor English GCSEs
  adr/0016-structured-gcse-grades.md
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/forms/candidate_interface/english_gcse_grade_form.rb
  app/forms/candidate_interface/science_gcse_grade_form.rb
  app/presenters/vendor_api/single_application_presenter.rb
  db/migrate/20201118140921_update_grades_to_structured_grades.rb
  db/schema.rb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/forms/candidate_interface/science_gcse_grade_form_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
Labels: Candidate

#3464 Fix test related to provider access controls
  spec/services/support_interface/provider_access_controls_stats_spec.rb
Labels: ProVendor

#3457 Remove autocomplete complete from GCSE Maths grade form
  app/forms/candidate_interface/gcse_qualification_details_form.rb
  app/views/candidate_interface/gcse/maths/grade/edit.html.erb
  spec/forms/candidate_interface/gcse_qualification_details_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_is_redirected_to_before_you_start_page_on_first_sign_in_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
Labels: Candidate

#3462 Review candidate decision views
  app/controllers/candidate_interface/decisions_controller.rb
  app/views/candidate_interface/decisions/accept_offer.html.erb
  app/views/candidate_interface/decisions/decline.html.erb
  app/views/candidate_interface/decisions/decline_offer.html.erb
  app/views/candidate_interface/decisions/feedback.html.erb
  app/views/candidate_interface/decisions/offer.html.erb
  app/views/candidate_interface/decisions/offer_via_support.html.erb
  app/views/candidate_interface/decisions/withdraw.html.erb
  app/views/candidate_interface/decisions/withdrawal_feedback.html.erb
  config/locales/decisions.yml
  config/locales/en.yml
  config/routes.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_accepts_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_declines_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_withdraws_spec.rb
Labels: Candidate

#3466 Multiple GSCE grade flow tidy up
  app/controllers/candidate_interface/gcse/english/grade_controller.rb
  app/controllers/candidate_interface/gcse/grade_controller.rb
  app/controllers/candidate_interface/gcse/grade_controller_concern.rb
  app/controllers/candidate_interface/gcse/maths/grade_controller.rb
  app/controllers/candidate_interface/gcse/science/grade_controller.rb
  app/forms/candidate_interface/english_gcse_grade_form.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/gcse/english/grade/edit.html.erb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_science_award_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_science_spec.rb
Labels: Candidate

#3461 Add referee guidance to application page for providers
  app/views/provider_interface/application_choices/_references_context.html.erb
Labels: ProVendor

#3468 Include section name on application feedback form
  app/components/candidate_interface/application_feedback_component.html.erb
  app/controllers/candidate_interface/application_feedback_controller.rb
  app/forms/candidate_interface/application_feedback_form.rb
  app/views/candidate_interface/application_feedback/new.html.erb
  config/locales/application_feedback.yml
  config/locales/application_feedback_component.yml
  config/locales/application_form.yml
  config/locales/en.yml
  spec/components/candidate_interface/application_feedback_component_spec.rb
  spec/system/candidate_interface/feedback/candidate_provides_feedback_while_completing_their_application_spec.rb
Labels: Candidate

#3458 Validate A/AS level grades
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/forms/candidate_interface/other_qualification_wizard.rb
  app/views/candidate_interface/other_qualifications/type/_shared_form.html.erb
  config/initializers/qualifications/a_and_as_level_grades.rb
  config/initializers/qualifications/a_and_as_level_subjects.rb
  config/initializers/qualifications/gcse_grades.rb
  config/initializers/qualifications/hesa_degree_grades.rb
  config/initializers/qualifications/hesa_degree_institutions.rb
  config/initializers/qualifications/hesa_degree_subjects.rb
  config/initializers/qualifications/hesa_degree_types.rb
  config/initializers/qualifications/other_uk_qualifications.rb
  config/locales/application_form.yml
  spec/forms/candidate_interface/other_qualification_wizard_spec.rb
Labels: Candidate

#3453 Remove autocomplete from IELTS Grade field and update spec
  app/forms/candidate_interface/english_foreign_language/ielts_form.rb
  app/views/candidate_interface/english_foreign_language/ielts/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/ielts/edit.html.erb
  app/views/candidate_interface/english_foreign_language/ielts/new.html.erb
  app/views/candidate_interface/english_foreign_language/toefl/_form_fields.html.erb
  config/locales/application_form.yml
  spec/forms/candidate_interface/english_foreign_language/ielts_form_spec.rb
  spec/system/candidate_interface/entering_details/your_ielts_results_spec.rb
Labels: Candidate

#3483 Update word limit
  app/forms/referee_interface/reference_feedback_form.rb
  app/views/referee_interface/reference/feedback.html.erb
Labels: Candidate

#3477 Validate grades when adding 'Other' GCSEs
  app/forms/candidate_interface/other_qualification_wizard.rb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  config/initializers/qualifications/gcse_subjects.rb
  config/locales/gcse_details.yml
  spec/forms/candidate_interface/other_qualification_wizard_spec.rb
Labels: Candidate

#3482 Multiple English GCSE tidy up
  app/controllers/candidate_interface/gcse/english/grade_controller.rb
  app/forms/candidate_interface/english_gcse_grade_form.rb
  spec/forms/candidate_interface/english_gcse_grade_form_spec.rb
Labels: Candidate

#3484 Add trackable applicant ID to UCAS matches
  app/components/support_interface/ucas_match_action_component.rb
  app/models/ucas_match.rb
  app/models/ucas_matched_application.rb
  app/views/support_interface/ucas_matches/show.html.erb
  spec/components/support_interface/ucas_match_action_component_spec.rb
  spec/factories.rb
  spec/system/support_interface/ucas_matches_spec.rb
  spec/system/ucas_matching/matching_data_example.csv
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: Support

#3489 Fix application status value in E&D report
  app/services/support_interface/equality_and_diversity_export.rb
  spec/services/support_interface/equality_and_diversity_export_spec.rb
Labels: Candidate

#3486 Remove the eligibility and not eligible pages
  app/controllers/candidate_interface/start_page_controller.rb
  app/forms/candidate_interface/eligibility_form.rb
  app/views/candidate_interface/start_page/eligibility.html.erb
  app/views/candidate_interface/start_page/not_eligible.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/routes.rb
Labels: Candidate

#3474 Review referee interface
  app/views/referee_interface/reference/confirmation.html.erb
  app/views/referee_interface/reference/feedback.html.erb
  app/views/referee_interface/reference/finish.html.erb
  app/views/referee_interface/reference/refuse_feedback.html.erb
  app/views/referee_interface/reference/relationship.html.erb
  app/views/referee_interface/reference/review.html.erb
  app/views/referee_interface/reference/safeguarding.html.erb
  config/locales/en.yml
  config/locales/referee.yml
  spec/system/referee_interface/referee_can_submit_a_reference_for_candidate_with_relationship_and_safeguarding_spec.rb
  spec/system/referee_interface/referee_refuses_to_give_a_reference_spec.rb
Labels: Referee

#3490 Add validation string for right to work question
  config/locales/application_form.yml
  spec/system/candidate_interface/entering_details/international_candidate_enters_their_personal_details_spec.rb
Labels: Candidate

#3497 Add unique index to application choices
  db/migrate/20201123174522_add_unique_index_to_application_choices.rb
  db/schema.rb
  spec/system/provider_interface/provider_applications_pagination_spec.rb
Labels: Candidate

#3502 Add provider_type column to providers
  db/migrate/20201124162533_add_type_to_providers.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3492 Update layout - application pages (unsubmitted & review)
  app/components/candidate_interface/application_form_apply_again_course_choice_component.html.erb
  app/components/candidate_interface/application_form_apply_again_course_choice_component.rb
  app/components/candidate_interface/application_form_course_choices_component.html.erb
  app/components/candidate_interface/application_form_course_choices_component.rb
  app/components/candidate_interface/contact_details_review_component.rb
  app/helpers/select_options_helper.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/application_choices/review.html.erb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/contact_details/address/edit.html.erb
  app/views/candidate_interface/contact_details/address_type/edit.html.erb
  app/views/candidate_interface/contact_details/base/edit.html.erb
  app/views/candidate_interface/contact_details/review/show.html.erb
  app/views/candidate_interface/personal_details/base/_shared_form.html.erb
  app/views/candidate_interface/personal_details/base/edit.html.erb
  app/views/candidate_interface/personal_details/base/new.html.erb
  app/views/candidate_interface/personal_details/review/show.html.erb
  app/views/candidate_interface/submitted_application_form/complete.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  spec/components/candidate_interface/application_form_apply_again_course_choice_component_spec.rb
  spec/components/candidate_interface/application_form_course_choices_component_spec.rb
  spec/components/candidate_interface/contact_details_review_component_spec.rb
  spec/helpers/select_options_helper_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/apply_again/candidate_carries_over_unsubmitted_application_between_cycles_spec.rb
  spec/system/candidate_interface/apply_again/candidate_carries_over_unsubmitted_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/apply_again/candidate_carries_over_unsubmitted_application_without_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/apply_again/candidate_with_unsuccessful_application_applies_again_spec.rb
  spec/system/candidate_interface/apply_again/carry_over_unsuccessful_application_between_cycles_spec.rb
  spec/system/candidate_interface/apply_again/carry_over_unsuccessful_application_spec.rb
  spec/system/candidate_interface/course_selection/candidate_cannot_add_new_course_once_the_cycle_has_closed_spec.rb
  spec/system/candidate_interface/course_selection/candidate_deletes_course_after_completing_section_spec.rb
  spec/system/candidate_interface/course_selection/candidate_does_not_know_where_they_want_to_apply_spec.rb
  spec/system/candidate_interface/course_selection/candidate_edits_course_choices_spec.rb
  spec/system/candidate_interface/course_selection/candidate_sees_add_additional_courses_after_adding_course_spec.rb
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_not_on_apply_spec.rb
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_spec.rb
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_study_mode_spec.rb
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_that_is_full_spec.rb
  spec/system/candidate_interface/entering_details/add_other_qualification_spec.rb
  spec/system/candidate_interface/entering_details/candidate_becoming_a_teacher_spec.rb
  spec/system/candidate_interface/entering_details/candidate_edits_or_deletes_volunteering_section_after_competing_the_section_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_contact_details_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_disability_info_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_when_languages_hidden_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_subject_knowledge_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_volunteering_and_school_experience_spec.rb
  spec/system/candidate_interface/entering_details/candidate_viewing_a_science_gcse_spec.rb
  spec/system/candidate_interface/entering_details/declare_no_qualification_spec.rb
  spec/system/candidate_interface/entering_details/declare_qualification_not_needed_spec.rb
  spec/system/candidate_interface/entering_details/international_candidate_enters_their_personal_details_spec.rb
  spec/system/candidate_interface/entering_details/your_ielts_results_spec.rb
  spec/system/candidate_interface/entering_details/your_toefl_result_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_accepts_offer_for_a_course_held_open_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
  spec/system/support_interface/validation_errors_spec.rb
  spec/system/support_interface/validation_errors_summary_spec.rb
Labels: Candidate

#3485 Add govuk error summaries and track validation errors where missing
  app/controllers/candidate_interface/degrees/completion_status_controller.rb
  app/controllers/candidate_interface/degrees/grade_controller.rb
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/controllers/candidate_interface/degrees/naric_statement_controller.rb
  app/controllers/candidate_interface/degrees/subject_controller.rb
  app/controllers/candidate_interface/degrees/type_controller.rb
  app/controllers/candidate_interface/degrees/year_controller.rb
  app/controllers/candidate_interface/english_foreign_language/ielts_controller.rb
  app/controllers/candidate_interface/english_foreign_language/other_efl_qualification_controller.rb
  app/controllers/candidate_interface/english_foreign_language/start_controller.rb
  app/controllers/candidate_interface/english_foreign_language/toefl_controller.rb
  app/controllers/candidate_interface/english_foreign_language/type_controller.rb
  app/controllers/candidate_interface/prefill_application_form_controller.rb
  app/views/candidate_interface/decisions/withdrawal_feedback.html.erb
  app/views/candidate_interface/degrees/completion_status/_form_fields.html.erb
  app/views/candidate_interface/degrees/grade/edit.html.erb
  app/views/candidate_interface/degrees/grade/new.html.erb
  app/views/candidate_interface/degrees/institution/_form_fields.html.erb
  app/views/candidate_interface/degrees/naric_statement/edit.html.erb
  app/views/candidate_interface/degrees/naric_statement/new.html.erb
  app/views/candidate_interface/degrees/subject/_form_fields.html.erb
  app/views/candidate_interface/degrees/type/add_another.html.erb
  app/views/candidate_interface/degrees/type/edit.html.erb
  app/views/candidate_interface/degrees/type/new.html.erb
  app/views/candidate_interface/degrees/year/edit.html.erb
  app/views/candidate_interface/degrees/year/new.html.erb
  app/views/candidate_interface/english_foreign_language/other_efl_qualification/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/start/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/toefl/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/type/new.html.erb
  app/views/candidate_interface/prefill_application_form/new.html.erb
Labels: Candidate

#3496 Add Activity Log query service
  app/queries/get_activity_log_events.rb
  app/queries/get_application_choices_for_providers.rb
  spec/factories.rb
  spec/queries/get_activity_log_events_spec.rb
Labels: ProVendor

#3503 Populate latitude and longitude on Site sync from Find
  app/services/find_sync/sync_courses_from_find.rb
  spec/services/find_sync/sync_provider_from_find_spec.rb
  spec/support/test_helpers/find_api_helper.rb
Labels: Core

#3493 Applying for the same course twice bug
  app/controllers/candidate_interface/find_course_selections_controller.rb
  app/models/application_choice.rb
  spec/models/application_choice_spec.rb
  spec/system/candidate_interface/course_selection/candidate_cannot_add_course_twice_with_back_button_spec.rb
Labels: Candidate

#3515 Renamed application section tweaks
  app/components/interview_preferences_component.html.erb
  app/components/provider_interface/diversity_information_component.html.erb
  app/components/provider_interface/safeguarding_declaration_component.html.erb
  app/components/provider_interface/training_with_disability_component.html.erb
  app/components/qualifications_component.html.erb
  app/views/candidate_interface/application_choices/index.html.erb
  config/locales/en.yml
  spec/system/candidate_interface/entering_details/candidate_entering_disability_info_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_suitability_to_work_with_children_spec.rb
Labels: Candidate, Content, ProVendor

#3518 Fix bug with withdrawal feedback page not rendering
  app/controllers/candidate_interface/decisions_controller.rb
  app/views/candidate_interface/decisions/withdrawal_feedback.html.erb
  config/locales/application_form.yml
  spec/system/candidate_interface/offers_and_withdrawls/candidate_withdraws_spec.rb
Labels: Candidate

#3516 Support: add filtering by candidate and application choice IDs
  app/components/filter_component.html.erb
  app/components/support_interface/applications_table_component.html.erb
  app/components/support_interface/candidates_table_component.html.erb
  app/controllers/support_interface/candidates_controller.rb
  app/models/support_interface/applications_filter.rb
  app/models/support_interface/candidates_filter.rb
  spec/system/support_interface/see_applications_spec.rb
  spec/system/support_interface/see_candidates_spec.rb
Labels: Support

#3514 Detect and warn about database-level enum changes (requires Ruby 2.7.2)
  .github/scripts/enums_in_models.rb
  .github/workflows/pull_request_checks.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: Core

#3523 Fix provider permissions list component
  app/components/associated_providers_permissions_list_component.html.erb
  app/components/associated_providers_permissions_list_component.rb
  spec/components/associated_providers_permissions_list_component_spec.rb
Labels: ProVendor

#3512 Remove banner style dependency from incomplete section component
  app/components/candidate_interface/becoming_a_teacher_review_component.html.erb
  app/components/candidate_interface/contact_details_review_component.html.erb
  app/components/candidate_interface/course_choices_review_component.html.erb
  app/components/candidate_interface/degrees_review_component.html.erb
  app/components/candidate_interface/gcse_qualification_review_component.html.erb
  app/components/candidate_interface/incomplete_section_component.html.erb
  app/components/candidate_interface/incomplete_section_component.rb
  app/components/candidate_interface/interview_preferences_review_component.html.erb
  app/components/candidate_interface/other_qualifications_review_component.html.erb
  app/components/candidate_interface/personal_details_review_component.html.erb
  app/components/candidate_interface/safeguarding_review_component.html.erb
  app/components/candidate_interface/section_missing_banner_component.html.erb
  app/components/candidate_interface/subject_knowledge_review_component.html.erb
  app/components/candidate_interface/training_with_a_disability_review_component.html.erb
  app/components/candidate_interface/volunteering_review_component.html.erb
  app/components/candidate_interface/work_history_review_component.html.erb
  app/frontend/styles/_banner.scss
  app/frontend/styles/_inset-text.scss
  app/frontend/styles/application.scss
  app/views/candidate_interface/application_form/_review.html.erb
  spec/components/candidate_interface/incomplete_section_component_spec.rb
  spec/components/candidate_interface/section_missing_banner_component_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_disability_info_spec.rb
  spec/system/candidate_interface/entering_details/candidate_viewing_a_science_gcse_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviewing_an_incomplete_application_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
Labels: Candidate

#3536 Update ordering of candidate routes
  config/routes.rb
Labels: Candidate

#3525 Update applications index banner with RBD date information
  app/services/feature_flag.rb
  app/views/provider_interface/application_choices/index.html.erb
  app/views/provider_interface/start_page/show.html.erb
  spec/system/provider_interface/providers_can_view_end_of_cycle_comms_spec.rb
  spec/system/provider_interface/providers_can_view_information_in_the_banner_spec.rb
Labels: ProVendor

#3528 Add provider code to access controls export
  app/services/support_interface/provider_access_controls_export.rb
  spec/services/support_interface/provider_access_controls_export_spec.rb
Labels: Support

#3539 Add columns to work history export
  app/services/support_interface/unexplained_breaks_in_work_history_export.rb
  spec/services/support_interface/unexplained_breaks_in_work_history_export_spec.rb
Labels: Candidate

#3534 Update copy for organisational permissions page
  config/locales/provider_relationship_permissions.yml
Labels: Content, ProVendor

#3543 Update EFL edit initial question path
  config/routes.rb
Labels: Candidate

#3542 Update the candidate tracker and application reference export to include references' requested_at times
  app/services/support_interface/application_references_export.rb
  app/services/support_interface/candidate_journey_tracker.rb
  spec/services/support_interface/application_references_export_spec.rb
  spec/services/support_interface/candidate_journey_tracker_spec.rb
Labels: Candidate

#3463 Send initial emails to resolve dual applications
  app/components/support_interface/ucas_match_action_component.rb
  app/controllers/support_interface/ucas_matches_controller.rb
  app/lib/time_limit_config.rb
  app/mailers/candidate_mailer.rb
  app/mailers/provider_mailer.rb
  app/models/ucas_match.rb
  app/models/ucas_matched_application.rb
  app/services/support_interface/send_ucas_match_initial_emails.rb
  app/services/support_interface/send_ucas_match_initial_emails_duplicate_applications.rb
  app/services/support_interface/send_ucas_match_initial_emails_multiple_acceptances.rb
  app/views/candidate_mailer/ucas_match_initial_email_duplicate_applications.text.erb
  app/views/candidate_mailer/ucas_match_initial_email_multiple_acceptances.text.erb
  app/views/provider_mailer/ucas_match_initial_email_duplicate_applications.text.erb
  config/locales/candidate_mailer.yml
  config/locales/provider_mailer.yml
  config/routes.rb
  spec/components/support_interface/ucas_match_action_component_spec.rb
  spec/lib/time_limit_config_spec.rb
  spec/mailers/candidate_mailer_ucas_match_initial_email_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/mailers/previews/provider_mailer_preview.rb
  spec/mailers/provider_mailer_spec.rb
  spec/models/ucas_match_spec.rb
  spec/models/ucas_matched_application_spec.rb
  spec/services/support_interface/send_ucas_match_initial_emails_duplicate_applications_spec.rb
  spec/services/support_interface/send_ucas_match_initial_emails_multiple_acceptances_spec.rb
  spec/services/support_interface/send_ucas_match_initial_emails_spec.rb
  spec/system/support_interface/docs_spec.rb
  spec/system/support_interface/ucas_matches_spec.rb
Labels: Support

#3551 Show more course information in Support
  app/components/support_interface/course_details_component.html.erb
  app/components/support_interface/course_details_component.rb
  app/views/support_interface/course/show.html.erb
  config/locales/en.yml
  spec/components/support_interface/course_details_component_spec.rb
Labels: Support

#3554 Bugfix: initialising country autocomplete on non-UK qualification
  app/frontend/packs/country-autocomplete.js
Labels: Bug bash 🐞🔨, Candidate

#3545 Update other qualification paths
  config/routes.rb
Labels: Candidate

#3541 Rename GCSE ‘naric-reference’ to ‘naric’
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/controllers/candidate_interface/gcse/institution_country_controller.rb
  app/controllers/candidate_interface/gcse/naric_controller.rb
  app/forms/candidate_interface/gcse_naric_form.rb
  app/models/application_qualification.rb
  app/views/candidate_interface/gcse/naric/edit.html.erb
  config/locales/application_form.yml
  config/locales/gcse_details.yml
  config/routes.rb
  spec/forms/candidate_interface/gcse_naric_form_spec.rb
  spec/models/application_qualification_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_international_gcse_spec.rb
Labels: Candidate

#3544 Review reference paths
  app/components/candidate_interface/references_review_component.html.erb
  config/routes.rb
Labels: Candidate

#3404 Structured reasons for rejection
  app/components/provider_interface/reasons_for_rejection_component.html.erb
  app/components/provider_interface/reasons_for_rejection_component.rb
  app/components/provider_interface/status_box_components/rejected_component.html.erb
  app/controllers/provider_interface/decisions_controller.rb
  app/controllers/provider_interface/reasons_for_rejection_controller.rb
  app/forms/provider_interface/reasons_for_rejection_wizard.rb
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_reject.scss
  app/models/provider_interface/reasons_for_rejection.rb
  app/services/feature_flag.rb
  app/services/reject_application.rb
  app/views/provider_interface/reasons_for_rejection/check.html.erb
  app/views/provider_interface/reasons_for_rejection/edit_initial_questions.html.erb
  app/views/provider_interface/reasons_for_rejection/edit_other_reasons.html.erb
  config/locales/reasons_for_rejection.yml
  config/routes.rb
  spec/components/provider_interface/reasons_for_rejection_component_spec.rb
  spec/forms/provider_interface/reasons_for_rejection_wizard_spec.rb
  spec/models/application_choice_spec.rb
  spec/services/reject_application_spec.rb
  spec/system/provider_interface/provider_rejects_application_spec.rb
  spec/system/provider_interface/reject_a_rejected_application_spec.rb
  spec/system/provider_interface/reject_an_application_spec.rb
Labels: ProVendor
