Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2020-08, with the labels that each got.

#2628 Use the form builder's built-in legends and captions
  app/views/provider_interface/decisions/new_offer.html.erb
  app/views/provider_interface/decisions/new_withdraw_offer.html.erb
  app/views/provider_interface/decisions/respond.html.erb
  app/views/provider_interface/provider_users/edit_providers.html.erb
Labels: ProVendor

#2627 Fix for country autocomplete saving wrong value
  app/frontend/packs/application.js
  app/frontend/packs/country-autocomplete.js
  app/frontend/packs/nationality-autocomplete.js
Labels: Candidate

#2615 Content update service guidance with access controls
  app/views/content/service_guidance_provider.md
Labels: ProVendor

#2634 Fix several bugs related to IELTS band score
  app/forms/candidate_interface/english_foreign_language/ielts_form.rb
  app/frontend/packs/ielts-band-score-autocomplete.js
Labels: Candidate

#2622 Update browser titles and ensure 'Error:' prefix is shown on error
  app/views/provider_interface/account/show.html.erb
  app/views/provider_interface/account_creation_in_progress.html.erb
  app/views/provider_interface/application_choices/emails.html.erb
  app/views/provider_interface/application_choices/index.html.erb
  app/views/provider_interface/application_choices/new_note.html.erb
  app/views/provider_interface/application_choices/notes.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/provider_interface/application_choices/timeline.html.erb
  app/views/provider_interface/conditions/confirm_update.html.erb
  app/views/provider_interface/conditions/edit.html.erb
  app/views/provider_interface/content/rendered_markdown_template.html.erb
  app/views/provider_interface/decisions/confirm_offer.html.erb
  app/views/provider_interface/decisions/confirm_reject.html.erb
  app/views/provider_interface/decisions/confirm_withdraw_offer.html.erb
  app/views/provider_interface/decisions/new_edit_response.html.erb
  app/views/provider_interface/decisions/new_offer.html.erb
  app/views/provider_interface/decisions/new_reject.html.erb
  app/views/provider_interface/decisions/new_withdraw_offer.html.erb
  app/views/provider_interface/decisions/respond.html.erb
  app/views/provider_interface/permission_error.html.erb
  app/views/provider_interface/provider_agreements/data_sharing_agreement.html.erb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
  app/views/provider_interface/provider_users/edit_permissions.html.erb
  app/views/provider_interface/provider_users/edit_providers.html.erb
  app/views/provider_interface/provider_users/index.html.erb
  app/views/provider_interface/provider_users_invitations/check.html.erb
  app/views/provider_interface/provider_users_invitations/edit_details.html.erb
  app/views/provider_interface/provider_users_invitations/edit_permissions.html.erb
  app/views/provider_interface/provider_users_invitations/edit_providers.html.erb
  app/views/provider_interface/sessions/authentication_fallback.html.erb
  app/views/provider_interface/sessions/check_your_email.html.erb
  app/views/provider_interface/sessions/new.html.erb
  app/views/provider_interface/start_page/show.html.erb
  app/views/support_interface/provider_users/edit.html.erb
  app/views/support_interface/provider_users/new.html.erb
  app/views/support_interface/support_users/new.html.erb
Labels: ProVendor

#2617 Hide header navigation links from provider interface during onboarding
  app/controllers/provider_interface/provider_interface_controller.rb
  app/helpers/navigation_items.rb
  app/services/provider_setup.rb
  app/views/layouts/_header.html.erb
  spec/system/provider_interface/provider_accepts_data_sharing_agreement.rb
Labels: ProVendor

#2643 Update existing code to be backward compatible for other and non_uk qualifications
  app/controllers/candidate_interface/other_qualifications/base_controller.rb
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/forms/candidate_interface/other_qualification_form.rb
  app/forms/candidate_interface/other_qualification_type_form.rb
  app/views/candidate_interface/other_qualifications/base/_form.html.erb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  app/views/candidate_interface/other_qualifications/details/new.html.erb
  app/views/candidate_interface/other_qualifications/type/_shared_form.html.erb
  config/locales/application_form.yml
  spec/forms/candidate_interface/other_qualification_type_form_spec.rb
  spec/system/candidate_interface/candidate_entering_other_qualification_spec.rb
  spec/system/candidate_interface/international/international_candidate_enters_their_other_qualification_spec.rb
Labels: Candidate

#2639 Optional fields are correctly marked optional in the API docs
  app/frontend/styles/_syntax-highlighting.scss
  app/presenters/api_docs/api_schema.rb
  app/views/api_docs/reference/_properties_list.html.erb
  config/vendor-api-v1.yml
Labels: ProVendor

#2629 Correct error message ordering on Provider User wizard details page
  app/forms/provider_interface/provider_user_invitation_wizard.rb
  config/locales/en.yml
Labels: ProVendor

#2649 Refactor OtherQualifications
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/controllers/candidate_interface/other_qualifications/base_controller.rb
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/controllers/candidate_interface/other_qualifications/type_controller.rb
  app/forms/candidate_interface/other_qualification_form.rb
  app/views/candidate_interface/other_qualifications/base/_form.html.erb
  app/views/candidate_interface/other_qualifications/base/edit.html.erb
  app/views/candidate_interface/other_qualifications/base/new.html.erb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  config/routes.rb
  spec/components/candidate_interface/other_qualifications_review_component_spec.rb
  spec/factories.rb
  spec/forms/candidate_interface/other_qualification_form_spec.rb
  spec/models/application_qualification_spec.rb
Labels: Candidate

#2648 Remove `provider_change_response` feature flag
  app/components/provider_interface/status_box_components/offer_component.html.erb
  app/components/provider_interface/status_box_components/offer_component.rb
  app/controllers/provider_interface/decisions_controller.rb
  app/services/feature_flag.rb
  app/views/provider_interface/decisions/respond.html.erb
  spec/system/provider_interface/provider_changes_an_offer_spec.rb
  spec/system/provider_interface/provider_makes_changes_before_offer_spec.rb
  spec/system/provider_interface/provider_withdraws_an_offer_spec.rb
Labels: ProVendor

#2635 Use the new countries autocomplete where appropriate
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/forms/candidate_interface/gcse_institution_country_form.rb
  app/forms/candidate_interface/other_qualification_form.rb
  app/frontend/packs/country-autocomplete.js
  app/frontend/packs/nationality-autocomplete.js
  app/helpers/select_options_helper.rb
  app/views/candidate_interface/gcse/institution_country/edit.html.erb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  config/initializers/countries.rb
  spec/forms/candidate_interface/gcse_institution_country_form_spec.rb
  spec/forms/candidate_interface/other_qualification_form_spec.rb
  spec/system/candidate_interface/international/international_candidate_enters_their_other_qualification_spec.rb
Labels: Candidate

#2642 Restrict 'confirm conditions' to provider users with `make_decisions`
  app/components/provider_interface/status_box_components/pending_conditions_component.html.erb
  app/components/provider_interface/status_box_components/pending_conditions_component.rb
  app/controllers/provider_interface/application_choices_controller.rb
  app/controllers/provider_interface/conditions_controller.rb
  app/controllers/provider_interface/decisions_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/vendor_api/decisions_controller.rb
  app/lib/test_applications.rb
  app/services/change_offer.rb
  app/services/conditions_not_met.rb
  app/services/confirm_enrolment.rb
  app/services/confirm_offer_conditions.rb
  app/services/make_an_offer.rb
  app/services/make_decisions_authorisation.rb
  app/services/provider_authorisation.rb
  app/services/reject_application.rb
  app/services/withdraw_offer.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
  spec/services/conditions_not_met_spec.rb
  spec/services/confirm_enrolment_spec.rb
  spec/services/confirm_offer_conditions_spec.rb
  spec/services/provider_authorisation_spec.rb
  spec/services/withdraw_offer_spec.rb
  spec/system/candidate_interface/candidate_receives_rejection_email_spec.rb
Labels: ProVendor

#2646 Display provider relationships as a graph in support
  app/controllers/support_interface/providers_controller.rb
  app/frontend/styles/_provider.scss
  app/presenters/support_interface/provider_relationships_diagram.rb
  app/views/support_interface/providers/relationships.html.erb
  app/views/support_interface/providers/users.html.erb
  config/routes.rb
Labels: ProVendor

#2651 Add course_code to TAD export
  app/services/support_interface/tad_provider_stats_export.rb
  spec/services/support_interface/tad_provider_stats_export_spec.rb
Labels: ProVendor

#2653 Consistent usage of ‘sign in’, not ‘log in’
  README.md
  adr/0012-extra-security-for-support.md
  app/views/content/cookies_candidate.md
  app/views/content/cookies_provider.md
  app/views/provider_interface/provider_agreements/data_sharing_agreement.html.erb
  app/views/provider_mailer/application_submitted.text.erb
  app/views/provider_mailer/chase_provider_decision.text.erb
  docs/developer-onboarding.md
  docs/manual-deployment.md
  spec/requests/provider_interface/landing_page_redirect_spec.rb
  spec/requests/provider_interface/provider_user_impersonates_candidate_spec.rb
  spec/system/provider_interface/provider_acts_as_candidate_on_sandbox_spec.rb
Labels: ProVendor

#2655 Add autocomplete to Maths and English GCSE grades
  app/controllers/candidate_interface/gcse/grade_controller.rb
  app/forms/candidate_interface/gcse_qualification_details_form.rb
  app/frontend/packs/application.js
  app/frontend/packs/gcse-grade-autocomplete.js
  app/views/candidate_interface/gcse/grade/edit.html.erb
  config/initializers/gcse_grades.rb
  config/locales/application_form.yml
  config/locales/en.yml
  spec/components/candidate_interface/gcse_grade_guidance_component_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_gcse_spec.rb
  spec/system/candidate_interface/candidate_is_redirected_to_before_you_start_page_on_first_sign_in_spec.rb
Labels: Candidate

#2656 Check feature flag when validating EFL completion
  app/models/application_form.rb
  spec/models/application_form_spec.rb
Labels: Candidate

#2640 Fix for focus appearing on mousedown of checkbox labels
  app/components/provider_interface/filter_component.html.erb
  app/frontend/styles/_filter.scss
Labels: ProVendor

#2659 Remove the 'Applications' breadcrumb
  app/views/provider_interface/application_choices/notes.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/provider_interface/application_choices/timeline.html.erb
Labels: ProVendor

#2657 Remove old feature flags
  app/components/candidate_interface/course_choices_review_component.html.erb
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/new_course_choice_needed_banner_component.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/base_controller.rb
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  app/forms/candidate_interface/degree_grade_form.rb
  app/mailers/candidate_mailer.rb
  app/models/application_reference.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/services/decline_offer.rb
  app/services/feature_flag.rb
  app/services/withdraw_application.rb
  app/views/candidate_interface/degrees/grade/_form_fields.html.erb
  app/views/candidate_interface/degrees/institution/_form_fields.html.erb
  app/views/candidate_interface/degrees/subject/_form_fields.html.erb
  app/views/candidate_interface/degrees/type/_form_fields.html.erb
  app/views/candidate_interface/submitted_application_form/complete.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  app/views/candidate_mailer/course_unavailable_course_full.text.erb
  app/views/candidate_mailer/course_unavailable_course_withdrawn.text.erb
  app/views/candidate_mailer/course_unavailable_location_full.text.erb
  app/views/candidate_mailer/course_unavailable_study_mode_full.text.erb
  app/workers/send_course_full_notifications_worker.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
  spec/components/candidate_interface/new_course_choice_needed_banner_component_spec.rb
  spec/forms/candidate_interface/degree_grade_form_spec.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/models/application_reference_spec.rb
  spec/requests/candidate_interface/validation_error_tracking_spec.rb
  spec/services/submit_application_spec.rb
  spec/system/candidate_interface/candidate_becoming_a_teacher_spec.rb
  spec/system/candidate_interface/candidate_can_see_their_rejection_reasons_on_apply_again_spec.rb
  spec/system/candidate_interface/candidate_declines_offer_spec.rb
  spec/system/candidate_interface/candidate_entering_contact_details_spec.rb
  spec/system/candidate_interface/candidate_entering_degrees_spec.rb
  spec/system/candidate_interface/candidate_removes_a_full_or_withdrawn_course_choice_post_submission_spec.rb
  spec/system/candidate_interface/candidate_replaces_reference_after_applying_again_spec.rb
  spec/system/candidate_interface/candidate_reviewing_application_with_unavailable_course_options_spec.rb
  spec/system/candidate_interface/candidate_signs_in_with_validation_errors_spec.rb
  spec/system/candidate_interface/candidate_submits_application_with_full_course_location_spec.rb
  spec/system/candidate_interface/candidate_submits_application_with_full_course_study_mode_spec.rb
  spec/system/candidate_interface/candidate_with_unsuccessful_application_applies_again_spec.rb
  spec/system/candidate_interface/candidate_withdraws_spec.rb
  spec/system/candidate_interface/course_selection/candidate_can_replace_full_or_withdrawn_course_choices_spec.rb
  spec/system/candidate_interface/course_selection/candidate_replaces_a_full_course_spec.rb
  spec/system/candidate_interface/decline_by_default_spec.rb
  spec/system/candidate_interface/international/candidate_entering_contact_details_without_international_addresses_spec.rb
  spec/system/support_interface/validation_errors_spec.rb
  spec/system/support_interface/validation_errors_summary_spec.rb
  spec/workers/send_course_full_notifications_worker_spec.rb
Labels: Candidate

#2630 Add JavaScript to the personal details nationalities page
  app/frontend/packs/application.js
  app/frontend/packs/nationalities-component.js
  app/frontend/styles/_nationalities-component.scss
  app/frontend/styles/application.scss
  app/views/candidate_interface/personal_details/nationalities/_shared_form.html.erb
  app/views/candidate_interface/personal_details/nationalities/edit.html.erb
  app/views/candidate_interface/personal_details/nationalities/new.html.erb
Labels: Candidate

#2623 Delete test candidates and applications via support interface on QA
  app/controllers/support_interface/tasks_controller.rb
  app/views/support_interface/tasks/confirm_delete_test_applications.html.erb
  app/views/support_interface/tasks/index.html.erb
  app/workers/delete_test_applications.rb
  config/routes.rb
  spec/system/support_interface/purge_test_applications_spec.rb
  spec/workers/delete_test_applications_spec.rb
Labels: Support

#2645 Fix character limit rendering for API fields
  app/presenters/api_docs/api_schema.rb
Labels: ProVendor

#2638 Update the display of safeguarding information
  app/components/provider_interface/safeguarding_declaration_component.html.erb
  app/components/provider_interface/safeguarding_declaration_component.rb
  app/views/provider_interface/application_choices/show.html.erb
  config/locales/safeguarding.yml
  spec/components/provider_interface/safeguarding_declaration_component_spec.rb
  spec/system/provider_interface/manage_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: ProVendor

#2667 Fix bug in the nationalities component
  app/frontend/packs/nationalities-component.js
Labels: Candidate

#2652 Email candidates when they are rejected by default
  app/mailers/candidate_mailer.rb
  app/queries/get_application_choices_ready_to_reject_by_default.rb
  app/services/reject_application_by_default.rb
  app/views/candidate_mailer/_application_rejected_intro.erb
  app/views/candidate_mailer/application_rejected_all_rejected_apply_again.erb
  app/views/candidate_mailer/application_rejected_awaiting_decisions.erb
  app/views/candidate_mailer/application_rejected_offers_made.erb
  app/workers/send_candidate_rejection_email_worker.rb
  config/locales/candidate_mailer.yml
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/system/provider_interface/provider_receives_email_when_an_application_has_been_rejected_by_default_spec.rb
  spec/system/provider_interface/provider_receives_email_when_an_application_is_getting_close_to_the_reject_by_default_date_spec.rb
Labels: Candidate

#2675 Don't show details link if no safeguarding issues declared
  app/components/provider_interface/safeguarding_declaration_component.html.erb
  app/components/provider_interface/safeguarding_declaration_component.rb
  spec/components/provider_interface/safeguarding_declaration_component_spec.rb
Labels: ProVendor

#2674 Generate safeguarding issues correctly
  app/lib/test_applications.rb
  app/services/generate_test_data.rb
  spec/factories.rb
Labels: ProVendor

#2586 Adr logging monitoring
  adr/0014-alerting-monitoring.md
Labels: DevOps

#2669 Fix AbstractController::DoubleRenderError in ProviderUsersController
  app/controllers/provider_interface/provider_users_controller.rb
Labels: ProVendor

#2678 Deprecate Withdrawal.reason in the API
  app/presenters/api_docs/api_schema.rb
  app/views/api_docs/pages/release_notes.md
  app/views/api_docs/reference/_properties_list.html.erb
  config/vendor-api-v1.yml
Labels: ProVendor

#2685 Review CSS styles
  app/components/phase_banner.html.erb
  app/components/provider_interface/header_component.html.erb
  app/components/provider_interface/work_history_item_component.html.erb
  app/frontend/packs/nationalities-component.js
  app/frontend/styles/_action-bar.scss
  app/frontend/styles/_breadcrumbs.scss
  app/frontend/styles/_checkboxes-scroll.scss
  app/frontend/styles/_definition-list.scss
  app/frontend/styles/_filter.scss
  app/frontend/styles/_footer.scss
  app/frontend/styles/_header.scss
  app/frontend/styles/_input.scss
  app/frontend/styles/_nationalities-component.scss
  app/frontend/styles/_nationalities.scss
  app/frontend/styles/_phase-banner.scss
  app/frontend/styles/_provider.scss
  app/frontend/styles/_relationship-diagram.scss
  app/frontend/styles/_sortable-table.scss
  app/frontend/styles/_status-box.scss
  app/frontend/styles/_tabs.scss
  app/frontend/styles/_timeline.scss
  app/frontend/styles/_work-history.scss
  app/frontend/styles/application.scss
  app/views/candidate_interface/personal_details/nationalities/edit.html.erb
  app/views/candidate_interface/personal_details/nationalities/new.html.erb
  app/views/layouts/_footer.html.erb
  app/views/support_interface/providers/users.html.erb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: Core

#2663 Implement the provider permissions setup flow
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/provider_interface/provider_relationship_permissions_setup_controller.rb
  app/forms/provider_interface/provider_relationship_permissions_setup_wizard.rb
  app/services/provider_authorisation.rb
  app/services/provider_interface/setup_provider_relationship_permissions.rb
  app/views/provider_interface/provider_relationship_permissions_setup/check.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/info.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/organisations.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/setup_permissions.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/success.html.erb
  config/routes.rb
  spec/forms/provider_interface/provider_relationship_permissions_setup_wizard_spec.rb
  spec/requests/provider_interface/setup_provider_relationship_permissions_request_spec.rb
  spec/services/provider_interface/setup_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/setup_provider_relationship_permissions_spec.rb
Labels: ProVendor

#2677 Change respond banner to include date and add a button
  app/views/provider_interface/application_choices/_application_choice_header.html.erb
  spec/system/provider_interface/provider_makes_an_offer_spec.rb
Labels: ProVendor

#2693 bump serialize-javascript to 3.1.0
  yarn.lock
Labels: Core, dependencies

#2690 Add view diversity information permissions for provider users
  db/migrate/20200811102357_add_view_diversity_information_to_provider_permissions.rb
  db/migrate/20200811113541_add_view_diversity_information_to_provider_relationship_permissions.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#2691 Add user guidance page to support interface regarding GDPR
  app/controllers/support_interface/guidance_controller.rb
  app/helpers/navigation_items.rb
  app/views/support_interface/guidance/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/support_interface/see_user_guidance_spec.rb
Labels: Candidate

#2708 resolve serialize-javascript to 3.1.0
  package.json
Labels: Core, dependencies, javascript

#2684 Fix international GCSEs and Other qualifications on the support app
  app/components/qualification_title_component.rb
  spec/components/qualification_title_component_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#2686 Fix international personal details section in the support app
  app/components/personal_details_component.rb
  spec/components/personal_details_component_spec.rb
  spec/factories.rb
Labels: Bug bash 🐞🔨, Candidate

#2689 Take candidate to the personal details review section if sections have been completed
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/system/candidate_interface/international/international_candidate_enters_their_personal_details_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#2701 Minor UI tweaks to OtherQualifications
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  config/locales/application_form.yml
  spec/components/candidate_interface/other_qualifications_review_component_spec.rb
  spec/system/candidate_interface/candidate_entering_other_qualification_spec.rb
Labels: Candidate

#2661 Require tests to be explicit about which feature flags they rely on
  app/services/feature_flag.rb
  azure/pipelines/build.yml
  azure/pipelines/templates/rspec-job.yml
  azure/pipelines/templates/run-rspec-test.yml
  docker-compose.azure.yml
  spec/components/candidate_interface/other_qualifications_review_component_spec.rb
  spec/components/provider_interface/safeguarding_declaration_component_spec.rb
  spec/forms/candidate_interface/degree_type_form_spec.rb
  spec/forms/candidate_interface/gcse_qualification_details_form_spec.rb
  spec/forms/candidate_interface/nationalities_form_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/rails_helper.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_deletes_and_adds_other_qualificaitons_after_completing_the_section_spec.rb
  spec/system/candidate_interface/candidate_entering_degree_with_missing_information_spec.rb
  spec/system/candidate_interface/candidate_entering_degrees_spec.rb
  spec/system/candidate_interface/candidate_entering_gcse_other_uk_qualification_spec.rb
  spec/system/candidate_interface/candidate_entering_gcse_spec.rb
  spec/system/candidate_interface/candidate_entering_other_qualification_spec.rb
  spec/system/candidate_interface/candidate_entering_personal_details_spec.rb
  spec/system/candidate_interface/candidate_needs_to_provide_two_new_referees_spec.rb
  spec/system/candidate_interface/international/candidate_entering_contact_details_without_international_addresses_spec.rb
  spec/system/candidate_interface/international/international_candidate_enters_their_personal_details_spec.rb
  spec/system/candidate_interface/international/international_candidate_submitting_application_spec.rb
  spec/system/provider_interface/provider_confirms_conditions_met_spec.rb
  spec/system/provider_interface/provider_confirms_conditions_not_met_spec.rb
  spec/system/provider_interface/provider_fails_to_select_response_spec.rb
  spec/system/provider_interface/provider_rejects_application_spec.rb
  spec/system/provider_interface/provider_responds_to_application_spec.rb
  spec/system/provider_interface/provider_withdraws_an_offer_spec.rb
Labels: Core

#2704 Prevent candidates adding courses after the cycle has ended
  app/controllers/candidate_interface/application_choices_controller.rb
  app/controllers/candidate_interface/course_choices/base_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/base_controller.rb
  app/controllers/candidate_interface/find_course_selections_controller.rb
  app/services/candidate_interface/end_of_cycle_policy.rb
  app/services/end_of_cycle_timetable.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/submitted_application_form/complete.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/services/candidate_interface/end_of_cycle_policy_spec.rb
  spec/system/candidate_interface/candidate_cannot_add_new_course_once_the_cycle_has_closed_spec.rb
Labels: Candidate

#2699 Sanitise CSV output by removing spreadsheet formulae
  app/controllers/support_interface/performance_controller.rb
  app/models/provider_emails_for_application_choices.rb
  app/services/safe_csv.rb
  app/services/ucas_matching/matching_data_file.rb
  config/initializers/inflector.rb
  spec/services/safe_csv_spec.rb
Labels: Core

#2707 update steps to deploy using the ops-dashboard
  docs/deployment.md
Labels: Core

#2713 EoC should be at end of deadline dates
  app/services/end_of_cycle_timetable.rb
  spec/services/end_of_cycle_timetable_spec.rb
Labels: Candidate

#2709 Communicate date 2021 cycles open
  app/components/candidate_interface/apply_again_banner_component.rb
  app/components/candidate_interface/reopen_banner_component.html.erb
  app/components/candidate_interface/reopen_banner_component.rb
  app/services/end_of_cycle_timetable.rb
  app/views/candidate_interface/submitted_application_form/complete.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/components/candidate_interface/apply_again_banner_component_spec.rb
  spec/components/candidate_interface/reopen_banner_component_spec.rb
  spec/services/end_of_cycle_timetable_spec.rb
  spec/system/candidate_interface/candidate_views_unsubmitted_application_between_cycles_spec.rb
  spec/system/candidate_interface/candidate_views_unsuccessful_application_between_cycles_spec.rb
Labels: Candidate

#2712 Make /application/:id/offer idempotent
  app/controllers/vendor_api/decisions_controller.rb
  app/services/change_offer.rb
  app/views/api_docs/pages/release_notes.md
  config/locales/en.yml
  spec/requests/vendor_api/post_make_an_offer_spec.rb
  spec/services/change_offer_spec.rb
Labels: ProVendor

#2621 do not mount /public assets local folder
  Makefile
  docker-compose.override.yml
Labels: Core

#2706 Add a JSON 500 error response to API
  app/controllers/errors_controller.rb
Labels: ProVendor

#2680 Make 404 pages have meaningful headers
  app/controllers/candidate_interface/errors_controller.rb
  app/controllers/provider_interface/errors_controller.rb
  app/controllers/support_interface/errors_controller.rb
  app/helpers/application_helper.rb
  app/helpers/navigation_items.rb
  app/views/errors/not_found.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/support_layout.html.erb
  config/routes.rb
Labels: Core

#2720 Don't ask candidate if they want to another job when editing one
  app/views/candidate_interface/work_history/edit/_form.html.erb
  app/views/candidate_interface/work_history/edit/edit.html.erb
  app/views/candidate_interface/work_history/edit/new.html.erb
  spec/system/candidate_interface/candidate_entering_work_history_spec.rb
Labels: Candidate

#2710 Signing out of Manage should also sign you out of DfE Sign-In
  app/controllers/dfe_sign_in_controller.rb
  app/controllers/provider_interface/sessions_controller.rb
  app/controllers/support_interface/sessions_controller.rb
  app/models/dfe_sign_in_user.rb
  config/routes.rb
  spec/system/provider_interface/sign_out_spec.rb
  spec/system/support_interface/sign_out_spec.rb
Labels: ProVendor

#2729 Use the degrees HESA abbreviation for the title on the review component
  app/components/candidate_interface/degrees_review_component.rb
  spec/components/candidate_interface/degrees_review_component_spec.rb
  spec/factories.rb
Labels: Candidate

#2732 bump serialize-javascript to 4.0.0
  package.json
  yarn.lock
Labels: Core, dependencies

#2726 Prevent submitting applications between cycles
  app/components/candidate_interface/apply_again_banner_component.rb
  app/components/candidate_interface/reopen_banner_component.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/services/end_of_cycle_timetable.rb
  app/views/candidate_interface/unsubmitted_application_form/review.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/components/candidate_interface/reopen_banner_component_spec.rb
  spec/services/end_of_cycle_timetable_spec.rb
  spec/system/candidate_interface/candidate_cannot_add_new_course_once_the_cycle_has_closed_spec.rb
  spec/system/candidate_interface/candidate_with_unsubmitted_application_between_cycles_spec.rb
Labels: Candidate

#2711 Implement diversity permissions
  app/components/permissions_list.html.erb
  app/components/provider_interface/edit_provider_user_permissions_component.html.erb
  app/components/provider_interface/provider_relationship_permissions_list_component.rb
  app/components/provider_interface/provider_user_invitation_permissions_component.rb
  app/components/provider_relationship_permissions_list.html.erb
  app/controllers/provider_interface/provider_relationship_permissions_controller.rb
  app/forms/provider_interface/provider_relationship_permissions_form.rb
  app/forms/provider_interface/provider_user_invitation_wizard.rb
  app/forms/provider_interface/provider_user_permissions_form.rb
  app/models/provider_permissions.rb
  app/models/provider_relationship_permissions.rb
  app/services/provider_interface/setup_provider_relationship_permissions.rb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/info.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/setup_permissions.html.erb
  app/views/support_interface/provider_users/_provider_options.html.erb
  config/locales/permissions.yml
  spec/components/permissions_list_component_spec.rb
  spec/components/provider_interface/provider_relationship_permissions_list_component_spec.rb
  spec/components/provider_relationship_permissions_list_spec.rb
  spec/factories.rb
  spec/forms/provider_interface/provider_relationship_permissions_form_spec.rb
  spec/forms/provider_interface/provider_relationship_permissions_setup_wizard_spec.rb
  spec/models/provider_relationship_permissions_spec.rb
  spec/services/provider_interface/setup_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/manage_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/manage_provider_user_permissions_spec.rb
  spec/system/provider_interface/provider_invites_user_with_new_wizard_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
  spec/system/provider_interface/setup_provider_relationship_permissions_spec.rb
  spec/system/support_interface/managing_provider_users_spec.rb
Labels: ProVendor

#2703 Add ADR about carrying applications over to the next cycle
  adr/0015-carrying-over-applications.md
Labels: Core

#2716 Ensure support UI can handle long email addresses
  app/helpers/view_helper.rb
  app/views/layouts/support_layout.html.erb
  app/views/support_interface/application_forms/audit.html.erb
  app/views/support_interface/application_forms/show.html.erb
Labels: Support

#2736 Add support for testing EoC features
  app/lib/hosting_environment.rb
  app/services/end_of_cycle_timetable.rb
  app/services/feature_flag.rb
  app/workers/delete_test_applications.rb
  spec/services/end_of_cycle_timetable_spec.rb
Labels: Candidate

#2719 Remove links to Find when the service is down
  app/components/candidate_interface/course_choices_review_component.html.erb
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/rejection_reasons_component.rb
  app/components/candidate_interface/reopen_banner_component.rb
  app/components/grouped_provider_courses_component.html.erb
  app/controllers/candidate_interface/application_choices_controller.rb
  app/controllers/candidate_interface/course_choices/base_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/base_controller.rb
  app/controllers/candidate_interface/find_course_selections_controller.rb
  app/services/candidate_interface/end_of_cycle_policy.rb
  app/services/end_of_cycle_timetable.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/submitted_application_form/complete.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
  spec/components/candidate_interface/rejection_reasons_component_spec.rb
  spec/components/grouped_provider_courses_component_spec.rb
  spec/services/candidate_interface/end_of_cycle_policy_spec.rb
  spec/services/end_of_cycle_timetable_spec.rb
  spec/system/candidate_interface/candidate_cannot_add_new_course_once_the_cycle_has_closed_spec.rb
Labels: Candidate

#2728 Sections should redirect to the beginning of the flow if all entries are deleted
  app/controllers/candidate_interface/degrees/destroy_controller.rb
  app/controllers/candidate_interface/degrees/review_controller.rb
  app/controllers/candidate_interface/other_qualifications/review_controller.rb
  app/controllers/candidate_interface/volunteering/destroy_controller.rb
  app/controllers/candidate_interface/work_history/review_controller.rb
  spec/system/candidate_interface/candidate_edits_work_history_after_completing_the_section_spec.rb
  spec/system/candidate_interface/candidate_entering_degrees_spec.rb
  spec/system/candidate_interface/candidate_entering_other_qualification_spec.rb
  spec/system/candidate_interface/candidate_entering_volunteering_and_school_experience_spec.rb
  spec/system/candidate_interface/candidate_entering_work_history_spec.rb
Labels: Candidate

#2748 Carried over applications have courses removed
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  app/services/apply_again.rb
  app/services/carry_over_application.rb
  app/services/duplicate_application.rb
  app/services/end_of_cycle_timetable.rb
  spec/services/apply_again_spec.rb
  spec/services/carry_over_application_spec.rb
  spec/services/duplicate_application_shared_examples.rb
  spec/services/send_apply_again_call_to_action_spec.rb
  spec/services/submit_application_spec.rb
Labels: Candidate

#2731 Prevent new candidates from signing up between cycles
  app/controllers/candidate_interface/sign_up_controller.rb
  app/controllers/candidate_interface/start_page_controller.rb
  app/services/end_of_cycle_timetable.rb
  app/views/candidate_interface/start_page/applications_closed.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/candidate_interface/candidate_without_account_arrives_between_cycles_spec.rb
Labels: Candidate

#2750 Download and process matching files from UCAS
  .env.example
  .env.test
  .gitignore
  app/controllers/support_interface/ucas_matches_controller.rb
  app/models/ucas_match.rb
  app/services/ucas_matching/api_error.rb
  app/services/ucas_matching/process_matching_data.rb
  app/services/ucas_matching/ucas_api.rb
  app/services/ucas_matching/upload_matching_data.rb
  app/services/ucas_matching/upload_test_file.rb
  app/views/support_interface/performance/index.html.erb
  app/views/support_interface/ucas_matches/index.html.erb
  app/views/support_interface/ucas_matches/show.html.erb
  azure/pipelines/templates/deploy.yml
  azure/template.json
  config/clock.rb
  config/routes.rb
  db/migrate/20200819081548_create_ucas_matches.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/system/ucas_matching/matching_data_example.csv
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
  spec/system/ucas_matching/upload_matching_data_to_ucas_spec.rb
Labels: Core

#2752 Improve the Slack message for UCAS matching
  app/services/ucas_matching/process_matching_data.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: Core

#2753 Generate test applications with correct equality and diversity data
  app/lib/test_applications.rb
  spec/factories.rb
Labels: Core

#2744 Make magic links single-use and add confirmation page
  app/controllers/candidate_interface/sign_in_controller.rb
  app/models/candidate.rb
  app/queries/find_candidate_by_token.rb
  app/views/candidate_interface/sign_in/confirm_authentication.html.erb
  app/views/candidate_interface/sign_in/expired.html.erb
  config/locales/authentication.yml
  config/routes.rb
  spec/mailers/authentication_mailer_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/models/candidate_spec.rb
  spec/support/test_helpers/sign_in_helper.rb
  spec/support/test_helpers/sign_up.rb
  spec/system/candidate_interface/application_choices_are_delivered_to_providers_spec.rb
  spec/system/candidate_interface/candidate_account_spec.rb
  spec/system/candidate_interface/candidate_clicking_on_expired_magic_link_spec.rb
  spec/system/candidate_interface/candidate_is_redirected_to_before_you_start_page_on_first_sign_in_spec.rb
  spec/system/candidate_interface/candidate_signs_up_using_magic_link_with_an_invalid_token_spec.rb
  spec/system/candidate_interface/candidate_tries_to_reuse_magic_link_spec.rb
  spec/system/candidate_interface/course_selection/candidate_existing_user_with_course_params_spec.rb
  spec/system/candidate_interface/course_selection/candidate_new_user_with_course_params_and_cancel_spec.rb
  spec/system/candidate_interface/course_selection/candidate_new_user_with_course_params_spec.rb
  spec/system/candidate_interface/two_candidates_sign_in_on_same_machine_spec.rb
  spec/system/decline_by_default_spec.rb
Labels: Candidate

#2717 Add missing audible label for first line of address
  app/views/candidate_interface/contact_details/address/edit.html.erb
  config/locales/application_form.yml
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_contact_details_spec.rb
  spec/system/candidate_interface/international/candidate_entering_contact_details_without_international_addresses_spec.rb
Labels: Candidate

#2749 Add DSA success page with contextual content
  app/controllers/provider_interface/provider_agreements_controller.rb
  app/views/provider_interface/provider_agreements/success.html.erb
  spec/system/provider_interface/provider_accepts_data_sharing_agreement_spec.rb
Labels: ProVendor

#2730 Implement design for permissions not yet set by provider
  app/components/provider_relationship_permissions_list.html.erb
  app/views/provider_interface/organisations/show.html.erb
  spec/components/provider_relationship_permissions_list_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
Labels: ProVendor

#2747 Force all course codes to be unique when generating fake data
  app/services/generate_fake_provider.rb
Labels: Core

#2756 Show the selected course option's study mode in the API response
  app/presenters/vendor_api/single_application_presenter.rb
  app/views/api_docs/pages/release_notes.md
Labels: ProVendor

#2769 Refactor permissions list component
  app/components/associated_providers_permissions_list_component.html.erb
  app/components/associated_providers_permissions_list_component.rb
  app/components/permissions_list.html.erb
  app/components/permissions_list_component.html.erb
  app/components/permissions_list_component.rb
  app/components/provider_interface/edit_provider_user_permissions_component.html.erb
  app/components/provider_interface/edit_provider_user_permissions_component.rb
  app/components/provider_interface/provider_account_component.rb
  app/components/provider_interface/provider_user_details_component.rb
  app/components/support_interface/provider_users_table_component.html.erb
  app/views/provider_interface/organisations/_permissions_list.html.erb
  spec/components/associated_providers_permissions_list_component_spec.rb
  spec/components/permissions_list_component_spec.rb
Labels: ProVendor

#2767 Section titles and ordering
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/volunteering/base/edit.html.erb
  app/views/candidate_interface/volunteering/base/new.html.erb
  config/locales/en.yml
Labels: Candidate, Content

#2771 Update apply again description in candidate flow
  config/locales/application_states.yml
Labels: Candidate, Content

#2751 Conditionally show Diversity information on an individual application page
  app/components/provider_interface/diversity_information_component.html.erb
  app/components/provider_interface/diversity_information_component.rb
  app/services/application_state_change.rb
  app/services/provider_authorisation.rb
  app/views/provider_interface/application_choices/show.html.erb
  spec/components/provider_interface/diversity_information_component_spec.rb
  spec/services/provider_authorisation_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: ProVendor

#2770 Modify back to application links to back links on additional referee and work history views
  app/views/candidate_interface/additional_referees/confirm.html.erb
  app/views/candidate_interface/work_history/explanation/show.html.erb
Labels: Candidate

#2764 Fix ActiveRecord::RecordInvalid in TestApplications
  app/lib/test_applications.rb
Labels: Core

#2768 Make it easier to find applications from provider notification emails
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/application_rejected_by_default.text.erb
  app/views/provider_mailer/application_withdrawn.text.erb
  app/views/provider_mailer/declined.text.erb
  app/views/provider_mailer/declined_by_default.text.erb
  app/views/provider_mailer/offer_accepted.text.erb
  config/locales/provider_mailer.yml
  config/locales/provider_notifications.yml
  spec/mailers/provider_mailer_spec.rb
  spec/system/candidate_interface/candidate_accepts_offer_spec.rb
  spec/system/candidate_interface/candidate_declines_offer_spec.rb
  spec/system/candidate_interface/candidate_withdraws_spec.rb
  spec/system/decline_by_default_spec.rb
  spec/system/provider_interface/provider_invites_user_with_new_wizard_spec.rb
  spec/system/reject_by_default_spec.rb
  spec/system/support_interface/managing_provider_users_spec.rb
Labels: Bug bash 🐞🔨

#2773 [1964] - Add Skylight performance monitoring
  Gemfile
  Gemfile.lock
  README.md
  azure/pipelines/build.yml
  azure/pipelines/release.yml
  azure/pipelines/templates/deploy.yml
  azure/template.json
  config/application.rb
  config/skylight.yml
  docker-compose.azure.yml
  docs/performance-monitoring.md
Labels: Core

#2778 Remove duplicated heading in API release notes
  app/views/api_docs/pages/release_notes.md
Labels: Core

#2779 Add feature flag to enable normal features between recruitment cycles
  app/services/end_of_cycle_timetable.rb
  app/services/feature_flag.rb
  spec/services/end_of_cycle_timetable_spec.rb
Labels: Core

#2782 Configure Skylight environment
  .env.example
  azure/template.json
  docker-compose.azure.yml
  docs/performance-monitoring.md
Labels: Core

#2759 Carry over unsubmitted applications automatically
  app/services/duplicate_application.rb
  app/services/end_of_cycle_timetable.rb
  app/workers/carry_over_unsubmitted_applications_worker.rb
  spec/factories.rb
  spec/services/carry_over_application_spec.rb
  spec/services/duplicate_application_shared_examples.rb
  spec/system/candidate_interface/automatically_carry_over_unsubmitted_application_to_new_cycle_spec.rb
  spec/workers/carry_over_unsubmitted_applications_worker_spec.rb
Labels: Candidate

#2774 Allow providers to filter applications by recruitment cycle
  app/components/provider_interface/filter_component.html.erb
  app/lib/test_applications.rb
  app/models/course.rb
  app/models/provider_interface/provider_applications_page_state.rb
  app/models/recruitment_cycle.rb
  app/queries/get_application_choices_for_providers.rb
  app/services/feature_flag.rb
  app/services/filter_application_choices_for_providers.rb
  app/workers/generate_test_applications.rb
  lib/tasks/generate_test_data.rake
  lib/tasks/local_dev.rake
  spec/factories.rb
  spec/models/provider_interface/provider_applications_page_state_spec.rb
  spec/queries/get_application_choices_for_providers_spec.rb
  spec/requests/vendor_api/get_multiple_applications_spec.rb
  spec/services/provider_interface/filter_application_choices_for_providers_spec.rb
  spec/system/provider_interface/provider_applications_filter_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
Labels: ProVendor

#2789 Be strict about how clients use TextOrdinalizer
  app/components/candidate_interface/links_to_previous_applications_component.rb
  app/components/candidate_interface/referees_review_component.html.erb
  app/controllers/candidate_interface/referees_controller.rb
  app/lib/text_ordinalizer.rb
Labels: Core

#2791 Fix two flaky tests
  app/services/provider_setup.rb
  spec/system/candidate_interface/candidate_receives_rejection_email_spec.rb
Labels: Core

#2785 Correct back link styling
  app/frontend/styles/_back_link.scss
  app/frontend/styles/application.scss
  app/frontend/styles/candidate/_all.scss
Labels: Core

#2784 If one application choice is cancelled, still send the others
  app/queries/get_application_forms_ready_to_send_to_providers.rb
  app/services/application_state_change.rb
  app/services/send_application_to_provider.rb
  app/services/send_applications_to_provider.rb
  spec/queries/get_application_forms_ready_to_send_to_providers_spec.rb
  spec/services/send_application_to_provider_spec.rb
  spec/services/send_applications_to_provider_spec.rb
Labels: Core

#2772 Carry over unsuccessful applications manually
  app/components/candidate_interface/apply_again_banner_component.html.erb
  app/components/candidate_interface/apply_again_banner_component.rb
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  app/services/carry_over_application.rb
  app/services/end_of_cycle_timetable.rb
  app/views/candidate_interface/submitted_application_form/start_carry_over.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/candidate_interface/apply_again_banner_component_spec.rb
  spec/services/end_of_cycle_timetable_spec.rb
  spec/system/candidate_interface/carry_over_unsuccessful_application_spec.rb
Labels: Candidate

#2763 Reject applications that are awaiting references at the end of the cycle
  app/components/candidate_interface/application_status_tag_component.rb
  app/components/provider_interface/application_status_tag_component.rb
  app/components/provider_interface/application_timeline_component.rb
  app/components/support_interface/application_status_tag_component.rb
  app/models/application_choice.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/application_state_change.rb
  app/services/candidate_interface/get_previous_cycles_awaiting_references_course_choices.rb
  app/services/candidate_interface/reject_awaiting_references_application.rb
  app/workers/carry_over_unsubmitted_applications_worker.rb
  app/workers/reject_awaiting_references_course_choices_worker.rb
  config/clock.rb
  config/locales/application_states.yml
  spec/components/candidate_interface/apply_again_banner_component_spec.rb
  spec/services/application_state_change_spec.rb
  spec/services/candidate_interface/get_previous_cycles_awaiting_references_course_choices_spec.rb
  spec/services/candidate_interface/reject_awaiting_references_application_spec.rb
  spec/services/end_of_cycle_timetable_spec.rb
  spec/support_specs/clockwork_spec.rb
  spec/system/candidate_interface/candidate_is_awaiting_references_when_the_next_cycle_launches_spec.rb
  spec/workers/carry_over_unsubmitted_applications_worker_spec.rb
  spec/workers/reject_awaiting_references_course_choices_worker_spec.rb
Labels: Candidate

#2792 Prevent SVGs in candidate application flow doc from overflowing
  app/views/support_interface/docs/candidate_flow.html.erb
Labels: Support

#2775 Introduce an API field indicating whether safeguarding information has been supplied
  app/presenters/vendor_api/single_application_presenter.rb
  app/views/api_docs/pages/release_notes.md
  app/views/provider_interface/application_choices/show.html.erb
  config/vendor-api-v1.yml
  spec/factories.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: ProVendor

#2798 Small improvements to UCAS matching UX
  app/components/support_interface/application_summary_component.rb
  app/models/candidate.rb
  app/services/ucas_matching/process_matching_data.rb
  spec/components/support_interface/application_summary_component_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: Support

#2783 Remove institution_name from other qualification
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/forms/candidate_interface/other_qualification_form.rb
  app/models/application_qualification.rb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  config/locales/application_form.yml
  spec/components/candidate_interface/other_qualifications_review_component_spec.rb
  spec/forms/candidate_interface/other_qualification_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_deletes_and_adds_other_qualifications_after_completing_the_section_spec.rb
  spec/system/candidate_interface/candidate_entering_other_qualification_spec.rb
  spec/system/candidate_interface/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/international/international_candidate_enters_their_other_qualification_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: Candidate

#2788 Stop applications with unavailable course options after Sep 7
  app/mailers/candidate_mailer.rb
  app/services/candidate_interface/end_of_cycle_policy.rb
  app/services/end_of_cycle_timetable.rb
  app/services/feature_flag.rb
  app/services/send_applications_to_provider.rb
  app/views/candidate_mailer/eoc_choice_unavailable_and_no_other_choices.text.erb
  app/views/candidate_mailer/eoc_choice_unavailable_and_still_waiting_on_other_choices.text.erb
  config/locales/application_states.yml
  config/locales/candidate_mailer.yml
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/candidate_interface/end_of_cycle_policy_spec.rb
  spec/services/end_of_cycle_timetable_spec.rb
  spec/system/candidate_interface/candidate_submits_application_to_unavailable_course_option_as_end_of_cycle_approaches_but_has_other_options_spec.rb
  spec/system/candidate_interface/candidate_submits_application_to_unavailable_course_option_as_end_of_cycle_approaches_spec.rb
Labels: Candidate

#2797 Add clock entry for automatically carrying over unsubmitted apps
  config/clock.rb
  spec/support_specs/clockwork_spec.rb
Labels: Candidate

#2794 Remove content about withdrawing from application dashboard
  app/components/candidate_interface/course_choices_review_component.html.erb
  config/locales/application_form.yml
  spec/components/candidate_interface/course_choices_review_component_spec.rb
Labels: Candidate, Content
