Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2020-07, with the labels that each got.

#2419 Remove redundant test
  spec/models/application_form_spec.rb
Labels: Core

#2420 Simplify database diagram
  .erdconfig
  README.md
  docs/domain-model.png
Labels: Core

#2408 Fix a cycle-related bug in GetApplicationChoicesForProviders
  app/queries/get_application_choices_for_providers.rb
  spec/queries/get_application_choices_for_providers_spec.rb
Labels: ProVendor

#2407 Return a validation error when vendors submit outlandish timestamps on the since param
  app/controllers/vendor_api/applications_controller.rb
  spec/requests/vendor_api/get_multiple_applications_spec.rb
  spec/support/vendor_api/vendor_api_spec_helpers.rb
Labels: ProVendor

#2402 Disallow UCAS data download in production
  app/controllers/support_interface/performance_controller.rb
  app/services/feature_flag.rb
  app/views/support_interface/performance/index.html.erb
  spec/system/support_interface/exporting_applications_for_ucas_spec.rb
Labels: Core

#2423 Remove gems-node-modules build trigger on new branch
  .github/workflows/run-gems-node-modules-build.yml
  azure-pipelines.yml
Labels: DevOps

#2390 Candidate journey tracking report (CSV download)
  app/controllers/support_interface/performance_controller.rb
  app/services/support_interface/candidate_journey_tracker.rb
  app/services/support_interface/candidate_journey_tracking_export.rb
  app/views/support_interface/performance/index.html.erb
  config/routes.rb
  spec/services/support_interface/candidate_journey_tracker_spec.rb
  spec/services/support_interface/candidate_journey_tracking_export_spec.rb
  spec/system/support_interface/application_choices_performance_spec.rb
Labels: Candidate

#2442 move pipeline files inside azure/ folder
  azure/pipelines/build-gems-node-modules.yml
  azure/pipelines/build.yml
  azure/pipelines/release.yml
  azure/pipelines/swap-slots.yml
  azure/pipelines/templates/cancel-build-if-not-latest.yml
  azure/pipelines/templates/deploy.yml
  azure/pipelines/templates/health-check.yml
  azure/pipelines/templates/metrics-check.yml
  azure/pipelines/templates/rspec-job.yml
  azure/pipelines/templates/run-rspec-test.yml
  azure/pipelines/templates/swap-staging-production-slots.yml
Labels: DevOps

#2443 fix deploy template path in release pipeline.
  azure/pipelines/release.yml
Labels: DevOps

#2441 Add text warning to withdraw offer confirmation page
  app/components/warning_text_component.html.erb
  app/components/warning_text_component.rb
  app/views/provider_interface/decisions/confirm_reject.html.erb
  app/views/provider_interface/decisions/confirm_withdraw_offer.html.erb
  app/views/support_interface/providers/courses.html.erb
  spec/components/warning_text_component_spec.rb
Labels: ProVendor

#2424 Content no conditions
  app/views/content/service_guidance_provider.md
  app/views/provider_interface/decisions/confirm_offer.html.erb
Labels: ProVendor

#2397 Content emails to providers edits and additions
  app/mailers/provider_mailer.rb
  app/views/layouts/provider_email_with_footer.text.erb
  app/views/provider_mailer/application_rejected_by_default.text.erb
  app/views/provider_mailer/application_submitted.text.erb
  app/views/provider_mailer/application_withdrawn.text.erb
  app/views/provider_mailer/chase_provider_decision.text.erb
  app/views/provider_mailer/declined.text.erb
  app/views/provider_mailer/declined_by_default.text.erb
  app/views/provider_mailer/offer_accepted.text.erb
  spec/mailers/previews/provider_mailer_preview.rb
Labels: ProVendor

#2444 trigger apply CI from if gems-node-modules is built from master
  azure/pipelines/build-gems-node-modules.yml
Labels: DevOps

#2435 Break personal details into separate pages
  app/components/candidate_interface/personal_details_review_component.rb
  app/controllers/candidate_interface/personal_details/base_controller.rb
  app/controllers/candidate_interface/personal_details/languages_controller.rb
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/controllers/candidate_interface/personal_details/review_controller.rb
  app/controllers/candidate_interface/personal_details_controller.rb
  app/forms/candidate_interface/languages_form.rb
  app/forms/candidate_interface/nationalities_form.rb
  app/forms/candidate_interface/personal_details_form.rb
  app/frontend/packs/nationality-autocomplete.js
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/views/candidate_interface/application_form/show.html.erb
  app/views/candidate_interface/personal_details/base/_shared_form.html.erb
  app/views/candidate_interface/personal_details/base/edit.html.erb
  app/views/candidate_interface/personal_details/base/new.html.erb
  app/views/candidate_interface/personal_details/edit.html.erb
  app/views/candidate_interface/personal_details/languages/_shared_form.html.erb
  app/views/candidate_interface/personal_details/languages/edit.html.erb
  app/views/candidate_interface/personal_details/languages/new.html.erb
  app/views/candidate_interface/personal_details/nationalities/_shared_form.html.erb
  app/views/candidate_interface/personal_details/nationalities/edit.html.erb
  app/views/candidate_interface/personal_details/nationalities/new.html.erb
  app/views/candidate_interface/personal_details/review/show.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/routes.rb
  spec/forms/candidate_interface/languages_form_spec.rb
  spec/forms/candidate_interface/nationalities_form_spec.rb
  spec/forms/candidate_interface/personal_details_form_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_personal_details_spec.rb
Labels: Candidate

#2448 remove assets:precompile command before running integration test
  Makefile
Labels: DevOps

#2426 Sort by reject by default date
  app/components/provider_interface/application_card_component.html.erb
  app/components/provider_interface/application_card_component.rb
  app/components/provider_interface/filter_component.html.erb
  app/components/provider_interface/filter_component.rb
  app/components/provider_interface/sort_order_component.html.erb
  app/components/provider_interface/sort_order_component.rb
  app/controllers/provider_interface/application_choices_controller.rb
  app/models/provider_interface/provider_applications_page_state.rb
  app/services/provider_interface/sort_application_choices.rb
  app/views/provider_interface/application_choices/index.html.erb
  spec/components/provider_interface/application_card_component_spec.rb
  spec/components/provider_interface/filter_component_spec.rb
  spec/components/provider_interface/sort_order_component_spec.rb
  spec/models/provider_interface/provider_applications_page_state_spec.rb
  spec/services/provider_interface/sort_application_choices_spec.rb
  spec/system/provider_interface/provider_applications_sort_spec.rb
Labels: ProVendor

#2461 remove github actions
  .github/workflows/tests.yml
Labels: DevOps

#2460 add timeout setting for rspec test runs
  azure/pipelines/templates/run-rspec-test.yml
Labels: DevOps

#2456 Validation error summary page
  app/controllers/support_interface/validation_errors_controller.rb
  app/queries/validation_error_summary_query.rb
  app/views/support_interface/performance/index.html.erb
  app/views/support_interface/validation_errors/summary.html.erb
  config/routes.rb
  spec/queries/validation_error_summary_query_spec.rb
  spec/system/support_interface/validation_errors_summary_spec.rb
Labels: Support

#2467 Merge "provider_add_provider_users" and "provider_make_decisions_restriction" flags
  app/controllers/provider_interface/provider_users_controller.rb
  app/models/navigation_items.rb
  app/services/feature_flag.rb
  app/services/offer_authorisation.rb
  app/views/provider_interface/provider_users/edit_providers.html.erb
  app/views/provider_interface/provider_users/index.html.erb
  app/views/provider_interface/start_page/show.html.erb
  spec/requests/provider_interface/managing_provider_users_spec.rb
  spec/requests/provider_interface/provider_relationship_permissions_request_spec.rb
  spec/services/make_an_offer_spec.rb
  spec/services/provider_authorisation_spec.rb
  spec/support/test_helpers/provider_user_permissions_helper.rb
  spec/system/provider_interface/manage_provider_user_permissions_spec.rb
  spec/system/provider_interface/provider_invites_user_spec.rb
  spec/system/provider_interface/providers_can_view_managed_users_spec.rb
  spec/system/provider_interface/removing_provider_user_spec.rb
Labels: ProVendor

#2466 Migration for international degrees
  db/migrate/20200708095213_add_international_degree_columns.rb
  db/schema.rb
  docs/domain-model.png
Labels: Core

#2474 Add initial navigation to English as a foreign language page
  app/controllers/candidate_interface/english_language/start_controller.rb
  app/models/application_form.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/application_form/show.html.erb
  app/views/candidate_interface/english_language/start/new.html.erb
  config/routes.rb
  db/migrate/20200708121600_add_efl_completed_to_application_form.rb
  db/schema.rb
  docs/domain-model.png
  spec/models/application_form_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/view_efl_form_spec.rb
Labels: Candidate

#2454 Remove old test data endpoint promote experimental endpoints
  app/controllers/vendor_api/test_data_controller.rb
  app/views/api_docs/pages/release_notes.md
  config/routes.rb
  config/vendor-api-experimental.yml
  config/vendor-api-v1.yml
  spec/lib/vendor_api_specification_spec.rb
  spec/requests/vendor_api/post_experimental_endpoints_moved_spec.rb
  spec/requests/vendor_api/post_test_data_clear_spec.rb
  spec/requests/vendor_api/post_test_data_generate_spec.rb
  spec/requests/vendor_api/post_test_data_regenerate_spec.rb
Labels: ProVendor

#2482 International degrees part 1 - modifications to degree type form
  app/controllers/candidate_interface/degrees/type_controller.rb
  app/forms/candidate_interface/degree_type_form.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/degrees/type/_form_fields.html.erb
  config/locales/application_form.yml
  spec/forms/candidate_interface/degree_type_form_spec.rb
  spec/system/candidate_interface/candidate_entering_international_degrees_spec.rb
Labels: Candidate

#2471 Fix link to chase_provider_decision email preview
  spec/mailers/previews/provider_mailer_preview.rb
Labels: Support

#2483 Add non-uk GCSEs columns to the application qualifications table
  db/migrate/20200710101438_add_non_uk_gcse_columnns_to_application_qualification.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#2481 Remove manual check from deployment.md
  docs/deployment.md
Labels: Core

#2487 Add IELTS flow to English as a foreign language section
  app/controllers/candidate_interface/english_foreign_language/ielts_controller.rb
  app/controllers/candidate_interface/english_foreign_language/review_controller.rb
  app/controllers/candidate_interface/english_foreign_language/start_controller.rb
  app/controllers/candidate_interface/english_foreign_language/type_controller.rb
  app/controllers/candidate_interface/english_language/start_controller.rb
  app/forms/candidate_interface/english_foreign_language/ielts_form.rb
  app/forms/candidate_interface/english_foreign_language/start_form.rb
  app/forms/candidate_interface/english_foreign_language/type_form.rb
  app/models/application_form.rb
  app/models/english_language_proficiency.rb
  app/models/ielts_qualification.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/english_foreign_language/ielts/new.html.erb
  app/views/candidate_interface/english_foreign_language/review/show.html.erb
  app/views/candidate_interface/english_foreign_language/start/new.html.erb
  app/views/candidate_interface/english_foreign_language/type/new.html.erb
  app/views/candidate_interface/english_language/start/new.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200709153902_create_english_language_proficiencies.rb
  db/migrate/20200709154207_create_ielts_qualifications.rb
  db/migrate/20200710113941_add_qualification_status_to_english_language_proficiencies.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/forms/candidate_interface/english_foreign_language/ielts_form_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/add_ielts_qualification_spec.rb
Labels: Candidate

#2485 Add non-uk qualifications to the GCSE type page
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/controllers/candidate_interface/gcse/type_controller.rb
  app/forms/candidate_interface/gcse_qualification_type_form.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/gcse/type/edit.html.erb
  config/locales/application_form.yml
  spec/forms/candidate_interface/gcse_qualification_type_form_spec.rb
  spec/system/candidate_interface/candidate_entering_international_gcse_spec.rb
Labels: Candidate

#2486 add support for multiple custom domain bindings in App Service Template
  azure/containers.json
  azure/pipelines/build.yml
  azure/pipelines/release.yml
  azure/pipelines/templates/deploy.yml
  azure/template.json
Labels: DevOps

#2493 middleware to redirect education to service.gov.uk
  README.md
  adr/0012-extra-security-for-support.md
  app/controllers/candidate_interface/apply_from_find_controller.rb
  app/middlewares/redirect_to_service_gov_uk_middleware.rb
  app/models/provider_emails_for_application_choices.rb
  app/views/api_docs/pages/alpha_release_notes.md
  app/views/api_docs/pages/home.md
  app/views/api_docs/reference/reference.html.erb
  app/views/candidate_interface/apply_from_find/not_found.html.erb
  app/views/candidate_interface/course_choices/replace_choices/decision/contact_support.html.erb
  app/views/candidate_interface/course_choices/shared/_go_to_find.html.erb
  app/views/content/sandbox.html.erb
  app/views/content/service_guidance_provider.md
  azure/containers.json
  config/application.rb
  config/vendor-api-v1.yml
  db/migrate/20200211141124_add_replacement_to_references.rb
  lib/tasks/local_dev.rake
  spec/models/provider_emails_for_application_choices_spec.rb
  spec/requests/redirect_to_service_gov_uk_spec.rb
  spec/system/candidate_interface/candidate_does_not_know_where_they_want_to_apply_spec.rb
Labels: Core, DevOps

#2479 Remove cucumber and tests
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Makefile
  azure/pipelines/build.yml
  config/cucumber.yml
  features/reject_by_default.feature
  features/step_definitions/application_steps.rb
  features/submitting_references.feature
  features/successful_application_statuses.feature
  features/support/env.rb
  lib/tasks/cucumber.rake
  lib/tasks/testing.rake
  script/cucumber
  spec/services/set_reject_by_default_spec.rb
Labels: Core

#2494 Persist filter state across requests
  app/controllers/provider_interface/application_choices_controller.rb
  app/models/provider_interface/provider_applications_page_state.rb
  spec/components/provider_interface/filter_component_spec.rb
  spec/components/provider_interface/sort_order_component_spec.rb
  spec/models/provider_interface/provider_applications_page_state_spec.rb
Labels: ProVendor

#2503 UCAS upload: timestamp format and baseurl/folder env vars
  .env.example
  .env.test
  app/services/ucas_matching/ucas_api.rb
  app/services/ucas_matching/upload_matching_data.rb
  azure/pipelines/templates/deploy.yml
  azure/template.json
  docker-compose.azure.yml
Labels: ProVendor

#2497 International degrees part 2 - NARIC statement form and minor changes
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/controllers/candidate_interface/degrees/naric_statement_controller.rb
  app/forms/candidate_interface/degree_institution_form.rb
  app/forms/candidate_interface/degree_naric_statement_form.rb
  app/forms/candidate_interface/degree_subject_form.rb
  app/frontend/packs/application.js
  app/frontend/packs/degree-institution-country-autocomplete.js
  app/models/application_qualification.rb
  app/views/candidate_interface/degrees/institution/_form_fields.html.erb
  app/views/candidate_interface/degrees/naric_statement/_form_fields.html.erb
  app/views/candidate_interface/degrees/naric_statement/edit.html.erb
  app/views/candidate_interface/degrees/naric_statement/new.html.erb
  app/views/candidate_interface/degrees/subject/_form_fields.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/routes.rb
  spec/forms/candidate_interface/degree_institution_form_spec.rb
  spec/forms/candidate_interface/degree_naric_statement_form_spec.rb
  spec/system/candidate_interface/candidate_entering_international_degrees_spec.rb
Labels: Candidate

#2502 Add EFL review components
  app/components/ielts_review_component.html.erb
  app/components/ielts_review_component.rb
  app/components/toefl_review_component.html.erb
  app/components/toefl_review_component.rb
  app/controllers/candidate_interface/english_foreign_language/review_controller.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/application_form/show.html.erb
  app/views/candidate_interface/english_foreign_language/review/show.html.erb
  config/routes.rb
  spec/components/ielts_review_component_spec.rb
  spec/components/toefl_review_component_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/add_ielts_qualification_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/add_toefl_qualification_spec.rb
Labels: Candidate

#2504 Rename EnglishLanguageProficiency model
  app/controllers/candidate_interface/english_foreign_language/review_controller.rb
  app/forms/candidate_interface/english_foreign_language/ielts_form.rb
  app/forms/candidate_interface/english_foreign_language/toefl_form.rb
  app/models/application_form.rb
  app/models/english_proficiency.rb
  app/models/ielts_qualification.rb
  app/models/toefl_qualification.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  db/migrate/20200714112945_rename_english_language_proficiency.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/forms/candidate_interface/english_foreign_language/ielts_form_spec.rb
  spec/forms/candidate_interface/english_foreign_language/toefl_form_spec.rb
Labels: Candidate

#2511 Missing link classes
  app/components/provider_interface/reference_with_feedback_component.rb
  app/lib/hosting_environment.rb
Labels: Core

#2464 Generate fake providers with courses in the sandbox
  app/controllers/support_interface/tasks_controller.rb
  app/services/generate_fake_provider.rb
  app/services/generate_vendor_providers.rb
  app/views/support_interface/tasks/create_fake_provider.html.erb
  app/views/support_interface/tasks/index.html.erb
  config/routes.rb
  spec/services/generate_fake_provider_spec.rb
  spec/services/generate_vendor_providers_spec.rb
  spec/system/support_interface/tasks_spec.rb
Labels: ProVendor, Sandbox

#2516 Add jest back in build process
  Dockerfile
  azure/pipelines/build.yml
Labels: Core

#2512 Content service guidance
  app/views/content/service_guidance_provider.md
Labels: ProVendor

#2519 Catch MessageVerifier::InvalidSignature errors in Encryptor
  app/services/encryptor.rb
  spec/services/encryptor_spec.rb
Labels: Core

#2520 Use a single model per set of ProviderRelationshipPermissions
  app/components/provider_relationship_permissions_list.html.erb
  app/components/provider_relationship_permissions_list.rb
  app/controllers/provider_interface/organisations_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/provider_interface/provider_relationship_permissions_controller.rb
  app/forms/provider_interface/provider_relationship_permissions_form.rb
  app/models/provider.rb
  app/models/provider_relationship_permissions.rb
  app/models/provider_relationship_permissions_pair.rb
  app/models/ratifying_provider_permissions.rb
  app/models/training_provider_permissions.rb
  app/services/offer_authorisation.rb
  app/services/provider_authorisation.rb
  app/services/provider_setup.rb
  app/services/sync_provider_from_find.rb
  app/views/provider_interface/organisations/show.html.erb
  app/views/provider_interface/provider_relationship_permissions/_provider_permissions.html.erb
  app/views/provider_interface/provider_relationship_permissions/confirm.html.erb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
  app/views/provider_interface/provider_relationship_permissions/setup.html.erb
  app/views/provider_interface/provider_relationship_permissions/success.html.erb
  db/migrate/20200709073219_add_permissions_to_table.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/forms/provider_interface/provider_relationship_permissions_form_spec.rb
  spec/models/navigation_items_spec.rb
  spec/models/provider_relationship_permissions_pair_spec.rb
  spec/models/provider_spec.rb
  spec/requests/provider_interface/provider_relationship_permissions_request_spec.rb
  spec/requests/provider_interface/provider_relationship_permissions_setup_spec.rb
  spec/requests/provider_interface/see_organisations_pages_spec.rb
  spec/services/provider_authorisation_spec.rb
  spec/services/provider_setup_spec.rb
  spec/services/sync_provider_from_find_spec.rb
  spec/support/test_helpers/provider_relationship_permissions_helper.rb
  spec/system/provider_interface/manage_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/provider_cannot_respond_to_application_spec.rb
  spec/system/provider_interface/provider_responds_to_application_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
  spec/system/provider_interface/setup_provider_relationship_permissions_spec.rb
Labels: ProVendor

#2510 Change provider footer
  app/views/layouts/_footer_meta_provider.html.erb
  config/locales/en.yml
Labels: ProVendor

#2500 International degrees part 3 - Review component and changes to grades form
  app/components/candidate_interface/degrees_review_component.rb
  app/controllers/candidate_interface/degrees/grade_controller.rb
  app/forms/candidate_interface/degree_grade_form.rb
  app/frontend/packs/degree-institution-country-autocomplete.js
  app/views/candidate_interface/degrees/grade/_form_fields.html.erb
  app/views/candidate_interface/degrees/institution/_form_fields.html.erb
  app/views/candidate_interface/degrees/naric_statement/edit.html.erb
  config/locales/application_form.yml
  spec/components/candidate_interface/degrees_review_component_spec.rb
  spec/system/candidate_interface/candidate_entering_international_degrees_spec.rb
Labels: Candidate

#2532 Fix international address label
  app/views/candidate_interface/contact_details/address/edit.html.erb
  config/locales/application_form.yml
  spec/system/candidate_interface/candidate_entering_contact_details_spec.rb
Labels: Candidate

#2484 Zip the file we're sending to UCAS
  .env.example
  .env.test
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/services/ucas_matching/matching_data_file.rb
  app/services/ucas_matching/upload_matching_data.rb
  azure/pipelines/build.yml
  azure/pipelines/release.yml
  azure/pipelines/templates/deploy.yml
  azure/template.json
  docker-compose.azure.yml
  spec/system/ucas_matching/upload_matching_data_to_ucas_spec.rb
Labels: Core

#2531 arm templates to create event hubs & logic app
  azure/eventhubs-logic-app.json
  azure/eventhubs.json
  azure/pipelines/templates/deploy.yml
  azure/template.json
Labels: DevOps

#2527 Add the two-level header to Manage (v2)
  app/components/header_component.html.erb
  app/components/phase_banner.html.erb
  app/components/phase_banner.rb
  app/components/provider_interface/header_component.html.erb
  app/components/provider_interface/primary_navigation.html.erb
  app/components/provider_interface/primary_navigation.rb
  app/frontend/styles/_phase-banner.scss
  app/frontend/styles/application.scss
  app/models/navigation_items.rb
  app/views/layouts/_header.html.erb
  spec/models/navigation_items_spec.rb
  spec/system/provider_interface/see_applications_spec.rb
Labels: ProVendor

#2523 Provider user invitation wizard - part 1
  app/controllers/provider_interface/provider_users_invitations_controller.rb
  app/forms/provider_interface/provider_user_invitation_wizard.rb
  app/forms/provider_interface/provider_user_permissions_form.rb
  app/views/provider_interface/provider_users/index.html.erb
  app/views/provider_interface/provider_users_invitations/check.html.erb
  app/views/provider_interface/provider_users_invitations/edit_details.html.erb
  app/views/provider_interface/provider_users_invitations/edit_permissions.html.erb
  app/views/provider_interface/provider_users_invitations/edit_providers.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/forms/provider_interface/provider_user_invitation_wizard_spec.rb
  spec/system/provider_interface/provider_invites_user_with_new_wizard_spec.rb
Labels: ProVendor

#2446 Add International candidates nationalities page
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/forms/candidate_interface/nationalities_form.rb
  app/frontend/packs/nationality-autocomplete.js
  app/models/application_form.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/views/candidate_interface/personal_details/nationalities/_shared_form.html.erb
  config/locales/application_form.yml
  spec/forms/candidate_interface/nationalities_form_spec.rb
  spec/models/application_form_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/system/candidate_interface/international_candidate_enters_their_personal_details_spec.rb
Labels: Candidate

#2533 Update permissions display on organisations show page
  app/components/provider_relationship_permissions_list.html.erb
  app/components/provider_relationship_permissions_list.rb
  app/models/provider_relationship_permissions.rb
  app/views/provider_interface/organisations/show.html.erb
  spec/components/provider_relationship_permissions_list_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
Labels: ProVendor

#2499 Add country to international GCSE flow
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/controllers/candidate_interface/gcse/institution_country_controller.rb
  app/controllers/candidate_interface/gcse/type_controller.rb
  app/forms/candidate_interface/gcse_institution_country_form.rb
  app/frontend/packs/nationality-autocomplete.js
  app/helpers/select_options_helper.rb
  app/views/candidate_interface/gcse/institution_country/edit.html.erb
  config/initializers/countries.rb
  config/locales/application_form.yml
  config/locales/gcse_details.yml
  config/routes.rb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/forms/candidate_interface/gcse_institution_country_form_spec.rb
  spec/system/candidate_interface/candidate_entering_international_gcse_spec.rb
Labels: Candidate

#2478 Add international contacts right to work page
  app/components/candidate_interface/personal_details_review_component.rb
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/controllers/candidate_interface/personal_details/review_controller.rb
  app/controllers/candidate_interface/personal_details/right_to_work_or_study_controller.rb
  app/forms/candidate_interface/nationalities_form.rb
  app/forms/candidate_interface/right_to_work_or_study_form.rb
  app/models/application_form.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/views/candidate_interface/personal_details/right_to_work_or_study/_shared_form.html.erb
  app/views/candidate_interface/personal_details/right_to_work_or_study/edit.html.erb
  app/views/candidate_interface/personal_details/right_to_work_or_study/new.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/routes.rb
  spec/forms/candidate_interface/nationalities_form_spec.rb
  spec/forms/candidate_interface/right_to_work_or_study_form_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/support/test_helpers/efl_helper.rb
  spec/system/candidate_interface/english_as_a_foreign_language/view_efl_form_spec.rb
  spec/system/candidate_interface/international_candidate_enters_their_personal_details_spec.rb
Labels: Candidate

#2521 Add international GCSE grade page
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/controllers/candidate_interface/gcse/details_controller.rb
  app/controllers/candidate_interface/gcse/grade_controller.rb
  app/forms/candidate_interface/gcse_qualification_details_form.rb
  app/models/application_qualification.rb
  app/views/candidate_interface/gcse/grade/edit.html.erb
  config/locales/application_form.yml
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/forms/candidate_interface/gcse_qualification_details_form_spec.rb
  spec/models/application_qualification_spec.rb
  spec/system/candidate_interface/candidate_entering_gcse_spec.rb
  spec/system/candidate_interface/candidate_entering_international_gcse_spec.rb
Labels: Candidate

#2541 Provider user invitation wizard - part 2 - Saving new users
  app/controllers/provider_interface/provider_users_invitations_controller.rb
  app/forms/provider_interface/provider_user_invitation_wizard.rb
  app/services/invite_provider_user.rb
  app/services/provider_interface/save_provider_user_service.rb
  spec/forms/provider_interface/provider_user_invitation_wizard_spec.rb
  spec/services/invite_provider_user_spec.rb
  spec/services/provider_interface/save_provider_user_service_spec.rb
  spec/system/provider_interface/provider_invites_user_with_new_wizard_spec.rb
Labels: ProVendor

#2524 Add EFL 'No qualification' options
  app/components/no_efl_qualification_review_component.html.erb
  app/components/no_efl_qualification_review_component.rb
  app/controllers/candidate_interface/english_foreign_language/review_controller.rb
  app/controllers/candidate_interface/english_foreign_language/start_controller.rb
  app/forms/candidate_interface/english_foreign_language/ielts_form.rb
  app/forms/candidate_interface/english_foreign_language/start_form.rb
  app/forms/candidate_interface/english_foreign_language/toefl_form.rb
  app/models/english_proficiency.rb
  app/services/candidate_interface/update_english_proficiency.rb
  app/views/candidate_interface/english_foreign_language/start/new.html.erb
  db/migrate/20200714184239_add_no_qualification_details_to_english_proficiencies.rb
  db/schema.rb
  docs/domain-model.png
  spec/components/no_efl_qualification_review_component_spec.rb
  spec/factories.rb
  spec/forms/candidate_interface/english_foreign_language/ielts_form_spec.rb
  spec/forms/candidate_interface/english_foreign_language/start_form_spec.rb
  spec/forms/candidate_interface/english_foreign_language/toefl_form_spec.rb
  spec/services/candidate_interface/update_english_proficiency_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/declare_no_qualification_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/declare_qualification_not_needed_spec.rb
Labels: Candidate

#2525 Refactor ChooseEflReviewComponent and MissingApplicationFormError
  app/controllers/candidate_interface/english_foreign_language/review_controller.rb
  app/forms/candidate_interface/english_foreign_language/ielts_form.rb
  app/forms/candidate_interface/english_foreign_language/missing_application_form_error.rb
  app/forms/candidate_interface/english_foreign_language/start_form.rb
  app/forms/candidate_interface/english_foreign_language/toefl_form.rb
  app/services/candidate_interface/choose_efl_review_component.rb
  spec/forms/candidate_interface/english_foreign_language/start_form_spec.rb
  spec/services/candidate_interface/choose_efl_review_component_spec.rb
Labels: Candidate

#2528 Add 'Other' qualifications to EFL section
  app/components/other_efl_qualification_review_component.html.erb
  app/components/other_efl_qualification_review_component.rb
  app/controllers/candidate_interface/english_foreign_language/other_efl_qualification_controller.rb
  app/forms/candidate_interface/english_foreign_language/other_efl_qualification_form.rb
  app/forms/candidate_interface/english_foreign_language/type_form.rb
  app/models/other_efl_qualification.rb
  app/services/candidate_interface/choose_efl_review_component.rb
  app/views/candidate_interface/english_foreign_language/other_efl_qualification/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/other_efl_qualification/edit.html.erb
  app/views/candidate_interface/english_foreign_language/other_efl_qualification/new.html.erb
  app/views/candidate_interface/english_foreign_language/type/new.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200717110837_create_other_efl_qualifications.rb
  db/schema.rb
  docs/domain-model.png
  spec/components/other_efl_qualification_review_component_spec.rb
  spec/factories.rb
  spec/forms/candidate_interface/english_foreign_language/other_efl_qualification_form_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/add_other_qualification_spec.rb
Labels: Candidate

#2542 Update GenerateTestApplications with full courses
  app/lib/test_applications.rb
  app/workers/generate_test_applications.rb
  spec/workers/generate_test_applications_spec.rb
Labels: Core

#2535 English as a Foreign Language UI improvements
  app/controllers/candidate_interface/english_foreign_language/efl_root_concern.rb
  app/controllers/candidate_interface/english_foreign_language/ielts_controller.rb
  app/controllers/candidate_interface/english_foreign_language/other_efl_qualification_controller.rb
  app/controllers/candidate_interface/english_foreign_language/review_controller.rb
  app/controllers/candidate_interface/english_foreign_language/toefl_controller.rb
  app/forms/candidate_interface/english_foreign_language/ielts_form.rb
  app/forms/candidate_interface/english_foreign_language/other_efl_qualification_form.rb
  app/forms/candidate_interface/english_foreign_language/toefl_form.rb
  app/frontend/packs/application.js
  app/frontend/packs/ielts-band-score-autocomplete.js
  app/models/ielts_qualification.rb
  app/views/candidate_interface/english_foreign_language/ielts/_form_fields.html.erb
  spec/system/candidate_interface/english_as_a_foreign_language/add_ielts_qualification_spec.rb
Labels: Candidate

#2543 Centralise `can_manage_users?` permission
  app/controllers/provider_interface/provider_users_controller.rb
  app/controllers/provider_interface/provider_users_invitations_controller.rb
  app/models/navigation_items.rb
  app/models/provider_user.rb
  app/services/provider_authorisation.rb
  spec/models/provider_user_spec.rb
  spec/queries/get_all_change_options_from_offered_option_spec.rb
  spec/services/provider_authorisation_spec.rb
Labels: ProVendor

#2556 Modification of content on the becoming_a_teacher edit view
  app/views/candidate_interface/personal_statement/becoming_a_teacher/edit.html.erb
Labels: Candidate

#2553 Centralise query to figure out providers that the user has `manage_users` permissions for
  app/models/provider_permissions.rb
  app/models/provider_user.rb
  app/services/provider_authorisation.rb
  app/services/remove_provider_user.rb
  spec/services/save_provider_user_spec.rb
Labels: ProVendor

#2558 Add provider-provider permissions to permissions list component
  app/components/permissions_list.html.erb
  app/components/permissions_list.rb
  spec/components/permissions_list_component_spec.rb
Labels: ProVendor

#2549 Update the nationalities section in personal details to use the new design (non JS)
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/forms/candidate_interface/nationalities_form.rb
  app/frontend/packs/nationality-autocomplete.js
  app/models/application_form.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/services/candidate_interface/get_nationalities_form_hash.rb
  app/views/candidate_interface/personal_details/nationalities/_shared_form.html.erb
  config/locales/application_form.yml
  db/migrate/20200721125644_add_additional_nationalities_columns.rb
  db/schema.rb
  spec/forms/candidate_interface/nationalities_form_spec.rb
  spec/models/application_form_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/services/candidate_interface/get_nationalities_form_hash_spec.rb
  spec/system/candidate_interface/international_candidate_enters_their_personal_details_spec.rb
Labels: Candidate

#2530 Add provider-specific edit user permissions flow to provider_interface
  app/components/provider_interface/edit_provider_user_permissions_component.html.erb
  app/components/provider_interface/edit_provider_user_permissions_component.rb
  app/components/provider_interface/provider_user_details_component.rb
  app/controllers/provider_interface/provider_users_controller.rb
  app/controllers/provider_interface/provider_users_invitations_controller.rb
  app/forms/provider_interface/provider_user_permissions_form.rb
  app/services/provider_authorisation.rb
  app/views/provider_interface/provider_users/edit_permissions.html.erb
  app/views/provider_interface/provider_users_invitations/edit_permissions.html.erb
  config/routes.rb
  spec/components/previews/provider_interface/edit_provider_user_permissions_component_preview.rb
  spec/forms/provider_interface/provider_user_permissions_form_spec.rb
  spec/requests/provider_interface/managing_provider_users_spec.rb
  spec/system/provider_interface/manage_provider_user_permissions_spec.rb
  spec/system/provider_interface/provider_invites_user_with_new_wizard_spec.rb
Labels: ProVendor

#2563 Remove dependency on `rollout` gem
  Gemfile
  Gemfile.lock
  app/services/feature_flag_migrator.rb
  db/migrate/20200514152945_migrate_feature_flags_from_redis_to_pg.rb
  spec/services/feature_flag_migrator_spec.rb
Labels: Core

#2557 Implement separate page for editing providers
  app/components/provider_interface/provider_user_details_component.rb
  app/controllers/provider_interface/provider_users_controller.rb
  app/forms/provider_interface/provider_user_providers_form.rb
  app/views/provider_interface/provider_users/edit_providers.html.erb
  app/views/provider_interface/provider_users/show.html.erb
  spec/forms/provider_interface/provider_user_providers_form_spec.rb
  spec/requests/provider_interface/managing_provider_users_spec.rb
  spec/system/provider_interface/manage_provider_user_permissions_spec.rb
  spec/system/provider_interface/manage_provider_user_providers_spec.rb
Labels: ProVendor

#2560 Small fixes for the permissions interface
  app/views/provider_interface/provider_users/confirm_remove.html.erb
  app/views/provider_interface/provider_users/index.html.erb
Labels: Support

#2561 Don't show users providers whose relationships they can't manage
  app/controllers/provider_interface/organisations_controller.rb
  app/models/navigation_items.rb
  app/models/provider.rb
  app/services/provider_authorisation.rb
  spec/models/provider_spec.rb
  spec/requests/provider_interface/see_organisations_pages_spec.rb
  spec/services/provider_authorisation_spec.rb
Labels: ProVendor

#2566 use sslmod=require for database connection
  config/database.yml
Labels: Core

#2567 Add provider-provider permissions to the edit page
  app/components/provider_interface/edit_provider_user_permissions_component.html.erb
  app/components/provider_interface/edit_provider_user_permissions_component.rb
Labels: ProVendor

#2539 Add more logging for UCAS Sync
  app/services/ucas_matching/matching_data_file.rb
  app/services/ucas_matching/upload_matching_data.rb
Labels: Core

#2529 Fix course replacement bug
  app/controllers/candidate_interface/course_choices/replace_choices/course_selection_controller.rb
  app/controllers/candidate_interface/course_choices/replace_choices/study_mode_selection_controller.rb
  spec/system/candidate_interface/course_selection/candidate_can_replace_full_or_withdrawn_course_choices_spec.rb
Labels: Candidate

#2572 Add code for launching `make_decisions` and `manage_users`
  app/workers/launch_make_decisions_and_manage_users.rb
  db/migrate/20200723160935_give_make_decisions_and_manage_users_to_provider_users.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/workers/launch_make_decisions_and_manage_users_spec.rb
Labels: ProVendor

#2574 Update ApplicationForm#english_speaking_nationality?
  app/models/application_form.rb
  spec/models/application_form_spec.rb
Labels: Candidate

#2562 Update content on content providers view
  app/views/candidate_interface/content/providers.html.erb
  config/locales/en.yml
Labels: Candidate

#2571 Reintroduce Languages to international_personal_details flow
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/controllers/candidate_interface/personal_details/review_controller.rb
  app/controllers/candidate_interface/personal_details/right_to_work_or_study_controller.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/views/candidate_interface/application_form/show.html.erb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/support/test_helpers/efl_helper.rb
  spec/system/candidate_interface/english_as_a_foreign_language/view_efl_form_spec.rb
  spec/system/candidate_interface/international_candidate_enters_their_personal_details_spec.rb
Labels: Candidate

#2568 Refactor content on Choosing your courses page
  app/views/candidate_interface/application_choices/_guidance.html.erb
Labels: Candidate

#2573 Simplify changed_offer email
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/changed_offer.text.erb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
Labels: Candidate

#2547 Implement new checkbox structure for managing provider level permissions
  app/components/provider_relationship_permissions_list.html.erb
  app/controllers/provider_interface/provider_relationship_permissions_controller.rb
  app/forms/provider_interface/provider_relationship_permissions_form.rb
  app/models/provider_relationship_permissions.rb
  app/views/provider_interface/organisations/show.html.erb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
  config/locales/permissions.yml
  config/routes.rb
  spec/factories.rb
  spec/forms/provider_interface/provider_relationship_permissions_form_spec.rb
  spec/models/provider_relationship_permissions_spec.rb
  spec/requests/provider_interface/provider_relationship_permissions_request_spec.rb
  spec/services/provider_authorisation_spec.rb
  spec/system/provider_interface/manage_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/provider_cannot_respond_to_application_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
Labels: ProVendor

#2555 Provider user invitation wizard - part 3 - check page
  app/components/provider_interface/provider_user_invitation_details_component.html.erb
  app/components/provider_interface/provider_user_invitation_details_component.rb
  app/components/provider_interface/provider_user_invitation_permissions_component.html.erb
  app/components/provider_interface/provider_user_invitation_permissions_component.rb
  app/controllers/provider_interface/provider_users_invitations_controller.rb
  app/forms/provider_interface/provider_user_invitation_wizard.rb
  app/services/provider_interface/save_provider_user_service.rb
  app/views/provider_interface/provider_users/index.html.erb
  app/views/provider_interface/provider_users_invitations/check.html.erb
  app/views/provider_interface/provider_users_invitations/edit_permissions.html.erb
  config/locales/en.yml
  spec/components/provider_interface/provider_user_invitation_details_component_spec.rb
  spec/forms/provider_interface/provider_user_invitation_wizard_spec.rb
  spec/services/provider_interface/save_provider_user_service_spec.rb
  spec/system/provider_interface/provider_invites_user_spec.rb
  spec/system/provider_interface/provider_invites_user_with_new_wizard_spec.rb
  spec/system/provider_interface/removing_provider_user_spec.rb
Labels: ProVendor

#2585 Hide Languages section of Personal Details when EFL is active
  app/components/candidate_interface/personal_details_review_component.rb
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/controllers/candidate_interface/personal_details/review_controller.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/services/languages_section_policy.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/services/languages_section_policy_spec.rb
  spec/system/candidate_interface/candidate_entering_personal_details_when_languages_hidden_spec.rb
Labels: Candidate

#2584 Bug fix on referees controller to flow back to app if choice is deleted
  app/controllers/candidate_interface/referees_controller.rb
Labels: Candidate

#2578 Content welcome email
  app/views/provider_mailer/account_created.text.erb
Labels: ProVendor

#2569 Update content when a provider can only view applications
  app/components/provider_relationship_permissions_list.html.erb
  app/components/provider_relationship_permissions_list.rb
  spec/components/provider_relationship_permissions_list_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
Labels: ProVendor

#2596 Fix bug when hiding Languages page
  app/controllers/candidate_interface/personal_details/right_to_work_or_study_controller.rb
  spec/system/candidate_interface/candidate_entering_personal_details_when_languages_hidden_spec.rb
Labels: Candidate

#2597 mount local dev folder as container's working directory
  docker-compose.override.yml
  docker-compose.yml
Labels: DevOps

#2582 Provider end of cycle comms page
  app/controllers/provider_interface/content_controller.rb
  app/services/feature_flag.rb
  app/views/content/getting_ready_for_next_cycle.md
  app/views/provider_interface/application_choices/index.html.erb
  app/views/provider_interface/start_page/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/provider_interface/providers_can_view_end_of_cycle_comms_spec.rb
Labels: ProVendor

#2593 Remove duplicated org relationships on the organisations show page
  app/controllers/provider_interface/organisations_controller.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
Labels: ProVendor

#2604 Use /provider/users path for all provider users routes
  app/components/provider_interface/edit_provider_user_permissions_component.html.erb
  app/controllers/provider_interface/provider_users_controller.rb
  app/views/provider_interface/provider_users/edit_providers.html.erb
  app/views/provider_interface/provider_users/new.html.erb
  config/routes.rb
Labels: ProVendor

#2600 Fix UX inconsistencies around ProviderUsers
  app/components/permissions_list.html.erb
  app/components/permissions_list.rb
  app/components/provider_interface/edit_provider_user_permissions_component.html.erb
  app/components/provider_interface/provider_account_component.html.erb
  app/components/provider_interface/provider_account_component.rb
  app/components/provider_interface/provider_user_details_component.rb
  app/components/provider_interface/provider_user_invitation_details_component.rb
  app/components/provider_interface/provider_user_invitation_permissions_component.html.erb
  app/components/provider_interface/provider_user_invitation_permissions_component.rb
  app/components/provider_interface/user_details_organisations_list.html.erb
  app/components/provider_interface/user_details_organisations_list.rb
  app/components/support_interface/provider_users_table_component.html.erb
  app/forms/provider_interface/provider_user_providers_form.rb
  app/views/provider_interface/provider_users/edit_providers.html.erb
  app/views/provider_interface/provider_users_invitations/edit_details.html.erb
  app/views/provider_interface/provider_users_invitations/edit_permissions.html.erb
  app/views/provider_interface/provider_users_invitations/edit_providers.html.erb
  app/views/support_interface/provider_users/_provider_options.html.erb
  config/locales/en.yml
  spec/components/permissions_list_component_spec.rb
  spec/components/provider_interface/provider_account_component_spec.rb
  spec/system/provider_interface/manage_provider_user_permissions_spec.rb
  spec/system/provider_interface/manage_provider_user_providers_spec.rb
  spec/system/provider_interface/provider_invites_user_with_new_wizard_spec.rb
  spec/system/provider_interface/providers_can_view_managed_users_spec.rb
  spec/system/support_interface/managing_provider_users_spec.rb
Labels: ProVendor

#2609 Create 'open on apply' courses and course options for fake sandbox provider
  app/services/generate_fake_provider.rb
  spec/factories.rb
  spec/services/generate_fake_provider_spec.rb
Labels: ProVendor

#2590 Prevent audit trail errors if provider_id cannot be found for permission updates
  app/components/support_interface/audit_trail_item_component.rb
  spec/components/support_interface/audit_trail_item_component_spec.rb
Labels: ProVendor

#2606 Support the single provider journey through the invite provider user wizard
  app/components/provider_interface/provider_user_invitation_details_component.rb
  app/controllers/provider_interface/provider_users_invitations_controller.rb
  app/forms/provider_interface/provider_user_invitation_wizard.rb
  app/views/provider_interface/provider_users_invitations/edit_permissions.html.erb
  spec/components/provider_interface/provider_user_invitation_details_component_spec.rb
  spec/forms/provider_interface/provider_user_invitation_wizard_spec.rb
Labels: ProVendor

#2608 Other qualifications: Add non-uk qualification creation
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/controllers/candidate_interface/other_qualifications/type_controller.rb
  app/forms/candidate_interface/other_qualification_form.rb
  app/forms/candidate_interface/other_qualification_type_form.rb
  app/frontend/packs/nationality-autocomplete.js
  app/services/feature_flag.rb
  app/views/candidate_interface/other_qualifications/details/new.html.erb
  app/views/candidate_interface/other_qualifications/type/new.html.erb
  config/locales/application_form.yml
  spec/components/candidate_interface/other_qualifications_review_component_spec.rb
  spec/forms/candidate_interface/other_qualification_form_spec.rb
  spec/forms/candidate_interface/other_qualification_type_form_spec.rb
  spec/system/candidate_interface/international_candidate_enters_their_other_qualification_spec.rb
Labels: Candidate

#2599 Present new EFL qualification data in Manage and on the API
  app/forms/candidate_interface/languages_form.rb
  app/models/application_form.rb
  app/models/english_proficiency.rb
  app/models/ielts_qualification.rb
  app/models/toefl_qualification.rb
  app/services/languages_section_policy.rb
  spec/forms/candidate_interface/languages_form_spec.rb
  spec/models/application_form_spec.rb
  spec/models/english_proficiency_spec.rb
  spec/system/candidate_interface/candidate_entering_personal_details_when_languages_hidden_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: Candidate

#2616 Update error handling when editing provider permissions
  app/controllers/provider_interface/provider_relationship_permissions_controller.rb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
Labels: ProVendor

#2607 Add breadcrumb for Apply again candidates in support
  app/views/support_interface/application_forms/show.html.erb
  app/views/support_interface/candidates/show.html.erb
Labels: Candidate

#2619 Swap to using smart quotes in error messages
  config/locales/en.yml
  spec/system/provider_interface/provider_invites_user_with_new_wizard_spec.rb
Labels: Core

#2613 Check EFL section on application submit
  app/models/application_form.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/application_form/_review.html.erb
  config/locales/review_application.yml
  spec/factories.rb
  spec/models/application_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_reviewing_an_incomplete_application_spec.rb
  spec/system/candidate_interface/candidate_submits_application_with_full_course_location_spec.rb
  spec/system/candidate_interface/candidate_submits_application_with_full_course_study_mode_spec.rb
  spec/system/candidate_interface/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/international/candidate_entering_contact_details_without_international_addresses_spec.rb
  spec/system/candidate_interface/international/candidate_entering_international_degrees_spec.rb
  spec/system/candidate_interface/international/candidate_entering_international_gcse_spec.rb
  spec/system/candidate_interface/international/international_candidate_enters_their_personal_details_spec.rb
  spec/system/candidate_interface/international/international_candidate_submitting_application_spec.rb
Labels: Candidate

#2620 Fix year validation in WorkExperienceForm
  app/helpers/date_validation_helper.rb
  spec/forms/candidate_interface/work_experience_form_spec.rb
Labels: Candidate
