Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2020-09, with the labels that each got.

#2694 Remove enrolment feature
  app/components/candidate_interface/application_complete_content_component.html.erb
  app/components/candidate_interface/application_complete_content_component.rb
  app/components/candidate_interface/application_status_tag_component.rb
  app/components/candidate_interface/covid19_dashboard_banner_component.html.erb
  app/components/candidate_interface/covid19_dashboard_banner_component.rb
  app/components/provider_interface/application_status_tag_component.rb
  app/components/provider_interface/application_timeline_component.rb
  app/components/provider_interface/status_box_components/enrolled_component.html.erb
  app/components/provider_interface/status_box_components/enrolled_component.rb
  app/components/support_interface/application_status_tag_component.rb
  app/controllers/vendor_api/decisions_controller.rb
  app/models/application_choice.rb
  app/models/application_form.rb
  app/models/performance_statistics.rb
  app/models/provider_interface/provider_applications_page_state.rb
  app/services/application_state_change.rb
  app/services/confirm_enrolment.rb
  app/services/process_state.rb
  app/services/support_interface/application_monitor.rb
  app/services/support_interface/candidate_journey_tracker.rb
  app/views/api_docs/pages/home.md
  app/views/api_docs/pages/release_notes.md
  app/views/api_docs/pages/usage.md
  app/views/candidate_interface/equality_and_diversity/start.html.erb
  app/views/candidate_interface/submitted_application_form/complete.html.erb
  app/views/candidate_mailer/application_submitted.text.erb
  app/views/integrations/performance_dashboard/dashboard.html.erb
  config/locales/application_complete.yml
  config/locales/application_states.yml
  config/vendor-api-v1.yml
  spec/components/candidate_interface/application_complete_content_component_spec.rb
  spec/components/candidate_interface/covid19_dashboard_banner_component_spec.rb
  spec/components/previews/provider_interface/application_timeline_component_preview.rb
  spec/components/provider_interface/filter_component_spec.rb
  spec/models/performance_statistics_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/requests/vendor_api/post_confirm_enrolment_spec.rb
  spec/services/application_state_change_spec.rb
  spec/services/confirm_enrolment_spec.rb
  spec/services/process_state_spec.rb
  spec/services/provider_interface/filter_application_choices_for_providers_spec.rb
  spec/services/send_candidate_rejection_email_spec.rb
  spec/services/support_interface/candidate_journey_tracker_spec.rb
  spec/system/candidate_interface/candidate_submitting_application_spec.rb
Labels: Core

#2795 Store ProviderRelationshipPermissions wizard data in Redis
  app/controllers/provider_interface/provider_relationship_permissions_setup_controller.rb
  app/controllers/provider_interface/provider_users_invitations_controller.rb
  app/forms/provider_interface/provider_relationship_permissions_setup_wizard.rb
  app/forms/provider_interface/provider_user_invitation_wizard.rb
  app/lib/wizard_state_stores/redis_store.rb
  app/lib/wizard_state_stores/session_store.rb
  spec/forms/provider_interface/provider_relationship_permissions_setup_wizard_spec.rb
  spec/forms/provider_interface/provider_user_invitation_wizard_spec.rb
Labels: ProVendor

#2808 Fix AssociatedProvidersPermissionsListComponent on the edit user page
  app/components/associated_providers_permissions_list_component.html.erb
  app/components/provider_interface/edit_provider_user_permissions_component.html.erb
Labels: ProVendor

#2819 Change the wording for ‘What institution did you study at?’
  config/locales/application_form.yml
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_degrees_spec.rb
Labels: Candidate, Content

#2815 Open button links in new window when specified in html_options
  app/helpers/view_helper.rb
  spec/helpers/view_helper_spec.rb
Labels: Core

#2818 Fix alignment of header in referee survey
  app/views/referee_interface/reference/confirmation.html.erb
Labels: Candidate

#2816 Remove ‘suggest’ from page title
  app/views/candidate_interface/unsubmitted_application_form/before_you_start.html.erb
Labels: Candidate, Content

#2820 Fix autocomplete error styles
  app/frontend/styles/_autocomplete.scss
Labels: Core

#2799 Change reject awaiting refs at EoC to a one-off job
  app/services/candidate_interface/get_previous_cycles_awaiting_references_course_choices.rb
  config/clock.rb
  spec/services/candidate_interface/get_previous_cycles_awaiting_references_course_choices_spec.rb
  spec/support_specs/clockwork_spec.rb
  spec/system/candidate_interface/candidate_is_awaiting_references_when_the_next_cycle_launches_spec.rb
Labels: Candidate

#2817 Adapt apply again for unsuccessful candidates between cycles
  app/components/candidate_interface/apply_again_banner_component.html.erb
  app/components/candidate_interface/apply_again_banner_component.rb
  app/components/candidate_interface/reopen_banner_component.rb
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  app/services/candidate_interface/end_of_cycle_policy.rb
  app/services/carry_over_application.rb
  app/services/end_of_cycle_timetable.rb
  app/views/candidate_interface/start_page/applications_closed.html.erb
  app/views/candidate_interface/submitted_application_form/start_carry_over_between_cycles.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  app/views/support_interface/docs/cycles.html.erb
  config/clock.rb
  config/locales/en.yml
  spec/components/candidate_interface/apply_again_banner_component_spec.rb
  spec/services/candidate_interface/end_of_cycle_policy_spec.rb
  spec/services/candidate_interface/get_previous_cycles_awaiting_references_course_choices_spec.rb
  spec/services/carry_over_application_spec.rb
  spec/services/end_of_cycle_timetable_spec.rb
  spec/system/candidate_interface/candidate_cannot_add_new_course_once_the_cycle_has_closed_spec.rb
  spec/system/candidate_interface/carry_over_unsuccessful_application_between_cycles_spec.rb
Labels: Candidate

#2821 Add recruitment time inversion to support
  app/controllers/support_interface/cycles_controller.rb
  app/models/site_setting.rb
  app/services/end_of_cycle_timetable.rb
  app/services/feature_flag.rb
  app/views/support_interface/cycles/index.html.erb
  config/routes.rb
  db/migrate/20200901201150_create_site_settings.rb
  db/schema.rb
  docs/domain-model.png
  spec/services/end_of_cycle_timetable_spec.rb
  spec/support/dates.rb
  spec/system/support_interface/cycle_switching_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: End of cycle, Support

#2823 Sent application paused email to candidates after apply_2_deadline
  app/mailers/candidate_mailer.rb
  app/services/candidate_interface/get_previous_cycles_awaiting_references_applications.rb
  app/services/candidate_interface/get_previous_cycles_awaiting_references_course_choices.rb
  app/views/candidate_mailer/application_on_pause.erb
  app/workers/reject_awaiting_references_course_choices_worker.rb
  config/locales/application_states.yml
  config/locales/candidate_mailer.yml
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/candidate_interface/get_previous_cycles_awaiting_references_applications_spec.rb
  spec/workers/reject_awaiting_references_course_choices_worker_spec.rb
Labels: Candidate

#2828 Add application_forms.recruitment_cycle_year column
  db/migrate/20200903155450_add_application_forms_recruitment_cycle_year.rb
  db/schema.rb
  docs/domain-model.png
Labels: Core

#2825 Tweaks for provider footer
  app/views/candidate_interface/shared/_support.html.erb
  app/views/layouts/_footer_meta_candidate.html.erb
  app/views/layouts/_footer_meta_provider.html.erb
  config/locales/en.yml
  spec/system/candidate_interface/candidate_content_spec.rb
  spec/system/provider_interface/provider_content_spec.rb
Labels: ProVendor

#2831 Send "find another course" email for unavailable choices at end of cycle
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/find_another_course.erb
  app/workers/send_course_full_notifications_worker.rb
  config/locales/candidate_mailer.yml
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/system/support_interface/docs_spec.rb
  spec/workers/reject_awaiting_references_course_choices_worker_spec.rb
  spec/workers/send_course_full_notifications_worker_spec.rb
Labels: Candidate

#2824 Add inset text styles and h2 to awaiting decision application header
  app/views/provider_interface/application_choices/_application_choice_header.html.erb
Labels: ProVendor

#2834 Add validation message to EFL qualification status
  config/locales/application_form.yml
Labels: Candidate

#2835 Use ‘interview needs’ not ‘interview preferences’
  config/locales/application_form.yml
  config/locales/review_application.yml
  config/vendor-api-v1.yml
Labels: Candidate

#2836 Remove the between cycles banner from the application dashboard
  app/components/candidate_interface/apply_again_banner_component.html.erb
  app/components/candidate_interface/apply_again_banner_component.rb
  app/views/candidate_interface/submitted_application_form/complete.html.erb
  spec/system/candidate_interface/candidate_views_unsuccessful_application_between_cycles_spec.rb
  spec/system/candidate_interface/carry_over_unsuccessful_application_between_cycles_spec.rb
Labels: Candidate

#2843 Revert changes on the 'Getting ready for the next cycle' content page
  app/helpers/content_helper.rb
  app/views/provider_interface/content/rendered_markdown_template.html.erb
  config/locales/en.yml
Labels: Candidate

#2829 Add logic to default ApplicationForm#recruitment_cycle_year to current year
  app/models/application_form.rb
  db/migrate/20200903170404_drop_application_forms_recruitment_cycle_year_default.rb
  db/schema.rb
Labels: Core

#2813 Start syncing courses from 2021
  app/services/feature_flag.rb
  app/services/sync_all_providers_from_find.rb
  spec/services/sync_all_providers_from_find_spec.rb
  spec/support/test_helpers/find_api_helper.rb
  spec/system/support_interface/provider_sync_courses_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
Labels: Core

#2826 Automatically infer the current cycle from the schedule
  app/models/recruitment_cycle.rb
  spec/models/recruitment_cycle_spec.rb
Labels: Core

#2833 Correct input width for IELTS score
  app/frontend/packs/ielts-band-score-autocomplete.js
  app/views/candidate_interface/english_foreign_language/ielts/_form_fields.html.erb
Labels: Candidate

#2827 Provide context for answers for disability, safeguarding, interview and qualifications sections of application
  app/components/interview_preferences_component.html.erb
  app/components/personal_statement_component.html.erb
  app/components/provider_interface/diversity_information_component.html.erb
  app/components/provider_interface/safeguarding_declaration_component.html.erb
  app/components/provider_interface/training_with_disability_component.html.erb
  app/components/provider_interface/volunteering_history_component.html.erb
  app/components/provider_interface/work_history_component.html.erb
  app/components/qualifications_component.html.erb
  app/views/provider_interface/application_choices/_references_context.html.erb
  app/views/provider_interface/application_choices/show.html.erb
Labels: ProVendor

#2812 Make support interface deal better with courses from multiple cycles
  app/components/support_interface/application_choice_component.html.erb
  app/components/support_interface/provider_courses_table_component.html.erb
  app/models/course.rb
  app/views/support_interface/courses/show.html.erb
  app/views/support_interface/providers/courses.html.erb
  spec/components/support_interface/provider_courses_table_component_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
Labels: Support

#2811 Reuse the wizard's check-answers permissions list on the Organisation edit page
  app/components/provider_interface/provider_relationship_permissions_list_component.html.erb
  app/components/provider_interface/provider_relationship_permissions_list_component.rb
  app/components/provider_relationship_permissions_list.html.erb
  app/components/provider_relationship_permissions_list.rb
  app/controllers/provider_interface/provider_relationship_permissions_setup_controller.rb
  app/forms/provider_interface/provider_relationship_permissions_setup_wizard.rb
  app/services/provider_interface/provider_relationship_edit_change_link_builder.rb
  app/services/provider_interface/provider_relationship_wizard_change_link_builder.rb
  app/services/provider_interface/setup_provider_relationship_permissions.rb
  app/views/provider_interface/organisations/show.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/check.html.erb
  spec/components/provider_interface/provider_relationship_permissions_list_component_spec.rb
  spec/components/provider_relationship_permissions_list_spec.rb
  spec/factories.rb
  spec/forms/provider_interface/provider_relationship_permissions_setup_wizard_spec.rb
  spec/services/provider_interface/setup_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/manage_provider_relationship_permissions_spec.rb
  spec/system/provider_interface/see_organisations_and_permissions_spec.rb
Labels: ProVendor

#2804 Add offer_deferred status
  app/components/candidate_interface/application_status_tag_component.rb
  app/components/provider_interface/application_status_tag_component.rb
  app/components/provider_interface/application_timeline_component.rb
  app/components/provider_interface/status_box_components/offer_deferred_component.html.erb
  app/components/provider_interface/status_box_components/offer_deferred_component.rb
  app/components/support_interface/application_status_tag_component.rb
  app/controllers/vendor_api/applications_controller.rb
  app/controllers/vendor_api/decisions_controller.rb
  app/models/application_choice.rb
  app/models/performance_statistics.rb
  app/queries/get_application_choices_for_providers.rb
  app/services/application_state_change.rb
  app/services/process_state.rb
  app/services/support_interface/tad_provider_stats_export.rb
  config/locales/application_states.yml
  docs/states.png
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/queries/get_application_choices_for_providers_spec.rb
  spec/services/application_state_change_spec.rb
  spec/services/support_interface/tad_provider_stats_export_spec.rb
Labels: ProVendor

#2845 Capitalise environment name tag
  app/lib/hosting_environment.rb
  config/initializers/inflector.rb
Labels: Content, Core

#2844 Add provider satisfaction survey to footer and header
  app/components/phase_banner.html.erb
  app/components/phase_banner.rb
  app/lib/hosting_environment.rb
  app/lib/provider_interface.rb
  app/views/layouts/_footer_meta_provider.html.erb
  app/views/layouts/_header.html.erb
  spec/components/phase_banner_spec.rb
Labels: ProVendor

#2822 Send a slack notification when a ProviderUser is added
  app/services/invite_provider_user.rb
  spec/services/invite_provider_user_spec.rb
Labels: ProVendor

#2850 Fix broken error summary in the permissions wizard
  app/controllers/provider_interface/provider_relationship_permissions_setup_controller.rb
  app/forms/provider_interface/provider_relationship_permissions_setup_wizard.rb
  app/views/provider_interface/provider_relationship_permissions_setup/setup_permissions.html.erb
  spec/forms/provider_interface/provider_relationship_permissions_setup_wizard_spec.rb
Labels: ProVendor

#2852 Update 'application_submitted' email content
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/application_submitted.text.erb
  spec/mailers/candidate_mailer_spec.rb
Labels: Candidate, Content

#2863 Update API release notes following bug fix
  app/views/api_docs/pages/release_notes.md
Labels: ProVendor

#2861 Support ability to filter 'offer_deferred' with test data and DeferOffer service
  app/lib/test_applications.rb
  app/services/defer_offer.rb
  app/workers/generate_test_applications.rb
  db/migrate/20200908141522_add_offer_deferred_at_to_application_choices.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/services/defer_offer_spec.rb
Labels: ProVendor

#2855 Show fewer page links when paginating above a threshold
  app/components/paginator_component.html.erb
  app/components/paginator_component.rb
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_pagination.scss
  spec/components/paginator_component_spec.rb
Labels: ProVendor

#2864 Show right to work fields when viewing application in Provider interface
  app/components/personal_details_component.rb
  spec/components/personal_details_component_spec.rb
Labels: Candidate

#2840 Change rejected_at_end_of_cycle to applications_not_sent
  app/components/candidate_interface/application_complete_content_component.html.erb
  app/components/candidate_interface/application_complete_content_component.rb
  app/components/candidate_interface/application_status_tag_component.html.erb
  app/components/candidate_interface/application_status_tag_component.rb
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/provider_interface/application_status_tag_component.rb
  app/components/provider_interface/application_timeline_component.rb
  app/components/support_interface/application_status_tag_component.rb
  app/models/application_choice.rb
  app/models/application_form.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/application_state_change.rb
  config/locales/application_complete.yml
  config/locales/application_states.yml
  spec/components/candidate_interface/application_status_tag_component_spec.rb
  spec/factories.rb
  spec/models/application_form_spec.rb
  spec/services/application_state_change_spec.rb
  spec/services/candidate_interface/reject_awaiting_references_application_spec.rb
  spec/system/candidate_interface/candidate_is_awaiting_references_when_the_next_cycle_launches_spec.rb
Labels: Candidate

#2878 Remove "Safe to work with children" from referee survey export
  app/models/referee_questionnaire.rb
  app/services/support_interface/referee_survey_export.rb
  spec/services/support_interface/referee_survey_export_spec.rb
Labels: Candidate

#2880 don't trigger build if another one is inprogress
  azure/pipelines/build-gems-node-modules.yml
  azure/pipelines/templates/swap-staging-production-slots.yml
Labels: DevOps

#2853 Carry over un-submitted applications manually after EoC
  app/components/candidate_interface/apply_again_banner_component.html.erb
  app/components/candidate_interface/apply_again_banner_component.rb
  app/components/candidate_interface/carry_over_banner_component.html.erb
  app/components/candidate_interface/carry_over_banner_component.rb
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/helpers/view_helper.rb
  app/models/application_form.rb
  app/services/application_state_change.rb
  app/services/candidate_interface/cancel_unsubmitted_application_at_end_of_cycle.rb
  app/services/candidate_interface/end_of_cycle_policy.rb
  app/services/carry_over_application.rb
  app/services/duplicate_application.rb
  app/services/end_of_cycle_timetable.rb
  app/views/candidate_interface/submitted_application_form/complete.html.erb
  app/views/candidate_interface/submitted_application_form/start_carry_over.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  app/workers/cancel_unsubmitted_applications_worker.rb
  config/locales/application_states.yml
  config/locales/en.yml
  spec/components/candidate_interface/apply_again_banner_component_spec.rb
  spec/components/candidate_interface/carry_over_banner_component_spec.rb
  spec/services/apply_again_spec.rb
  spec/services/cancel_unsubmitted_application_at_end_of_cycle_spec.rb
  spec/services/candidate_interface/end_of_cycle_policy_spec.rb
  spec/services/carry_over_application_spec.rb
  spec/services/duplicate_application_shared_examples.rb
  spec/services/end_of_cycle_timetable_spec.rb
  spec/system/candidate_interface/candidate_cannot_add_new_course_once_the_cycle_has_closed_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_without_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/candidate_with_unsubmitted_application_between_cycles_spec.rb
  spec/system/candidate_interface/carry_over_unsuccessful_application_between_cycles_spec.rb
  spec/system/candidate_interface/carry_over_unsuccessful_application_spec.rb
  spec/workers/cancel_unsubmitted_applications_worker_spec.rb
Labels: Candidate

#2882 Fix error caused by validation error on completing personal details
  app/controllers/candidate_interface/personal_details/review_controller.rb
Labels: Candidate

#2869 Show how org/org permissions affect user permissions in the Invitation wizard
  app/components/associated_providers_permissions_list_component.rb
  app/components/permissions_list_component.html.erb
  app/components/provider_interface/edit_provider_user_permissions_component.html.erb
  app/forms/provider_interface/provider_user_invitation_wizard.rb
  app/views/provider_interface/provider_users_invitations/edit_permissions.html.erb
  spec/components/associated_providers_permissions_list_component_spec.rb
Labels: ProVendor

#2877 Allow providers to defer offers
  app/components/provider_interface/status_box_components/offer_deferred_component.rb
  app/components/provider_interface/status_box_components/pending_conditions_component.html.erb
  app/components/provider_interface/status_box_components/recruited_component.html.erb
  app/components/provider_interface/status_box_components/recruited_component.rb
  app/controllers/provider_interface/decisions_controller.rb
  app/lib/state_change_notifier.rb
  app/mailers/candidate_mailer.rb
  app/models/recruitment_cycle.rb
  app/services/defer_offer.rb
  app/views/candidate_mailer/deferred_offer.text.erb
  app/views/provider_interface/decisions/new_defer_offer.html.erb
  config/locales/application_states.yml
  config/locales/candidate_mailer.yml
  config/routes.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/models/recruitment_cycle_spec.rb
  spec/services/defer_offer_spec.rb
  spec/system/provider_interface/provider_defers_an_offer_spec.rb
Labels: ProVendor

#2893 Update the application dashboards UI for deferred applications
  app/components/candidate_interface/application_complete_content_component.html.erb
  app/components/candidate_interface/application_complete_content_component.rb
  app/components/candidate_interface/application_status_tag_component.html.erb
  app/components/candidate_interface/course_choices_review_component.rb
  app/models/application_form.rb
  config/locales/application_complete.yml
  spec/components/candidate_interface/application_complete_content_component_spec.rb
  spec/components/candidate_interface/application_status_tag_component_spec.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
Labels: Candidate

#2883 Fix Application form presenter safeguarding section to route to review
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
Labels: Candidate

#2871 Fix training with a disability section to route to review page
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
Labels: Candidate

#2865 Fix application form presenter & view to validate contact details
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
Labels: Candidate

#2902 Check if find is down only once on providers page
  app/components/grouped_provider_courses_component.html.erb
Labels: Core

#2847 When validating nationality, highlight inputs containing errors
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/forms/candidate_interface/nationalities_form.rb
  app/frontend/packs/nationalities-component.js
  app/frontend/packs/nationality-autocomplete.js
  app/models/application_form.rb
  app/services/candidate_interface/get_nationalities_form_hash.rb
  app/views/candidate_interface/personal_details/nationalities/_shared_form.html.erb
  config/locales/application_form.yml
  spec/forms/candidate_interface/nationalities_form_spec.rb
  spec/services/candidate_interface/get_nationalities_form_hash_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#2901 Add filtering to providers, candidates and applications in support
  app/components/paginated_filter_component.html.erb
  app/components/paginated_filter_component.rb
  app/components/support_interface/candidates_table_component.html.erb
  app/components/support_interface/candidates_table_component.rb
  app/controllers/support_interface/application_forms_controller.rb
  app/controllers/support_interface/candidates_controller.rb
  app/controllers/support_interface/providers_controller.rb
  app/frontend/packs/application-provider.js
  app/frontend/packs/application-support.js
  app/frontend/packs/components/paginated_filter.js
  app/frontend/styles/application-support.scss
  app/models/support_interface/applications_filter.rb
  app/models/support_interface/candidates_filter.rb
  app/models/support_interface/providers_filter.rb
  app/views/support_interface/application_forms/index.html.erb
  app/views/support_interface/candidates/index.html.erb
  app/views/support_interface/providers/index.html.erb
  app/views/support_interface/providers/other_providers.html.erb
  spec/components/support_interface/candidates_table_component_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
  spec/system/support_interface/see_applications_spec.rb
  spec/system/support_interface/see_candidates_spec.rb
Labels: Support

#2900 Increase the max length of `address_line1` to 200 chars in the API
  app/views/api_docs/pages/release_notes.md
  config/vendor-api-v1.yml
Labels: ProVendor

#2899 Display conditional deferral guidance on the dashboard
  app/components/candidate_interface/application_status_tag_component.html.erb
  spec/components/candidate_interface/application_status_tag_component_spec.rb
Labels: Candidate

#2906 Use FilterPagination component in provider UI
  app/components/filter_component.rb
  app/components/paginated_filter_component.html.erb
  app/controllers/provider_interface/application_choices_controller.rb
  app/models/provider_interface/provider_applications_filter.rb
  app/views/provider_interface/application_choices/index.html.erb
  spec/components/filter_component_spec.rb
  spec/components/previews/provider_interface/filter_component_preview.rb
  spec/models/provider_interface/provider_applications_filter_spec.rb
Labels: Core

#2890 Remove repetitive ‘Complete section’ links on application review page
  app/components/section_missing_banner_component.html.erb
  config/locales/review_application.yml
  spec/components/section_missing_banner_component_spec.rb
  spec/system/candidate_interface/candidate_adding_referees_in_sandbox_spec.rb
  spec/system/candidate_interface/candidate_entering_equality_and_diversity_information_spec.rb
  spec/system/candidate_interface/candidate_reviewing_an_incomplete_application_spec.rb
  spec/system/candidate_interface/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/international/international_candidate_submitting_application_spec.rb
Labels: Candidate

#2891 Update config for GCSE grade autocomplete
  app/frontend/packs/gcse-grade-autocomplete.js
Labels: Bug bash 🐞🔨, Candidate

#2909 Add validation methods for subject knowledge and interview preferences
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
Labels: Candidate

#2886 Set references_completed correctly when carrying over application
  app/services/duplicate_application.rb
  spec/services/duplicate_application_shared_examples.rb
Labels: Candidate

#2907 Add validation method for Becoming a Teacher section to application presenter
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
Labels: Candidate

#2895 Render error page if candidate selects unavailable course
  app/controllers/candidate_interface/course_choices/course_selection_controller.rb
  app/forms/candidate_interface/pick_course_form.rb
  app/forms/candidate_interface/pick_site_form.rb
  app/models/course.rb
  app/models/course_option.rb
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_that_is_full_spec.rb
Labels: Candidate

#2911 Create an offer accepted email
  app/mailers/candidate_mailer.rb
  app/services/accept_offer.rb
  app/views/candidate_mailer/offer_accepted.text.erb
  config/locales/application_states.yml
  config/locales/candidate_mailer.yml
  spec/mailers/candidate_mailer_spec.rb
  spec/services/accept_offer_spec.rb
  spec/system/candidate_interface/candidate_accepts_offer_spec.rb
Labels: Candidate

#2887 Only reject choices awaiting references at eoc
  app/workers/reject_awaiting_references_course_choices_worker.rb
  spec/workers/reject_awaiting_references_course_choices_worker_spec.rb
Labels: Candidate

#2912 Combine 2 paragraphs of the deferral guidance on the dashboard
  app/components/candidate_interface/application_status_tag_component.html.erb
Labels: Candidate, Content

#2904 Add deferral guidance to the offer emails
  app/views/candidate_mailer/new_offer/decisions_pending.text.erb
  app/views/candidate_mailer/new_offer/multiple_offers.text.erb
  app/views/candidate_mailer/new_offer/single_offer.text.erb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
Labels: Candidate

#2898 Return nationality and residency data in the API
  app/models/application_form.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/views/api_docs/pages/release_notes.md
  config/vendor-api-v1.yml
  spec/factories.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: ProVendor

#2908 Create Application Reference CSV report
  app/controllers/support_interface/performance_controller.rb
  app/services/support_interface/application_references_export.rb
  app/views/support_interface/performance/index.html.erb
  config/routes.rb
  spec/services/support_interface/application_references_export_spec.rb
  spec/system/support_interface/application_references_performance_spec.rb
Labels: Support

#2905 Add validation methods for all GCSE types to application presenter
  app/lib/test_applications.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/components/candidate_interface/additional_referees_start_component_spec.rb
  spec/components/candidate_interface/referees_review_component_spec.rb
  spec/factories.rb
  spec/mailers/candidate_mailer_referee_mails_spec.rb
  spec/mailers/referee_mailer_spec.rb
  spec/models/application_reference_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/services/apply_again_spec.rb
  spec/services/carry_over_application_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_without_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/candidate_entering_equality_and_diversity_information_spec.rb
  spec/system/candidate_interface/candidate_entering_gcse_spec.rb
  spec/system/candidate_interface/candidate_replaces_reference_after_applying_again_spec.rb
  spec/system/candidate_interface/candidate_views_unsuccessful_application_between_cycles_spec.rb
  spec/system/candidate_interface/candidate_with_unsuccessful_application_applies_again_spec.rb
  spec/system/support_interface/see_individual_application_spec.rb
Labels: Candidate

#2923 Use the courses start date for the deferral guidance in the offer emails
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/new_offer/decisions_pending.text.erb
  app/views/candidate_mailer/new_offer/multiple_offers.text.erb
  app/views/candidate_mailer/new_offer/single_offer.text.erb
Labels: Candidate, Content

#2925 Fix styling and remove erroneous divs from the deferral guidance
  app/components/candidate_interface/application_status_tag_component.html.erb
Labels: Candidate

#2910 Change Unit 4's test provider code
  app/services/generate_vendor_providers.rb
Labels: ProVendor

#2884 Show EFL qualifications on Provider interface
  app/components/efl_qualification_card_component.html.erb
  app/components/efl_qualification_card_component.rb
  app/components/language_skills_component.rb
  app/components/qualifications_component.html.erb
  app/controllers/provider_interface/application_choices_controller.rb
  app/frontend/styles/_card.scss
  app/frontend/styles/_flex-grid.scss
  app/frontend/styles/application.scss
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_qualification.scss
  app/models/ielts_qualification.rb
  app/models/other_efl_qualification.rb
  app/models/toefl_qualification.rb
  app/views/provider_interface/application_choices/show.html.erb
  spec/components/efl_qualification_card_component_spec.rb
  spec/components/language_skills_component_spec.rb
  spec/factories.rb
Labels: ProVendor

#2928 Mailer copy update - References did not come back in time
  app/mailers/candidate_mailer.rb
  app/models/recruitment_cycle.rb
  app/views/candidate_mailer/application_on_pause.erb
  app/views/candidate_mailer/referees_did_not_respond_before_end_of_cycle.erb
  app/workers/reject_awaiting_references_course_choices_worker.rb
  config/locales/application_states.yml
  config/locales/candidate_mailer.yml
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/models/recruitment_cycle_spec.rb
  spec/workers/reject_awaiting_references_course_choices_worker_spec.rb
Labels: Candidate, End of cycle

#2918 Change how we display GCSEs on the Manage application choice page
  app/components/gcse_qualification_cards_component.html.erb
  app/components/gcse_qualification_cards_component.rb
  app/components/qualifications_component.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  spec/components/gcse_qualification_cards_component_spec.rb
  spec/factories.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: ProVendor

#2933 Update EndOfCycleTimetable schedules
  app/services/end_of_cycle_timetable.rb
  spec/system/support_interface/cycle_switching_spec.rb
Labels: Bug bash 🐞🔨, Candidate, End of cycle

#2932 2135 - Application reference export amends
  app/services/support_interface/application_references_export.rb
  spec/services/support_interface/application_references_export_spec.rb
  spec/system/support_interface/application_references_performance_spec.rb
Labels: Support

#2924 Allow filtering applications by phase (apply 1 or apply 2)
  app/controllers/support_interface/application_forms_controller.rb
  app/models/support_interface/applications_filter.rb
Labels: Support

#2937 Remove Extraneous Feature Test File
  spec/system/candidate_interface/course_selection/candidate_replaces_a_full_course_spec.rb
Labels: Candidate

#2929 EOC: References did not come back in time - copy changes
  app/components/candidate_interface/carry_over_banner_component.html.erb
  app/helpers/view_helper.rb
  app/views/candidate_interface/submitted_application_form/start_carry_over.html.erb
  app/views/candidate_interface/submitted_application_form/start_carry_over_between_cycles.html.erb
  config/locales/en.yml
  spec/components/candidate_interface/carry_over_banner_component_spec.rb
  spec/system/candidate_interface/candidate_cannot_add_new_course_once_the_cycle_has_closed_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_without_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/candidate_views_unsuccessful_application_between_cycles_spec.rb
  spec/system/candidate_interface/candidate_with_unsubmitted_application_between_cycles_spec.rb
  spec/system/candidate_interface/carry_over_unsuccessful_application_between_cycles_spec.rb
  spec/system/candidate_interface/carry_over_unsuccessful_application_spec.rb
Labels: Candidate, Content, End of cycle

#2876 Trigger one-off EoC jobs manually via support interface
  app/controllers/support_interface/tasks_controller.rb
  app/services/candidate_interface/get_previous_cycles_awaiting_references_applications.rb
  app/views/support_interface/tasks/confirm_cancel_applications_at_end_of_cycle.html.erb
  app/views/support_interface/tasks/confirm_reject_applications_awaiting_references_at_end_of_cycle.html.erb
  app/views/support_interface/tasks/index.html.erb
  app/workers/cancel_unsubmitted_applications_worker.rb
  config/clock.rb
  config/routes.rb
  spec/services/candidate_interface/get_previous_cycles_awaiting_references_applications_spec.rb
  spec/support_specs/clockwork_spec.rb
  spec/system/support_interface/cancel_unsubmitted_at_eoc_task_spec.rb
  spec/system/support_interface/reject_awaiting_references_at_eoc_task_spec.rb
  spec/workers/cancel_unsubmitted_applications_worker_spec.rb
Labels: Candidate

#2885 Carry over unsubmitted application between cycles
  app/controllers/candidate_interface/carry_over_controller.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/services/carry_over_application.rb
  app/views/candidate_interface/carry_over/start.html.erb
  app/views/candidate_interface/carry_over/start_between_cycles.html.erb
  app/views/candidate_interface/carry_over/start_between_cycles_unsubmitted.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/services/carry_over_application_spec.rb
  spec/system/candidate_interface/candidate_cannot_add_new_course_once_the_cycle_has_closed_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_between_cycles_spec.rb
  spec/system/candidate_interface/carry_over_unsuccessful_application_between_cycles_spec.rb
Labels: Candidate

#2940 Update the equality and diversity privacy content
  app/views/candidate_interface/equality_and_diversity/start.html.erb
  app/views/content/privacy_policy.md
Labels: Candidate, Content

#2939 Remove ClockWorkCheck
  adr/0009-async-and-scheduled-jobs.md
  app/workers/clockwork_check.rb
  config/clock.rb
  spec/support_specs/clockwork_spec.rb
  spec/support_specs/logstash_logging_spec.rb
  spec/workers/clockwork_check_spec.rb
Labels: Core

#2938 Cancel outstanding references at the end of cycle
  app/components/candidate_interface/referees_review_component.rb
  app/models/application_reference.rb
  app/services/candidate_interface/cancel_reference_at_end_of_cycle.rb
  app/services/duplicate_application.rb
  app/workers/reject_awaiting_references_course_choices_worker.rb
  config/locales/application_form.yml
  config/locales/reference.yml
  spec/components/candidate_interface/referees_review_component_spec.rb
  spec/services/candidate_interface/cancel_reference_at_end_of_cycle_spec.rb
  spec/services/carry_over_application_spec.rb
  spec/workers/reject_awaiting_references_course_choices_worker_spec.rb
Labels: Candidate

#2944 Don't show the referee banner at end of cycle
  app/components/candidate_interface/new_references_needed_component.rb
  spec/components/candidate_interface/new_references_needed_component_spec.rb
Labels: Candidate

#2945 Add I18n fallback when showing GCSE qualifications
  app/components/gcse_qualification_cards_component.rb
Labels: Candidate

#2936 Change how we display degrees on the Manage application choice page
  app/components/degree_qualification_cards_component.html.erb
  app/components/degree_qualification_cards_component.rb
  app/components/efl_qualification_card_component.html.erb
  app/components/gcse_qualification_cards_component.html.erb
  app/components/qualifications_component.html.erb
  app/components/qualifications_component.rb
  app/components/qualifications_table_component.html.erb
  app/frontend/styles/_card.scss
  app/frontend/styles/_flex-grid.scss
  app/views/provider_interface/application_choices/show.html.erb
  spec/components/degree_qualification_cards_component_spec.rb
  spec/components/efl_qualification_card_component_spec.rb
  spec/components/qualifications_table_component_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: ProVendor

#2927 Update content for candidate unsuccessful at EoC
  app/components/candidate_interface/carry_over_banner_component.html.erb
  app/components/candidate_interface/carry_over_banner_component.rb
  app/mailers/candidate_mailer.rb
  app/models/application_form.rb
  app/services/candidate_interface/end_of_cycle_policy.rb
  app/views/candidate_interface/carry_over/start_between_cycles.html.erb
  app/views/candidate_interface/carry_over/start_between_cycles_unsubmitted.html.erb
  app/views/candidate_mailer/application_rejected_all_rejected.erb
  app/views/candidate_mailer/application_rejected_all_rejected_apply_again.erb
  config/locales/candidate_mailer.yml
  config/locales/en.yml
  spec/components/candidate_interface/carry_over_banner_component_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/models/application_form_spec.rb
  spec/system/candidate_interface/candidate_cannot_add_new_course_once_the_cycle_has_closed_spec.rb
  spec/system/candidate_interface/carry_over_unsuccessful_application_between_cycles_spec.rb
Labels: Candidate

#2947 Add missing support translation string for cancelled at eoc references
  app/components/support_interface/reference_with_feedback_component.rb
  config/locales/reference.yml
Labels: Candidate

#2946 Update interstitial content for unsubmitted applications
  app/views/candidate_interface/carry_over/start.html.erb
  app/views/candidate_interface/carry_over/start_between_cycles.html.erb
  app/views/candidate_interface/carry_over/start_between_cycles_unsubmitted.html.erb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_between_cycles_spec.rb
Labels: Candidate

#2948 EoC task list updates
  app/helpers/view_helper.rb
  app/services/candidate_interface/end_of_cycle_policy.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/services/candidate_interface/end_of_cycle_policy_spec.rb
  spec/system/candidate_interface/candidate_cannot_add_new_course_once_the_cycle_has_closed_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_between_cycles_spec.rb
  spec/system/candidate_interface/candidate_with_unsubmitted_application_between_cycles_spec.rb
  spec/system/candidate_interface/carry_over_unsuccessful_application_between_cycles_spec.rb
Labels: Candidate

#2950 Fix CancelUnsubmittedApplicationsWorker
  app/services/candidate_interface/cancel_unsubmitted_application_at_end_of_cycle.rb
  app/workers/cancel_unsubmitted_applications_worker.rb
  spec/workers/cancel_unsubmitted_applications_worker_spec.rb
Labels: Core

#2934 Render 404 when an application is not visible to user or does not exist
  app/controllers/provider_interface/application_choices_controller.rb
  spec/requests/provider_interface/viewing_applications_spec.rb
Labels: ProVendor

#2941 Replace English foreign lang qual with English foreign lang assessment
  app/components/candidate_interface/english_foreign_language/efl_review_helper.rb
  app/components/candidate_interface/english_foreign_language/no_efl_qualification_review_component.rb
  app/components/efl_qualification_card_component.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/english_foreign_language/start/_form_fields.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/locales/review_application.yml
  spec/components/candidate_interface/english_foreign_language/ielts_review_component_spec.rb
  spec/components/candidate_interface/english_foreign_language/no_efl_qualification_review_component_spec.rb
  spec/components/candidate_interface/english_foreign_language/other_efl_qualification_review_component_spec.rb
  spec/components/candidate_interface/english_foreign_language/toefl_review_component_spec.rb
  spec/components/efl_qualification_card_component_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/change_qualification_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/declare_no_qualification_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/view_efl_form_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/your_ielts_results_spec.rb
  spec/system/candidate_interface/english_as_a_foreign_language/your_toefl_result.rb
  spec/system/candidate_interface/international/international_candidate_submitting_application_spec.rb
Labels: Candidate

#2955 overrideFullDeployment variable to control full ARM deployment
  azure/pipelines/templates/deploy.yml
Labels: DevOps

#2922 Add application card for applications list
  app/components/provider_interface/application_card_component.html.erb
  app/components/provider_interface/user_list_card_component.html.erb
  app/components/support_interface/application_card_component.html.erb
  app/components/support_interface/application_card_component.rb
  app/components/support_interface/application_status_tag_component.html.erb
  app/components/support_interface/applications_table_component.html.erb
  app/components/support_interface/applications_table_component.rb
  app/controllers/support_interface/application_forms_controller.rb
  app/frontend/styles/_application-card.scss
  app/frontend/styles/application.scss
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_application-card.scss
  app/views/support_interface/providers/applications.html.erb
  spec/components/provider_interface/application_card_component_spec.rb
  spec/components/support_interface/applications_table_component_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
  spec/system/support_interface/see_individual_application_spec.rb
Labels: Support

#2957 Share qualification styles
  app/frontend/styles/_qualification.scss
  app/frontend/styles/application.scss
  app/frontend/styles/provider/_all.scss
Labels: Support

#2952 Update content in the chase candidate decision email
  app/views/candidate_mailer/chase_candidate_decision.text.erb
Labels: Candidate

#2964 Update copy for equality and diversity
  app/views/candidate_interface/equality_and_diversity/start.html.erb
  app/views/content/privacy_policy.md
  spec/system/candidate_interface/candidate_entering_equality_and_diversity_information_spec.rb
Labels: Candidate, Content

#2935 Use background task fan-out for provider sync
  app/services/sync_provider_from_find.rb
  app/workers/sync_all_from_find.rb
  app/workers/sync_courses_from_find.rb
  config/sidekiq.yml
  lib/tasks/local_dev.rake
  spec/services/sync_provider_from_find_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
Labels: Core

#2954 Add pagination and filtering to providers application list
  app/controllers/support_interface/application_forms_controller.rb
  app/controllers/support_interface/providers_controller.rb
  app/models/support_interface/applications_filter.rb
  app/views/support_interface/providers/applications.html.erb
Labels: Support

#2920 Allow provider users to reinstate deferred offers from previous cycle
  app/components/provider_interface/conditions_component.html.erb
  app/components/provider_interface/conditions_component.rb
  app/components/provider_interface/deferred_offer_details_component.html.erb
  app/components/provider_interface/deferred_offer_details_component.rb
  app/controllers/provider_interface/application_choices_controller.rb
  app/controllers/provider_interface/reconfirm_deferred_offers_controller.rb
  app/forms/provider_interface/reconfirm_deferred_offer_wizard.rb
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_offer.scss
  app/lib/state_change_notifier.rb
  app/models/course_option.rb
  app/services/defer_offer.rb
  app/services/reinstate_conditions_met.rb
  app/services/reinstate_pending_conditions.rb
  app/views/provider_interface/application_choices/_application_choice_header.html.erb
  app/views/provider_interface/reconfirm_deferred_offers/check.html.erb
  app/views/provider_interface/reconfirm_deferred_offers/conditions.html.erb
  app/views/provider_interface/reconfirm_deferred_offers/start.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200916155314_add_status_before_deferral_to_application_choices.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories.rb
  spec/forms/provider_interface/reconfirm_deferred_offer_wizard_spec.rb
  spec/services/reinstate_conditions_met_spec.rb
  spec/services/reinstate_pending_conditions_spec.rb
  spec/system/provider_interface/provider_reinstates_deferred_offer_spec.rb
Labels: ProVendor

#2805 Grant default organisation permissions
  db/migrate/20200922092516_add_default_permissions_for_provider_relationships.rb
  db/schema.rb
Labels: ProVendor

#2963 Fix A11y issues in components
  app/components/filter_component.html.erb
  app/components/summary_list_component.html.erb
  spec/components/summary_list_component_spec.rb
Labels: Core

#2959 Fixes for A11y issues on candidate landing page
  app/components/header_component.html.erb
  app/components/phase_banner.html.erb
  app/components/phase_banner.rb
  app/frontend/styles/_environments.scss
  app/frontend/styles/_header.scss
  app/frontend/styles/application.scss
  app/views/candidate_interface/referees/_form.html.erb
  app/views/provider_interface/application_choices/show.html.erb
Labels: Core

#2968 Remove to work details when a candidate selects they are British or Irish
  app/forms/candidate_interface/nationalities_form.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  spec/forms/candidate_interface/nationalities_form_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#2953 Update the change offer confirmation component to work on QA
  spec/components/previews/provider_interface/change_offer_preview.rb
Labels: Core

#2967 Bug fixes for international Degrees & GCSEs
  app/components/candidate_interface/degrees_review_component.rb
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/forms/candidate_interface/degree_naric_statement_form.rb
  config/locales/application_form.yml
  spec/components/candidate_interface/degrees_review_component_spec.rb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/forms/candidate_interface/degree_naric_statement_form_spec.rb
  spec/system/candidate_interface/candidate_entering_gcse_spec.rb
  spec/system/candidate_interface/international/candidate_entering_international_degrees_spec.rb
Labels: Candidate

#2972 Handle when permissions are empty in save provider user service
  app/services/provider_interface/save_provider_user_service.rb
  spec/services/provider_interface/save_provider_user_service_spec.rb
Labels: ProVendor

#2970 Restructure the Find Sync code for easier changing
  app/services/find_sync/course_study_modes.rb
  app/services/find_sync/course_vacancy_status.rb
  app/services/find_sync/sync_all_providers_from_find.rb
  app/services/find_sync/sync_courses_from_find.rb
  app/services/find_sync/sync_provider_from_find.rb
  app/services/sync_all_providers_from_find.rb
  app/services/sync_provider_from_find.rb
  app/workers/sync_all_from_find.rb
  app/workers/sync_courses_from_find.rb
  lib/tasks/local_dev.rake
  spec/services/find_sync/course_study_modes_spec.rb
  spec/services/find_sync/course_vacancy_status_spec.rb
  spec/services/find_sync/sync_provider_from_find_spec.rb
  spec/services/sync_all_providers_from_find_spec.rb
  spec/system/find_sync/site_is_deleted_spec.rb
  spec/system/find_sync/study_mode_changes_spec.rb
  spec/system/find_sync/syncing_providers_spec.rb
  spec/workers/sync_all_from_find_spec.rb
Labels: Core

#2979 Remove open_on_apply constraint on broken view component
  spec/components/previews/provider_interface/change_offer_preview.rb
Labels: Core

#2977 Fix ended without success count in performance statistics
  app/models/performance_statistics.rb
Labels: Support

#2980 Remove unnecessary comments in ‘nationalities_form_spec’
  spec/forms/candidate_interface/nationalities_form_spec.rb
Labels: Candidate

#2974 Support: Update design of pages in Tasks section
  app/frontend/styles/_section.scss
  app/frontend/styles/_styled-content.scss
  app/frontend/styles/application.scss
  app/frontend/styles/provider/_all.scss
  app/views/provider_interface/start_page/show.html.erb
  app/views/support_interface/tasks/confirm_cancel_applications_at_end_of_cycle.html.erb
  app/views/support_interface/tasks/confirm_delete_test_applications.html.erb
  app/views/support_interface/tasks/confirm_reject_applications_awaiting_references_at_end_of_cycle.html.erb
  app/views/support_interface/tasks/index.html.erb
  spec/system/support_interface/cancel_unsubmitted_at_eoc_task_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
  spec/system/support_interface/purge_test_applications_spec.rb
  spec/system/support_interface/reject_awaiting_references_at_eoc_task_spec.rb
  spec/system/support_interface/tasks_spec.rb
Labels: Support

#2981 Fix flaky change offer preview component
  spec/components/previews/provider_interface/change_offer_preview.rb
Labels: Core

#2982 Add definitions for new HESA codes
  config/initializers/hesa_disabilities.rb
  config/initializers/hesa_ethnicities.rb
  config/initializers/hesa_sex.rb
Labels: Candidate

#2978 Update title on equality and diversity start page
  app/views/candidate_interface/equality_and_diversity/start.html.erb
  spec/system/candidate_interface/candidate_entering_equality_and_diversity_information_spec.rb
Labels: Candidate

#2975 Add rejection reason to applications CSV download
  app/services/support_interface/application_choices_export.rb
  spec/services/application_choices_export_spec.rb
  spec/services/support_interface/application_choices_export_spec.rb
Labels: Support

#2983 Notify in Slack when the cycle is changed through support
  app/controllers/support_interface/cycles_controller.rb
Labels: Support

#2984 Smol support IA changes
  app/helpers/navigation_items.rb
  app/views/support_interface/candidates/_candidates_navigation.html.erb
  app/views/support_interface/course_options/index.html.erb
  app/views/support_interface/cycles/index.html.erb
  app/views/support_interface/docs/_docs_navigation.html.erb
  app/views/support_interface/email_log/index.html.erb
  app/views/support_interface/feature_flags/index.html.erb
  app/views/support_interface/performance/_performance_navigation.html.erb
  app/views/support_interface/performance/course_stats.html.erb
  app/views/support_interface/performance/data.html.erb
  app/views/support_interface/performance/index.html.erb
  app/views/support_interface/settings/_settings_navigation.html.erb
  app/views/support_interface/support_users/index.html.erb
  app/views/support_interface/support_users/new.html.erb
  app/views/support_interface/support_users/show.html.erb
  app/views/support_interface/tasks/index.html.erb
  app/views/support_interface/ucas_matches/index.html.erb
  app/views/support_interface/ucas_matches/show.html.erb
  app/views/support_interface/validation_errors/index.html.erb
  app/views/support_interface/validation_errors/search.html.erb
  app/views/support_interface/validation_errors/summary.html.erb
  config/routes.rb
  spec/system/support_interface/active_provider_users_csv_export_spec.rb
  spec/system/support_interface/application_choices_performance_spec.rb
  spec/system/support_interface/application_references_performance_spec.rb
  spec/system/support_interface/candidate_survey_csv_spec.rb
  spec/system/support_interface/course_choice_withdrawal_survey_csv_spec.rb
  spec/system/support_interface/cycle_switching_spec.rb
  spec/system/support_interface/managing_support_users_spec.rb
  spec/system/support_interface/referee_survey_csv_spec.rb
  spec/system/support_interface/tad_provider_performance_spec.rb
  spec/system/support_interface/validation_errors_summary_spec.rb
Labels: Support

#2986 Fix hidden text change link descriptions in the EFL review component
  app/components/candidate_interface/english_foreign_language/efl_review_helper.rb
  app/components/candidate_interface/english_foreign_language/toefl_review_component.rb
Labels: Bug bash 🐞🔨, Candidate

#2987 Refactor QualificationsTableComponent
  app/components/qualifications_component.html.erb
  app/components/qualifications_table_component.html.erb
  app/components/qualifications_table_component.rb
  spec/components/qualifications_table_component_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: ProVendor

#2985 Add data migration to update legacy degree grade values
  db/migrate/20200924121000_migrate_old_degree_grade_values_to_hesa_descriptions.rb
  db/schema.rb
  spec/factories.rb
Labels: Core

#2989 Use the offered_course_choice in the offer emails if one is present
  app/mailers/candidate_mailer.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#2988 Show HESA codes for qualifications in support
  app/components/degree_qualification_cards_component.html.erb
  app/components/degree_qualification_cards_component.rb
  app/components/qualifications_component.html.erb
  app/components/qualifications_component.rb
  app/views/support_interface/application_forms/show.html.erb
  spec/components/degree_qualification_cards_component_spec.rb
Labels: Candidate, Support

#2992 Fix a webpacker deprecation warning
  config/webpacker.yml
Labels: Core

#2894 Add offer tab to applications
  app/components/provider_interface/status_box_components/conditions_not_met_component.html.erb
  app/components/provider_interface/status_box_components/course_rows.rb
  app/components/provider_interface/status_box_components/declined_component.html.erb
  app/components/provider_interface/status_box_components/offer_component.html.erb
  app/components/provider_interface/status_box_components/offer_component.rb
  app/components/provider_interface/status_box_components/offer_deferred_component.html.erb
  app/components/provider_interface/status_box_components/offer_withdrawn_component.html.erb
  app/components/provider_interface/status_box_components/pending_conditions_component.html.erb
  app/components/provider_interface/status_box_components/pending_conditions_component.rb
  app/components/provider_interface/status_box_components/recruited_component.html.erb
  app/controllers/provider_interface/application_choices_controller.rb
  app/frontend/styles/_status-box.scss
  app/views/provider_interface/application_choices/offer.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/provider_interface/conditions/edit.html.erb
  config/routes.rb
  spec/system/provider_interface/provider_changes_an_offer_spec.rb
  spec/system/provider_interface/provider_confirms_conditions_met_spec.rb
  spec/system/provider_interface/provider_confirms_conditions_not_met_spec.rb
  spec/system/provider_interface/provider_defers_an_offer_spec.rb
  spec/system/provider_interface/provider_makes_changes_before_offer_spec.rb
  spec/system/provider_interface/provider_withdraws_an_offer_spec.rb
Labels: ProVendor

#2993 Exclude British and Irish sub-nationalities from ‘Other’ nationalities
  app/helpers/select_options_helper.rb
  app/views/candidate_interface/personal_details/nationalities/_shared_form.html.erb
  spec/helpers/select_options_helper_spec.rb
  spec/system/candidate_interface/candidate_entering_personal_details_when_languages_hidden_spec.rb
  spec/system/candidate_interface/international/international_candidate_enters_their_personal_details_spec.rb
  spec/system/candidate_interface/international/international_candidate_submitting_application_spec.rb
Labels: Candidate

#2956 Update TabNavigationComponent elements and styles
  app/components/tab_navigation_component.html.erb
  app/frontend/styles/_tab-navigation.scss
  app/frontend/styles/_tabs.scss
  app/frontend/styles/application.scss
  spec/components/tab_navigation_component_spec.rb
Labels: ProVendor

#2999 Create vendor_api_requests table
  db/migrate/20200928124834_create_vendor_api_requests.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#2996 Update cookie expiry information
  app/views/content/cookies_candidate.md
  app/views/content/cookies_provider.md
  spec/system/candidate_interface/candidate_content_spec.rb
Labels: Core

#2971 Add a rake task to create large numbers of test applications
  app/services/bulk_create_test_applications.rb
  lib/tasks/generate_test_data.rake
Labels: Core

#2960 Load test spike - Apache JMeter
  Gemfile
  Gemfile.lock
  docs/load_testing.md
  lib/tasks/jmeter.rake
Labels: Core

#2997 Include reference ids in API responses
  app/presenters/vendor_api/single_application_presenter.rb
  app/views/api_docs/pages/release_notes.md
  config/vendor-api-v1.yml
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: ProVendor

#3010 Fix data issue where courses are inadvertently accredited to self
  app/services/find_sync/sync_courses_from_find.rb
  spec/services/find_sync/sync_provider_from_find_spec.rb
Labels: ProVendor

#3002 Remove content related to editing an application post submission
  app/components/candidate_interface/application_complete_content_component.html.erb
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/submitted_application_form/submit_success.html.erb
  spec/components/candidate_interface/application_complete_content_component_spec.rb
  spec/services/submit_application_spec.rb
  spec/system/candidate_interface/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/candidate_with_unsuccessful_application_applies_again_spec.rb
Labels: Candidate, Content

#3003 Toggle all courses to have vacancies using a feature flag
  app/models/application_choice.rb
  app/models/course.rb
  app/models/course_option.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/course_choices/course_selection/new.html.erb
  app/views/candidate_interface/course_choices/provider_selection/new.html.erb
  docs/domain-model.png
  spec/system/candidate_interface/candidate_accepts_offer_for_a_course_held_open_spec.rb
Labels: Candidate

#3013 Add new flow for decoupled references (part 1)
  app/controllers/candidate_interface/referees_controller.rb
  app/views/candidate_interface/referees/start.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/candidate_interface/candidate_adding_referees_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_between_cycles_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/candidate_carries_over_unsubmitted_application_without_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/candidate_replaces_reference_after_applying_again_spec.rb
  spec/system/candidate_interface/decoupled_references/candidate_adds_a_new_reference_spec.rb
Labels: Candidate

#3016 Remove not null constraint from the references email address table
  db/migrate/20200930091030_remove_validation_on_referees_email_address.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3018 Fix Zeitwerk loading problems
  app/services/find_sync/sync_error.rb
  config/environments/test.rb
Labels: Core

#3020 Increase debuggability of provider interface problems
  app/controllers/provider_interface/application_choices_controller.rb
  app/controllers/provider_interface/conditions_controller.rb
  app/controllers/provider_interface/decisions_controller.rb
  app/controllers/provider_interface/offer_changes_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/provider_interface/reconfirm_deferred_offers_controller.rb
  app/controllers/support_interface/provider_users_controller.rb
  app/lib/logstash_logging.rb
  config/routes.rb
  spec/requests/provider_interface/account_creation_in_progress_spec.rb
  spec/requests/provider_interface/landing_page_redirect_spec.rb
Labels: Core

#3021 Always enforce user-level make_decisions, even if flags are off
  app/services/make_decisions_authorisation.rb
  spec/requests/provider_interface/provider_relationship_permissions_request_spec.rb
  spec/services/conditions_not_met_spec.rb
  spec/services/confirm_offer_conditions_spec.rb
  spec/services/defer_offer_spec.rb
  spec/services/make_an_offer_spec.rb
  spec/services/provider_authorisation_spec.rb
  spec/services/withdraw_offer_spec.rb
  spec/support/test_helpers/provider_user_permissions_helper.rb
  spec/system/provider_interface/provider_confirms_conditions_met_spec.rb
  spec/system/provider_interface/provider_confirms_conditions_not_met_spec.rb
  spec/system/provider_interface/provider_defers_an_offer_spec.rb
  spec/system/provider_interface/provider_fails_to_select_response_spec.rb
  spec/system/provider_interface/provider_rejects_application_spec.rb
  spec/system/provider_interface/provider_responds_to_application_spec.rb
  spec/system/provider_interface/provider_withdraws_an_offer_spec.rb
Labels: ProVendor

#3025 Remove 'Subject Knowledge' from reference submit page
  app/components/referee_interface/feedback_hints_component.html.erb
Labels: Candidate

#3022 Create a separate DecoupledRefereesController for the new decoupled references implementation
  app/controllers/candidate_interface/decoupled_references_controller.rb
  app/controllers/candidate_interface/referees_controller.rb
  app/views/candidate_interface/decoupled_references/start.html.erb
  app/views/candidate_interface/decoupled_references/type.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/candidate_interface/decoupled_references/candidate_adds_a_new_reference_spec.rb
Labels: Candidate

#2998 Explain what NARIC means
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/components/degree_qualification_cards_component.rb
  app/components/gcse_qualification_cards_component.rb
  app/views/candidate_interface/degrees/naric_statement/_form_fields.html.erb
  app/views/candidate_interface/gcse/naric_reference/edit.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/locales/gcse_details.yml
  spec/components/candidate_interface/degrees_review_component_spec.rb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/components/degree_qualification_cards_component_spec.rb
  spec/components/gcse_qualification_cards_component_spec.rb
  spec/system/candidate_interface/international/candidate_entering_international_degrees_spec.rb
  spec/system/candidate_interface/international/candidate_entering_international_gcse_spec.rb
Labels: Candidate, Content, Provider UI

#3014 Update to gov_back_link_to class and implemented throughout application
  app/frontend/packs/app-back-link.js
  app/helpers/view_helper.rb
  app/views/candidate_interface/degrees/grade/new.html.erb
  app/views/candidate_interface/degrees/institution/new.html.erb
  app/views/candidate_interface/degrees/naric_statement/new.html.erb
  app/views/candidate_interface/degrees/subject/new.html.erb
  app/views/candidate_interface/degrees/year/new.html.erb
  app/views/candidate_interface/english_foreign_language/ielts/edit.html.erb
  app/views/candidate_interface/english_foreign_language/ielts/new.html.erb
  app/views/candidate_interface/english_foreign_language/other_efl_qualification/edit.html.erb
  app/views/candidate_interface/english_foreign_language/other_efl_qualification/new.html.erb
  app/views/candidate_interface/english_foreign_language/start/edit.html.erb
  app/views/candidate_interface/english_foreign_language/start/new.html.erb
  app/views/candidate_interface/english_foreign_language/toefl/edit.html.erb
  app/views/candidate_interface/english_foreign_language/toefl/new.html.erb
  app/views/candidate_interface/english_foreign_language/type/new.html.erb
  app/views/candidate_interface/volunteering/base/new.html.erb
  app/views/candidate_interface/work_history/edit/new.html.erb
  spec/helpers/view_helper_spec.rb
Labels: Candidate

#3026 Re-enable auditing during setup_local_dev_data
  lib/tasks/local_dev.rake
Labels: Core
