Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2020-12, with the labels that each got.

#3517 Service to measure average distances
  app/services/candidate_interface/measure_distances.rb
  spec/services/candidate_interface/measure_distances_spec.rb
Labels: Candidate

#3519 Let candidates proceed if they decide not to add another job
  app/controllers/candidate_interface/work_history/edit_controller.rb
  app/forms/candidate_interface/other_qualification_details_form.rb
  app/forms/candidate_interface/work_experience_form.rb
  app/views/candidate_interface/work_history/edit/new.html.erb
  spec/forms/candidate_interface/other_qualification_details_form_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_blank_work_history_spec.rb
Labels: Candidate

#3511 Populate latitude and longitude on providers when syncing from Find
  app/services/find_sync/sync_provider_from_find.rb
  spec/support/test_helpers/find_api_helper.rb
Labels: Candidate

#3555 DRY up structured reasons for rejection validations
  app/forms/provider_interface/reasons_for_rejection_wizard.rb
Labels: ProVendor

#3557 Add the candidate chaser emails to UCAS matching workflow
  app/components/support_interface/ucas_match_action_component.rb
  app/controllers/support_interface/ucas_matches_controller.rb
  app/mailers/candidate_mailer.rb
  app/models/ucas_match.rb
  app/services/support_interface/send_ucas_match_reminder_emails.rb
  app/views/candidate_mailer/ucas_match_reminder_email_duplicate_applications.text.erb
  app/views/candidate_mailer/ucas_match_reminder_email_multiple_acceptances.text.erb
  config/locales/candidate_mailer.yml
  config/routes.rb
  spec/components/support_interface/ucas_match_action_component_spec.rb
  spec/mailers/candidate_mailer_ucas_match_reminder_email_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/models/ucas_match_spec.rb
  spec/services/support_interface/send_ucas_match_reminder_emails_spec.rb
  spec/system/support_interface/docs_spec.rb
  spec/system/support_interface/ucas_matches_spec.rb
Labels: ProVendor, Support

#3560 Migration to add the find_feedback table
  db/migrate/20201201132605_add_find_feedback_table.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3567 Improve the referee's journey when their references aren't required
  app/controllers/referee_interface/reference_controller.rb
  app/models/application_reference.rb
  app/services/submit_reference.rb
  app/views/referee_interface/reference/finish.html.erb
  spec/system/referee_interface/referee_cannot_provide_reference_if_two_already_received_spec.rb
Labels: Candidate

#3564 Content changes to the reference request email to soften the tone
  app/views/referee_mailer/reference_request_email.text.erb
  spec/system/candidate_interface/references/candidate_requests_a_reference_spec.rb
Labels: Candidate, Content

#3561 Code background on confirmation panels
  app/frontend/styles/_code.scss
  app/views/candidate_interface/submitted_application_form/submit_success.html.erb
  app/views/support_interface/api_tokens/create.html.erb
Labels: Support

#3577 Change original_controller to find_controller
  db/migrate/20201203144318_change_original_controller_to_find_controller.rb
  db/schema.rb
Labels: Candidate

#3578 Create postgre read replica server
  azure/pipelines/templates/deploy.yml
  azure/template.json
Labels: DevOps

#3540 Structured Qualifications Clean Up
  app/components/candidate_interface/gcse_grade_guidance_component.html.erb
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/components/gcse_qualification_cards_component.rb
  app/forms/candidate_interface/english_gcse_grade_form.rb
  app/forms/candidate_interface/science_gcse_grade_form.rb
  app/helpers/gcse_qualification_helper.rb
  app/models/application_qualification.rb
  app/views/candidate_interface/gcse/english/grade/edit.html.erb
  app/views/candidate_interface/gcse/grade/edit.html.erb
  app/views/candidate_interface/gcse/maths/grade/edit.html.erb
  app/views/candidate_interface/gcse/science/grade/awards_edit.html.erb
  app/views/candidate_interface/gcse/science/grade/edit.html.erb
  app/views/candidate_interface/gcse/year/edit.html.erb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  config/locales/application_form.yml
  config/locales/gcse_details.yml
  spec/forms/candidate_interface/english_gcse_grade_form_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_english_gcse_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_science_award_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_science_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_international_gcse_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#3576 Add a 90% threshold to the word count message
  app/views/candidate_interface/work_history/break/_form.html.erb
Labels: Candidate

#3572 Update the decline reference journey
  app/controllers/referee_interface/reference_controller.rb
  app/forms/referee_interface/refuse_feedback_form.rb
  app/views/referee_interface/reference/refuse_feedback.html.erb
  app/views/referee_interface/reference/relationship.html.erb
  app/views/referee_interface/reference/thank_you.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/locales/referee.yml
  config/routes.rb
  spec/forms/referee_interface/refuse_feedback_form_spec.rb
  spec/system/referee_interface/referee_refuses_to_give_a_reference_spec.rb
Labels: Referee

#3581 Set BLAZER_DATABASE_URL to read only Database URL
  azure/template.json
Labels: DevOps

#3587 Remove remaining app-review styling
  app/components/candidate_interface/course_choices_review_component.html.erb
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/incomplete_section_component.html.erb
  app/components/provider_interface/reasons_for_rejection_component.html.erb
  app/frontend/styles/_inset-text.scss
  app/frontend/styles/candidate/_all.scss
  app/frontend/styles/candidate/_review_warning.scss
  spec/components/candidate_interface/incomplete_section_component_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_accepts_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_declines_offer_spec.rb
Labels: Candidate

#3582 Add messaging for more than 2 complete references
  app/components/candidate_interface/references_review_component.html.erb
  app/components/candidate_interface/references_review_component.rb
  app/controllers/candidate_interface/references/review_controller.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/models/application_form.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/unsubmitted_application_form/review.html.erb
  config/locales/application_form.yml
  spec/components/candidate_interface/references_review_component_spec.rb
  spec/models/application_form_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/system/candidate_interface/references/candidate_has_too_many_references_spec.rb
Labels: Candidate

#3552 Notify providers and candidates when a ucas match is resolved
  app/components/support_interface/ucas_match_action_component.rb
  app/mailers/candidate_mailer.rb
  app/mailers/provider_mailer.rb
  app/models/ucas_match.rb
  app/models/ucas_matched_application.rb
  app/services/ucas_matches/resolve_on_apply.rb
  app/services/ucas_matches/resolve_on_ucas.rb
  app/services/ucas_matches/retrieve_for_application_choice.rb
  app/services/ucas_matches/send_resolved_on_apply_emails.rb
  app/services/ucas_matches/send_resolved_on_ucas_emails.rb
  app/services/ucas_matching/process_matching_data.rb
  app/services/withdraw_application.rb
  app/views/candidate_mailer/ucas_match_resolved_on_apply_email.text.erb
  app/views/candidate_mailer/ucas_match_resolved_on_ucas_email.text.erb
  app/views/provider_mailer/ucas_match_resolved_on_apply_email.text.erb
  app/views/provider_mailer/ucas_match_resolved_on_ucas_email.text.erb
  config/locales/candidate_mailer.yml
  config/locales/provider_mailer.yml
  spec/components/support_interface/ucas_match_action_component_spec.rb
  spec/mailers/candidate_mailer_ucas_match_emails_spec.rb
  spec/mailers/provider_mailer_spec.rb
  spec/models/ucas_match_spec.rb
  spec/models/ucas_matched_application_spec.rb
  spec/services/ucas_matches/resolve_on_apply_spec.rb
  spec/services/ucas_matches/resolve_on_ucas_spec.rb
  spec/services/ucas_matches/send_resolved_on_apply_emails_spec.rb
  spec/services/ucas_matches/send_resolved_on_ucas_emails_spec.rb
  spec/services/withdraw_application_spec.rb
  spec/system/support_interface/docs_spec.rb
  spec/system/support_interface/ucas_matches_spec.rb
Labels: ProVendor

#3558 Update the new provider sync service to grab lat, long & provider_type
  app/services/teacher_training_public_api/sync_provider.rb
  spec/examples/teacher_training_api/single_provider_response.json
Labels: Candidate

#3592 Remove banner style dependency from incomplete section component (follow up)
  app/frontend/styles/_banner.scss
  app/views/candidate_interface/unsubmitted_application_form/review.html.erb
  spec/system/candidate_interface/submitting/candidate_submitting_application_spec.rb
Labels: Candidate

#3589 Transparent header border colour on app-start-page
  app/frontend/styles/_header.scss
  app/frontend/styles/_phase-banner.scss
Labels: Provider UI

#3590 Fix bug that stops import from ucas
  app/services/ucas_matching/file_download_check.rb
  app/services/ucas_matching/process_matching_data.rb
  config/initializers/okcomputer.rb
  spec/services/ucas_matching/file_download_check_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: ProVendor

#3598 Use govuk-list--spaced modifier
  app/components/provider_interface/reasons_for_rejection_component.html.erb
  app/frontend/styles/provider/_reject.scss
Labels: Provider UI

#3562 Activity log for application events across a provider user's providers
  app/components/provider_interface/activity_log_event_component.html.erb
  app/components/provider_interface/activity_log_event_component.rb
  app/controllers/provider_interface/activity_log_controller.rb
  app/frontend/styles/provider/_timeline.scss
  app/helpers/navigation_items.rb
  app/lib/activity_log_event.rb
  app/queries/get_activity_log_events.rb
  app/queries/get_application_choices_for_providers.rb
  app/services/feature_flag.rb
  app/services/filter_application_choices_for_providers.rb
  app/views/layouts/previews/provider.html.erb
  app/views/provider_interface/activity_log/index.html.erb
  config/routes.rb
  spec/components/previews/provider_interface/activity_log_event_component_preview.rb
  spec/components/provider_interface/activity_log_event_component_spec.rb
  spec/factories.rb
  spec/queries/get_activity_log_events_spec.rb
  spec/system/provider_interface/see_activity_log_spec.rb
  spec/system/provider_interface/see_application_after_provider_change_spec.rb
Labels: ProVendor

#3593 Bug fix - Reference is no longer required (guidance)
  app/controllers/referee_interface/reference_controller.rb
  app/views/referee_interface/reference/finish.html.erb
  spec/system/referee_interface/referee_can_submit_a_reference_for_candidate_with_relationship_and_safeguarding_spec.rb
  spec/system/referee_interface/referee_cannot_provide_reference_if_two_already_received_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#3586 Update database replica server connection string
  azure/template.json
Labels: DevOps

#3608 Add average distance to site to the provider export
  app/services/support_interface/providers_export.rb
  spec/services/support_interface/providers_export_spec.rb
Labels: Candidate

#3595 Add Last action taken filter to UCAS Matches page
  app/models/support_interface/ucas_matches_filter.rb
  spec/system/support_interface/ucas_matches_spec.rb
Labels: ProVendor, Support

#3607 Store an offer_changed_at timestamp for ChangeOffer events
  app/services/change_offer.rb
  app/services/set_decline_by_default.rb
  db/migrate/20201207175009_add_offer_changed_at_to_application_choice.rb
  db/schema.rb
  docs/domain-model.png
  spec/services/change_offer_spec.rb
  spec/services/set_decline_by_default_spec.rb
Labels: ProVendor

#3606 Format govuk_date_and_time and govuk_time according to the style guide
  config/initializers/date_formats.rb
  spec/components/support_interface/ucas_match_action_component_spec.rb
  spec/config/initializers/date_formats_spec.rb
Labels: Core

#3610 Further fixes for inaccurate geocoding results
  app/services/geocode_filter.rb
  app/workers/geocode_application_address_worker.rb
  lib/tasks/geocode.rake
  spec/workers/geocode_application_address_worker_spec.rb
Labels: Candidate

#3613 Bug fix - editing 'other' qualifications
  app/controllers/candidate_interface/other_qualifications/review_controller.rb
  app/forms/candidate_interface/other_qualification_type_form.rb
  app/views/candidate_interface/other_qualifications/details/edit.html.erb
  spec/forms/candidate_interface/other_qualification_type_form_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#3609 Add edit functionality for date of birth to to support UI
  app/components/support_interface/personal_details_component.rb
  app/controllers/support_interface/application_forms/applicant_details_controller.rb
  app/forms/support_interface/application_forms/edit_applicant_details_form.rb
  app/views/support_interface/application_forms/applicant_details/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/support_interface/editing_applicant_details_spec.rb
Labels: Candidate

#3579 Update BTEC page
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/forms/candidate_interface/other_qualification_details_form.rb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  spec/system/candidate_interface/entering_details/candidate_entering_other_qualification_btec_spec.rb
Labels: Candidate

#3626 Fix a typo in UCASMatches namespace
  app/services/ucas_matching/process_matching_data.rb
Labels: ProVendor

#3622 Include paragraph detailing RBD date when a user cannot make decisions
  app/components/provider_interface/application_choice_header_component.html.erb
  app/components/provider_interface/application_choice_header_component.rb
  spec/components/provider_interface/application_choice_header_component_spec.rb
Labels: ProVendor

#3616 Add manually resolved action_taken to UCASMatch
  app/components/support_interface/ucas_match_action_component.rb
  app/models/ucas_match.rb
  spec/components/support_interface/ucas_match_action_component_spec.rb
  spec/models/ucas_match_spec.rb
Labels: ProVendor

#3624 Add edit functionality to email address attribute on Support UI
  app/components/support_interface/personal_details_component.rb
  app/controllers/support_interface/application_forms/applicant_details_controller.rb
  app/forms/support_interface/application_forms/edit_applicant_details_form.rb
  app/views/support_interface/application_forms/applicant_details/edit.html.erb
  config/locales/en.yml
  spec/system/support_interface/editing_applicant_details_spec.rb
Labels: Support

#3627 Strip whitespace from candidate input
  Gemfile
  Gemfile.lock
  app/controllers/candidate_interface/application_feedback_controller.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/candidate_interface/contact_details/address_type_controller.rb
  app/controllers/candidate_interface/contact_details/base_controller.rb
  app/controllers/candidate_interface/contact_details/review_controller.rb
  app/controllers/candidate_interface/degrees/grade_controller.rb
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/controllers/candidate_interface/degrees/naric_controller.rb
  app/controllers/candidate_interface/degrees/review_controller.rb
  app/controllers/candidate_interface/degrees/subject_controller.rb
  app/controllers/candidate_interface/degrees/type_controller.rb
  app/controllers/candidate_interface/degrees/year_controller.rb
  app/controllers/candidate_interface/english_foreign_language/ielts_controller.rb
  app/controllers/candidate_interface/english_foreign_language/other_efl_qualification_controller.rb
  app/controllers/candidate_interface/english_foreign_language/review_controller.rb
  app/controllers/candidate_interface/english_foreign_language/start_controller.rb
  app/controllers/candidate_interface/english_foreign_language/toefl_controller.rb
  app/controllers/candidate_interface/english_foreign_language/type_controller.rb
  app/controllers/candidate_interface/feedback_form_controller.rb
  app/controllers/candidate_interface/gcse/details_controller.rb
  app/controllers/candidate_interface/gcse/english/grade_controller.rb
  app/controllers/candidate_interface/gcse/maths/grade_controller.rb
  app/controllers/candidate_interface/gcse/naric_controller.rb
  app/controllers/candidate_interface/gcse/review_controller.rb
  app/controllers/candidate_interface/gcse/science/grade_controller.rb
  app/controllers/candidate_interface/gcse/type_controller.rb
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/controllers/candidate_interface/other_qualifications/review_controller.rb
  app/controllers/candidate_interface/other_qualifications/type_controller.rb
  app/controllers/candidate_interface/personal_details/base_controller.rb
  app/controllers/candidate_interface/personal_details/languages_controller.rb
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/controllers/candidate_interface/personal_details/review_controller.rb
  app/controllers/candidate_interface/personal_details/right_to_work_or_study_controller.rb
  app/controllers/candidate_interface/personal_statement/becoming_a_teacher_controller.rb
  app/controllers/candidate_interface/personal_statement/interview_preferences_controller.rb
  app/controllers/candidate_interface/personal_statement/subject_knowledge_controller.rb
  app/controllers/candidate_interface/references/candidate_name_controller.rb
  app/controllers/candidate_interface/references/email_address_controller.rb
  app/controllers/candidate_interface/references/name_controller.rb
  app/controllers/candidate_interface/references/relationship_controller.rb
  app/controllers/candidate_interface/references/retry_request_controller.rb
  app/controllers/candidate_interface/safeguarding_controller.rb
  app/controllers/candidate_interface/start_page_controller.rb
  app/controllers/candidate_interface/training_with_a_disability_controller.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/controllers/candidate_interface/volunteering/base_controller.rb
  app/controllers/candidate_interface/volunteering/experience_controller.rb
  app/controllers/candidate_interface/volunteering/review_controller.rb
  app/controllers/candidate_interface/work_history/break_controller.rb
  app/controllers/candidate_interface/work_history/breaks_controller.rb
  app/controllers/candidate_interface/work_history/edit_controller.rb
  app/controllers/candidate_interface/work_history/explanation_controller.rb
  app/controllers/candidate_interface/work_history/length_controller.rb
  app/controllers/candidate_interface/work_history/review_controller.rb
  app/lib/strip_whitespace.rb
  spec/lib/strip_whitespace_spec.rb
Labels: Candidate

#3563 Add the find feedback page
  app/controllers/candidate_interface/find_feedback_controller.rb
  app/forms/candidate_interface/find_feedback_form.rb
  app/models/find_feedback.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/find_feedback/new.html.erb
  app/views/candidate_interface/find_feedback/thank_you.html.erb
  config/locales/application_form.yml
  config/locales/en.yml
  config/locales/find_feedback.yml
  config/routes.rb
  spec/forms/candidate_interface/find_feedback_form_spec.rb
  spec/system/candidate_interface/feedback/candidate_arrives_from_find_to_provide_feedback_spec.rb
Labels: Candidate

#3583 Remove matchedstate from ucas matches
  app/components/support_interface/ucas_matches_table_component.rb
  app/controllers/support_interface/ucas_matches_controller.rb
  app/models/ucas_match.rb
  app/services/ucas_matching/process_matching_data.rb
  app/views/support_interface/ucas_matches/show.html.erb
  config/routes.rb
  spec/components/support_interface/application_summary_component_spec.rb
  spec/components/support_interface/ucas_match_action_component_spec.rb
  spec/components/support_interface/ucas_matches_table_component_spec.rb
  spec/factories.rb
  spec/models/ucas_match_spec.rb
  spec/services/support_interface/send_ucas_match_reminder_emails_spec.rb
  spec/system/support_interface/ucas_matches_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: ProVendor

#3633 Update referee guidance to inform them to complete their ref in one sitting
  app/components/referee_interface/feedback_hints_component.html.erb
Labels: Candidate, Content

#3639 When managing a user’s providers, order them by name
  app/forms/support_interface/provider_user_form.rb
Labels: Support

#3630 Include change offer events in timeline and activity log
  app/components/provider_interface/activity_log_event_component.rb
  app/components/provider_interface/application_timeline_component.html.erb
  app/components/provider_interface/application_timeline_component.rb
  app/lib/activity_log_event.rb
  app/lib/test_applications.rb
  app/models/course.rb
  app/queries/find_status_change_audits.rb
  app/queries/get_activity_log_events.rb
  app/services/make_an_offer.rb
  app/workers/generate_test_applications.rb
  spec/components/previews/provider_interface/activity_log_event_component_preview.rb
  spec/components/provider_interface/activity_log_event_component_spec.rb
  spec/components/provider_interface/application_timeline_component_spec.rb
  spec/factories.rb
  spec/queries/find_status_change_audits_spec.rb
  spec/services/make_an_offer_spec.rb
Labels: ProVendor

#3618 Display accredited body on applications in support
  app/components/support_interface/application_choice_component.html.erb
  app/components/support_interface/application_choice_component.rb
  app/components/support_interface/course_name_and_status_component.html.erb
  app/components/support_interface/course_name_and_status_component.rb
  app/components/support_interface/location_status_component.html.erb
  app/components/support_interface/location_status_component.rb
Labels: Support

#3635 Remove the withdraw link from states with accepted offers
  app/components/provider_interface/status_box_components/offer_deferred_component.html.erb
  app/components/provider_interface/status_box_components/pending_conditions_component.html.erb
  spec/system/provider_interface/provider_defers_an_offer_spec.rb
Labels: Bug bash 🐞🔨, ProVendor

#3620 Add csv export for application data
  app/decorators/application_choice_export_decorator.rb
  app/models/application_form.rb
  app/models/application_qualification.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/data_set_documentation.rb
  app/services/provider_interface/application_data_export.rb
  app/services/provider_interface/hesa_data_export.rb
  spec/decorators/application_choice_export_decorator_spec.rb
  spec/factories.rb
  spec/models/application_qualification_spec.rb
  spec/services/provider_interface/application_data_export_spec.rb
  spec/services/provider_interface/hesa_data_export_spec.rb
  spec/system/provider_interface/export_applications_spec.rb
Labels: ProVendor

#3643 Remove the :efl_section feature flag
  app/controllers/candidate_interface/english_foreign_language/ielts_controller.rb
  app/controllers/candidate_interface/english_foreign_language/other_efl_qualification_controller.rb
  app/controllers/candidate_interface/english_foreign_language/start_controller.rb
  app/controllers/candidate_interface/english_foreign_language/toefl_controller.rb
  app/controllers/candidate_interface/english_foreign_language/type_controller.rb
  app/models/application_form.rb
  app/services/feature_flag.rb
  app/services/languages_section_policy.rb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/models/application_form_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/services/languages_section_policy_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/support/test_helpers/efl_helper.rb
  spec/system/candidate_interface/entering_details/add_other_qualification_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_when_languages_hidden_spec.rb
  spec/system/candidate_interface/entering_details/change_qualification_spec.rb
  spec/system/candidate_interface/entering_details/declare_no_qualification_spec.rb
  spec/system/candidate_interface/entering_details/declare_qualification_not_needed_spec.rb
  spec/system/candidate_interface/entering_details/international_candidate_enters_their_personal_details_spec.rb
  spec/system/candidate_interface/entering_details/view_efl_form_spec.rb
  spec/system/candidate_interface/entering_details/your_ielts_results_spec.rb
  spec/system/candidate_interface/entering_details/your_toefl_result_spec.rb
  spec/system/candidate_interface/submitting/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: Candidate

#3652 Remove the find_feedback feature flag
  app/services/feature_flag.rb
  spec/system/candidate_interface/feedback/candidate_arrives_from_find_to_provide_feedback_spec.rb
Labels: Candidate

#3658 Update copy on ‘terms of use’ page
  app/views/content/terms_candidate.md
Labels: Candidate, Content

#3634 Enable 'add a course' in support interface
  app/components/support_interface/application_add_course_component.html.erb
  app/components/support_interface/application_add_course_component.rb
  app/controllers/support_interface/application_forms/courses_controller.rb
  app/forms/support_interface/application_forms/course_search_form.rb
  app/forms/support_interface/application_forms/pick_course_form.rb
  app/views/support_interface/application_forms/courses/new.html.erb
  app/views/support_interface/application_forms/courses/new_search.html.erb
  app/views/support_interface/application_forms/show.html.erb
  config/locales/support_interface.yml
  config/routes.rb
  spec/components/support_interface/application_add_course_component_spec.rb
  spec/forms/support_interface/application_forms/course_search_form_spec.rb
  spec/forms/support_interface/application_forms/pick_course_form_spec.rb
  spec/system/support_interface/add_course_to_submitted_application_spec.rb
Labels: Support

#3653 Provide a list of possible GCSE/A-Level autocomplete values in the API
  app/controllers/vendor_api/reference_data_controller.rb
  app/views/api_docs/pages/home.md
  app/views/api_docs/pages/release_notes.md
  config/routes.rb
  config/vendor-api-v1.yml
  spec/requests/vendor_api/get_reference_data_spec.rb
Labels: ProVendor

#3621 UCASMatch#matching state removal migration
  db/migrate/20201210145233_remove_matching_state_from_ucas_matches.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#3654 Document international address changes in the API
  app/views/api_docs/pages/release_notes.md
  config/vendor-api-v1.yml
Labels: ProVendor

#3588 Automate sending of initial and reminder emails about UCAS matches
  app/components/support_interface/ucas_match_action_component.html.erb
  app/components/support_interface/ucas_match_action_component.rb
  app/controllers/support_interface/ucas_matches_controller.rb
  app/models/ucas_match.rb
  app/services/support_interface/send_ucas_match_initial_emails.rb
  app/services/ucas_matches/record_action_taken.rb
  app/services/ucas_matches/resolve_on_apply.rb
  app/services/ucas_matches/resolve_on_ucas.rb
  app/services/ucas_matches/send_ucas_match_emails.rb
  app/services/ucas_matches/send_ucas_match_initial_emails.rb
  app/services/ucas_matches/send_ucas_match_initial_emails_duplicate_applications.rb
  app/services/ucas_matches/send_ucas_match_initial_emails_multiple_acceptances.rb
  app/services/ucas_matches/send_ucas_match_reminder_emails.rb
  app/services/ucas_matching/process_matching_data.rb
  config/routes.rb
  spec/components/support_interface/ucas_match_action_component_spec.rb
  spec/models/ucas_match_spec.rb
  spec/services/support_interface/send_ucas_match_initial_emails_spec.rb
  spec/services/ucas_matches/record_action_taken_spec.rb
  spec/services/ucas_matches/resolve_on_apply_spec.rb
  spec/services/ucas_matches/resolve_on_ucas_spec.rb
  spec/services/ucas_matches/send_ucas_match_emails_spec.rb
  spec/services/ucas_matches/send_ucas_match_initial_emails_duplicate_applications_spec.rb
  spec/services/ucas_matches/send_ucas_match_initial_emails_multiple_acceptances_spec.rb
  spec/services/ucas_matches/send_ucas_match_initial_emails_spec.rb
  spec/services/ucas_matches/send_ucas_match_reminder_emails_spec.rb
  spec/system/support_interface/ucas_matches_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: ProVendor

#3644 Allow support users to update references in support
  app/components/support_interface/reference_with_feedback_component.html.erb
  app/components/support_interface/reference_with_feedback_component.rb
  app/controllers/support_interface/application_forms/references_controller.rb
  app/forms/support_interface/application_forms/edit_reference_details_form.rb
  app/forms/support_interface/application_forms/edit_reference_feedback_form.rb
  app/services/submit_reference.rb
  app/views/support_interface/application_forms/references/edit_reference_details.html.erb
  app/views/support_interface/application_forms/references/edit_reference_feedback.html.erb
  config/locales/en.yml
  config/locales/support_interface.yml
  config/routes.rb
  spec/system/support_interface/editing_reference_spec.rb
Labels: Support

#3675 Migration to rename authenticable_id and authenticable_type to user_id and user_type
  db/migrate/20201215200431_add_user_id_and_user_type_columns.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3676 Make authenticable_id & authenticable_type nullable
  db/migrate/20201217121006_make_authenticable_id_and_type_columns_nullable.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3663 Return domicile values consistent with HESA codes, not ISO 3166-2
  app/components/support_interface/personal_details_component.rb
  app/lib/domicile_resolver.rb
  app/models/application_form.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/provider_interface/application_data_export.rb
  app/services/provider_interface/hesa_data_export.rb
  app/views/api_docs/pages/release_notes.md
  config/vendor-api-v1.yml
  spec/components/support_interface/personal_details_component_spec.rb
  spec/lib/domicile_resolver_spec.rb
  spec/models/application_form_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/services/provider_interface/application_data_export_spec.rb
  spec/services/provider_interface/hesa_data_export_spec.rb
  spec/system/provider_interface/export_applications_in_hesa_format_spec.rb
  spec/system/support_interface/editing_reference_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: ProVendor

#3660 Emails for structured reasons for rejection
  app/lib/test_applications.rb
  app/mailers/candidate_mailer.rb
  app/presenters/rejected_application_choice_presenter.rb
  app/services/send_candidate_rejection_email.rb
  app/views/candidate_mailer/_application_rejected_intro.text.erb
  app/views/candidate_mailer/_get_support.text.erb
  app/views/candidate_mailer/_reasons_for_rejection.text.erb
  app/views/candidate_mailer/_rejected_by_default_intro.text.erb
  app/views/candidate_mailer/application_rejected_all_applications_rejected.text.erb
  app/views/candidate_mailer/application_rejected_all_rejected.text.erb
  app/views/candidate_mailer/application_rejected_awaiting_decision_only.text.erb
  app/views/candidate_mailer/application_rejected_awaiting_decisions.text.erb
  app/views/candidate_mailer/application_rejected_offers_made.text.erb
  app/views/candidate_mailer/application_rejected_offers_only.text.erb
  app/views/candidate_mailer/application_rejected_one_offer_one_awaiting_decision.text.erb
  config/locales/application_states.yml
  config/locales/candidate_mailer.yml
  config/locales/reasons_for_rejection.yml
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/presenters/rejected_application_choice_presenter_spec.rb
  spec/services/send_candidate_rejection_email_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_receives_rejection_email_spec.rb
  spec/system/reject_by_default_spec.rb
Labels: ProVendor

#3611 Allow candidates and providers to use old magic links
  app/controllers/candidate_interface/sign_in_controller.rb
  app/controllers/candidate_interface/sign_up_controller.rb
  app/mailers/candidate_mailer.rb
  app/models/authentication_token.rb
  app/models/candidate.rb
  app/models/concerns/authenticated_using_magic_links.rb
  app/models/support_user.rb
  app/queries/find_candidate_by_token.rb
  app/services/candidate_interface/request_magic_link.rb
  app/services/candidate_interface/sign_in_candidate.rb
  app/services/magic_link_sign_in.rb
  app/services/magic_link_sign_up.rb
  app/services/support_interface/magic_link_authentication.rb
  db/migrate/20201215211124_backfill_authentication_tokens.rb
  db/migrate/20201217114113_backfill_user_id_and_user_type_columns.rb
  docs/domain-model.png
  spec/factories.rb
  spec/models/candidate_spec.rb
  spec/services/support_interface/magic_link_authentication_spec.rb
  spec/support/test_helpers/mailer_setup_helper.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_with_the_penultimate_valid_token_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_up_using_magic_link_with_an_invalid_token_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_tries_to_reuse_magic_link_spec.rb
Labels: Core

#3671 Refactor entering degrees spec
  spec/system/candidate_interface/entering_details/candidate_entering_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_delete_and_replace_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_editing_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_degree_with_missing_information_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_degree_with_predicted_grade_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_international_degrees_spec.rb
Labels: Candidate

#3678 Fix typo in migration
  db/migrate/20201217114113_backfill_user_id_and_user_type_columns.rb
Labels: Candidate

#3664 Update email subject lines
  app/mailers/candidate_mailer.rb
  app/mailers/provider_mailer.rb
  app/mailers/support_mailer.rb
  config/locales/authentication.yml
  config/locales/candidate_mailer.yml
  config/locales/chaser_emails.yml
  config/locales/new_offer_emails.yml
  config/locales/provider_mailer.yml
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/provider_mailer_spec.rb
  spec/system/referee_interface/referee_does_not_respond_spec.rb
  spec/system/support_interface/authentication_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: Candidate, Content, ProVendor

#3674 Add ability to edit candidate addresses
  app/components/support_interface/personal_details_component.rb
  app/controllers/support_interface/application_forms/address_details_controller.rb
  app/controllers/support_interface/application_forms/address_type_controller.rb
  app/forms/support_interface/application_forms/edit_address_details_form.rb
  app/views/support_interface/application_forms/address_details/edit.html.erb
  app/views/support_interface/application_forms/address_type/edit.html.erb
  config/locales/en.yml
  config/locales/support_interface.yml
  config/routes.rb
  spec/forms/support_interface/application_forms/edit_address_details_form_spec.rb
  spec/system/support_interface/editing_address_details_spec.rb
Labels: Support

#3683 Remove duplicate assignments to @application_form
  app/mailers/candidate_mailer.rb
  spec/mailers/candidate_mailer_spec.rb
Labels: Candidate

#3670 Add nationality editing to support interface
  app/components/support_interface/personal_details_component.rb
  app/controllers/support_interface/application_forms/nationalities_controller.rb
  app/controllers/support_interface/application_forms/right_to_work_or_study_controller.rb
  app/forms/candidate_interface/right_to_work_or_study_form.rb
  app/forms/support_interface/application_forms/nationalities_form.rb
  app/forms/support_interface/application_forms/right_to_work_or_study_form.rb
  app/views/support_interface/application_forms/nationalities/edit.html.erb
  app/views/support_interface/application_forms/right_to_work_or_study/edit.html.erb
  config/routes.rb
  spec/system/support_interface/editing_applicant_details_spec.rb
Labels: Candidate, Support

#3679 Add an api key to local dev and review app data
  lib/tasks/local_dev.rake
Labels: ProVendor

#3677 Add ApplicationResponseCaches table
  app/models/application_response_cache.rb
  db/migrate/20201217151221_create_application_response_caches.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#3686 Remove UCASMatch emails from Notifications check
  app/services/ucas_matches/send_resolved_on_apply_emails.rb
  app/services/ucas_matches/send_resolved_on_ucas_emails.rb
  app/services/ucas_matches/send_ucas_match_initial_emails_duplicate_applications.rb
  spec/factories.rb
  spec/services/accept_offer_spec.rb
  spec/services/send_application_to_provider_spec.rb
  spec/services/send_new_application_email_to_provider_spec.rb
  spec/support/test_helpers/dfe_sign_in_helpers.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_accepts_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_declines_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_withdraws_spec.rb
  spec/system/decline_by_default_spec.rb
  spec/system/provider_interface/sandbox_emails_spec.rb
  spec/system/reject_by_default_spec.rb
Labels: ProVendor

#3684 Add international addresses to Support UI
  app/components/support_interface/personal_details_component.rb
  app/forms/support_interface/application_forms/edit_address_details_form.rb
  app/views/support_interface/application_forms/address_details/edit.html.erb
  config/locales/en.yml
  spec/forms/support_interface/application_forms/edit_address_details_form_spec.rb
  spec/system/support_interface/editing_address_details_spec.rb
Labels: Support

#3665 Add provide and refuse feedback links in the support UI
  app/components/support_interface/reference_with_feedback_component.rb
  spec/system/support_interface/provide_or_refuse_feedback_for_a_feedback_requested_reference_spec.rb
Labels: Referee

#3673 Provider users can configure their notifications
  app/controllers/provider_interface/notifications_controller.rb
  app/views/provider_interface/account/show.html.erb
  app/views/provider_interface/notifications/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/provider_interface/account_page_spec.rb
  spec/system/provider_interface/manage_provider_user_notifications_spec.rb
Labels: ProVendor

#3691 Streamline process of adding JS autocompletes - round 1
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/frontend/packs/application-candidate.js
  app/frontend/packs/application-support.js
  app/frontend/packs/autocompletes/api-token-autocomplete.js
  app/frontend/packs/autocompletes/country-autocomplete.js
  app/frontend/packs/autocompletes/courses-autocomplete.js
  app/frontend/packs/autocompletes/nationality-autocomplete.js
  app/frontend/packs/autocompletes/providers-autocomplete.js
  app/frontend/packs/autosuggests/degree-grade-autosuggest.js
  app/frontend/packs/autosuggests/degree-institution-autosuggest.js
  app/frontend/packs/autosuggests/degree-subject-autosuggest.js
  app/frontend/packs/autosuggests/degree-type-autosuggest.js
  app/frontend/packs/autosuggests/helpers.js
  app/frontend/packs/autosuggests/other-qualifications-grade-autosuggest.js
  app/frontend/packs/autosuggests/other-qualifications-subject-autosuggest.js
  app/frontend/packs/autosuggests/other-uk-qualifications-type-autosuggest.js
  app/frontend/packs/gcse-grade-autocomplete.js
  app/frontend/packs/helpers.js
  app/frontend/packs/ielts-band-score-autocomplete.js
  app/views/candidate_interface/degrees/grade/_form_fields.html.erb
  app/views/candidate_interface/degrees/institution/_form_fields.html.erb
  app/views/candidate_interface/degrees/subject/_form_fields.html.erb
  app/views/candidate_interface/degrees/type/_form_fields.html.erb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  app/views/candidate_interface/other_qualifications/details/edit.html.erb
  app/views/candidate_interface/other_qualifications/details/new.html.erb
  app/views/candidate_interface/other_qualifications/type/_shared_form.html.erb
  spec/system/candidate_interface/entering_details/candidate_entering_other_qualification_spec.rb
Labels: Core

#3682 Move UCASMatch file download check to worker
  app/workers/ucas_integration_check.rb
  config/clock.rb
  config/initializers/okcomputer.rb
  spec/workers/ucas_integration_check_spec.rb
Labels: ProVendor

#3692 Return iso8601 values for DEGSTDT, DEGENDDT in HESA export
  app/decorators/application_choice_export_decorator.rb
  app/services/provider_interface/application_data_export.rb
  app/services/provider_interface/hesa_data_export.rb
  spec/factories.rb
  spec/requests/provider_interface/provider_user_impersonates_candidate_spec.rb
  spec/services/provider_interface/application_data_export_spec.rb
  spec/services/provider_interface/hesa_data_export_spec.rb
Labels: ProVendor

#3696 Add last_public_update_at to application choices
  db/migrate/20201217161757_add_last_public_update_at_to_application_choices.rb
  db/schema.rb
  docs/domain-model.png
Labels: Core

#3669 Surface structured reasons for rejection in the API
  app/presenters/vendor_api/rejection_reason_presenter.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/views/api_docs/pages/release_notes.md
  config/vendor-api-v1.yml
  spec/presenters/vendor_api/rejection_reason_presenter_spec.rb
Labels: ProVendor

#3680 Add a support UI filter for provider users who have never signed in
  app/controllers/support_interface/provider_users_controller.rb
  app/models/support_interface/provider_users_filter.rb
  spec/system/support_interface/managing_provider_users_spec.rb
Labels: ProVendor

#3704 Remove unnecessary validation from EditApplicantDetailsForm
  app/forms/support_interface/application_forms/edit_applicant_details_form.rb
Labels: Support

#3705 Unique labels for feature flag buttons
  app/views/support_interface/settings/feature_flags.html.erb
Labels: Accessibility, Support

#3702 Automate courses open provider email
  app/mailers/provider_mailer.rb
  app/services/open_provider_courses.rb
  app/views/provider_mailer/courses_open_on_apply.text.erb
  config/locales/provider_mailer.yml
  spec/factories.rb
  spec/mailers/previews/provider_mailer_preview.rb
  spec/mailers/provider_mailer_spec.rb
  spec/services/open_provider_courses_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: ProVendor

#3706 Show filetype on download buttons
  app/views/provider_interface/application_data_export/new.html.erb
  app/views/provider_interface/hesa_export/new.html.erb
  app/views/support_interface/data_exports/show.html.erb
Labels: Accessibility, Provider UI, Support

#3713 Add additional context to links with duplicate labels
  app/components/support_interface/provider_users_table_component.html.erb
  app/components/support_interface/reference_with_feedback_component.rb
  app/helpers/view_helper.rb
  app/views/support_interface/support_users/index.html.erb
  spec/system/support_interface/remove_and_restore_a_support_user_spec.rb
Labels: Accessibility, Support

#3715 Ensure pages have unique titles
  app/views/candidate_interface/apply_from_find/apply_on_ucas_only.html.erb
  app/views/candidate_interface/apply_from_find/not_found.html.erb
  app/views/candidate_interface/prefill_application_form/new.html.erb
  app/views/candidate_interface/start_page/applications_closed.html.erb
  app/views/candidate_interface/start_page/create_account_or_sign_in.html.erb
  app/views/provider_interface/decisions/confirm_offer.html.erb
  app/views/provider_interface/decisions/confirm_reject.html.erb
  app/views/provider_interface/decisions/confirm_withdraw_offer.html.erb
  app/views/provider_interface/decisions/new_defer_offer.html.erb
  app/views/provider_interface/decisions/new_edit_response.html.erb
  app/views/provider_interface/decisions/new_offer.html.erb
  app/views/provider_interface/decisions/new_reject.html.erb
  app/views/provider_interface/decisions/new_withdraw_offer.html.erb
  app/views/provider_interface/decisions/respond.html.erb
  app/views/provider_interface/email_address_not_recognised.html.erb
  app/views/provider_interface/start_page/show.html.erb
  app/views/support_interface/unauthorized.html.erb
  config/locales/apply_from_find.yml
  config/locales/en.yml
  spec/system/candidate_interface/course_selection/candidate_apply_from_find_spec.rb
  spec/system/support_interface/editing_applicant_details_spec.rb
Labels: Accessibility, Candidate, Provider UI

#3693 Return prevalent nationality for HESA export
  app/decorators/application_choice_hesa_export_decorator.rb
  app/services/provider_interface/hesa_data_export.rb
  config/initializers/nationalities.rb
  spec/decorators/application_choice_hesa_export_decorator_spec.rb
  spec/services/provider_interface/hesa_data_export_spec.rb
Labels: ProVendor

#3710 Remove ambiguous graphics from accessibility tree
  app/components/state_diagram_component.html.erb
  app/components/state_diagram_component.rb
  app/components/state_event_explanation_component.html.erb
  app/components/state_explanation_component.html.erb
  app/components/when_emails_are_sent_component.html.erb
  app/frontend/styles/_diagram.scss
  app/frontend/styles/application.scss
  app/frontend/styles/support/_all.scss
  app/frontend/styles/support/_relationship-diagram.scss
  app/lib/state_diagram.rb
  app/views/api_docs/pages/lifecycle.html.erb
  app/views/support_interface/docs/candidate_flow.html.erb
  app/views/support_interface/docs/provider_flow.html.erb
  app/views/support_interface/docs/when_emails_are_sent.html.erb
  app/views/support_interface/providers/users.html.erb
Labels: API docs, Accessibility, Support

#3656 Structured reasons for rejection for previous applications in candidate interface
  app/components/candidate_interface/rejection_reasons_component.html.erb
  app/components/candidate_interface/rejection_reasons_component.rb
  spec/components/candidate_interface/rejection_reasons_component_spec.rb
  spec/system/candidate_interface/rejection/candidate_reviews_reasons_for_rejection_spec.rb
Labels: Candidate

#3718 Reinstate missing label for deprecated work breaks page
  app/views/candidate_interface/work_history/breaks/edit.html.erb
  config/locales/application_form.yml
Labels: Candidate

#3722 Unique sub-section label for candidate accounts in support
  app/components/support_interface/candidates_table_component.html.erb
  app/views/support_interface/application_forms/_application_navigation.html.erb
  app/views/support_interface/candidates/_candidates_navigation.html.erb
  app/views/support_interface/candidates/show.html.erb
Labels: Accessibility, Support

#3712 Improve sites data export
  app/models/site.rb
  app/services/support_interface/sites_export.rb
  spec/services/support_interface/sites_export_spec.rb
Labels: Support

#3719 Different namespaces for service feedback and application rejection styles
  app/components/candidate_interface/application_feedback_component.html.erb
  app/components/reasons_for_rejection_component.html.erb
  app/frontend/styles/_feedback.scss
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_rejection.scss
  spec/components/provider_interface/reasons_for_rejection_component_spec.rb
  spec/components/reasons_for_rejection_component_spec.rb
Labels: Candidate, Provider UI

#3720 Remove ambiguous form labelling on nationality forms
  app/frontend/packs/nationalities-component.js
  app/frontend/styles/candidate/_nationalities.scss
  app/views/candidate_interface/personal_details/nationalities/_shared_form.html.erb
  app/views/support_interface/application_forms/nationalities/edit.html.erb
Labels: Accessibility, Candidate, Support

#3708 Hide Sign in link in header when on Sign in page
  app/helpers/navigation_items.rb
Labels: ProVendor

#3709 Make user_id & user_not not nullable and add index to AuthenticationToken table
  db/migrate/20201222123211_remove_unused_sign_in_related_columns.rb
  db/migrate/20201222134529_make_user_id_and_user_type_not_nullable_and_add_index.rb
  db/schema.rb
Labels: Core

#3661 Add traits to ucas_match factory and use them in the tests
  spec/components/support_interface/ucas_match_action_component_spec.rb
  spec/components/support_interface/ucas_match_table_component_spec.rb
  spec/factories.rb
  spec/mailers/candidate_mailer_ucas_match_reminder_email_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/models/ucas_match_spec.rb
  spec/services/ucas_matches/send_resolved_on_apply_emails_spec.rb
  spec/services/ucas_matches/send_resolved_on_ucas_emails_spec.rb
  spec/services/ucas_matches/send_ucas_match_emails_spec.rb
  spec/services/ucas_matches/send_ucas_match_initial_emails_duplicate_applications_spec.rb
  spec/services/ucas_matches/send_ucas_match_initial_emails_multiple_acceptances_spec.rb
  spec/services/ucas_matches/send_ucas_match_reminder_emails_spec.rb
  spec/system/support_interface/ucas_matches_spec.rb
  spec/system/ucas_matching/matching_data_example.csv
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: Core

#3689 Update process matching data from ucas spec
  spec/system/ucas_matching/matching_data_example.csv
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: ProVendor

#3742 Support interface cleanup
  app/frontend/packs/application-support.js
  app/frontend/packs/autocompletes/country-autocomplete.js
  app/views/support_interface/application_forms/address_type/edit.html.erb
  config/locales/en.yml
Labels: Candidate

#3743 Retain the correct input nationalities if validation error occurs
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/controllers/support_interface/application_forms/nationalities_controller.rb
Labels: Bug bash 🐞🔨, Candidate

#3737 Add sorting to validation error summary page
  app/controllers/support_interface/validation_errors_controller.rb
  app/frontend/styles/support/_all.scss
  app/frontend/styles/support/_sort.scss
  app/helpers/select_options_helper.rb
  app/queries/validation_error_summary_query.rb
  app/views/support_interface/validation_errors/summary.html.erb
  spec/queries/validation_error_summary_query_spec.rb
Labels: Support

#3745 Update candidate routes (misc)
  config/routes.rb
  spec/mailers/authentication_mailer_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/system/decline_by_default_spec.rb
Labels: Candidate

#3747 Update routes and paths to align with interface (personal details)
  app/components/candidate_interface/personal_details_review_component.html.erb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/views/candidate_interface/personal_details/base/edit.html.erb
  app/views/candidate_interface/personal_details/base/new.html.erb
  app/views/candidate_interface/personal_details/nationalities/new.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  config/routes.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/requests/candidate_interface/audit_trail_spec.rb
Labels: Candidate

#3746 Make changes to provider-access-controls CSV
  app/services/support_interface/provider_access_controls_export.rb
  app/services/support_interface/provider_access_controls_stats.rb
  spec/services/support_interface/provider_access_controls_export_spec.rb
  spec/services/support_interface/provider_access_controls_stats_spec.rb
Labels: ProVendor

#3749 Update routes and paths to align with interface (contact details)
  app/components/candidate_interface/contact_details_review_component.html.erb
  app/components/candidate_interface/contact_details_review_component.rb
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/candidate_interface/contact_details/address_type_controller.rb
  app/controllers/candidate_interface/contact_details/base_controller.rb
  app/views/candidate_interface/contact_details/address/edit.html.erb
  app/views/candidate_interface/contact_details/address_type/edit.html.erb
  app/views/candidate_interface/contact_details/base/edit.html.erb
  app/views/candidate_interface/contact_details/review/show.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  config/routes.rb
  spec/components/candidate_interface/contact_details_review_component_spec.rb
  spec/requests/candidate_interface/validation_error_tracking_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/entering_details/candidate_entering_contact_details_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_contact_details_without_international_addresses_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
Labels: Candidate

#3752 Update routes to align with interface (training with a disability)
  config/routes.rb
Labels: Candidate
