Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2020-05, with the labels that each got.

#1991 Show recent provider note subjects on applications list
  app/components/provider_interface/application_card_component.html.erb
  app/components/provider_interface/application_card_component.rb
  app/frontend/styles/_notes.scss
  spec/components/provider_interface/application_card_component_spec.rb
Labels: ProVendor

#1987 Candidate can see rejection reasons from Apply1 application
  app/components/candidate_interface/rejection_reasons_component.html.erb
  app/components/candidate_interface/rejection_reasons_component.rb
  app/controllers/candidate_interface/application_form_controller.rb
  app/services/duplicate_application.rb
  app/views/candidate_interface/application_form/show.html.erb
  spec/components/candidate_interface/rejection_reasons_component_spec.rb
  spec/factories.rb
  spec/services/duplicate_application_spec.rb
  spec/system/candidate_interface/candidate_can_see_their_rejection_reasons_on_apply_again_spec.rb
Labels: Candidate

#1998 Apply two thirds width to withdraw offer views
  app/views/provider_interface/decisions/confirm_withdraw_offer.html.erb
  app/views/provider_interface/decisions/new_withdraw_offer.html.erb
Labels: ProVendor

#2003 Add ping test before slot swap
  azure-pipelines-deploy-template.yml
Labels: DevOps

#1931 Providers can assign permissions to their own users
  app/components/provider_interface/provider_permissions_list_component.html.erb
  app/components/provider_interface/provider_permissions_list_component.rb
  app/components/provider_interface/provider_user_details_component.html.erb
  app/components/provider_interface/provider_user_details_component.rb
  app/components/provider_interface/user_list_card_component.html.erb
  app/controllers/provider_interface/provider_users_controller.rb
  app/controllers/support_interface/provider_users_controller.rb
  app/models/provider_interface/provider_user_form.rb
  app/models/provider_permissions_form.rb
  app/models/provider_permissions_options.rb
  app/models/support_interface/provider_user_form.rb
  app/services/save_provider_user.rb
  app/views/provider_interface/provider_users/edit_providers.html.erb
  app/views/provider_interface/provider_users/index.html.erb
  app/views/provider_interface/provider_users/new.html.erb
  app/views/provider_interface/provider_users/show.html.erb
  app/views/support_interface/provider_users/_provider_options.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/provider_interface/provider_permissions_list_component_spec.rb
  spec/models/provider_interface/provider_user_form_spec.rb
  spec/models/provider_permissions_options_spec.rb
  spec/models/support_interface/provider_user_form_spec.rb
  spec/requests/provider_interface/managing_provider_users_spec.rb
  spec/services/save_and_invite_provider_user_spec.rb
  spec/services/save_provider_user_spec.rb
  spec/system/provider_interface/manage_provider_user_permissions_spec.rb
  spec/system/provider_interface/providers_can_view_managed_users_spec.rb
  spec/system/support_interface/managing_provider_users_spec.rb
Labels: ProVendor

#2010 new pipeline to swap app service slots
  README.md
  azure-pipelines-deploy-template.yml
  azure-pipelines-swap-slots.yml
  docs/swap-slot-environments.png
  docs/swap-slots-pipeline.md
  swap-staging-production-template.yml
Labels: DevOps

#1988 Apply again email content
  app/mailers/candidate_mailer.rb
  app/services/decline_offer.rb
  app/services/withdraw_application.rb
  app/views/candidate_mailer/_get_help.erb
  app/views/candidate_mailer/_interested_with_rejections.erb
  app/views/candidate_mailer/_interested_without_rejections.erb
  app/views/candidate_mailer/application_rejected_all_rejected_apply_again.erb
  app/views/candidate_mailer/decline_last_application_choice.text.erb
  app/views/candidate_mailer/declined_by_default_with_rejections.text.erb
  app/views/candidate_mailer/declined_by_default_without_rejections.text.erb
  app/views/candidate_mailer/withdraw_last_application_choice.text.erb
  config/locales/application_states.yml
  config/locales/candidate_mailer.yml
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/system/candidate_interface/candidate_declines_offer_spec.rb
  spec/system/candidate_interface/candidate_withdraws_spec.rb
  spec/system/candidate_interface/decline_by_default_spec.rb
Labels: Candidate

#2024 Fix domain model diagram
  README.md
  Rakefile
  docs/domain-model.png
  lib/tasks/erd.rake
Labels: Core

#2020 Restrict course selection when candidates Apply Again
  app/components/candidate_interface/application_form_apply_again_course_choice_component.html.erb
  app/components/candidate_interface/application_form_apply_again_course_choice_component.rb
  app/components/candidate_interface/application_form_course_choices_component.html.erb
  app/components/candidate_interface/application_form_course_choices_component.rb
  app/controllers/candidate_interface/course_choices_controller.rb
  app/models/application_form.rb
  app/models/candidate_interface/pick_site_form.rb
  app/views/candidate_interface/application_form/show.html.erb
  app/views/candidate_interface/course_choices/_guidance_apply_again.html.erb
  app/views/candidate_interface/course_choices/index.html.erb
  app/views/candidate_interface/course_choices/review.html.erb
  config/locales/en.yml
  spec/components/candidate_interface/application_form_apply_again_course_choice_component_spec.rb
  spec/components/candidate_interface/application_form_course_choices_component_spec.rb
  spec/system/candidate_interface/candidate_with_unsuccessful_application_applies_again_spec.rb
Labels: Candidate

#2036 Fix bug on the support interfaces candidate show page
  app/views/support_interface/candidates/show.html.erb
Labels: Candidate

#2016 Candidate can see previous application when applying again
  app/components/candidate_interface/links_to_previous_applications_component.html.erb
  app/components/candidate_interface/links_to_previous_applications_component.rb
  app/controllers/candidate_interface/application_form_controller.rb
  app/views/candidate_interface/application_form/review_submitted.html.erb
  app/views/candidate_interface/application_form/show.html.erb
  config/routes.rb
  spec/components/candidate_interface/links_to_previous_applications_component_spec.rb
  spec/system/candidate_interface/candidate_with_unsuccessful_application_applies_again_spec.rb
Labels: Candidate

#2043 Remove feature flags (candidate)
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/referees_review_component.html.erb
  app/components/work_history_review_component.rb
  app/controllers/candidate_interface/equality_and_diversity_controller.rb
  app/controllers/candidate_interface/safeguarding_controller.rb
  app/controllers/candidate_interface/work_history/break_controller.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/application_form/review.html.erb
  app/views/candidate_interface/application_form/show.html.erb
  app/views/candidate_interface/work_history/edit/_form.html.erb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
  spec/components/work_history_review_component_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_adding_referees_in_sandbox_spec.rb
  spec/system/candidate_interface/candidate_cancels_a_reference_spec.rb
  spec/system/candidate_interface/candidate_edits_course_choices_spec.rb
  spec/system/candidate_interface/candidate_edits_work_history_after_completing_the_section_spec.rb
  spec/system/candidate_interface/candidate_entering_equality_and_diversity_information_spec.rb
  spec/system/candidate_interface/candidate_entering_suitability_to_work_with_children_spec.rb
  spec/system/candidate_interface/candidate_entering_work_history_breaks_spec.rb
  spec/system/candidate_interface/candidate_entering_work_history_spec.rb
  spec/system/candidate_interface/candidate_reviewing_an_incomplete_application_spec.rb
  spec/system/candidate_interface/course_selection/candidate_submitting_application_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: Candidate

#2033 Make reference guidance dynamic
  app/components/candidate_interface/referee_guidance_component.html.erb
  app/components/candidate_interface/referee_guidance_component.rb
  app/controllers/candidate_interface/application_form_controller.rb
  app/views/candidate_interface/application_form/submit_success.html.erb
  spec/components/candidate_interface/referee_guidance_component_spec.rb
  spec/system/candidate_interface/candidate_replaces_reference_after_applying_again_spec.rb
  spec/system/candidate_interface/candidate_with_unsuccessful_application_applies_again_spec.rb
Labels: Candidate

#2058 Do not show the unhelpful default error when a rejection reason is too long
  app/views/provider_interface/decisions/new_reject.html.erb
  config/locales/en.yml
Labels: Bug bash 🐞🔨

#2059 Hide subnavigation links in print stylesheet
  app/components/sub_navigation_component.html.erb
Labels: Bug bash 🐞🔨

#2056 Correct flash message on successful provider user invitation
  app/controllers/provider_interface/provider_users_controller.rb
  spec/system/provider_interface/provider_invites_user_spec.rb
  spec/system/provider_interface/removing_provider_user_spec.rb
Labels: Bug bash 🐞🔨

#2055 Remove edit application guidance for apply again
  app/components/candidate_interface/application_complete_content_component.html.erb
  app/controllers/candidate_interface/application_form_controller.rb
  app/views/candidate_interface/application_form/submit_success.html.erb
  spec/system/candidate_interface/candidate_with_unsuccessful_application_applies_again_spec.rb
Labels: Candidate

#2063 Add confirm completion checkbox for personal details section
  app/components/candidate_interface/complete_section_component.html.erb
  app/components/candidate_interface/complete_section_component.rb
  app/controllers/candidate_interface/personal_details_controller.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/personal_details/show.html.erb
  config/locales/application_form.yml
  config/routes.rb
  spec/components/candidate_interface/complete_section_component_spec.rb
  spec/factories.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_personal_details_spec.rb
Labels: Candidate

#2074 Support: redirect to application forms from application choice IDs
  app/controllers/support_interface/application_choices_controller.rb
  config/routes.rb
  spec/requests/support_interface/application_choices_spec.rb
Labels: Support

#2086 Add completed checkbox to 5 sections of the application form
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/candidate_interface/contact_details/base_controller.rb
  app/controllers/candidate_interface/contact_details/review_controller.rb
  app/controllers/candidate_interface/gcse/details_controller.rb
  app/controllers/candidate_interface/gcse/grade_controller.rb
  app/controllers/candidate_interface/gcse/review_controller.rb
  app/controllers/candidate_interface/gcse/type_controller.rb
  app/controllers/candidate_interface/gcse/year_controller.rb
  app/controllers/candidate_interface/safeguarding_controller.rb
  app/controllers/candidate_interface/training_with_a_disability_controller.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/contact_details/review/show.html.erb
  app/views/candidate_interface/gcse/review/show.html.erb
  app/views/candidate_interface/safeguarding/show.html.erb
  app/views/candidate_interface/training_with_a_disability/show.html.erb
  config/routes.rb
  spec/factories.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_contact_details_spec.rb
  spec/system/candidate_interface/candidate_entering_disability_info_spec.rb
  spec/system/candidate_interface/candidate_entering_gcse_spec.rb
  spec/system/candidate_interface/candidate_entering_suitability_to_work_with_children_spec.rb
Labels: Candidate

#2087 Add last completed checkboxes for each application form section
  app/components/candidate_interface/complete_section_component.html.erb
  app/components/candidate_interface/complete_section_component.rb
  app/controllers/candidate_interface/personal_statement/becoming_a_teacher_controller.rb
  app/controllers/candidate_interface/personal_statement/interview_preferences_controller.rb
  app/controllers/candidate_interface/personal_statement/subject_knowledge_controller.rb
  app/controllers/candidate_interface/referees_controller.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/contact_details/review/show.html.erb
  app/views/candidate_interface/gcse/review/show.html.erb
  app/views/candidate_interface/personal_details/show.html.erb
  app/views/candidate_interface/personal_statement/becoming_a_teacher/show.html.erb
  app/views/candidate_interface/personal_statement/interview_preferences/show.html.erb
  app/views/candidate_interface/personal_statement/subject_knowledge/show.html.erb
  app/views/candidate_interface/referees/review.html.erb
  app/views/candidate_interface/safeguarding/show.html.erb
  app/views/candidate_interface/training_with_a_disability/show.html.erb
  config/routes.rb
  spec/components/candidate_interface/complete_section_component_spec.rb
  spec/factories.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_adding_referees_spec.rb
  spec/system/candidate_interface/candidate_becoming_a_teacher_spec.rb
  spec/system/candidate_interface/candidate_entering_interview_preferences_spec.rb
  spec/system/candidate_interface/candidate_entering_subject_knowledge_spec.rb
Labels: Candidate

#2104 publish docker image to hub before test runs
  azure-pipelines.yml
  docker-compose.azure.yml
Labels: DevOps

#2110 Bring Provider application page closer to the prototype
  app/components/interview_preferences_component.html.erb
  app/components/interview_preferences_component.rb
  app/components/personal_statement_component.html.erb
  app/components/personal_statement_component.rb
  app/components/provider_interface/reference_with_feedback_component.rb
  app/components/provider_interface/safeguarding_declaration_component.html.erb
  app/components/provider_interface/training_with_disability_component.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/support_interface/application_forms/show.html.erb
  spec/components/provider_interface/reference_with_feedback_component_spec.rb
  spec/components/provider_interface/safeguarding_declaration_component_spec.rb
  spec/components/provider_interface/training_with_disability_component_spec.rb
Labels: Bug bash 🐞🔨

#2118 run deploy QA stage in parallel to test stages
  azure-pipelines-deploy-template.yml
  azure-pipelines.yml
  azure/containers.json
Labels: DevOps

#2116 Display errors in the add note form in order
  app/models/provider_interface/new_note_form.rb
Labels: Bug bash 🐞🔨

#2117 Don’t show "Awaiting decision" if flash is present
  app/views/provider_interface/application_choices/_application_choice_header.html.erb
Labels: Bug bash 🐞🔨

#2099 Move #edit_by to ApplicationForm
  app/lib/test_applications.rb
  app/models/application_dates.rb
  app/services/feature_flag.rb
  app/services/get_application_forms_ready_to_send_to_providers.rb
  app/services/submit_application.rb
  app/services/submit_application_choice.rb
  app/services/submit_reference.rb
  db/migrate/20200521112623_migrate_edit_by_value_to_application_form.rb
  db/schema.rb
  docs/domain-model.png
  spec/models/application_dates_spec.rb
  spec/services/get_application_forms_ready_to_send_to_providers_spec.rb
  spec/services/submit_application_spec.rb
  spec/services/submit_reference_spec.rb
Labels: Candidate

#2125 Completed sections - Fix error links
  app/components/candidate_interface/becoming_a_teacher_review_component.rb
  app/components/candidate_interface/contact_details_review_component.rb
  app/components/candidate_interface/gcse_qualification_review_component.html.erb
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/components/candidate_interface/interview_preferences_review_component.rb
  app/components/candidate_interface/other_information.html.erb
  app/components/candidate_interface/personal_details_review_component.html.erb
  app/components/candidate_interface/personal_details_review_component.rb
  app/components/candidate_interface/referees_review_component.rb
  app/components/candidate_interface/subject_knowledge_review_component.rb
  app/components/candidate_interface/training_with_a_disability_review_component.rb
  app/components/safeguarding_review_component.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/gcse/review/show.html.erb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
Labels: Candidate

#2128 Complete sections - fix checkbox related behaviour
  app/controllers/candidate_interface/gcse/review_controller.rb
  app/lib/test_applications.rb
  app/views/candidate_interface/gcse/review/show.html.erb
  spec/factories.rb
Labels: Candidate

#2132 reapply Gemfile.lock updates with correct rack version
  Gemfile.lock
Labels: dependencies

#2129 Ensure completed section booleans are updated with the flag off
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/candidate_interface/contact_details/base_controller.rb
  app/controllers/candidate_interface/gcse/details_controller.rb
  app/controllers/candidate_interface/gcse/grade_controller.rb
  app/controllers/candidate_interface/gcse/type_controller.rb
  app/controllers/candidate_interface/gcse/year_controller.rb
  app/controllers/candidate_interface/personal_details_controller.rb
  app/controllers/candidate_interface/personal_statement/becoming_a_teacher_controller.rb
  app/controllers/candidate_interface/personal_statement/interview_preferences_controller.rb
  app/controllers/candidate_interface/personal_statement/subject_knowledge_controller.rb
  app/controllers/candidate_interface/referees_controller.rb
  app/controllers/candidate_interface/safeguarding_controller.rb
  app/controllers/candidate_interface/training_with_a_disability_controller.rb
  spec/system/candidate_interface/candidate_completes_application_with_mark_every_section_complete_flag_off_spec.rb
Labels: Candidate

#2091 Migration to backfill completed section booleans
  db/migrate/20200526122730_populate_completed_section_booleans.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#2157 Cancel build if there are new commits to a branch
  azure-pipelines-deploy-template.yml
  azure-pipelines-release.yml
  azure-pipelines-swap-slots.yml
  azure-pipelines.yml
  cancel-build-if-not-latest-template.yml
  swap-staging-production-template.yml
Labels: DevOps

#2177 Adding PR trigger to build
  azure-pipelines.yml
Labels: DevOps
