Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2021-06, with the labels that each got.

#4860 Remove Azure DevOps templates and update environment variables documentation
  .github/PULL_REQUEST_TEMPLATE.md
  azure/containers.json
  azure/pipelines/build-gems-node-modules.yml
  azure/pipelines/build.yml
  azure/pipelines/release.yml
  azure/pipelines/swap-slots.yml
  azure/pipelines/templates/cancel-build-if-not-latest.yml
  azure/pipelines/templates/deploy.yml
  azure/pipelines/templates/health-check.yml
  azure/pipelines/templates/metrics-check.yml
  azure/pipelines/templates/rspec-job.yml
  azure/pipelines/templates/run-rspec-test.yml
  azure/pipelines/templates/swap-staging-production-slots.yml
  azure/template.json
  docker-compose.azure.yml
  docs/environment-variables.md
  spec/azure/configuration_spec.rb
Labels: DevOps

#4847 Use explicit backlinks in the degree section
  app/controllers/candidate_interface/degrees/base_controller.rb
  app/controllers/candidate_interface/degrees/completion_status_controller.rb
  app/controllers/candidate_interface/degrees/enic_controller.rb
  app/controllers/candidate_interface/degrees/grade_controller.rb
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/controllers/candidate_interface/degrees/subject_controller.rb
  app/controllers/candidate_interface/degrees/type_controller.rb
  app/controllers/candidate_interface/degrees/year_controller.rb
  app/forms/candidate_interface/degree_enic_form.rb
  app/views/candidate_interface/degrees/base/_base_form.html.erb
  app/views/candidate_interface/degrees/base/edit.html.erb
  app/views/candidate_interface/degrees/base/new_another.html.erb
  app/views/candidate_interface/degrees/base/new_undergraduate.html.erb
  app/views/candidate_interface/degrees/completion_status/edit.html.erb
  app/views/candidate_interface/degrees/completion_status/new.html.erb
  app/views/candidate_interface/degrees/enic/edit.html.erb
  app/views/candidate_interface/degrees/enic/new.html.erb
  app/views/candidate_interface/degrees/grade/edit.html.erb
  app/views/candidate_interface/degrees/grade/new.html.erb
  app/views/candidate_interface/degrees/institution/edit.html.erb
  app/views/candidate_interface/degrees/institution/new.html.erb
  app/views/candidate_interface/degrees/subject/edit.html.erb
  app/views/candidate_interface/degrees/subject/new.html.erb
  app/views/candidate_interface/degrees/type/add_another.html.erb
  app/views/candidate_interface/degrees/type/edit.html.erb
  app/views/candidate_interface/degrees/type/new.html.erb
  app/views/candidate_interface/degrees/year/new.html.erb
  app/views/candidate_interface/gcse/grade/edit.html.erb
  config/routes.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_international_degrees_spec.rb
Labels: Candidate

#4824 Update the select references UI
  app/components/task_list_item_references_component.html.erb
  app/components/task_list_item_references_component.rb
  app/controllers/candidate_interface/references/review_controller.rb
  app/controllers/candidate_interface/references/selection_controller.rb
  app/models/application_reference.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/references/selection/new.html.erb
  app/views/candidate_interface/references/selection/review.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/candidate_interface/references/reference_selection/candidate_selects_two_references_spec.rb
Labels: Candidate

#4828 Add new flow for creating or updating a single provider user
  app/components/support_interface/provider_users_table_component.html.erb
  app/controllers/support_interface/providers_controller.rb
  app/controllers/support_interface/single_provider_users_controller.rb
  app/forms/support_interface/create_single_provider_user_form.rb
  app/forms/support_interface/edit_single_provider_user_form.rb
  app/services/feature_flag.rb
  app/views/support_interface/providers/users.html.erb
  app/views/support_interface/single_provider_users/_edit_provider_permissions.html.erb
  app/views/support_interface/single_provider_users/_provider_permissions.html.erb
  app/views/support_interface/single_provider_users/edit.html.erb
  app/views/support_interface/single_provider_users/new.html.erb
  config/locales/support_interface/support_interface.yml
  config/routes.rb
  spec/forms/support_interface/create_single_provider_user_form_spec.rb
  spec/forms/support_interface/edit_single_provider_user_form_spec.rb
  spec/system/support_interface/managing_users_v2/adding_a_new_provider_user_spec.rb
  spec/system/support_interface/managing_users_v2/adding_provider_to_existing_provider_user_spec.rb
  spec/system/support_interface/managing_users_v2/editing_permissions_for_a_provider_user_spec.rb
Labels: Support

#4868 Ensure the SignInCandidate only adds courses from the current cycle
  app/services/candidate_interface/sign_in_candidate.rb
  spec/services/candidate_interface/sign_in_candidate_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#4852 Handle state changes when a selected reference is deleted
  app/controllers/candidate_interface/references/review_controller.rb
  app/services/delete_reference.rb
  app/views/candidate_interface/references/review/confirm_destroy_reference.html.erb
  config/locales/en.yml
  spec/services/delete_reference_spec.rb
  spec/system/candidate_interface/references/reference_selection/candidate_deletes_a_selected_reference_spec.rb
Labels: Candidate

#4882 Add yabeda config for Rails metrics graphing in Grafana
  Gemfile
  Gemfile.lock
  config/initializers/sidekiq.rb
  config/puma.rb
  config/routes.rb
Labels: Core

#4877 Remove old implementation of notifications
  app/components/support_interface/provider_user_summary_component.rb
  app/controllers/provider_interface/notifications_controller.rb
  app/controllers/support_interface/provider_user_notification_preferences_controller.rb
  app/exports/notifications_export.yml
  app/models/data_export.rb
  app/services/feature_flag.rb
  app/services/notifications_list.rb
  app/services/support_interface/notifications_export.rb
  app/views/provider_interface/notifications/show.html.erb
  app/views/support_interface/provider_users/edit.html.erb
  config/clock.rb
  spec/components/support_interface/provider_user_summary_component_spec.rb
  spec/services/accept_offer_spec.rb
  spec/services/decline_offer_by_default_spec.rb
  spec/services/decline_offer_spec.rb
  spec/services/notifications_list_spec.rb
  spec/services/send_new_application_email_to_provider_spec.rb
  spec/services/send_reject_by_default_email_to_provider_spec.rb
  spec/services/support_interface/notifications_export_spec.rb
  spec/services/withdraw_application_spec.rb
  spec/system/provider_interface/manage_provider_user_global_notifications_spec.rb
  spec/system/provider_interface/manage_provider_user_notifications_spec.rb
  spec/system/support_interface/managing_provider_user_notification_preferences_spec.rb
Labels: ProVendor

#4871 Expose free text equality and diversity data in Vendor API
  app/forms/candidate_interface/equality_and_diversity/disabilities_form.rb
  app/forms/candidate_interface/equality_and_diversity/ethnic_background_form.rb
  app/helpers/checkbox_options_helper.rb
  app/helpers/disability_helper.rb
  app/helpers/ethnic_background_helper.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/views/api_docs/vendor_api_docs/pages/release_notes.md
  config/initializers/ethnicities.rb
  config/vendor-api-v1.yml
  spec/factories/application_form.rb
  spec/helpers/checkbox_options_helper_spec.rb
  spec/helpers/ethnic_background_helper_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
Labels: API, ProVendor

#4838 Make app submission work with selected references
  app/components/selected_references_component.html.erb
  app/components/selected_references_component.rb
  app/controllers/candidate_interface/references/selection_controller.rb
  app/models/application_form.rb
  app/models/application_reference.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/services/submit_application.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/references/selection/review.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  config/locales/candidate_interface/references.yml
  config/locales/candidate_interface/review_application.yml
  spec/components/selected_references_component_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/services/submit_application_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/references/candidate_has_too_many_references_spec.rb
  spec/system/candidate_interface/references/reference_selection/candidate_has_too_many_selected_references_spec.rb
  spec/system/candidate_interface/references/reference_selection/candidate_submits_an_application_spec.rb
Labels: Candidate

#4895 Add logging to TTAPI provider/course sync
  app/services/teacher_training_public_api/sync_all_providers_and_courses.rb
  app/services/teacher_training_public_api/sync_courses.rb
  app/services/teacher_training_public_api/sync_provider.rb
Labels: Core

#4863 Throw an exception when trying to mark a stale application changed
  app/lib/test_applications.rb
  app/models/application_form.rb
  app/models/concerns/published_in_api.rb
  spec/models/application_form_spec.rb
  spec/system/support_interface/feature_metrics_dashboard_spec.rb
Labels: Core

#4873 Add Restructured Work History to Support UI
  app/components/candidate_interface/restructured_work_history/gap_component.rb
  app/components/candidate_interface/restructured_work_history/job_component.rb
  app/components/candidate_interface/restructured_work_history/review_component.rb
  app/components/candidate_interface/restructured_work_history/work_break_component.rb
  app/components/restructured_work_history/gap_component.html.erb
  app/components/restructured_work_history/gap_component.rb
  app/components/restructured_work_history/job_component.html.erb
  app/components/restructured_work_history/job_component.rb
  app/components/restructured_work_history/review_component.html.erb
  app/components/restructured_work_history/review_component.rb
  app/components/restructured_work_history/work_break_component.html.erb
  app/components/restructured_work_history/work_break_component.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/restructured_work_history/review/show.html.erb
  app/views/support_interface/application_forms/show.html.erb
  spec/components/restructured_work_history/gap_component_spec.rb
  spec/components/restructured_work_history/job_component_spec.rb
  spec/components/restructured_work_history/review_component_spec.rb
  spec/components/restructured_work_history/work_break_component_spec.rb
Labels: Support

#4881 Add cannot sponsor visa to structured rejections
  app/components/reasons_for_rejection_component.html.erb
  app/components/support_interface/reasons_for_rejection_dashboard_component.html.erb
  app/controllers/provider_interface/reasons_for_rejection_controller.rb
  app/exports/structured_reasons_for_rejection_export.yml
  app/forms/provider_interface/reasons_for_rejection_wizard.rb
  app/models/reasons_for_rejection.rb
  app/presenters/rejected_application_choice_presenter.rb
  app/presenters/support_interface/flat_reasons_for_rejection_presenter.rb
  app/views/provider_interface/reasons_for_rejection/edit_initial_questions.html.erb
  config/locales/provider_interface/reasons_for_rejection.yml
  spec/components/provider_interface/reasons_for_rejection_component_spec.rb
  spec/components/reasons_for_rejection_component_spec.rb
  spec/factories/application_choice.rb
  spec/forms/provider_interface/reasons_for_rejection_wizard_spec.rb
  spec/presenters/rejected_application_choice_presenter_spec.rb
  spec/presenters/support_interface/flat_reasons_for_rejection_presenter_spec.rb
  spec/services/support_interface/structured_reasons_for_rejection_export_spec.rb
  spec/system/provider_interface/provider_gives_feedback_for_rejected_by_default_spec.rb
  spec/system/provider_interface/reject_an_application_spec.rb
  spec/system/support_interface/reasons_for_rejection_dashboard_spec.rb
Labels: ProVendor

#4883 Show course choices on previous applications
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/system/candidate_interface/apply_again/carry_over_unsuccessful_application_spec.rb
Labels: Candidate

#4903 Paas internal routes
  terraform/modules/paas/data.tf
  terraform/modules/paas/main.tf
  terraform/modules/paas/network-policies.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/sandbox.tfvars
Labels: DevOps

#4915 Deploy to Research environment
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Makefile
  terraform/modules/paas/variables.tf
  terraform/workspace_variables/research.tfvars
  terraform/workspace_variables/research_backend.tfvars
Labels: DevOps

#4890 Fix test suite for reference_selection feature
  app/lib/test_applications.rb
  app/models/reference_feature_metrics.rb
  app/services/submit_reference.rb
  spec/components/candidate_interface/add_reference_component_spec.rb
  spec/components/candidate_interface/references_review_component_spec.rb
  spec/models/application_form_spec.rb
  spec/services/reference_actions_policy_spec.rb
  spec/services/submit_reference_spec.rb
  spec/spec_helper.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/apply_again/candidate_carries_over_unsubmitted_application_between_cycles_spec.rb
  spec/system/candidate_interface/apply_again/candidate_carries_over_unsubmitted_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/apply_again/candidate_carries_over_unsubmitted_application_without_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/apply_again/candidate_reviews_rejection_reasons_from_previous_applications_spec.rb
  spec/system/candidate_interface/feedback/candidate_provides_feedback_while_completing_their_application_spec.rb
  spec/system/candidate_interface/references/backlinks_spec.rb
  spec/system/candidate_interface/references/candidate_adds_a_new_reference_spec.rb
  spec/system/candidate_interface/references/candidate_has_too_many_references_spec.rb
  spec/system/candidate_interface/references/candidate_receives_feedback_from_their_reference_requests_spec.rb
  spec/system/candidate_interface/references/review_references_spec.rb
  spec/system/candidate_interface/references/submitting_an_application_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviewing_an_incomplete_application_spec.rb
  spec/system/candidate_interface/submitting/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
  spec/system/referee_interface/referee_cannot_provide_reference_if_two_already_received_spec.rb
Labels: Candidate, Referee

#4908 Only incrementally sync Providers that have been updated since last sync
  app/services/teacher_training_public_api/sync_all_providers_and_courses.rb
  app/services/teacher_training_public_api/sync_courses.rb
  app/services/teacher_training_public_api/sync_provider.rb
  app/workers/teacher_training_public_api/sync_provider_worker.rb
  lib/tasks/local_dev.rake
  spec/services/teacher_training_public_api/sync_all_providers_and_courses_spec.rb
  spec/services/teacher_training_public_api/sync_courses_spec.rb
  spec/services/teacher_training_public_api/sync_provider_spec.rb
  spec/support/test_helpers/teacher_training_public_api_helper.rb
  spec/system/find_sync/syncing_providers_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
  spec/system/teacher_training_public_api/study_mode_changes_spec.rb
  spec/system/teacher_training_public_api/sync_course_spec.rb
  spec/system/teacher_training_public_api/sync_site_spec.rb
Labels: Core

#4841 Start reading from new offer and conditions tables
  app/components/candidate_interface/application_dashboard_course_choices_component.rb
  app/components/candidate_interface/offer_review_component.rb
  app/components/provider_interface/conditions_component.html.erb
  app/components/provider_interface/conditions_component.rb
  app/components/provider_interface/offer_summary_component.html.erb
  app/components/provider_interface/offer_summary_component.rb
  app/components/support_interface/application_choice_component.rb
  app/components/support_interface/conditions_component.html.erb
  app/controllers/vendor_api/decisions_controller.rb
  app/forms/provider_interface/offer_wizard.rb
  app/forms/provider_interface/reconfirm_deferred_offer_wizard.rb
  app/forms/support_interface/conditions_form.rb
  app/mailers/candidate_mailer.rb
  app/models/application_choice.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/accept_offer.rb
  app/services/change_offer.rb
  app/services/make_offer.rb
  app/services/offer_validations.rb
  app/services/support_interface/offer_conditions_export.rb
  app/services/update_accepted_offer_conditions.rb
  app/services/update_offer_conditions.rb
  app/views/candidate_interface/decisions/offer.html.erb
  app/views/provider_interface/offer/checks/edit.html.erb
  app/views/provider_interface/offer/checks/new.html.erb
  app/views/provider_interface/offers/show.html.erb
  app/views/provider_interface/reconfirm_deferred_offers/conditions.html.erb
  spec/components/candidate_interface/application_dashboard_course_choices_component_spec.rb
  spec/components/candidate_interface/offer_review_component_spec.rb
  spec/components/provider_interface/completed_offer_summary_component_spec.rb
  spec/components/provider_interface/conditions_component_spec.rb
  spec/components/provider_interface/offer_summary_component_spec.rb
  spec/components/provider_interface/read_only_completed_offer_summary_component_spec.rb
  spec/components/support_interface/application_choice_component_spec.rb
  spec/factories/application_choice.rb
  spec/factories/offer.rb
  spec/factories/offer_condition.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
  spec/forms/provider_interface/reconfirm_deferred_offer_wizard_spec.rb
  spec/forms/support_interface/conditions_form_spec.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/models/application_choice_spec.rb
  spec/requests/vendor_api/post_conditions_met_spec.rb
  spec/requests/vendor_api/post_conditions_not_met_spec.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
  spec/services/accept_offer_spec.rb
  spec/services/change_offer_spec.rb
  spec/services/conditions_not_met_spec.rb
  spec/services/confirm_offer_conditions_spec.rb
  spec/services/make_offer_spec.rb
  spec/services/offer_validations_spec.rb
  spec/services/reinstate_conditions_met_spec.rb
  spec/services/reinstate_pending_conditions_spec.rb
  spec/services/support_interface/offer_conditions_export_spec.rb
  spec/services/update_offer_conditions_spec.rb
  spec/system/provider_interface/change_existing_offer_spec.rb
  spec/system/support_interface/change_offer_conditions_spec.rb
Labels: ProVendor

#4922 Introduce feature flag for individual conditions
  app/services/feature_flag.rb
Labels: ProVendor

#4918 Add custom tags to filter queries in Grafana dashboard
  config/initializers/yabeda.rb
Labels: DevOps

#4909 Add new data migration service for removing all application choices in the incorrect cycle
  app/models/application_choice.rb
  app/services/data_migrations/remove_application_choices_in_the_incorrect_cycle.rb
  lib/tasks/data.rake
  spec/services/data_migrations/remove_application_choices_in_the_incorrect_cycle_spec.rb
Labels: Core

#4891 Handle state changes when a new reference is received
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/reference_received.text.erb
  spec/mailers/candidate_mailer_referee_mails_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
Labels: Candidate, Referee

#4912 Create OpenAPI spec for Candidate API
  config/candidates-api.yml
Labels: API, Candidate

#4879 Mark send_notifications as an ignored column
  app/controllers/provider_interface/notifications_controller.rb
  app/controllers/support_interface/provider_user_notification_preferences_controller.rb
  app/models/provider_user.rb
  app/services/provider_interface/save_provider_user_service.rb
  app/services/save_provider_user.rb
  app/services/save_provider_user_notification_preferences.rb
  config/routes.rb
  spec/components/provider_user_notification_preferences_component_spec.rb
  spec/components/support_interface/provider_user_summary_component_spec.rb
  spec/factories/provider_user.rb
  spec/services/accept_offer_spec.rb
  spec/services/accept_unconditional_offer_spec.rb
  spec/services/decline_offer_by_default_spec.rb
  spec/services/decline_offer_spec.rb
  spec/services/notifications_list_spec.rb
  spec/services/save_provider_user_notification_preferences_spec.rb
  spec/services/save_provider_user_spec.rb
  spec/services/send_application_to_provider_spec.rb
  spec/services/send_new_application_email_to_provider_spec.rb
  spec/services/send_reject_by_default_email_to_provider_spec.rb
  spec/services/withdraw_application_spec.rb
  spec/support/test_helpers/dfe_sign_in_helpers.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_declines_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_withdraws_spec.rb
  spec/system/decline_by_default_spec.rb
  spec/system/reject_by_default_spec.rb
  spec/system/support_interface/managing_provider_user_notification_preferences_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
  spec/system/vendor_api/vendor_makes_unconditional_offer_spec.rb
Labels: ProVendor

#4928 Substitute calls to `UpdateOfferConditions` service with bulk updates…
  app/services/conditions_not_met.rb
  app/services/confirm_offer_conditions.rb
Labels: ProVendor

#4894 New reference design – content refinement
  app/components/candidate_interface/add_reference_component.html.erb
  app/components/referee_interface/reference_review_component.rb
  app/components/selected_references_component.rb
  app/components/task_list_item_references_component.html.erb
  app/controllers/candidate_interface/references/selection_controller.rb
  app/models/application_form.rb
  app/models/reference_history.rb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/references/review/show_for_reference_selection.html.erb
  app/views/candidate_interface/references/selection/new.html.erb
  app/views/candidate_interface/references/start/show.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  app/views/candidate_mailer/reference_received.text.erb
  config/locales/candidate_interface/candidate_reference_status.yml
  config/locales/candidate_interface/references.yml
  config/locales/en.yml
  config/locales/support_interface/reference_status.yml
  config/locales/support_interface/support_interface.yml
  spec/components/candidate_interface/add_reference_component_spec.rb
  spec/components/candidate_interface/reference_history_component_spec.rb
  spec/components/referee_interface/reference_review_component_spec.rb
  spec/components/task_list_item_references_component_spec.rb
  spec/mailers/candidate_mailer_referee_mails_spec.rb
  spec/models/reference_history_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/apply_again/candidate_reviews_rejection_reasons_from_previous_applications_spec.rb
  spec/system/candidate_interface/feedback/candidate_provides_feedback_while_completing_their_application_spec.rb
  spec/system/candidate_interface/references/backlinks_spec.rb
  spec/system/candidate_interface/references/candidate_adding_referees_in_sandbox_spec.rb
  spec/system/candidate_interface/references/candidate_adds_a_new_reference_spec.rb
  spec/system/candidate_interface/references/candidate_receives_feedback_from_their_reference_requests_spec.rb
  spec/system/candidate_interface/references/reference_selection/candidate_deletes_a_selected_reference_spec.rb
  spec/system/candidate_interface/references/reference_selection/candidate_selects_two_references_spec.rb
  spec/system/candidate_interface/references/reference_selection/candidate_submits_an_application_spec.rb
  spec/system/candidate_interface/references/submitting_an_application_spec.rb
Labels: Candidate, Referee

#4932 Reference section update – small copy tweak to referee facing content
  app/components/referee_interface/reference_review_component.rb
  spec/components/referee_interface/reference_review_component_spec.rb
Labels: Candidate, Referee

#4880 [Do not merge] Remove provider_users.send_notifications from database
  db/migrate/20210603152817_drop_send_notifications_from_provider_users.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#4929 remove dependency on updateofferservice from reinstate services
  app/services/reinstate_conditions_met.rb
  app/services/reinstate_pending_conditions.rb
Labels: ProVendor

#4931 Add reference auto-response to all test environments
  app/lib/hosting_environment.rb
  app/services/request_reference.rb
  app/views/candidate_interface/references/email_address/_shared_form.html.erb
Labels: Candidate

#4933 Add support for multiple refbot email addresses
  app/services/request_reference.rb
  spec/system/candidate_interface/references/candidate_adding_referees_in_sandbox_spec.rb
Labels: Candidate

#4935 Reload application offer before rendering in the API response
  app/controllers/vendor_api/decisions_controller.rb
  app/presenters/vendor_api/single_application_presenter.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
Labels: Bug bash 🐞🔨, Offers, ProVendor

#4897 Backfill providerrelationshippermissions on test environments
  app/services/data_migrations/set_missing_provider_relationship_permissions.rb
  lib/tasks/data.rake
  spec/factories/course.rb
  spec/services/data_migrations/set_missing_provider_relationship_permissions_spec.rb
Labels: ProVendor, Sandbox

#4851 🏈 refactor move offer related concerns from application choice to the offer class
  app/components/candidate_interface/application_dashboard_course_choices_component.rb
  app/components/candidate_interface/offer_review_component.rb
  app/components/support_interface/application_choice_component.html.erb
  app/controllers/support_interface/application_forms/application_choices/change_offered_course_controller.rb
  app/forms/provider_interface/offer_wizard.rb
  app/forms/support_interface/conditions_form.rb
  app/mailers/candidate_mailer.rb
  app/models/application_choice.rb
  app/models/course_option.rb
  app/models/offer.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/accept_offer.rb
  app/services/offer_validations.rb
  app/services/support_interface/offer_conditions_export.rb
  app/views/candidate_interface/decisions/offer.html.erb
  spec/factories/application_choice.rb
  spec/factories/offer_condition.rb
  spec/forms/support_interface/conditions_form_spec.rb
  spec/models/application_choice_spec.rb
  spec/models/offer_condition_spec.rb
  spec/models/offer_spec.rb
  spec/services/offer_validations_spec.rb
Labels: ProVendor

#4934 Replace rubocop-govuk with rubocop
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/services/provider_authorisation.rb
  config/rubocop/config/layout.yml
  config/rubocop/config/lint.yml
  config/rubocop/config/metrics.yml
  config/rubocop/config/rails.yml
  config/rubocop/config/rake.yml
  config/rubocop/config/rspec.yml
  config/rubocop/config/style.yml
Labels: Core

#4937 Add support playbook to docs folder
  docs/support_playbook.md
Labels: Support

#4939 Enable non controversial new cops and resolve errors
  app/controllers/candidate_interface/course_choices/ucas_controller.rb
  app/forms/candidate_interface/english_gcse_grade_form.rb
  app/services/support_interface/structured_reasons_for_rejection_export.rb
  app/views/support_interface/validation_errors/user/index.html.erb
  config/rubocop/config/layout.yml
  config/rubocop/config/rails.yml
  config/rubocop/config/style.yml
  spec/forms/candidate_interface/english_foreign_language/ielts_form_spec.rb
  spec/forms/candidate_interface/english_foreign_language/other_efl_qualification_form_spec.rb
  spec/forms/candidate_interface/english_foreign_language/toefl_form_spec.rb
  spec/models/apply_again_feature_metrics_spec.rb
  spec/models/carry_over_feature_metrics_spec.rb
Labels: Core

#4917 Generate documentation for GIT API
  app/controllers/api_docs/candidate_api_docs/open_api_controller.rb
  app/controllers/api_docs/candidate_api_docs/reference_controller.rb
  app/helpers/application_helper.rb
  app/lib/candidate_api_specification.rb
  app/views/api_docs/candidate_api_docs/reference/reference.html.erb
  config/candidate-api.yml
  config/locales/en.yml
  config/routes.rb
  spec/system/candidate_api/candidate_api_docs_spec.rb
Labels: API, API docs, Candidate

#4921 Ensure we set '00' hesa_disabilities code
  app/forms/candidate_interface/equality_and_diversity/disability_status_form.rb
  spec/forms/candidate_interface/equality_and_diversity/disability_status_form_spec.rb
Labels: API

#4943 Update HostingEnvironment to support Research
  app/components/phase_banner_component.rb
  app/frontend/styles/_header.scss
  app/lib/hosting_environment.rb
  config/application.rb
  lib/tasks/generate_test_data.rake
  lib/tasks/reset_qa.rake
Labels: Core

#4920 Lint SCSS files according to the GDS style guide
  Dockerfile
  app/frontend/styles/_add_another.scss
  app/frontend/styles/_application-card.scss
  app/frontend/styles/_banner.scss
  app/frontend/styles/_card.scss
  app/frontend/styles/_grid.scss
  app/frontend/styles/_syntax-highlighting.scss
  app/frontend/styles/_tab-navigation.scss
  app/frontend/styles/api_docs/_all.scss
  app/frontend/styles/application-support.scss
  app/frontend/styles/application.scss
  app/frontend/styles/candidate/_all.scss
  app/frontend/styles/candidate/_task-list.scss
  app/frontend/styles/components/_checkbox_search_filter.scss
  app/frontend/styles/components/_paginated_filter.scss
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_count.scss
  app/frontend/styles/provider/_interview_card.scss
  app/frontend/styles/provider/_masthead.scss
  app/frontend/styles/provider/_notes.scss
  app/frontend/styles/provider/_offer.scss
  app/frontend/styles/provider/_timeline.scss
  app/frontend/styles/support/_all.scss
  app/frontend/styles/support/_sort.scss
  lib/tasks/testing.rake
  package.json
  yarn.lock
Labels: CSS

#4945 Raise exception when attempting to check authorisation with no permissions
  app/services/provider_authorisation.rb
  spec/components/provider_interface/diversity_information_component_spec.rb
  spec/services/provider_authorisation_spec.rb
  spec/support/test_helpers/course_option_helpers.rb
Labels: ProVendor

#4936 Link conditions to DB entries in the frontend to enable better auditing
  app/controllers/provider_interface/offer/conditions_controller.rb
  app/controllers/provider_interface/offers_controller.rb
  app/forms/provider_interface/offer_condition_field.rb
  app/forms/provider_interface/offer_wizard.rb
  app/frontend/packs/further_conditions/assignIndexBasedValues.js
  app/frontend/packs/further_conditions/index.spec.js
  app/services/save_offer_conditions_from_params.rb
  app/views/provider_interface/offer/conditions/_form.html.erb
  app/views/provider_interface/offer/conditions/_further_condition.html.erb
  spec/components/provider_interface/conditions_form_component_spec.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
  spec/requests/provider_interface/offers_controller_spec.rb
  spec/services/save_offer_conditions_from_params_spec.rb
Labels: ProVendor, Provider UI

#4953 Rubocop Cop configuration - part 1
  app/forms/candidate_interface/english_gcse_grade_form.rb
  app/forms/referee_interface/questionnaire_form.rb
  app/lib/test_applications.rb
  config/rubocop/config/layout.yml
  config/rubocop/config/lint.yml
  config/rubocop/config/style.yml
  spec/components/provider_interface/status_box_components/recruited_component_spec.rb
  spec/forms/support_interface/application_forms/reinstate_declined_offer_form_spec.rb
  spec/system/candidate_interface/entering_details/international_candidate_enters_their_personal_details_spec.rb
Labels: Core

#4958 change permissions prompt to scope on open courses
  app/services/provider_setup.rb
  spec/requests/provider_interface/provider_relationship_permissions_request_spec.rb
  spec/services/provider_setup_spec.rb
  spec/system/provider_interface/provider_accepts_data_sharing_agreement_spec.rb
  spec/system/provider_interface/setup_provider_relationship_permissions_spec.rb
Labels: ProVendor

#4938 Support interface conditions form passes condition ids in params
  app/forms/support_interface/conditions_form.rb
  app/services/update_accepted_offer_conditions.rb
  app/views/support_interface/application_choice_conditions/edit.html.erb
  config/locales/support_interface/support_interface.yml
  spec/forms/support_interface/conditions_form_spec.rb
  spec/system/support_interface/change_offer_conditions_spec.rb
Labels: ProVendor, Support

#4957 Switch on offercondition auditing
  app/controllers/vendor_api/decisions_controller.rb
  app/lib/test_applications.rb
  app/models/offer_condition.rb
  app/services/save_offer_conditions_from_params.rb
  app/services/save_offer_conditions_from_text.rb
  app/services/update_offer_conditions.rb
  spec/forms/support_interface/conditions_form_spec.rb
  spec/services/change_offer_spec.rb
  spec/services/make_offer_spec.rb
  spec/services/save_offer_conditions_from_text_spec.rb
  spec/services/update_offer_conditions_spec.rb
  spec/system/support_interface/audit_trail_spec.rb
Labels: ProVendor

#4970 Separate domain to service static assets
  config/environments/production.rb
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
Labels: DevOps

#4977 Hide organisational permissions if they have not been set up
  app/controllers/provider_interface/organisations_controller.rb
  app/services/provider_authorisation.rb
  app/views/provider_interface/account/show.html.erb
  spec/services/provider_authorisation_spec.rb
  spec/system/provider_interface/viewing_organisational_permissions_spec.rb
Labels: ProVendor

#4982 Update guidance on reverting a rejected application choice
  docs/support_playbook.md
Labels: Documentation, Support

#4972 Refactor confirm conditions views to make way for individual conditions
  app/components/provider_interface/condition_status_bulk_edit_form_component.html.erb
  app/components/provider_interface/condition_status_bulk_edit_form_component.rb
  app/components/provider_interface/condition_status_bulk_review_page_component.html.erb
  app/components/provider_interface/condition_status_bulk_review_page_component.rb
  app/components/provider_interface/condition_status_tag_component.html.erb
  app/components/provider_interface/condition_status_tag_component.rb
  app/components/provider_interface/conditions_component.html.erb
  app/components/provider_interface/offer_summary_component.html.erb
  app/controllers/provider_interface/conditions_controller.rb
  app/views/provider_interface/conditions/confirm_update.html.erb
  app/views/provider_interface/conditions/edit.html.erb
  spec/components/provider_interface/condition_status_tag_component_spec.rb
Labels: ProVendor

#4987 Remove Provider relationship permission backfill data migration
  app/services/data_migrations/set_missing_provider_relationship_permissions.rb
  lib/tasks/data.rake
  spec/services/data_migrations/set_missing_provider_relationship_permissions_spec.rb
Labels: ProVendor

#4983 Stop writing to application_choice offer column
  app/services/change_offer.rb
  app/services/make_offer.rb
  app/services/update_accepted_offer_conditions.rb
Labels: ProVendor

#4944 OfferCondition model improvements
  app/forms/provider_interface/offer_wizard.rb
  app/forms/support_interface/conditions_form.rb
  app/helpers/checkbox_options_helper.rb
  app/models/offer_condition.rb
  app/services/make_offer.rb
  app/services/save_offer_conditions_from_params.rb
  spec/components/previews/provider_interface/offer_summary_component_preview.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
  spec/forms/support_interface/conditions_form_spec.rb
  spec/helpers/checkbox_options_helper_spec.rb
  spec/models/offer_condition_spec.rb
  spec/services/save_offer_conditions_from_params_spec.rb
Labels: ProVendor

#4896 Create a new flow for bulk creation of provider users
  app/components/support_interface/permissions_list_review_component.html.erb
  app/components/support_interface/permissions_list_review_component.rb
  app/controllers/support_interface/bulk_upload/checks_controller.rb
  app/controllers/support_interface/bulk_upload/permissions_controller.rb
  app/controllers/support_interface/bulk_upload/provider_users_controller.rb
  app/controllers/support_interface/bulk_upload/provider_users_details_controller.rb
  app/forms/support_interface/create_single_provider_user_form.rb
  app/forms/support_interface/multiple_provider_users_wizard.rb
  app/views/support_interface/bulk_upload/checks/show.html.erb
  app/views/support_interface/bulk_upload/permissions/_provider_permissions.html.erb
  app/views/support_interface/bulk_upload/permissions/edit.html.erb
  app/views/support_interface/bulk_upload/provider_users_details/new.html.erb
  app/views/support_interface/providers/users.html.erb
  config/locales/support_interface/support_interface.yml
  config/routes.rb
  spec/components/support_interface/permissions_list_review_component_spec.rb
  spec/forms/support_interface/multiple_provider_users_wizard_spec.rb
  spec/system/support_interface/managing_users_v2/bulk_upload_a_single_provider_user_spec.rb
  spec/system/support_interface/managing_users_v2/bulk_upload_multiple_provider_users_spec.rb
Labels: Support

#4942 Add redirect to GCSE controller if GCSE is missing
  app/controllers/candidate_interface/gcse/type_controller.rb
  spec/requests/candidate_interface/gcse/type_controller_spec.rb
Labels: Candidate

#4984 Add offer association to applicationchoice model
  app/components/candidate_interface/application_dashboard_course_choices_component.rb
  app/controllers/vendor_api/applications_controller.rb
  app/models/application_choice.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/save_offer_conditions_from_text.rb
  spec/factories/application_choice.rb
  spec/factories/ucas_match.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
  spec/services/provider_interface/sort_application_choices_spec.rb
  spec/services/reinstate_pending_conditions_spec.rb
Labels: ProVendor

#4919 Refactor offer and condition styles
  app/components/provider_interface/conditions_component.html.erb
  app/components/provider_interface/offer_summary_component.html.erb
  app/components/provider_interface/offer_summary_component.rb
  app/frontend/styles/_status-box.scss
  app/frontend/styles/_table.scss
  app/frontend/styles/application.scss
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_offer-panel.scss
  app/frontend/styles/provider/_offer.scss
  app/views/provider_interface/reconfirm_deferred_offers/check.html.erb
  app/views/provider_interface/reconfirm_deferred_offers/conditions.html.erb
  spec/components/provider_interface/completed_offer_summary_component_spec.rb
  spec/components/provider_interface/offer_summary_component_spec.rb
  spec/system/provider_interface/set_offer_conditions_js_spec.rb
Labels: CSS, Provider UI

#5004 Update provider user details page
  app/components/support_interface/application_choice_component.html.erb
  app/components/support_interface/notification_preferences_component.html.erb
  app/components/support_interface/notification_preferences_component.rb
  app/components/support_interface/permissions_list_component.html.erb
  app/components/support_interface/permissions_list_component.rb
  app/components/support_interface/provider_user_permissions_component.rb
  app/components/support_interface/provider_user_permissions_summary_component.rb
  app/components/support_interface/provider_user_summary_component.rb
  app/views/support_interface/provider_users/show.html.erb
  spec/components/support_interface/permissions_list_component_spec.rb
  spec/components/support_interface/provider_user_permissions_summary_component_spec.rb
  spec/components/support_interface/provider_user_summary_component_spec.rb
  spec/system/support_interface/managing_provider_user_notification_preferences_spec.rb
  spec/system/support_interface/managing_provider_users_spec.rb
Labels: Support

#4986 Drop applicationchoice offer column
  db/migrate/20210618132255_remove_offer_from_application_choice.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#4998 Enable Style/StringConcatenation cop
  app/components/filter_component.rb
  app/components/support_interface/reference_with_feedback_component.rb
  app/components/when_emails_are_sent_component.html.erb
  app/forms/support_interface/multiple_provider_users_wizard.rb
  app/lib/state_diagram.rb
  app/mailers/referee_mailer.rb
  app/services/set_open_on_apply_for_new_course.rb
  app/services/support_interface/find_feedback_export.rb
  app/validators/valid_for_notify_validator.rb
  config/rubocop/config/style.yml
  spec/support/json_schema_validator.rb
  spec/validators/word_count_validator_spec.rb
Labels: Core

#5011 Redirect away from prefill form if there is already an application
  app/controllers/candidate_interface/prefill_application_form_controller.rb
  spec/requests/candidate_interface/prefill_application_form_controller_spec.rb
Labels: Sandbox

#5016 Close tags that were left open
  app/views/provider_interface/start_page/show.html.erb
  app/views/support_interface/application_forms/application_choices/change_offered_course/change_offered_course_search.html.erb
  app/views/support_interface/application_forms/courses/new_search.html.erb
Labels: Core

#5007 Begin adopting govuk_summary_list component
  app/components/api_docs/property_list_component.html.erb
  app/frontend/styles/_syntax-highlighting.scss
  app/views/candidate_interface/submitted_application_form/review_submitted.html.erb
Labels: Components

#4997 Update frontend development docs
  docs/frontend.md
Labels: Documentation

#5008 Fix carry over test applications
  app/lib/test_applications.rb
  spec/lib/test_applications_spec.rb
Labels: Core

#5003 Add components and UI for individual conditions
  app/components/provider_interface/conditions_list_component.html.erb
  app/components/provider_interface/conditions_list_component.rb
  app/components/provider_interface/individual_condition_status_form_component.html.erb
  app/components/provider_interface/individual_condition_status_form_component.rb
  app/components/provider_interface/individual_condition_status_review_component.html.erb
  app/components/provider_interface/individual_condition_status_review_component.rb
  app/frontend/styles/_box.scss
  app/frontend/styles/_conditions-list.scss
  app/frontend/styles/application.scss
  spec/components/previews/provider_interface/conditions_list_component_preview.rb
  spec/components/provider_interface/conditions_list_component_spec.rb
  spec/components/provider_interface/individual_condition_status_review_component_spec.rb
Labels: ProVendor, Provider UI

#5037 Update the r4r export to pass the correct ids for candidate_id
  app/services/support_interface/structured_reasons_for_rejection_export.rb
  spec/services/support_interface/structured_reasons_for_rejection_export_spec.rb
Labels: Candidate

#5028 Remove 'add provider user' button if 'new provider user flow' is turned on
  app/views/support_interface/provider_users/index.html.erb
Labels: Support

#5033 Fix site sync concurrency issue
  app/services/teacher_training_public_api/sync_sites.rb
Labels: Bug bash 🐞🔨, Core

#5018 Migrate more components to govuk_summary_list
  app/components/provider_interface/provider_relationship_permissions_list_component.html.erb
  app/components/provider_interface/provider_relationship_permissions_list_component.rb
  app/components/summary_list_component.html.erb
  app/components/summary_list_component.rb
  app/components/support_interface/audit_trail_change_component.html.erb
  app/components/support_interface/audit_trail_change_component.rb
  app/components/support_interface/audit_trail_item_component.html.erb
  app/components/support_interface/audit_trail_item_component.rb
  app/frontend/styles/_table.scss
  db/schema.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
  spec/components/provider_interface/provider_relationship_permissions_list_component_spec.rb
  spec/components/summary_list_component_spec.rb
  spec/components/support_interface/audit_trail_change_component_spec.rb
  spec/components/support_interface/audit_trail_item_component/audit_trail_change_spec.rb
  spec/system/support_interface/editing_address_details_spec.rb
Labels: Components

#5060 Support: show date a course was opened on Apply
  app/components/support_interface/course_details_component.rb
  spec/components/support_interface/course_details_component_spec.rb
Labels: Support

#5063 Enable Style/Alias cop
  app/components/candidate_interface/application_form_course_choice_component.rb
  app/components/candidate_interface/application_form_course_choices_component.rb
  app/components/degree_qualification_cards_component.rb
  app/components/qualifications_component.rb
  app/components/support_interface/data_export_history_component.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/dfe_sign_in_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/support_interface/support_interface_controller.rb
  app/controllers/support_interface/support_users_controller.rb
  app/forms/candidate_interface/degree_enic_form.rb
  app/forms/provider_interface/fields_for_provider_user_permissions_form.rb
  app/models/interview.rb
  app/services/support_interface/application_choices_export.rb
  app/services/support_interface/applications_export.rb
  app/services/support_interface/candidate_journey_tracking_export.rb
  app/services/support_interface/offer_conditions_export.rb
  app/services/support_interface/providers_export.rb
  app/services/support_interface/referee_survey_export.rb
  app/services/support_interface/sites_export.rb
  app/services/support_interface/tad_provider_stats_export.rb
  config/rubocop/config/style.yml
  spec/support/active_record_relation_stub.rb
  spec/support/test_helpers/dfe_sign_in_helpers.rb
Labels: Core

#5054 Enable editing provider notification prefs via support
  app/components/support_interface/provider_user_summary_component.rb
  app/controllers/support_interface/single_provider_user_notifications_controller.rb
  app/views/support_interface/single_provider_user_notifications/edit.html.erb
  config/routes.rb
  spec/system/support_interface/managing_users_v2/managing_provider_user_notification_preferences_spec.rb
Labels: Support
