Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2021-02, with the labels that each got.

#3954 Restructured work experience - add a job
  app/controllers/candidate_interface/restructured_work_history/job_controller.rb
  app/forms/candidate_interface/restructured_work_history/job_form.rb
  app/models/application_experience.rb
  app/views/candidate_interface/restructured_work_history/job/_form.html.erb
  app/views/candidate_interface/restructured_work_history/job/edit.html.erb
  app/views/candidate_interface/restructured_work_history/job/new.html.erb
  config/locales/candidate_interface/restructured_work_history.yml
  config/routes.rb
  spec/forms/candidate_interface/restructured_work_history/job_form_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_restructured_work_history_add_job_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_full_time_education_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_not_worked_with_restructured_work_history_flag_on_spec.rb
Labels: Candidate

#3945 Issues with pdf application downloads
  app/components/header_component.html.erb
  app/components/interview_preferences_component.html.erb
  app/components/personal_statement_component.html.erb
  app/components/primary_navigation_component.html.erb
  app/components/product_header_component.html.erb
  app/components/provider_interface/application_choice_header_component.html.erb
  app/components/provider_interface/diversity_information_component.html.erb
  app/components/provider_interface/safeguarding_declaration_component.html.erb
  app/components/provider_interface/training_with_disability_component.html.erb
  app/components/qualifications_component.html.erb
  app/components/sandbox_feature_component.html.erb
  app/components/tab_navigation_component.html.erb
  app/components/volunteering_history_component.html.erb
  app/components/work_history_component.html.erb
  app/views/provider_interface/application_choices/_references_context.html.erb
  config/application.rb
Labels: ProVendor

#3966 Resolve bug with incorrect data format for view
  app/components/support_interface/application_choice_component.rb
  spec/components/support_interface/application_choice_component_spec.rb
Labels: Bug bash 🐞🔨, ProVendor

#3856 Add interview form
  app/components/provider_interface/interview_details_component.html.erb
  app/components/provider_interface/interview_details_component.rb
  app/controllers/provider_interface/interviews_controller.rb
  app/forms/provider_interface/interview_wizard.rb
  app/frontend/styles/_banner.scss
  app/views/provider_interface/interviews/cancel.html.erb
  app/views/provider_interface/interviews/check.html.erb
  app/views/provider_interface/interviews/new.html.erb
  app/views/provider_interface/interviews/review_cancel.html.erb
  config/locales/interview.yml
  config/routes.rb
  spec/forms/provider_interface/interview_wizard_spec.rb
  spec/system/provider_interface/provider_manages_application_interviews_spec.rb
Labels: ProVendor

#3957 Add structured rejection reasons to the ApplicationChoicesExport
  app/services/support_interface/application_choices_export.rb
  spec/services/support_interface/application_choices_export_spec.rb
Labels: Candidate

#3948 Show all interviews against applications in support
  app/components/support_interface/application_choice_component.rb
  app/components/support_interface/interview_details_component.html.erb
  app/components/support_interface/interview_details_component.rb
  app/models/interview.rb
  app/workers/generate_test_applications.rb
Labels: ProVendor, Support

#3933 Change append operator to assignment, fixes duplication of "ratified by message" in Activity Log
  app/components/provider_interface/activity_log_event_component.rb
  spec/components/provider_interface/activity_log_event_component_spec.rb
Labels: ProVendor

#3970 Remove branch filter
  azure/pipelines/build.yml
Labels: DevOps

#3879 Fix state-mixing bug in "Other qualifications" section
  app/controllers/candidate_interface/other_qualifications/base_controller.rb
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/controllers/candidate_interface/other_qualifications/review_controller.rb
  app/controllers/candidate_interface/other_qualifications/type_controller.rb
  app/forms/candidate_interface/other_qualification_details_form.rb
  app/forms/candidate_interface/other_qualification_type_form.rb
  spec/forms/candidate_interface/other_qualification_details_form_spec.rb
  spec/services/candidate_interface/intermediate_data_service_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_other_qualification_spec.rb
Labels: Candidate

#3964 Add interview events to ApplicationForm history in Support
  app/components/support_interface/audit_trail_component.rb
  spec/system/support_interface/add_audit_comment_spec.rb
  spec/system/support_interface/audit_trail_spec.rb
Labels: ProVendor, Support

#3907 Update rake rspec to use format --progress
  lib/tasks/testing.rake
Labels: Core

#3946 Initial migration for addition of public ids for qualifications
  adr/0018-public-ids-for-qualifications.md
  db/migrate/20210201142920_add_public_id_to_qualifications.rb
  db/schema.rb
  docs/domain-model.png
  lib/tasks/backfill_constituent_grades.rake
Labels: ProVendor

#3967 Improve the support providers view
  app/components/tab_navigation_component.html.erb
  app/components/tab_navigation_component.rb
  app/controllers/support_interface/providers_controller.rb
  app/models/support_interface/providers_filter.rb
  app/views/support_interface/providers/_no_admin_users_warning.html.erb
  app/views/support_interface/providers/_provider_navigation.html.erb
  app/views/support_interface/providers/_providers_navigation.html.erb
  app/views/support_interface/providers/index.html.erb
  app/views/support_interface/providers/other_providers.html.erb
  config/routes.rb
  spec/models/support_interface/providers_filter_spec.rb
  spec/system/support_interface/managing_provider_permissions_spec.rb
  spec/system/support_interface/provider_sync_courses_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
  spec/system/support_interface/viewing_provider_permissions_spec.rb
Labels: ProVendor

#3961 Add 'Has interviews' filter to support console
  app/models/support_interface/applications_filter.rb
  app/services/process_state.rb
  config/locales/application_states.yml
  spec/factories.rb
  spec/models/support_interface/applications_filter_spec.rb
Labels: ProVendor, Support

#3976 Add region column to the sites table
  db/migrate/20210202171852_add_region_code_to_sites.rb
  db/schema.rb
Labels: Candidate

#3909 Fix N+1 query in the support interface
  app/components/support_interface/application_card_component.html.erb
  app/components/support_interface/application_card_component.rb
  app/models/support_interface/applications_filter.rb
Labels: Support

#3962 Ensure conditions status is correct for deferred offers
  app/components/provider_interface/conditions_component.rb
  spec/components/provider_interface/conditions_component_spec.rb
Labels: ProVendor

#3987 Update SortApplicationChoices spec and remove TODOs
  app/components/provider_interface/change_offer/change_location_component.rb
  app/queries/get_all_change_options_from_offered_option.rb
  spec/factories.rb
  spec/services/provider_interface/sort_application_choices_spec.rb
Labels: ProVendor

#3983 Review todo items in the codebase
  app/components/provider_interface/application_timeline_component.rb
  app/components/support_interface/provider_users_table_component.html.erb
  app/forms/candidate_interface/volunteering_role_form.rb
  app/helpers/view_helper.rb
  app/mailers/provider_mailer.rb
  app/models/provider_user.rb
  app/services/provider_interface/hesa_data_export.rb
  app/views/support_interface/provider_users/_provider_user_navigation.html.erb
  app/views/support_interface/provider_users/audits.html.erb
  app/views/support_interface/provider_users/edit.html.erb
  app/views/support_interface/provider_users/show.html.erb
  spec/mailers/previews/provider_mailer_preview.rb
  spec/requests/candidate_interface/authentication_spec.rb
  spec/services/support_interface/application_choices_export_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: Candidate, ProVendor

#3982 Fix structured_grades data migration rake task
  lib/tasks/backfill_constituent_grades.rake
Labels: ProVendor

#3926 Other qualifications: fix issue with grades when changing BTEC to GCSE
  app/forms/candidate_interface/other_qualification_details_form.rb
  app/forms/candidate_interface/other_qualification_type_form.rb
  spec/system/candidate_interface/entering_details/candidate_entering_other_qualification_btec_spec.rb
Labels: Candidate

#3985 Enable GCSE year editing via support
  app/components/gcse_qualification_cards_component.html.erb
  app/components/gcse_qualification_cards_component.rb
  app/controllers/support_interface/application_forms/gcses_controller.rb
  app/forms/support_interface/application_forms/edit_gcse_form.rb
  app/views/support_interface/application_forms/gcses/edit.html.erb
  config/locales/support_interface/support_interface.yml
  config/routes.rb
  spec/system/support_interface/editing_gcse_spec.rb
Labels: Support

#3997 Fix one time export for UR
  app/services/support_interface/rejected_candidates_export.rb
Labels: Candidate

#3992 Fix flaky support audit trail spec; minor interview tweaks
  app/components/support_interface/audit_trail_component.rb
  app/components/support_interface/audit_trail_item_component.html.erb
  app/models/support_interface/applications_filter.rb
  spec/system/support_interface/audit_trail_spec.rb
Labels: ProVendor

#3965 Migrate to use constituent grades
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/components/gcse_qualification_cards_component.rb
  app/forms/candidate_interface/english_gcse_grade_form.rb
  app/forms/candidate_interface/science_gcse_grade_form.rb
  app/models/application_qualification.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/support_interface/qualifications_export.rb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/components/gcse_qualification_cards_component_spec.rb
  spec/forms/candidate_interface/english_gcse_grade_form_spec.rb
  spec/forms/candidate_interface/science_gcse_grade_form_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/services/support_interface/qualifications_export_spec.rb
Labels: ProVendor

#4004 Add a spec to cover more of the english gcse form
  spec/system/candidate_interface/entering_details/candidate_entering_english_gcse_spec.rb
Labels: Candidate

#4008 Add Candidate ID to application page in Support
  app/components/support_interface/application_summary_component.rb
Labels: Support

#4007 Conform to Sentry's user_context schema
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/integrations/notify_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/referee_interface/reference_controller.rb
  app/controllers/support_interface/support_interface_controller.rb
  app/controllers/vendor_api/vendor_api_controller.rb
Labels: Core

#3969 Reasons for rejection support search page
  app/components/support_interface/reason_for_rejection_dashboard_section_component.html.erb
  app/components/support_interface/reason_for_rejection_dashboard_section_component.rb
  app/components/support_interface/reasons_for_rejection_dashboard_component.html.erb
  app/components/support_interface/reasons_for_rejection_search_breadcrumb_component.html.erb
  app/components/support_interface/reasons_for_rejection_search_breadcrumb_component.rb
  app/components/support_interface/reasons_for_rejection_search_results_component.html.erb
  app/components/support_interface/reasons_for_rejection_search_results_component.rb
  app/components/support_interface/sub_reasons_for_rejection_table_component.html.erb
  app/components/support_interface/sub_reasons_for_rejection_table_component.rb
  app/controllers/support_interface/performance_controller.rb
  app/forms/provider_interface/reasons_for_rejection_wizard.rb
  app/frontend/styles/_mark.scss
  app/frontend/styles/_overrides.scss
  app/frontend/styles/application.scss
  app/lib/test_applications.rb
  app/models/reasons_for_rejection.rb
  app/models/reasons_for_rejection_feature_metrics.rb
  app/queries/reasons_for_rejection_applications_query.rb
  app/queries/reasons_for_rejection_count_query.rb
  app/views/support_interface/performance/reasons_for_rejection_application_choices.html.erb
  config/routes.rb
  spec/components/support_interface/reasons_for_rejection_search_breadcrumb_component_spec.rb
  spec/components/support_interface/reasons_for_rejection_search_results_component_spec.rb
  spec/forms/provider_interface/reasons_for_rejection_wizard_spec.rb
  spec/system/support_interface/reasons_for_rejection_dashboard_spec.rb
Labels: Candidate

#4020 Exclude interviews from activity log for now
  app/queries/get_activity_log_events.rb
  spec/queries/get_activity_log_events_spec.rb
Labels: ProVendor

#4006 Allow bulk creation of test applications for ratified courses via API
  app/controllers/vendor_api/test_data_controller.rb
  app/lib/test_applications.rb
  app/queries/get_courses_ratified_by_provider.rb
  app/views/api_docs/pages/release_notes.md
  config/vendor-api-experimental.yml
  spec/lib/test_applications_spec.rb
  spec/queries/get_courses_ratified_by_provider_spec.rb
Labels: API docs, ProVendor

#4011 Remove the feedback prompts feature flag
  app/components/candidate_interface/application_feedback_component.html.erb
  app/services/feature_flag.rb
  spec/system/candidate_interface/feedback/candidate_provides_feedback_while_completing_their_application_spec.rb
Labels: Candidate

#4025 Link to ApplicationChoices from API log
  app/components/support_interface/vendor_api_request_details_component.html.erb
  app/components/support_interface/vendor_api_request_details_component.rb
  app/views/support_interface/vendor_api_requests/index.html.erb
  spec/components/support_interface/vendor_api_request_details_component_spec.rb
Labels: Support

#3989 Set public IDs for qualifications
  Gemfile
  Gemfile.lock
  adr/0018-public-ids-for-qualifications.md
  app/services/backfill_qualification_public_id.rb
  db/migrate/20210203160529_add_qualification_public_id_sequence.rb
  db/schema.rb
  docs/domain-model.png
  lib/tasks/backfill_qualification_public_ids.rake
  spec/services/backfill_qualification_public_id_spec.rb
Labels: ProVendor

#4022 Add region to the locations export
  app/services/support_interface/locations_export.rb
  spec/factories.rb
  spec/services/support_interface/locations_export_spec.rb
Labels: Candidate

#3960 Restructured work history - update the design of review page and candidate flow
  app/components/candidate_interface/restructured_work_history/gap_component.html.erb
  app/components/candidate_interface/restructured_work_history/gap_component.rb
  app/components/candidate_interface/restructured_work_history/job_component.html.erb
  app/components/candidate_interface/restructured_work_history/job_component.rb
  app/components/candidate_interface/restructured_work_history/review_component.html.erb
  app/components/candidate_interface/restructured_work_history/review_component.rb
  app/components/candidate_interface/restructured_work_history/work_break_component.html.erb
  app/components/candidate_interface/restructured_work_history/work_break_component.rb
  app/controllers/candidate_interface/restructured_work_history/break_controller.rb
  app/controllers/candidate_interface/restructured_work_history/job_controller.rb
  app/controllers/candidate_interface/restructured_work_history/review_controller.rb
  app/controllers/candidate_interface/restructured_work_history/start_controller.rb
  app/forms/candidate_interface/restructured_work_history/choice_form.rb
  app/forms/candidate_interface/restructured_work_history/work_breaks_form.rb
  app/forms/candidate_interface/restructured_work_history/work_history_break_form.rb
  app/frontend/styles/_grid.scss
  app/frontend/styles/application.scss
  app/views/candidate_interface/restructured_work_history/break/_form.html.erb
  app/views/candidate_interface/restructured_work_history/break/confirm_destroy.html.erb
  app/views/candidate_interface/restructured_work_history/break/edit.html.erb
  app/views/candidate_interface/restructured_work_history/break/new.html.erb
  app/views/candidate_interface/restructured_work_history/job/confirm_destroy.html.erb
  app/views/candidate_interface/restructured_work_history/job/edit.html.erb
  app/views/candidate_interface/restructured_work_history/review/show.html.erb
  config/initializers/date_formats.rb
  config/locales/candidate_interface/restructured_work_history.yml
  config/locales/en.yml
  config/routes.rb
  spec/components/candidate_interface/restructured_work_history/gap_component_spec.rb
  spec/components/candidate_interface/restructured_work_history/job_component_spec.rb
  spec/components/candidate_interface/restructured_work_history/review_component_spec.rb
  spec/components/candidate_interface/restructured_work_history/work_break_component_spec.rb
  spec/forms/candidate_interface/restructured_work_history/work_history_break_form_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_deleting_work_history_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_restructured_work_history_add_job_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_breaks_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_full_time_education_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_not_worked_with_restructured_work_history_flag_on_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_edits_work_history_after_completing_the_section_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_entering_blank_work_history_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_entering_work_history_breaks_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_entering_work_history_not_worked_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_entering_work_history_spec.rb
Labels: Candidate

#4012 Remove international address feature flag
  app/components/candidate_interface/contact_details_review_component.rb
  app/components/support_interface/personal_details_component.rb
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/support_interface/application_forms/address_details_controller.rb
  app/forms/candidate_interface/contact_details_form.rb
  app/forms/support_interface/application_forms/edit_address_details_form.rb
  app/models/application_form.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/contact_details/address/edit.html.erb
  app/views/support_interface/application_forms/address_details/edit.html.erb
  config/locales/candidate_interface/contact_details.yml
  config/locales/support_interface/support_interface.yml
  db/migrate/20210208105018_clean_up_international_addresses_data.rb
  db/schema.rb
  spec/components/candidate_interface/contact_details_review_component_spec.rb
  spec/factories.rb
  spec/forms/candidate_interface/contact_details_form_spec.rb
  spec/forms/support_interface/application_forms/edit_address_details_form_spec.rb
  spec/models/application_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/entering_details/candidate_entering_contact_details_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_contact_details_without_international_addresses_spec.rb
  spec/system/support_interface/editing_address_details_spec.rb
Labels: Candidate

#4005 Add more filtering to the Support /providers view
  app/models/support_interface/providers_filter.rb
  app/views/support_interface/providers/_providers_navigation.html.erb
  app/views/support_interface/providers/index.html.erb
  spec/models/support_interface/providers_filter_spec.rb
  spec/system/support_interface/provider_sync_courses_spec.rb
Labels: Support

#4026 Implement interview schedule
  app/components/provider_interface/interview_card_component.html.erb
  app/components/provider_interface/interview_card_component.rb
  app/controllers/provider_interface/interview_schedules_controller.rb
  app/controllers/provider_interface/interviews_controller.rb
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_interview_card.scss
  app/helpers/navigation_items.rb
  app/models/interview.rb
  app/views/provider_interface/interview_schedules/past.html.erb
  app/views/provider_interface/interview_schedules/show.html.erb
  config/routes.rb
  spec/components/provider_interface/interview_card_component_spec.rb
  spec/factories.rb
  spec/system/provider_interface/provider_can_view_interview_schedule_spec.rb
Labels: ProVendor

#3984 Add interview emails
  app/mailers/candidate_mailer.rb
  app/services/cancel_interview.rb
  app/services/create_interview.rb
  app/services/update_interview.rb
  app/views/candidate_mailer/interview_cancelled.text.erb
  app/views/candidate_mailer/interview_updated.text.erb
  app/views/candidate_mailer/new_interview.text.erb
  config/locales/emails/candidate_mailer.yml
  spec/factories.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/cancel_interview_spec.rb
  spec/services/create_interview_spec.rb
  spec/services/update_interview_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: ProVendor

#4034 Fix errors on support interface R4R search page
  app/components/support_interface/reasons_for_rejection_search_results_component.rb
  app/components/support_interface/sub_reasons_for_rejection_table_component.rb
  spec/components/support_interface/reasons_for_rejection_search_results_component_spec.rb
  spec/system/support_interface/reasons_for_rejection_dashboard_spec.rb
Labels: Support

#4029 Moved respond_by_date out of ViewHelper and into ApplicationCompleteContentComponent
  app/components/candidate_interface/application_complete_content_component.rb
  app/helpers/view_helper.rb
  spec/components/candidate_interface/application_complete_content_component_spec.rb
  spec/components/dfe_sign_in_button_component_spec.rb
  spec/helpers/view_helper_spec.rb
Labels: Candidate

#4003 Get support content in candidate emails
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/_get_help.text.erb
  app/views/candidate_mailer/_get_support.text.erb
  app/views/candidate_mailer/application_rejected_all_applications_rejected.text.erb
  app/views/candidate_mailer/application_rejected_awaiting_decision_only.text.erb
  app/views/candidate_mailer/application_rejected_offers_only.text.erb
  app/views/candidate_mailer/application_rejected_one_offer_one_awaiting_decision.text.erb
  app/views/candidate_mailer/application_submitted.text.erb
  app/views/candidate_mailer/application_submitted_apply_again.text.erb
  app/views/candidate_mailer/apply_again_call_to_action.text.erb
  app/views/candidate_mailer/changed_offer.text.erb
  app/views/candidate_mailer/chase_candidate_decision.text.erb
  app/views/candidate_mailer/conditions_met.text.erb
  app/views/candidate_mailer/conditions_not_met.text.erb
  app/views/candidate_mailer/decline_last_application_choice.text.erb
  app/views/candidate_mailer/declined_by_default.text.erb
  app/views/candidate_mailer/declined_by_default_with_rejections.text.erb
  app/views/candidate_mailer/declined_by_default_without_rejections.text.erb
  app/views/candidate_mailer/deferred_offer.text.erb
  app/views/candidate_mailer/deferred_offer_reminder.text.erb
  app/views/candidate_mailer/feedback_received_for_application_rejected_by_default.text.erb
  app/views/candidate_mailer/find_another_course.text.erb
  app/views/candidate_mailer/new_offer/decisions_pending.text.erb
  app/views/candidate_mailer/new_offer/multiple_offers.text.erb
  app/views/candidate_mailer/new_offer/single_offer.text.erb
  app/views/candidate_mailer/reinstated_offer.text.erb
  app/views/candidate_mailer/ucas_match_initial_email_duplicate_applications.text.erb
  app/views/candidate_mailer/ucas_match_initial_email_multiple_acceptances.text.erb
  app/views/candidate_mailer/ucas_match_reminder_email_duplicate_applications.text.erb
  app/views/candidate_mailer/ucas_match_reminder_email_multiple_acceptances.text.erb
  app/views/candidate_mailer/ucas_match_resolved_on_apply_email.text.erb
  app/views/candidate_mailer/withdraw_last_application_choice.text.erb
  app/views/layouts/candidate_email_with_support_footer.text.erb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/candidate_mailer_ucas_match_reminder_email_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
Labels: Candidate

#3943 Spec enhancements - stubbing in factories
  spec/models/ucas_match_spec.rb
  spec/models/ucas_matched_application_spec.rb
  spec/rails_helper.rb
  spec/support/factory_stubs/dual_application_ucas_match_stub.rb
Labels: Core

#4045 Remove one time export for UR
  app/models/data_export.rb
  app/services/support_interface/rejected_candidates_export.rb
Labels: Candidate

#4028 Add DateValidator & YearValidator
  app/forms/candidate_interface/degree_year_form.rb
  app/forms/candidate_interface/english_foreign_language/ielts_form.rb
  app/forms/candidate_interface/english_foreign_language/other_efl_qualification_form.rb
  app/forms/candidate_interface/english_foreign_language/toefl_form.rb
  app/forms/candidate_interface/english_gcse_grade_form.rb
  app/forms/candidate_interface/gcse_qualification_details_form.rb
  app/forms/candidate_interface/languages_form.rb
  app/forms/candidate_interface/other_qualification_details_form.rb
  app/forms/candidate_interface/personal_details_form.rb
  app/forms/candidate_interface/restructured_work_history/job_form.rb
  app/forms/candidate_interface/restructured_work_history/work_history_break_form.rb
  app/forms/candidate_interface/science_gcse_grade_form.rb
  app/forms/candidate_interface/volunteering_role_form.rb
  app/forms/candidate_interface/work_experience_form.rb
  app/forms/candidate_interface/work_history_break_form.rb
  app/forms/provider_interface/interview_wizard.rb
  app/forms/support_interface/application_forms/course_search_form.rb
  app/forms/support_interface/application_forms/edit_applicant_details_form.rb
  app/forms/support_interface/application_forms/edit_reference_details_form.rb
  app/forms/support_interface/application_forms/pick_course_form.rb
  app/helpers/date_validation_helper.rb
  app/lib/validation_utils.rb
  app/validators/concerns/date_and_year_concerns.rb
  app/validators/date_validator.rb
  app/validators/year_validator.rb
  config/locales/candidate_interface/degree.yml
  config/locales/candidate_interface/english_foreign_language.yml
  config/locales/candidate_interface/gcse.yml
  config/locales/candidate_interface/other_qualification.yml
  config/locales/candidate_interface/personal_details.yml
  config/locales/candidate_interface/restructured_work_history.yml
  config/locales/candidate_interface/volunteering.yml
  config/locales/candidate_interface/work_history.yml
  config/locales/en.yml
  config/locales/support_interface/support_interface.yml
  spec/forms/candidate_interface/degree_year_form_spec.rb
  spec/forms/candidate_interface/english_foreign_language/ielts_form_spec.rb
  spec/forms/candidate_interface/english_foreign_language/other_efl_qualification_form_spec.rb
  spec/forms/candidate_interface/english_foreign_language/toefl_form_spec.rb
  spec/forms/candidate_interface/other_qualification_details_form_spec.rb
  spec/forms/candidate_interface/restructured_work_history/job_form_spec.rb
  spec/forms/candidate_interface/work_experience_form_spec.rb
  spec/forms/provider_interface/interview_wizard_spec.rb
  spec/lib/validation_utils_spec.rb
  spec/support/candidate_interface/shared_examples/end_date_validation.rb
  spec/support/candidate_interface/shared_examples/start_date_validation.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_volunteering_and_school_experience_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_restructured_work_history_add_job_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_entering_work_history_spec.rb
  spec/system/support_interface/editing_applicant_details_spec.rb
  spec/validators/date_validator_spec.rb
  spec/validators/year_validator_spec.rb
Labels: Core

#3995 Add constants for GIT contact numbers and URLs
  app/components/personal_statement_component.html.erb
  app/components/personal_statement_component.rb
  app/components/provider_interface/training_with_disability_component.html.erb
  app/views/candidate_interface/apply_from_find/apply_on_ucas_only.html.erb
  app/views/candidate_interface/course_choices/ucas/no_courses.html.erb
  app/views/candidate_interface/course_choices/ucas/with_course.html.erb
  app/views/candidate_interface/decisions/offer.html.erb
  app/views/candidate_interface/degrees/naric/_form_fields.html.erb
  app/views/candidate_interface/gcse/naric/edit.html.erb
  app/views/candidate_interface/gcse/type/edit.html.erb
  app/views/candidate_interface/personal_details/right_to_work_or_study/_shared_form.html.erb
  app/views/candidate_interface/personal_statement/edit.html.erb
  app/views/candidate_interface/training_with_a_disability/edit.html.erb
  app/views/candidate_mailer/_get_support.text.erb
  app/views/content/terms_candidate.md
  app/views/support_interface/application_forms/right_to_work_or_study/edit.html.erb
  config/locales/en.yml
Labels: Candidate, Content, Provider UI, Support

#4059 Delete deprecated COVID-19 content
  app/views/content/covid_19_guidance.md
Labels: Content, ProVendor, Provider UI

#3501 Add ability to run read queries on the database from support
  Dockerfile
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  config/application.rb
  config/blazer.yml
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/routes.rb
  db/migrate/20210210142049_install_blazer.rb
  db/schema.rb
  docs/domain-model.png
  spec/system/support_interface/blazer_sql_spec.rb
Labels: Support

#4032 Link to Get Into Teaching from footer and sidebar
  app/views/candidate_interface/shared/_support.html.erb
  app/views/layouts/_footer_meta_candidate.html.erb
  config/locales/en.yml
Labels: Candidate

#4047 Restore interviews in the provider activity log
  app/components/provider_interface/application_timeline_component.rb
  app/queries/get_activity_log_events.rb
  config/brakeman.ignore
  spec/components/provider_interface/application_timeline_component_spec.rb
  spec/queries/get_activity_log_events_spec.rb
Labels: ProVendor

#4058 Change govuk_link_to/govuk_button_link_to be consistent with Rails
  app/components/candidate_interface/restructured_work_history/job_component.html.erb
  app/components/candidate_interface/restructured_work_history/work_break_component.html.erb
  app/components/provider_interface/provider_relationship_permissions_list_component.html.erb
  app/components/support_interface/provider_users_table_component.html.erb
  app/helpers/view_helper.rb
  app/views/candidate_interface/course_choices/have_you_chosen/go_to_find.html.erb
  app/views/candidate_interface/restructured_work_history/review/show.html.erb
  app/views/candidate_interface/volunteering/review/show.html.erb
  app/views/candidate_interface/work_history/review/show.html.erb
  app/views/provider_interface/start_page/show.html.erb
  app/views/support_interface/data_exports/index.html.erb
  app/views/support_interface/support_users/index.html.erb
  spec/helpers/view_helper_spec.rb
Labels: Core

#4054 Small fixes to interviews
  app/components/provider_interface/application_choice_header_component.html.erb
  app/components/provider_interface/interview_and_course_summary_component.html.erb
  app/components/provider_interface/interview_and_course_summary_component.rb
  app/controllers/provider_interface/interviews_controller.rb
  app/forms/provider_interface/cancel_interview_wizard.rb
  app/views/provider_interface/interviews/cancel.html.erb
  app/views/provider_interface/interviews/index.html.erb
  app/views/provider_interface/interviews/new.html.erb
  app/views/provider_interface/interviews/review_cancel.html.erb
  config/locales/interview.yml
  spec/components/provider_interface/interview_and_course_summary_component_spec.rb
  spec/forms/provider_interface/cancel_interview_wizard_spec.rb
  spec/forms/provider_interface/interview_wizard_spec.rb
  spec/system/provider_interface/provider_manages_application_interviews_spec.rb
Labels: ProVendor

#4072 Enforce `start_date` presence on candidate work history
  app/forms/candidate_interface/restructured_work_history/job_form.rb
  app/forms/candidate_interface/work_experience_form.rb
  spec/forms/candidate_interface/restructured_work_history/job_form_spec.rb
  spec/forms/candidate_interface/work_experience_form_spec.rb
  spec/support/candidate_interface/shared_examples/start_date_validation.rb
Labels: Candidate

#4075 Pass $(databaseUsername) from variable group
  azure/pipelines/build.yml
  azure/pipelines/release.yml
Labels: DevOps

#4076 Don’t render automated reminder text on reference reminder page, if already sent
  app/views/candidate_interface/references/reminder/new.html.erb
Labels: Candidate

#4083 Resolves sentry error caused by lack of validation of volunteering role start date
  app/forms/candidate_interface/volunteering_role_form.rb
  spec/forms/candidate_interface/volunteering_role_form_spec.rb
Labels: Candidate

#4056 Remove candidate and referee guidance from provider interface
  app/components/degree_qualification_cards_component.html.erb
  app/components/gcse_qualification_cards_component.html.erb
  app/components/interview_preferences_component.html.erb
  app/components/language_skills_component.html.erb
  app/components/personal_statement_component.html.erb
  app/components/provider_interface/course_details_component.html.erb
  app/components/provider_interface/diversity_information_component.html.erb
  app/components/provider_interface/personal_details_component.html.erb
  app/components/provider_interface/safeguarding_declaration_component.html.erb
  app/components/provider_interface/training_with_disability_component.html.erb
  app/components/qualifications_component.html.erb
  app/components/volunteering_history_component.html.erb
  app/components/work_history_component.html.erb
  app/views/provider_interface/application_choices/_references.html.erb
  app/views/provider_interface/application_choices/_references_context.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: Provider UI, Support

#4084 Fix setup_local_dev_data task by syncing courses and sites synchronously
  app/services/teacher_training_public_api/sync_courses.rb
  app/services/teacher_training_public_api/sync_provider.rb
  lib/tasks/local_dev.rake
Labels: Core

#4085 3363 interview schedule page bugs
  app/components/provider_interface/interview_and_course_summary_component.html.erb
  app/components/provider_interface/interview_card_component.html.erb
  app/views/provider_interface/interview_schedules/past.html.erb
  app/views/provider_interface/interview_schedules/show.html.erb
  spec/components/provider_interface/interview_card_component_spec.rb
  spec/system/provider_interface/provider_can_view_interview_schedule_spec.rb
Labels: ProVendor

#4087 Interview cancellation flow bugfixes
  app/forms/provider_interface/cancel_interview_wizard.rb
  app/views/provider_interface/interviews/cancel.html.erb
  app/views/provider_interface/interviews/check.html.erb
  app/views/provider_interface/interviews/edit.html.erb
  app/views/provider_interface/interviews/new.html.erb
  app/views/provider_interface/interviews/review_cancel.html.erb
  config/locales/en.yml
  config/locales/interview.yml
  spec/forms/provider_interface/cancel_interview_wizard_spec.rb
Labels: ProVendor

#4092 Use POST for check answers pages in interview flows rather than GET
  app/views/provider_interface/interviews/cancel.html.erb
  app/views/provider_interface/interviews/edit.html.erb
  app/views/provider_interface/interviews/new.html.erb
  config/routes.rb
Labels: ProVendor

#4091 Include interview feature info on service guidance page
  app/views/content/service_guidance_provider.md
Labels: ProVendor

#4096 Fix link to online chat in candidate email support footer
  app/views/candidate_mailer/_get_support.text.erb
Labels: Candidate

#4097 Fix double error in other efl qualifications view
  app/views/candidate_interface/english_foreign_language/other_efl_qualification/_form_fields.html.erb
Labels: Bug bash 🐞🔨, Candidate

#4089 Partition interviews into past and upcoming
  app/controllers/provider_interface/interviews_controller.rb
  app/forms/provider_interface/interview_wizard.rb
  app/views/provider_interface/interview_schedules/past.html.erb
  app/views/provider_interface/interview_schedules/show.html.erb
  app/views/provider_interface/interviews/index.html.erb
  config/locales/interview.yml
  spec/system/provider_interface/provider_manages_application_interviews_spec.rb
Labels: ProVendor

#4093 Always show provider interface calls to action when applicable
  app/components/provider_interface/application_choice_header_component.rb
Labels: ProVendor

#4070 Interview wizard fixes
  app/components/provider_interface/interview_details_component.rb
  app/forms/provider_interface/interview_wizard.rb
  app/views/provider_interface/interviews/_form.html.erb
  app/views/provider_interface/interviews/edit.html.erb
  app/views/provider_interface/interviews/new.html.erb
  config/initializers/date_formats.rb
  config/locales/interview.yml
  spec/components/candidate_interface/reference_history_component_spec.rb
  spec/components/provider_interface/application_timeline_component_spec.rb
  spec/components/provider_interface/interview_details_component_spec.rb
  spec/components/support_interface/application_choice_component_spec.rb
  spec/components/support_interface/audit_trail_component_spec.rb
  spec/components/support_interface/feature_audit_trail_component_spec.rb
  spec/config/initializers/date_formats_spec.rb
  spec/forms/provider_interface/interview_wizard_spec.rb
  spec/helpers/view_helper_spec.rb
  spec/system/candidate_interface/references/candidate_views_reference_history_spec.rb
  spec/system/provider_interface/provider_manages_application_interviews_spec.rb
Labels: ProVendor

#4077 Correct policy on when we show the Interviews tab and when interviews are editable
  app/components/provider_interface/application_choice_header_component.rb
  app/controllers/provider_interface/interviews_controller.rb
  app/services/application_state_change.rb
  app/views/provider_interface/interviews/index.html.erb
  spec/components/provider_interface/application_choice_header_component_spec.rb
  spec/system/provider_interface/provider_manages_application_interviews_spec.rb
Labels: ProVendor

#4094 Add interview emails to 'When emails are sent' doc
  config/locales/application_states.yml
  spec/system/support_interface/docs_spec.rb
Labels: Support

#4064 Structured reasons for rejection on RBD
  app/components/provider_interface/activity_log_event_component.rb
  app/components/provider_interface/application_choice_header_component.html.erb
  app/components/provider_interface/application_choice_header_component.rb
  app/components/provider_interface/application_feedback_component.html.erb
  app/components/provider_interface/application_feedback_component.rb
  app/components/provider_interface/application_timeline_component.rb
  app/components/provider_interface/feedback_preview_component.rb
  app/components/provider_interface/status_box_components/rejected_component.html.erb
  app/components/provider_interface/status_box_components/rejected_component.rb
  app/controllers/provider_interface/application_choices_controller.rb
  app/controllers/provider_interface/feedback_controller.rb
  app/controllers/provider_interface/reasons_for_rejection_controller.rb
  app/mailers/candidate_mailer.rb
  app/models/application_choice.rb
  app/services/feature_flag.rb
  app/services/provider_interface/sort_application_choices.rb
  app/services/reject_by_default_feedback.rb
  app/views/candidate_mailer/_reasons_for_rejection.text.erb
  app/views/candidate_mailer/feedback_received_for_application_rejected_by_default.text.erb
  app/views/provider_interface/application_choices/feedback.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/provider_interface/feedback/check.html.erb
  app/views/provider_interface/reasons_for_rejection/check.html.erb
  app/views/provider_interface/reasons_for_rejection/edit_initial_questions.html.erb
  config/routes.rb
  spec/components/provider_interface/activity_log_event_component_spec.rb
  spec/components/provider_interface/application_choice_header_component_spec.rb
  spec/components/provider_interface/application_timeline_component_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/models/application_choice_spec.rb
  spec/services/provider_interface/sort_application_choices_spec.rb
  spec/services/reject_by_default_feedback_spec.rb
  spec/services/save_and_send_reject_by_default_feedback_spec.rb
  spec/system/provider_interface/provider_gives_feedback_for_rejected_by_default_spec.rb
  spec/system/provider_interface/provider_gives_simple_feedback_for_rejected_by_default_spec.rb
  spec/system/provider_interface/reject_a_rejected_application_spec.rb
  spec/system/provider_interface/reject_an_application_spec.rb
Labels: ProVendor

#4079 Add notifications export with daily schedule
  app/exports/notifications_export.yml
  app/models/data_export.rb
  app/services/support_interface/notifications_export.rb
  config/clock.rb
  spec/services/support_interface/notifications_export_spec.rb
Labels: ProVendor

#4109 Change offered course option column type to BIGINT
  db/migrate/20210217131741_change_offered_course_option_column_type.rb
  db/schema.rb
Labels: Core

#4110 Refactoring BaseControllers where appropriate
  app/components/candidate_interface/contact_details_review_component.html.erb
  app/components/candidate_interface/contact_details_review_component.rb
  app/components/candidate_interface/personal_details_review_component.html.erb
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/candidate_interface/contact_details/address_type_controller.rb
  app/controllers/candidate_interface/contact_details/phone_number_controller.rb
  app/controllers/candidate_interface/personal_details/name_and_dob_controller.rb
  app/controllers/candidate_interface/references/base_controller.rb
  app/controllers/candidate_interface/references/candidate_name_controller.rb
  app/controllers/candidate_interface/references/email_address_controller.rb
  app/controllers/candidate_interface/references/name_controller.rb
  app/controllers/candidate_interface/references/relationship_controller.rb
  app/controllers/candidate_interface/references/reminder_controller.rb
  app/controllers/candidate_interface/references/request_controller.rb
  app/controllers/candidate_interface/references/retry_request_controller.rb
  app/controllers/candidate_interface/references/review_controller.rb
  app/controllers/candidate_interface/references/start_controller.rb
  app/controllers/candidate_interface/volunteering/base_controller.rb
  app/controllers/candidate_interface/volunteering/destroy_controller.rb
  app/controllers/candidate_interface/volunteering/role_controller.rb
  app/controllers/candidate_interface/volunteering/start_controller.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/views/candidate_interface/contact_details/phone_number/edit.html.erb
  app/views/candidate_interface/personal_details/name_and_dob/_shared_form.html.erb
  app/views/candidate_interface/personal_details/name_and_dob/edit.html.erb
  app/views/candidate_interface/personal_details/name_and_dob/new.html.erb
  app/views/candidate_interface/personal_details/nationalities/new.html.erb
  app/views/candidate_interface/references/start/show.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  app/views/candidate_interface/volunteering/role/_form.html.erb
  app/views/candidate_interface/volunteering/role/edit.html.erb
  app/views/candidate_interface/volunteering/role/new.html.erb
  app/views/candidate_interface/volunteering/start/show.html.erb
  config/routes.rb
  spec/components/candidate_interface/contact_details_review_component_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/requests/candidate_interface/audit_trail_spec.rb
  spec/requests/candidate_interface/validation_error_tracking_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/entering_details/candidate_entering_contact_details_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
Labels: Candidate

#4098 Interviews tab summary component content changes
  app/components/provider_interface/interview_and_course_summary_component.rb
  app/components/provider_interface/interview_card_component.html.erb
  spec/components/provider_interface/interview_and_course_summary_component_spec.rb
Labels: ProVendor

#4090 Restructured Work History cleanup
  app/components/candidate_interface/work_history_review_component.rb
  app/controllers/candidate_interface/work_history/base_controller.rb
  app/controllers/candidate_interface/work_history/break_controller.rb
  app/controllers/candidate_interface/work_history/breaks_controller.rb
  app/controllers/candidate_interface/work_history/destroy_controller.rb
  app/controllers/candidate_interface/work_history/edit_controller.rb
  app/controllers/candidate_interface/work_history/explanation_controller.rb
  app/controllers/candidate_interface/work_history/length_controller.rb
  app/controllers/candidate_interface/work_history/review_controller.rb
  app/forms/candidate_interface/restructured_work_history/job_form.rb
  app/forms/candidate_interface/restructured_work_history/work_breaks_form.rb
  app/forms/candidate_interface/work_breaks_form.rb
  app/queries/get_application_choices_for_providers.rb
  app/views/candidate_interface/work_history/breaks/edit.html.erb
  config/locales/candidate_interface/work_history.yml
  config/locales/en.yml
  config/routes.rb
  spec/components/candidate_interface/work_history_review_component_spec.rb
  spec/factories.rb
  spec/forms/candidate_interface/restructured_work_history/job_form_spec.rb
  spec/forms/candidate_interface/work_breaks_form_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_not_worked_spec.rb
Labels: Candidate

#4126 Remove repeated footer on the interview emails
  app/views/candidate_mailer/_get_support.text.erb
  app/views/candidate_mailer/interview_cancelled.text.erb
  app/views/candidate_mailer/interview_updated.text.erb
  app/views/candidate_mailer/new_interview.text.erb
  app/views/layouts/candidate_email_with_support_footer.text.erb
Labels: ProVendor

#4125 Show applications count on the index page in the header and title
  app/controllers/provider_interface/application_choices_controller.rb
  app/views/provider_interface/application_choices/index.html.erb
  spec/system/provider_interface/see_applications_spec.rb
Labels: Accessibility, ProVendor

#4107 Fix bugs on work history flow
  app/controllers/candidate_interface/restructured_work_history/break_controller.rb
  app/controllers/candidate_interface/restructured_work_history/job_controller.rb
  app/controllers/candidate_interface/restructured_work_history/start_controller.rb
  app/forms/candidate_interface/restructured_work_history/choice_form.rb
  app/forms/candidate_interface/restructured_work_history/job_form.rb
  app/forms/candidate_interface/restructured_work_history/work_history_break_form.rb
  app/views/candidate_interface/restructured_work_history/job/_form.html.erb
  app/views/candidate_interface/restructured_work_history/start/choice.html.erb
  config/locales/candidate_interface/restructured_work_history.yml
  config/locales/en.yml
  spec/forms/candidate_interface/restructured_work_history/choice_form_spec.rb
  spec/forms/candidate_interface/restructured_work_history/job_form_spec.rb
  spec/forms/candidate_interface/restructured_work_history/work_history_break_form_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_breaks_spec.rb
Labels: Candidate

#4100 Add NotificationMessageComponent
  app/components/candidate_interface/apply_again_banner_component.html.erb
  app/components/candidate_interface/apply_again_banner_component.rb
  app/components/candidate_interface/carry_over_banner_component.html.erb
  app/components/candidate_interface/deadline_banner_component.html.erb
  app/components/candidate_interface/reopen_banner_component.html.erb
  app/components/candidate_interface/ucas_downtime_component.html.erb
  app/components/flash_message_component.html.erb
  app/components/flash_message_component.rb
  app/components/notification_message_component.html.erb
  app/components/notification_message_component.rb
  app/frontend/styles/_banner.scss
  app/frontend/styles/_notification_banner.scss
  app/frontend/styles/application.scss
  app/views/provider_interface/application_choices/index.html.erb
  app/views/provider_interface/sessions/authentication_fallback.html.erb
  app/views/provider_interface/sessions/new.html.erb
  app/views/provider_interface/start_page/show.html.erb
  app/views/support_interface/sessions/authentication_fallback.html.erb
  config/locales/notification_banner.yml
  spec/components/flash_message_component_spec.rb
  spec/components/notification_message_component_spec.rb
  spec/components/previews/notification_message_component_preview.rb
Labels: Core

#4129 Correct error messages for date validations
  config/locales/en.yml
  config/locales/interview.yml
  spec/forms/candidate_interface/personal_details_form_spec.rb
  spec/forms/candidate_interface/restructured_work_history/job_form_spec.rb
  spec/forms/candidate_interface/work_experience_form_spec.rb
  spec/forms/provider_interface/interview_wizard_spec.rb
Labels: ProVendor

#4078 Enforce use of govuk_link_to et al
  .rubocop.yml
  app/components/candidate_interface/break_in_work_history_component.html.erb
  app/components/candidate_interface/break_placeholder_in_work_history_component.html.erb
  app/components/candidate_interface/course_choices_review_component.html.erb
  app/components/candidate_interface/degrees_review_component.html.erb
  app/components/candidate_interface/degrees_review_component.rb
  app/components/candidate_interface/other_qualifications_review_component.html.erb
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/components/candidate_interface/references_review_component.html.erb
  app/components/candidate_interface/references_review_component.rb
  app/components/candidate_interface/restructured_work_history/review_component.html.erb
  app/components/candidate_interface/volunteering_review_component.html.erb
  app/components/candidate_interface/volunteering_review_component.rb
  app/components/candidate_interface/work_history_review_component.html.erb
  app/components/candidate_interface/work_history_review_component.rb
  app/components/dfe_sign_in_button_component.html.erb
  app/components/filter_component.html.erb
  app/components/provider_interface/application_timeline_component.html.erb
  app/components/provider_interface/application_timeline_component.rb
  app/components/provider_interface/interview_and_course_summary_component.html.erb
  app/components/provider_interface/interview_and_course_summary_component.rb
  app/components/provider_interface/interview_card_component.html.erb
  app/components/provider_interface/interview_card_component.rb
  app/components/summary_list_component.html.erb
  app/components/summary_list_component.rb
  app/components/support_interface/anchor_link_component.html.erb
  app/components/support_interface/anchor_link_component.rb
  app/components/support_interface/reference_with_feedback_component.html.erb
  app/helpers/view_helper.rb
  app/views/candidate_interface/carry_over/start.html.erb
  app/views/candidate_interface/carry_over/start_between_cycles.html.erb
  app/views/candidate_interface/carry_over/start_between_cycles_unsubmitted.html.erb
  app/views/candidate_interface/course_choices/course_selection/full.html.erb
  app/views/candidate_interface/decisions/withdraw.html.erb
  app/views/candidate_interface/find_course_selections/confirm_selection.html.erb
  app/views/candidate_interface/submitted_application_form/start_apply_again.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/check.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/setup_permissions.html.erb
  app/views/provider_interface/start_page/show.html.erb
  app/views/support_interface/application_forms/show.html.erb
  app/views/support_interface/candidates/show.html.erb
  app/views/support_interface/data_exports/new.html.erb
  app/views/support_interface/docs/missing_test_data.html.erb
  app/views/support_interface/provider_users/_provider_user_impersonation.html.erb
  app/views/support_interface/settings/feature_flags.html.erb
  app/views/support_interface/tasks/index.html.erb
  app/views/support_interface/validation_errors/summary.html.erb
  lib/rubocop/cop/govuk/govuk_button_to.rb
  lib/rubocop/cop/govuk/govuk_link_to.rb
  lib/rubocop/cop/govuk/govuk_submit.rb
Labels: Core

#4124 Refactor tile component
  app/components/support_interface/anchor_link_component.html.erb
  app/components/support_interface/anchor_link_component.rb
  app/components/support_interface/tile_component.html.erb
  app/components/support_interface/tile_component.rb
  app/frontend/styles/_card.scss
  app/views/support_interface/performance/service_performance_dashboard.html.erb
  spec/components/previews/support_interface/tile_component_preview.rb
  spec/components/support_interface/tile_component_spec.rb
  spec/components/support_interface/ucas_matches_statistics_component_spec.rb
Labels: Support

#4128 Add hidden fields to clear filter buttons to improve compatibility wi…
  app/components/filter_component.html.erb
  spec/components/filter_component_spec.rb
Labels: ProVendor

#4134 Move component display checks to component class
  app/components/candidate_interface/add_reference_component.html.erb
  app/components/candidate_interface/add_reference_component.rb
  app/components/candidate_interface/deadline_banner_component.html.erb
  app/components/candidate_interface/deadline_banner_component.rb
  app/components/candidate_interface/reopen_banner_component.html.erb
  app/components/candidate_interface/reopen_banner_component.rb
  app/components/support_interface/provider_users_table_component.html.erb
  app/components/support_interface/provider_users_table_component.rb
  spec/components/candidate_interface/reopen_banner_component_spec.rb
Labels: Core

#4133 Add additional column to CandidateEmailSendCountsExport
  app/services/support_interface/candidate_email_send_counts_export.rb
  spec/services/support_interface/candidate_email_send_counts_export_spec.rb
Labels: Support

#4137 Only send email if edit interview actually changes the interview
  app/services/update_interview.rb
  spec/services/update_interview_spec.rb
Labels: ProVendor

#4119 Use EFL qualification description string only in the english_language_qualifications API field
  app/controllers/vendor_api/applications_controller.rb
  app/models/application_form.rb
  app/models/english_proficiency.rb
  app/models/ielts_qualification.rb
  app/models/other_efl_qualification.rb
  app/models/toefl_qualification.rb
  app/presenters/vendor_api/single_application_presenter.rb
  config/vendor-api-v1.yml
  spec/components/efl_qualification_card_component_spec.rb
  spec/factories.rb
  spec/forms/candidate_interface/english_foreign_language/other_efl_qualification_form_spec.rb
  spec/models/last_updated_at_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/services/candidate_interface/choose_efl_review_component_spec.rb
Labels: ProVendor

#4122 Stop setting deprecated fields on application form in factory
  app/controllers/provider_interface/application_data_export_controller.rb
  spec/factories.rb
Labels: Core

#4086 Create new exports for longitudinal permissions analysis
  app/models/data_export.rb
  app/services/support_interface/organisation_permissions_export.rb
  app/services/support_interface/user_permissions_export.rb
  spec/factories.rb
  spec/services/support_interface/organisation_permissions_export_spec.rb
  spec/services/support_interface/user_permissions_export_spec.rb
Labels: ProVendor, Support

#4138 Enable support agents to replace withdrawn application choices
  app/components/support_interface/application_add_course_component.html.erb
  app/components/support_interface/application_summary_component.rb
  app/models/application_form.rb
  spec/components/support_interface/application_add_course_component_spec.rb
Labels: ProVendor

#4116 Add submitted_at to TAD export
  app/exports/tad_export.yml
  app/services/data_api/tad_application_export.rb
  app/services/data_api/tad_export.rb
Labels: Support

#4146 Add new guidance to course search page on Support UI
  app/views/support_interface/application_forms/courses/new_search.html.erb
Labels: Support

#4142 Add a word limit to interview free text fields
  app/forms/provider_interface/cancel_interview_wizard.rb
  app/forms/provider_interface/interview_wizard.rb
  spec/forms/provider_interface/cancel_interview_wizard_spec.rb
  spec/forms/provider_interface/interview_wizard_spec.rb
Labels: ProVendor

#4147 Stub state diagram generation
  spec/system/support_interface/docs_spec.rb
Labels: Core

#4136 Show interviews that happened today in upcoming interviews sections
  app/components/provider_interface/application_choice_interviews_list_component.html.erb
  app/components/provider_interface/application_choice_interviews_list_component.rb
  app/controllers/provider_interface/interview_schedules_controller.rb
  app/controllers/provider_interface/interviews_controller.rb
  app/models/interview.rb
  app/views/provider_interface/interviews/index.html.erb
  spec/components/provider_interface/application_choice_interviews_list_component_spec.rb
  spec/system/provider_interface/provider_can_view_interview_schedule_spec.rb
  spec/system/provider_interface/provider_manages_application_interviews_spec.rb
Labels: ProVendor

#4139 Exclude the application status transition from cancelling an interview
  app/queries/get_activity_log_events.rb
  spec/queries/get_activity_log_events_spec.rb
Labels: ProVendor

#4156 Fix layout of application in Support and Manage
  app/components/efl_qualification_card_component.html.erb
  app/components/qualifications_table_component.html.erb
  app/views/support_interface/application_forms/show.html.erb
Labels: Bug bash 🐞🔨, Provider UI, Support

#4160 Override teacherTrainingApiBaseUrl in staging
  azure/pipelines/release.yml
Labels: DevOps

#4153 Make timeline links unique to address DAC recommendations
  app/components/provider_interface/application_timeline_component.html.erb
  spec/components/provider_interface/application_timeline_component_spec.rb
Labels: ProVendor

#4115 Update locations export
  app/models/data_export.rb
  app/services/support_interface/persona_export.rb
  spec/services/support_interface/persona_export_spec.rb
Labels: Support

#4157 Handle non-integer values for app choice id filter
  app/models/support_interface/applications_filter.rb
  spec/models/support_interface/applications_filter_spec.rb
Labels: Support

#4131 Add hidden fields to change details and cancel interview links
  app/components/provider_interface/interview_and_course_summary_component.html.erb
  spec/components/provider_interface/interview_and_course_summary_component_spec.rb
Labels: ProVendor

#4159 Refactor primary navigation component
  app/components/primary_navigation_component.html.erb
  app/components/primary_navigation_component.rb
  app/frontend/styles/_primary-navigation.scss
  app/views/layouts/_header.html.erb
Labels: CSS, Core

#4168 Provide provisional fee status over the API
  app/presenters/vendor_api/single_application_presenter.rb
  app/views/api_docs/pages/release_notes.md
  config/initializers/nationalities.rb
  config/vendor-api-v1.yml
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: API docs, ProVendor

#4181 Validate presence of candidate date of birth
  app/forms/candidate_interface/personal_details_form.rb
  spec/forms/candidate_interface/personal_details_form_spec.rb
  spec/support/shared_examples/date_of_birth.rb
Labels: Candidate
