Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2021-11, with the labels that each got.

#5968 Update R4R word count regex to match the frontend word count pattern
  app/forms/provider_interface/reasons_for_rejection_wizard.rb
Labels: ProVendor

#5945 Use timeliness to parse interview time
  Gemfile
  Gemfile.lock
  app/forms/provider_interface/interview_wizard.rb
  config/initializers/timeliness.rb
  config/locales/provider_interface/interviews.yml
  spec/components/provider_interface/interview_details_component_spec.rb
  spec/forms/provider_interface/interview_wizard_spec.rb
  spec/system/provider_interface/provider_manages_application_interviews_spec.rb
  spec/system/support_interface/validation_errors_provider_spec.rb
  spec/system/support_interface/validation_errors_provider_summary_spec.rb
  spec/system/wizard_cache_cleared_spec.rb
Labels: ProVendor

#5967 Update content in request a referee journey
  app/views/candidate_interface/references/candidate_name/new.html.erb
  config/locales/candidate_interface/references.yml
  config/locales/en.yml
  spec/system/candidate_interface/references/candidate_requests_a_reference_spec.rb
Labels: Candidate

#5969 Add applications_open_from column to the courses table
  db/migrate/20211101130355_add_applications_open_from_to_course.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#5970 Add applications_open_from to the CourseSync
  app/services/teacher_training_public_api/sync_courses.rb
  spec/factories/course.rb
  spec/services/teacher_training_public_api/sync_courses_spec.rb
Labels: Candidate

#5980 Geocode address after update
  app/models/application_form.rb
  spec/models/application_form_spec.rb
Labels: Candidate, Bug bash 🐞🔨

#5971 Ensure only courses only show on dropdown/radios if they're open for applications
  app/forms/candidate_interface/pick_course_form.rb
  app/forms/candidate_interface/pick_provider_form.rb
  app/models/course.rb
  spec/factories/course.rb
  spec/forms/candidate_interface/pick_course_form_spec.rb
  spec/forms/candidate_interface/pick_provider_form_spec.rb
Labels: Candidate

#5990 Remove duplicated copy from 'Why do you want to teach' review page
  app/views/candidate_interface/personal_statement/show.html.erb
Labels: Candidate

#5989 Radio button doesn't make sense when read with the associated question
  config/locales/provider_interface/decisions.yml
Labels: ProVendor

#5995 Monthly statistics: Include 'withdrawn' and 'offer_withdrawn' in 'unsuccessful' count
  app/models/monthly_statistics/base.rb
  spec/models/monthly_statistics/by_age_group_spec.rb
  spec/models/monthly_statistics/by_area_spec.rb
  spec/models/monthly_statistics/by_course_age_group_spec.rb
  spec/models/monthly_statistics/by_course_type_spec.rb
  spec/models/monthly_statistics/by_primary_specialist_subject_spec.rb
  spec/models/monthly_statistics/by_provider_area_spec.rb
  spec/models/monthly_statistics/by_secondary_subject_spec.rb
  spec/models/monthly_statistics/by_sex_spec.rb
Labels: Metrics & reporting, defect

#5998 Add additional logic to the `by_age_group` query for `withdrawn` and `offer_withdrawn` statuses
  app/models/monthly_statistics/by_age_group.rb
  spec/models/monthly_statistics/by_age_group_spec.rb
Labels: Candidate

#5997 Configure 'UpdateMonthlyStatisticsReport' job to run at the beginning of every month
  config/clock.rb
  spec/workers/update_monthly_statistics_report_spec.rb
Labels: Candidate, Metrics & reporting

#5987 Update content on email: 'feedback_received_for_application_rejected_by_default'
  app/mailers/candidate_mailer.rb
  app/services/reject_by_default_feedback.rb
  app/views/candidate_mailer/feedback_received_for_application_rejected_by_default.text.erb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/reject_by_default_feedback_spec.rb
Labels: Candidate

#6003 Ensure candidates with no region are added to the ExternalReportCandidatesExport
  app/services/support_interface/external_report_candidates_export.rb
  config/initializers/external_report_candidates.rb
  spec/services/support_interface/external_report_candidates_export_spec.rb
Labels: Candidate

#6006 Fix deprecation warnings
  spec/queries/get_course_option_from_codes_spec.rb
  spec/support/capybara.rb
Labels: ProVendor

#6005 Log changes when alerting on site sync changes
  app/services/concerns/full_sync_error_handler.rb
  app/services/teacher_training_public_api/sync_sites.rb
  spec/services/teacher_training_public_api/sync_courses_spec.rb
  spec/services/teacher_training_public_api/sync_sites_spec.rb
  spec/support/test_helpers/teacher_training_public_api_helper.rb
Labels: ProVendor

#5999 [428] Change terraform vars to json
  .github/workflows/deploy.yml
  Makefile
  docs/manual-deployment.md
  terraform/.terraform.lock.hcl
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/research.tfvars
  terraform/workspace_variables/research.tfvars.json
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.tfvars
  terraform/workspace_variables/staging.tfvars.json
Labels: DevOps

#6007 Update `Accepted` and `Conditions met` labels to match prototype
  adr/0015-carrying-over-applications.md
  app/components/provider_interface/status_box_components/recruited_component.rb
  app/models/support_interface/applications_filter.rb
  config/locales/application_states.yml
  spec/components/previews/provider_interface/filter_component_preview.rb
  spec/components/support_interface/application_choice_component_spec.rb
  spec/components/utility/filter_component_spec.rb
  spec/system/provider_interface/provider_edits_condition_statuses_spec.rb
  spec/system/provider_interface/provider_marks_conditions_as_met_spec.rb
  spec/system/provider_interface/provider_reinstates_deferred_offer_spec.rb
  spec/system/provider_interface/provider_user_exports_applications_to_csv_spec.rb
Labels: ProVendor

#6018 Remove feature flags from the db when they are removed from the application
  .github/PULL_REQUEST_TEMPLATE.md
  app/services/data_migrations/remove_obsolete_feature_flags.rb
  app/workers/detect_invariants_daily_check.rb
  lib/tasks/data.rake
  spec/factories/feature.rb
  spec/services/data_migrations/remove_obsolete_feature_flags_spec.rb
  spec/workers/detect_invariants_daily_check_spec.rb
Labels: ProVendor

#6021 [429] Set up docker buildx
  .github/workflows/build.yml
Labels: DevOps

#6027 Remove `courses_open_on_apply` email, spec and preview
  app/mailers/provider_mailer.rb
  config/locales/emails/provider_mailer.yml
  spec/mailers/previews/provider_mailer_preview.rb
  spec/mailers/provider_mailer_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: ProVendor

#6017 Offers back link error when referer path is set
  app/controllers/provider_interface/offers_controller.rb
  config/routes.rb
  spec/requests/provider_interface/offers_controller_spec.rb
Labels: ProVendor

#6028 Add recruitment cycle year and submitted at to the candidates API
  app/controllers/candidate_api/candidates_controller.rb
  config/candidate-api.yml
  spec/requests/candidate_api/get_candidates_spec.rb
Labels: Candidate

#6013 Add candidates and applications by status exports
  app/exports/applications_by_status_export.yml
  app/exports/candidates_by_status_export.yml
  app/exports/common_columns/_common_columns.yml
  app/exports/external_report_candidates_export.yml
  app/helpers/monthly_statistics_export_helper.rb
  app/models/data_export.rb
  app/services/support_interface/monthly_statistics_exports/applications_by_status_export.rb
  app/services/support_interface/monthly_statistics_exports/candidates_by_status_export.rb
  spec/services/support_interface/monthly_statistics_exports/applications_by_status_export_spec.rb
  spec/services/support_interface/monthly_statistics_exports/candidates_by_status_export_spec.rb
Labels: Candidate

#6042 add uuid to sites
  db/migrate/20211112082940_add_uuid_to_sites.rb
  db/schema.rb
  docs/domain-model.png
Labels: Core

#6026 Expose Monthly statistics exports on the report and run once a month
  app/controllers/monthly_statistics_controller.rb
  app/models/data_export.rb
  app/views/monthly_statistics/show.html.erb
  app/views/support_interface/data_exports/view_export_information.html.erb
  app/workers/generate_monthly_statistics.rb
  app/workers/update_monthly_statistics_report.rb
  config/clock.rb
  spec/system/monthly_statistics/monthly_statistics_page_spec.rb
  spec/workers/generate_monthly_statistics_spec.rb
  spec/workers/update_monthly_statistics_report_spec.rb
Labels: Candidate

#6039 Replace provider marketing page
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_masthead.scss
  app/views/provider_interface/start_page/show.html.erb
  public/provider/hero.svg
  public/provider/providers.png
  public/provider/respond.png
  public/provider/team.jpg
  public/provider/view.png
  spec/support/test_helpers/dfe_sign_in_helpers.rb
Labels: ProVendor

#6015 Add error page for exceptions not handled by controllers
  app/lib/rack_exceptions_app.rb
  app/views/errors/forbidden.html.erb
  app/views/errors/internal_server_error.html.erb
  app/views/errors/not_found.html.erb
  app/views/errors/unprocessable_entity.html.erb
  config/application.rb
  config/locales/en.yml
Labels: Core

#6052 Fix the external report exports
  app/services/support_interface/external_report_applications_export.rb
  app/services/support_interface/external_report_candidates_export.rb
  spec/services/support_interface/external_report_applications_export_spec.rb
  spec/services/support_interface/external_report_candidates_export_spec.rb
Labels: Candidate

#6029 Touch application form and choices when course changes
  app/models/course.rb
  spec/rails_helper.rb
  spec/services/teacher_training_public_api/sync_courses_spec.rb
Labels: ProVendor

#6025 [421] Alert when pipeline fails
  .github/workflows/build.yml
  .github/workflows/database-backup.yml
  .github/workflows/deploy.yml
Labels: DevOps

#6047 Use timetable to generate and publish monthly reports
  app/controllers/monthly_statistics_controller.rb
  app/models/data_export.rb
  app/services/monthly_statistics_timetable.rb
  app/views/monthly_statistics/show.html.erb
  app/views/support_interface/data_exports/view_export_information.html.erb
  app/workers/generate_monthly_statistics.rb
  config/clock.rb
  config/locales/monthly_statistics.yml
  spec/models/data_export_spec.rb
  spec/services/monthly_statistics_timetable_spec.rb
  spec/system/monthly_statistics/monthly_statistics_page_spec.rb
  spec/workers/generate_monthly_statistics_spec.rb
Labels: Candidate

#6099 [4232] Add sidekiq metrics to prometheus config
  terraform/modules/paas/main.tf
  terraform/modules/paas/network-policies.tf
Labels: DevOps

#6075 Prevent provider impersonation bugs by restricting sign-in, impersonation across logins
  app/controllers/dfe_sign_in_controller.rb
  app/controllers/provider_interface/sessions_controller.rb
  spec/requests/provider_interface/sessions_controller_spec.rb
Labels: ProVendor

#6115 Fix application export by correctly rendering GCSE constituent grades
  app/components/shared/gcse_qualification_cards_component.rb
  app/decorators/application_choice_export_decorator.rb
  app/decorators/application_qualification_decorator.rb
  spec/decorators/application_qualification_decorator_spec.rb
Labels: ProVendor
