Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2021-12, with the labels that each got.

#6133 Use makefile for terraform
  .github/workflows/deploy.yml
  Makefile
Labels: DevOps

#6130 [4169] - Add missing line break in our rejection emails
  app/views/candidate_mailer/_reasons_for_rejection.text.erb
  app/views/candidate_mailer/_reasons_for_rejection_intro.text.erb
  app/views/candidate_mailer/application_rejected_all_applications_rejected.text.erb
  app/views/candidate_mailer/application_rejected_awaiting_decision_only.text.erb
  app/views/candidate_mailer/application_rejected_offers_only.text.erb
  app/views/candidate_mailer/application_rejected_one_offer_one_awaiting_decision.text.erb
  app/views/candidate_mailer/feedback_received_for_application_rejected_by_default.text.erb
Labels: Candidate, Bug bash 🐞🔨

#6203 Add some guidance about per_page and since when using pagination
  app/views/api_docs/vendor_api_docs/reference/draft.html.erb
  config/vendor_api/v1.1.yml
Labels: ProVendor

#6147 Add support for review apps
  .github/workflows/build.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  Makefile
  db/migrate/20210208105018_clean_up_international_addresses_data.rb
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/review.tfvars.json
  terraform/workspace_variables/review_backend.tfvars
Labels: DevOps, deploy

#6218 Use default GITHUB_TOKEN
  .github/workflows/build.yml
Labels: deploy

#6220 Fix environment check for review apps
  .github/workflows/deploy.yml
Labels: deploy

#6197 Detect out-of-date provider_ids in application_choices
  app/queries/find_application_choices_with_out_of_date_provider_ids.rb
  app/workers/detect_invariants_daily_check.rb
  spec/queries/find_application_choices_with_out_of_date_provider_ids_spec.rb
  spec/workers/detect_invariants_daily_check_spec.rb
Labels: ProVendor

#6214 Add .tool-versions and document asdf
  .gitignore
  .tool-versions
  README.md
Labels: deploy

#6229 Hide empty reasons for rejection in the structured reasons for rejection report in support
  app/components/support_interface/reasons_for_rejection_search_results_component.rb
  spec/components/support_interface/reasons_for_rejection_search_results_component_spec.rb
  spec/system/support_interface/reasons_for_rejection_dashboard_spec.rb
Labels: Support

#6223 Remove account created email
  app/mailers/provider_mailer.rb
  app/services/invite_provider_user.rb
  app/services/provider_interface/add_user_to_provider.rb
  config/locales/emails/provider_mailer.yml
  lib/sandbox_interceptor.rb
  spec/lib/sandbox_interceptor_spec.rb
  spec/mailers/previews/provider_mailer_preview.rb
  spec/mailers/provider_mailer_spec.rb
  spec/services/invite_provider_user_spec.rb
  spec/system/provider_interface/invite_user_spec.rb
  spec/system/support_interface/adding_a_new_provider_user_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: ProVendor

#6228 Add write permission to packages
  .github/workflows/build.yml
Labels: DevOps, deploy

#6170 Implement versioning in the api
  app/components/support_interface/application_choice_component.rb
  app/controllers/concerns/versioning.rb
  app/controllers/vendor_api/applications_controller.rb
  app/controllers/vendor_api/decisions_controller.rb
  app/controllers/vendor_api/vendor_api_controller.rb
  app/lib/allowed_cross_namespace_usage.rb
  app/lib/concerns/versioning_helpers.rb
  app/lib/vendor_api.rb
  app/lib/vendor_api/changes/a_and_as_level_grades.rb
  app/lib/vendor_api/changes/a_and_as_level_subjects.rb
  app/lib/vendor_api/changes/clear_test_data.rb
  app/lib/vendor_api/changes/conditions_not_met.rb
  app/lib/vendor_api/changes/confirm_conditions_met.rb
  app/lib/vendor_api/changes/confirm_enrolment.rb
  app/lib/vendor_api/changes/experimental_clear_test_data.rb
  app/lib/vendor_api/changes/experimental_generate_test_data.rb
  app/lib/vendor_api/changes/gcse_grades.rb
  app/lib/vendor_api/changes/gcse_subjects.rb
  app/lib/vendor_api/changes/generate_test_data.rb
  app/lib/vendor_api/changes/make_an_offer.rb
  app/lib/vendor_api/changes/ping_endpoint.rb
  app/lib/vendor_api/changes/regenerate_test_data.rb
  app/lib/vendor_api/changes/reject_application.rb
  app/lib/vendor_api/changes/retrieve_applications.rb
  app/lib/vendor_api/changes/retrieve_single_application.rb
  app/lib/version_change.rb
  app/presenters/vendor_api/application_presenter.rb
  app/presenters/vendor_api/base.rb
  config/initializers/route_validators.rb
  config/routes.rb
  spec/presenters/vendor_api/application_presenter_spec.rb
  spec/presenters/vendor_api/base_spec.rb
  spec/requests/vendor_api/post_test_data_regenerate_spec.rb
  spec/requests/vendor_api/versioning_spec.rb
  spec/support/test_helpers/api_test_presenter_class.rb
  spec/system/support_interface/view_vendor_api_requests_spec.rb
Labels: ProVendor, API

#6238 Remove links and references to provider complains form
  app/components/utility/phase_banner_component.rb
  app/controllers/provider_interface/content_controller.rb
  app/views/content/provider_complaints.md
  app/views/layouts/_footer_meta_provider.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/provider_interface/provider_content_spec.rb
Labels: ProVendor

#6241 Automate cycle dates in provider emails
  app/mailers/provider_mailer.rb
  config/locales/emails/provider_mailer.yml
Labels: ProVendor

#6242 Redirect to correct path when using the fallback mechanism to login
  app/controllers/provider_interface/sessions_controller.rb
  spec/system/provider_interface/authentication_fallback_spec.rb
Labels: ProVendor

#6237 Implement email to notify users when their user permissions are updated
  app/controllers/provider_interface/user_permissions_controller.rb
  app/mailers/provider_mailer.rb
  app/services/provider_interface/edit_provider_user_permissions.rb
  app/services/save_provider_user.rb
  app/views/provider_mailer/permissions_updated.text.erb
  config/locales/emails/provider_mailer.yml
  spec/mailers/previews/provider_mailer_preview.rb
  spec/mailers/provider_mailer_spec.rb
  spec/services/provider_interface/edit_provider_user_permissions_spec.rb
  spec/services/save_provider_user_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: ProVendor, Support

#6252 Update provider email content and footers - application rejected by default
  app/mailers/provider_mailer.rb
  app/views/layouts/provider_email.text.erb
  app/views/provider_mailer/_notification_preferences.text.erb
  app/views/provider_mailer/application_rejected_by_default.text.erb
  spec/mailers/provider_mailer_spec.rb
Labels: ProVendor

#6253 Update provider email content and footers - application submitted
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/application_submitted.text.erb
  app/views/provider_mailer/application_submitted_with_safeguarding_issues.text.erb
  app/views/provider_mailer/chase_provider_decision.text.erb
  config/locales/emails/provider_mailer.yml
  spec/mailers/provider_mailer_spec.rb
Labels: ProVendor

#6254 Update provider email content and footers - apply service is now open
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/apply_service_is_now_open.text.erb
  config/locales/emails/provider_mailer.yml
  spec/mailers/provider_mailer_spec.rb
Labels: ProVendor

#6256 Update provider email content and footers - chase provider decision
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/chase_provider_decision.text.erb
  config/locales/emails/provider_mailer.yml
  spec/mailers/provider_mailer_spec.rb
  spec/system/reject_by_default_spec.rb
Labels: ProVendor

#6257 Update provider email content and footers - confirm sign in
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/confirm_sign_in.text.erb
  config/locales/emails/provider_mailer.yml
  spec/system/provider_interface/provider_signs_in_from_new_device_spec.rb
Labels: ProVendor

#6258 Update provider email content and footers - declined
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/declined.text.erb
  config/locales/emails/provider_mailer.yml
  spec/mailers/provider_mailer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_declines_offer_spec.rb
Labels: ProVendor

#6259 Update provider email content and footers - declined by default
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/declined_by_default.text.erb
  config/locales/emails/provider_mailer.yml
  spec/mailers/provider_mailer_spec.rb
  spec/system/decline_by_default_spec.rb
Labels: ProVendor

#6261 Update provider email content and footers - offer accepted
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/offer_accepted.text.erb
  config/locales/emails/provider_mailer.yml
  spec/mailers/provider_mailer_spec.rb
  spec/services/accept_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_spec.rb
  spec/system/provider_interface/sandbox_emails_spec.rb
Labels: ProVendor

#6262 Update provider email content and footers - organisation permissions set up
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/organisation_permissions_set_up.text.erb
  config/locales/emails/provider_mailer.yml
  spec/mailers/provider_mailer_spec.rb
Labels: ProVendor

#6265 Update provider email content and footers - permissions removed
  app/mailers/provider_mailer.rb
  spec/mailers/provider_mailer_spec.rb
Labels: ProVendor

#6266 Update provider email content and footers - set up organisation permissions
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/_multiple_provider_relationship_set_up.text.erb
  app/views/provider_mailer/set_up_organisation_permissions.text.erb
  spec/mailers/provider_mailer_spec.rb
Labels: ProVendor

#6268 Update provider email content and footers - permissions updated
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/permissions_updated.text.erb
  spec/mailers/provider_mailer_spec.rb
Labels: ProVendor

#6270 Update fallback_sign_in email
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/fallback_sign_in_email.text.erb
  config/locales/emails/provider_mailer.yml
  spec/mailers/provider_mailer_spec.rb
  spec/system/provider_interface/authentication_fallback_spec.rb
Labels: ProVendor
