Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2021-08, with the labels that each got.

#5257 Display header links on all controller actions
  app/helpers/navigation_items.rb
Labels: ProVendor, Provider UI

#5268 Display breakdown of user’s relationship permission based on provider…
  app/components/provider_interface/provider_partner_permission_breakdown_component.html.erb
  app/components/provider_interface/provider_partner_permission_breakdown_component.rb
  spec/components/previews/provider_interface/provider_partner_permission_breakdown_component_preview.rb
  spec/components/provider_interface/provider_partner_permission_breakdown_component_spec.rb
Labels: ProVendor, Provider UI

#5252 Create new bulk email - new cycle has started
  app/mailers/candidate_mailer.rb
  app/models/chaser_sent.rb
  app/queries/get_unsuccessful_and_unsubmitted_applications_from_previous_cycle.rb
  app/services/cycle_timetable.rb
  app/services/send_new_cycle_has_started_email_to_candidate.rb
  app/views/candidate_mailer/new_cycle_has_started.erb
  app/workers/send_new_cycle_has_started_email_to_candidates_worker.rb
  config/clock.rb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/queries/get_unsuccessful_and_unsubmitted_applications_from_previous_cycle_spec.rb
  spec/services/cycle_timetable_spec.rb
  spec/system/support_interface/docs_spec.rb
  spec/workers/send_new_cycle_has_started_email_to_candidates_worker_spec.rb
Labels: Candidate, End of cycle

#5282 Fix linter errors
  spec/services/cycle_timetable_spec.rb
Labels: Bug bash 🐞🔨

#5273 Fix redirects when updating personal details
  app/components/candidate_interface/contact_details_review_component.rb
  app/components/candidate_interface/personal_details_review_component.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/candidate_interface/contact_details/address_type_controller.rb
  app/controllers/candidate_interface/contact_details/phone_number_controller.rb
  app/controllers/candidate_interface/personal_details/languages_controller.rb
  app/controllers/candidate_interface/personal_details/name_and_dob_controller.rb
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/controllers/candidate_interface/personal_details/right_to_work_or_study_controller.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/contact_details/address/edit.html.erb
  app/views/candidate_interface/contact_details/address_type/edit.html.erb
  app/views/candidate_interface/contact_details/phone_number/edit.html.erb
  app/views/candidate_interface/personal_details/languages/edit.html.erb
  app/views/candidate_interface/personal_details/name_and_dob/edit.html.erb
  app/views/candidate_interface/personal_details/nationalities/edit.html.erb
  app/views/candidate_interface/personal_details/right_to_work_or_study/edit.html.erb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_details_section_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#5284 Remove sign up being blocked between cycles
  app/controllers/candidate_interface/sign_up_controller.rb
  app/controllers/candidate_interface/start_page_controller.rb
  app/views/candidate_interface/start_page/applications_closed.html.erb
  config/locales/en.yml
  spec/system/candidate_interface/signup_and_signin/candidate_without_account_arrives_between_cycles_spec.rb
Labels: Candidate

#5315 Fix redirects when updating personal statement and subject knowledge
  app/components/candidate_interface/becoming_a_teacher_review_component.rb
  app/components/candidate_interface/subject_knowledge_review_component.rb
  app/controllers/candidate_interface/personal_statement_controller.rb
  app/controllers/candidate_interface/subject_knowledge_controller.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/personal_statement/edit.html.erb
  app/views/candidate_interface/subject_knowledge/edit.html.erb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_statement_section_spec.rb
Labels: Candidate, Bug bash 🐞🔨

#5321 Fix redirects when updating the 'adjustments' section
  app/components/candidate_interface/interview_preferences_review_component.rb
  app/components/candidate_interface/training_with_a_disability_review_component.rb
  app/controllers/candidate_interface/interview_needs_controller.rb
  app/controllers/candidate_interface/training_with_a_disability_controller.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/interview_needs/edit.html.erb
  app/views/candidate_interface/training_with_a_disability/edit.html.erb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_adjustments_section_spec.rb
Labels: Candidate, Bug bash 🐞🔨

#5313 Fix redirects when updating qualifications
  app/components/candidate_interface/degrees_review_component.rb
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/candidate_interface/contact_details/address_type_controller.rb
  app/controllers/candidate_interface/contact_details/phone_number_controller.rb
  app/controllers/candidate_interface/degrees/completion_status_controller.rb
  app/controllers/candidate_interface/degrees/enic_controller.rb
  app/controllers/candidate_interface/degrees/grade_controller.rb
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/controllers/candidate_interface/degrees/start_year_controller.rb
  app/controllers/candidate_interface/degrees/subject_controller.rb
  app/controllers/candidate_interface/degrees/type_controller.rb
  app/controllers/candidate_interface/degrees/year_controller.rb
  app/controllers/candidate_interface/gcse/english/grade_controller.rb
  app/controllers/candidate_interface/gcse/enic_controller.rb
  app/controllers/candidate_interface/gcse/institution_country_controller.rb
  app/controllers/candidate_interface/gcse/maths/grade_controller.rb
  app/controllers/candidate_interface/gcse/science/grade_controller.rb
  app/controllers/candidate_interface/gcse/type_controller.rb
  app/controllers/candidate_interface/gcse/year_controller.rb
  app/controllers/candidate_interface/other_qualifications/details_controller.rb
  app/controllers/candidate_interface/other_qualifications/type_controller.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/degrees/completion_status/edit.html.erb
  app/views/candidate_interface/degrees/enic/edit.html.erb
  app/views/candidate_interface/degrees/grade/edit.html.erb
  app/views/candidate_interface/degrees/institution/edit.html.erb
  app/views/candidate_interface/degrees/start_year/edit.html.erb
  app/views/candidate_interface/degrees/subject/edit.html.erb
  app/views/candidate_interface/degrees/type/edit.html.erb
  app/views/candidate_interface/gcse/english/grade/edit.html.erb
  app/views/candidate_interface/gcse/enic/edit.html.erb
  app/views/candidate_interface/gcse/institution_country/edit.html.erb
  app/views/candidate_interface/gcse/maths/grade/edit.html.erb
  app/views/candidate_interface/gcse/science/grade/edit.html.erb
  app/views/candidate_interface/gcse/type/edit.html.erb
  app/views/candidate_interface/gcse/year/edit.html.erb
  app/views/candidate_interface/other_qualifications/details/edit.html.erb
  app/views/candidate_interface/other_qualifications/type/edit.html.erb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_adjustments_section_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_details_section_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_statement_section_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_qualifications_spec.rb
Labels: Candidate, Bug bash 🐞🔨

#5333 Introduce new Report table component
  app/components/provider_interface/report_table_component.html.erb
  app/components/provider_interface/report_table_component.rb
  spec/components/previews/provider_interface/report_table_component_preview.rb
  spec/components/provider_interface/report_table_component_spec.rb
Labels: ProVendor

#5320 Add new controller or provider reports and expose path to reports
  app/components/provider_interface/reports_controller.rb
  app/helpers/navigation_items.rb
  app/views/provider_interface/application_data_export/new.html.erb
  app/views/provider_interface/hesa_export/new.html.erb
  app/views/provider_interface/reports/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/system/provider_interface/provider_reports_page_spec.rb
Labels: ProVendor

#5324 Amendments to export data report page
  app/views/provider_interface/application_data_export/new.html.erb
  spec/system/provider_interface/provider_reports_page_spec.rb
  spec/system/provider_interface/provider_user_exports_applications_to_csv_spec.rb
Labels: ProVendor

#5347 Rename existing apply-redis instance to apply-worker-redis
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/loadtest.tfvars
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/research.tfvars
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/staging.tfvars
Labels: DevOps

#5335 Fix redirects when updating the 'safeguarding' section
  app/components/candidate_interface/safeguarding_review_component.rb
  app/controllers/candidate_interface/safeguarding_controller.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/safeguarding/edit.html.erb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_safeguarding_section_spec.rb
Labels: Candidate, Bug bash 🐞🔨

#5325 Amendments to HESA report page
  app/views/provider_interface/hesa_export/new.html.erb
  config/locales/en.yml
  spec/system/provider_interface/export_applications_in_hesa_format_spec.rb
Labels: ProVendor

#5351 Config redis cache instance for rails cache_store
  Dockerfile
  config/environments/production.rb
  docker-compose.yml
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/loadtest.tfvars
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/research.tfvars
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/staging.tfvars
Labels: DevOps

#5346 Fragment cache the provider select box
  app/controllers/candidate_interface/course_choices/provider_selection_controller.rb
  app/views/candidate_interface/course_choices/provider_selection/new.html.erb
  spec/spec_helper.rb
Labels: Performance

#5373 Drop word count validation to 100 for other_advice_or_feedback_details field
  app/forms/provider_interface/reasons_for_rejection_wizard.rb
  config/locales/provider_interface/reasons_for_rejection.yml
Labels: ProVendor

#5367 Reintroduce rack-mini-profiler
  Gemfile
  Gemfile.lock
  config/initializers/rack_profiler.rb
Labels: Performance

#5326 Add caching to unsubmitted application form page
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/views/candidate_interface/unsubmitted_application_form/_task_list.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  config/application.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_breaks_spec.rb
  spec/system/register_api/register_receives_application_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: Performance

#5395 Use colons when displaying time of day
  config/locales/en.yml
Labels: Candidate, Bug bash 🐞🔨

#5399 Exclude candidates who have been excluded from performance data from the performance dashboard
  app/models/performance_statistics.rb
  spec/models/performance_statistics_spec.rb
Labels: Candidate

#5301 Cache return value of `VendorAPI::SingleApplicationPresenter#as_json`
  app/presenters/vendor_api/single_application_presenter.rb
  spec/requests/vendor_api/post_make_an_offer_spec.rb
Labels: Performance

#5393 Indicate for support if an application was submitted over 5 days ago
  app/components/support_interface/application_summary_component.rb
  spec/components/support_interface/application_summary_component_spec.rb
Labels: Candidate, Support

#5354 Fix redirects when updating the work experience section
  app/components/shared/restructured_work_history/gap_component.html.erb
  app/components/shared/restructured_work_history/gap_component.rb
  app/components/shared/restructured_work_history/job_component.html.erb
  app/components/shared/restructured_work_history/job_component.rb
  app/components/shared/restructured_work_history/review_component.html.erb
  app/components/shared/restructured_work_history/review_component.rb
  app/components/shared/restructured_work_history/work_break_component.html.erb
  app/components/shared/restructured_work_history/work_break_component.rb
  app/controllers/candidate_interface/restructured_work_history/break_controller.rb
  app/controllers/candidate_interface/restructured_work_history/job_controller.rb
  app/controllers/candidate_interface/restructured_work_history/review_controller.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/restructured_work_history/break/confirm_destroy.html.erb
  app/views/candidate_interface/restructured_work_history/break/edit.html.erb
  app/views/candidate_interface/restructured_work_history/break/new.html.erb
  app/views/candidate_interface/restructured_work_history/job/confirm_destroy.html.erb
  app/views/candidate_interface/restructured_work_history/job/edit.html.erb
  app/views/candidate_interface/restructured_work_history/job/new.html.erb
  app/views/candidate_interface/restructured_work_history/review/show.html.erb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_work_experience_section_spec.rb
Labels: Candidate, Bug bash 🐞🔨

#5397 Update 'Find closes' calendar event in CycleTimetable
  app/services/cycle_timetable.rb
  app/services/set_reject_by_default.rb
  spec/services/set_reject_by_default_spec.rb
Labels: Core

#5409 Update course full feedback
  app/components/shared/reasons_for_rejection_component.html.erb
  config/locales/provider_interface/reasons_for_rejection.yml
  spec/presenters/rejected_application_choice_presenter_spec.rb
Labels: ProVendor

#5418 Add new columns for GCSEs, degrees and visa requirements
  db/migrate/20210820132740_add_structured_degree_columns_to_the_courses_table.rb
  db/migrate/20210820133151_add_structured_gsce_columns_to_the_courses_table.rb
  db/migrate/20210820133333_add_visa_columns_to_providers_table.rb
  db/schema.rb
  docs/domain-model.png
Labels: Core

#5375 Pre-fill application if you arrive from Find with course params and are a Sandbox candidate user
  app/controllers/candidate_interface/after_sign_in_controller.rb
  app/controllers/candidate_interface/prefill_application_form_controller.rb
  app/lib/prefill_application_state_store/rails_cache.rb
  spec/lib/prefill_application_state_store/rails_cache_spec.rb
  spec/system/candidate_interface/course_selection/sandbox_user_apply_from_find_spec.rb
Labels: Candidate, Bug bash 🐞🔨

#5417 Update `reject_by_default` date and add to CycleTimetable
  app/services/cycle_timetable.rb
  app/services/set_reject_by_default.rb
  spec/services/set_reject_by_default_spec.rb
Labels: Core

#5431 Update Duplicate Candidate query and table component
  app/components/support_interface/duplicate_candidate_matches_table_component.html.erb
  app/queries/get_duplicate_candidate_matches.rb
  spec/components/support_interface/duplicate_candidate_matches_table_component_spec.rb
  spec/queries/get_duplicate_candidate_matches_spec.rb
Labels: Support

#5461 Invite Provider User - Permissions
  app/components/provider_interface/provider_user_permissions_form_component.html.erb
  app/components/provider_interface/provider_user_permissions_form_component.rb
  app/components/provider_interface/user_personal_details_component.rb
  app/controllers/provider_interface/user_invitation/base_controller.rb
  app/controllers/provider_interface/user_invitation/permissions_controller.rb
  app/controllers/provider_interface/user_invitation/personal_details_controller.rb
  app/controllers/provider_interface/user_invitation/review_controller.rb
  app/forms/provider_interface/invite_user_wizard.rb
  app/services/provider_interface/add_user_to_provider.rb
  app/views/provider_interface/personal_details/show.html.erb
  app/views/provider_interface/user_invitation/permissions/new.html.erb
  app/views/provider_interface/user_invitation/personal_details/new.html.erb
  app/views/provider_interface/user_invitation/review/check.html.erb
  app/views/provider_interface/user_permissions/edit.html.erb
  app/views/provider_interface/users/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/provider_interface/provider_user_permissions_form_component_spec.rb
  spec/components/provider_interface/user_personal_details_component_spec.rb
  spec/requests/provider_interface/user_invitation/review_controller_spec.rb
  spec/services/provider_interface/add_user_to_provider_spec.rb
  spec/system/provider_interface/invite_user_spec.rb
Labels: ProVendor
