Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2021-03, with the labels that each got.

#4182 Add missing spec for support form `EditApplicantDetailsForm`
  app/forms/support_interface/application_forms/edit_applicant_details_form.rb
  spec/forms/candidate_interface/personal_details_form_spec.rb
  spec/forms/support_interface/application_forms/edit_applicant_details_form_spec.rb
  spec/support/shared_examples/date_of_birth.rb
Labels: Core

#4188 Add feature flag for new make offer flow
  app/services/feature_flag.rb
Labels: ProVendor

#4189 Reorder validations, error is displayed in wrong position
  app/forms/candidate_interface/volunteering_role_form.rb
Labels: Candidate

#4169 Refactor provider user permissions forms
  app/components/provider_interface/edit_provider_user_permissions_component.rb
  app/controllers/provider_interface/provider_users_controller.rb
  app/controllers/provider_interface/provider_users_invitations_controller.rb
  app/forms/provider_interface/fields_for_provider_user_permissions_form.rb
  app/forms/provider_interface/provider_user_edit_permissions_form.rb
  app/forms/provider_interface/provider_user_invitation_wizard.rb
  app/forms/provider_interface/provider_user_permissions_form.rb
  app/views/provider_interface/_fields_for_permissions.html.erb
  app/views/provider_interface/provider_users/edit_permissions.html.erb
  app/views/provider_interface/provider_users_invitations/edit_permissions.html.erb
  spec/components/previews/provider_interface/edit_provider_user_permissions_component_preview.rb
  spec/forms/provider_interface/fields_for_provider_user_permissions_form_spec.rb
  spec/forms/provider_interface/provider_user_edit_permissions_form_spec.rb
  spec/forms/provider_interface/provider_user_invitation_wizard_spec.rb
  spec/forms/provider_interface/provider_user_permissions_form_spec.rb
Labels: ProVendor

#4186 Delete redundant ViewComponent code
  app/components/candidate_interface/application_complete_content_component.rb
  app/components/candidate_interface/application_status_tag_component.rb
  app/components/candidate_interface/apply_again_banner_component.rb
  app/components/candidate_interface/becoming_a_teacher_review_component.rb
  app/components/candidate_interface/carry_over_banner_component.rb
  app/components/candidate_interface/complete_section_component.rb
  app/components/candidate_interface/contact_details_review_component.rb
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/course_option_review_component.rb
  app/components/candidate_interface/degrees_review_component.rb
  app/components/candidate_interface/grouped_provider_courses_component.rb
  app/components/candidate_interface/incomplete_section_component.rb
  app/components/candidate_interface/interview_preferences_review_component.rb
  app/components/candidate_interface/links_to_previous_applications_component.rb
  app/components/candidate_interface/offer_conditions_review_component.rb
  app/components/candidate_interface/offer_review_component.html.erb
  app/components/candidate_interface/offer_review_component.rb
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/components/candidate_interface/personal_details_review_component.rb
  app/components/candidate_interface/rejection_reasons_component.rb
  app/components/candidate_interface/restructured_work_history/review_component.rb
  app/components/candidate_interface/subject_knowledge_review_component.rb
  app/components/candidate_interface/training_with_a_disability_review_component.rb
  app/components/candidate_interface/unsubmitted_reference_review_component.html.erb
  app/components/candidate_interface/unsubmitted_reference_review_component.rb
  app/components/candidate_interface/volunteering_review_component.rb
  app/components/candidate_interface/work_history_review_component.rb
  app/components/language_skills_component.rb
  app/components/personal_statement_component.rb
  app/components/provider_interface/application_status_tag_component.rb
  app/components/provider_interface/application_timeline_component.rb
  app/components/provider_interface/feedback_preview_component.html.erb
  app/components/provider_interface/feedback_preview_component.rb
  app/components/provider_interface/interview_details_component.html.erb
  app/components/provider_interface/interview_details_component.rb
  app/components/provider_interface/provider_user_invitation_details_component.html.erb
  app/components/provider_interface/provider_user_invitation_details_component.rb
  app/components/provider_interface/reference_with_feedback_component.rb
  app/components/qualification_row_component.rb
  app/components/summary_card_component.rb
  app/components/summary_list_component.rb
  app/components/support_interface/audit_trail_change_component.rb
  app/components/support_interface/audit_trail_component.rb
  app/components/support_interface/audit_trail_item_component.rb
  app/components/support_interface/course_details_component.html.erb
  app/components/support_interface/course_details_component.rb
  app/components/support_interface/course_option_details_component.html.erb
  app/components/support_interface/course_option_details_component.rb
  app/components/support_interface/feature_audit_trail_component.rb
  app/components/support_interface/reference_with_feedback_component.rb
  app/components/support_interface/vendor_api_request_details_component.html.erb
  app/components/support_interface/vendor_api_request_details_component.rb
  app/components/task_list_item_component.rb
  app/components/volunteering_history_component.rb
  app/components/work_history_component.rb
  app/components/work_history_item_component.rb
Labels: Core

#4095 Add ERB Lint to CI workflow
  Makefile
  azure/pipelines/build.yml
  lib/tasks/testing.rake
Labels: Core

#4193 Resolve erblint errors
  .rubocop.yml
  app/components/provider_interface/interview_and_course_summary_component.html.erb
  app/views/support_interface/performance/feature_metrics_dashboard.html.erb
  spec/mailers/previews/rails/mailers/email.html.erb
Labels: Core

#4199 Add missing work history break start_date validation
  app/forms/candidate_interface/work_history_break_form.rb
  spec/forms/candidate_interface/work_history_break_form_spec.rb
Labels: Candidate

#4202 Fix flaky spec
  spec/components/support_interface/application_add_course_component_spec.rb
Labels: Core

#4201 Hide sensitive HESA codes in support audit trail
  app/components/support_interface/audit_trail_change_component.rb
  spec/components/support_interface/audit_trail_change_component_spec.rb
Labels: Support

#4200 Split First and Last name on application form view in Manage and Support
  app/components/provider_interface/personal_details_component.rb
  app/components/support_interface/personal_details_component.rb
  spec/components/provider_interface/personal_details_component_spec.rb
  spec/components/support_interface/personal_details_component_spec.rb
  spec/system/support_interface/editing_address_details_spec.rb
  spec/system/support_interface/editing_applicant_details_spec.rb
  spec/system/support_interface/editing_reference_spec.rb
Labels: ProVendor, Support

#4194 Remove unused code
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/gcse/base_controller.rb
  app/controllers/candidate_interface/other_qualifications/type_controller.rb
  app/controllers/provider_interface/conditions_controller.rb
  app/controllers/provider_interface/sessions_controller.rb
  app/controllers/support_interface/application_forms/courses_controller.rb
  app/helpers/gcse_qualification_helper.rb
  app/models/application_choice.rb
  app/models/application_form.rb
  app/models/application_reference.rb
  app/models/course.rb
  app/models/course_option.rb
  app/models/provider.rb
  spec/models/application_form_spec.rb
  spec/models/course_option_spec.rb
Labels: Core

#4179 Update mail copy for apply again invitation
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/_interested_with_rejections.text.erb
  app/views/candidate_mailer/_interested_without_rejections.text.erb
  app/views/candidate_mailer/_still_interested_content.text.erb
  app/views/candidate_mailer/_still_interested_in_teaching.text.erb
  app/views/candidate_mailer/application_rejected_all_applications_rejected.text.erb
  app/views/candidate_mailer/decline_last_application_choice.text.erb
  app/views/candidate_mailer/declined_by_default_with_rejections.text.erb
  app/views/candidate_mailer/declined_by_default_without_rejections.text.erb
  app/views/candidate_mailer/withdraw_last_application_choice.text.erb
  spec/system/decline_by_default_spec.rb
Labels: Candidate

#4106 Add code review guidelines
  docs/code-review-guidelines.md
Labels: Core

#4210 Support: Increase container width
  app/frontend/styles/support/_all.scss
  app/frontend/styles/support/_template.scss
  app/views/layouts/support_layout.html.erb
Labels: Support

#4207 Add shared examples for month year validations
  app/components/candidate_interface/volunteering_review_component.rb
  app/forms/candidate_interface/restructured_work_history/job_form.rb
  app/forms/candidate_interface/restructured_work_history/work_history_break_form.rb
  app/forms/candidate_interface/volunteering_role_form.rb
  app/forms/candidate_interface/work_experience_form.rb
  app/forms/candidate_interface/work_history_break_form.rb
  app/helpers/date_validation_helper.rb
  app/validators/date_validator.rb
  config/locales/candidate_interface/restructured_work_history.yml
  config/locales/candidate_interface/volunteering.yml
  config/locales/en.yml
  spec/forms/candidate_interface/restructured_work_history/job_form_spec.rb
  spec/forms/candidate_interface/restructured_work_history/work_history_break_form_spec.rb
  spec/forms/candidate_interface/volunteering_role_form_spec.rb
  spec/forms/candidate_interface/work_experience_form_spec.rb
  spec/forms/candidate_interface/work_history_break_form_spec.rb
  spec/helpers/date_validation_helper_spec.rb
  spec/support/candidate_interface/shared_examples/end_date_validation.rb
  spec/support/candidate_interface/shared_examples/start_date_validation.rb
  spec/support/shared_examples/month_and_year_date_validations.rb
  spec/validators/date_validator_spec.rb
Labels: Core

#4190 Update work history break export
  app/models/data_export.rb
  app/services/support_interface/unexplained_breaks_in_work_history_export.rb
  app/services/support_interface/work_history_break_export.rb
  spec/services/support_interface/unexplained_breaks_in_work_history_export_spec.rb
  spec/services/support_interface/work_history_break_export_spec.rb
Labels: Support

#4214 Remove interview info from dashboard when cancelled
  app/components/candidate_interface/course_choices_review_component.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
  spec/factories.rb
Labels: Candidate

#4208 Add shared examples for year validations
  spec/forms/candidate_interface/degree_year_form_spec.rb
  spec/forms/candidate_interface/other_qualification_details_form_spec.rb
  spec/support/shared_examples/year_validations.rb
  spec/validators/year_validator_spec.rb
Labels: Core

#4230 Smol support bugs
  app/views/support_interface/providers/no_relationships.html.erb
  app/views/support_interface/sessions/confirm_environment.html.erb
  spec/system/support_interface/feature_flags_spec.rb
Labels: Support

#4158 Support: Show useful links relating to an application
  app/components/support_interface/application_navigation_component.html.erb
  app/components/support_interface/application_navigation_component.rb
  app/views/support_interface/application_forms/_application_navigation.html.erb
  app/views/support_interface/application_forms/audit.html.erb
  app/views/support_interface/application_forms/show.html.erb
  spec/components/support_interface/application_navigation_component_spec.rb
Labels: Support

#4231 Add reusable component for selecting provider
  app/components/provider_interface/select_provider_component.html.erb
  app/components/provider_interface/select_provider_component.rb
  spec/components/previews/provider_interface/select_provider_component_preview.rb
  spec/components/provider_interface/select_provider_component_spec.rb
Labels: ProVendor

#4240 Add duplicate boolean to the ApplicationReference table
  db/migrate/20210308172728_add_duplicate_boolean_to_references.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#4252 Disable batch build
  azure/pipelines/build.yml
Labels: DevOps

#4238 Create export for autosuggest usage
  app/models/data_export.rb
  app/services/support_interface/candidate_autofill_usage_export.rb
  spec/services/support_interface/candidate_autofill_usage_export_spec.rb
Labels: Candidate, Support

#4236 Remove V3 API (1/4) — Apply from Find uses public API
  app/models/teacher_training_public_api/course.rb
  app/models/teacher_training_public_api/location.rb
  app/models/teacher_training_public_api/recruitment_cycle.rb
  app/services/candidate_interface/apply_from_find_page.rb
  app/services/teacher_training_public_api/sync_all_providers_and_courses.rb
  spec/examples/teacher_training_api/course_single_response.json
  spec/services/candidate_interface/apply_from_find_page_spec.rb
  spec/support/test_helpers/teacher_training_public_api_helper.rb
  spec/system/candidate_interface/course_selection/candidate_apply_from_find_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
Labels: Core

#4237 Work history nil check fix
  app/services/support_interface/work_history_break_export.rb
  spec/services/support_interface/work_history_break_export_spec.rb
Labels: Support

#4217 Add new permissions based query service for courses and providers
  Gemfile
  Gemfile.lock
  app/queries/get_change_offer_options.rb
  spec/queries/get_change_offer_options_spec.rb
Labels: ProVendor

#4257 Qualifications export: Don't load all application choices in memory at once
  app/services/support_interface/qualifications_export.rb
Labels: Bug bash 🐞🔨, Candidate

#4262 Create provider_user_notifications table
  db/migrate/20210303223028_create_provider_user_notifications.rb
  db/schema.rb
  docs/domain-model.png
Labels: ProVendor

#4258 Corrections to autosuggest data export
  app/services/support_interface/candidate_autofill_usage_export.rb
  spec/services/support_interface/candidate_autofill_usage_export_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#4222 Remove duplicate references from the referee survey export and cleanse data
  app/models/application_reference.rb
  app/models/candidate.rb
  app/models/reference_feature_metrics.rb
  app/services/candidate_interface/backfill_duplicate_boolean_and_populate_feedback_provided_at.rb
  app/services/duplicate_application.rb
  app/services/support_interface/referee_survey_export.rb
  db/migrate/20210304112335_cleanse_feedback_provided_at_data.rb
  spec/factories.rb
  spec/models/reference_feature_metrics_spec.rb
  spec/services/candidate_interface/backfill_duplicate_boolean_and_populate_feedback_provided_at_spec.rb
  spec/services/duplicate_application_shared_examples.rb
  spec/services/support_interface/referee_survey_export_spec.rb
Labels: Candidate

#4272 Qualifications export - remove N+1 queries
  app/services/support_interface/qualifications_export.rb
Labels: Candidate

#4255 Remove V3 API (2/4) — sync subjects from public API, remove refs to V3
  README.md
  app/controllers/support_interface/course_controller.rb
  app/controllers/support_interface/tasks_controller.rb
  app/services/feature_flag.rb
  app/services/teacher_training_public_api/sync_courses.rb
  app/views/support_interface/course/vacancies.html.erb
  app/views/support_interface/tasks/index.html.erb
  config/clock.rb
  config/initializers/okcomputer.rb
  config/initializers/raven.rb
  lib/tasks/local_dev.rake
  spec/examples/teacher_training_api/course_list_response.json
  spec/services/teacher_training_public_api/sync_courses_spec.rb
  spec/system/candidate_interface/course_selection/candidate_view_available_courses_spec.rb
  spec/system/find_sync/syncing_providers_spec.rb
  spec/system/support_interface/provider_sync_courses_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
Labels: Core

#4267 Hide interview link in activity log if it has been cancelled
  app/components/provider_interface/activity_log_event_component.html.erb
  app/components/provider_interface/activity_log_event_component.rb
  spec/components/provider_interface/activity_log_event_component_spec.rb
  spec/factories.rb
Labels: ProVendor

#4223 Add interview changes export
  app/exports/interview_changes_export.yml
  app/models/data_export.rb
  app/services/support_interface/interview_changes_export.rb
  spec/factories.rb
  spec/services/support_interface/interview_changes_export_spec.rb
Labels: Support

#4228 Set up models and services for granular provider notification settings
  app/controllers/provider_interface/notifications_controller.rb
  app/controllers/support_interface/provider_users_controller.rb
  app/models/provider_user.rb
  app/models/provider_user_notification_preferences.rb
  app/services/accept_offer.rb
  app/services/accept_unconditional_offer.rb
  app/services/decline_offer.rb
  app/services/decline_offer_by_default.rb
  app/services/feature_flag.rb
  app/services/notifications_list.rb
  app/services/send_chase_email_to_provider.rb
  app/services/send_new_application_email_to_provider.rb
  app/services/send_reject_by_default_email_to_provider.rb
  app/services/withdraw_application.rb
  config/brakeman.ignore
  spec/factories.rb
  spec/models/provider_user_notification_preferences_spec.rb
  spec/services/accept_offer_spec.rb
  spec/services/decline_offer_by_default_spec.rb
  spec/services/decline_offer_spec.rb
  spec/services/notifications_list_spec.rb
  spec/services/send_chase_email_to_provider_spec.rb
  spec/services/send_new_application_email_to_provider_spec.rb
  spec/services/send_reject_by_default_email_to_provider_spec.rb
  spec/services/withdraw_application_spec.rb
  spec/system/reject_by_default_spec.rb
Labels: ProVendor

#4280 Humanize compared attribute
  app/validators/date_validator.rb
  spec/support/shared_examples/month_and_year_date_validations.rb
  spec/validators/date_validator_spec.rb
Labels: Candidate

#4061 Adds `data:migrate` task
  app/models/data_migration.rb
  app/services/data_migration_runner.rb
  db/migrate/20210213002839_create_data_migrations.rb
  db/schema.rb
  docs/data-migrations.md
  lib/generators/data_migration_generator.rb
  lib/generators/templates/data_migration.rb.tt
  lib/generators/templates/data_migration_spec.rb.tt
  lib/tasks/data.rake
  spec/models/data_migration_spec.rb
  spec/services/data_migration_runner_spec.rb
Labels: Core

#4268 Display valid date in interview date hint
  app/components/provider_interface/interview_form_component.html.erb
  app/components/provider_interface/interview_form_component.rb
  app/forms/provider_interface/interview_wizard.rb
  app/models/application_choice.rb
  app/views/provider_interface/interviews/_form.html.erb
  app/views/provider_interface/interviews/edit.html.erb
  app/views/provider_interface/interviews/new.html.erb
  config/locales/interview.yml
  spec/components/previews/provider_interface/interview_form_component_preview.rb
  spec/components/provider_interface/interview_form_component_spec.rb
  spec/forms/provider_interface/interview_wizard_spec.rb
  spec/models/application_choice_spec.rb
Labels: ProVendor

#4291 Add new option in "Things to check" section in the Github PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Core

#4277 UK NARIC name change to UK ENIC
  app/components/candidate_interface/degrees_review_component.rb
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/components/degree_qualification_cards_component.html.erb
  app/components/degree_qualification_cards_component.rb
  app/components/gcse_qualification_cards_component.html.erb
  app/components/gcse_qualification_cards_component.rb
  app/controllers/candidate_interface/degrees/enic_controller.rb
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/controllers/candidate_interface/degrees/naric_controller.rb
  app/controllers/candidate_interface/gcse/enic_controller.rb
  app/controllers/candidate_interface/gcse/institution_country_controller.rb
  app/controllers/candidate_interface/gcse/naric_controller.rb
  app/forms/candidate_interface/degree_enic_form.rb
  app/forms/candidate_interface/gcse_enic_form.rb
  app/models/application_qualification.rb
  app/views/candidate_interface/degrees/enic/_form_fields.html.erb
  app/views/candidate_interface/degrees/enic/edit.html.erb
  app/views/candidate_interface/degrees/enic/new.html.erb
  app/views/candidate_interface/degrees/naric/_form_fields.html.erb
  app/views/candidate_interface/gcse/enic/edit.html.erb
  config/locales/candidate_interface/degree.yml
  config/locales/candidate_interface/gcse.yml
  config/locales/candidate_interface/gcse_details.yml
  config/locales/en.yml
  config/routes.rb
  config/vendor-api-v1.yml
  spec/components/candidate_interface/degrees_review_component_spec.rb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/components/degree_qualification_cards_component_spec.rb
  spec/components/gcse_qualification_cards_component_spec.rb
  spec/factories.rb
  spec/forms/candidate_interface/degree_enic_form_spec.rb
  spec/forms/candidate_interface/gcse_enic_form_spec.rb
  spec/forms/candidate_interface/gcse_naric_form_spec.rb
  spec/models/application_qualification_spec.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_international_gcse_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_international_degrees_spec.rb
Labels: Core

#4296 Distinguish changes that were made by support in application timeline
  app/components/provider_interface/application_timeline_component.rb
  spec/components/provider_interface/application_timeline_component_spec.rb
Labels: ProVendor

#4300 Remove BackfillEnicReference data migration task
  app/services/data_migrations/backfill_enic_reference_data.rb
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_enic_reference_data_spec.rb
Labels: Core

#4301 Interview csv fixes
  app/components/provider_interface/application_timeline_component.rb
  app/helpers/audit_helper.rb
  app/services/support_interface/interview_changes_export.rb
  spec/helpers/audit_helper_spec.rb
  spec/services/support_interface/interview_changes_export_spec.rb
Labels: Support

#4306 Remove 'naric_reference' column from 'application_qualifications' table
  app/forms/candidate_interface/degree_naric_form.rb
  app/forms/candidate_interface/gcse_naric_form.rb
  db/migrate/20210316154831_delete_naric_reference_column_from_application_qualifications_table.rb
  db/schema.rb
  docs/domain-model.png
Labels: Core

#4254 Refactor APIDocs namespace so we can reuse it for new APIs
  app/components/api_docs/api_reference_component.html.erb
  app/components/api_docs/api_reference_component.rb
  app/components/api_docs/field_lengths_component.html.erb
  app/components/api_docs/field_lengths_component.rb
  app/components/api_docs/operation_component.html.erb
  app/components/api_docs/operation_component.rb
  app/components/api_docs/property_list_component.html.erb
  app/components/api_docs/property_list_component.rb
  app/components/api_docs/schema_component.html.erb
  app/components/api_docs/schema_component.rb
  app/controllers/api_docs/openapi_controller.rb
  app/controllers/api_docs/pages_controller.rb
  app/controllers/api_docs/reference_controller.rb
  app/controllers/api_docs/vendor_api_docs/openapi_controller.rb
  app/controllers/api_docs/vendor_api_docs/pages_controller.rb
  app/controllers/api_docs/vendor_api_docs/reference_controller.rb
  app/helpers/navigation_items.rb
  app/presenters/api_docs/api_reference.rb
  app/views/api_docs/pages/rendered_markdown_template.html.erb
  app/views/api_docs/vendor_api_docs/pages/alpha_release_notes.md
  app/views/api_docs/vendor_api_docs/pages/help.md
  app/views/api_docs/vendor_api_docs/pages/home.md
  app/views/api_docs/vendor_api_docs/pages/lifecycle.html.erb
  app/views/api_docs/vendor_api_docs/pages/release_notes.md
  app/views/api_docs/vendor_api_docs/pages/rendered_markdown_template.html.erb
  app/views/api_docs/vendor_api_docs/pages/usage.md
  app/views/api_docs/vendor_api_docs/pages/when_emails_are_sent.html.erb
  app/views/api_docs/vendor_api_docs/reference/reference.html.erb
  app/views/layouts/_header.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: API docs

#4303 Use the offered_option in the ApplicationDataExport
  app/controllers/provider_interface/application_data_export_controller.rb
  app/models/application_choice.rb
  app/services/provider_interface/application_data_export.rb
  spec/services/provider_interface/application_data_export_spec.rb
Labels: Bug bash 🐞🔨, ProVendor

#4302 Add JS specs to autosuggests
  app/frontend/packs/application-candidate.js
  app/frontend/packs/autosuggests/__snapshots__/autosuggest-inputs.spec.js.snap
  app/frontend/packs/autosuggests/__snapshots__/init-autosuggest.spec.js.snap
  app/frontend/packs/autosuggests/autosuggest-inputs.js
  app/frontend/packs/autosuggests/autosuggest-inputs.spec.js
  app/frontend/packs/autosuggests/degree-grade-autosuggest.js
  app/frontend/packs/autosuggests/degree-institution-autosuggest.js
  app/frontend/packs/autosuggests/degree-subject-autosuggest.js
  app/frontend/packs/autosuggests/degree-type-autosuggest.js
  app/frontend/packs/autosuggests/init-autosuggest.js
  app/frontend/packs/autosuggests/init-autosuggest.spec.js
  app/frontend/packs/autosuggests/other-qualifications-grade-autosuggest.js
  app/frontend/packs/autosuggests/other-qualifications-subject-autosuggest.js
  app/frontend/packs/autosuggests/other-uk-qualifications-type-autosuggest.js
  package.json
Labels: Candidate, javascript

#4288 Apply again metrics for Feature Metrics dashboard 2.0 (part 2/4)
  app/models/apply_again_feature_metrics.rb
  app/models/feature_metrics_dashboard.rb
  app/views/support_interface/performance/feature_metrics_dashboard.html.erb
  config/brakeman.ignore
  spec/models/apply_again_feature_metrics_spec.rb
  spec/models/feature_metrics_dashboard_spec.rb
Labels: Candidate, Support

#4320 Move factories to their own file
  .rubocop.yml
  spec/factories.rb
  spec/factories/application_choice.rb
  spec/factories/application_choice_audit.rb
  spec/factories/application_experience.rb
  spec/factories/application_feedback.rb
  spec/factories/application_form.rb
  spec/factories/application_qualification.rb
  spec/factories/application_work_history_break.rb
  spec/factories/audit.rb
  spec/factories/authentication_token.rb
  spec/factories/candidate.rb
  spec/factories/chase_sent.rb
  spec/factories/course.rb
  spec/factories/course_option.rb
  spec/factories/dfe_sign_in_user.rb
  spec/factories/email.rb
  spec/factories/english_proficiency.rb
  spec/factories/feature.rb
  spec/factories/iels_qualifications.rb
  spec/factories/interview.rb
  spec/factories/note.rb
  spec/factories/other_efl_qualification.rb
  spec/factories/provider.rb
  spec/factories/provider_agreement.rb
  spec/factories/provider_permissions.rb
  spec/factories/provider_relationship_permissions.rb
  spec/factories/provider_user.rb
  spec/factories/provider_user_notification_preferences.rb
  spec/factories/reference.rb
  spec/factories/reference_token.rb
  spec/factories/site.rb
  spec/factories/support_user.rb
  spec/factories/toefl_qualification.rb
  spec/factories/ucas_match.rb
  spec/factories/validation_error.rb
  spec/factories/vendor_api_request.rb
  spec/factories/vendor_api_token.rb
  spec/factories/vendor_api_user.rb
Labels: Core

#4331 Update notification preferences in one transaction
  app/models/provider_user_notification_preferences.rb
Labels: Notifications, ProVendor

#4328 Add index to audits table to improve query performance
  db/migrate/20210319163050_add_auditable_type_id_index_to_audits.rb
  db/schema.rb
Labels: Core

#4295 Export documentation
  app/exports/_common_columns.yml
  app/exports/active_provider_user_permissions_export.yml
  app/exports/application_choices_export.yml
  app/exports/candidate_application_feedback_export.yml
  app/exports/candidate_feedback_export.yml
  app/exports/candidate_journey_tracking_export.yml
  app/exports/equality_and_diversity_export.yml
  app/exports/interview_changes_export.yml
  app/exports/tad_export.yml
  app/exports/work_history_break_export.yml
  app/models/data_export.rb
  app/services/data_set_documentation.rb
  app/services/support_interface/application_choices_export.rb
  app/services/support_interface/candidate_application_feedback_export.rb
  app/services/support_interface/candidate_feedback_export.rb
  app/services/support_interface/candidate_journey_tracker.rb
  app/services/support_interface/candidate_journey_tracking_export.rb
  app/services/support_interface/equality_and_diversity_export.rb
  app/services/support_interface/work_history_break_export.rb
  spec/services/support_interface/application_choices_export_spec.rb
  spec/services/support_interface/candidate_application_feedback_export_spec.rb
  spec/services/support_interface/candidate_feedback_export_spec.rb
  spec/services/support_interface/candidate_journey_tracker_spec.rb
  spec/services/support_interface/candidate_journey_tracking_export_spec.rb
  spec/services/support_interface/equality_and_diversity_export_spec.rb
  spec/services/support_interface/work_history_break_export_spec.rb
  spec/support/data_export_shared_example.rb
  spec/system/support_interface/data_export_spec.rb
Labels: Support

#4317 Add JS specs to autocompletes
  app/frontend/packs/application-candidate.js
  app/frontend/packs/application-support.js
  app/frontend/packs/autocompletes/__snapshots__/init-autocomplete.spec.js.snap
  app/frontend/packs/autocompletes/api-token-autocomplete.js
  app/frontend/packs/autocompletes/candidate/__snapshots__/candidate-autocomplete-inputs.spec.js.snap
  app/frontend/packs/autocompletes/candidate/candidate-autocomplete-inputs.js
  app/frontend/packs/autocompletes/candidate/candidate-autocomplete-inputs.spec.js
  app/frontend/packs/autocompletes/country-autocomplete.js
  app/frontend/packs/autocompletes/courses-autocomplete.js
  app/frontend/packs/autocompletes/init-autocomplete.js
  app/frontend/packs/autocompletes/init-autocomplete.spec.js
  app/frontend/packs/autocompletes/nationality-autocomplete.js
  app/frontend/packs/autocompletes/providers-autocomplete.js
  app/frontend/packs/autocompletes/support/__snapshots__/support-autocomplete-inputs.spec.js.snap
  app/frontend/packs/autocompletes/support/support-autocomplete-inputs.js
  app/frontend/packs/autocompletes/support/support-autocomplete-inputs.spec.js
  app/frontend/packs/autosuggests/__snapshots__/autosuggest-inputs.spec.js.snap
  app/frontend/packs/autosuggests/autosuggest-inputs.spec.js
  app/frontend/packs/autosuggests/candidate/__snapshots__/candidate-autosuggest-inputs.spec.js.snap
  app/frontend/packs/autosuggests/candidate/candidate-autosuggest-inputs.js
  app/frontend/packs/autosuggests/candidate/candidate-autosuggest-inputs.spec.js
Labels: Core, JavaScript

#4337 Remove service created for a data migration
  app/services/data_migrations/revert_application_choice_updated_at_timestamps.rb
  lib/tasks/data.rake
  spec/services/data_migrations/revert_application_choice_updated_at_timestamps_spec.rb
Labels: Core

#4338 Applications export handles no degree level qualification
  app/services/provider_interface/application_data_export.rb
  spec/services/provider_interface/application_data_export_spec.rb
Labels: Bug bash 🐞🔨, ProVendor, Sandbox

#4322 Extend test data for feature metrics dashboard
  app/lib/test_applications.rb
  app/workers/generate_test_applications.rb
  spec/factories/application_form.rb
  spec/workers/generate_test_applications_spec.rb
Labels: Test data

#4334 Add additional details to the add course page on the support UI
  app/forms/support_interface/application_forms/pick_course_form.rb
  app/views/support_interface/application_forms/courses/new.html.erb
  spec/forms/support_interface/application_forms/pick_course_form_spec.rb
Labels: Support

#4342 Remove inline styles
  app/views/candidate_interface/volunteering/role/_form.html.erb
  app/views/candidate_interface/work_history/edit/_form.html.erb
Labels: CSS, Candidate

#4340 Copy changes to task list and application page
  app/components/provider_interface/application_choice_header_component.html.erb
  app/helpers/task_view_helper.rb
Labels: ProVendor, Provider UI

#4304 Update notification_preferences when updating send_notifications
  app/controllers/provider_interface/notifications_controller.rb
  app/controllers/support_interface/provider_users_controller.rb
  app/services/provider_interface/save_provider_user_service.rb
  app/services/save_provider_user.rb
  app/services/save_provider_user_notification_preferences.rb
  spec/factories/provider_user.rb
  spec/services/provider_interface/save_provider_user_service_spec.rb
  spec/services/save_provider_user_notification_preferences_spec.rb
  spec/services/save_provider_user_spec.rb
Labels: Notifications, ProVendor

#4335 Refactor API User Authentication
  app/controllers/concerns/service_api_user_authentication.rb
  app/controllers/data_api/tad_data_exports_controller.rb
  app/controllers/register_api/applications_controller.rb
  app/models/service_api_user.rb
  config/routes.rb
  spec/requests/data_api/tad_api_spec.rb
  spec/requests/register_api/applications_controller_spec.rb
Labels: ProVendor

#4269 Upsert ProviderUserNotificationPreferences
  app/services/data_migrations/upsert_provider_user_send_notifications.rb
  lib/tasks/data.rake
  spec/services/data_migrations/upsert_provider_user_send_notifications_spec.rb
Labels: Notifications, ProVendor

#4316 Add service to validate course detail combination.
  app/services/offered_course_option_details_check.rb
  spec/services/offered_course_option_details_check_spec.rb
Labels: Offers, ProVendor

#4347 Replace warning component with one from govuk-components
  Gemfile
  Gemfile.lock
  app/components/warning_text_component.html.erb
  app/components/warning_text_component.rb
  app/views/provider_interface/decisions/confirm_withdraw_offer.html.erb
  app/views/support_interface/docs/index.html.erb
  app/views/support_interface/providers/courses.html.erb
  app/views/support_interface/support_users/new.html.erb
  spec/components/warning_text_component_spec.rb
Labels: Core, Provider UI, Ruby, Support

#4353 Enable autocompletes for 'choose a provider' and 'choose a course'
  app/frontend/packs/autocompletes/candidate/__snapshots__/candidate-autocomplete-inputs.spec.js.snap
  app/frontend/packs/autocompletes/candidate/candidate-autocomplete-inputs.js
Labels: Bug bash 🐞🔨, Candidate, JavaScript

#4343 Add Javascript linter
  Dockerfile
  app/frontend/packs/app-back-link.js
  app/frontend/packs/application-api-docs.js
  app/frontend/packs/application-candidate.js
  app/frontend/packs/application-provider.js
  app/frontend/packs/application-support.js
  app/frontend/packs/application.js
  app/frontend/packs/autocompletes/candidate/candidate-autocomplete-inputs.js
  app/frontend/packs/autocompletes/candidate/candidate-autocomplete-inputs.spec.js
  app/frontend/packs/autocompletes/init-autocomplete.js
  app/frontend/packs/autocompletes/init-autocomplete.spec.js
  app/frontend/packs/autocompletes/support/support-autocomplete-inputs.js
  app/frontend/packs/autocompletes/support/support-autocomplete-inputs.spec.js
  app/frontend/packs/autosuggests/candidate/candidate-autosuggest-inputs.js
  app/frontend/packs/autosuggests/candidate/candidate-autosuggest-inputs.spec.js
  app/frontend/packs/autosuggests/helpers.js
  app/frontend/packs/autosuggests/init-autosuggest.js
  app/frontend/packs/autosuggests/init-autosuggest.spec.js
  app/frontend/packs/components/paginated_filter.js
  app/frontend/packs/nationalities-component.js
  app/frontend/packs/warn-on-unsaved-changes.js
  app/frontend/packs/warn-on-unsaved-changes.test.js
  package.json
  yarn.lock
Labels: Core, JavaScript

#4339 Fix back links and add page titles to setup_permission views
  app/views/provider_interface/provider_relationship_permissions_setup/check.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/setup_permissions.html.erb
Labels: Bug bash 🐞🔨, ProVendor, Provider UI

#4351 Remove `ProviderUserForm`
  app/forms/provider_interface/provider_user_form.rb
  spec/forms/provider_interface/provider_user_form_spec.rb
Labels: ProVendor, Provider UI

#4332 Add specs to the API docs
  app/components/api_docs/operation_component.html.erb
  app/presenters/api_docs/api_operation.rb
  app/presenters/api_docs/api_reference.rb
  app/presenters/api_docs/api_schema.rb
  spec/components/api_docs/operation_component_spec.rb
  spec/presenters/api_docs/api_operation_spec.rb
  spec/presenters/api_docs/api_reference_spec.rb
  spec/presenters/api_docs/api_schema_spec.rb
  spec/support/open_api_example_spec.rb
Labels: API docs, Documentation

#4333 Export documentation 2
  app/components/support_interface/qualification_documentation_component.html.erb
  app/components/support_interface/qualification_documentation_component.rb
  app/controllers/support_interface/docs_controller.rb
  app/exports/_common_columns.yml
  app/exports/active_provider_users_export.yml
  app/exports/application_choices_export.yml
  app/exports/application_references_export.yml
  app/exports/applications_export.yml
  app/exports/candidate_autofill_usage_export.yml
  app/exports/providers_export.yml
  app/exports/qualifications_export.yml
  app/exports/referee_survey_export.yml
  app/exports/sites_export.yml
  app/services/support_interface/active_provider_users_export.rb
  app/services/support_interface/application_references_export.rb
  app/services/support_interface/applications_export.rb
  app/services/support_interface/candidate_autofill_usage_export.rb
  app/services/support_interface/equality_and_diversity_export.rb
  app/services/support_interface/providers_export.rb
  app/services/support_interface/qualifications_export.rb
  app/services/support_interface/referee_survey_export.rb
  app/services/support_interface/sites_export.rb
  app/views/support_interface/docs/_docs_navigation.html.erb
  app/views/support_interface/docs/qualifications.html.erb
  config/routes.rb
  spec/services/support_interface/active_provider_users_export_spec.rb
  spec/services/support_interface/application_references_export_spec.rb
  spec/services/support_interface/applications_export_spec.rb
  spec/services/support_interface/candidate_autofill_usage_export_spec.rb
  spec/services/support_interface/providers_export_spec.rb
  spec/services/support_interface/qualifications_export_spec.rb
  spec/services/support_interface/referee_survey_export_spec.rb
  spec/services/support_interface/sites_export_spec.rb
Labels: Documentation, Support

#4341 Split common columns documentation
  app/exports/_common_columns.yml
  app/exports/common_columns/_common_columns.yml
  app/exports/common_columns/_personal_information.yml
  app/exports/common_columns/_provider_information.yml
  app/services/data_set_documentation.rb
Labels: Documentation, Support

#4314 Qualifications (A level) metrics for Feature Metrics dashboard 2.0 (part 4/4)
  app/models/feature_metrics_dashboard.rb
  app/models/qualifications_feature_metrics.rb
  app/views/support_interface/performance/feature_metrics_dashboard.html.erb
  spec/models/feature_metrics_dashboard_spec.rb
  spec/models/qualifications_feature_metrics_spec.rb
Labels: Metrics & reporting

#4323 Test application generator improvements
  app/controllers/vendor_api/test_data_controller.rb
  app/lib/test_applications.rb
  app/services/vendor_api/generate_test_applications_for_provider.rb
  app/views/api_docs/vendor_api_docs/pages/release_notes.md
  app/workers/generate_test_applications_for_courses.rb
  config/vendor-api-experimental.yml
  config/vendor-api-v1.yml
  spec/lib/test_applications_spec.rb
  spec/requests/vendor_api/post_test_data_generate_spec.rb
  spec/services/vendor_api/generate_test_applications_for_provider_spec.rb
Labels: Test data

#4286 Let users manage the type of email notifications they receive
  app/components/provider_user_notification_preferences_component.html.erb
  app/components/provider_user_notification_preferences_component.rb
  app/components/support_interface/provider_user_summary_component.rb
  app/controllers/provider_interface/notifications_controller.rb
  app/controllers/support_interface/provider_user_notification_preferences_controller.rb
  app/controllers/support_interface/provider_users_controller.rb
  app/services/save_provider_user_notification_preferences.rb
  app/views/provider_interface/notifications/show.html.erb
  app/views/support_interface/provider_users/edit.html.erb
  app/views/support_interface/provider_users/show.html.erb
  config/locales/provider_user_notification_preferences.yml
  config/routes.rb
  spec/components/previews/provider_user_notification_preferences_component_preview.rb
  spec/components/previews/support_interface/provider_user_summary_component_preview.rb
  spec/components/provider_user_notification_preferences_component_spec.rb
  spec/components/support_interface/provider_user_summary_component_spec.rb
  spec/system/provider_interface/manage_provider_user_global_notifications_spec.rb
  spec/system/provider_interface/manage_provider_user_notifications_spec.rb
  spec/system/support_interface/managing_provider_user_notification_preferences_spec.rb
Labels: Notifications, ProVendor

#4360 Remove old data migrations
  app/services/data_migrations/update_authentication_token_types.rb
  app/services/data_migrations/upsert_provider_user_send_notifications.rb
  lib/tasks/data.rake
  spec/services/data_migrations/update_authentication_token_types_spec.rb
  spec/services/data_migrations/upsert_provider_user_send_notifications_spec.rb
Labels: Core

#4354 Rework how PickCourseOption deals with repeated course choices
  app/controllers/candidate_interface/course_choices/course_selection_controller.rb
  app/controllers/candidate_interface/course_choices/site_selection_controller.rb
  app/controllers/candidate_interface/course_choices/study_mode_selection_controller.rb
  app/forms/candidate_interface/pick_course_form.rb
  app/services/candidate_interface/pick_course_option.rb
  app/services/candidate_interface/pick_replacement_course_option.rb
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_spec.rb
Labels: Candidate

#4367 Bump mimemagic to 0.3.6
  Gemfile.lock
Labels: DevOps, dependencies

#4363 Further refinements to course choice flow
  app/controllers/candidate_interface/course_choices/course_selection_controller.rb
  app/controllers/candidate_interface/course_choices/site_selection_controller.rb
  app/controllers/candidate_interface/course_choices/study_mode_selection_controller.rb
  app/controllers/candidate_interface/find_course_selections_controller.rb
  app/forms/candidate_interface/pick_site_form.rb
  app/services/candidate_interface/add_or_update_course_choice.rb
  app/views/candidate_interface/course_choices/site_selection/new.html.erb
  config/locales/en.yml
  spec/system/candidate_interface/course_selection/candidate_signed_in_user_with_course_params_spec.rb
Labels: Candidate

#4373 Use GovukComponent::BackLink
  app/frontend/styles/_back_link.scss
  app/helpers/view_helper.rb
  spec/helpers/view_helper_spec.rb
Labels: Components, Core

#4345 Update the candidate offer page
  app/components/candidate_interface/offer_conditions_review_component.html.erb
  app/components/candidate_interface/offer_review_component.rb
  app/controllers/candidate_interface/decisions_controller.rb
  app/views/candidate_interface/decisions/offer.html.erb
  config/locales/provider_interface/decisions.yml
  spec/components/candidate_interface/offer_review_component_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_spec.rb
  spec/system/vendor_api/vendor_makes_unconditional_offer_spec.rb
Labels: Candidate, Content, Offers

#4355 GitHub Actions workflow to build docker image
  .dockerignore
  .github/workflows/build.yml
Labels: DevOps, PaaS

#4375 Add matrix job to run rspec tests
  .github/workflows/build.yml
Labels: DevOps, PaaS

#4383 Refactor queries where multiple args are passed into where.not
  app/services/support_interface/candidate_autofill_usage_export.rb
  app/services/support_interface/referee_survey_export.rb
Labels: Core

#4384 Never display header as part of conditions component
  app/components/provider_interface/conditions_component.html.erb
  app/components/provider_interface/conditions_component.rb
  app/components/provider_interface/deferred_offer_details_component.html.erb
  app/components/provider_interface/status_box_components/pending_conditions_component.html.erb
  app/views/provider_interface/conditions/edit.html.erb
  app/views/provider_interface/reconfirm_deferred_offers/conditions.html.erb
Labels: Offers, ProVendor

#4372 Add course validation service to offer wizard
  app/forms/provider_interface/offer_wizard.rb
  app/services/offered_course_option_details_check.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
Labels: Offers, ProVendor

#4318 Adding a Data Directory to the Performance tab
  app/components/data_set_attribute_component.html.erb
  app/components/data_set_attribute_component.rb
  app/controllers/support_interface/data_exports_controller.rb
  app/models/data_export.rb
  app/views/data_api/tad_docs/docs.html.erb
  app/views/support_interface/data_exports/_data_export_navigation.html.erb
  app/views/support_interface/data_exports/directory.html.erb
  app/views/support_interface/data_exports/show.html.erb
  app/views/support_interface/data_exports/view_export_information.html.erb
  app/views/support_interface/data_exports/view_history.html.erb
  app/views/support_interface/docs/_docs_navigation.html.erb
  app/views/support_interface/docs/index.html.erb
  app/views/support_interface/performance/_performance_navigation.html.erb
  app/workers/data_exporter.rb
  config/routes.rb
  spec/system/support_interface/data_directory_spec.rb
  spec/system/support_interface/data_export_spec.rb
  spec/system/support_interface/see_user_guidance_spec.rb
Labels: Documentation

#4388 Unconditional Offers can't be submitted through Manage
  app/controllers/provider_interface/decisions_controller.rb
  spec/services/make_an_offer_spec.rb
Labels: Offers, ProVendor

#4390 Only retrieve study modes of course options with vacancies
  app/forms/candidate_interface/pick_course_form.rb
  app/forms/candidate_interface/pick_study_mode_form.rb
  app/models/course.rb
  spec/forms/candidate_interface/pick_course_form_spec.rb
  spec/forms/candidate_interface/pick_study_mode_form_spec.rb
  spec/models/course_spec.rb
Labels: Candidate

#4396 Offers with conditions met can not be withdrawn
  app/components/provider_interface/status_box_components/recruited_component.html.erb
  spec/components/provider_interface/status_box_components/recruited_component_spec.rb
Labels: Offers, ProVendor

#4395 Terraform config to deploy web app to PaaS
  .dockerignore
  .gitignore
  terraform/.terraform.lock.hcl
  terraform/data.tf
  terraform/modules/paas/data.tf
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/qa_backend.tfvars
Labels: DevOps, PaaS

#4402 Workflow to restore Azure Database to PaaS
  .github/workflows/database-restore.yml
Labels: DevOps, PaaS

#4404 Create & bind postgres and redis service instances
  terraform/modules/paas/data.tf
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/qa.tfvars
Labels: DevOps, PaaS

#4356 Use GovukComponent::Accordion
  app/components/candidate_interface/grouped_provider_courses_component.html.erb
  app/components/support_interface/audit_trail_item_component.html.erb
  spec/components/candidate_interface/grouped_provider_courses_component_spec.rb
Labels: Candidate, Components

#4344 Run rspec in parallel by default
  lib/tasks/testing.rake
Labels: Core

#4187 Display details of offered course
  app/components/candidate_interface/course_choices_review_component.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
Labels: Candidate, Offers

#4407 Update OffersController to use new ChangeOffer service wrapper
  app/controllers/provider_interface/offers_controller.rb
Labels: Offers, ProVendor

#4370 3162 export documentation 4
  app/exports/active_provider_users_export.yml
  app/exports/application_choices_export.yml
  app/exports/common_columns/_common_columns.yml
  app/exports/common_columns/_provider_information.yml
  app/exports/offer_conditions_export.yml
  app/exports/organisation_permissions_export.yml
  app/exports/persona_export.yml
  app/exports/provider_access_controls_export.yml
  app/exports/structured_reasons_for_rejection_export.yml
  app/exports/tad_provider_stats_export.yml
  app/exports/user_permissions_export.yml
  app/presenters/support_interface/flat_reasons_for_rejection_presenter.rb
  app/services/data_set_documentation.rb
  app/services/support_interface/offer_conditions_export.rb
  app/services/support_interface/persona_export.rb
  app/services/support_interface/provider_access_controls_export.rb
  app/services/support_interface/structured_reasons_for_rejection_export.rb
  app/services/support_interface/tad_provider_stats_export.rb
  spec/presenters/support_interface/flat_reasons_for_rejection_presenter_spec.rb
  spec/services/support_interface/application_choices_export_spec.rb
  spec/services/support_interface/equality_and_diversity_export_spec.rb
  spec/services/support_interface/offer_conditions_export_spec.rb
  spec/services/support_interface/persona_export_spec.rb
  spec/services/support_interface/provider_access_controls_export_spec.rb
  spec/services/support_interface/structured_reasons_for_rejection_export_spec.rb
  spec/services/support_interface/tad_provider_stats_export_spec.rb
  spec/support/data_export_shared_example.rb
Labels: Documentation, Support

#4406 Clock and Worker app terraform configuration
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
Labels: DevOps, PaaS

#4394 Display DBD information on application page
  app/components/provider_interface/application_choice_header_component.html.erb
  app/components/provider_interface/application_choice_header_component.rb
  app/helpers/view_helper.rb
  spec/components/provider_interface/application_choice_header_component_spec.rb
  spec/helpers/view_helper_spec.rb
Labels: ProVendor, Provider UI

#4414 Offer flow - back button error
  app/services/wizard_path_history.rb
  spec/services/wizard_path_history_spec.rb
Labels: Offers, ProVendor

#4398 Document the Data API and support retrieving single reports over it
  app/components/api_docs/operation_component.html.erb
  app/controllers/api_docs/data_api_docs/open_api_controller.rb
  app/controllers/api_docs/data_api_docs/reference_controller.rb
  app/controllers/data_api/tad_data_exports_controller.rb
  app/controllers/data_api/tad_docs_controller.rb
  app/exports/common_columns/_provider_information.yml
  app/helpers/api_docs_helper.rb
  app/helpers/application_helper.rb
  app/lib/data_api_specification.rb
  app/presenters/api_docs/api_operation.rb
  app/services/data_api/tad_export.rb
  app/views/api_docs/data_api_docs/reference/reference.html.erb
  app/views/layouts/base.html.erb
  config/data-api.yml
  config/locales/en.yml
  config/routes.rb
  spec/presenters/api_docs/api_operation_spec.rb
  spec/requests/data_api/tad_api_spec.rb
  spec/requests/data_api/tad_exports_spec.rb
  spec/requests/data_api/tad_latest_spec.rb
  spec/requests/data_api/tad_single_export_spec.rb
  spec/support/data_api/data_api_spec_helper.rb
  spec/support/data_api/shared_examples.rb
  spec/system/data_api/data_api_docs_spec.rb
  spec/system/data_api/tad_data_docs_spec.rb
Labels: API docs, Core

#4397 Use GovukComponent::Details
  app/components/api_docs/operation_component.html.erb
  app/components/candidate_interface/application_status_tag_component.html.erb
  app/components/candidate_interface/rejection_reasons_component.html.erb
  app/components/provider_interface/email_log_row_component.html.erb
  app/components/provider_interface/provider_relationship_permissions_list_component.html.erb
  app/components/provider_interface/safeguarding_declaration_component.html.erb
  app/components/state_diagram_component.html.erb
  app/components/support_interface/application_api_representation_component.html.erb
  app/components/support_interface/email_log_row_component.html.erb
  app/components/support_interface/ucas_match_table_component.html.erb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
  app/views/provider_interface/reconfirm_deferred_offers/start.html.erb
  app/views/support_interface/vendor_api_requests/index.html.erb
Labels: Components, Core

#4421 Use GovukComponent::Footer
  app/views/layouts/_footer.html.erb
Labels: Components, Core

#4425 Use GovukComponent::Panel
  app/views/candidate_interface/decisions/withdrawal_feedback.html.erb
  app/views/candidate_interface/submitted_application_form/submit_success.html.erb
  app/views/provider_interface/provider_agreements/success.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/success.html.erb
  app/views/referee_interface/reference/confirmation.html.erb
  app/views/support_interface/api_tokens/create.html.erb
Labels: Components, Core

#4426 Use GovukComponent::StartNowButton
  app/components/gov_uk_start_button_component.html.erb
  app/components/gov_uk_start_button_component.rb
  app/views/candidate_interface/apply_from_find/_apply_using_ucas.html.erb
  app/views/candidate_interface/course_choices/course_decision/go_to_find.html.erb
  app/views/content/sandbox.html.erb
  app/views/provider_interface/start_page/show.html.erb
  spec/components/gov_uk_start_button_component_spec.rb
Labels: Components, Core
