Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2021-01, with the labels that each got.

#3698 Fix illogical heading structures
  app/components/candidate_interface/break_in_work_history_component.html.erb
  app/components/candidate_interface/break_in_work_history_component.rb
  app/components/candidate_interface/break_placeholder_in_work_history_component.html.erb
  app/components/candidate_interface/break_placeholder_in_work_history_component.rb
  app/components/candidate_interface/references_review_component.html.erb
  app/components/candidate_interface/references_review_component.rb
  app/components/candidate_interface/volunteering_review_component.html.erb
  app/components/candidate_interface/work_history_review_component.html.erb
  app/components/filter_component.html.erb
  app/components/provider_interface/activity_log_event_component.html.erb
  app/components/provider_interface/application_choice_header_component.html.erb
  app/components/provider_interface/application_timeline_component.html.erb
  app/components/provider_interface/provider_relationship_permissions_list_component.html.erb
  app/components/provider_interface/provider_relationship_permissions_list_component.rb
  app/components/provider_interface/provider_user_details_component.html.erb
  app/components/provider_interface/user_list_card_component.html.erb
  app/components/state_explanation_component.html.erb
  app/components/support_interface/application_card_component.html.erb
  app/components/support_interface/application_card_component.rb
  app/components/support_interface/application_choice_component.html.erb
  app/components/support_interface/applications_table_component.html.erb
  app/components/support_interface/applications_table_component.rb
  app/components/support_interface/audit_trail_item_component.html.erb
  app/components/support_interface/provider_user_permissions_component.html.erb
  app/components/support_interface/reference_with_feedback_component.html.erb
  app/components/support_interface/ucas_match_action_component.html.erb
  app/views/api_docs/pages/alpha_release_notes.md
  app/views/api_docs/pages/release_notes.md
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/degrees/institution/_form_fields.html.erb
  app/views/candidate_interface/degrees/subject/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/type/new.html.erb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/submitted_application_form/complete.html.erb
  app/views/content/sandbox.html.erb
  app/views/provider_interface/notes/index.html.erb
  app/views/provider_interface/organisations/show.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/check.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/setup_permissions.html.erb
  app/views/support_interface/data_exports/index.html.erb
  app/views/support_interface/data_exports/new.html.erb
  app/views/support_interface/docs/mailer_previews.erb
  app/views/support_interface/docs/mailer_previews.html.erb
  app/views/support_interface/performance/unavailable_choices.html.erb
  app/views/support_interface/performance_dashboard/dashboard.html.erb
  app/views/support_interface/providers/courses.html.erb
  app/views/support_interface/providers/ratified_courses.html.erb
  app/views/support_interface/settings/cycles.html.erb
  app/views/support_interface/settings/feature_flags.html.erb
  app/views/support_interface/tasks/index.html.erb
  app/views/support_interface/ucas_matches/show.html.erb
  app/views/support_interface/validation_errors/index.html.erb
  app/views/support_interface/validation_errors/search.html.erb
Labels: API docs, Accessibility, Candidate, Provider UI, Support

#3753 Redirect to the offer page after deferring an offer
  app/controllers/provider_interface/decisions_controller.rb
  spec/system/provider_interface/provider_defers_an_offer_spec.rb
Labels: ProVendor

#3755 Update routes to align with interface (school experience)
  config/routes.rb
Labels: Candidate

#3723 Add focus styles to links in SVG diagrams
  app/frontend/styles/_diagram.scss
  app/lib/state_diagram.rb
  app/presenters/support_interface/provider_relationships_diagram.rb
Labels: Accessibility, Support

#3756 Fix underscore in degrees completion status paths
  config/routes.rb
Labels: Candidate

#3754 Reduce number of notifications in apply support channel
  app/lib/state_change_notifier.rb
  app/services/accept_offer.rb
  app/services/confirm_offer_conditions.rb
  app/services/decline_offer.rb
  app/services/make_an_offer.rb
  app/services/reinstate_conditions_met.rb
  app/services/reinstate_pending_conditions.rb
  app/services/reject_application.rb
  app/services/reject_application_by_default.rb
  app/services/submit_application.rb
  app/services/withdraw_application.rb
  app/services/withdraw_offer.rb
  config/locales/slack_notifications.yml
  spec/lib/state_change_notifier_spec.rb
  spec/services/confirm_offer_conditions_spec.rb
  spec/services/decline_offer_spec.rb
  spec/services/reinstate_conditions_met_spec.rb
  spec/services/reinstate_pending_conditions_spec.rb
  spec/services/reject_application_by_default_spec.rb
  spec/services/reject_application_spec.rb
  spec/services/reject_applications_by_default_spec.rb
  spec/services/withdraw_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_accepts_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_declines_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_withdraws_spec.rb
  spec/system/candidate_interface/submitting/candidate_submitting_application_spec.rb
Labels: ProVendor

#3716 Fix issues with validation errors and summaries
  app/components/provider_interface/change_offer/change_course_component.html.erb
  app/components/provider_interface/edit_provider_user_permissions_component.html.erb
  app/controllers/candidate_interface/safeguarding_controller.rb
  app/controllers/candidate_interface/training_with_a_disability_controller.rb
  app/views/candidate_interface/application_choices/review.html.erb
  app/views/candidate_interface/application_feedback/new.html.erb
  app/views/candidate_interface/course_choices/have_you_chosen/ask.html.erb
  app/views/candidate_interface/course_choices/site_selection/new.html.erb
  app/views/candidate_interface/course_choices/study_mode_selection/new.html.erb
  app/views/candidate_interface/decisions/withdrawal_feedback.html.erb
  app/views/candidate_interface/degrees/completion_status/_form_fields.html.erb
  app/views/candidate_interface/degrees/grade/_form_fields.html.erb
  app/views/candidate_interface/degrees/naric/_form_fields.html.erb
  app/views/candidate_interface/degrees/type/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/start/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/type/new.html.erb
  app/views/candidate_interface/equality_and_diversity/edit_disabilities.html.erb
  app/views/candidate_interface/equality_and_diversity/edit_ethnic_background.html.erb
  app/views/candidate_interface/find_course_selections/confirm_selection.html.erb
  app/views/candidate_interface/gcse/english/grade/edit.html.erb
  app/views/candidate_interface/gcse/naric/edit.html.erb
  app/views/candidate_interface/gcse/science/grade/awards_edit.html.erb
  app/views/candidate_interface/gcse/science/grade/edit.html.erb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  app/views/candidate_interface/other_qualifications/details/new.html.erb
  app/views/candidate_interface/other_qualifications/type/_shared_form.html.erb
  app/views/candidate_interface/personal_details/nationalities/_shared_form.html.erb
  app/views/candidate_interface/personal_details/right_to_work_or_study/_shared_form.html.erb
  app/views/candidate_interface/references/review/unsubmitted.html.erb
  app/views/candidate_interface/references/type/_shared_form.html.erb
  app/views/candidate_interface/safeguarding/edit.html.erb
  app/views/candidate_interface/sign_up/new.html.erb
  app/views/candidate_interface/start_page/create_account_or_sign_in.html.erb
  app/views/candidate_interface/training_with_a_disability/edit.html.erb
  app/views/candidate_interface/work_history/edit/new.html.erb
  app/views/provider_interface/application_data_export/new.html.erb
  app/views/provider_interface/notifications/show.html.erb
  app/views/provider_interface/provider_agreements/data_sharing_agreement.html.erb
  app/views/provider_interface/provider_relationship_permissions/edit.html.erb
  app/views/provider_interface/provider_relationship_permissions_setup/setup_permissions.html.erb
  app/views/provider_interface/provider_users_invitations/edit_permissions.html.erb
  app/views/provider_interface/reasons_for_rejection/edit_initial_questions.html.erb
  app/views/provider_interface/reconfirm_deferred_offers/conditions.html.erb
  app/views/referee_interface/reference/confirmation.html.erb
  app/views/referee_interface/reference/refuse_feedback.html.erb
  app/views/support_interface/application_forms/address_type/edit.html.erb
  app/views/support_interface/application_forms/courses/new.html.erb
  app/views/support_interface/application_forms/nationalities/edit.html.erb
  app/views/support_interface/application_forms/right_to_work_or_study/edit.html.erb
  app/views/support_interface/provider_users/_provider_options.html.erb
  config/locales/application_form.yml
Labels: Accessibility, Candidate

#3767 Update routes to align with interface (personal statement)
  app/controllers/candidate_interface/interview_needs_controller.rb
  app/controllers/candidate_interface/personal_statement_controller.rb
  app/controllers/candidate_interface/subject_knowledge_controller.rb
  app/views/candidate_interface/interview_needs/edit.html.erb
  app/views/candidate_interface/interview_needs/show.html.erb
  app/views/candidate_interface/personal_statement/edit.html.erb
  app/views/candidate_interface/personal_statement/show.html.erb
  app/views/candidate_interface/subject_knowledge/edit.html.erb
  app/views/candidate_interface/subject_knowledge/show.html.erb
  config/routes.rb
Labels: Candidate

#3751 Only export the current cycles data for the HESA export
  app/queries/get_application_choices_for_providers.rb
  app/services/provider_interface/hesa_data_export.rb
  app/views/provider_interface/hesa_export/new.html.erb
  config/locales/en.yml
  spec/queries/get_application_choices_for_providers_spec.rb
  spec/services/provider_interface/hesa_data_export_spec.rb
  spec/support/test_helpers/course_option_helpers.rb
Labels: ProVendor

#3778 Show rejected_at and rejected_by_default_at in Support
  app/components/support_interface/application_choice_component.rb
  spec/components/support_interface/application_choice_component_spec.rb
Labels: Support

#3780 Link to 2020/21 HESA codes in the API docs
  app/views/api_docs/pages/home.md
Labels: ProVendor

#3770 Remove structured qualifications feature flags
  app/components/candidate_interface/gcse_grade_guidance_component.html.erb
  app/controllers/candidate_interface/gcse/english/grade_controller.rb
  app/controllers/candidate_interface/gcse/science/grade_controller.rb
  app/forms/candidate_interface/english_gcse_grade_form.rb
  app/services/feature_flag.rb
  config/locales/gcse_details.yml
  spec/components/candidate_interface/gcse_grade_guidance_component_spec.rb
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/forms/candidate_interface/english_gcse_grade_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/candidate_entering_english_gcse_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_science_award_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_science_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: Candidate

#3777 Add validations to provider permissions setting forms
  app/forms/provider_interface/provider_user_invitation_wizard.rb
  app/forms/provider_interface/provider_user_permissions_form.rb
  spec/forms/provider_interface/provider_user_permissions_form_spec.rb
  spec/system/provider_interface/manage_provider_user_permissions_spec.rb
  spec/system/provider_interface/provider_invites_user_with_new_wizard_spec.rb
Labels: ProVendor

#3783 Fix two styling issues with the API docs
  app/frontend/styles/api_docs/_syntax-highlighting.scss
  app/views/api_docs/reference/reference.html.erb
Labels: ProVendor

#3774 Reinstate authentication links from emails that rely on the `u` (user id) param
  app/controllers/candidate_interface/sign_in_controller.rb
  app/models/candidate.rb
  app/views/candidate_interface/sign_in/expired.html.erb
  spec/models/candidate_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_using_legacy_email_link_with_u_param_spec.rb
Labels: Candidate

#3727 Add unsubscribe link to footer in status change emails
  app/views/layouts/provider_email_with_footer.text.erb
  app/views/provider_mailer/_unsubscribe.text.erb
  app/views/provider_mailer/application_rejected_by_default.text.erb
  app/views/provider_mailer/application_submitted.text.erb
  app/views/provider_mailer/application_submitted_with_safeguarding_issues.text.erb
  app/views/provider_mailer/application_withdrawn.text.erb
  app/views/provider_mailer/declined.text.erb
  app/views/provider_mailer/declined_by_default.text.erb
  app/views/provider_mailer/offer_accepted.text.erb
Labels: ProVendor

#3796 Only show status change events for statuses visible to providers
  app/queries/get_activity_log_events.rb
  spec/queries/get_activity_log_events_spec.rb
Labels: ProVendor

#3739 Allow support users to sign in as provider users
  app/controllers/provider_interface/feedback_controller.rb
  app/controllers/provider_interface/provider_agreements_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/support_interface/provider_users_controller.rb
  app/controllers/vendor_api/decisions_controller.rb
  app/helpers/navigation_items.rb
  app/lib/impersonation_audit_helper.rb
  app/lib/test_applications.rb
  app/models/dfe_sign_in_user.rb
  app/models/provider_impersonation.rb
  app/models/provider_user.rb
  app/models/support_user.rb
  app/services/change_offer.rb
  app/services/conditions_not_met.rb
  app/services/confirm_offer_conditions.rb
  app/services/defer_offer.rb
  app/services/make_an_offer.rb
  app/services/provider_interface/save_provider_user_service.rb
  app/services/reinstate_conditions_met.rb
  app/services/reinstate_pending_conditions.rb
  app/services/reject_application.rb
  app/services/remove_provider_user.rb
  app/services/save_and_send_reject_by_default_feedback.rb
  app/services/withdraw_offer.rb
  app/views/support_interface/provider_users/_provider_user_impersonation.html.erb
  app/views/support_interface/provider_users/audits.html.erb
  app/views/support_interface/provider_users/show.html.erb
  config/routes.rb
  spec/factories.rb
  spec/lib/impersonation_audit_helper_spec.rb
  spec/lib/test_applications_spec.rb
  spec/models/df_e_sign_in_user_spec.rb
  spec/models/provider_user_spec.rb
  spec/models/support_user_spec.rb
  spec/services/reject_application_spec.rb
  spec/services/save_and_send_reject_by_default_feedback_spec.rb
  spec/system/support_interface/sign_in_as_provider_user_spec.rb
Labels: Core

#3788 Send a slack notification when a feature flag is changed in production
  app/controllers/support_interface/settings_controller.rb
  spec/system/support_interface/feature_flags_spec.rb
Labels: Support

#3795 Add affirmative flash messages for a candidate accepting and declining an offer
  app/controllers/candidate_interface/decisions_controller.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_accepts_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawls/candidate_declines_offer_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#3798 Bugfix: re-render course location form if there is a validation error
  app/controllers/candidate_interface/course_choices/site_selection_controller.rb
Labels: Candidate

#3772 Allow users to be pointed to a specific endpoint using the AuthenticationToken
  app/controllers/candidate_interface/after_sign_in_controller.rb
  app/controllers/candidate_interface/sign_in_controller.rb
  app/models/concerns/authenticated_using_magic_links.rb
  app/services/candidate_interface/request_magic_link.rb
  app/views/candidate_interface/sign_in/confirm_authentication.html.erb
  config/brakeman.ignore
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_with_an_authentication_token_with_a_path_spec.rb
Labels: Candidate

#3793 Remove checkboxes from feedback form, and make feedback mandatory
  app/controllers/candidate_interface/application_feedback_controller.rb
  app/forms/candidate_interface/application_feedback_form.rb
  app/views/candidate_interface/application_feedback/new.html.erb
  config/locales/application_feedback.yml
  config/locales/application_form.yml
  spec/forms/candidate_interface/application_feedback_form_spec.rb
  spec/system/candidate_interface/feedback/candidate_provides_feedback_while_completing_their_application_spec.rb
Labels: Candidate

#3790 Improve Reasons for Rejection validation messaging
  app/services/reject_application.rb
  spec/services/reject_application_spec.rb
Labels: ProVendor

#3791 Refactor application state change to use symbols
  app/models/application_form.rb
  app/models/performance_statistics.rb
  app/models/ucas_matched_application.rb
  app/services/application_state_change.rb
  app/services/process_state.rb
  app/services/send_apply_again_call_to_action.rb
  app/services/support_interface/candidate_journey_tracker.rb
  spec/models/application_form_spec.rb
  spec/models/performance_statistics_spec.rb
Labels: ProVendor

#3797 Setup data model for interviews
  app/models/interview.rb
  db/migrate/20210107175105_create_interviews.rb
  db/schema.rb
  spec/models/interview_spec.rb
Labels: ProVendor

#3701 Show UCAS matches statistics
  app/components/support_interface/ucas_matches_statistics_component.html.erb
  app/components/support_interface/ucas_matches_statistics_component.rb
  app/controllers/support_interface/performance_controller.rb
  app/views/support_interface/performance/index.html.erb
  app/views/support_interface/performance/ucas_matches_stats.html.erb
  config/routes.rb
  spec/components/support_interface/ucas_matches_statistics_component_spec.rb
  spec/factories.rb
  spec/system/support_interface/service_performance_spec.rb
Labels: ProVendor, Support

#3803 Qualifications data extract
  app/models/data_export.rb
  app/services/support_interface/qualifications_export.rb
  spec/services/support_interface/qualifications_export_spec.rb
Labels: Support

#3806 ApplicationFeedback cleanup (part1)
  app/services/support_interface/candidate_application_feedback_export.rb
  spec/factories.rb
  spec/services/support_interface/candidate_application_feedback_export_spec.rb
Labels: Candidate

#3807 ApplicationFeedback cleanup (part2)
  db/migrate/20210110100235_remove_unused_application_feedback_booleans_and_add_feedback_column.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3794 Feature metric dashboard part 2 - Work history/Rejections
  app/controllers/support_interface/feature_metrics_dashboard_controller.rb
  app/lib/test_applications.rb
  app/models/reasons_for_rejection_feature_metrics.rb
  app/models/reference_feature_metrics.rb
  app/models/work_history_feature_metrics.rb
  app/views/support_interface/feature_metrics_dashboard/dashboard.html.erb
  config/brakeman.ignore
  spec/models/reasons_for_rejection_feature_metrics_spec.rb
  spec/models/reference_feature_metrics_spec.rb
  spec/models/work_history_feature_metrics_spec.rb
  spec/system/support_interface/feature_metrics_dashboard_spec.rb
Labels: Candidate

#3813 Rename Submitted state to Received in the provider interface
  app/components/provider_interface/activity_log_event_component.rb
  app/components/provider_interface/application_timeline_component.rb
  config/locales/application_states.yml
  spec/components/provider_interface/activity_log_event_component_spec.rb
  spec/components/provider_interface/application_timeline_component_spec.rb
  spec/mailers/provider_mailer_spec.rb
  spec/models/provider_emails_for_application_choices_spec.rb
Labels: ProVendor

#3816 ENV vars for Apply and Manage Google analytics
  .env.development
  .env.example
  .env.test
  azure/pipelines/templates/deploy.yml
  azure/template.json
Labels: Core

#3784 Let providers search by candidate reference number
  app/components/filter_component.html.erb
  app/components/filter_component.rb
  app/components/paginated_filter_component.html.erb
  app/components/provider_interface/application_card_component.html.erb
  app/frontend/styles/_application-card.scss
  app/frontend/styles/components/_paginated_filter.scss
  app/models/provider_interface/provider_applications_filter.rb
  app/services/filter_application_choices_for_providers.rb
  app/views/provider_interface/application_choices/index.html.erb
  spec/models/provider_interface/provider_applications_filter_spec.rb
  spec/services/filter_application_choices_for_providers_spec.rb
  spec/system/provider_interface/provider_applications_filter_spec.rb
  spec/system/provider_interface/provider_applications_search_spec.rb
Labels: ProVendor

#3808 ApplicationFeedback cleanup (part3)
  app/controllers/candidate_interface/application_feedback_controller.rb
  app/forms/candidate_interface/application_feedback_form.rb
  app/services/support_interface/candidate_application_feedback_export.rb
  app/views/candidate_interface/application_feedback/new.html.erb
  config/locales/application_form.yml
  db/migrate/20210110112042_backfill_feedback_column.rb
  db/schema.rb
  spec/factories.rb
  spec/forms/candidate_interface/application_feedback_form_spec.rb
  spec/services/support_interface/candidate_application_feedback_export_spec.rb
  spec/system/candidate_interface/feedback/candidate_provides_feedback_while_completing_their_application_spec.rb
Labels: Candidate

#3828 Set postgres server storage size at 15GB
  azure/template.json
Labels: DevOps

#3829 Add phase and candidate_id to the ApplicationsExport
  app/services/support_interface/applications_export.rb
  spec/services/support_interface/applications_export_spec.rb
Labels: Candidate

#3809 ApplicationFeedback cleanup (part4)
  db/migrate/20210110112942_drop_other_feedback_column.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3831 Specify healthCheckPath to determine if app service instance is healthy
  azure/containers.json
  azure/template.json
Labels: DevOps

#3815 Introduce "Interviewing" state
  app/components/candidate_interface/application_status_tag_component.rb
  app/components/provider_interface/application_status_tag_component.rb
  app/components/provider_interface/application_timeline_component.rb
  app/components/support_interface/application_status_tag_component.rb
  app/helpers/task_view_helper.rb
  app/models/application_choice.rb
  app/models/interview.rb
  app/presenters/vendor_api/single_application_presenter.rb
  app/services/application_state_change.rb
  app/services/create_interview.rb
  app/services/provider_interface/sort_application_choices.rb
  config/locales/application_states.yml
  docs/states.png
  spec/presenters/vendor_api/single_application_presenter_spec.rb
  spec/services/application_state_change_spec.rb
  spec/services/create_interview_spec.rb
  spec/services/provider_interface/sort_application_choices_spec.rb
Labels: ProVendor

#3789 Implement Google analytics
  app/components/flash_message_component.html.erb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/content_controller.rb
  app/controllers/candidate_interface/cookie_preferences_controller.rb
  app/controllers/concerns/cookie_preference_concerns.rb
  app/controllers/provider_interface/content_controller.rb
  app/controllers/provider_interface/cookie_preferences_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/forms/cookie_preferences_form.rb
  app/frontend/styles/_cookies-banner.scss
  app/frontend/styles/application.scss
  app/views/content/cookies.html.erb
  app/views/content/cookies_candidate.md
  app/views/content/cookies_provider.md
  app/views/layouts/base.html.erb
  app/views/shared/_analytics.html.erb
  app/views/shared/_cookies_banner.html.erb
  config/routes.rb
  spec/system/candidate_interface/candidate_content_spec.rb
  spec/system/provider_interface/provider_content_spec.rb
Labels: Core

#3853 Reverts healthCheckPath
  azure/containers.json
  azure/template.json
Labels: DevOps

#3851 Only redirect to prod Apply service in production
  app/views/candidate_interface/content/providers.html.erb
  config/routes.rb
Labels: Candidate

#3846 Fix issue with referee sign in creating excess tokens
  app/components/support_interface/reference_with_feedback_component.rb
  app/controllers/support_interface/references_controller.rb
  config/routes.rb
  spec/system/support_interface/provide_or_refuse_feedback_for_a_feedback_requested_reference_spec.rb
Labels: Referee

#3854 Update clock for ProcessMatchingData
  config/clock.rb
Labels: Bug bash 🐞🔨, ProVendor

#3859 Display provider header links on Export data page
  app/helpers/navigation_items.rb
Labels: Bug bash 🐞🔨, ProVendor

#3819 Generate applications in Interviewing state
  app/lib/test_applications.rb
  spec/factories.rb
  spec/lib/test_applications_spec.rb
Labels: Core

#3845 Verify offering via the API logs to VendorAPIRequest as intended
  spec/requests/vendor_api/post_make_an_offer_spec.rb
Labels: ProVendor

#3860 Add keepalives params to postgres driver config
  config/database.yml
Labels: Core

#3857 Group rejected_by_default and declined_by_default applications in Slack notifications
  app/lib/state_change_notifier.rb
  app/services/decline_offer_by_default.rb
  app/services/reject_application_by_default.rb
  config/locales/slack_notifications.yml
  spec/lib/state_change_notifier_spec.rb
  spec/models/application_dates_spec.rb
  spec/services/change_offer_spec.rb
  spec/services/decline_offer_by_default_spec.rb
  spec/services/reject_application_by_default_spec.rb
  spec/services/reject_applications_by_default_spec.rb
Labels: Bug bash 🐞🔨, ProVendor

#3848 Implement set up an interview flow
  app/components/provider_interface/application_choice_header_component.html.erb
  app/components/provider_interface/application_choice_header_component.rb
  app/components/provider_interface/status_box_components/interviewing_component.html.erb
  app/components/provider_interface/status_box_components/interviewing_component.rb
  app/controllers/provider_interface/interviews_controller.rb
  app/helpers/navigation_items.rb
  app/models/interview.rb
  app/services/application_state_change.rb
  app/services/cancel_interview.rb
  app/services/create_interview.rb
  app/services/feature_flag.rb
  app/views/provider_interface/interviews/cancel.html.erb
  app/views/provider_interface/interviews/index.html.erb
  app/views/provider_interface/interviews/new.html.erb
  app/views/provider_interface/interviews/review_cancel.html.erb
  config/locales/application_states.yml
  config/routes.rb
  db/migrate/20210113121730_add_interviews_cancellation_reason.rb
  db/schema.rb
  docs/domain-model.png
  spec/components/provider_interface/application_choice_header_component_spec.rb
  spec/components/provider_interface/application_timeline_component_spec.rb
  spec/factories.rb
  spec/services/application_state_change_spec.rb
  spec/services/cancel_interview_spec.rb
  spec/services/create_interview_spec.rb
  spec/system/provider_interface/provider_makes_an_offer_spec.rb
  spec/system/provider_interface/provider_makes_changes_before_offer_spec.rb
  spec/system/provider_interface/provider_manages_application_interviews_spec.rb
  spec/system/provider_interface/provider_responds_to_application_spec.rb
Labels: ProVendor

#3863 Refactor and speed up Mailer specs
  .rubocop.yml
  app/views/candidate_mailer/ucas_match_resolved_on_ucas_email.text.erb
  spec/factories.rb
  spec/mailers/authentication_mailer_spec.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_referee_mails_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/candidate_mailer_ucas_match_emails_spec.rb
  spec/mailers/candidate_mailer_ucas_match_initial_email_spec.rb
  spec/mailers/candidate_mailer_ucas_match_reminder_email_spec.rb
  spec/mailers/provider_mailer_spec.rb
  spec/mailers/referee_mailer_spec.rb
  spec/support/shared_examples/mailers.rb
Labels: Core

#3868 Skylight tweaks: add sidekiq, track git SHA
  config/skylight.yml
Labels: Core

#3867 Stub geocoder requests in our specs
  spec/rails_helper.rb
  spec/support/geocode_test_helper.rb
Labels: Candidate

#3872 SKYLIGHT_ENABLE as string parameter
  azure/pipelines/build.yml
  azure/pipelines/release.yml
  azure/pipelines/templates/deploy.yml
  azure/template.json
Labels: DevOps

#3869 Fix feature metrics crash
  app/models/reference_feature_metrics.rb
  app/models/work_history_feature_metrics.rb
  spec/models/reference_feature_metrics_spec.rb
  spec/models/work_history_feature_metrics_spec.rb
Labels: Candidate, Support

#3878 Fix typo in slack notifications locale
  config/locales/slack_notifications.yml
Labels: ProVendor

#3881 Fix pull request template link to Azure DevOps pipeline variable config
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Core

#3849 Extend GetActivityLog to retrieve associated audits for interviews
  app/components/provider_interface/activity_log_event_component.html.erb
  app/components/provider_interface/activity_log_event_component.rb
  app/components/provider_interface/application_timeline_component.rb
  app/lib/activity_log_event.rb
  app/queries/get_activity_log_events.rb
  spec/components/provider_interface/activity_log_event_component_spec.rb
  spec/components/provider_interface/application_timeline_component_spec.rb
  spec/factories.rb
  spec/queries/get_activity_log_events_spec.rb
Labels: ProVendor

#3876 Be explicit about Skylight env in skylight.yml
  config/skylight.yml
Labels: Core

#3820 Add another button on review pages
  app/components/candidate_interface/add_reference_component.html.erb
  app/helpers/view_helper.rb
  app/views/candidate_interface/application_choices/review.html.erb
  app/views/candidate_interface/course_choices/add_another_course/ask.html.erb
  app/views/candidate_interface/degrees/review/show.html.erb
  app/views/candidate_interface/other_qualifications/review/show.html.erb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/volunteering/review/show.html.erb
  app/views/candidate_interface/work_history/review/show.html.erb
  config/locales/application_form/courses.yml
  config/locales/application_form/volunteering.yml
  config/locales/application_form/work_history.yml
  spec/components/candidate_interface/add_reference_component_spec.rb
  spec/system/candidate_interface/entering_details/candidate_edits_work_history_after_completing_the_section_spec.rb
Labels: Candidate

#3893 Pin docker image to alpine 3.12
  Dockerfile
Labels: DevOps

#3886 Feature metric dashboard - fixes reference stats
  app/models/reference_feature_metrics.rb
  spec/models/reference_feature_metrics_spec.rb
Labels: Support

#3894 Add columns for timestamps for feedback_status changes for references
  db/migrate/20210121181602_add_timestamp_columns_to_the_application_reference_table.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3887 Prevent users from submitting gcses as completed with an empty award year
  app/components/candidate_interface/gcse_qualification_review_component.html.erb
  app/components/candidate_interface/gcse_qualification_review_component.rb
  app/controllers/candidate_interface/gcse/review_controller.rb
  app/models/application_qualification.rb
  config/locales/review_application.yml
  spec/components/candidate_interface/gcse_qualification_review_component_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_spec.rb
Labels: Candidate

#3896 Add feature_restructured_work_history boolean to the application form
  db/migrate/20210122102149_add_feature_restructured_work_history_bool_to_application_form.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3901 Add timestamps when a references feedback_status is updated
  app/components/support_interface/reference_with_feedback_component.rb
  app/controllers/support_interface/references_controller.rb
  app/forms/referee_interface/refuse_feedback_form.rb
  app/lib/test_applications.rb
  app/models/application_reference.rb
  app/models/reference_feature_metrics.rb
  app/services/cancel_referee.rb
  app/services/candidate_interface/request_reference.rb
  app/services/request_reference.rb
  app/services/submit_reference.rb
  app/services/support_interface/candidate_journey_tracker.rb
  db/migrate/20210125142659_backfill_new_application_reference_datetime_columns.rb
  db/schema.rb
  spec/factories.rb
  spec/forms/referee_interface/refuse_feedback_form_spec.rb
  spec/models/reference_feature_metrics_spec.rb
  spec/services/cancel_referee_spec.rb
  spec/services/cancel_unsubmitted_application_at_end_of_cycle_spec.rb
  spec/services/submit_reference_spec.rb
  spec/services/support_interface/application_references_export_spec.rb
  spec/services/support_interface/candidate_journey_tracker_spec.rb
  spec/system/support_interface/feature_metrics_dashboard_spec.rb
Labels: Candidate

#3910 Fix typo in migration
  db/migrate/20210125142659_backfill_new_application_reference_datetime_columns.rb
Labels: Candidate

#3911 Use correct path for adding another volunteering role
  app/views/candidate_interface/volunteering/review/show.html.erb
Labels: Candidate

#3912 Fix Support email log search by email address
  app/controllers/support_interface/email_log_controller.rb
  spec/system/support_interface/email_log_spec.rb
Labels: Core

#3905 Migration to add work_history_status column to the application_forms table
  db/migrate/20210125092451_add_work_history_status_to_application_form.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3913 Use the correct enum value in failing migration
  db/migrate/20210125142659_backfill_new_application_reference_datetime_columns.rb
Labels: Candidate

#3897 Email accredited bodies about changes
  app/services/accept_offer.rb
  app/services/decline_offer.rb
  app/services/decline_offer_by_default.rb
  app/services/notifications_list.rb
  app/services/send_new_application_email_to_provider.rb
  app/services/submit_application.rb
  app/services/withdraw_application.rb
  spec/services/accept_offer_spec.rb
  spec/services/decline_offer_by_default_spec.rb
  spec/services/decline_offer_spec.rb
  spec/services/notifications_list_spec.rb
  spec/services/send_new_application_email_to_provider_spec.rb
  spec/services/withdraw_application_spec.rb
Labels: ProVendor

#3914 Final fix for migration
  db/migrate/20210125142659_backfill_new_application_reference_datetime_columns.rb
Labels: Candidate

#3883 Update UCAS matches emails content
  app/mailers/candidate_mailer.rb
  app/mailers/provider_mailer.rb
  app/views/candidate_mailer/ucas_match_initial_email_duplicate_applications.text.erb
  app/views/candidate_mailer/ucas_match_reminder_email_duplicate_applications.text.erb
  app/views/provider_mailer/ucas_match_initial_email_duplicate_applications.text.erb
  app/views/provider_mailer/ucas_match_resolved_on_apply_email.text.erb
  app/views/provider_mailer/ucas_match_resolved_on_ucas_email.text.erb
  config/locales/emails/candidate_mailer.yml
  config/locales/emails/provider_mailer.yml
  spec/mailers/candidate_mailer_ucas_match_initial_email_spec.rb
  spec/mailers/candidate_mailer_ucas_match_reminder_email_spec.rb
  spec/mailers/provider_mailer_spec.rb
  spec/services/ucas_matches/send_ucas_match_emails_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: ProVendor

#3891 R4R Support Dashboard
  app/components/support_interface/reason_for_rejection_dashboard_section_component.html.erb
  app/components/support_interface/reason_for_rejection_dashboard_section_component.rb
  app/components/support_interface/reasons_for_rejection_dashboard_component.html.erb
  app/components/support_interface/reasons_for_rejection_dashboard_component.rb
  app/controllers/support_interface/performance_controller.rb
  app/helpers/view_helper.rb
  app/queries/get_reasons_for_rejection_from_application_choices.rb
  app/views/support_interface/performance/index.html.erb
  app/views/support_interface/performance/reasons_for_rejection.html.erb
  config/routes.rb
  spec/system/support_interface/reasons_for_rejection_dashboard_spec.rb
Labels: Support

#3890 Put locale files in folders per namespace
  app/components/support_interface/reference_with_feedback_component.rb
  config/locales/candidate_interface/application_complete.yml
  config/locales/candidate_interface/application_feedback.yml
  config/locales/candidate_interface/application_form.yml
  config/locales/candidate_interface/apply_from_find.yml
  config/locales/candidate_interface/authentication.yml
  config/locales/candidate_interface/candidate_reference_status.yml
  config/locales/candidate_interface/contact_details.yml
  config/locales/candidate_interface/courses.yml
  config/locales/candidate_interface/degree.yml
  config/locales/candidate_interface/english_foreign_language.yml
  config/locales/candidate_interface/equality_and_diversity.yml
  config/locales/candidate_interface/feedback_form.yml
  config/locales/candidate_interface/find_feedback.yml
  config/locales/candidate_interface/further_information.yml
  config/locales/candidate_interface/gcse.yml
  config/locales/candidate_interface/gcse_details.yml
  config/locales/candidate_interface/new_referee_request.yml
  config/locales/candidate_interface/other_qualification.yml
  config/locales/candidate_interface/personal_details.yml
  config/locales/candidate_interface/personal_statement.yml
  config/locales/candidate_interface/provider_regions.yml
  config/locales/candidate_interface/references.yml
  config/locales/candidate_interface/review_application.yml
  config/locales/candidate_interface/safeguarding.yml
  config/locales/candidate_interface/submit_application.yml
  config/locales/candidate_interface/training_with_a_disability.yml
  config/locales/candidate_interface/volunteering.yml
  config/locales/candidate_interface/work_history.yml
  config/locales/provider_interface/decisions.yml
  config/locales/provider_interface/provider_relationship_permissions.yml
  config/locales/provider_interface/reasons_for_rejection.yml
  config/locales/provider_interface/safeguarding.yml
  config/locales/referee_interface/referee_interface.yml
  config/locales/support_interface/cycles.yml
  config/locales/support_interface/reference_status.yml
  config/locales/support_interface/safeguarding_issues.yml
  config/locales/support_interface/slack_notifications.yml
  config/locales/support_interface/support_interface.yml
  spec/lib/state_change_notifier_spec.rb
Labels: Core

#3932 Ensure incomplete a levels are excluded from the qualifications export
  app/services/support_interface/qualifications_export.rb
  spec/services/support_interface/qualifications_export_spec.rb
Labels: Candidate

#3936 Don't add HESA data to every API response
  app/presenters/vendor_api/single_application_presenter.rb
  spec/presenters/vendor_api/single_application_presenter_spec.rb
Labels: Bug bash 🐞🔨, ProVendor

#3937 Update the R4R percentage tile
  app/components/support_interface/reason_for_rejection_dashboard_section_component.html.erb
  app/components/support_interface/reason_for_rejection_dashboard_section_component.rb
  app/components/support_interface/reasons_for_rejection_dashboard_component.html.erb
  app/components/support_interface/reasons_for_rejection_dashboard_component.rb
  spec/system/support_interface/reasons_for_rejection_dashboard_spec.rb
Labels: Candidate

#3931 "Open all courses" now opens ratified courses too
  app/models/provider.rb
  app/services/open_provider_courses.rb
  app/views/support_interface/providers/courses.html.erb
  spec/services/open_provider_courses_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
Labels: ProVendor

#3944 Update spec for adding volunteering roles
  spec/system/candidate_interface/entering_details/candidate_entering_volunteering_and_school_experience_spec.rb
Labels: Candidate

#3953 Only show Decline by default at row if the date is present
  app/components/support_interface/application_choice_component.rb
  app/services/accept_offer.rb
  spec/components/support_interface/application_choice_component_spec.rb
Labels: ProVendor, Support

#3952 Remove null constraints from application_experiences table
  db/migrate/20210129135146_remove_null_constraints_from_application_experiences.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#3935 Show API-formatted applications in Support
  app/components/support_interface/application_api_representation_component.html.erb
  app/components/support_interface/application_api_representation_component.rb
  app/components/support_interface/application_choice_component.rb
  app/frontend/styles/_syntax-highlighting.scss
  app/frontend/styles/support/_all.scss
  app/lib/allowed_cross_namespace_usage.rb
  spec/system/support_interface/audit_trail_spec.rb
Labels: ProVendor

#3956 Configure teacherTrainingApiBaseUrl
  azure/pipelines/release.yml
Labels: DevOps

#3940 Update UCAS matches dual application resolved on UCAS emails
  app/mailers/candidate_mailer.rb
  app/mailers/provider_mailer.rb
  app/services/ucas_matches/resolve_on_ucas.rb
  app/services/ucas_matches/send_resolved_on_ucas_emails.rb
  app/views/candidate_mailer/ucas_match_reminder_email_multiple_acceptances.text.erb
  app/views/candidate_mailer/ucas_match_resolved_on_ucas_at_our_request_email.text.erb
  app/views/candidate_mailer/ucas_match_resolved_on_ucas_email.text.erb
  app/views/provider_mailer/ucas_match_resolved_on_ucas_email.text.erb
  config/locales/emails/candidate_mailer.yml
  config/locales/emails/provider_mailer.yml
  spec/mailers/candidate_mailer_ucas_match_emails_spec.rb
  spec/mailers/candidate_mailer_ucas_match_initial_email_spec.rb
  spec/mailers/candidate_mailer_ucas_match_reminder_email_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/mailers/previews/provider_mailer_preview.rb
  spec/mailers/provider_mailer_spec.rb
  spec/services/ucas_matches/resolve_on_ucas_spec.rb
  spec/services/ucas_matches/send_resolved_on_ucas_emails_spec.rb
  spec/system/support_interface/docs_spec.rb
  spec/system/ucas_matching/process_matching_data_from_ucas_spec.rb
Labels: ProVendor
