Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2021-05, with the labels that each got.

#4623 Remove application form '_completed' field defaults
  app/components/candidate_interface/complete_section_component.html.erb
  app/components/candidate_interface/complete_section_component.rb
  app/controllers/candidate_interface/application_choices_controller.rb
  app/views/candidate_interface/application_choices/review.html.erb
  app/views/candidate_interface/contact_details/review/show.html.erb
  app/views/candidate_interface/degrees/review/show.html.erb
  app/views/candidate_interface/english_foreign_language/review/show.html.erb
  app/views/candidate_interface/gcse/review/show.html.erb
  app/views/candidate_interface/interview_needs/show.html.erb
  app/views/candidate_interface/other_qualifications/review/show.html.erb
  app/views/candidate_interface/personal_details/review/show.html.erb
  app/views/candidate_interface/personal_statement/show.html.erb
  app/views/candidate_interface/restructured_work_history/review/show.html.erb
  app/views/candidate_interface/safeguarding/show.html.erb
  app/views/candidate_interface/subject_knowledge/show.html.erb
  app/views/candidate_interface/training_with_a_disability/show.html.erb
  app/views/candidate_interface/volunteering/review/show.html.erb
  app/views/candidate_interface/work_history/review/show.html.erb
  db/migrate/20210429083515_remove_null_constraints_from_application_forms_table.rb
  db/migrate/20210429084354_remove_defaults_from_application_forms_table.rb
  db/schema.rb
  docs/domain-model.png
  spec/components/candidate_interface/complete_section_component_spec.rb
  spec/services/duplicate_application_shared_examples.rb
  spec/system/candidate_interface/entering_details/add_other_qualification_spec.rb
  spec/system/candidate_interface/entering_details/declare_no_qualification_spec.rb
  spec/system/candidate_interface/entering_details/declare_qualification_not_needed_spec.rb
  spec/system/candidate_interface/entering_details/your_ielts_results_spec.rb
  spec/system/candidate_interface/entering_details/your_toefl_result_spec.rb
Labels: Candidate

#4642 Use correct contact group for StatusCake notifications
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/staging.tfvars
Labels: DevOps, PaaS

#4636 Add Maintenance page
  app/components/service_unavailable_component.html.erb
  app/components/service_unavailable_component.rb
  app/middlewares/service_unavailable_middleware.rb
  app/services/feature_flag.rb
  app/views/errors/service_unavailable.html.erb
  app/views/layouts/error.html.erb
  config/application.rb
  config/locales/service_unavailable.yml
  spec/components/previews/service_unavailable_component_preview.rb
  spec/components/service_unavailable_component_spec.rb
  spec/middlewares/service_unavailable_middleware_spec.rb
Labels: Core

#4644 Run clock and worker apps in Sandbox
  terraform/workspace_variables/sandbox.tfvars
Labels: DevOps, PaaS

#4643 Don't restore Azure sandbox to PaaS sandbox after migration
  .github/workflows/database-restore.yml
Labels: DevOps, PaaS

#4641 Bug: Add missing instance variable
  app/controllers/candidate_interface/volunteering/review_controller.rb
Labels: Bug bash 🐞🔨, Candidate

#4646 Increase sandbox and production app instances and memory
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/sandbox.tfvars
Labels: DevOps, PaaS

#4647 Use default startup command for worker in all env
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/sandbox.tfvars
Labels: DevOps, PaaS

#4577 Add course type parameters to test data generate endpoint
  app/controllers/vendor_api/test_data_controller.rb
  app/services/generate_fake_provider.rb
  app/services/test_provider.rb
  app/services/vendor_api/generate_test_applications_for_provider.rb
  app/views/api_docs/vendor_api_docs/pages/release_notes.md
  app/workers/generate_test_applications_for_courses.rb
  config/vendor-api-experimental.yml
  spec/requests/vendor_api/post_test_data_generate_spec.rb
  spec/services/test_provider_spec.rb
  spec/services/vendor_api/generate_test_applications_for_provider_spec.rb
Labels: API, ProVendor

#4629 Refactor work_history_with_breaks spec
  spec/services/work_history_with_breaks_spec.rb
Labels: ProVendor

#4652 Enable clockwork in prod (PaaS)
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/staging.tfvars
Labels: DevOps, PaaS

#4571 Logging configuration for PaaS
  Gemfile
  Gemfile.lock
  app/lib/logstash_logging.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/semantic_logger.rb
  spec/support/test_helpers/logging_helper.rb
  spec/support_specs/logstash_logging_spec.rb
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
Labels: DevOps, PaaS

#4653 Remove workflow to restore database from Azure
  .github/workflows/database-restore.yml
Labels: DevOps, PaaS

#4649 Don't show withdrawal reasons if choice is not 'offer_withdrawn'
  app/components/candidate_interface/application_dashboard_course_choices_component.rb
  app/components/candidate_interface/course_choices_review_component.rb
  spec/components/candidate_interface/application_dashboard_course_choices_component_spec.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
Labels: Candidate

#4665 Increase statuscake confirmations to 2
  terraform/workspace_variables/production.tfvars
  terraform/workspace_variables/sandbox.tfvars
Labels: DevOps

#4668 Increase memory to 1.5 GB
  terraform/workspace_variables/production.tfvars
Labels: DevOps, PaaS

#4672 Increase app memory to 2GB
  terraform/workspace_variables/production.tfvars
Labels: DevOps, PaaS

#4673 Disable ssh for the web app
  terraform/modules/paas/main.tf
Labels: DevOps, PaaS

#4671 Remove default false for 'safe_guarding_issues_completed' and 'interview_preferences_completed'
  db/migrate/20210506101257_remove_more_defaults_from_application_forms_table.rb
  db/schema.rb
Labels: Candidate

#4657 Remove reference to deleted data migration file
  lib/tasks/data.rake
Labels: Bug bash 🐞🔨

#4676 Increase to 6GB
  terraform/workspace_variables/production.tfvars
Labels: DevOps, PaaS

#4639 Add recruitment cycle year arg to sync
  app/services/teacher_training_public_api/sync_all_providers_and_courses.rb
  spec/services/teacher_training_public_api/sync_all_providers_and_courses_spec.rb
  spec/support/test_helpers/teacher_training_public_api_helper.rb
Labels: ProVendor

#4640 Make it easier for providers to spot gaps in work history in manage
  app/components/work_history_and_unpaid_experience_component.html.erb
  app/components/work_history_and_unpaid_experience_component.rb
  app/components/work_history_and_unpaid_experience_item_component.html.erb
  app/components/work_history_and_unpaid_experience_item_component.rb
  app/components/work_history_component.rb
  app/components/work_history_item_component.rb
  app/services/work_history_with_breaks.rb
  app/views/provider_interface/application_choices/show.html.erb
  spec/components/work_history_and_unpaid_experience_component_spec.rb
  spec/components/work_history_and_unpaid_experience_item_component_spec.rb
  spec/services/work_history_with_breaks_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: ProVendor

#4681 Increase web app instances to 8
  terraform/workspace_variables/production.tfvars
Labels: DevOps, PaaS

#4682 Increase web app instances in qa, staging & sandbox
  terraform/workspace_variables/qa.tfvars
  terraform/workspace_variables/sandbox.tfvars
  terraform/workspace_variables/staging.tfvars
Labels: DevOps, PaaS

#4663 Add Satisfaction Survey Response rate to the Feature Metric Dashboard
  app/models/feature_metrics_dashboard.rb
  app/models/satisfaction_survey_feature_metrics.rb
  app/views/support_interface/performance/feature_metrics_dashboard.html.erb
  spec/models/feature_metrics_dashboard_spec.rb
  spec/models/satisfaction_survey_feature_metrics_spec.rb
  spec/system/support_interface/feature_metrics_dashboard_spec.rb
Labels: Metrics & reporting, Support

#4658 [2-1/3] Remove the subject field from notes: stop reading from subject field
  app/exports/notes_export.yml
  app/services/data_migrations/prefix_note_subject_to_message.rb
  app/services/support_interface/notes_export.rb
  app/views/provider_interface/notes/index.html.erb
  app/views/provider_interface/notes/show.html.erb
  lib/tasks/data.rake
  spec/components/provider_interface/application_timeline_component_spec.rb
  spec/factories/note.rb
  spec/services/data_migrations/prefix_note_subject_to_message_spec.rb
  spec/services/support_interface/notes_export_spec.rb
Labels: ProVendor

#4684 Update sidekiq retries statuscake test name
  terraform/workspace_variables/production.tfvars
Labels: DevOps

#4680 Replace 'onchange' with a JS script in the validation error summary
  app/components/support_interface/validation_errors_summary_component.html.erb
  app/frontend/packs/application-support.js
  app/frontend/packs/sort-by-filter.js
Labels: JavaScript, Support

#4632 Add DeleteApplication service for data deletion requests
  app/services/delete_application.rb
  spec/services/delete_application_spec.rb
Labels: Core, Support

#4578 Report and ignore UCASMatch records with no applications
  app/components/support_interface/ucas_matches_statistics_component.html.erb
  app/models/ucas_match.rb
  app/services/ucas_matches/send_ucas_match_initial_emails_duplicate_applications.rb
  spec/models/ucas_match_spec.rb
  spec/services/ucas_matches/send_ucas_match_initial_emails_duplicate_applications_spec.rb
Labels: ProVendor

#4662 [2-2/3] Remove data migration
  app/services/data_migrations/prefix_note_subject_to_message.rb
  spec/services/data_migrations/prefix_note_subject_to_message_spec.rb
Labels: ProVendor

#4699 Remove paas- prefix from docker image tag
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Dockerfile
Labels: DevOps

#4703 Reduce worker app instances to 2
  terraform/workspace_variables/production.tfvars
Labels: DevOps

#4702 Start writing opened_on_apply_at for courses
  app/controllers/support_interface/course_controller.rb
  app/models/course.rb
  app/services/open_provider_courses.rb
  app/services/teacher_training_public_api/sync_courses.rb
  lib/tasks/local_dev.rake
  spec/factories/course.rb
  spec/models/course_spec.rb
  spec/services/open_provider_courses_spec.rb
  spec/services/teacher_training_public_api/sync_courses_spec.rb
Labels: Core

#4664 Allow up to 20 further conditions of offer
  app/components/provider_interface/conditions_form_component.html.erb
  app/components/provider_interface/conditions_form_component.rb
  app/controllers/provider_interface/offer/conditions_controller.rb
  app/forms/provider_interface/offer_wizard.rb
  app/frontend/styles/_add_another.scss
  app/frontend/styles/application.scss
  app/views/provider_interface/offer/conditions/_form.html.erb
  app/views/provider_interface/offer/conditions/_further_condition.html.erb
  app/views/provider_interface/offer/conditions/edit.html.erb
  app/views/provider_interface/offer/conditions/new.html.erb
  config/locales/provider_interface/make_offer.yml
  spec/components/provider_interface/conditions_form_component_spec.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
  spec/system/provider_interface/change_existing_offer_spec.rb
  spec/system/provider_interface/make_offer_spec.rb
Labels: ProVendor, Provider UI

#4708 Backfill `opened_on_apply_at` for all courses using audits
  app/services/data_migrations/backfill_opened_on_apply_at_from_audits.rb
  config/brakeman.ignore
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_opened_on_apply_at_from_audits_spec.rb
Labels: Core

#4717 Use created_at for `opened_on_apply_at` if audits are missing
  app/services/data_migrations/backfill_opened_on_apply_at_from_audits.rb
  spec/services/data_migrations/backfill_opened_on_apply_at_from_audits_spec.rb
Labels: Core

#4718 Extend work history and unpaid experience to include additional details
  app/components/work_history_and_unpaid_experience_component.html.erb
  app/components/work_history_and_unpaid_experience_component.rb
  app/components/work_history_component.rb
  spec/components/work_history_and_unpaid_experience_component_spec.rb
Labels: ProVendor

#4720 Delete all course audits to reduce table size
  app/models/course.rb
  app/services/data_migrations/backfill_opened_on_apply_at_from_audits.rb
  app/services/data_migrations/delete_all_course_audits.rb
  config/brakeman.ignore
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_opened_on_apply_at_from_audits_spec.rb
  spec/services/data_migrations/delete_all_course_audits_spec.rb
  spec/services/open_provider_courses_spec.rb
Labels: Core

#4719 Remove interviews feature flag
  app/components/provider_interface/application_choice_header_component.html.erb
  app/components/provider_interface/application_choice_header_component.rb
  app/controllers/provider_interface/interview_schedules_controller.rb
  app/controllers/provider_interface/interviews_controller.rb
  app/helpers/navigation_items.rb
  app/services/application_state_change.rb
  app/services/feature_flag.rb
  spec/components/provider_interface/application_choice_header_component_spec.rb
  spec/components/provider_interface/application_timeline_component_spec.rb
  spec/requests/provider_interface/interviews_controller_spec.rb
  spec/services/application_state_change_spec.rb
  spec/services/update_interview_spec.rb
  spec/system/provider_interface/provider_can_view_interview_schedule_spec.rb
  spec/system/provider_interface/provider_manages_application_interviews_spec.rb
Labels: ProVendor

#4729 Trigger builds for main branch
  .github/workflows/build.yml
  .github/workflows/pull_request_checks.yml
Labels: DevOps

#4726 Fix Flakey Provider Interview Schedule Spec
  spec/system/provider_interface/provider_can_view_interview_schedule_spec.rb
Labels: Bug bash 🐞🔨, ProVendor

#4698 Use GovukComponent::Header
  app/components/header_component.html.erb
  app/components/header_component.rb
  app/components/product_header_component.html.erb
  app/components/product_header_component.rb
  app/frontend/styles/_header.scss
  app/views/layouts/_header.html.erb
  app/views/layouts/error.html.erb
  spec/components/header_component_spec.rb
  spec/components/product_header_component_spec.rb
Labels: Components, Core

#4705 Update flow and forms so that references are created after name step
  app/components/candidate_interface/references_review_component.rb
  app/controllers/candidate_interface/references/email_address_controller.rb
  app/controllers/candidate_interface/references/name_controller.rb
  app/controllers/candidate_interface/references/type_controller.rb
  app/forms/candidate_interface/reference/referee_name_form.rb
  app/forms/candidate_interface/reference/referee_type_form.rb
  app/views/candidate_interface/references/email_address/new.html.erb
  app/views/candidate_interface/references/name/new.html.erb
  app/views/candidate_interface/references/type/_shared_form.html.erb
  config/routes.rb
  spec/components/candidate_interface/references_review_component_spec.rb
  spec/forms/candidate_interface/reference/referee_name_form_spec.rb
  spec/forms/candidate_interface/reference/referee_type_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/references/candidate_adding_incomplete_referees_spec.rb
  spec/system/candidate_interface/references/candidate_adding_referees_in_sandbox_spec.rb
  spec/system/candidate_interface/references/candidate_adds_a_new_reference_spec.rb
  spec/system/candidate_interface/references/candidate_receives_feedback_from_their_reference_requests_spec.rb
  spec/system/candidate_interface/references/candidate_replaces_reference_after_applying_again_spec.rb
  spec/system/candidate_interface/references/candidate_views_reference_history_spec.rb
Labels: Candidate

#4716 Add an expanded Qualifications export
  app/services/feature_flag.rb
  app/services/support_interface/expanded_qualifications_export.rb
  app/services/support_interface/qualifications_export.rb
  spec/services/support_interface/expanded_qualifications_export_spec.rb
  spec/services/support_interface/qualifications_export_spec.rb
Labels: Metrics & reporting

#4730 Add export type to notifications exports
  app/services/data_api/tad_export.rb
  app/services/data_migrations/specify_export_type_for_notification_exports.rb
  app/services/data_migrations/specify_export_type_for_tad_exports.rb
  config/clock.rb
  lib/tasks/data.rake
  spec/requests/data_api/tad_latest_spec.rb
  spec/requests/data_api/tad_single_export_spec.rb
  spec/services/data_migrations/specify_export_type_for_notification_exports_spec.rb
  spec/services/data_migrations/specify_export_type_for_tad_exports_spec.rb
Labels: ProVendor

#4707 Append custom messages to Semantic Logger
  app/controllers/api_docs/api_docs_controller.rb
  app/controllers/application_controller.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/content_controller.rb
  app/controllers/candidate_interface/sign_in_controller.rb
  app/controllers/candidate_interface/sign_up_controller.rb
  app/controllers/integrations/notify_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/referee_interface/reference_controller.rb
  app/controllers/support_interface/support_interface_controller.rb
  app/controllers/vendor_api/vendor_api_controller.rb
  app/lib/log_query_params.rb
  app/lib/request_query_params.rb
  app/services/candidate_interface/sign_in_candidate.rb
  config/initializers/semantic_logger.rb
  spec/support_specs/request_query_params_spec.rb
Labels: Core

#4739 Use blue-green deployment strategy for worker apps
  terraform/modules/paas/main.tf
Labels: DevOps

#4746 Add selected boolean to the references table
  db/migrate/20210515213413_add_selected_boolean_to_application_reference.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#4722 Link back to personal details review page when editing
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/views/candidate_interface/personal_details/languages/edit.html.erb
  app/views/candidate_interface/personal_details/name_and_dob/edit.html.erb
  app/views/candidate_interface/personal_details/nationalities/edit.html.erb
  app/views/candidate_interface/personal_details/right_to_work_or_study/edit.html.erb
Labels: Bug bash 🐞🔨, Candidate

#4756 Stop clock container before starting new deployment
  .github/workflows/deploy.yml
Labels: DevOps

#4759 File PG::QueryCanceled errors in Skylight against the right controller action
  app/controllers/application_controller.rb
  app/controllers/data_api/tad_data_exports_controller.rb
  app/controllers/register_api/applications_controller.rb
  app/controllers/vendor_api/vendor_api_controller.rb
Labels: Core

#4712 Allow Providers and Courses to be synced incrementally
  app/controllers/support_interface/tasks_controller.rb
  app/models/teacher_training_public_api/sync_check.rb
  app/services/teacher_training_public_api/sync_all_providers_and_courses.rb
  app/services/teacher_training_public_api/sync_courses.rb
  app/services/teacher_training_public_api/sync_provider.rb
  app/views/support_interface/tasks/index.html.erb
  app/workers/teacher_training_public_api/full_sync_all_providers_and_courses_worker.rb
  app/workers/teacher_training_public_api/incremental_sync_all_providers_and_courses_worker.rb
  config/clock.rb
  spec/services/teacher_training_public_api/sync_all_providers_and_courses_spec.rb
  spec/services/teacher_training_public_api/sync_courses_spec.rb
  spec/services/teacher_training_public_api/sync_provider_spec.rb
  spec/support/test_helpers/teacher_training_public_api_helper.rb
  spec/system/find_sync/syncing_providers_spec.rb
  spec/system/support_interface/provider_sync_courses_spec.rb
  spec/system/support_interface/providers_and_courses_spec.rb
  spec/system/teacher_training_public_api/study_mode_changes_spec.rb
  spec/system/teacher_training_public_api/sync_course_spec.rb
  spec/system/teacher_training_public_api/sync_provider_spec.rb
  spec/system/teacher_training_public_api/sync_site_spec.rb
  spec/workers/teacher_training_public_api/full_sync_all_providers_and_courses_worker_spec.rb
  spec/workers/teacher_training_public_api/incremental_sync_all_providers_and_courses_worker_spec.rb
Labels: Core

#4757 Fix bug on Previous Unsubmitted Application Review
  app/helpers/view_helper.rb
  spec/helpers/view_helper_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#4696 Offer another course for pending conditions choices
  app/components/support_interface/application_choice_component.html.erb
  app/components/support_interface/application_choice_component.rb
  app/controllers/support_interface/application_forms/application_choices/base_controller.rb
  app/controllers/support_interface/application_forms/application_choices/change_offered_course_controller.rb
  app/controllers/support_interface/application_forms/application_choices/reinstate_declined_offer_controller.rb
  app/controllers/support_interface/application_forms/application_choices_controller.rb
  app/forms/support_interface/application_forms/pick_course_form.rb
  app/forms/support_interface/application_forms/update_offered_course_option_form.rb
  app/services/feature_flag.rb
  app/views/support_interface/application_forms/application_choices/change_offered_course/change_offered_course_search.html.erb
  app/views/support_interface/application_forms/application_choices/change_offered_course/confirm_offered_course_option.html.erb
  app/views/support_interface/application_forms/application_choices/change_offered_course/offered_course_options.html.erb
  app/views/support_interface/application_forms/application_choices/reinstate_declined_offer/confirm_reinstate_offer.html.erb
  app/views/support_interface/application_forms/courses/new.html.erb
  config/locales/support_interface/support_interface.yml
  config/routes.rb
  spec/components/support_interface/application_choice_component_spec.rb
  spec/forms/support_interface/application_forms/pick_course_form_spec.rb
  spec/forms/support_interface/application_forms/update_offered_course_option_form_spec.rb
  spec/system/support_interface/change_offered_course_for_a_submitted_application_spec.rb
  spec/system/support_interface/reinstate_offer_to_declined_course_choice_spec.rb
Labels: Candidate

#4764 Add references completed boolean to the application forms table
  db/migrate/20210518113512_add_references_completed_boolean_to_application_forms.rb
  db/schema.rb
  docs/domain-model.png
Labels: Candidate

#4750 Support interface tweaks
  app/components/when_emails_are_sent_component.html.erb
  app/frontend/styles/_section.scss
  app/frontend/styles/provider/_masthead.scss
  app/views/support_interface/data_exports/directory.html.erb
  app/views/support_interface/data_exports/history.html.erb
  app/views/support_interface/performance/index.html.erb
  app/views/support_interface/settings/cycles.html.erb
  app/views/support_interface/support_users/index.html.erb
  app/views/support_interface/validation_errors/index.html.erb
  spec/system/support_interface/data_directory_spec.rb
Labels: Support

#4666 Let support users change conditions on accepted applications
  app/components/support_interface/application_choice_component.rb
  app/components/support_interface/conditions_component.html.erb
  app/components/support_interface/conditions_component.rb
  app/controllers/support_interface/application_choice_conditions_controller.rb
  app/forms/support_interface/conditions_form.rb
  app/services/update_accepted_offer_conditions.rb
  app/views/support_interface/application_choice_conditions/confirm_make_unconditional.html.erb
  app/views/support_interface/application_choice_conditions/edit.html.erb
  config/locales/support_interface/support_interface.yml
  config/routes.rb
  spec/forms/support_interface/conditions_form_spec.rb
  spec/system/support_interface/change_offer_conditions_spec.rb
Labels: Support

#4754 JS enhancements for "Add another" further conditions
  .github/workflows/build.yml
  README.md
  app/components/provider_interface/conditions_form_component.html.erb
  app/forms/provider_interface/offer_wizard.rb
  app/frontend/packs/application-provider.js
  app/frontend/packs/further_conditions/add.js
  app/frontend/packs/further_conditions/assignIndexBasedValues.js
  app/frontend/packs/further_conditions/constants.js
  app/frontend/packs/further_conditions/index.js
  app/frontend/packs/further_conditions/index.spec.js
  app/frontend/packs/further_conditions/remove.js
  app/frontend/packs/further_conditions/updateAddButtonVisibility.js
  app/frontend/styles/_add_another.scss
  app/views/provider_interface/offer/conditions/_form.html.erb
  app/views/provider_interface/offer/conditions/_further_condition.html.erb
  config/locales/provider_interface/make_offer.yml
  spec/components/provider_interface/conditions_form_component_spec.rb
  spec/support/capybara.rb
  spec/support/webmock.rb
  spec/system/provider_interface/make_offer_spec.rb
  spec/system/provider_interface/set_offer_conditions_js_spec.rb
Labels: ProVendor, Provider UI

#4771 Add redirect to application feedback form
  app/controllers/candidate_interface/application_feedback_controller.rb
Labels: Bug bash 🐞🔨, Candidate

#4776 Add ADR for JS system specs
  adr/0019-js-system-specs.md
Labels: Documentation

#4783 Remove unused require statement for csv
  app/services/ucas_matching/matching_data_file.rb
Labels: ProVendor

#4789 Remove MakeAnOffer and ChangeAnOffer services
  app/forms/provider_interface/offer_wizard.rb
  app/forms/support_interface/conditions_form.rb
  app/helpers/checkbox_options_helper.rb
  app/lib/test_applications.rb
  app/services/change_an_offer.rb
  app/services/make_an_offer.rb
  app/services/make_offer.rb
  app/views/provider_interface/decisions/confirm_offer.html.erb
  spec/components/previews/provider_interface/offer_summary_component_preview.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
  spec/helpers/checkbox_options_helper_spec.rb
  spec/services/change_an_offer_spec.rb
  spec/services/make_an_offer_spec.rb
  spec/system/support_interface/audit_trail_spec.rb
Labels: ProVendor

#4769 Stop auditing site changes; remove existing records
  app/models/site.rb
  app/services/data_migrations/delete_all_course_audits.rb
  app/services/data_migrations/delete_all_site_audits.rb
  config/brakeman.ignore
  lib/tasks/data.rake
  spec/services/data_migrations/delete_all_course_audits_spec.rb
  spec/services/data_migrations/delete_all_site_audits_spec.rb
  spec/system/provider_interface/provider_history_spec.rb
Labels: Core

#4781 implement course subject filter
  app/components/filter_component.html.erb
  app/components/filter_component.rb
  app/frontend/packs/application-provider.js
  app/frontend/packs/components/checkbox_search_filter.js
  app/frontend/packs/polyfills.js
  app/frontend/styles/application-provider.scss
  app/frontend/styles/components/_checkbox_search_filter.scss
  app/models/course.rb
  app/models/provider_interface/provider_applications_filter.rb
  app/services/filter_application_choices_for_providers.rb
  lib/tasks/local_dev.rake
  spec/models/course_spec.rb
  spec/models/provider_interface/provider_applications_filter_spec.rb
  spec/services/filter_application_choices_for_providers_spec.rb
  spec/system/provider_interface/provider_application_filter_by_subject_spec.rb
Labels: ProVendor

#4797 Wrap Rspec include & exclude pattern in quotes
  .github/workflows/build.yml
Labels: DevOps

#4728 Install nodejs & yarn for local development in docker container instance
  Makefile
Labels: DevOps

#4744 Update back links across Referee flow
  app/components/candidate_interface/references_review_component.rb
  app/components/candidate_interface/unsubmitted_reference_review_component.rb
  app/controllers/candidate_interface/references/base_controller.rb
  app/controllers/candidate_interface/references/email_address_controller.rb
  app/controllers/candidate_interface/references/name_controller.rb
  app/controllers/candidate_interface/references/relationship_controller.rb
  app/controllers/candidate_interface/references/start_controller.rb
  app/controllers/candidate_interface/references/type_controller.rb
  app/forms/candidate_interface/reference/referee_name_form.rb
  app/forms/candidate_interface/reference/referee_type_form.rb
  app/views/candidate_interface/references/candidate_name/new.html.erb
  app/views/candidate_interface/references/email_address/edit.html.erb
  app/views/candidate_interface/references/email_address/new.html.erb
  app/views/candidate_interface/references/name/edit.html.erb
  app/views/candidate_interface/references/name/new.html.erb
  app/views/candidate_interface/references/relationship/edit.html.erb
  app/views/candidate_interface/references/relationship/new.html.erb
  app/views/candidate_interface/references/start/show.html.erb
  app/views/candidate_interface/references/type/edit.html.erb
  app/views/candidate_interface/references/type/new.html.erb
  config/routes.rb
  spec/components/candidate_interface/unsubmitted_reference_review_component_spec.rb
  spec/forms/candidate_interface/reference/referee_name_form_spec.rb
  spec/forms/candidate_interface/reference/referee_type_form_spec.rb
  spec/system/candidate_interface/references/backlinks_spec.rb
  spec/system/candidate_interface/references/candidate_adding_incomplete_referees_spec.rb
  spec/system/candidate_interface/references/candidate_requests_a_reference_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#4806 Show the locations filter section for users which belong to one provider
  app/models/provider_interface/provider_applications_filter.rb
  spec/models/provider_interface/provider_applications_filter_spec.rb
Labels: ProVendor

#4807 Filter ValidationErrors by service to display candidate ones
  app/controllers/support_interface/validation_errors/candidate_controller.rb
  app/controllers/support_interface/validation_errors/user_controller.rb
  app/queries/validation_error_summary_query.rb
  spec/components/previews/support_interface/validation_errors_component_preview.rb
  spec/queries/validation_error_summary_query_spec.rb
Labels: Support

#4809 Handle 404s for resources that are not html format
  app/controllers/candidate_interface/errors_controller.rb
  app/controllers/errors_controller.rb
  app/controllers/provider_interface/errors_controller.rb
  app/controllers/support_interface/errors_controller.rb
Labels: Core

#4812 Support: Content tweaks and layout fixes for changing courses
  app/components/support_interface/application_choice_component.html.erb
  app/controllers/support_interface/application_forms/application_choices/change_offered_course_controller.rb
  app/models/application_choice.rb
  app/views/support_interface/application_forms/application_choices/change_offered_course/change_offered_course_search.html.erb
  app/views/support_interface/application_forms/application_choices/change_offered_course/confirm_offered_course_option.html.erb
  app/views/support_interface/application_forms/application_choices/change_offered_course/offered_course_options.html.erb
  app/views/support_interface/application_forms/application_choices/confirm_revert_rejection.html.erb
  app/views/support_interface/application_forms/application_choices/reinstate_declined_offer/confirm_reinstate_offer.html.erb
  app/views/support_interface/application_forms/courses/new.html.erb
  app/views/support_interface/application_forms/courses/new_search.html.erb
  spec/components/support_interface/application_choice_component_spec.rb
  spec/models/application_choice_spec.rb
  spec/system/support_interface/add_course_to_submitted_application_spec.rb
  spec/system/support_interface/change_offered_course_for_a_submitted_application_spec.rb
Labels: Content, Support

#4778 Allow the candidate to receive > 2 references
  app/components/candidate_interface/add_reference_component.html.erb
  app/components/candidate_interface/references_review_component.rb
  app/models/application_form.rb
  app/services/reference_actions_policy.rb
  app/services/submit_reference.rb
  spec/services/submit_reference_spec.rb
  spec/spec_helper.rb
  spec/system/candidate_interface/references/reference_selection/candidate_can_continuously_request_references_spec.rb
Labels: Candidate

#4800 Use govuk mixins for notification banner warning variant
  app/frontend/styles/_notification_banner.scss
Labels: CSS, Core

#4799 Use the correct role value for success and warning flash components
  app/components/flash_message_component.html.erb
  app/components/flash_message_component.rb
  spec/components/flash_message_component_spec.rb
Labels: Core

#4827 Add further sanitization to double science GCSE
  app/forms/candidate_interface/science_gcse_grade_form.rb
  spec/forms/candidate_interface/science_gcse_grade_form_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#4793 Add initial version of select references flow
  app/controllers/candidate_interface/references/review_controller.rb
  app/controllers/candidate_interface/references/selection_controller.rb
  app/forms/candidate_interface/reference/selection_form.rb
  app/forms/candidate_interface/section_complete_form.rb
  app/models/application_form.rb
  app/models/application_reference.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/references/review/show_for_reference_selection.html.erb
  app/views/candidate_interface/references/selection/new.html.erb
  config/locales/candidate_interface/references.yml
  config/locales/en.yml
  config/routes.rb
  spec/system/candidate_interface/references/reference_selection/candidate_selects_two_references_spec.rb
Labels: Candidate

#4833 Update production db to medium-ha-11
  terraform/workspace_variables/production.tfvars
Labels: DevOps

#4834 Bring back unauthorised edits check in DetectInvariants
  app/workers/detect_invariants.rb
  spec/workers/detect_invariants_spec.rb
Labels: Core

#4826 Backfill the `feature_restructured_work_history` boolean
  app/services/data_migrations/backfill_restuctured_work_history_boolean.rb
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_restuctured_work_history_boolean_spec.rb
Labels: Candidate

#4837 Bug: candidate can change their course to one already on their application
  app/controllers/candidate_interface/course_choices/course_selection_controller.rb
  spec/system/candidate_interface/course_selection/candidate_edits_course_choices_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#4810 Add validation to ensure max allowed number of conditions is never ex…
  app/forms/provider_interface/offer_wizard.rb
  config/locales/provider_interface/make_offer.yml
  spec/forms/provider_interface/offer_wizard_spec.rb
Labels: Offers, ProVendor

#4829 Make filters use provider, location, year etc. of *current* course
  app/components/provider_interface/application_card_component.rb
  app/controllers/provider_interface/application_choices_controller.rb
  app/services/filter_application_choices_for_providers.rb
  spec/components/provider_interface/application_card_component_spec.rb
  spec/services/filter_application_choices_for_providers_spec.rb
Labels: ProVendor

#4842 Add further sanitization to the Science GCSE form mk2
  app/forms/candidate_interface/science_gcse_grade_form.rb
  app/models/application_qualification.rb
  spec/forms/candidate_interface/science_gcse_grade_form_spec.rb
  spec/models/application_qualification_spec.rb
Labels: Bug bash 🐞🔨, Candidate

#4850 Export path in Dockerfile to avoid having to type full path
  Dockerfile
Labels: Core

#4840 Start writing to offer and conditions tables when making and changing offers
  app/models/offer.rb
  app/models/offer_condition.rb
  app/services/change_offer.rb
  app/services/conditions_not_met.rb
  app/services/confirm_offer_conditions.rb
  app/services/make_offer.rb
  app/services/reinstate_conditions_met.rb
  app/services/reinstate_pending_conditions.rb
  app/services/update_accepted_offer_conditions.rb
  app/services/update_offer_conditions.rb
  spec/factories/application_choice.rb
  spec/forms/support_interface/conditions_form_spec.rb
  spec/models/offer_condition_spec.rb
  spec/requests/vendor_api/post_conditions_met_spec.rb
  spec/requests/vendor_api/post_conditions_not_met_spec.rb
  spec/services/change_offer_spec.rb
  spec/services/conditions_not_met_spec.rb
  spec/services/confirm_offer_conditions_spec.rb
  spec/services/make_offer_spec.rb
  spec/services/reinstate_conditions_met_spec.rb
  spec/services/reinstate_pending_conditions_spec.rb
  spec/services/update_offer_conditions_spec.rb
Labels: ProVendor

#4839 Backfill data migration to copy old offers to new offer and conditions tables
  app/services/data_migrations/backfill_offer_data.rb
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_offer_data_spec.rb
Labels: Offers

#4853 Destroy application choices with a course from the previous cycle
  app/services/data_migrations/remove_previous_cycles_courses_from_applications_in_the_current_cycle.rb
  lib/tasks/data.rake
  spec/services/data_migrations/remove_previous_cycles_courses_from_applications_in_the_current_cycle_spec.rb
Labels: Candidate

#4855 Correct spelling of DfE Sign-in
  adr/0012-extra-security-for-support.md
  app/views/provider_interface/sessions/authentication_fallback.html.erb
  app/views/support_interface/sessions/authentication_fallback.html.erb
  azure/template.json
Labels: Content
