Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-12, with the labels that each got.

#7623 Stop using set-output in check_sp workflow
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/pull_request_checks.yml
  .gitignore
Labels: DevOps, deploy, github_actions

#7751 655 Upload/download db backup with azcopy
  .github/workflows/database-backup.yml
  .github/workflows/restore-production-snapshot.yml
  bin/download-nightly-backup
Labels: DevOps, github_actions

#7764 Convert the v1.2 candidate API over to using standard `updated_at`s
  app/components/support_interface/application_card_component.rb
  app/components/support_interface/application_summary_component.rb
  app/components/support_interface/candidates_table_component.html.erb
  app/components/support_interface/candidates_table_component.rb
  app/services/application_form_state_inferrer.rb
  app/services/application_state_change.rb
  app/services/candidate_api/serializers/v1_1.rb
  app/services/candidate_api/serializers/v1_2.rb
  app/services/candidate_flow.rb
  app/services/support_interface/application_references_export.rb
  app/services/support_interface/applications_export.rb
  app/services/support_interface/equality_and_diversity_export.rb
  app/services/support_interface/persona_export.rb
  app/views/support_interface/docs/candidate_flow.html.erb
  spec/models/application_form_spec.rb
  spec/models/performance_statistics_spec.rb
  spec/requests/candidate_api/get_candidates_v1_1_spec.rb
  spec/requests/candidate_api/get_candidates_v1_2_spec.rb
  spec/services/application_form_state_inferrer_spec.rb
  spec/services/support_interface/application_references_export_spec.rb
  spec/system/candidate_api/candidate_api_application_state_change_triggers_update_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: deploy

#7771 Relax rules for changing offer conditions on support
  app/components/support_interface/application_choice_component.rb
  spec/components/support_interface/application_choice_component_spec.rb
Labels: deploy

#7773 Update GIT links
  config/locales/en.yml
  spec/mailers/candidate_mailer_withdrawn_on_request_spec.rb
Labels: deploy

#7782 Reduce content in Success banner
  app/components/candidate_interface/application_dashboard_guidance_component.html.erb
  app/controllers/candidate_interface/feedback_form_controller.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_and_reviews_equality_and_diversity_responses_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_and_reviews_rejection_reasons_from_previous_applications_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_and_views_redesigned_rejection_reasons_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_spec.rb
  spec/system/candidate_interface/feedback/candidate_completes_the_feedback_form_spec.rb
  spec/system/candidate_interface/references/candidate_submits_a_duplicate_application_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_and_prefills_application_in_sandbox_spec.rb
  spec/system/candidate_interface/submitting/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
Labels: deploy
