Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-02, with the labels that each got.

#6479 Review api validations
  app/controllers/vendor_api/interviews_controller.rb
  app/controllers/vendor_api/notes_controller.rb
  app/controllers/vendor_api/withdraw_or_decline_offer_controller.rb
  app/services/create_note.rb
  app/services/decline_or_withdraw_application.rb
  spec/requests/vendor_api/v1.1/create_notes_spec.rb
  spec/requests/vendor_api/v1.1/post_cancel_interview_spec.rb
  spec/requests/vendor_api/v1.1/post_confirm_deferred_offer_spec.rb
  spec/requests/vendor_api/v1.1/post_create_interview_spec.rb
  spec/requests/vendor_api/v1.1/post_update_interview_spec.rb
  spec/services/create_note_spec.rb
  spec/services/decline_or_withdraw_application_spec.rb
Labels: ProVendor

#6477 Implement versioning api documentation
  app/controllers/api_docs/vendor_api_docs/reference_controller.rb
  app/lib/allowed_cross_namespace_usage.rb
  app/presenters/api_docs/api_reference.rb
  app/views/api_docs/vendor_api_docs/reference/reference.html.erb
  config/routes.rb
  spec/requests/api_docs/reference_spec.rb
Labels: deploy

#6487 [514] Remove research environment
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  Makefile
  app/components/utility/phase_banner_component.rb
  app/frontend/styles/_header.scss
  app/lib/hosting_environment.rb
  docs/manual-deployment.md
  terraform/workspace_variables/research.tfvars.json
  terraform/workspace_variables/research_backend.tfvars
Labels: DevOps

#6452 Add pagination to v1.1 of the Vendor API
  app/controllers/vendor_api/applications_controller.rb
  app/lib/vendor_api.rb
  app/lib/vendor_api/changes/application_meta.rb
  app/lib/vendor_api/changes/pagination.rb
  app/lib/vendor_api/changes/retrieve_applications.rb
  app/lib/vendor_api/changes/retrieve_single_application.rb
  app/presenters/concerns/api_meta.rb
  app/presenters/concerns/pagination_api_data.rb
  app/presenters/vendor_api/meta_presenter.rb
  app/presenters/vendor_api/multiple_applications_presenter.rb
  app/presenters/vendor_api/single_application_presenter.rb
  spec/presenters/vendor_api/v1.1/multiple_applications_presenter_spec.rb
  spec/requests/vendor_api/v1.1/get_multiple_applications_spec.rb
Labels: ProVendor

#6473 GIT links audit plus style changes
  app/components/candidate_interface/apply_again_call_to_action_component.html.erb
  app/views/candidate_interface/decisions/decline_offer.html.erb
  app/views/candidate_interface/decisions/withdraw.html.erb
  app/views/candidate_interface/decisions/withdrawal_feedback.html.erb
  app/views/candidate_interface/degrees/enic/_form_fields.html.erb
  app/views/candidate_interface/degrees/type/new.html.erb
  app/views/candidate_interface/gcse/grade_explanation/_form.html.erb
  app/views/candidate_interface/gcse/type/_form.html.erb
  app/views/candidate_interface/references/start/show.html.erb
  app/views/candidate_interface/shared/_support.html.erb
  app/views/candidate_interface/training_with_a_disability/_form.html.erb
  app/views/candidate_mailer/application_withdrawn_on_request_all_applications_withdrawn.text.erb
  app/views/candidate_mailer/application_withdrawn_on_request_awaiting_decision_only.text.erb
  app/views/candidate_mailer/application_withdrawn_on_request_offers_only.text.erb
  app/views/candidate_mailer/application_withdrawn_on_request_one_offer_one_awaiting_decision.text.erb
  app/views/candidate_mailer/eoc_deadline_reminder.erb
  app/views/candidate_mailer/new_cycle_has_started.erb
  app/views/content/accessibility.md
  app/views/content/terms_candidate.md
  spec/system/candidate_interface/apply_again/candidate_applies_again_after_apply_1_deadline_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_withdraws_spec.rb
Labels: deploy

#6498 Update the public roadmap copy
  app/views/content/roadmap.md
  config/locales/en.yml
  spec/system/provider_interface/provider_edits_organisation_permissions_spec.rb
Labels: deploy

#6524 Add weekly cache refresh workflow
  .github/workflows/build-nocache.yml
Labels: DevOps

#6519 4330 remove fraud language from classes and copy
  app/controllers/support_interface/duplicate_matches_controller.rb
  app/forms/support_interface/block_submission_form.rb
  app/forms/support_interface/remove_access_form.rb
  app/forms/support_interface/unblock_submission_form.rb
  app/models/candidate.rb
  app/models/duplicate_match.rb
  app/queries/get_duplicate_matches.rb
  app/services/data_migrations/fixup_candidates_submission_blocked.rb
  app/services/data_migrations/fixup_single_candidate_duplicate_matches.rb
  app/services/data_migrations/remove_duplicate_matching_feature_flag.rb
  app/services/duplicate_match_block_submissions.rb
  app/services/duplicate_match_send_email.rb
  app/services/update_duplicate_matches.rb
  app/workers/update_duplicate_matches_worker.rb
  config/clock.rb
  config/locales/emails/candidate_mailer.yml
  lib/tasks/data.rake
  lib/tasks/local_dev.rake
  spec/components/support_interface/duplicate_matches_candidates_table_component_spec.rb
  spec/components/support_interface/duplicate_matches_resolve_component_spec.rb
  spec/components/support_interface/duplicate_matches_table_component_spec.rb
  spec/factories/duplicate_match.rb
  spec/forms/support_interface/block_submission_form_spec.rb
  spec/forms/support_interface/remove_access_form_spec.rb
  spec/forms/support_interface/unblock_submission_form_spec.rb
  spec/queries/get_duplicate_matches_spec.rb
  spec/services/data_migrations/fixup_candidates_submission_blocked_spec.rb
  spec/services/data_migrations/fixup_single_candidate_duplicate_matches_spec.rb
  spec/services/data_migrations/remove_duplicate_matching_feature_flag_spec.rb
  spec/services/duplicate_match_block_submissions_spec.rb
  spec/services/duplicate_match_send_email_spec.rb
  spec/services/support_interface/send_duplicate_match_email_spec.rb
  spec/services/update_duplicate_matches_spec.rb
  spec/system/candidate_interface/references/candidate_submits_a_duplicate_application_spec.rb
  spec/system/support_interface/duplicate_matches_spec.rb
  spec/system/support_interface/edit_candidate_account_status_spec.rb
  spec/workers/update_duplicate_matches_worker_spec.rb
Labels: deploy

#6533 Amend offer validations to prepare for Apply 2 multiple applications
  app/models/candidate.rb
  app/services/offer_validations.rb
  spec/models/candidate_spec.rb
  spec/services/offer_validations_spec.rb
Labels: deploy

#6512 Style edits emails
  app/components/candidate_interface/offers_call_to_action_component.rb
  app/views/authentication_mailer/sign_in_email.text.erb
  app/views/authentication_mailer/sign_in_without_account_email.text.erb
  app/views/authentication_mailer/sign_up_email.text.erb
  app/views/candidate_mailer/_rejected_by_default_intro.text.erb
  app/views/candidate_mailer/application_rejected_all_applications_rejected.text.erb
  app/views/candidate_mailer/application_rejected_awaiting_decision_only.text.erb
  app/views/candidate_mailer/application_rejected_offers_only.text.erb
  app/views/candidate_mailer/application_rejected_one_offer_one_awaiting_decision.text.erb
  app/views/candidate_mailer/application_withdrawn_on_request_all_applications_withdrawn.text.erb
  app/views/candidate_mailer/application_withdrawn_on_request_awaiting_decision_only.text.erb
  app/views/candidate_mailer/application_withdrawn_on_request_offers_only.text.erb
  app/views/candidate_mailer/application_withdrawn_on_request_one_offer_one_awaiting_decision.text.erb
  app/views/candidate_mailer/apply_again_call_to_action.text.erb
  app/views/candidate_mailer/changed_offer.text.erb
  app/views/candidate_mailer/chase_candidate_decision.text.erb
  app/views/candidate_mailer/conditions_met.text.erb
  app/views/candidate_mailer/conditions_not_met.text.erb
  app/views/candidate_mailer/decline_last_application_choice.text.erb
  app/views/candidate_mailer/declined_by_default.text.erb
  app/views/candidate_mailer/declined_by_default_with_rejections.text.erb
  app/views/candidate_mailer/declined_by_default_without_rejections.text.erb
  app/views/candidate_mailer/deferred_offer.text.erb
  app/views/candidate_mailer/deferred_offer_reminder.text.erb
  app/views/candidate_mailer/eoc_deadline_reminder.erb
  app/views/candidate_mailer/find_another_course.text.erb
  app/views/candidate_mailer/find_has_opened.erb
  app/views/candidate_mailer/interview_cancelled.text.erb
  app/views/candidate_mailer/interview_updated.text.erb
  app/views/candidate_mailer/new_cycle_has_started.erb
  app/views/candidate_mailer/new_interview.text.erb
  app/views/candidate_mailer/new_offer/decisions_pending.text.erb
  app/views/candidate_mailer/new_offer/multiple_offers.text.erb
  app/views/candidate_mailer/new_offer/single_offer.text.erb
  app/views/candidate_mailer/offer_accepted.text.erb
  app/views/candidate_mailer/offer_withdrawn.text.erb
  app/views/candidate_mailer/reinstated_offer.text.erb
  app/views/candidate_mailer/unconditional_offer_accepted.text.erb
  app/views/candidate_mailer/withdraw_last_application_choice.text.erb
  app/views/referee_mailer/reference_cancelled_email.text.erb
  app/views/referee_mailer/reference_confirmation_email.text.erb
  app/views/referee_mailer/reference_request_email.text.erb
  app/views/support_mailer/fallback_sign_in_email.text.erb
  spec/components/candidate_interface/offers_call_to_action_component_spec.rb
  spec/mailers/authentication_mailer_spec.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_receives_rejection_email_spec.rb
  spec/system/candidate_interface/references/candidate_requests_a_reference_spec.rb
  spec/system/candidate_interface/references/candidate_reviews_references_spec.rb
Labels: deploy

#6538 Resolve deprecated `Redis.current` warning
  app/lib/state_stores/redis_store.rb
  app/models/teacher_training_public_api/sync_check.rb
  spec/lib/wizard_state_stores/redis_store_spec.rb
Labels: deploy

#6537 Release Vendor API version 1.1 to sandbox
  app/lib/vendor_api.rb
  app/lib/vendor_api_specification.rb
Labels: deploy

#6348 Ministerial reports fixes and improvements
  app/lib/ministerial_report.rb
  app/models/data_export.rb
  app/services/publications/compare_ministerial_reports.rb
  app/services/support_interface/ministerial_report_applications_export.rb
  app/services/support_interface/ministerial_report_candidates_export.rb
  docs/domain-model.png
  lib/tasks/report_utils.rake
  spec/models/publications/monthly_statistics/by_age_group_spec.rb
  spec/models/publications/monthly_statistics/by_area_spec.rb
  spec/models/publications/monthly_statistics/by_course_age_group_spec.rb
  spec/models/publications/monthly_statistics/by_course_type_spec.rb
  spec/models/publications/monthly_statistics/by_provider_area_spec.rb
  spec/models/publications/monthly_statistics/by_secondary_subject_spec.rb
  spec/models/publications/monthly_statistics/by_sex_spec.rb
  spec/models/publications/monthly_statistics/by_status_spec.rb
  spec/requests/data_api/ministerial_report_candidates_export_spec.rb
  spec/services/publications/compare_ministerial_reports_spec.rb
  spec/services/support_interface/ministerial_report_applications_export_spec.rb
  spec/services/support_interface/ministerial_report_candidates_export_spec.rb
  spec/support/statistics_test_helper.rb
Labels: Candidate, Metrics & reporting

#6553 Fix content for apply 2
  app/views/candidate_mailer/_still_interested_content.text.erb
Labels: deploy

#6554 Reinstate Rails as main gem dependency
  Gemfile
  Gemfile.lock
Labels: deploy

#6376 Delete review app environments
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
Labels: deploy

#6565 too many email headings
  app/views/authentication_mailer/sign_up_email.text.erb
  app/views/candidate_mailer/application_withdrawn_on_request_offers_only.text.erb
  app/views/candidate_mailer/chase_candidate_decision.text.erb
  app/views/candidate_mailer/chase_reference.text.erb
  app/views/candidate_mailer/chase_reference_again.text.erb
  app/views/candidate_mailer/conditions_met.text.erb
  app/views/candidate_mailer/conditions_not_met.text.erb
  app/views/candidate_mailer/new_referee_request.text.erb
  app/views/candidate_mailer/reference_received.text.erb
  app/views/candidate_mailer/withdraw_last_application_choice.text.erb
  spec/mailers/authentication_mailer_spec.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_referee_mails_spec.rb
Labels: deploy

#6578 Remove docker credentials from terraform
  terraform/modules/paas/main.tf
  terraform/modules/paas/variables.tf
  terraform/terraform.tf
  terraform/variables.tf
Labels: deploy

#6586 4896 email reminders connect the new field to the current applicationreceived setting
  app/services/save_provider_user_notification_preferences.rb
  spec/factories/provider_user_notification_preferences.rb
  spec/services/save_provider_user_notification_preferences_spec.rb
Labels: ProVendor

#6566 4398 apply again after production delete old code
  app/controllers/candidate_interface/after_sign_in_controller.rb
  app/forms/candidate_interface/pick_site_form.rb
  app/mailers/candidate_mailer.rb
  app/models/application_form.rb
  app/services/candidate_interface/add_or_update_course_choice.rb
  app/services/submit_application.rb
  app/views/candidate_interface/application_choices/review.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  app/views/candidate_mailer/_still_interested_content.text.erb
  app/views/candidate_mailer/application_submitted_apply_again.text.erb
  app/views/content/terms_candidate.md
  config/locales/application_states.yml
  config/locales/emails/candidate_mailer.yml
  config/locales/en.yml
  spec/components/candidate_interface/apply_again_add_another_course_component_spec.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/models/application_form_spec.rb
  spec/services/submit_application_spec.rb
  spec/services/submit_application_with_three_choices_deactivated_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_after_apply_1_deadline_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_and_reviews_rejection_reasons_from_previous_applications_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_and_reviews_rejection_reasons_from_previous_applications_three_choices_inactive_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_during_mid_cycle_three_choices_inactive_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_with_a_course_to_new_cycle_apply_again_with_three_choices_deactivated_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_with_a_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_without_course_to_new_cycle_apply_again_with_three_choices_deactivated_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_without_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/course_selection/candidate_deletes_course_after_completing_section_apply_again_with_three_choices_deactivated_spec.rb
  spec/system/candidate_interface/course_selection/candidate_deletes_course_after_completing_section_spec.rb
  spec/system/candidate_interface/course_selection/candidate_edits_course_choices_spec.rb
  spec/system/candidate_interface/course_selection/candidate_edits_course_choices_with_apply_again_with_three_choices_deactivated_spec.rb
  spec/system/candidate_interface/course_selection/candidate_sees_add_additional_courses_after_adding_course_spec.rb
  spec/system/candidate_interface/course_selection/candidate_sees_add_additional_courses_after_adding_course_with_apply_again_three_choices_deativated_spec.rb
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_when_only_one_site_available_spec.rb
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_when_only_one_site_available_with_apply_again_three_choices_deactivated_spec.rb
  spec/system/candidate_interface/course_selection/candidate_signed_in_user_with_course_params_apply_again_with_three_choices_deactivated_spec.rb
  spec/system/candidate_interface/course_selection/candidate_signed_in_user_with_course_params_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_subject_knowledge_apply_again_three_times_deactivated_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_subject_knowledge_spec.rb
  spec/system/candidate_interface/entering_details/candidate_viewing_a_science_gcse_apply_again_three_times_deactivated_spec.rb
  spec/system/candidate_interface/entering_details/candidate_viewing_a_science_gcse_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_with_apply_again_three_choices_deactivated_spec.rb
  spec/system/decline_by_default_apply_again_with_three_choices_deactivated_spec.rb
  spec/system/decline_by_default_spec.rb
  spec/system/provider_interface/provider_views_application_submitted_in_new_cycle_spec.rb
  spec/system/provider_interface/provider_views_application_submitted_in_new_cycle_with_apply_again_with_three_choices_deactivated_spec.rb
Labels: deploy

#6593 Improve no vacancies page
  app/views/candidate_interface/course_choices/course_selection/full.html.erb
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_that_is_full_spec.rb
Labels: deploy
