Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-07, with the labels that each got.

#7174 Provider EoC emails no longer use hardcoded dates
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/apply_service_is_now_open.text.erb
  app/views/provider_mailer/find_service_is_now_open.text.erb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/provider_mailer_spec.rb
Labels: End of cycle

#7175 Add data loss documentation
  .gitignore
  Makefile
  docs/disaster-recovery.md
Labels: DevOps, deploy

#7137 Upgrade Terraform to 1.2.3
  .github/actions/deploy/action.yml
  .github/workflows/delete-review-app.yml
  .tool-versions
  jmeter/README.md
  jmeter/terraform.tf
  terraform/terraform.tf
Labels: DevOps, deploy

#7188 Update azurerm provider to 3.12.0
  jmeter/.terraform.lock.hcl
  jmeter/terraform.tf
  terraform/.terraform.lock.hcl
  terraform/terraform.tf
Labels: DevOps, deploy

#7178 Remove Postgres timeout values
  config/database.yml
Labels: DevOps, deploy

#7195 Increase the stagger time to 12 hours for the Find has opened and the new cycle has started email
  app/workers/send_find_has_opened_email_to_candidates_worker.rb
  app/workers/send_new_cycle_has_started_email_to_candidates_worker.rb
Labels: End of cycle

#7217 Remove statuscake alerts before upgrade reapply
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/rollover.tfvars.json
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.tfvars.json
Labels: DevOps, deploy

#7201 Upgrade cloudfoundry and statuscake providers.
  docs/disaster-recovery.md
  jmeter/terraform.tf
  terraform/.terraform.lock.hcl
  terraform/modules/paas/main.tf
  terraform/modules/statuscake/main.tf
  terraform/modules/statuscake/variables.tf
  terraform/terraform.tf
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/rollover.tfvars.json
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.tfvars.json
Labels: DevOps, deploy

#7221 Add compression to the daily postgres db backup
  .github/workflows/database-backup.yml
  .github/workflows/restore-production-snapshot.yml
  bin/restore-nightly-backup
Labels: DevOps

#7219 Add data migration to fix wrong column data
  app/services/data_migrations/provider_interview_data_fix.rb
  lib/tasks/data.rake
  spec/services/data_migrations/provider_interview_data_fix_spec.rb
Labels: DO NOT MERGE

#7240 Configures version updates for GitHub Actions
  .github/dependabot.yml
Labels: DevOps
