Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-03, with the labels that each got.

#6618 Stop UpdateFeatureMetricsDashboard data collection
  config/clock.rb
Labels: Core

#6619 Add application number to candidate interface
  app/components/candidate_interface/course_choices_review_component.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
Labels: deploy

#6610 Remove `content_security_policy` feature flag
  app/middlewares/apply/content_security_policy_middleware.rb
  app/services/data_migrations/drop_content_security_policy_feature_flag.rb
  app/services/feature_flag.rb
  config/initializers/content_security_policy.rb
  lib/tasks/data.rake
  spec/middlewares/apply/content_security_policy_middleware_spec.rb
  spec/services/data_migrations/drop_content_security_policy_feature_flag_spec.rb
Labels: deploy

#6623 Remove FixLatLongFlipFlops data migration
  app/services/data_migrations/fix_lat_long_flip_flops.rb
  lib/tasks/data.rake
  spec/services/data_migrations/fix_lat_long_flip_flops_spec.rb
Labels: Core

#6624 Add back links to Accessibility, Cookies, Privacy policy, Terms of use and Complaints
  app/controllers/candidate_interface/content_controller.rb
  app/controllers/provider_interface/content_controller.rb
  app/views/content/accessibility.html.erb
  app/views/content/accessibility.md
  app/views/content/service_privacy_notice.html.erb
  app/views/content/terms_candidate.html.erb
  app/views/content/terms_candidate.md
  config/locales/en.yml
Labels: deploy

#6597 Ensure that contact details forms are pre-loaded with existing data
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/candidate_interface/contact_details/address_type_controller.rb
  app/controllers/candidate_interface/contact_details/phone_number_controller.rb
  app/forms/candidate_interface/contact_details_form.rb
  app/models/application_form.rb
  spec/system/candidate_interface/entering_details/candidate_completes_contact_details_with_a_missing_address_spec.rb
Labels: deploy

#6600 Call to action links replace empty values on contact details review page
  app/components/candidate_interface/contact_details_review_component.rb
  spec/components/candidate_interface/contact_details_review_component_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_contact_details_section_spec.rb
  spec/system/candidate_interface/submitting/candidate_submits_application_with_a_missing_address_spec.rb
Labels: deploy

#6614 Reset contact details completed when invalid
  app/controllers/candidate_interface/contact_details/address_controller.rb
  app/controllers/candidate_interface/contact_details/address_type_controller.rb
  app/controllers/candidate_interface/contact_details/phone_number_controller.rb
  app/controllers/candidate_interface/contact_details/review_controller.rb
  app/forms/candidate_interface/contact_details_form.rb
  app/views/candidate_interface/contact_details/review/show.html.erb
  spec/forms/candidate_interface/contact_details_form_spec.rb
  spec/system/candidate_interface/entering_details/candidate_changes_contact_details_address_from_international_to_uk_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_contact_details_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_contact_details_section_spec.rb
Labels: deploy

#6645 Ensure inset help text still appears
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/course_choices_review_visa_status_component.html.erb
  app/components/candidate_interface/course_choices_review_visa_status_component.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
  spec/components/candidate_interface/course_choices_review_visa_status_component_spec.rb
Labels: deploy

#6663 make rejection text more sympathetic
  app/views/candidate_mailer/_reasons_for_rejection_intro.text.erb
  app/views/candidate_mailer/application_rejected_all_applications_rejected.text.erb
  app/views/candidate_mailer/application_rejected_awaiting_decision_only.text.erb
  app/views/candidate_mailer/application_rejected_offers_only.text.erb
  app/views/candidate_mailer/application_rejected_one_offer_one_awaiting_decision.text.erb
Labels: deploy

#6657 4525 add new what is your immigration status page
  app/components/candidate_interface/personal_details_review_component.rb
  app/components/provider_interface/personal_details_component.rb
  app/components/support_interface/personal_details_component.rb
  app/controllers/candidate_interface/personal_details/immigration_right_to_work_controller.rb
  app/controllers/candidate_interface/personal_details/immigration_route_controller.rb
  app/controllers/candidate_interface/personal_details/immigration_status_controller.rb
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/controllers/candidate_interface/personal_details/review_controller.rb
  app/forms/candidate_interface/immigration_right_to_work_form.rb
  app/forms/candidate_interface/immigration_route_form.rb
  app/forms/candidate_interface/immigration_status_form.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/presenters/concerns/candidate_api_data.rb
  app/services/format_residency_details_service.rb
  app/views/candidate_interface/personal_details/immigration_right_to_work/_shared_form.html.erb
  app/views/candidate_interface/personal_details/immigration_right_to_work/edit.html.erb
  app/views/candidate_interface/personal_details/immigration_route/_shared_form.html.erb
  app/views/candidate_interface/personal_details/immigration_route/new.html.erb
  app/views/candidate_interface/personal_details/immigration_status/_shared_form.html.erb
  config/locales/candidate_interface/personal_details.yml
  config/locales/en.yml
  config/routes.rb
  spec/forms/candidate_interface/immigration_right_to_work_form_spec.rb
  spec/forms/candidate_interface/immigration_route_form_spec.rb
  spec/forms/candidate_interface/immigration_status_form_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/presenters/concerns/candidate_api_data_spec.rb
  spec/services/format_residency_details_service_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_when_languages_hidden_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_when_requiring_visa_2022_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_when_requiring_visa_2022_without_entry_date_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_when_requiring_visa_spec.rb
Labels: deploy

#6670 Remove inset from explained breaks in work history
  app/components/shared/work_history_and_unpaid_experience_item_component.html.erb
  app/components/shared/work_history_and_unpaid_experience_item_component.rb
  spec/components/shared/work_history_and_unpaid_experience_item_component_spec.rb
Labels: ProVendor

#6650 Change Make Decision button to green once interviewing
  app/components/provider_interface/application_choice_header_component.html.erb
  app/components/provider_interface/application_choice_header_component.rb
  spec/components/provider_interface/application_choice_header_component_spec.rb
Labels: ProVendor

#6685 Update email content
  app/views/candidate_mailer/_wait_or_respond.text.erb
  app/views/candidate_mailer/new_offer/decisions_pending.text.erb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
Labels: deploy

#6677 Improve style/content of provider/support DSI fallback sign-in flows
  app/controllers/provider_interface/sessions_controller.rb
  app/controllers/support_interface/sessions_controller.rb
  app/views/provider_interface/sessions/authentication_fallback.html.erb
  app/views/provider_interface/sessions/check_your_email.html.erb
  app/views/provider_interface/sessions/confirm_authentication_with_token.html.erb
  app/views/provider_interface/sessions/new.html.erb
  app/views/support_interface/sessions/authentication_fallback.html.erb
  app/views/support_interface/sessions/check_your_email.html.erb
  app/views/support_interface/sessions/confirm_authentication_with_token.html.erb
  app/views/support_interface/sessions/expired_token.html.erb
  config/locales/en.yml
  spec/system/provider_interface/authentication_fallback_expired_link_spec.rb
  spec/system/provider_interface/authentication_fallback_spec.rb
  spec/system/support_interface/authentication_fallback_spec.rb
Labels: ProVendor, Support, deploy

#6691 [540] Fix Github rate limiting
  .github/actions/deploy/action.yml
Labels: DevOps

#6659 Remove expanded quals export feature flag
  app/services/data_migrations/drop_expanded_quals_export_feature_flag.rb
  app/services/data_set_documentation.rb
  app/services/feature_flag.rb
  app/services/support_interface/qualifications_export.rb
  lib/tasks/data.rake
  spec/services/data_migrations/drop_expanded_quals_export_feature_flag_spec.rb
  spec/services/support_interface/qualifications_export_spec.rb
Labels: deploy

#6705 Tweaks to DSI fallback sign-in content
  app/views/provider_interface/sessions/authentication_fallback.html.erb
  app/views/provider_interface/sessions/confirm_authentication_with_token.html.erb
  app/views/provider_interface/sessions/expired_token.html.erb
  app/views/provider_mailer/fallback_sign_in_email.text.erb
  app/views/support_interface/sessions/confirm_authentication_with_token.html.erb
  app/views/support_interface/sessions/expired_token.html.erb
  config/locales/en.yml
  spec/mailers/provider_mailer_spec.rb
  spec/system/provider_interface/authentication_fallback_expired_link_spec.rb
  spec/system/provider_interface/authentication_fallback_spec.rb
  spec/system/support_interface/authentication_fallback_expired_link_spec.rb
  spec/system/support_interface/authentication_fallback_spec.rb
Labels: ProVendor, deploy

#6676 Fix validation error
  app/forms/candidate_interface/english_foreign_language/ielts_form.rb
  app/forms/candidate_interface/english_foreign_language/other_efl_qualification_form.rb
  app/forms/candidate_interface/english_foreign_language/toefl_form.rb
  app/views/candidate_interface/english_foreign_language/ielts/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/other_efl_qualification/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/toefl/_form_fields.html.erb
  config/locales/candidate_interface/english_foreign_language.yml
  spec/forms/candidate_interface/english_foreign_language/ielts_form_spec.rb
  spec/forms/candidate_interface/english_foreign_language/other_efl_qualification_form_spec.rb
  spec/forms/candidate_interface/english_foreign_language/toefl_form_spec.rb
Labels: deploy

#6722 can't remove hint text
  app/views/candidate_interface/restructured_work_history/review/show.html.erb
  app/views/candidate_interface/work_history/review/show.html.erb
Labels: deploy

#6687 Draft spec for Candidate API v1.2
  app/controllers/api_docs/candidate_api_docs/open_api_controller.rb
  app/controllers/api_docs/candidate_api_docs/reference_controller.rb
  app/lib/candidate_api_specification.rb
  config/candidate_api/v1.1.yml
  config/candidate_api/v1.2.yml
  config/initializers/route_validators.rb
  config/routes.rb
  spec/validators/valid_candidate_api_route_spec.rb
Labels: deploy

#6738 Course Change - Add the new email
  app/mailers/candidate_mailer.rb
  app/services/change_course.rb
  app/views/candidate_mailer/change_course.text.erb
  app/views/candidate_mailer/changed_offer.text.erb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/change_course_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: deploy

#6742 DNM: Amend easter holidays from 4th to the 18th of April
  app/components/provider_interface/key_dates_banner.html.erb
  app/components/provider_interface/key_dates_banner.rb
  app/services/cycle_timetable.rb
  config/locales/key_dates_banner.yml
  spec/components/provider_interface/key_dates_banner_spec.rb
  spec/services/cycle_timetable_spec.rb
Labels: deploy

#6725 Send nudge emails to candidates who have fully completed applications
  app/mailers/candidate_mailer.rb
  app/queries/get_unsubmitted_applications_ready_to_nudge.rb
  app/services/feature_flag.rb
  app/views/candidate_mailer/nudge_unsubmitted.text.erb
  app/workers/nudge_unsubmitted_candidates_worker.rb
  config/brakeman.ignore
  config/clock.rb
  config/locales/application_states.yml
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/queries/get_unsubmitted_applications_ready_to_nudge_spec.rb
  spec/workers/nudge_unsubmitted_candidates_worker_spec.rb
Labels: Candidate, deploy
