Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-04, with the labels that each got.

#6709 4342 degrees new source of data
  app/components/candidate_interface/degree_required_component.rb
  app/controllers/candidate_interface/degrees/institution_controller.rb
  app/controllers/candidate_interface/degrees/subject_controller.rb
  app/controllers/candidate_interface/degrees/type_controller.rb
  app/forms/candidate_interface/degree_grade_form.rb
  app/forms/candidate_interface/degree_institution_form.rb
  app/forms/candidate_interface/degree_subject_form.rb
  app/forms/candidate_interface/degree_type_form.rb
  app/lib/hesa/degree_type.rb
  app/lib/hesa/grade.rb
  app/lib/hesa/institution.rb
  app/lib/hesa/subject.rb
  app/presenters/concerns/qualification_api_data.rb
  app/presenters/concerns/qualification_include_uuids.rb
  app/presenters/register_api/single_application_presenter.rb
  app/services/support_interface/applications_by_demographic_domicile_and_degree_class_export.rb
  app/services/support_interface/candidate_autofill_usage_export.rb
  app/views/support_interface/docs/qualifications.html.erb
  config/register-api.yml
  spec/factories/application_choice.rb
  spec/forms/candidate_interface/degree_grade_form_spec.rb
  spec/lib/hesa/degree_type_spec.rb
  spec/lib/hesa/grade_spec.rb
  spec/lib/hesa/institution_spec.rb
  spec/lib/hesa/subject_spec.rb
  spec/presenters/concerns/qualification_api_data_spec.rb
  spec/presenters/register_api/single_application_presenter_spec.rb
  spec/requests/data_api/applications_by_demographic_domicile_and_degree_class_export_spec.rb
  spec/services/provider_interface/hesa_data_export_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/course_selection/candidate_can_view_degree_requirements_and_guidance_for_selected_courses_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_delete_and_replace_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_editing_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_degrees_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_qualifications_spec.rb
  spec/system/candidate_interface/submitting/candidate_submitting_application_spec.rb
  spec/system/register_api/register_receives_application_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: deploy

#6744 Move to rails 6.1 defaults
  app/services/save_provider_user.rb
  config/application.rb
  config/initializers/new_framework_defaults_6_0.rb
  config/initializers/new_framework_defaults_6_1.rb
Labels: deploy

#6723 Separate R4R presentation according to `ApplicationChoice#rejection_reasons_type`
  app/components/candidate_interface/application_dashboard_course_choices_component.rb
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/rejection_reasons_component.rb
  app/components/provider_interface/application_rejection_feedback_component.html.erb
  app/components/shared/reasons_for_rejection_component.rb
  app/components/shared/rejection_reasons/reasons_for_rejection_component.html.erb
  app/components/shared/rejection_reasons/reasons_for_rejection_component.rb
  app/components/shared/rejection_reasons/rejection_reason_component.html.erb
  app/components/shared/rejection_reasons/rejection_reason_component.rb
  app/components/shared/rejection_reasons/rejection_reasons_component.html.erb
  app/components/shared/rejection_reasons/rejection_reasons_component.rb
  app/components/shared/rejection_reasons/structured_rejection_reasons_component.rb
  app/components/shared/rejection_reasons_component.rb
  app/components/shared/rejections_component.html.erb
  app/components/shared/rejections_component.rb
  app/components/support_interface/application_choice_component.rb
  app/presenters/rejected_application_choice_presenter.rb
  app/presenters/rejection_reasons/reasons_for_rejection_presenter.rb
  app/presenters/rejection_reasons/rejection_reason_presenter.rb
  app/presenters/rejection_reasons/rejection_reasons_presenter.rb
  app/views/provider_interface/reasons_for_rejection/check.html.erb
  app/views/provider_interface/rejections/check.html.erb
  spec/components/shared/rejection_reasons/reasons_for_rejection_component_spec.rb
  spec/components/shared/rejection_reasons/rejection_reasons_component_spec.rb
  spec/components/shared/rejections_component_spec.rb
  spec/components/utility/reasons_for_rejection_component_spec.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/presenters/rejected_application_choice_presenter_spec.rb
  spec/presenters/rejection_reasons/reasons_for_rejection_presenter_spec.rb
  spec/presenters/rejection_reasons/rejection_reason_presenter_spec.rb
  spec/presenters/rejection_reasons/rejection_reasons_presenter_spec.rb
  spec/presenters/vendor_api/v1.0/rejection_reason_presenter_spec.rb
Labels: deploy

#6746 R4R redesign: Email presentation of redesigned reasons
  app/presenters/rejection_reasons/rejection_reasons_presenter.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/presenters/rejection_reasons/rejection_reasons_presenter_spec.rb
Labels: deploy

#6767 Amend confirm email content
  app/controllers/dfe_sign_in_controller.rb
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/confirm_sign_in.text.erb
  spec/mailers/previews/provider_mailer_preview.rb
  spec/mailers/provider_mailer_spec.rb
  spec/system/provider_interface/provider_signs_in_from_new_device_spec.rb
Labels: deploy

#6754 Upgrade rails 7.0 defaults
  app/controllers/provider_interface/sessions_controller.rb
  app/controllers/support_interface/sessions_controller.rb
  config/application.rb
  config/initializers/cookies_rotator.rb
  config/initializers/new_framework_defaults_7_0.rb
  spec/components/candidate_interface/carry_over_inset_text_component_spec.rb
  spec/components/provider_interface/individual_condition_status_review_component_spec.rb
  spec/components/support_interface/application_add_course_component_spec.rb
  spec/components/support_interface/duplicate_matches_resolve_component_spec.rb
  spec/components/support_interface/persona_user_component_spec.rb
  spec/components/utility/dfe_sign_in_button_component_spec.rb
  spec/queries/get_recruited_application_choices_spec.rb
Labels: deploy

#6760 Update content for nudge unsubmitted applications email
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/nudge_unsubmitted.text.erb
Labels: Candidate, deploy

#6775 Add backlinks to the change course flow
  app/helpers/course_path_helper.rb
  app/views/provider_interface/courses/checks/edit.html.erb
  app/views/provider_interface/courses/courses/edit.html.erb
  app/views/provider_interface/courses/locations/edit.html.erb
  app/views/provider_interface/courses/providers/edit.html.erb
  app/views/provider_interface/courses/study_modes/edit.html.erb
  spec/helpers/course_path_helper_spec.rb
  spec/system/provider_interface/provider_changes_a_course_before_point_of_offer_spec.rb
Labels: deploy

#6787 Use workflow concurrency for build and deploy
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
Labels: deploy

#6778 Course Change - Validations
  app/forms/provider_interface/course_wizard.rb
  config/locales/provider_interface/change_course.yml
  spec/forms/provider_interface/course_wizard_spec.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
Labels: deploy

#6797 Remove the old job history flow
  app/components/candidate_interface/break_in_work_history_component.html.erb
  app/components/candidate_interface/break_in_work_history_component.rb
  app/components/candidate_interface/break_placeholder_in_work_history_component.html.erb
  app/components/candidate_interface/break_placeholder_in_work_history_component.rb
  app/components/candidate_interface/work_history_review_component.html.erb
  app/components/candidate_interface/work_history_review_component.rb
  app/components/shared/restructured_work_history/review_component.rb
  app/controllers/candidate_interface/work_history/base_controller.rb
  app/controllers/candidate_interface/work_history/break_controller.rb
  app/controllers/candidate_interface/work_history/destroy_controller.rb
  app/controllers/candidate_interface/work_history/edit_controller.rb
  app/controllers/candidate_interface/work_history/explanation_controller.rb
  app/controllers/candidate_interface/work_history/length_controller.rb
  app/controllers/candidate_interface/work_history/review_controller.rb
  app/forms/candidate_interface/work_experience_form.rb
  app/forms/candidate_interface/work_explanation_form.rb
  app/forms/candidate_interface/work_history_break_form.rb
  app/forms/candidate_interface/work_history_form.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/restructured_work_history/break/confirm_destroy.html.erb
  app/views/candidate_interface/restructured_work_history/review/show.html.erb
  app/views/candidate_interface/work_history/break/_form.html.erb
  app/views/candidate_interface/work_history/break/confirm_destroy.html.erb
  app/views/candidate_interface/work_history/break/edit.html.erb
  app/views/candidate_interface/work_history/break/new.html.erb
  app/views/candidate_interface/work_history/destroy/confirm_destroy.html.erb
  app/views/candidate_interface/work_history/edit/_form.html.erb
  app/views/candidate_interface/work_history/edit/edit.html.erb
  app/views/candidate_interface/work_history/edit/new.html.erb
  app/views/candidate_interface/work_history/explanation/show.html.erb
  app/views/candidate_interface/work_history/length/show.html.erb
  app/views/candidate_interface/work_history/review/show.html.erb
  config/locales/candidate_interface/restructured_work_history.yml
  config/locales/candidate_interface/work_history.yml
  config/routes.rb
  spec/components/candidate_interface/break_in_work_history_component_spec.rb
  spec/components/candidate_interface/break_placeholder_in_work_history_component_spec.rb
  spec/components/candidate_interface/work_history_review_component_spec.rb
  spec/forms/candidate_interface/work_experience_form_spec.rb
  spec/forms/candidate_interface/work_explanation_form_spec.rb
  spec/forms/candidate_interface/work_history_break_form_spec.rb
  spec/forms/candidate_interface/work_history_form_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_breaks_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_full_time_education_spec.rb
  spec/system/candidate_interface/entering_details/restructured_work_history/candidate_entering_work_history_not_worked_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_edits_work_history_after_completing_the_section_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_entering_blank_work_history_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_entering_work_history_breaks_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_entering_work_history_not_worked_spec.rb
  spec/system/candidate_interface/entering_details/work_history/candidate_entering_work_history_spec.rb
Labels: deploy

#6766 SR4R Redesign: Make `RejectionReasonsHistory` work new R4R data
  app/components/candidate_interface/review_rejection_reasons_component.html.erb
  app/components/candidate_interface/review_rejection_reasons_component.rb
  app/models/candidate_interface/rejection_reasons_history.rb
  app/models/rejection_reasons.rb
  app/views/candidate_interface/personal_statement/show.html.erb
  app/views/candidate_interface/subject_knowledge/show.html.erb
  spec/components/candidate_interface/review_rejection_reasons_component_spec.rb
  spec/models/candidate_interface/rejection_reasons_history_spec.rb
  spec/models/rejection_reasons_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_and_views_redesigned_rejection_reasons_spec.rb
Labels: deploy

#6788 Make offer flow - content update
  app/components/provider_interface/change_course_details_component.rb
  app/components/provider_interface/check_course_details_component.rb
  app/components/provider_interface/completed_offer_summary_component.rb
  app/components/provider_interface/conditions_form_component.html.erb
  app/components/provider_interface/conditions_form_component.rb
  app/components/provider_interface/course_change_warning_text_component.html.erb
  app/components/provider_interface/course_details_component.rb
  app/components/provider_interface/course_summary_component.rb
  app/components/provider_interface/offer_summary_component.rb
  app/models/site.rb
  app/views/provider_interface/offer/checks/edit.html.erb
  app/views/provider_interface/offer/checks/new.html.erb
  app/views/provider_interface/offer/conditions/_form.html.erb
  app/views/provider_interface/offer/conditions/edit.html.erb
  app/views/provider_interface/offer/conditions/new.html.erb
  app/views/provider_interface/offer/courses/edit.html.erb
  app/views/provider_interface/offer/courses/new.html.erb
  app/views/provider_interface/offer/locations/edit.html.erb
  app/views/provider_interface/offer/locations/new.html.erb
  app/views/provider_interface/offer/providers/edit.html.erb
  app/views/provider_interface/offer/providers/new.html.erb
  app/views/provider_interface/offer/study_modes/edit.html.erb
  app/views/provider_interface/offer/study_modes/new.html.erb
  config/locales/provider_interface/make_offer.yml
  spec/components/provider_interface/change_course_details_component_spec.rb
  spec/components/provider_interface/completed_offer_summary_component_spec.rb
  spec/components/provider_interface/conditions_form_component_spec.rb
  spec/components/provider_interface/course_change_warning_text_component_spec.rb
  spec/components/provider_interface/course_details_component_spec.rb
  spec/components/provider_interface/course_summary_component_spec.rb
  spec/components/provider_interface/offer_summary_component_spec.rb
  spec/models/site_spec.rb
  spec/system/provider_interface/change_existing_offer_spec.rb
  spec/system/provider_interface/change_make_offer_spec.rb
  spec/system/provider_interface/make_offer_spec.rb
  spec/system/provider_interface/provider_changes_a_course_before_point_of_offer_spec.rb
  spec/system/provider_interface/provider_reinstates_deferred_offer_spec.rb
Labels: deploy

#6817 [562] Increase clock instances memory
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.tfvars.json
Labels: DevOps

#6811 Render Candidate specific redesigned Reasons for Rejection Component
  app/components/candidate_interface/application_dashboard_course_choices_component.rb
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/rejection_reasons/rejection_reasons_component.html.erb
  app/components/candidate_interface/rejection_reasons/rejection_reasons_component.rb
  app/components/candidate_interface/rejection_reasons_component.rb
  app/components/shared/rejections_component.rb
  app/models/candidate_interface/rejection_reasons_history.rb
  spec/components/shared/rejections_component_spec.rb
Labels: deploy

#6808 Prepare to drop feature restructured work history column
  app/components/shared/work_history_item_component.rb
  app/controllers/candidate_interface/restructured_work_history/base_controller.rb
  app/models/application_form.rb
  app/services/duplicate_application.rb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/support_interface/application_forms/show.html.erb
  config/analytics.yml
  spec/components/shared/work_history_and_unpaid_experience_component_spec.rb
  spec/components/utility/work_history_component_spec.rb
  spec/services/carry_over_application_spec.rb
  spec/system/candidate_interface/entering_details/candidate_edits_or_deletes_volunteering_section_after_competing_the_section_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: deploy

#6803 5028 replace application number in application search
  app/components/provider_interface/application_card_component.html.erb
  app/components/utility/filter_component.html.erb
  app/services/feature_flag.rb
  app/services/filter_application_choices_for_providers.rb
  spec/components/provider_interface/application_card_component_spec.rb
  spec/services/feature_flag_spec.rb
  spec/services/filter_application_choices_for_providers_spec.rb
  spec/system/provider_interface/provider_applications_search_spec.rb
Labels: deploy

#6807 Allow words to be used to input the month
  app/helpers/date_validation_helper.rb
  spec/helpers/date_validation_helper_spec.rb
Labels: deploy

#6821 Course Change - Only render change links for applicable application states
  app/components/provider_interface/change_course_details_component.html.erb
  app/components/provider_interface/course_details_component.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  spec/system/provider_interface/provider_changes_a_course_before_point_of_offer_spec.rb
Labels: deploy

#6814 Course Change - email candidates about upcoming interviews
  app/components/provider_interface/course_change_warning_text_component.rb
  app/mailers/candidate_mailer.rb
  app/models/interview.rb
  app/services/change_course.rb
  app/services/update_interviews_provider.rb
  app/views/candidate_mailer/interview_updated.text.erb
  config/locales/emails/candidate_mailer.yml
  spec/components/provider_interface/course_change_warning_text_component_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/change_course_spec.rb
  spec/services/update_interviews_provider_spec.rb
Labels: deploy

#6822 Add return to review page behaviour to the degree wizard
  app/components/candidate_interface/degree_new_review_component.rb
  app/controllers/candidate_interface/degrees/degree/destroy_controller.rb
  app/controllers/candidate_interface/degrees/degree_controller.rb
  app/forms/candidate_interface/degree_wizard.rb
  app/views/candidate_interface/degrees/degree/new_university.html.erb
  config/locales/candidate_interface/degree.yml
  spec/components/candidate_interface/degree_new_review_component_spec.rb
  spec/forms/candidate_interface/degree_wizard_spec.rb
  spec/system/candidate_interface/entering_details/degrees/new_degree_flow/candidate_editing_degrees_spec.rb
Labels: deploy

#6840 experiments to promote tta service better
  app/components/candidate_interface/application_dashboard_guidance_component.html.erb
  app/views/candidate_interface/personal_statement/_form.html.erb
  app/views/candidate_interface/subject_knowledge/_form.html.erb
Labels: deploy

#6786 Update yarn dependencies
  yarn.lock
Labels: deploy

#6846 Removed conditon from build job in workflow
  .github/workflows/build-and-deploy.yml
Labels: DevOps, deploy

#6836 Vendor API return latest minor version
  app/lib/concerns/versioning_helpers.rb
  app/presenters/vendor_api/base.rb
  lib/tasks/version.rake
  spec/lib/concerns/versioning_helpers_spec.rb
  spec/requests/api_docs/reference_spec.rb
  spec/requests/vendor_api/versioning_spec.rb
  spec/support/vendor_api/shared_examples.rb
Labels: deploy

#6805 Update both versions of priv pol
  app/views/content/service_privacy_notice.md
  app/views/content/service_privacy_notice_candidate.html.erb
Labels: deploy

#6835 Reduce content and remove terms of use checkbox on Sign up page
  app/controllers/candidate_interface/sign_up_controller.rb
  app/forms/candidate_interface/sign_up_form.rb
  app/views/candidate_interface/shared/_check_your_email.html.erb
  app/views/candidate_interface/sign_up/new.html.erb
  config/locales/candidate_interface/authentication.yml
  cypress/integration/candidate.spec.js
  jmeter/plans/apply.rb
  spec/forms/candidate_interface/sign_up_form_spec.rb
  spec/system/candidate_api/candidate_api_application_state_change_triggers_update_spec.rb
  spec/system/candidate_interface/course_selection/candidate_existing_submitted_user_with_course_params_spec.rb
  spec/system/candidate_interface/course_selection/candidate_new_user_with_course_params_and_cancel_spec.rb
  spec/system/candidate_interface/course_selection/candidate_new_user_with_course_params_spec.rb
  spec/system/candidate_interface/course_selection/candidate_signed_in_user_with_course_params_spec.rb
  spec/system/candidate_interface/course_selection/sandbox_user_apply_from_find_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_account_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_using_legacy_email_link_with_u_param_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_with_validation_errors_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_up_to_test_environment_without_dfe_email_address_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_up_using_magic_link_with_an_invalid_token_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_tries_to_reuse_magic_link_spec.rb
  spec/system/candidate_interface/signup_and_signin/two_candidates_sign_in_on_same_machine_spec.rb
Labels: deploy

#6847 Bring v1.1 spec up to date with draft spec
  app/controllers/concerns/vendor_api/application_data_concerns.rb
  config/vendor_api/draft.yml
  config/vendor_api/v1.1.yml
  spec/requests/vendor_api/versioning_spec.rb
Labels: deploy

#6873 Remove bold formatting from location labels
  app/views/provider_interface/courses/locations/edit.html.erb
  app/views/provider_interface/offer/locations/edit.html.erb
  app/views/provider_interface/offer/locations/new.html.erb
Labels: deploy

#6856 Nudge emails to help candidate with missing course choices or personal statement
  app/mailers/candidate_mailer.rb
  app/models/application_form.rb
  app/queries/get_incomplete_course_choice_applications_ready_to_nudge.rb
  app/queries/get_incomplete_personal_statement_applications_ready_to_nudge.rb
  app/queries/get_unsubmitted_applications_ready_to_nudge.rb
  app/services/feature_flag.rb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_courses.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_personal_statement.text.erb
  app/workers/nudge_candidates_worker.rb
  app/workers/nudge_unsubmitted_candidates_worker.rb
  config/clock.rb
  config/locales/application_states.yml
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/queries/get_incomplete_course_choice_applications_ready_to_nudge_spec.rb
  spec/queries/get_incomplete_personal_statement_applications_ready_to_nudge_spec.rb
  spec/workers/nudge_candidates_worker_spec.rb
  spec/workers/nudge_unsubmitted_candidates_worker_spec.rb
Labels: Candidate, deploy

#6886 4656 fix styles in support interface
  app/frontend/packs/application-candidate.js
  app/frontend/packs/application-support.js
  app/frontend/styles/application-candidate.scss
  app/frontend/styles/application-support.scss
  yarn.lock
Labels: deploy

#6843 4647 add autocompletes to the new degree entry flow behind feature flag
  app/components/candidate_interface/degree_grade_component.html.erb
  app/components/candidate_interface/degree_type_component.html.erb
  app/components/candidate_interface/degree_type_component.rb
  app/controllers/candidate_interface/degrees/degree_controller.rb
  app/forms/candidate_interface/degree_wizard.rb
  app/helpers/view_helper.rb
  app/lib/hesa/degree_type.rb
  app/views/candidate_interface/degrees/degree/new_country.html.erb
  app/views/candidate_interface/degrees/degree/new_subject.html.erb
  app/views/candidate_interface/degrees/degree/new_university.html.erb
  spec/components/candidate_interface/degree_type_component_spec.rb
  spec/forms/candidate_interface/degree_wizard_spec.rb
  spec/lib/hesa/degree_type_spec.rb
  spec/system/candidate_interface/course_selection/candidate_can_view_degree_requirements_and_guidance_for_selected_courses_new_degree_flow_spec.rb
  spec/system/candidate_interface/entering_details/degrees/new_degree_flow/candidate_editing_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/new_degree_flow/candidate_entering_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/new_degree_flow/candidate_entering_international_degrees_spec.rb
Labels: deploy
