Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-06, with the labels that each got.

#7036 Fiz support interface edit references feedback bug
  app/controllers/support_interface/application_forms/references_controller.rb
  app/services/submit_reference.rb
  spec/requests/support_interface/update_reference_feedback_spec.rb
  spec/services/submit_reference_spec.rb
Labels: deploy

#7009 Fix degree type free text bug
  app/components/candidate_interface/degree_new_review_component.rb
  app/forms/candidate_interface/degree_wizard.rb
  spec/components/candidate_interface/degree_new_review_component_spec.rb
  spec/forms/candidate_interface/degree_wizard_spec.rb
  spec/system/candidate_interface/entering_details/degrees/new_degree_flow/candidate_adding_unknown_degrees_spec.rb
Labels: deploy

#7044 [598] Do not fail silently if imagetag not provided
  .github/workflows/build-and-deploy.yml
  Makefile
Labels: DevOps

#7019 Amend application header for RBD'd applications when the user cannot give feedback
  app/components/provider_interface/application_choice_header_component.html.erb
  app/components/provider_interface/application_choice_header_component.rb
  app/components/provider_interface/application_header_components/awaiting_decision_cannot_respond_component.html.erb
  app/components/provider_interface/application_header_components/awaiting_decision_cannot_respond_component.rb
  app/components/provider_interface/application_header_components/deferred_offer_component.html.erb
  app/components/provider_interface/application_header_components/deferred_offer_component.rb
  app/components/provider_interface/application_header_components/offer_will_be_declined_by_default_component.html.erb
  app/components/provider_interface/application_header_components/offer_will_be_declined_by_default_component.rb
  app/components/provider_interface/application_header_components/rejection_reason_required_component.html.erb
  app/components/provider_interface/application_header_components/rejection_reason_required_component.rb
  app/components/provider_interface/application_header_components/respond_component.html.erb
  app/components/provider_interface/application_header_components/respond_component.rb
  spec/components/provider_interface/application_choice_header_component_spec.rb
  spec/components/provider_interface/application_header_components/awaiting_decision_cannot_respond_component_spec.rb
  spec/components/provider_interface/application_header_components/deferred_offer_component_spec.rb
  spec/components/provider_interface/application_header_components/offer_will_be_declined_by_default_component_spec.rb
  spec/components/provider_interface/application_header_components/rejection_reason_required_component_spec.rb
  spec/components/provider_interface/application_header_components/respond_component_spec.rb
Labels: deploy

#7048 Fix delete review app workflow
  .github/workflows/delete-review-app.yml
Labels: DevOps

#7034 Run qa and staging deployments in parallel
  .github/workflows/build-and-deploy.yml
Labels: DevOps

#7062 Support site providers page: show sites per recruitment cycle
  app/views/support_interface/providers/sites.html.erb
Labels: deploy

#7056 Fix accessibility issues
  app/components/candidate_interface/selected_references_component.rb
  app/components/provider_interface/completed_offer_summary_component.rb
  app/frontend/packs/components/checkbox_search_filter.js
  app/views/candidate_interface/references/selection/new.html.erb
  app/views/candidate_interface/restructured_work_history/job/_form.html.erb
  app/views/candidate_interface/volunteering/role/_form.html.erb
  app/views/provider_interface/offers/show.html.erb
  spec/system/candidate_interface/references/candidate_selects_two_references_spec.rb
Labels: deploy

#7069 338 scan docker images
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
Labels: DevOps, deploy

#7084 Load testing doc
  jmeter/Makefile
  jmeter/README.md
  jmeter/build.sh
Labels: DevOps

#7099 Add the summer banner to the cycle switcher
  app/services/cycle_timetable.rb
Labels: End of cycle

#7023 Swap site models
  app/exports/sites_export.yml
  app/models/course_option.rb
  app/models/provider.rb
  app/models/provider_interface/provider_applications_filter.rb
  app/models/site.rb
  app/models/temp_site.rb
  app/queries/get_all_change_options_from_offered_option.rb
  app/queries/get_change_offer_options.rb
  app/queries/get_course_option_from_codes.rb
  app/services/filter_application_choices_for_providers.rb
  app/services/support_interface/providers_export.rb
  app/services/support_interface/sites_export.rb
  app/services/teacher_training_public_api/assign_site_attributes.rb
  app/services/teacher_training_public_api/assign_temp_site_attributes.rb
  app/services/teacher_training_public_api/sync_sites.rb
  app/views/support_interface/providers/show.html.erb
  app/views/support_interface/providers/sites.html.erb
  config/locales/vendor_api/make_offer.yml
  spec/factories/course_option.rb
  spec/factories/site.rb
  spec/models/course_option_spec.rb
  spec/models/provider_interface/provider_applications_filter_spec.rb
  spec/models/site_spec.rb
  spec/models/temp_site_spec.rb
  spec/queries/get_course_option_from_codes_spec.rb
  spec/requests/vendor_api/v1.0/post_make_an_offer_spec.rb
  spec/services/filter_application_choices_for_providers_spec.rb
  spec/services/support_interface/sites_export_spec.rb
  spec/services/teacher_training_public_api/assign_site_attributes_spec.rb
  spec/services/teacher_training_public_api/sync_sites_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/provider_interface/provider_applications_filter_spec.rb
  spec/system/teacher_training_public_api/sync_site_spec.rb
  spec/system/vendor_api/vendor_makes_an_offer_for_course_in_past_cycle_spec.rb
Labels: deploy, Sites refactor

#7102 Test swap sites
  app/exports/sites_export.yml
  app/models/course_option.rb
  app/models/provider.rb
  app/models/provider_interface/provider_applications_filter.rb
  app/models/site.rb
  app/models/temp_site.rb
  app/queries/get_all_change_options_from_offered_option.rb
  app/queries/get_change_offer_options.rb
  app/queries/get_course_option_from_codes.rb
  app/services/filter_application_choices_for_providers.rb
  app/services/support_interface/providers_export.rb
  app/services/support_interface/sites_export.rb
  app/services/teacher_training_public_api/assign_site_attributes.rb
  app/services/teacher_training_public_api/assign_temp_site_attributes.rb
  app/services/teacher_training_public_api/sync_sites.rb
  app/views/support_interface/providers/show.html.erb
  app/views/support_interface/providers/sites.html.erb
  config/locales/vendor_api/make_offer.yml
  spec/factories/course_option.rb
  spec/factories/site.rb
  spec/models/course_option_spec.rb
  spec/models/provider_interface/provider_applications_filter_spec.rb
  spec/models/site_spec.rb
  spec/models/temp_site_spec.rb
  spec/queries/get_course_option_from_codes_spec.rb
  spec/requests/vendor_api/v1.0/post_make_an_offer_spec.rb
  spec/services/filter_application_choices_for_providers_spec.rb
  spec/services/support_interface/sites_export_spec.rb
  spec/services/teacher_training_public_api/assign_site_attributes_spec.rb
  spec/services/teacher_training_public_api/sync_sites_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/provider_interface/provider_applications_filter_spec.rb
  spec/system/teacher_training_public_api/sync_site_spec.rb
  spec/system/vendor_api/vendor_makes_an_offer_for_course_in_past_cycle_spec.rb
Labels: deploy

#7087 Reinstate course change tool in support
  app/components/support_interface/application_choice_component.rb
  app/controllers/support_interface/application_forms/courses_controller.rb
  app/errors/course_choice_error.rb
  app/errors/provider_interview_error.rb
  app/forms/support_interface/application_forms/change_course_choice_form.rb
  app/models/application_form.rb
  app/services/data_migrations/drop_change_course_details_before_offer_feature_flag.rb
  app/services/support_interface/change_application_choice_course_option.rb
  app/views/support_interface/application_forms/courses/edit.html.erb
  config/locales/support_interface/support_interface.yml
  config/routes.rb
  docs/support_playbook.md
  lib/tasks/data.rake
  spec/components/support_interface/application_choice_component_spec.rb
  spec/forms/support_interface/application_forms/change_course_choice_form_spec.rb
  spec/models/application_form_spec.rb
  spec/services/data_migrations/drop_change_course_details_before_offer_feature_flag_spec.rb
  spec/services/support_interface/change_application_choice_course_option_spec.rb
  spec/system/support_interface/change_course_choice_spec.rb
Labels: deploy

#7113 Data migration to remove orphaned temp sites
  app/services/data_migrations/destroy_orphaned_sites.rb
  lib/tasks/data.rake
  spec/services/data_migrations/destroy_orphaned_sites_spec.rb
Labels: Sites refactor

#7108 Error returned if no provider selected when generating token
  app/controllers/support_interface/api_tokens_controller.rb
  app/errors/missing_provider_error.rb
  spec/system/support_interface/api_tokens_spec.rb
Labels: deploy

#7110 [1] Migration to remove Sites
  config/analytics.yml
  config/analytics_blocklist.yml
  db/migrate/20220620065317_drop_sites_references.rb
  db/migrate/20220620065444_drop_sites_table.rb
  db/schema.rb
  docs/domain-model.png
Labels: deploy, Sites refactor

#7114 [2] Migrations to copy the temp sites table to sites
  db/migrate/20220620124444_copy_temp_sites.rb
  db/migrate/20220620131638_add_site_to_course_options.rb
  db/schema.rb
  docs/domain-model.png
Labels: deploy, Sites refactor

#7115 [3] Pause sync sites job
  config/clock.rb
Labels: deploy, Sites refactor

#7117 [5] Backfill sites from temp sites
  app/services/data_migrations/backfill_sites_from_temp_sites.rb
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_sites_from_temp_sites_spec.rb
Labels: deploy, Sites refactor

#7118 [6] Use sites not temp sites
  app/models/course_option.rb
  app/models/provider.rb
  app/models/site.rb
  app/models/temp_site.rb
  app/queries/get_all_change_options_from_offered_option.rb
  app/queries/get_change_offer_options.rb
  app/services/data_migrations/backfill_sites_from_temp_sites.rb
  app/services/data_migrations/destroy_orphaned_sites.rb
  app/services/filter_application_choices_for_providers.rb
  app/services/support_interface/sites_export.rb
  app/services/teacher_training_public_api/assign_site_attributes.rb
  app/services/teacher_training_public_api/sync_sites.rb
  spec/factories/site.rb
  spec/factories/temp_sites.rb
  spec/models/site_spec.rb
  spec/services/data_migrations/backfill_sites_from_temp_sites_spec.rb
  spec/services/data_migrations/destroy_orphaned_sites_spec.rb
  spec/services/teacher_training_public_api/assign_site_attributes_spec.rb
  spec/services/teacher_training_public_api/sync_sites_spec.rb
  spec/system/teacher_training_public_api/sync_site_spec.rb
Labels: deploy, Sites refactor

#7125 [7] Re-enable writing to sites and syncing with TTAPI
  config/clock.rb
Labels: deploy

#7120 [8] Delete temp sites table
  config/analytics.yml
  config/analytics_blocklist.yml
  db/migrate/20220620162358_delete_temp_sites.rb
  db/migrate/20220620162702_remove_temp_site_id_from_course_options.rb
  db/schema.rb
Labels: deploy, Sites refactor

#7127 [10] Add validations to the Site for UUID
  app/models/site.rb
  spec/models/site_spec.rb
Labels: deploy, Sites refactor

#7121 API applications timeout fix
  app/controllers/concerns/vendor_api/application_data_concerns.rb
  app/presenters/vendor_api/multiple_applications_presenter.rb
  app/services/retrieve_api_field_length.rb
  spec/controllers/concerns/vendor_api/application_data_concerns_spec.rb
Labels: deploy

#7138 Automate updating out of date provider ids on application choices
  app/models/application_choice.rb
  app/workers/update_out_of_date_provider_ids_on_application_choices.rb
  config/clock.rb
  spec/factories/application_choice.rb
  spec/models/application_choice_spec.rb
  spec/workers/update_out_of_date_provider_ids_on_application_choices_spec.rb
Labels: deploy

#7144 Improve performance of PersonaExport
  app/services/support_interface/persona_export.rb
Labels: deploy

#7156 Use current course to surface diversity information
  app/components/provider_interface/diversity_information_component.rb
  spec/components/provider_interface/diversity_information_component_spec.rb
Labels: deploy

#7143 Fix offer withdrawn box not showing
  app/components/candidate_interface/rejection_reasons_component.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/components/candidate_interface/rejection_reasons_component_spec.rb
  spec/components/shared/rejection_reasons/rejection_reason_component_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
Labels: deploy
