Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-10, with the labels that each got.

#7520 Update content on initial Equality and diversity questions page
  app/views/candidate_interface/equality_and_diversity/start.html.erb
Labels: deploy

#7492 691 fix the reminder sent at copy rendering on the post offer dashboard
  app/components/candidate_interface/new_reference_status_line_component.html.erb
  app/components/candidate_interface/new_reference_status_line_component.rb
  spec/components/candidate_interface/new_reference_status_line_component_spec.rb
  spec/system/candidate_interface/new-references/candidate_views_their_references_on_the_post_offer_dashboard_spec.rb
Labels: deploy

#7529 Update the ethnic group and background questions in our hesa questionnaire
  app/lib/hesa/ethnicity.rb
  app/views/candidate_interface/equality_and_diversity/edit_ethnic_group.html.erb
  config/initializers/hesa_disabilities.rb
  config/initializers/hesa_ethnicities.rb
  config/locales/candidate_interface/equality_and_diversity.yml
  spec/components/provider_interface/diversity_information_component_spec.rb
  spec/factories/application_form.rb
  spec/lib/hesa/ethnicity_spec.rb
  spec/lib/test_applications_spec.rb
Labels: deploy

#7540 Update our disabilities question page in our hesa questionnaire
  app/components/candidate_interface/equality_and_diversity_review_component.rb
  app/controllers/candidate_interface/equality_and_diversity_controller.rb
  app/forms/candidate_interface/equality_and_diversity/disabilities_form.rb
  app/helpers/checkbox_options_helper.rb
  app/helpers/disability_helper.rb
  app/lib/hesa/disability.rb
  app/presenters/concerns/hesa_itt_data_api_data.rb
  app/views/candidate_interface/equality_and_diversity/edit_disabilities.html.erb
  app/views/candidate_interface/equality_and_diversity/edit_ethnic_group.html.erb
  config/locales/candidate_interface/equality_and_diversity.yml
  spec/components/candidate_interface/equality_and_diversity_review_component_spec.rb
  spec/components/provider_interface/diversity_information_component_spec.rb
  spec/factories/application_form.rb
  spec/forms/candidate_interface/equality_and_diversity/disabilities_form_spec.rb
  spec/helpers/checkbox_options_helper_spec.rb
  spec/lib/hesa/disability_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_and_reviews_rejection_reasons_from_previous_applications_feature_flag_disabled_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_and_views_redesigned_rejection_reasons_feature_flag_disabled_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_spec.rb
  spec/system/candidate_interface/references/candidate_submits_a_duplicate_application_feature_flag_disabled_spec.rb
  spec/system/candidate_interface/references/candidate_submits_an_application_feature_flag_disabled_spec.rb
  spec/system/candidate_interface/submitting/candidate_submitting_application_feature_flag_disabled_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_feature_flag_disabled_spec.rb
Labels: deploy

#7527 Update our hesa questionnaire sex question
  app/exports/common_columns/_common_columns.yml
  app/models/publications/monthly_statistics/by_sex.rb
  app/services/support_interface/applications_by_demographic_domicile_and_degree_class_export.rb
  app/views/candidate_interface/equality_and_diversity/edit_sex.html.erb
  config/locales/candidate_interface/equality_and_diversity.yml
  config/register-api.yml
  spec/components/provider_interface/diversity_information_component_spec.rb
  spec/factories/application_form.rb
  spec/models/publications/monthly_statistics/by_age_group_spec.rb
  spec/models/publications/monthly_statistics/by_area_spec.rb
  spec/models/publications/monthly_statistics/by_course_age_group_spec.rb
  spec/models/publications/monthly_statistics/by_course_type_spec.rb
  spec/models/publications/monthly_statistics/by_provider_area_spec.rb
  spec/models/publications/monthly_statistics/by_secondary_subject_spec.rb
  spec/models/publications/monthly_statistics/by_sex_spec.rb
  spec/models/publications/monthly_statistics/by_status_spec.rb
  spec/requests/data_api/applications_by_demographic_domicile_and_degree_class_export_spec.rb
  spec/services/support_interface/ministerial_report_applications_export_spec.rb
  spec/services/support_interface/ministerial_report_candidates_export_spec.rb
  spec/support/statistics_test_helper.rb
Labels: deploy

#7264 Updated reasons for rejection
  config/locales/provider_interface/rejections.yml
  config/rejection_reason_codes.yml
  config/rejection_reasons.yml
  spec/models/candidate_interface/rejection_reasons_history_spec.rb
Labels: deploy

#7536 Remove terraform from dependabot checks
  .github/dependabot.yml
Labels: DevOps

#7558 756 dont allow candidates to apply to courses which arent open yet
  app/forms/candidate_interface/pick_course_form.rb
  app/forms/candidate_interface/pick_provider_form.rb
  spec/forms/candidate_interface/pick_course_form_spec.rb
  spec/forms/candidate_interface/pick_provider_form_spec.rb
  spec/system/provider_interface/see_applications_for_accrediting_provider_spec.rb
Labels: deploy

#7559 Fix some email subjects/contents
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/conditions_met.text.erb
  app/views/candidate_mailer/reinstated_offer.text.erb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
Labels: deploy

#7560 Temporarily redirect monthly statistics
  app/controllers/publications/monthly_statistics_controller.rb
  app/views/publications/monthly_statistics/temporarily_unavailable.html.erb
  app/workers/detect_invariants_daily_check.rb
  config/routes.rb
  spec/requests/publications/monthly_statistics_spec.rb
  spec/system/monthly_statistics/monthly_statistics_page_spec.rb
  spec/workers/detect_invariants_daily_check_spec.rb
Labels: deploy

#7564 Update accessibility statements
  app/views/content/accessibility.md
  app/views/content/accessibility_candidate.html.erb
Labels: deploy

#7480 Move CF and DB github secrets to Azure keyvault
  .github/workflows/database-backup.yml
  .github/workflows/restore-production-snapshot.yml
Labels: DevOps

#7578 Remove GitHub action minor version pinning
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/delete-review-app.yml
Labels: DevOps, deploy, github_actions

#7576 Don't try to render grade details for qualifications marked as missing
  app/decorators/application_qualification_decorator.rb
  spec/decorators/application_qualification_decorator_spec.rb
Labels: deploy

#7575 Use `ActionController::Live` to better handle streaming of files
  app/controllers/concerns/streamable_data_export.rb
  app/controllers/provider_interface/application_data_export_controller.rb
  app/controllers/provider_interface/reports/hesa_exports_controller.rb
  app/controllers/support_interface/providers_controller.rb
  app/services/provider_interface/hesa_data_export.rb
  spec/controllers/concerns/streamable_data_export_spec.rb
  spec/system/provider_interface/provider_user_exports_applications_to_csv_spec.rb
Labels: deploy

#7577 755 update the equality and diversity survey
  app/components/candidate_interface/equality_and_diversity_review_component.rb
  app/controllers/candidate_interface/equality_and_diversity_controller.rb
  app/views/candidate_interface/equality_and_diversity/edit_disabilities.html.erb
  app/views/candidate_interface/equality_and_diversity/edit_ethnic_background.html.erb
  app/views/candidate_interface/equality_and_diversity/edit_ethnic_group.html.erb
  app/views/candidate_interface/equality_and_diversity/edit_free_school_meals.html.erb
  app/views/candidate_interface/equality_and_diversity/edit_sex.html.erb
  app/views/layouts/_footer_meta_candidate.html.erb
  spec/components/candidate_interface/equality_and_diversity_review_component_spec.rb
  spec/requests/candidate_interface/equality_and_diversity_review_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/entering_details/candidate_entering_equality_and_diversity_information_spec.rb
Labels: deploy

#7345 Replace Cypress
  .env.example
  .env.test
  .github/actions/deploy/action.yml
  .github/workflows/build-and-deploy.yml
  .gitignore
  .rspec
  Gemfile
  Makefile
  app/controllers/apply_mailers_controller.rb
  app/lib/hosting_environment.rb
  app/views/layouts/mailer.html.erb
  bin/smoke
  config/application.rb
  config/environments/test.rb
  config/initializers/mailer_previews.rb
  config/initializers/okcomputer.rb
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/candidate.spec.js
  cypress/integration/components.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  docs/environment-variables.md
  lib/healthchecks.rb
  lib/healthchecks/notify_check.rb
  lib/healthchecks/simulated_failure_check.rb
  package.json
  spec/controllers/rails/mailers_controller_spec.rb
  spec/healthchecks/notify_check_spec.rb
  spec/healthchecks/simulated_failure_check_spec.rb
  spec/rails_helper.rb
  spec/services/support_interface/application_references_export_spec.rb
  spec/services/support_interface/applications_export_spec.rb
  spec/services/support_interface/candidate_journey_tracking_export_spec.rb
  spec/services/support_interface/tad_provider_stats_export_spec.rb
  spec/smoke/candidate_login_spec.rb
  spec/spec_helper.rb
  spec/support/bullet.rb
  spec/support/capybara.rb
  spec/support/healthcheck_matchers.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_withdraws_spec.rb
  yarn.lock
Labels: deploy, github_actions
