Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-05, with the labels that each got.

#6845 Course Change - Feature flag clean up
  app/components/support_interface/application_choice_component.rb
  app/controllers/provider_interface/application_choices_controller.rb
  app/controllers/provider_interface/courses_controller.rb
  app/controllers/support_interface/application_forms/courses_controller.rb
  app/errors/course_choice_error.rb
  app/errors/provider_interview_error.rb
  app/forms/support_interface/application_forms/change_course_choice_form.rb
  app/models/application_form.rb
  app/services/data_migrations/drop_change_course_details_before_offer_feature_flag.rb
  app/services/feature_flag.rb
  app/services/support_interface/change_application_choice_course_option.rb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/support_interface/application_forms/courses/edit.html.erb
  config/locales/support_interface/support_interface.yml
  config/routes.rb
  docs/support_playbook.md
  lib/tasks/data.rake
  spec/components/support_interface/application_choice_component_spec.rb
  spec/forms/support_interface/application_forms/change_course_choice_form_spec.rb
  spec/models/application_form_spec.rb
  spec/requests/provider_interface/courses_controller_spec.rb
  spec/services/data_migrations/drop_change_course_details_before_offer_feature_flag_spec.rb
  spec/services/support_interface/change_application_choice_course_option_spec.rb
  spec/system/provider_interface/provider_changes_a_course_before_point_of_offer_spec.rb
  spec/system/provider_interface/provider_exits_journey_when_changing_a_course_before_an_offer_spec.rb
  spec/system/support_interface/change_course_choice_spec.rb
Labels: deploy

#6904 Update copy to reflect duplicate matching email
  app/views/candidate_interface/unsubmitted_application_form/review.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  spec/system/candidate_interface/references/candidate_submits_a_duplicate_application_spec.rb
Labels: deploy

#6912 Site UUIDS: Create a new TempSite model
  app/models/temp_site.rb
  config/analytics_blocklist.yml
  db/migrate/20220504100117_create_temp_sites.rb
  db/schema.rb
  docs/domain-model.png
  spec/factories/temp_sites.rb
  spec/models/temp_site_spec.rb
Labels: ProVendor

#6918 Update label for Role to Job title or role
  config/locales/candidate_interface/restructured_work_history.yml
Labels: Candidate, deploy

#6916 Increase char limit for job role from 60 to 100
  app/forms/candidate_interface/restructured_work_history/job_form.rb
  spec/forms/candidate_interface/restructured_work_history/job_form_spec.rb
Labels: Candidate, deploy

#6903 Changes to vendor API docs for version change
  app/views/api_docs/vendor_api_docs/pages/home.md
  app/views/api_docs/vendor_api_docs/reference/draft.html.erb
Labels: deploy

#6921 Upgrade Vendor API to v1.1
  app/controllers/api_docs/vendor_api_docs/pages_controller.rb
  app/lib/vendor_api.rb
  app/views/api_docs/vendor_api_docs/pages/home.md
  app/views/api_docs/vendor_api_docs/pages/release_notes.md
  app/views/api_docs/vendor_api_docs/reference/reference.html.erb
Labels: DO NOT MERGE, deploy

#6923 Degree flow bug
  app/components/candidate_interface/degree_new_review_component.rb
  app/controllers/candidate_interface/degrees/degree/destroy_controller.rb
  spec/components/candidate_interface/degree_new_review_component_spec.rb
  spec/system/candidate_interface/entering_details/degrees/new_degree_flow/candidate_delete_and_replace_degrees_spec.rb
Labels: deploy

#6925 Don't render conditions if the status is 'met'
  app/views/candidate_mailer/_offer_conditions.text.erb
  app/views/candidate_mailer/reinstated_offer.text.erb
  spec/mailers/candidate_mailer_spec.rb
Labels: deploy

#6939 Fix Available courses failing to scope to current cycle bug
  app/forms/support_interface/application_forms/pick_course_form.rb
  spec/forms/support_interface/application_forms/pick_course_form_spec.rb
Labels: deploy

#6931 Include SR4R in application data exports
  app/services/provider_interface/application_data_export.rb
  spec/services/provider_interface/application_data_export_spec.rb
Labels: deploy

#6940 Amend LEFT OUTER JOIN so it operates on current course
  app/queries/get_application_progress_data_by_course.rb
  spec/queries/get_application_progress_data_by_course_spec.rb
Labels: deploy

#6947 Cancel link added to the export application data page
  app/views/provider_interface/application_data_export/new.html.erb
Labels: deploy

#6950 Change form data type from boolean to string
  app/views/candidate_interface/volunteering/role/_form.html.erb
  spec/system/candidate_interface/entering_details/candidate_entering_volunteering_experience_spec.rb
Labels: deploy

#6942 Site UUIDs: start syncing the temp sites using a UUID
  app/models/provider.rb
  app/services/teacher_training_public_api/assign_temp_site_attributes.rb
  app/services/teacher_training_public_api/sync_sites.rb
  spec/examples/teacher_training_api/site_list_response_with_full_time_and_part_time_vacancies.json
  spec/examples/teacher_training_api/site_list_response_with_full_time_vacancies.json
  spec/examples/teacher_training_api/site_list_response_with_part_time_vacancies.json
  spec/services/teacher_training_public_api/assign_temp_site_attributes_spec.rb
  spec/services/teacher_training_public_api/sync_sites_spec.rb
  spec/system/find_sync/syncing_providers_spec.rb
  spec/system/teacher_training_public_api/site_is_deleted_spec.rb
Labels: deploy

#6943 Add dr docs data loss
  .github/workflows/database-backup.yml
  .gitignore
  .tool-versions
  Makefile
  bin/download-nightly-backup
  bin/restore-nightly-backup
  docs/disaster-recovery.md
  docs/maintenance-mode.md
Labels: DevOps, deploy

#6945 Remove legacy Languages section
  app/components/candidate_interface/personal_details_review_component.rb
  app/controllers/candidate_interface/personal_details/immigration_status_controller.rb
  app/controllers/candidate_interface/personal_details/languages_controller.rb
  app/controllers/candidate_interface/personal_details/nationalities_controller.rb
  app/controllers/candidate_interface/personal_details/review_controller.rb
  app/forms/candidate_interface/languages_form.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/services/duplicate_application.rb
  app/services/languages_section_policy.rb
  app/views/candidate_interface/personal_details/languages/_shared_form.html.erb
  app/views/candidate_interface/personal_details/languages/edit.html.erb
  app/views/candidate_interface/personal_details/languages/new.html.erb
  app/views/candidate_interface/personal_details/review/show.html.erb
  config/routes.rb
  spec/forms/candidate_interface/languages_form_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/requests/candidate_interface/redirects_spec.rb
  spec/services/languages_section_policy_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_when_languages_hidden_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_adjustments_section_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_contact_details_section_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_details_section_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_qualifications_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_safeguarding_section_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_unpaid_experience_section_spec.rb
Labels: deploy

#6826 Remove application_number_replacement feature flag uses
  app/components/provider_interface/application_card_component.html.erb
  app/components/provider_interface/application_summary_component.rb
  app/components/provider_interface/personal_information_component.rb
  app/components/utility/filter_component.html.erb
  app/services/data_migrations/remove_application_number_replacement_feature_flag.rb
  app/services/feature_flag.rb
  app/services/filter_application_choices_for_providers.rb
  lib/tasks/data.rake
  spec/components/provider_interface/application_card_component_spec.rb
  spec/components/provider_interface/application_summary_component_spec.rb
  spec/components/provider_interface/personal_information_component_spec.rb
  spec/services/data_migrations/remove_application_number_replacement_feature_flag_spec.rb
  spec/services/filter_application_choices_for_providers_spec.rb
  spec/system/provider_interface/provider_applications_search_spec.rb
  spec/system/provider_interface/see_applications_spec.rb
Labels: DO NOT MERGE, deploy

#6878 Email click tracking
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/mailers/candidate_mailer.rb
  app/models/email.rb
  app/models/email_click.rb
  app/views/candidate_mailer/_still_interested_content.text.erb
  app/views/candidate_mailer/_wait_or_respond.text.erb
  app/views/candidate_mailer/application_rejected_offers_only.text.erb
  app/views/candidate_mailer/application_rejected_one_offer_one_awaiting_decision.text.erb
  app/views/candidate_mailer/application_submitted.text.erb
  app/views/candidate_mailer/application_withdrawn_on_request_one_offer_one_awaiting_decision.text.erb
  app/views/candidate_mailer/changed_offer.text.erb
  app/views/candidate_mailer/chase_candidate_decision.text.erb
  app/views/candidate_mailer/chase_reference.text.erb
  app/views/candidate_mailer/chase_reference_again.text.erb
  app/views/candidate_mailer/deferred_offer_reminder.text.erb
  app/views/candidate_mailer/eoc_deadline_reminder.erb
  app/views/candidate_mailer/feedback_received_for_application_rejected_by_default.text.erb
  app/views/candidate_mailer/find_another_course.text.erb
  app/views/candidate_mailer/find_has_opened.erb
  app/views/candidate_mailer/new_offer/multiple_offers.text.erb
  app/views/candidate_mailer/new_offer/single_offer.text.erb
  app/views/candidate_mailer/new_referee_request.text.erb
  app/views/candidate_mailer/nudge_unsubmitted.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_courses.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_personal_statement.text.erb
  app/views/candidate_mailer/offer_accepted.text.erb
  app/views/candidate_mailer/reference_received.text.erb
  app/views/candidate_mailer/reinstated_offer.text.erb
  config/analytics.yml
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_email_tracking_spec.rb
Labels: Candidate, deploy

#6941 Implement references nudge
  app/mailers/candidate_mailer.rb
  app/models/application_reference.rb
  app/queries/get_incomplete_reference_applications_ready_to_nudge.rb
  app/services/feature_flag.rb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_references/no_references.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_references/one_received_reference.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_references/one_requested_reference.text.erb
  app/workers/nudge_candidates_worker.rb
  config/brakeman.ignore
  config/locales/application_states.yml
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/queries/get_incomplete_reference_applications_ready_to_nudge_spec.rb
Labels: Candidate, deploy

#6965 Deploy review apps for dependabot PRs
  .github/workflows/build-and-deploy.yml
  .github/workflows/delete-review-app.yml
Labels: DevOps

#6969 Fix delete-review-app workflow
  .github/workflows/delete-review-app.yml
Labels: DevOps

#6933 Rename and applications data export reorder columns
  app/services/provider_interface/application_data_export.rb
  spec/services/provider_interface/application_data_export_spec.rb
  spec/system/provider_interface/provider_user_exports_applications_to_csv_spec.rb
Labels: deploy

#6957 Integrate DfE::Analytics
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/concerns/emit_request_events.rb
  app/forms/candidate_interface/sign_up_form.rb
  app/lib/bigquery/entity_event.rb
  app/lib/bigquery/field_list.rb
  app/lib/bigquery/import_entity_events.rb
  app/lib/concerns/bigquery_data_conversion.rb
  app/lib/events/event.rb
  app/models/application_record.rb
  app/models/concerns/entity_events.rb
  config/initializers/bigquery.rb
  config/initializers/dfe-analytics.rb
  docs/bigquery.md
  lib/tasks/bigquery_fields.rake
  lib/tasks/import_data_to_bigquery.rake
  spec/forms/candidate_interface/sign_up_form_spec.rb
  spec/lib/bigquery/entity_event_spec.rb
  spec/lib/bigquery/field_list_spec.rb
  spec/lib/bigquery/import_entity_events_spec.rb
  spec/lib/events/event_spec.rb
  spec/models/concerns/entity_events_spec.rb
  spec/requests/emit_request_events_spec.rb
  spec/support/bigquery.rb
  spec/workers/send_events_to_bigquery_spec.rb
Labels: deploy

#7005 Skip cypress tests for rollover deployment
  .github/actions/deploy/action.yml
Labels: deploy

#6966 Enable user to return to application review page
  app/controllers/candidate_interface/degrees/degree/review_controller.rb
  app/controllers/candidate_interface/degrees/degree_controller.rb
  app/forms/candidate_interface/degree_wizard.rb
  app/views/candidate_interface/degrees/degree/new_country.html.erb
  spec/system/candidate_interface/entering_details/degrees/new_degree_flow/backlinks_spec.rb
  spec/system/candidate_interface/entering_details/degrees/new_degree_flow/candidate_editing_degrees_spec.rb
Labels: deploy

#6994 Backfill TempSites from TTAPI
  app/services/data_migrations/backfill_temp_sites.rb
  app/workers/migrate_temp_sites_for_providers_worker.rb
  config/analytics_blocklist.yml
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_temp_sites_spec.rb
  spec/workers/migrate_temp_sites_for_providers_worker_spec.rb
Labels: deploy

#7011 Add guidance page for Organisation Permissions
  app/controllers/provider_interface/content_controller.rb
  app/views/content/organisation_permissions.md
  app/views/provider_interface/content/service_guidance_provider.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: deploy

#7010 Run sandbox and rollover deploys in parallel
  .github/workflows/build-and-deploy.yml
Labels: DevOps

#7035 Update cycle dates
  app/services/cycle_timetable.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
Labels: deploy
