Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-08, with the labels that each got.

#7234 New References - Manage carry over
  app/components/candidate_interface/new_references_section_component.html.erb
  app/components/candidate_interface/new_references_section_component.rb
  app/services/duplicate_application.rb
  app/views/candidate_interface/unsubmitted_application_form/_task_list.html.erb
  spec/services/carry_over_application_spec.rb
  spec/services/duplicate_application_spec.rb
  spec/system/candidate_api/candidate_api_application_state_change_triggers_update_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_application_with_references_to_new_cycle_and_referee_provides_reference_spec.rb
  spec/system/candidate_interface/references/candidate_carries_over_unsubmitted_application_to_new_reference_flow_spec.rb
  spec/system/candidate_interface/references/candidate_carries_over_unsuccessful_application_to_new_cycle_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
  spec/workers/chase_references_spec.rb
Labels: New reference flow

#7261 New References – Reference section on the application review page
  app/components/candidate_interface/complete_references_component.html.erb
  app/components/candidate_interface/complete_references_component.rb
  app/components/candidate_interface/incomplete_new_references_section_component.rb
  app/components/candidate_interface/new_references_review_component.html.erb
  app/components/candidate_interface/new_references_review_component.rb
  app/controllers/candidate_interface/new_references/base_controller.rb
  app/controllers/candidate_interface/new_references/email_address_controller.rb
  app/controllers/candidate_interface/new_references/name_controller.rb
  app/controllers/candidate_interface/new_references/relationship_controller.rb
  app/controllers/candidate_interface/new_references/review_controller.rb
  app/controllers/candidate_interface/new_references/type_controller.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/services/cycle_timetable.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/new_references/review/show.html.erb
  config/locales/candidate_interface/references.yml
  config/locales/candidate_interface/review_application.yml
  spec/components/candidate_interface/new_references_review_component_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_references_feature_flag_new_references_enabled_spec.rb
  spec/system/candidate_interface/submitting/candidate_submits_application_with_missing_references_feature_flag_enabled_spec.rb
Labels: deploy, New reference flow

#7270 427 references candidate offer acceptance reference flow
  app/components/candidate_interface/accept_offer_add_new_reference_component.html.erb
  app/components/candidate_interface/accept_offer_add_new_reference_component.rb
  app/components/candidate_interface/add_new_reference_component.rb
  app/components/candidate_interface/new_references_accept_offer_review_component.rb
  app/components/candidate_interface/new_references_review_component.html.erb
  app/components/candidate_interface/new_references_review_component.rb
  app/components/shared/add_new_reference_helpers.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/decisions_controller.rb
  app/controllers/candidate_interface/new_references/accept_offer/email_address_controller.rb
  app/controllers/candidate_interface/new_references/accept_offer/name_controller.rb
  app/controllers/candidate_interface/new_references/accept_offer/relationship_controller.rb
  app/controllers/candidate_interface/new_references/accept_offer/review_controller.rb
  app/controllers/candidate_interface/new_references/accept_offer/type_controller.rb
  app/controllers/candidate_interface/new_references/email_address_controller.rb
  app/controllers/candidate_interface/new_references/name_controller.rb
  app/controllers/candidate_interface/new_references/relationship_controller.rb
  app/controllers/candidate_interface/new_references/review_controller.rb
  app/controllers/candidate_interface/new_references/type_controller.rb
  app/controllers/concerns/accept_offer_confirm_references.rb
  app/controllers/concerns/accept_offer_new_references_path.rb
  app/services/accept_offer.rb
  app/views/candidate_interface/decisions/accept_offer.html.erb
  app/views/candidate_interface/new_references/email_address/edit.html.erb
  app/views/candidate_interface/new_references/email_address/new.html.erb
  app/views/candidate_interface/new_references/name/edit.html.erb
  app/views/candidate_interface/new_references/name/new.html.erb
  app/views/candidate_interface/new_references/relationship/edit.html.erb
  app/views/candidate_interface/new_references/relationship/new.html.erb
  app/views/candidate_interface/new_references/review/confirm_destroy_reference.html.erb
  app/views/candidate_interface/new_references/type/edit.html.erb
  app/views/candidate_interface/new_references/type/new.html.erb
  config/locales/candidate_interface/accept_offer.yml
  config/locales/en.yml
  config/locales/provider_interface/decisions.yml
  config/routes.rb
  spec/components/candidate_interface/accept_offer_add_new_reference_component_spec.rb
  spec/services/accept_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_new_reference_feature_disabled_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_new_reference_feature_enabled_spec.rb
Labels: deploy, New reference flow

#7287 New References - Confirm apply again will handle references correctly
  spec/system/candidate_interface/new-references/candidate_apply_again_new_references_flow_spec.rb
Labels: New reference flow

#7280 Add course full details text field
  app/components/candidate_interface/rejection_reasons/rejection_reasons_component.html.erb
  app/components/shared/rejection_reasons/rejection_reasons_component.html.erb
  app/models/rejection_reasons/details.rb
  app/presenters/rejection_reasons/rejection_reasons_presenter.rb
  config/rejection_reasons.yml
  spec/components/shared/rejection_reasons/rejection_reasons_component_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/models/rejection_reasons/details_spec.rb
  spec/presenters/rejection_reasons/rejection_reasons_presenter_spec.rb
  spec/system/provider_interface/reject_an_application_spec.rb
Labels: deploy

#7299 [596] Simplify delete review app AZURE_STORAGE_CONNECTION_STRING
  .github/workflows/delete-review-app.yml
Labels: DevOps

#7296 New References - post offer dashboard
  app/components/candidate_interface/conditions_component.html.erb
  app/components/candidate_interface/conditions_component.rb
  app/components/candidate_interface/new_reference_history_component.html.erb
  app/components/candidate_interface/new_reference_history_component.rb
  app/components/candidate_interface/new_reference_send_reminder_component.html.erb
  app/components/candidate_interface/new_reference_send_reminder_component.rb
  app/components/candidate_interface/new_reference_statuses_component.html.erb
  app/components/candidate_interface/new_reference_statuses_component.rb
  app/components/candidate_interface/new_references_review_component.html.erb
  app/components/candidate_interface/new_references_review_component.rb
  app/components/candidate_interface/references_component.html.erb
  app/components/candidate_interface/references_component.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/new_references/base_controller.rb
  app/controllers/candidate_interface/new_references/cancel_controller.rb
  app/controllers/candidate_interface/new_references/reminder_controller.rb
  app/controllers/candidate_interface/offer_dashboard_controller.rb
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  app/services/accept_offer.rb
  app/services/reference_actions_policy.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/new_references/cancel/new.html.erb
  app/views/candidate_interface/new_references/reminder/new.html.erb
  app/views/candidate_interface/new_references/review/show.html.erb
  app/views/candidate_interface/offer_dashboard/show.html.erb
  app/views/candidate_interface/offer_dashboard/view_reference.html.erb
  config/locales/candidate_interface/candidate_reference_status.yml
  config/locales/candidate_interface/new_references.yml
  config/locales/en.yml
  config/routes.rb
  spec/components/candidate_interface/new_reference_history_component_spec.rb
  spec/components/candidate_interface/new_reference_send_reminder_component_spec.rb
  spec/components/candidate_interface/new_references_review_component_spec.rb
  spec/components/candidate_interface/references_component_spec.rb
  spec/requests/candidate_interface/new_references_accepted_offer_spec.rb
  spec/services/accept_offer_spec.rb
  spec/system/candidate_interface/new-references/candidate_views_their_references_on_the_post_offer_dashboard_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_new_reference_feature_enabled_spec.rb
Labels: deploy, New reference flow

#7309 Update email subject line in smoke test
  cypress/plugins/index.js
Labels: deploy

#7302 428 references post offer dashboard request references
  app/components/candidate_interface/new_reference_history_component.html.erb
  app/components/candidate_interface/new_references_review_component.rb
  app/components/candidate_interface/request_reference_review_component.html.erb
  app/components/candidate_interface/request_reference_review_component.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/new_references/request_reference/email_address_controller.rb
  app/controllers/candidate_interface/new_references/request_reference/name_controller.rb
  app/controllers/candidate_interface/new_references/request_reference/relationship_controller.rb
  app/controllers/candidate_interface/new_references/request_reference/review_controller.rb
  app/controllers/candidate_interface/new_references/request_reference/start_controller.rb
  app/controllers/candidate_interface/new_references/request_reference/type_controller.rb
  app/controllers/candidate_interface/offer_dashboard_controller.rb
  app/controllers/concerns/request_reference_new_references_path.rb
  app/controllers/concerns/request_reference_offer_dashboard.rb
  app/views/candidate_interface/new_references/request_reference/review/new.html.erb
  app/views/candidate_interface/new_references/request_reference/start/new.html.erb
  app/views/candidate_interface/offer_dashboard/show.html.erb
  config/locales/candidate_interface/new_references.yml
  config/locales/en.yml
  config/routes.rb
  spec/components/candidate_interface/new_reference_history_component_spec.rb
  spec/requests/candidate_interface/new_references_request_references_spec.rb
  spec/requests/candidate_interface/new_references_view_reference_redirect_spec.rb
  spec/system/candidate_interface/new-references/candidate_request_references_new_references_spec.rb
  spec/system/candidate_interface/new-references/candidate_views_their_references_on_the_post_offer_dashboard_spec.rb
Labels: deploy

#7295 Improve content of email when creating an account
  app/views/authentication_mailer/sign_up_email.text.erb
  config/locales/candidate_interface/authentication.yml
  cypress/plugins/index.js
  spec/mailers/authentication_mailer_spec.rb
Labels: deploy

#7314 Redirect to the review page after deleting a reference
  app/controllers/candidate_interface/new_references/review_controller.rb
  spec/requests/candidate_interface/new_references_delete_reference_spec.rb
Labels: deploy

#7319 New References - feature flag for Manage
  app/services/feature_flag.rb
Labels: New reference flow

#7320 Fix back link when cancel a request in the offer dashboard
  app/components/candidate_interface/new_reference_history_component.html.erb
  app/controllers/candidate_interface/new_references/cancel_controller.rb
  app/views/candidate_interface/new_references/cancel/new.html.erb
  spec/system/candidate_interface/new-references/candidate_request_references_new_references_spec.rb
Labels: deploy

#7330 Content changes to the post offer dashboard
  app/components/candidate_interface/references_component.html.erb
  app/views/candidate_interface/offer_dashboard/show.html.erb
  spec/system/candidate_interface/new-references/candidate_request_references_new_references_spec.rb
  spec/system/candidate_interface/new-references/candidate_views_their_references_on_the_post_offer_dashboard_spec.rb
Labels: New reference flow

#7327 433 new references tab on manage
  app/components/provider_interface/application_choice_header_component.rb
  app/components/provider_interface/new_reference_with_feedback_component.html.erb
  app/components/provider_interface/new_reference_with_feedback_component.rb
  app/controllers/provider_interface/references_controller.rb
  app/models/application_choice.rb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/provider_interface/references/_references.html.erb
  app/views/provider_interface/references/index.html.erb
  config/routes.rb
  spec/components/provider_interface/new_reference_with_feedback_component_spec.rb
  spec/system/provider_interface/provider_views_the_references_tab_on_manage_spec.rb
  spec/system/provider_interface/see_individual_application_spec.rb
Labels: deploy, New reference flow

#7344 Add Roma to White ethnicity group
  config/initializers/ethnicities.rb
Labels: deploy

#7359 New references flow - Update offer confirmation page
  app/components/candidate_interface/offer_conditions_review_component.html.erb
  app/components/provider_interface/deferred_offer_details_component.html.erb
  app/components/provider_interface/offer_summary_component.html.erb
  app/views/provider_interface/offer/conditions/_form.html.erb
  spec/components/candidate_interface/application_dashboard_course_choices_component_spec.rb
  spec/system/provider_interface/make_offer_spec.rb
Labels: New reference flow
