Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-09, with the labels that each got.

#7353 Add Check Service Principal workflow
  .github/workflows/check_sp.yml
Labels: DevOps

#7378 New references – Update candidate reference guidance
  app/components/candidate_interface/add_new_reference_component.html.erb
Labels: New reference flow

#7380 New references - Update the school based referee guidance
  config/locales/candidate_interface/new_references.yml
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_new_reference_feature_enabled_spec.rb
Labels: New reference flow

#7379 New references - Change the candidate wording for referee relationship
  app/components/candidate_interface/new_references_review_component.rb
  app/views/candidate_interface/offer_dashboard/view_reference.html.erb
  config/locales/candidate_interface/review_application.yml
  spec/components/candidate_interface/new_references_review_component_spec.rb
Labels: New reference flow

#7382 New references - Update the carry over interstitial to mention references
  app/components/candidate_interface/carry_over_interstitial_component.html.erb
  spec/components/candidate_interface/carry_over_interstitial_component_spec.rb
  spec/system/candidate_interface/course_selection/candidate_attempts_to_add_course_from_find_to_application_from_previous_cycle_spec.rb
Labels: deploy, New reference flow

#7383 New references - Update the content for references the candidate has already received
  app/components/candidate_interface/new_references_review_component.rb
  config/locales/candidate_interface/new_references.yml
  spec/components/candidate_interface/new_references_review_component_spec.rb
  spec/system/candidate_interface/new-references/candidate_apply_again_new_references_flow_spec.rb
Labels: New reference flow

#7381 New references - remove the mention of referees from the reference journey
  config/locales/candidate_interface/new_references.yml
  config/locales/candidate_interface/references.yml
  config/locales/en.yml
  spec/system/candidate_interface/new-references/candidate_add_references_spec.rb
  spec/system/candidate_interface/new-references/candidate_request_references_new_references_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_new_reference_feature_enabled_spec.rb
  spec/system/candidate_interface/references/candidate_adds_a_new_reference_feature_flag_disabled_spec.rb
  spec/system/candidate_interface/references/candidate_requests_a_reference_spec.rb
Labels: deploy, New reference flow

#7364 Improve the updated interview email
  app/controllers/provider_interface/courses_controller.rb
  app/mailers/candidate_mailer.rb
  app/services/update_interviews_provider.rb
  app/views/candidate_mailer/interview_updated.text.erb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/update_interviews_provider_spec.rb
Labels: deploy

#7394 Add Terraform check to dependabot
  .github/dependabot.yml
Labels: DevOps

#7269 Improve confirm sign in page
  app/controllers/candidate_interface/sign_in_controller.rb
  app/models/candidate.rb
  app/views/candidate_interface/sign_in/confirm_authentication.html.erb
  app/views/candidate_interface/sign_in/confirm_create_account.html.erb
  app/views/candidate_interface/sign_in/confirm_sign_in.html.erb
  config/locales/candidate_interface/authentication.yml
  cypress/integration/candidate.spec.js
  spec/factories/candidate.rb
  spec/support/test_helpers/sign_in_helper.rb
  spec/system/candidate_api/candidate_api_application_state_change_triggers_update_spec.rb
  spec/system/candidate_interface/course_selection/candidate_new_user_with_course_params_and_cancel_spec.rb
  spec/system/candidate_interface/course_selection/candidate_new_user_with_course_params_spec.rb
  spec/system/candidate_interface/course_selection/sandbox_user_apply_from_find_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_account_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_up_using_magic_link_with_an_invalid_token_spec.rb
  spec/system/candidate_interface/signup_and_signin/two_candidates_sign_in_on_same_machine_spec.rb
Labels: deploy

#7407 Render the make decision features on the references tab
  app/controllers/provider_interface/references_controller.rb
  app/views/provider_interface/references/index.html.erb
Labels: New reference flow

#7403 Post DR test documentation updates
  docs/disaster-recovery.md
Labels: DevOps

#7423 Improve Cypress specs and outputs
  .github/actions/deploy/action.yml
  cypress/integration/candidate.spec.js
Labels: deploy

#7406 Relax application states rules when changing courses
  app/components/support_interface/application_choice_component.rb
  app/controllers/support_interface/application_forms/courses_controller.rb
  app/services/support_interface/change_application_choice_course_option.rb
  app/views/support_interface/application_forms/courses/edit.html.erb
  spec/components/support_interface/application_choice_component_spec.rb
  spec/forms/support_interface/application_forms/change_course_choice_form_spec.rb
  spec/services/support_interface/change_application_choice_course_option_spec.rb
Labels: deploy

#7417 Update link in 'Find has opened' email
  app/views/candidate_mailer/find_has_opened.erb
  spec/mailers/candidate_mailer_spec.rb
Labels: deploy

#7425 Improved content for start of cycle candidate emails
  app/views/candidate_mailer/new_cycle_has_started.erb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_spec.rb
Labels: deploy

#7442 Rectify spelling mistakes in the reference received email
  app/models/application_form.rb
  app/views/candidate_mailer/_new_flow_reference_received.text.erb
  spec/mailers/candidate_mailer_referee_mails_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/models/application_form_spec.rb
Labels: New reference flow

#7444 Change reference status labels and the text underneath
  app/components/candidate_interface/new_reference_status_line_component.html.erb
  app/components/candidate_interface/new_reference_status_line_component.rb
  app/components/candidate_interface/references_component.html.erb
  config/locales/candidate_interface/candidate_reference_status.yml
  config/locales/candidate_interface/new_references.yml
  spec/components/candidate_interface/new_reference_status_line_component_spec.rb
  spec/components/candidate_interface/references_component_spec.rb
  spec/system/candidate_interface/new-references/candidate_request_references_new_references_spec.rb
  spec/system/candidate_interface/new-references/candidate_views_their_references_on_the_post_offer_dashboard_spec.rb
Labels: deploy, New reference flow

#7460 List unmet conditions in conditions-not-met email
  app/views/candidate_mailer/conditions_not_met.text.erb
  bin/bundle
  bin/rspec
  config/locales/emails/candidate_mailer.yml
  spec/factories/application_choice.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/system/provider_interface/provider_marks_conditions_as_not_met_spec.rb
Labels: deploy

#7465 Generate next cycle test applications
  app/controllers/support_interface/tasks_controller.rb
  app/lib/test_applications.rb
  app/services/submit_application.rb
  app/views/support_interface/tasks/index.html.erb
  app/workers/generate_test_applications.rb
  spec/workers/generate_test_applications_spec.rb
Labels: New reference flow

#7475 Don't scope course searches by provider for course change support page
  app/forms/support_interface/application_forms/pick_course_form.rb
  app/views/support_interface/application_forms/application_choices/change_offered_course/offered_course_options.html.erb
  spec/system/support_interface/change_offered_course_for_a_submitted_application_spec.rb
Labels: deploy

#7477 Allow providers to download application references as a PDF
  app/views/provider_interface/references/index.html.erb
  spec/system/provider_interface/see_individual_application_as_pdf_spec.rb
Labels: deploy

#7493 Render post offer dashboard for recruited candidates
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/offer_dashboard_controller.rb
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  app/models/application_choice.rb
  app/views/candidate_interface/offer_dashboard/show.html.erb
  spec/system/candidate_interface/new-references/candidate_request_references_new_references_spec.rb
  spec/system/candidate_interface/new-references/candidate_views_their_references_on_the_post_offer_dashboard_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_new_reference_feature_enabled_spec.rb
Labels: deploy, New reference flow
