Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2022-01, with the labels that each got.

#6291 Fix reasons for rejection paragraph formatting bugs
  app/components/shared/reasons_for_rejection_component.html.erb
  app/components/shared/reasons_for_rejection_component.rb
  app/views/candidate_mailer/_reasons_for_rejection.text.erb
Labels: ProVendor

#6288 Update 'Confirm deferred offer' page for unavailable course
  app/views/provider_interface/reconfirm_deferred_offers/new.html.erb
Labels: ProVendor

#6255 Update provider email content and footers - application withdrawn
  app/mailers/provider_mailer.rb
  app/services/withdraw_application.rb
  app/views/provider_mailer/application_withdrawn.text.erb
  config/locales/emails/provider_mailer.yml
  spec/mailers/previews/provider_mailer_preview.rb
  spec/mailers/provider_mailer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_withdraws_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_withdraws_with_upcoming_interviews_spec.rb
Labels: ProVendor

#6289 Copy changes on offer details page
  app/views/candidate_interface/decisions/offer.html.erb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_spec.rb
Labels: Candidate

#6301 Tidy up provider_mailer
  app/mailers/provider_mailer.rb
  app/views/provider_mailer/_unsubscribe.text.erb
Labels: ProVendor

#6226 Monthly report statistics data
  app/controllers/publications/monthly_statistics_controller.rb
  app/presenters/publications/monthly_statistics_presenter.rb
  app/services/data_migrations/backfill_monthly_statistics_data.rb
  app/services/monthly_statistics_timetable.rb
  app/views/publications/monthly_statistics/show.html.erb
  app/workers/generate_monthly_statistics.rb
  config/routes.rb
  lib/tasks/data.rake
  lib/tasks/monthly_report.rake
  spec/requests/publications/monthly_statistics_spec.rb
  spec/services/data_migrations/backfill_monthly_statistics_data_spec.rb
  spec/services/monthly_statistics_timetable_spec.rb
  spec/system/monthly_statistics/monthly_statistics_page_spec.rb
  spec/workers/generate_monthly_statistics_spec.rb
Labels: Candidate

#6317 Backport External report fixes to the Ministerial report
  app/exports/external_report_applications_export.yml
  app/exports/external_report_candidates_export.yml
  app/lib/ministerial_report.rb
  app/models/data_export.rb
  app/services/support_interface/external_report_applications_export.rb
  app/services/support_interface/external_report_candidates_export.rb
  app/services/support_interface/ministerial_report_applications_export.rb
  app/services/support_interface/ministerial_report_candidates_export.rb
  config/initializers/external_report_applications.rb
  config/initializers/external_report_candidates.rb
  spec/lib/ministerial_report_spec.rb
  spec/models/publications/monthly_statistics/by_age_group_spec.rb
  spec/models/publications/monthly_statistics/by_area_spec.rb
  spec/models/publications/monthly_statistics/by_course_age_group_spec.rb
  spec/models/publications/monthly_statistics/by_course_type_spec.rb
  spec/models/publications/monthly_statistics/by_primary_specialist_subject_spec.rb
  spec/models/publications/monthly_statistics/by_provider_area_spec.rb
  spec/models/publications/monthly_statistics/by_secondary_subject_spec.rb
  spec/models/publications/monthly_statistics/by_sex_spec.rb
  spec/models/publications/monthly_statistics/by_status_spec.rb
  spec/requests/publications/monthly_statistics_spec.rb
  spec/services/support_interface/external_report_applications_export_spec.rb
  spec/services/support_interface/external_report_candidates_export_spec.rb
  spec/services/support_interface/ministerial_report_applications_export_spec.rb
  spec/services/support_interface/ministerial_report_candidates_export_spec.rb
  spec/support/monthly_statistics_test_helper.rb
  spec/support/statistics_test_helper.rb
  spec/system/monthly_statistics/monthly_statistics_page_spec.rb
  spec/workers/generate_monthly_statistics_spec.rb
Labels: Metrics & reporting

#6245 Update manage to refer to recruitment cycles consistently
  app/components/provider_interface/application_summary_component.rb
  app/models/provider_interface/provider_applications_filter.rb
  app/models/recruitment_cycle.rb
  app/models/support_interface/applications_filter.rb
  app/views/provider_interface/application_data_export/new.html.erb
  spec/models/recruitment_cycle_spec.rb
  spec/support/test_helpers/cycle_timetable_helper.rb
Labels: ProVendor

#6316 Fix paragraph formatting for remaining R4R Other fields
  app/components/shared/reasons_for_rejection_component.html.erb
  spec/system/candidate_interface/rejection/candidate_reviews_reasons_for_rejection_spec.rb
Labels: ProVendor

#6320 Rename Yabeda exported_instance label
  config/initializers/yabeda.rb
Labels: DevOps, deploy

#6244 Add `Candidate#submission_blocked`
  app/components/support_interface/fraud_auditing_matches_table_component.rb
  app/forms/support_interface/block_submission_form.rb
  app/forms/support_interface/unblock_submission_form.rb
  app/services/data_migrations/backfill_candidates_submission_blocked.rb
  app/views/candidate_interface/unsubmitted_application_form/review.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  lib/tasks/data.rake
  spec/components/support_interface/fraud_auditing_matches_table_component_spec.rb
  spec/factories/course_option.rb
  spec/factories/site.rb
  spec/forms/support_interface/block_submission_form_spec.rb
  spec/forms/support_interface/unblock_submission_form_spec.rb
  spec/services/data_migrations/backfill_candidates_submission_blocked_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/references/candidate_submits_a_duplicate_application_spec.rb
  spec/system/support_interface/duplicate_candidate_matches_spec.rb
Labels: Candidate

#6314 Fix domicile codes for test applications
  spec/factories/application_form.rb
Labels: ProVendor

#6339 Use the new secrets action
  .github/workflows/deploy.yml
Labels: deploy

#6343 Amend vendor api caching to respect version of the api
  app/presenters/vendor_api/application_presenter.rb
  app/presenters/vendor_api/base.rb
  spec/presenters/vendor_api/application_presenter_spec.rb
Labels: ProVendor, API

#6329 Tighten phone number validation
  app/forms/candidate_interface/contact_details_form.rb
  app/validators/phone_number_validator.rb
  config/locales/candidate_interface/contact_details.yml
  spec/forms/candidate_interface/contact_details_form_spec.rb
  spec/validators/phone_number_validator_spec.rb
Labels: deploy

#6363 Update HESA report info text for previous cycles
  app/views/provider_interface/reports/hesa_exports/index.html.erb
  config/locales/provider_interface/reports.yml
  spec/system/provider_interface/export_applications_in_hesa_format_spec.rb
Labels: deploy

#6326 Handle removed conditions in the offer wizard
  app/forms/concerns/wizard.rb
  app/forms/provider_interface/offer_wizard.rb
  spec/system/provider_interface/provider_changes_conditions_on_an_offer_spec.rb
  spec/system/provider_interface/provider_removes_conditions_from_an_offer_spec.rb
Labels: ProVendor

#6367 Change daily API integration reports from vendor slack channels to weekly
  app/models/support_interface/vendor_api_monitor.rb
  app/workers/vendor_integration_stats_worker.rb
  config/clock.rb
  spec/models/support_interface/vendor_api_monitor_spec.rb
  spec/workers/vendor_integration_stats_worker_spec.rb
Labels: ProVendor

#6368 Update header component homepage_url to be configurable
  app/components/utility/header_component.html.erb
  app/components/utility/header_component.rb
  app/views/layouts/_header.html.erb
  spec/components/utility/header_component_spec.rb
Labels: ProVendor

#6358 Add pagination to new duplicate matching support UI
  app/components/support_interface/duplicate_matches_table_component.html.erb
  app/controllers/support_interface/duplicate_matches_controller.rb
  spec/components/support_interface/duplicate_matches_table_component_spec.rb
Labels: Support, deploy

#6356 Migrate notes provider users to users association
  app/services/data_migrations/backfill_user_columns_on_notes.rb
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_user_columns_on_notes_spec.rb
Labels: ProVendor

#6375 Fix square box characters in application pdfs
  Dockerfile
Labels: ProVendor

#6359 When returning from confirming environment to change a feature flag, return to an #anchor
  app/helpers/view_helper.rb
  app/views/support_interface/settings/feature_flags.html.erb
Labels: Support

#6377 Use `current_course_option` for course level in TAD export
  app/services/data_api/tad_application_export.rb
  spec/services/data_api/tad_export_spec.rb
Labels: Candidate, Metrics & reporting

#6360 Read from Note#user association
  app/components/provider_interface/application_timeline_component.rb
  app/services/support_interface/notes_export.rb
  app/views/provider_interface/notes/index.html.erb
  app/views/provider_interface/notes/show.html.erb
  spec/services/support_interface/notes_export_spec.rb
Labels: ProVendor, deploy

#6390 API v1.1 - Updates to rspec schema validator to support testing different API versions
  spec/support/vendor_api/shared_examples.rb
  spec/support/vendor_api/vendor_api_spec_helpers.rb
Labels: API

#6362 Update copy on various qualification pages
  app/components/candidate_interface/gcse_grade_guidance_component.html.erb
  app/components/candidate_interface/gcse_grade_guidance_component.rb
  app/helpers/gcse_qualification_helper.rb
  app/views/candidate_interface/gcse/english/grade/_single_grade_form.html.erb
  app/views/candidate_interface/gcse/maths/grade/_form.html.erb
  app/views/candidate_interface/gcse/science/grade/_form.html.erb
  config/locales/candidate_interface/gcse.yml
  config/locales/candidate_interface/gcse_details.yml
  spec/components/candidate_interface/gcse_grade_guidance_component_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/course_selection/candidate_can_view_gcse_requirements_and_guidance_for_selected_courses_spec.rb
  spec/system/candidate_interface/entering_details/candidate_changing_gcse_to_international_qualification_spec.rb
  spec/system/candidate_interface/entering_details/candidate_changing_their_gcse_type_from_completed_to_missing_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_english_gcse_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_international_science_qualification_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_without_pass_grade_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_international_gcse_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_qualifications_spec.rb
Labels: Candidate, deploy

#6383 Add standardised sorting to conditions list component
  app/components/provider_interface/conditions_list_component.rb
  spec/components/provider_interface/conditions_list_component_spec.rb
Labels: deploy

#6406 Stop assigning/writing to Note#provider_user
  app/forms/provider_interface/new_note_form.rb
  app/models/note.rb
  spec/components/provider_interface/application_timeline_component_spec.rb
  spec/factories/note.rb
  spec/forms/provider_interface/new_note_form_spec.rb
Labels: deploy

#6393 API v1.1 Update GetApplicationChoiceFromProviders service
  app/controllers/concerns/vendor_api/application_data_concerns.rb
  app/controllers/concerns/versioning.rb
  app/controllers/vendor_api/applications_controller.rb
  app/controllers/vendor_api/decisions_controller.rb
  app/lib/vendor_api.rb
  app/queries/get_application_choices_for_providers.rb
  spec/controllers/concerns/vendor_api/application_data_concerns_spec.rb
  spec/queries/get_application_choices_for_providers_spec.rb
Labels: API

#6405 API v1.1 - Deferrals - Refactor confirm deferred offer services
  app/controllers/provider_interface/reconfirm_deferred_offers_controller.rb
  app/services/confirm_deferred_offer.rb
  app/services/confirm_deferred_offer_validations.rb
  app/services/defer_offer.rb
  app/services/reinstate_conditions_met.rb
  app/services/reinstate_pending_conditions.rb
  app/views/provider_interface/reconfirm_deferred_offers/check.html.erb
  config/locales/en.yml
  spec/services/confirm_deferred_offer_spec.rb
  spec/services/data_api/tad_export_spec.rb
  spec/services/reinstate_conditions_met_spec.rb
  spec/services/reinstate_pending_conditions_spec.rb
  spec/support/shared_examples/confirm_deferred_offer_validations.rb
Labels: API

#6407 4313 address duplicate matching feedback
  app/frontend/styles/support/_app-count.scss
  app/views/support_interface/candidates/edit_candidate_account_status.html.erb
  app/views/support_interface/duplicate_matches/index.html.erb
  app/views/support_interface/duplicate_matches/show.html.erb
  spec/system/support_interface/duplicate_matches_spec.rb
Labels: deploy

#6411 API v1.1 Withdrawals backfill the candidate request flag
  app/services/data_migrations/backfill_withdrawn_or_declined_for_candidate_by_provider.rb
  lib/tasks/data.rake
  spec/factories/audit.rb
  spec/services/data_migrations/backfill_withdrawn_or_declined_for_candidate_by_provider_spec.rb
Labels: ProVendor, API

#6401 copy edit footer
  app/views/layouts/candidate_email_with_support_footer.text.erb
Labels: deploy

#6429 Move application choice includes to application data concerns
  app/controllers/concerns/vendor_api/application_data_concerns.rb
  app/controllers/vendor_api/applications_controller.rb
  spec/controllers/concerns/vendor_api/application_data_concerns_spec.rb
Labels: ProVendor

#6387 Add interviews to API v1.1 application responses
  app/controllers/concerns/vendor_api/add_interviews_to_application_api_data.rb
  app/controllers/concerns/vendor_api/application_data_concerns.rb
  app/lib/vendor_api.rb
  app/lib/vendor_api/changes/add_interviews_to_application.rb
  app/presenters/vendor_api/interview_presenter.rb
  spec/controllers/concerns/vendor_api/application_data_concerns_spec.rb
  spec/presenters/vendor_api/interview_presenter_spec.rb
  spec/presenters/vendor_api/v1.1/application_presenter_spec.rb
  spec/requests/vendor_api/v1.1/get_single_application_spec.rb
Labels: ProVendor

#6338 Add notes via API
  app/controllers/concerns/vendor_api/application_data_concerns.rb
  app/controllers/vendor_api/notes_controller.rb
  app/forms/provider_interface/new_note_form.rb
  app/lib/vendor_api.rb
  app/lib/vendor_api/changes/create_note.rb
  app/lib/vendor_api/changes/notes_for_application.rb
  app/lib/version_change.rb
  app/models/note.rb
  app/presenters/concerns/notes_api_data.rb
  app/presenters/vendor_api/note_presenter.rb
  app/services/create_note.rb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/concerns/vendor_api/application_data_concerns_spec.rb
  spec/forms/provider_interface/new_note_form_spec.rb
  spec/models/note_spec.rb
  spec/presenters/vendor_api/v1.1/application_presenter_spec.rb
  spec/requests/vendor_api/v1.1/create_notes_spec.rb
  spec/requests/vendor_api/versioning_spec.rb
  spec/services/create_note_spec.rb
Labels: ProVendor

#6443 Add create/update/cancel interview endpoints to API v1.1
  app/controllers/vendor_api/interviews_controller.rb
  app/lib/vendor_api.rb
  app/lib/vendor_api/changes/cancel_interview.rb
  app/lib/vendor_api/changes/create_interview.rb
  app/lib/vendor_api/changes/update_interview.rb
  app/services/provider_authorisation.rb
  config/routes.rb
  spec/factories/application_choice.rb
  spec/requests/vendor_api/v1.1/get_single_application_spec.rb
  spec/requests/vendor_api/v1.1/post_cancel_interview_spec.rb
  spec/requests/vendor_api/v1.1/post_create_interview_spec.rb
  spec/requests/vendor_api/v1.1/post_update_interview_spec.rb
  spec/services/provider_authorisation_spec.rb
Labels: ProVendor

#6422 Copy smoke tests from external repo
  .github/workflows/deploy.yml
  Makefile
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/candidate.spec.js
  cypress/integration/components.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  terraform/workspace_variables/production.tfvars.json
  terraform/workspace_variables/qa.tfvars.json
  terraform/workspace_variables/research.tfvars.json
  terraform/workspace_variables/review.tfvars.json
  terraform/workspace_variables/sandbox.tfvars.json
  terraform/workspace_variables/staging.tfvars.json
  yarn.lock
Labels: deploy
