Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2023-11, with the labels that each got.

#8741 Maths GCSE in support interface
  app/forms/support_interface/math_gcse_form.rb
  app/views/support_interface/application_forms/gcses/edit.html.erb
  app/views/support_interface/math_gcse_forms/_math_gcse_form.html.erb
  config/locales/support_interface/gcse.yml
  spec/system/support_interface/change_maths_gcse_spec.rb
Labels: deploy_v2, Continuous applications

#8749 Add science GCSE to support interface
  app/forms/candidate_interface/science_gcse_grade_form.rb
  app/forms/concerns/science_gcse_helper.rb
  app/forms/support_interface/science_gcse_form.rb
  app/views/support_interface/science_gcse_forms/_science_gcse_form.html.erb
  config/locales/support_interface/gcse.yml
  spec/system/support_interface/change_science_gcse_spec.rb
Labels: deploy_v2, Continuous applications

#8754 Add bigquery config code for monthly statistics report
  .env.example
  Gemfile
  Gemfile.lock
  app/lib/dfe/bigquery.rb
  config/initializers/dfe_bigquery.rb
  config/rubocop/config/rspec.yml
  spec/lib/dfe/bigquery_spec.rb
Labels: deploy_v2

#8755 Add Publications::DataTableComponent
  app/components/publications/data_table_component.html.erb
  app/components/publications/data_table_component.rb
  app/frontend/styles/application-publications.scss
  app/frontend/styles/publications/_itt_data_table.scss
  spec/components/previews/publications/data_table_component/default.html.erb
  spec/components/previews/publications/data_table_component_preview.rb
  spec/components/publications/data_table_component_spec.rb
Labels: deploy_v2

#8761 Remove provider banners
  app/components/provider_interface/key_dates_banner.html.erb
  app/components/provider_interface/key_dates_banner.rb
  app/components/provider_interface/summer_recruitment_banner.html.erb
  app/components/provider_interface/summer_recruitment_banner.rb
  app/views/provider_interface/application_choices/index.html.erb
  app/views/provider_interface/start_page/show.html.erb
  config/locales/key_dates_banner.yml
  config/locales/summer_recruitment_banner.yml
  spec/components/provider_interface/key_dates_banner_spec.rb
  spec/components/provider_interface/summer_recruitment_banner_spec.rb
Labels: deploy_v2

#8759 Implement the first section of the new monthly statistics
  app/lib/dfe/bigquery/application_metrics.rb
  app/models/publications/itt_monthly_report_generator.rb
  config/initializers/zeitwerk.rb
  config/locales/publications/itt_monthly_report_generator.yml
  spec/lib/dfe/bigquery/application_metrics_spec.rb
  spec/models/publications/itt_monthly_report_generator_spec.rb
Labels: deploy_v2

#8768 Add monthly_statistics_redirected FeatureFlag
  app/constraints/publications/monthly_statistics_constraint.rb
  app/controllers/publications/monthly_statistics_controller.rb
  app/services/feature_flag.rb
  config/routes/publications.rb
  spec/requests/publications/monthly_statistics_spec.rb
  spec/routes/monthly_statistics/publications_spec.rb
  spec/system/monthly_statistics/monthly_statistics_page_spec.rb
Labels: deploy_v2

#8763 Add all remaining sections to ITT monthly report
  app/lib/dfe/bigquery/application_metrics.rb
  app/lib/dfe/bigquery/condition.rb
  app/lib/dfe/bigquery/relation.rb
  app/lib/dfe/bigquery/table.rb
  app/models/publications/itt_monthly_report_generator.rb
  config/locales/publications/itt_monthly_report_generator.yml
  docs/bigquery_and_reports.md
  spec/lib/dfe/bigquery/application_metrics_spec.rb
  spec/lib/dfe/bigquery/table_spec.rb
  spec/models/publications/itt_monthly_report_generator_spec.rb
Labels: deploy_v2

#8771 Add all remaining sections to itt report
  app/lib/dfe/bigquery/application_metrics.rb
  app/models/publications/itt_monthly_report_generator.rb
  config/locales/publications/itt_monthly_report_generator.yml
  spec/lib/dfe/bigquery/application_metrics_spec.rb
  spec/models/publications/itt_monthly_report_generator_spec.rb
Labels: deploy_v2

#8764 ITT Monthly Statistics template, controller and routes
  app/controllers/publications/v2/monthly_statistics_controller.rb
  app/lib/dfe/bigquery/stubbed_report.rb
  app/presenters/publications/v2/monthly_statistics_presenter.rb
  app/views/publications/v2/monthly_statistics/show.html.erb
  config/locales/publications/itt_monthly_report_generator.yml
  config/routes/publications.rb
  spec/models/publications/itt_monthly_report_generator_spec.rb
  spec/requests/publications/v2/monthly_statistics_report_spec.rb
  spec/system/publications/v2/monthly_statistics/visit_monthly_statistics_spec.rb
Labels: deploy_v2

#8778 CSS issue with DataTableComponent
  app/frontend/styles/publications/_itt_data_table.scss
Labels: deploy_v2

#8783 Monthly statistics storage
  app/controllers/publications/v2/monthly_statistics_controller.rb
  app/lib/dfe/bigquery/test_helper.rb
  app/models/publications/itt_monthly_report_generator.rb
  app/models/publications/monthly_statistics/base.rb
  app/models/publications/monthly_statistics/by_age_group.rb
  app/models/publications/monthly_statistics/by_area.rb
  app/models/publications/monthly_statistics/by_course_age_group.rb
  app/models/publications/monthly_statistics/by_course_type.rb
  app/models/publications/monthly_statistics/by_primary_specialist_subject.rb
  app/models/publications/monthly_statistics/by_provider_area.rb
  app/models/publications/monthly_statistics/by_secondary_subject.rb
  app/models/publications/monthly_statistics/by_sex.rb
  app/models/publications/monthly_statistics/by_status.rb
  app/models/publications/monthly_statistics/deferred_applications.rb
  app/models/publications/monthly_statistics/monthly_statistics_report.rb
  app/presenters/publications/v2/monthly_statistics_presenter.rb
  app/services/data_migrations/monthly_reports_backfill.rb
  app/services/data_migrations/remove_intersex_from_reports.rb
  app/services/publications/monthly_statistics/json_export.rb
  app/workers/generate_monthly_statistics.rb
  config/brakeman.ignore
  docs/bigquery_and_reports.md
  lib/tasks/data.rake
  lib/tasks/monthly_report.rake
  spec/factories/monthly_statistics_reports.rb
  spec/models/publications/itt_monthly_report_generator_spec.rb
  spec/models/publications/monthly_statistics/by_age_group_spec.rb
  spec/models/publications/monthly_statistics/by_area_spec.rb
  spec/models/publications/monthly_statistics/by_course_age_group_spec.rb
  spec/models/publications/monthly_statistics/by_course_type_spec.rb
  spec/models/publications/monthly_statistics/by_primary_specialist_subject_spec.rb
  spec/models/publications/monthly_statistics/by_provider_area_spec.rb
  spec/models/publications/monthly_statistics/by_secondary_subject_spec.rb
  spec/models/publications/monthly_statistics/by_sex_spec.rb
  spec/models/publications/monthly_statistics/by_status_spec.rb
  spec/models/publications/monthly_statistics/deferred_applications_spec.rb
  spec/models/publications/monthly_statistics/monthly_statistics_report_spec.rb
  spec/requests/publications/monthly_statistics_spec.rb
  spec/requests/publications/v2/monthly_statistics_report_spec.rb
  spec/services/data_migrations/monthly_reports_backfill_spec.rb
  spec/services/data_migrations/remove_intersex_from_reports_spec.rb
  spec/services/monthly_statistics_timetable_spec.rb
  spec/services/publications/monthly_statistics/json_export_spec.rb
  spec/support/v1_monthly_statistics.yaml
  spec/support/v1_monthly_statistics_generator_test_helper.rb
  spec/system/monthly_statistics/monthly_statistics_page_spec.rb
  spec/system/publications/v2/monthly_statistics/visit_monthly_statistics_spec.rb
  spec/workers/detect_invariants_daily_check_spec.rb
  spec/workers/generate_monthly_statistics_spec.rb
Labels: deploy_v2

#8479 [Flowcharts] Add Personal Information flowchart
  docs/candidate-flow.md
  docs/candidate-flow/personal-information.md
Labels: Documentation

#8793 Fix Sidekiq retry errors on Review Apps
  app/workers/detect_invariants_daily_check.rb
  app/workers/slack_notification_worker.rb
Labels: deploy_v2

#8788 [Manage] Implement improved grouping and content for inactive applications
  app/components/provider_interface/application_card_component.html.erb
  app/components/provider_interface/application_card_component.rb
  app/frontend/styles/_status-indicator.scss
  app/frontend/styles/application.scss
  app/frontend/styles/candidate/_all.scss
  app/helpers/task_view_helper.rb
  app/models/application_choice.rb
  app/services/provider_interface/sort_application_choices.rb
  app/views/provider_interface/application_choices/index.html.erb
  config/brakeman.ignore
  spec/helpers/task_view_helper_spec.rb
  spec/services/provider_interface/sort_application_choices_spec.rb
Labels: deploy_v2

#8784 Add StatusTotals to the MonthlyStatistics page
  app/components/publications/status_totals_component.html.erb
  app/components/publications/status_totals_component.rb
  app/frontend/styles/_grid.scss
  app/frontend/styles/application-publications.scss
  app/frontend/styles/application.scss
  app/frontend/styles/publications/_itt_grid.scss
  app/frontend/styles/publications/_itt_status_totals.scss
  app/lib/dfe/bigquery/stubbed_report.rb
  app/presenters/publications/v2/monthly_statistics_presenter.rb
  app/views/publications/v2/monthly_statistics/show.html.erb
  config/locales/publications/itt_monthly_report_generator.yml
  spec/components/publications/status_totals_component_spec.rb
  spec/presenters/publications/v2/monthly_statistics_presenter_spec.rb
Labels: deploy_v2

#8789 Monthly statistics csv
  app/controllers/publications/v2/monthly_statistics_controller.rb
  app/lib/dfe/bigquery/application_metrics.rb
  app/lib/dfe/bigquery/test_helper.rb
  app/models/publications/itt_monthly_report_generator.rb
  app/models/publications/monthly_statistics/csv_section.rb
  app/models/publications/monthly_statistics/describe_queries.rb
  app/models/publications/monthly_statistics/report_sections.rb
  app/models/publications/monthly_statistics/stubbed_report.rb
  app/presenters/publications/v2/monthly_statistics_presenter.rb
  app/views/publications/v2/monthly_statistics/show.html.erb
  config/locales/publications/itt_monthly_report_generator.yml
  config/routes/publications.rb
  spec/factories/monthly_statistics_reports.rb
  spec/models/publications/itt_monthly_report_generator_spec.rb
  spec/presenters/publications/v2/monthly_statistics_presenter_spec.rb
  spec/workers/generate_monthly_statistics_spec.rb
Labels: deploy_v2

#8782 Add email notifications for applying to another/multiple courses after 30 days of inactivity
  app/mailers/candidate_mailer.rb
  app/models/application_choice.rb
  app/models/chaser_sent.rb
  app/queries/get_inactive_applications_from_past_day.rb
  app/services/batch_delivery.rb
  app/services/send_apply_to_another_course_when_inactive_email_to_candidate.rb
  app/services/send_apply_to_multiple_courses_when_inactive_email_to_candidate.rb
  app/views/candidate_mailer/apply_to_another_course_after_30_working_days.text.erb
  app/views/candidate_mailer/apply_to_multiple_courses_after_30_working_days.text.erb
  app/workers/send_apply_to_another_course_when_inactive_email_to_candidates_batch_worker.rb
  app/workers/send_apply_to_another_course_when_inactive_email_to_candidates_worker.rb
  app/workers/send_apply_to_multiple_courses_when_inactive_email_to_candidates_batch_worker.rb
  app/workers/send_apply_to_multiple_courses_when_inactive_email_to_candidates_worker.rb
  config/clock.rb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/queries/get_inactive_applications_from_past_day_spec.rb
  spec/services/batch_delivery_spec.rb
  spec/services/send_apply_to_another_course_when_inactive_email_to_candidate_spec.rb
  spec/services/send_apply_to_multiple_courses_when_inactive_email_to_candidate_spec.rb
  spec/system/support_interface/docs_spec.rb
  spec/workers/send_apply_to_another_course_when_inactive_email_to_candidates_batch_worker_spec.rb
  spec/workers/send_apply_to_another_course_when_inactive_email_to_candidates_worker_spec.rb
  spec/workers/send_apply_to_multiple_courses_when_inactive_email_to_candidates_batch_worker_spec.rb
  spec/workers/send_apply_to_multiple_courses_when_inactive_email_to_candidates_worker_spec.rb
Labels: deploy_v2

#8804 Reactivate the monthly statistics page
  app/controllers/publications/monthly_statistics_controller.rb
  app/controllers/publications/v2/monthly_statistics_controller.rb
  app/controllers/support_interface/monthly_statistics_reports_controller.rb
  app/filters/monthly_statistics_redirect_filter.rb
  app/models/publications/monthly_statistics/monthly_statistics_report.rb
  app/presenters/publications/monthly_statistics_presenter.rb
  app/presenters/publications/v1/monthly_statistics_presenter.rb
  app/presenters/publications/v2/monthly_statistics_presenter.rb
  app/services/monthly_statistics_timetable.rb
  app/services/publications/monthly_statistics/v1/calculate_download_sizes.rb
  app/services/publications/monthly_statistics/v1/export_csv.rb
  app/services/publications/monthly_statistics/v2/export_csv.rb
  app/views/publications/monthly_statistics/v1/show.html.erb
  app/views/publications/monthly_statistics/v2/show.html.erb
  app/views/support_interface/monthly_statistics_reports/index.html.erb
  app/views/support_interface/performance/_performance_navigation.html.erb
  config/routes/publications.rb
  config/routes/support.rb
  spec/factories/monthly_statistics_reports.rb
  spec/models/publications/monthly_statistics/monthly_statistics_report_spec.rb
  spec/presenters/publications/v1/monthly_statistics_presenter_spec.rb
  spec/requests/publications/v1/monthly_statistics_spec.rb
  spec/requests/publications/v2/monthly_statistics_report_spec.rb
  spec/services/monthly_statistics_timetable_spec.rb
  spec/system/support_interface/see_monthly_statistics_reports_spec.rb
Labels: deploy_v2

#8807 Remove `inactive` from the activity log on the timeline
  app/components/provider_interface/application_timeline_component.rb
  spec/components/provider_interface/application_timeline_component_spec.rb
Labels: deploy_v2

#8812 Remove 'free of charge' content from footer and Get help section on Apply
  app/views/candidate_interface/shared/_support.html.erb
  app/views/layouts/_footer_meta_candidate.html.erb
Labels: deploy_v2

#8822 Rectify table sort orders in Monthly Stats
  app/lib/dfe/bigquery/application_metrics.rb
  app/lib/dfe/bigquery/table.rb
  spec/lib/dfe/bigquery/application_metrics_spec.rb
  spec/lib/dfe/bigquery/table_spec.rb
Labels: deploy_v2

#8823 Hide status in the whole report with less than 3
  app/models/publications/itt_monthly_report_generator.rb
  app/models/publications/monthly_statistics/csv_section.rb
  app/models/publications/monthly_statistics/report_sections.rb
  app/models/publications/monthly_statistics/statistics_data_processor.rb
  app/presenters/publications/v2/monthly_statistics_presenter.rb
  spec/models/publications/itt_monthly_report_generator_spec.rb
  spec/models/publications/monthly_statistics/statistics_data_processor_spec.rb
Labels: deploy_v2

#8828 Add minor text changes to monthly statistics page
  app/views/publications/monthly_statistics/v2/show.html.erb
  config/locales/publications/itt_monthly_report_generator.yml
Labels: deploy_v2

#8830 Restore order of task view helper
  app/helpers/task_view_helper.rb
Labels: deploy_v2

#8824 Ensure consistent timestamps in diversity report export
  app/services/provider_interface/diversity_report_export.rb
  spec/services/provider_interface/diversity_report_export_spec.rb
Labels: deploy_v2

#8840 Redirect to post offer dashboard on course selection on accepted apps
  app/controllers/candidate_interface/continuous_applications/course_choices/base_controller.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_continuous_applications_feature_enabled_spec.rb
Labels: deploy_v2

#8836 [849] Add content relating to the limit on withdrawing applications
  app/views/candidate_interface/decisions/withdraw.html.erb
  spec/system/candidate_interface/continuous_applications/withdraws/candidate_withdraws_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_withdraws_spec.rb
Labels: deploy_v2

#8838 [992] Update content on GCSE missing page
  app/controllers/candidate_interface/gcse/missing_qualification_controller.rb
  app/forms/candidate_interface/gcse_missing_form.rb
  app/views/candidate_interface/gcse/missing_qualification/_form.html.erb
  config/locales/candidate_interface/gcse.yml
  spec/forms/candidate_interface/gcse_missing_form_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_gcse_without_pass_grade_spec.rb
Labels: deploy_v2
