Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2023-02, with the labels that each got.

#7902 Move DNS Terraform code
  Makefile
  terraform/dns/readme.md
  terraform/dns/records/.terraform.lock.hcl
  terraform/dns/records/data.tf
  terraform/dns/records/resources.tf
  terraform/dns/records/terraform.tf
  terraform/dns/records/variables.tf
  terraform/dns/records/workspace-variables/apply_pentest.tfvars.json
  terraform/dns/records/workspace-variables/apply_production.tfvars.json
  terraform/dns/records/workspace-variables/apply_qa.tfvars.json
  terraform/dns/records/workspace-variables/apply_sandbox.tfvars.json
  terraform/dns/records/workspace-variables/apply_staging.tfvars.json
  terraform/dns/records/workspace-variables/backend_apply_pentest.tfvars
  terraform/dns/records/workspace-variables/backend_apply_production.tfvars
  terraform/dns/records/workspace-variables/backend_apply_qa.tfvars
  terraform/dns/records/workspace-variables/backend_apply_sandbox.tfvars
  terraform/dns/records/workspace-variables/backend_apply_staging.tfvars
  terraform/dns/zones/.terraform.lock.hcl
  terraform/dns/zones/resources.tf
  terraform/dns/zones/terraform.tf
  terraform/dns/zones/variables.tf
  terraform/dns/zones/workspace-variables/apply-zone.tfvars.json
  terraform/dns/zones/workspace-variables/backend_apply.tfvars
Labels: DevOps, terraform, deploy_v2

#7903 [81] Load test logging
  jmeter/.gitignore
  jmeter/.terraform.lock.hcl
  jmeter/.tool-versions
  jmeter/Dockerfile
  jmeter/Makefile
  jmeter/README.md
  jmeter/log4j2.xml
  jmeter/variables.tf
Labels: DevOps

#7911 updated content on link expired page when signing in
  app/views/candidate_interface/sign_in/confirm_sign_in.html.erb
  app/views/candidate_interface/sign_in/expired.html.erb
  config/locales/candidate_interface/authentication.yml
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_using_legacy_email_link_with_u_param_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_tries_to_reuse_magic_link_spec.rb
  spec/system/candidate_interface/signup_and_signin/two_candidates_sign_in_on_same_machine_spec.rb
Labels: deploy_v2

#7908 Release v1.3 of the vendor API
  app/controllers/api_docs/vendor_api_docs/openapi_controller.rb
  app/controllers/api_docs/vendor_api_docs/reference_controller.rb
  app/lib/vendor_api.rb
  app/views/api_docs/vendor_api_docs/pages/release_notes.md
  app/views/api_docs/vendor_api_docs/reference/reference.html.erb
  config/routes/api/docs.rb
  config/vendor_api/v1.3.yml
  spec/requests/api_docs/get_spec_spec.rb
Labels: deploy_v2

#7913 Add success and failure reference endpoints to sandbox
  app/controllers/vendor_api/references_controller.rb
  app/lib/hosting_environment.rb
  app/lib/vendor_api.rb
  app/lib/vendor_api/changes/reference_status.rb
  app/models/application_form.rb
  app/models/provider.rb
  app/services/request_reference.rb
  app/views/candidate_interface/references/email_address/_shared_form.html.erb
  config/environments/test.rb
  config/initializers/route_validators.rb
  config/routes/api/vendor.rb
  config/vendor_api/experimental-v1.0.yml
  spec/factories/reference.rb
  spec/requests/vendor_api/sandbox/post_reference_status_spec.rb
  spec/requests/vendor_api/versioning_spec.rb
Labels: deploy

#7917 Dev platform aks
  .tool-versions
  Makefile
  global_config/dev_platform_review_aks.sh
  terraform/aks/.terraform.lock.hcl
  terraform/aks/outputs.tf
  terraform/aks/provider.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/dev_platform_review_aks.tfvars.json
  terraform/aks/workspace_variables/dev_platform_review_aks_backend.tfvars
  terraform/modules/kubernetes/outputs.tf
  terraform/paas/provider.tf
Labels: deploy

#7925 Remove plpgsql postgres extension
  db/schema.rb
Labels: DevOps, deploy, deploy_v2

#7926 [145] Remove PLPGSQL postgres extension from AKS postgres
  terraform/modules/kubernetes/azure-resources.tf
Labels: DevOps

#7936 Change review and loadtest namespace to bat-qa
  .github/actions/deploy_v2/action.yml
  terraform/aks/workspace_variables/loadtest_aks.tfvars.json
  terraform/aks/workspace_variables/review_aks.tfvars.json
Labels: DevOps, deploy_v2

#7937 Update origins, tags, add make recipes
  Makefile
  terraform/custom_domains/environment_domains/.terraform.lock.hcl
  terraform/custom_domains/environment_domains/workspace_variables/apply_pentest.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_staging.tfvars.json
  terraform/custom_domains/infrastructure/workspace_variables/apply.tfvars.json
Labels: DevOps, terraform

#7942 Add ability to validate domain resources
  Makefile
Labels: DevOps

#7951 Aks deploy apply qa
  .github/actions/deploy_v2/action.yml
  .github/workflows/deploy-v2.yml
  Makefile
  global_config/qa_aks.sh
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks_backend.tfvars
  terraform/custom_domains/environment_domains/main.tf
  terraform/custom_domains/environment_domains/workspace_variables/apply_pentest.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_staging.tfvars.json
  terraform/modules/kubernetes/main.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps

#7944 Adding SKE conditions during offer (provider)
  app/components/provider_interface/offer_summary_component.html.erb
  app/components/provider_interface/offer_summary_component.rb
  app/components/provider_interface/ske_conditions_component.html.erb
  app/components/provider_interface/ske_conditions_component.rb
  app/components/provider_interface/ske_length_component.html.erb
  app/components/provider_interface/ske_length_component.rb
  app/components/provider_interface/ske_reason_component.html.erb
  app/components/provider_interface/ske_reason_component.rb
  app/controllers/provider_interface/offer/ske_language_flows_controller.rb
  app/controllers/provider_interface/offer/ske_lengths_controller.rb
  app/controllers/provider_interface/offer/ske_reasons_controller.rb
  app/controllers/provider_interface/offer/ske_requirements_controller.rb
  app/controllers/provider_interface/offer/ske_standard_flows_controller.rb
  app/controllers/provider_interface/offers_controller.rb
  app/controllers/provider_interface/ske_controller.rb
  app/forms/provider_interface/offer_wizard.rb
  app/models/offer.rb
  app/models/offer_condition.rb
  app/models/ske_condition.rb
  app/models/subject.rb
  app/services/save_offer_conditions_from_params.rb
  app/views/provider_interface/offer/checks/new.html.erb
  app/views/provider_interface/offer/ske_language_flows/new.html.erb
  app/views/provider_interface/offer/ske_lengths/_lengths.html.erb
  app/views/provider_interface/offer/ske_lengths/new.html.erb
  app/views/provider_interface/offer/ske_reasons/_reasons.html.erb
  app/views/provider_interface/offer/ske_reasons/new.html.erb
  app/views/provider_interface/offer/ske_requirements/new.html.erb
  app/views/provider_interface/offer/ske_standard_flows/new.html.erb
  app/views/provider_interface/offers/show.html.erb
  config/locales/provider_interface/make_offer.yml
  config/routes/provider.rb
  spec/components/provider_interface/offer_summary_component_spec.rb
  spec/components/provider_interface/ske_conditions_component_spec.rb
  spec/factories/ske_condition.rb
  spec/factories/subjects.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
  spec/rails_helper.rb
  spec/system/provider_interface/make_offer_ske_language_flow_feature_flag_enabled_spec.rb
  spec/system/provider_interface/make_offer_ske_standard_flow_feature_flag_enabled_spec.rb
Labels: deploy

#7969 Update service CNAME TTL values
  terraform/custom_domains/environment_domains/workspace_variables/apply_pentest.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_staging.tfvars.json
Labels: DevOps, terraform

#7931 Allow candidates to sign up for a Teacher Training Adviser
  .env.example
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/candidate_interface/adviser_sign_ups_controller.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/helpers/get_into_teaching_api_helper.rb
  app/models/adviser/sign_up.rb
  app/services/adviser/application_form_validations.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/adviser_sign_ups/new.html.erb
  app/views/candidate_interface/unsubmitted_application_form/_adviser_call_to_action.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  app/workers/adviser_sign_up_worker.rb
  config/initializers/get_into_teaching_api_client.rb
  config/locales/candidate_interface/adviser_sign_up.yml
  config/locales/en.yml
  config/routes/candidate.rb
  spec/factories/application_form.rb
  spec/factories/application_qualification.rb
  spec/helpers/get_into_teaching_api_helper_spec.rb
  spec/models/adviser/sign_up_spec.rb
  spec/requests/candidate_interface/adviser_sign_up_availability_spec.rb
  spec/services/adviser/application_form_validations_spec.rb
  spec/support/error_matchers.rb
  spec/support/shared_examples/get_into_teaching_api_stubbed_endpoints.rb
  spec/system/candidate_interface/adviser_sign_up/candidate_becomes_eligible_for_adviser_spec.rb
  spec/system/candidate_interface/adviser_sign_up/candidate_signs_up_for_an_adviser_spec.rb
  spec/workers/adviser_sign_up_worker_spec.rb
Labels: deploy

#7970 Select either Azure or AKS container Redis URL
  terraform/aks/.terraform.lock.hcl
  terraform/modules/kubernetes/variables.tf
Labels: DevOps, deploy, terraform, deploy_v2

#7957 Add workflow to backup and restore DB to aks
  .github/actions/backup_and_restore/action.yml
  .github/workflows/backup-and-restore.yml
  .gitignore
  Makefile
Labels: DevOps

#7965 Add aks staging environment
  .github/workflows/deploy-v2.yml
  Makefile
  global_config/staging_aks.sh
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/apply_staging.tfvars.json
Labels: DevOps

#7975 Change SKE length validation
  app/forms/provider_interface/offer_wizard.rb
  app/views/provider_interface/offer/ske_lengths/new.html.erb
  config/locales/provider_interface/make_offer.yml
  spec/system/provider_interface/make_offer_ske_language_flow_feature_flag_enabled_spec.rb
Labels: deploy

#7971 [200] Add host information to AKS review apps
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
Labels: DevOps, deploy_v2

#7976 Delete SKE conditions on support UI course change post-acceptance
  app/forms/support_interface/application_forms/update_offered_course_option_form.rb
  spec/factories/offer.rb
  spec/forms/support_interface/application_forms/update_offered_course_option_form_spec.rb
Labels: deploy

#7979 Scheduled daily AKS db restore from PaaS env
  .github/workflows/scheduled-aks-db-restore.yml
Labels: DevOps

#7978 [202] Fix REDIS_URL and REDIS_CACHE_URL
  terraform/modules/kubernetes/azure-resources.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps, deploy_v2

#7972 Reformat SKE bullet points depending on course type
  app/controllers/provider_interface/ske_controller.rb
  app/forms/provider_interface/offer_wizard.rb
  app/models/subject.rb
  app/views/provider_interface/offer/ske_requirements/new.html.erb
Labels: deploy

#7973 Skip SKE length step for RE courses
  app/components/provider_interface/ske_conditions_component.html.erb
  app/components/provider_interface/ske_conditions_component.rb
  app/forms/provider_interface/offer_wizard.rb
  app/models/subject.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
Labels: deploy
