Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2023-10, with the labels that each got.

#8596 Remove unique index on choice, form and course
  app/models/application_choice.rb
  db/migrate/20230926153652_drop_unique_index_on_application_choice_form_and_course.rb
  db/schema.rb
  docs/domain-model.png
Labels: deploy_v2

#8611 Conditionally display suggestion on duplicate course selection
  app/views/candidate_interface/continuous_applications/course_choices/duplicate_course_selection/new.html.erb
Labels: deploy_v2

#8612 Fix the bug 'Candidate is unable to navigate back to the post offer'
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/references/cancel_controller.rb
  app/controllers/candidate_interface/references/reminder_controller.rb
  app/controllers/candidate_interface/section_controller.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/controllers/concerns/accept_offer_confirm_references.rb
  app/controllers/concerns/request_reference_offer_dashboard.rb
  app/helpers/view_helper.rb
  app/models/application_dates.rb
  app/views/candidate_interface/decisions/withdraw.html.erb
  app/views/candidate_interface/submitted_application_form/review_submitted.html.erb
  spec/models/application_dates_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_and_offer_and_is_redirected_when_tries_to_access_some_pages_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_continuous_applications_feature_enabled_spec.rb
  spec/system/candidate_interface/references/candidate_request_references_continuous_applications_feature_enabled_spec.rb
  spec/system/candidate_interface/references/candidate_views_their_references_on_the_post_offer_dashboard_continuous_applications_feature_enabled_spec.rb
Labels: deploy_v2, Continuous applications

#8622 Change "Edit your answer" to "Edit your personal statement"
  app/components/candidate_interface/becoming_a_teacher_review_component.html.erb
  spec/components/candidate_interface/becoming_a_teacher_review_component_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_updates_personal_statement_spec.rb
  spec/system/candidate_interface/continuous_applications/entering_details/candidate_can_edit_some_sections_after_first_submission_spec.rb
  spec/system/candidate_interface/entering_details/candidate_becoming_a_teacher_spec.rb
  spec/system/candidate_interface/entering_details/candidate_personal_statement_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_statement_section_spec.rb
Labels: deploy_v2, Continuous applications

#8620 Update application process guidance
  app/views/candidate_interface/guidance/index.html.erb
  spec/system/candidate_interface/signup_and_signin/candidate_views_guidance_spec.rb
Labels: deploy_v2

#8605 Add course choice validation on sibling status
  app/models/application_choice.rb
  app/services/application_state_change.rb
  app/services/course_validations.rb
  app/validators/candidate_interface/continuous_applications/course_selection_validator.rb
  app/validators/reapply_validator.rb
  spec/models/application_choice_spec.rb
  spec/models/support_interface/applications_filter_spec.rb
  spec/services/course_validations_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_reapplying_to_a_course_spec.rb
  spec/system/provider_interface/provider_can_view_interview_schedule_spec.rb
Labels: deploy_v2

#8616 Update provider reports
  app/forms/provider_interface/application_data_export_form.rb
  app/models/provider_interface/provider_applications_filter.rb
  app/queries/get_application_progress_data_by_course.rb
  app/services/application_state_change.rb
  app/services/filter_application_choices_for_providers.rb
  app/services/provider_interface/application_data_export.rb
  app/services/provider_interface/diversity_data_by_provider.rb
  app/services/provider_interface/status_of_active_applications_export.rb
  app/views/provider_interface/application_data_export/new.html.erb
  spec/services/filter_application_choices_for_providers_spec.rb
  spec/services/provider_interface/application_data_export_spec.rb
  spec/services/provider_interface/diversity_data_by_provider_spec.rb
  spec/services/provider_interface/status_of_active_applications_export_spec.rb
Labels: deploy_v2

#8624 Fix referee bug
  app/forms/referee_interface/confirm_refuse_feedback_form.rb
  app/forms/referee_interface/questionnaire_form.rb
  app/forms/referee_interface/reference_feedback_form.rb
  app/forms/referee_interface/reference_relationship_form.rb
  app/forms/referee_interface/reference_safeguarding_form.rb
  app/forms/referee_interface/refuse_feedback_form.rb
  app/services/cancel_referee.rb
  app/services/candidate_interface/send_reference_reminder.rb
  app/services/submit_reference.rb
  spec/system/candidate_interface/references/candidate_views_their_references_on_the_post_offer_dashboard_from_previous_cycle_spec.rb
  spec/system/referee_interface/referee_can_submit_a_reference_from_previous_cycle_spec.rb
  spec/system/referee_interface/referee_refuses_to_give_a_reference_from_previous_cycle_spec.rb
Labels: deploy_v2, Continuous applications

#8625 Application Choice submitted transaction email
  app/mailers/candidate_mailer.rb
  app/services/candidate_interface/continuous_applications/submit_application_choice.rb
  app/views/candidate_mailer/application_choice_submitted.text.erb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/candidate_interface/continuous_applications/submit_application_choice_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: deploy_v2

#8627 Fix performance on get unsuccessfull query
  app/queries/get_unsuccessful_and_unsubmitted_candidates.rb
  spec/queries/get_unsuccessful_and_unsubmitted_candidates_spec.rb
Labels: deploy_v2, Continuous applications

#8636 Remove apply again copy in candidate actions
  app/views/candidate_interface/decisions/decline_offer.html.erb
  app/views/candidate_interface/decisions/withdraw.html.erb
Labels: deploy_v2, Continuous applications

#8634 Prevent conditions from rendering for unsuccessful applications
  app/components/candidate_interface/application_dashboard_course_choices_component.rb
  spec/components/candidate_interface/application_dashboard_course_choices_component_spec.rb
Labels: deploy_v2, Continuous applications

#8621 Update the offer deferred page
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/continuous_applications_choices_controller.rb
  app/controllers/candidate_interface/offer_dashboard_controller.rb
  app/controllers/candidate_interface/references/cancel_controller.rb
  app/controllers/candidate_interface/references/reminder_controller.rb
  app/controllers/candidate_interface/section_controller.rb
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/controllers/concerns/accept_offer_confirm_references.rb
  app/controllers/concerns/request_reference_offer_dashboard.rb
  app/views/candidate_interface/offer_dashboard/_offer_deferred.html.erb
  app/views/candidate_interface/offer_dashboard/_pending_conditions.html.erb
  app/views/candidate_interface/offer_dashboard/_recruited.html.erb
  app/views/candidate_interface/offer_dashboard/_references_and_conditions.html.erb
  app/views/candidate_interface/offer_dashboard/_sidebar.html.erb
  app/views/candidate_interface/offer_dashboard/show.html.erb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_and_is_redirected_when_tries_to_access_some_pages_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_defers_offer_and_is_redirected_when_tries_to_access_some_pages_spec.rb
Labels: deploy_v2

#8633 Update the personal statement inset text
  app/components/candidate_interface/editable_section_warning.html.erb
  app/services/candidate_interface/section_policy.rb
  app/views/candidate_interface/personal_statement/show.html.erb
  spec/components/candidate_interface/editable_section_warning_spec.rb
Labels: deploy_v2, Continuous applications

#8629 Align dates deadlines page with recruitment process
  app/views/content/dates_and_deadlines.md
Labels: deploy_v2

#8635 Update offer deadline text
  app/components/provider_interface/application_header_components/offer_will_be_declined_by_default_component.html.erb
  app/components/provider_interface/application_header_components/offer_will_be_declined_by_default_component.rb
  spec/components/provider_interface/application_choice_header_component_spec.rb
  spec/components/provider_interface/application_header_components/offer_will_be_declined_by_default_component_spec.rb
Labels: deploy_v2, Continuous applications

#8638 Fix apply again bug on continuous applications
  app/models/application_form.rb
  spec/models/application_form_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_is_redirected_away_from_complete_page_spec.rb
Labels: deploy_v2, Continuous applications

#8613 Include the provider when candidate goes back when adding a course
  app/controllers/candidate_interface/continuous_applications/course_choices/provider_selection_controller.rb
  app/forms/candidate_interface/continuous_applications/concerns/course_selection_step_helper.rb
  app/forms/candidate_interface/continuous_applications/which_course_are_you_applying_to_step.rb
  app/views/candidate_interface/continuous_applications/course_choices/course_site/_form_fields.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/course_study_mode/_form_fields.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/provider_selection/new.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/which_course_are_you_applying_to/_form_fields.html.erb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_arrives_from_find_with_a_course_with_multiple_study_modes_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_study_mode_spec.rb
Labels: deploy_v2, Continuous applications

#8642 Sort and group application choices in candidate interface
  app/components/candidate_interface/continuous_applications/dashboard_component.html.erb
  app/components/candidate_interface/continuous_applications/dashboard_component.rb
  app/services/candidate_interface/sort_application_choices.rb
  config/locales/candidate_interface/sort_application_choices.yml
  spec/components/candidate_interface/continuous_applications/dashboard_component_spec.rb
  spec/services/candidate_interface/sort_application_choices_spec.rb
Labels: deploy_v2, Continuous applications

#8640 Updated terms and conditions page on Apply
  app/views/content/terms_candidate.html.erb
Labels: deploy_v2

#8651 Candidate shouldn't see personal statement on their draft application
  app/components/candidate_interface/continuous_applications/application_review_component.html.erb
  app/components/candidate_interface/continuous_applications/application_review_component.rb
  spec/components/candidate_interface/continuous_applications/application_review_component_spec.rb
Labels: deploy_v2, Continuous applications

#8644 Manage: Identify and remove all instances of "Automatic Rejections"
  app/components/candidate_interface/application_status_tag_component.html.erb
  app/components/provider_interface/application_card_component.html.erb
  app/components/provider_interface/application_card_component.rb
  app/components/provider_interface/application_header_components/offer_will_be_declined_by_default_component.rb
  app/components/provider_interface/application_header_components/respond_component.html.erb
  app/components/provider_interface/interview_form_component.html.erb
  app/forms/provider_interface/interview_wizard.rb
  app/helpers/task_view_helper.rb
  app/helpers/view_helper.rb
  app/models/application_choice.rb
  app/models/concerns/dateable.rb
  config/locales/provider_interface/interviews.yml
  spec/components/provider_interface/application_card_component_spec.rb
  spec/components/provider_interface/application_choice_header_component_spec.rb
  spec/components/provider_interface/application_header_components/offer_will_be_declined_by_default_component_spec.rb
  spec/components/provider_interface/application_header_components/respond_component_spec.rb
  spec/components/provider_interface/interview_form_component_spec.rb
  spec/forms/provider_interface/interview_wizard_spec.rb
  spec/models/application_choice_spec.rb
Labels: deploy_v2

#8652 Update candidate footer emails to include full stop around chat online
  app/views/candidate_mailer/find_has_opened.erb
  app/views/candidate_mailer/new_cycle_has_started.erb
  app/views/candidate_mailer/nudge_unsubmitted.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_courses.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_personal_statement.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_references/no_references.text.erb
  app/views/layouts/candidate_email_with_support_footer.text.erb
Labels: deploy_v2

#8660 [723] Reduce AKS pod usage
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
Labels: DevOps

#8662 Remove coverage report from CI
  .github/scripts/compare_coverage.js
  .github/scripts/simplecov_collate.rb
  .github/workflows/build-and-deploy.yml
Labels: deploy_v2

#8667 Implement flight check blocking pattern for visa sponsorship
  app/components/candidate_interface/continuous_applications/application_submit_component.html.erb
  app/components/candidate_interface/continuous_applications/application_submit_component.rb
  app/services/candidate_interface/continuous_applications/application_choice_submission.rb
  app/validators/immigration_status_validator.rb
  config/locales/candidate_interface/submit_application.yml
  spec/components/candidate_interface/continuous_applications/application_submit_component_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_with_no_right_to_work_tries_to_submit_course_spec.rb
Labels: deploy_v2, Continuous applications

#8659 Allow references without a type do be updated
  app/components/candidate_interface/references_review_component.rb
  app/forms/candidate_interface/reference/referee_type_form.rb
  app/helpers/references_path_helper.rb
  app/views/candidate_interface/references/type/new.html.erb
  config/routes/candidate.rb
  spec/helpers/references_path_helper_spec.rb
  spec/system/candidate_interface/references/candidate_adding_incomplete_referees_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_references_spec.rb
Labels: deploy_v2

#8666 Journey from Find – reapply for previously unsuccessful courses
  app/models/application_form.rb
  spec/factories/course.rb
  spec/models/application_form_spec.rb
Labels: deploy_v2

#8669 Monthly statistics – redirect away from 2024
  app/controllers/publications/monthly_statistics_controller.rb
  app/views/publications/monthly_statistics/temporarily_unavailable.html.erb
  config/routes/publications.rb
  spec/requests/publications/monthly_statistics_spec.rb
  spec/system/monthly_statistics/monthly_statistics_page_spec.rb
Labels: deploy_v2

#8668 Application choice submission errors updated
  app/components/candidate_interface/continuous_applications/application_submit_component.html.erb
  app/components/candidate_interface/continuous_applications/application_submit_component.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/presenters/candidate_interface/application_form_sections.rb
  app/services/candidate_interface/continuous_applications/application_choice_submission.rb
  app/validators/applications_closed_validator.rb
  app/validators/course_availability_validator.rb
  app/validators/course_unavailable_validator.rb
  app/validators/cycle_verification_validator.rb
  app/validators/immigration_status_validator.rb
  app/validators/incomplete_details_validator.rb
  app/validators/incomplete_including_primary_course_details_validator.rb
  app/validators/incomplete_primary_course_details_validator.rb
  app/validators/open_for_applications_validator.rb
  app/validators/submission_availability_validator.rb
  config/locales/candidate_interface/submit_application.yml
  config/routes.rb
  spec/components/candidate_interface/continuous_applications/application_submit_component_spec.rb
  spec/factories/application_form.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/applications_closed_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/course_unavailable_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/immigration_status_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/incomplete_form_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/incomplete_including_primary_course_form_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/incomplete_primary_course_form_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_submitting_application_spec.rb
Labels: deploy_v2

#8681 Add correct named route for adding Science GCSE qualification
  app/validators/incomplete_primary_course_details_validator.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/incomplete_primary_course_form_spec.rb
Labels: deploy_v2

#8699 Do not render RBD copy for users without permissions
  app/components/provider_interface/application_header_components/awaiting_decision_cannot_respond_component.html.erb
  spec/components/provider_interface/application_choice_header_component_spec.rb
  spec/components/provider_interface/application_header_components/awaiting_decision_cannot_respond_component_spec.rb
Labels: deploy_v2

#8691 Add recruited pending SKE content to candidate offer page
  app/components/candidate_interface/ske_conditions_component.html.erb
  app/components/candidate_interface/ske_conditions_component.rb
  app/controllers/provider_interface/offer/recruit_with_pending_conditions_controller.rb
  app/forms/provider_interface/recruit_with_pending_conditions_form.rb
  app/views/candidate_mailer/conditions_met.text.erb
  spec/system/provider_interface/provider_can_recruit_with_pending_ske_condition_spec.rb
Labels: deploy_v2

#8701 Update link to get school experience service
  config/locales/en.yml
Labels: deploy_v2

#8695 Highlight candidate application edits on manage
  app/components/provider_interface/application_card_component.html.erb
  app/components/provider_interface/application_timeline_component.rb
  app/components/provider_interface/contact_information_component.html.erb
  app/components/provider_interface/diversity_information_component.html.erb
  app/components/provider_interface/personal_information_component.html.erb
  app/components/provider_interface/training_with_disability_component.html.erb
  app/components/shared/interview_preferences_component.html.erb
  app/controllers/provider_interface/application_choices_controller.rb
  app/models/application_choice.rb
  app/queries/get_activity_log_events.rb
  app/queries/recently_updated_application_choice.rb
  app/views/provider_interface/application_choices/show.html.erb
  config/brakeman.ignore
  spec/factories/audit.rb
  spec/models/application_choice_spec.rb
  spec/queries/get_activity_log_events_spec.rb
  spec/queries/recently_updated_application_choice_spec.rb
  spec/system/provider_interface/see_updated_applications_post_submission_spec.rb
Labels: deploy_v2

#8704 Reintroduce review page before submission
  app/components/candidate_interface/continuous_applications/application_review_and_submit_component.html.erb
  app/components/candidate_interface/continuous_applications/application_review_and_submit_component.rb
  app/components/candidate_interface/continuous_applications/application_submit_component.html.erb
  app/components/candidate_interface/continuous_applications/course_review_component.html.erb
  app/components/candidate_interface/continuous_applications/course_review_component.rb
  app/controllers/candidate_interface/continuous_applications/application_choices_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/review_and_submit_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/review_controller.rb
  app/forms/candidate_interface/continuous_applications/submit_application_form.rb
  app/frontend/styles/candidate/_course-choice.scss
  app/views/candidate_interface/application_form/_review_unsubmitted.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/review/show.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/review_and_submit/show.html.erb
  config/locales/en.yml
  config/routes/candidate.rb
  spec/components/candidate_interface/continuous_applications/application_submit_component_spec.rb
  spec/forms/candidate_interface/continuous_applications/submit_application_form_spec.rb
  spec/requests/candidate_interface/continuous_applications_review_and_submit_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_tries_to_submit_after_exceeding_the_maximum_amount_of_unsuccessful_choices_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_with_no_right_to_work_tries_to_submit_course_spec.rb
Labels: deploy_v2, Continuous applications

#8702 Finished english GCSE edit from support
  app/components/shared/gcse_qualification_cards_component.html.erb
  app/controllers/support_interface/application_forms/gcses_controller.rb
  app/forms/candidate_interface/english_gcse_grade_form.rb
  app/forms/candidate_interface/gcse_year_form.rb
  app/forms/english_gcse_grade_attribute_builder.rb
  app/forms/support_interface/english_gcse_form.rb
  app/forms/support_interface/math_gcse_form.rb
  app/forms/support_interface/science_gcse_form.rb
  app/services/support_interface/gcse_form_resolver.rb
  app/validators/o_level_award_year_validator.rb
  app/views/support_interface/application_forms/gcses/edit.html.erb
  app/views/support_interface/application_forms/gcses/edit_award_year.html.erb
  app/views/support_interface/application_forms/gcses/edit_grade.html.erb
  app/views/support_interface/english_gcse_forms/_english_gcse_form.html.erb
  app/views/support_interface/math_gcse_forms/_math_gcse_form.html.erb
  app/views/support_interface/science_gcse_forms/_science_gcse_form.html.erb
  config/locales/support_interface/gcse.yml
  config/routes/support.rb
  spec/system/support_interface/change_english_gcse_spec.rb
  spec/system/support_interface/editing_gcse_award_year_spec.rb
  spec/system/support_interface/editing_gcse_constituent_grade_spec.rb
  spec/system/support_interface/editing_gcse_grade_spec.rb
Labels: deploy_v2, Continuous applications

#8709 Add option to modify individual jobs on application forms
  app/components/shared/work_history_and_unpaid_experience_item_component.html.erb
  app/components/shared/work_history_and_unpaid_experience_item_component.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/support_interface/application_forms/jobs_controller.rb
  app/forms/candidate_interface/restructured_work_history/job_form.rb
  app/forms/shared/job_form.rb
  app/forms/support_interface/application_forms/job_form.rb
  app/helpers/application_helper.rb
  app/views/support_interface/application_forms/jobs/edit.html.erb
  app/views/support_interface/application_forms/show.html.erb
  config/locales/candidate_interface/restructured_work_history.yml
  config/locales/shared/work_history.yml
  config/locales/support_interface/support_interface.yml
  config/routes/support.rb
  spec/forms/support_interface/application_forms/job_form_spec.rb
  spec/system/support_interface/change_job_spec.rb
Labels: deploy_v2

#8686 Update inactive application component
  app/components/candidate_interface/application_status_tag_component.html.erb
  app/components/candidate_interface/continuous_applications/application_summary_component.html.erb
  app/components/candidate_interface/interview_bookings_component.html.erb
  app/models/application_choice.rb
  app/services/application_state_change.rb
  spec/components/candidate_interface/application_dashboard_course_choices_component_spec.rb
  spec/components/candidate_interface/application_status_tag_component_with_continuous_applications_disabled_spec.rb
  spec/models/application_choice_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_has_an_application_become_inactive_spec.rb
Labels: deploy_v2, Continuous applications

#8707 Allow SKE conditions to be marked as met after recruited
  app/components/provider_interface/offer_summary_component.html.erb
  app/components/provider_interface/offer_summary_component.rb
  app/controllers/provider_interface/condition_statuses_controller.rb
  app/services/application_state_change.rb
  config/locales/application_states.yml
  spec/services/provider_interface/save_condition_statuses_spec.rb
  spec/system/provider_interface/provider_can_recruit_with_pending_ske_condition_spec.rb
Labels: deploy_v2

#8706 Highlight candidate application edits on manage (with activity log fix)
  app/components/provider_interface/activity_log/application_choice.rb
  app/components/provider_interface/activity_log/application_form.rb
  app/components/provider_interface/activity_log/interview.rb
  app/components/provider_interface/activity_log_event_component.rb
  app/components/provider_interface/application_card_component.html.erb
  app/components/provider_interface/application_timeline_component.rb
  app/components/provider_interface/contact_information_component.html.erb
  app/components/provider_interface/diversity_information_component.html.erb
  app/components/provider_interface/personal_information_component.html.erb
  app/components/provider_interface/training_with_disability_component.html.erb
  app/components/shared/interview_preferences_component.html.erb
  app/controllers/provider_interface/application_choices_controller.rb
  app/lib/activity_log_event.rb
  app/models/application_choice.rb
  app/models/application_form.rb
  app/models/application_form/column_section_mapping.rb
  app/queries/get_activity_log_events.rb
  app/queries/recently_updated_application_choice.rb
  app/views/provider_interface/application_choices/show.html.erb
  config/brakeman.ignore
  config/locales/provider_interface/activity_log.yml
  spec/components/provider_interface/activity_log_event_component_spec.rb
  spec/factories/audit.rb
  spec/models/application_choice_spec.rb
  spec/models/application_form/column_section_mapping_spec.rb
  spec/queries/get_activity_log_events_spec.rb
  spec/queries/recently_updated_application_choice_spec.rb
  spec/system/provider_interface/see_activity_log_spec.rb
  spec/system/provider_interface/see_updated_applications_post_submission_spec.rb
Labels: deploy_v2

#8716 Add editable_until to application forms
  config/analytics.yml
  db/migrate/20231023155155_add_editable_until_to_application_forms.rb
  db/schema.rb
  docs/domain-model.png
Labels: DO NOT MERGE, deploy_v2, Continuous applications

#8720 Add editable sections to application forms
  config/analytics.yml
  db/migrate/20231025084531_add_editable_sections_to_application_forms.rb
  db/schema.rb
  docs/domain-model.png
Labels: deploy_v2, Continuous applications

#8729 ProviderInterface shows sent_to_provider_at as submitted_at
  app/components/provider_interface/application_summary_component.rb
  spec/components/provider_interface/application_summary_component_spec.rb
Labels: deploy_v2

#8722 Introducing support functionality to grant an editable extension to any non editable section
  app/components/candidate_interface/degree_review_component.html.erb
  app/components/candidate_interface/degree_review_component.rb
  app/components/candidate_interface/other_qualifications_review_component.html.erb
  app/components/candidate_interface/other_qualifications_review_component.rb
  app/components/candidate_interface/references_review_component.html.erb
  app/components/candidate_interface/references_review_component.rb
  app/components/candidate_interface/volunteering_review_component.html.erb
  app/components/candidate_interface/volunteering_review_component.rb
  app/components/shared/restructured_work_history/job_component.html.erb
  app/components/shared/restructured_work_history/job_component.rb
  app/components/shared/restructured_work_history/review_component.html.erb
  app/components/shared/restructured_work_history/review_component.rb
  app/components/shared/restructured_work_history/work_break_component.html.erb
  app/components/shared/restructured_work_history/work_break_component.rb
  app/components/support_interface/application_summary_component.rb
  app/controllers/candidate_interface/application_choices_controller.rb
  app/controllers/candidate_interface/section_controller.rb
  app/controllers/concerns/accept_offer_confirm_references.rb
  app/controllers/support_interface/application_forms/editable_extension_controller.rb
  app/forms/english_gcse_grade_attribute_builder.rb
  app/forms/support_interface/editable_until_form.rb
  app/models/application_form.rb
  app/services/candidate_interface/section.rb
  app/services/candidate_interface/section_policy.rb
  app/services/section.rb
  app/views/candidate_interface/degrees/review/show.html.erb
  app/views/candidate_interface/other_qualifications/review/show.html.erb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/restructured_work_history/review/show.html.erb
  app/views/candidate_interface/volunteering/review/show.html.erb
  app/views/support_interface/application_forms/editable_extension/edit.html.erb
  config/application.rb
  config/locales/sections.yml
  config/locales/support_interface/support_interface.yml
  config/routes/support.rb
  spec/components/candidate_interface/degree_review_component_spec.rb
  spec/components/candidate_interface/volunteering_review_component_spec.rb
  spec/services/candidate_interface/section_policy_spec.rb
  spec/services/section_spec.rb
  spec/system/temporarily_editable_sections_spec.rb
Labels: deploy_v2, Continuous applications

#8714 Update candidate terms and conditions with 5 working day rule
  app/views/content/terms_candidate.html.erb
Labels: deploy_v2

#8735 Fix english edit after submission
  app/controllers/candidate_interface/gcse/english/grade_controller.rb
  spec/system/temporarily_editable_sections_spec.rb
Labels: deploy_v2, Continuous applications

#8723 Validate every step of course selection journey
  app/controllers/candidate_interface/continuous_applications/course_choices/concerns/duplicate_course_redirect.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/course_site_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/course_study_mode_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/duplicate_course_selection_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/find_course_selection_controller.rb
  app/models/application_choice.rb
  app/models/application_form.rb
  app/services/application_state_change.rb
  app/validators/candidate_interface/continuous_applications/course_selection_validator.rb
  app/validators/reapply_validator.rb
  app/views/candidate_interface/continuous_applications/course_choices/duplicate_course_selection/new.html.erb
  spec/models/application_choice_spec.rb
  spec/models/application_form_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_visiting_selection_flow_for_selected_course_spec.rb
Labels: deploy_v2

#8717 [838] Add the ability to edit other qualifications to support
  app/components/shared/qualification_row_component.html.erb
  app/components/shared/qualifications_table_component.html.erb
  app/controllers/support_interface/application_forms/other_qualifications_controller.rb
  app/forms/support_interface/application_forms/edit_other_qualification_award_year_form.rb
  app/forms/support_interface/application_forms/edit_other_qualification_form.rb
  app/forms/support_interface/application_forms/edit_other_qualification_grade_form.rb
  app/views/support_interface/application_forms/other_qualifications/edit.html.erb
  app/views/support_interface/application_forms/other_qualifications/edit_award_year.html.erb
  app/views/support_interface/application_forms/other_qualifications/edit_grade.html.erb
  config/locales/support_interface/support_interface.yml
  config/routes/support.rb
  config/rubocop/config/rspec.yml
  spec/factories/application_qualification.rb
  spec/forms/support_interface/application_forms/edit_other_qualification_award_year_form_spec.rb
  spec/forms/support_interface/application_forms/edit_other_qualification_form_spec.rb
  spec/forms/support_interface/application_forms/edit_other_qualification_grade_form_spec.rb
  spec/system/support_interface/editing_other_qualification_spec.rb
Labels: deploy_v2
