Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2023-04, with the labels that each got.

#8125 Set az config to Ignore warnings
  .github/workflows/database-backup-aks.yml
Labels: DevOps

#8127 Set az config to ignore warnings
  .github/workflows/database-backup.yml
  .github/workflows/restore-production-snapshot.yml
  bin/download-nightly-backup
Labels: DevOps

#8130 Fix logic around GCSE status for adviser sign up
  app/workers/adviser_sign_up_worker.rb
  spec/workers/adviser_sign_up_worker_spec.rb
Labels: deploy

#8132 Add statuscake for prod envs, add staging aks wf
  .github/workflows/build-and-deploy.yml
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
Labels: DevOps

#8039 Migrate staging env to AKS
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
  .github/workflows/scheduled-aks-db-restore.yml
  terraform/aks/workspace_variables/staging_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_staging.tfvars.json
Labels: DevOps

#8139 Sync courses visa sponsorship with Publish API
  app/services/teacher_training_public_api/sync_courses.rb
  spec/examples/teacher_training_api/course_list_response.json
  spec/examples/teacher_training_api/course_single_response.json
  spec/system/teacher_training_public_api/sync_courses_spec.rb
Labels: deploy_v2

#8124 765 change course bugfix
  app/components/provider_interface/application_choice_header_component.rb
  app/controllers/candidate_interface/offer_dashboard_controller.rb
  app/controllers/provider_interface/application_choices_controller.rb
  app/controllers/provider_interface/interviews_controller.rb
  app/controllers/provider_interface/notes_controller.rb
  app/controllers/provider_interface/offers_controller.rb
  app/controllers/provider_interface/provider_interface_controller.rb
  app/controllers/provider_interface/references_controller.rb
  app/services/provider_authorisation.rb
  app/views/provider_interface/application_choices/emails.html.erb
  app/views/provider_interface/application_choices/feedback.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  app/views/provider_interface/application_choices/timeline.html.erb
  app/views/provider_interface/interviews/index.html.erb
  app/views/provider_interface/notes/index.html.erb
  app/views/provider_interface/offer/checks/edit.html.erb
  app/views/provider_interface/offers/show.html.erb
  app/views/provider_interface/references/index.html.erb
  spec/requests/provider_interface/viewing_changed_provider_application_spec.rb
  spec/system/provider_interface/see_application_after_change_to_a_different_provider_spec.rb
Labels: deploy_v2

#8146 Migrate sandbox to aks
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
  .github/workflows/scheduled-aks-db-restore.yml
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_sandbox.tfvars.json
Labels: DevOps

#8138 Updating the duplicate matching email to reflect the duplicate matching process
  app/mailers/candidate_mailer.rb
  app/services/support_interface/send_duplicate_match_email.rb
  app/views/candidate_mailer/duplicate_match_email.text.erb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/support_interface/send_duplicate_match_email_spec.rb
Labels: deploy_v2

#8149 Add word count and increase box size on reference giving flow
  app/views/referee_interface/reference/feedback.html.erb
Labels: deploy_v2

#8147 Add visa sponsorship message when course can sponsor visa
  app/components/candidate_interface/course_choices_review_component.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
  spec/factories/course.rb
Labels: deploy_v2

#8166 Change content of maintenance page
  service_unavailable_page/web/public/internal/index.html
Labels: deploy

#8152 Migrate prod to aks
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/deploy.yml
  .github/workflows/scheduled-aks-db-restore.yml
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_production.tfvars.json
Labels: DevOps, deploy_v2

#8167 Fix Master's and PhD grade options
  app/components/candidate_interface/degree_grade_component.html.erb
  app/components/candidate_interface/degree_grade_component.rb
  app/components/candidate_interface/degree_review_component.rb
  app/components/candidate_interface/degree_type_component.rb
  app/forms/candidate_interface/degree_wizard.rb
  spec/components/candidate_interface/degree_grade_component_spec.rb
  spec/components/candidate_interface/degree_review_component_spec.rb
  spec/components/candidate_interface/degree_type_component_spec.rb
  spec/forms/candidate_interface/degree_wizard_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_delete_and_replace_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_editing_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_masters_degree_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_phd_degree_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_qualifications_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: deploy_v2

#8189 Fix arm storage secret for aks review apps
  .github/workflows/build-and-deploy.yml
  .github/workflows/delete-v2-review-app.yml
Labels: DevOps

#8191 Fix Sentry error in manage for check interviews page
  app/controllers/provider_interface/interviews/checks_controller.rb
  spec/requests/provider_interface/interviews/checks_controller_spec.rb
Labels: deploy_v2

#8021 Allow personal statement to be saved even if over word limit
  app/components/candidate_interface/becoming_a_teacher_review_component.html.erb
  app/components/candidate_interface/subject_knowledge_review_component.html.erb
  app/controllers/candidate_interface/personal_statement_controller.rb
  app/controllers/candidate_interface/subject_knowledge_controller.rb
  app/forms/candidate_interface/becoming_a_teacher_form.rb
  app/forms/candidate_interface/subject_knowledge_form.rb
  app/validators/word_count_validator.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/personal_statement/show.html.erb
  app/views/candidate_interface/subject_knowledge/show.html.erb
  config/locales/candidate_interface/further_information.yml
  config/locales/candidate_interface/gcse.yml
  config/locales/candidate_interface/personal_details.yml
  config/locales/candidate_interface/personal_statement.yml
  config/locales/candidate_interface/restructured_work_history.yml
  config/locales/candidate_interface/volunteering.yml
  config/locales/en.yml
  config/locales/referee_interface/referee_interface.yml
  config/locales/support_interface/support_interface.yml
  spec/components/candidate_interface/becoming_a_teacher_review_component_spec.rb
  spec/components/candidate_interface/subject_knowledge_review_component_spec.rb
  spec/system/candidate_interface/entering_details/candidate_becoming_a_teacher_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_subject_knowledge_spec.rb
  spec/system/candidate_interface/entering_details/candidate_personal_statement_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_statement_section_spec.rb
  spec/validators/word_count_validator_spec.rb
Labels: deploy_v2

#8180 Structured reference condition
  app/components/provider_interface/conditions_list_component.html.erb
  app/controllers/provider_interface/offer/conditions_controller.rb
  app/forms/provider_interface/offer_wizard.rb
  app/models/reference_condition.rb
  app/views/provider_interface/offer/checks/new.html.erb
  app/views/provider_interface/offer/conditions/_form.html.erb
  spec/factories/reference_condition.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
  spec/models/reference_condition_spec.rb
  spec/system/provider_interface/make_offer_feature_flag_spec.rb
  spec/system/provider_interface/make_offer_structured_conditions_feature_flag_enabled_spec.rb
  spec/system/provider_interface/set_offer_conditions_js_spec.rb
Labels: deploy_v2

#8199 Add patch schedule for Azure Redis
  terraform/modules/kubernetes/azure_redis.tf
Labels: DevOps

#8175 Restore AKS Snapshot DB - Switch back to az storage azcopy and mask access key
  .github/workflows/restore-production-snapshot-aks.yml
Labels: DevOps
