Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2023-05, with the labels that each got.

#8181 Use free-text grades for non Bachelors/Masters degrees
  app/components/candidate_interface/degree_grade_component.html.erb
  app/components/candidate_interface/degree_grade_component.rb
  app/forms/candidate_interface/degree_wizard.rb
  config/locales/candidate_interface/degree.yml
  spec/components/candidate_interface/degree_grade_component_spec.rb
  spec/forms/candidate_interface/degree_wizard_spec.rb
  spec/support/test_helpers/candidate_helper.rb
Labels: deploy_v2

#8219 Update reference condition on Manage
  app/components/provider_interface/offer_summary_component.html.erb
  app/controllers/provider_interface/offers_controller.rb
  app/forms/provider_interface/offer_wizard.rb
  app/models/offer.rb
  app/models/reference_condition.rb
  app/services/change_offer.rb
  app/services/make_offer.rb
  app/services/offer_validations.rb
  app/services/save_offer_conditions_from_params.rb
  app/views/provider_interface/offer/conditions/_form.html.erb
  app/views/provider_interface/offers/show.html.erb
  spec/models/reference_condition_spec.rb
  spec/services/offer_validations_spec.rb
  spec/system/provider_interface/make_offer_structured_conditions_spec.rb
Labels: deploy_v2

#8161 Implement the provider diversity report
  app/components/provider_interface/report_table_component.html.erb
  app/components/provider_interface/report_table_component.rb
  app/controllers/provider_interface/reports/diversity_reports_controller.rb
  app/services/feature_flag.rb
  app/services/provider_interface/diversity_data_by_provider.rb
  app/services/provider_interface/diversity_report_export.rb
  app/views/provider_interface/reports/diversity_reports/show.html.erb
  app/views/provider_interface/reports/index.html.erb
  config/locales/en.yml
  config/routes/provider.rb
  spec/components/provider_interface/report_table_component_spec.rb
  spec/rails_helper.rb
  spec/services/provider_interface/diversity_data_by_provider_spec.rb
  spec/services/provider_interface/diversity_report_export_spec.rb
Labels: deploy_v2

#8042 DSI documentation
  docs/dfe-sign-in.md
Labels: DevOps

#8239 Mid cycle report - National level
  app/controllers/publications/mid_cycle_report_controller.rb
  app/models/publications/national_mid_cycle_report.rb
  app/views/publications/mid_cycle_report/_table.html.erb
  app/views/publications/mid_cycle_report/show.html.erb
  config/routes/publications.rb
  lib/tasks/mid_cycle_national_report.rake
Labels: deploy_v2

#8243 Mid cycle report - Provider level
  app/controllers/provider_interface/reports/mid_cycle_reports_controller.rb
  app/models/publications/provider_mid_cycle_report.rb
  app/services/feature_flag.rb
  app/views/provider_interface/reports/index.html.erb
  app/views/provider_interface/reports/mid_cycle_reports/_table.html.erb
  app/views/provider_interface/reports/mid_cycle_reports/show.html.erb
  config/routes/provider.rb
  lib/tasks/mid_cycle_report.rake
Labels: deploy_v2

#8250 Candidate interface Reference condition
  app/components/candidate_interface/application_dashboard_course_choices_component.rb
  app/components/candidate_interface/offer_reference_condition_review_component.html.erb
  app/components/candidate_interface/offer_reference_condition_review_component.rb
  app/components/candidate_interface/offer_review_component.rb
  app/components/candidate_interface/reference_condition_header_component.html.erb
  app/components/candidate_interface/reference_condition_header_component.rb
  app/components/candidate_interface/references_component.html.erb
  app/components/candidate_interface/references_component.rb
  app/views/candidate_interface/decisions/accept_offer.html.erb
  app/views/candidate_interface/offer_dashboard/show.html.erb
  spec/components/candidate_interface/application_dashboard_course_choices_component_spec.rb
  spec/components/candidate_interface/offer_review_component_spec.rb
  spec/components/candidate_interface/reference_condition_header_component_spec.rb
  spec/components/candidate_interface/references_component_spec.rb
  spec/factories/offer.rb
Labels: deploy_v2

#8281 Reflect when data collection started on withdrawal report when a user hasn't got 10 responses
  app/views/provider_interface/reports/withdrawal_reports/show.html.erb
Labels: deploy_v2

#8280 Unchecked reference condition when change offer
  app/forms/provider_interface/offer_wizard.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
Labels: deploy_v2

#8284 Making content on the withdrawal report more clear to explain withdrawals are from a set list
  app/views/provider_interface/reports/withdrawal_reports/show.html.erb
Labels: deploy_v2

#8282 [349] Deploy postgres and redis containers to the app nodepool
  terraform/modules/kubernetes/aks_postgres.tf
  terraform/modules/kubernetes/aks_redis.tf
Labels: DevOps, deploy_v2

#8285 Update our public facing roadmap
  app/views/content/roadmap.md
Labels: deploy_v2

#8274 Nudge for signups that dont start form
  app/mailers/candidate_mailer.rb
  app/models/application_form.rb
  app/queries/get_unstarted_applications_ready_to_nudge.rb
  app/views/candidate_mailer/nudge_unstarted.text.erb
  app/workers/nudge_candidates_worker.rb
  config/locales/application_states.yml
  config/locales/emails/candidate_mailer.yml
  config/locales/en.yml
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/queries/get_unstarted_applications_ready_to_nudge_spec.rb
  spec/workers/nudge_candidates_worker_spec.rb
Labels: deploy_v2
