Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2023-06, with the labels that each got.

#8287 Switch order of personal statement forms for Apply again
  app/presenters/candidate_interface/application_form_presenter.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_updates_personal_statement_spec.rb
Labels: deploy_v2

#8305 [1584] Upgrade production redis queue to premium
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/modules/kubernetes/azure_redis.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps

#8306 [1584] Fix redis queue capacity
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: DevOps

#8309 Remove URL for 'talk-to-us' and update email template
  app/views/candidate_mailer/nudge_unstarted.text.erb
  config/locales/en.yml
Labels: DO NOT MERGE, deploy_v2

#8314 Migration to backfill E&D completed attributes
  app/services/data_migrations/backfill_equality_and_diversity_completed_attributes.rb
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_equality_and_diversity_completed_attributes_spec.rb
Labels: Continuous applications

#8311 Introduce Candidate Interface primary navigation
  app/components/utility/primary_navigation_component.html.erb
  app/components/utility/primary_navigation_component.rb
  app/frontend/styles/_primary-navigation.scss
  app/helpers/navigation_items.rb
  app/models/application_choice.rb
  app/views/candidate_interface/offer_dashboard/show.html.erb
  app/views/layouts/_header.html.erb
  config/locales/en.yml
  spec/helpers/navigation_items_spec.rb
  spec/models/application_choice_spec.rb
  spec/system/candidate_interface/course_selection/sandbox_user_apply_from_find_spec.rb
  spec/system/candidate_interface/references/candidate_request_references_spec.rb
  spec/system/candidate_interface/references/candidate_views_their_references_on_the_post_offer_dashboard_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_account_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_using_legacy_email_link_with_u_param_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_tries_to_reuse_magic_link_spec.rb
  spec/system/candidate_interface/signup_and_signin/two_candidates_sign_in_on_same_machine_spec.rb
Labels: deploy_v2

#8313 Merge Safeguarding Information
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/forms/candidate_interface/further_information_form.rb
  app/views/candidate_interface/safeguarding/_form.html.erb
  app/views/candidate_interface/unsubmitted_application_form/submit_show.html.erb
  spec/forms/candidate_interface/further_information_form_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/entering_details/candidate_entering_suitability_to_work_with_children_spec.rb
  spec/system/candidate_interface/references/candidate_submits_a_duplicate_application_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_and_prefills_application_in_sandbox_spec.rb
  spec/system/candidate_interface/submitting/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/submitting/international_candidate_submitting_application_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: deploy_v2

#8334 [425] Increase production database storage
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: DevOps

#8319 1529 add inactive status
  app/components/candidate_interface/application_status_tag_component.rb
  app/components/provider_interface/application_status_tag_component.rb
  app/components/shared/state_diagram_component.html.erb
  app/components/shared/state_diagram_component.rb
  app/components/support_interface/application_status_tag_component.rb
  app/lib/state_diagram.rb
  app/models/application_choice.rb
  app/services/application_state_change.rb
  app/services/candidate_flow.rb
  app/views/api_docs/vendor_api_docs/pages/lifecycle.html.erb
  config/locales/application_states.yml
  docs/states.png
  spec/services/application_state_change_spec.rb
Labels: deploy_v2

#8318 Add realistic job previews link with UTM tracking
  app/components/candidate_interface/apply_again_call_to_action_component.html.erb
  config/locales/en.yml
  spec/system/candidate_interface/apply_again/candidate_applies_again_updates_personal_statement_spec.rb
Labels: deploy_v2

#8338 Equality and diversity component will return Not answered
  app/components/candidate_interface/equality_and_diversity_review_component.rb
  app/controllers/candidate_interface/equality_and_diversity_controller.rb
  app/forms/candidate_interface/equality_and_diversity_complete_form.rb
  app/views/candidate_interface/equality_and_diversity/review.html.erb
  config/locales/candidate_interface/section_complete.yml
  spec/components/candidate_interface/equality_and_diversity_review_component_spec.rb
  spec/forms/candidate_interface/equality_and_diversity_complete_form_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_spec.rb
Labels: deploy_v2

#8332 Implement guidance for continuous applications
  app/controllers/candidate_interface/guidance_controller.rb
  app/views/candidate_interface/guidance/index.html.erb
  app/views/candidate_interface/start_page/create_account_or_sign_in.html.erb
  app/views/candidate_interface/unsubmitted_application_form/show.html.erb
  config/locales/en.yml
  config/routes/candidate.rb
  public/robots.txt
  spec/system/candidate_interface/signup_and_signin/candidate_views_guidance_from_unsubmitted_application_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_views_guidance_spec.rb
Labels: deploy_v2

#8356 Fix the publish sync
  app/services/feature_flag.rb
  app/services/teacher_training_public_api/sync_courses.rb
  app/services/teacher_training_public_api/sync_sites.rb
  spec/examples/teacher_training_api/course_list_response.json
  spec/examples/teacher_training_api/course_single_response.json
  spec/examples/teacher_training_api/site_list_response_with_full_time_and_part_time_vacancies.json
  spec/examples/teacher_training_api/site_list_response_with_full_time_vacancies.json
  spec/examples/teacher_training_api/site_list_response_with_part_time_vacancies.json
  spec/services/teacher_training_public_api/sync_sites_spec.rb
  spec/system/teacher_training_public_api/site_has_no_vacancies_and_is_not_updated_spec.rb
  spec/system/teacher_training_public_api/site_is_deleted_spec.rb
  spec/system/teacher_training_public_api/sync_is_called_with_the_new_course_attribute_spec.rb
Labels: deploy_v2

#8366 [282] Enable support to change an application choice to salaried course
  app/controllers/support_interface/application_forms/application_choices/change_offered_course_controller.rb
  app/controllers/support_interface/application_forms/courses_controller.rb
  app/errors/funding_type_error.rb
  app/forms/support_interface/application_forms/update_offered_course_option_form.rb
  app/models/course.rb
  app/services/support_interface/change_application_choice_course_option.rb
  config/locales/candidate_interface/courses.yml
  spec/forms/support_interface/application_forms/update_offered_course_option_form_spec.rb
  spec/services/support_interface/change_application_choice_course_option_spec.rb
  spec/system/support_interface/change_course_choice_spec.rb
  spec/system/support_interface/change_offered_course_for_a_submitted_application_spec.rb
Labels: deploy_v2
