Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2023-03, with the labels that each got.

#7992 Temp update host header value for sbox/prod
  terraform/custom_domains/environment_domains/workspace_variables/apply_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_sandbox.tfvars.json
Labels: DevOps, terraform

#7993 [81] Load test configuration
  jmeter/.gitignore
  jmeter/.tool-versions
  jmeter/jmeter-courses.csv
  jmeter/load-test-dashboard.json
  terraform/aks/workspace_variables/loadtest_aks.tfvars.json
  terraform/modules/kubernetes/azure-resources.tf
  terraform/modules/kubernetes/main.tf
  terraform/modules/kubernetes/postgres.tf
Labels: DevOps

#7983 Support existing candidates when signing up for an adviser
  .rubocop.yml
  app/controllers/candidate_interface/adviser_sign_ups_controller.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  app/models/adviser/sign_up.rb
  app/services/adviser/api_model_decorator.rb
  app/services/adviser/application_form_validations.rb
  app/services/adviser/candidate_matchback.rb
  app/services/adviser/sign_up_availability.rb
  app/services/adviser/tracking.rb
  app/workers/adviser_sign_up_worker.rb
  config/analytics_custom_events.yml
  config/locales/en.yml
  spec/models/adviser/sign_up_spec.rb
  spec/rails_helper.rb
  spec/requests/candidate_interface/adviser_sign_up_availability_spec.rb
  spec/services/adviser/api_model_decorator_spec.rb
  spec/services/adviser/application_form_validations_spec.rb
  spec/services/adviser/candidate_matchback_spec.rb
  spec/services/adviser/sign_up_availability_spec.rb
  spec/services/adviser/tracking_spec.rb
  spec/support/dfe_analytics.rb
  spec/support/shared_examples/get_into_teaching_api_stubbed_endpoints.rb
  spec/system/candidate_interface/adviser_sign_up/candidate_becomes_eligible_for_adviser_spec.rb
  spec/system/candidate_interface/adviser_sign_up/candidate_signs_up_for_an_adviser_spec.rb
  spec/workers/adviser_sign_up_worker_spec.rb
Labels: deploy

#7988 Don't break page if GCSE doesn't have a grade
  app/components/shared/gcse_qualification_cards_component.html.erb
Labels: deploy, deploy_v2

#8012 [97] sandbox aks pipeline
  .github/actions/backup_and_restore/action.yml
  .github/workflows/backup-and-restore.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy-v2.yml
  .github/workflows/scheduled-aks-db-restore.yml
  Makefile
  global_config/sandbox_aks.sh
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks_backend.tfvars
  terraform/custom_domains/environment_domains/workspace_variables/apply_sandbox.tfvars.json
  terraform/modules/kubernetes/variables.tf
Labels: DevOps, deploy_v2

#8002 Add statuscake monitoring for aks qa/staging envs
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: DevOps

#8020 Add adviser_status attribute to ApplicationForm
  config/analytics.yml
  db/migrate/20230309104350_add_adviser_status_to_application_forms.rb
  db/schema.rb
Labels: deploy

#8014 [88] Cache rails assets on AKS
  terraform/custom_domains/environment_domains/.terraform.lock.hcl
  terraform/custom_domains/environment_domains/main.tf
  terraform/custom_domains/environment_domains/workspace_variables/apply_pentest.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_staging.tfvars.json
Labels: DevOps

#8011 [101] Introduce liveness and startup probe into the workers
  terraform/modules/kubernetes/main.tf
Labels: DevOps

#8023 [79] Fix matrix reference for sandbox and prod step
  .github/workflows/scheduled-aks-db-restore.yml
Labels: DevOps

#8006 Show providers a preview of the rejection email
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_email-preview.scss
  app/views/provider_interface/rejections/check.html.erb
  spec/system/provider_interface/provider_gives_feedback_for_rejected_by_default_spec.rb
  spec/system/provider_interface/reject_an_application_spec.rb
Labels: deploy_v2

#8028 Remove singed_up_for_adviser field from ApplicationForm
  config/analytics.yml
  db/migrate/20230313100534_remove_signed_up_for_adviser_from_application_forms.rb
  db/schema.rb
  docs/domain-model.png
Labels: deploy

#8026 Fix IP address issue on AKS QA and beyond
  app/controllers/dfe_sign_in_controller.rb
  config/environments/production.rb
Labels: deploy_v2

#8031 Add the offer accepted at date to provider export
  app/services/provider_interface/application_data_export.rb
  spec/services/provider_interface/application_data_export_spec.rb
Labels: deploy, deploy_v2

#8032 Update the candidate API current version
  app/lib/candidate_api_specification.rb
  spec/requests/candidate_api/get_candidates_v1_1_spec.rb
Labels: deploy, deploy_v2

#8036 Migate QA env to AKS
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy.yml
  .github/workflows/scheduled-aks-db-restore.yml
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_qa.tfvars.json
Labels: DevOps

#8013 Basic monitoring for aks apps
  docs/aks-alerting.md
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
  terraform/custom_domains/environment_domains/monitoring.tf
  terraform/custom_domains/environment_domains/variables.tf
  terraform/custom_domains/environment_domains/workspace_variables/apply_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_staging.tfvars.json
  terraform/modules/kubernetes/monitoring.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps

#8043 Update prod front door config now AKS is deployed
  terraform/custom_domains/environment_domains/workspace_variables/apply_production.tfvars.json
Labels: DevOps, terraform

#8040 Created production apply related infra
  .github/workflows/backup-and-restore.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/deploy-v2.yml
  Makefile
  global_config/production_aks.sh
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/production_aks_backend.tfvars
  terraform/modules/kubernetes/main.tf
Labels: DevOps

#7997 Update roadmap
  app/views/content/roadmap.md
Labels: deploy_v2

#7929 One personal statement
  app/components/candidate_interface/becoming_a_teacher_review_component.rb
  app/components/shared/personal_statement_component.html.erb
  app/controllers/candidate_interface/personal_statement_controller.rb
  app/controllers/candidate_interface/subject_knowledge_controller.rb
  app/forms/candidate_interface/becoming_a_teacher_form.rb
  app/models/application_form.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/services/duplicate_application.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/personal_statement/_form.html.erb
  app/views/candidate_interface/personal_statement/show.html.erb
  app/views/candidate_interface/unsubmitted_application_form/_task_list.html.erb
  config/locales/candidate_interface/personal_statement.yml
  config/locales/en.yml
  spec/components/candidate_interface/becoming_a_teacher_review_component_spec.rb
  spec/forms/candidate_interface/becoming_a_teacher_form_spec.rb
  spec/services/duplicate_application_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_with_a_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_without_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/entering_details/candidate_personal_statement_spec.rb
  spec/system/provider_interface/provider_views_application_submitted_in_new_cycle_feature_flag_disabled_spec.rb
  spec/system/provider_interface/see_individual_application_new_personal_statement_spec.rb
  spec/system/provider_interface/see_individual_application_old_personal_statement_spec.rb
  spec/system/support_interface/editing_subject_knowledge_spec.rb
Labels: deploy, deploy_v2

#8059 [274] Remove staging2 from deployment pipeline
  .github/workflows/build-and-deploy.yml
Labels: DevOps

#8064 Display guidance shown to candidates in Manage and Support views
  app/components/shared/personal_statement_component.html.erb
  app/views/candidate_interface/personal_statement/_form.html.erb
  app/views/candidate_interface/personal_statement/_guidance.html.erb
  app/views/candidate_interface/personal_statement/_guidance_old.html.erb
  app/views/candidate_interface/subject_knowledge/_form.html.erb
  app/views/candidate_interface/subject_knowledge/_guidance.html.erb
Labels: deploy_v2

#8054 Mitigate redis timeout errors
  config/initializers/sidekiq.rb
  terraform/modules/kubernetes/azure-resources.tf
  terraform/modules/kubernetes/variables.tf
Labels: deploy, deploy_v2

#8044 Add code to support pod disruption budget
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
  terraform/modules/kubernetes/availability.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps, terraform, deploy_v2

#8067 Add production to scheduled database workflows
  .github/workflows/backup-and-restore.yml
  .github/workflows/scheduled-aks-db-restore.yml
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: DevOps, github_actions

#8056 Update terms and conditions content on Apply
  app/views/candidate_interface/sign_up/new.html.erb
  app/views/content/terms_candidate.html.erb
  config/locales/en.yml
  spec/system/candidate_interface/entering_details/candidate_entering_equality_and_diversity_information_spec.rb
Labels: deploy_v2

#8019 Change personal statement flows and return to application if empty
  app/controllers/candidate_interface/personal_statement_controller.rb
  app/controllers/candidate_interface/subject_knowledge_controller.rb
  app/forms/candidate_interface/becoming_a_teacher_form.rb
  app/forms/candidate_interface/subject_knowledge_form.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/views/candidate_interface/unsubmitted_application_form/_task_list.html.erb
  config/locales/candidate_interface/personal_statement.yml
  spec/forms/candidate_interface/becoming_a_teacher_form_spec.rb
  spec/forms/candidate_interface/subject_knowledge_form_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/system/candidate_interface/entering_details/candidate_becoming_a_teacher_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_subject_knowledge_spec.rb
  spec/system/candidate_interface/entering_details/candidate_personal_statement_spec.rb
Labels: deploy_v2

#8072 Upgrade postgres databases to 14
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/modules/kubernetes/azure-resources.tf
  terraform/modules/kubernetes/postgres.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps, deploy_v2

#8062 Fix the SKE condition Change link on check page
  app/components/provider_interface/offer_summary_component.html.erb
  app/components/provider_interface/ske_conditions_component.html.erb
  app/components/provider_interface/ske_conditions_component.rb
  app/services/change_offer.rb
  app/services/make_offer.rb
  app/services/offer_validations.rb
  spec/components/provider_interface/ske_conditions_component_spec.rb
  spec/services/offer_validations_spec.rb
  spec/system/provider_interface/change_existing_offer_ske_standard_flow_spec.rb
Labels: deploy_v2

#8045 Vendor API changes for SKE conditions
  app/models/offer.rb
  app/presenters/concerns/decisions_api_data.rb
  spec/factories/offer.rb
  spec/presenters/concerns/decisions_api_data_spec.rb
  spec/requests/vendor_api/v1.1/get_single_application_spec.rb
Labels: API

#8088 Support functionality: Change award year and grade for other qualifications
  app/components/shared/qualification_row_component.html.erb
  app/components/shared/qualification_row_component.rb
  app/components/shared/qualifications_component.html.erb
  app/components/shared/qualifications_table_component.html.erb
  app/components/shared/qualifications_table_component.rb
  app/controllers/support_interface/application_forms/other_qualifications_controller.rb
  app/forms/support_interface/application_forms/edit_other_qualification_award_year_form.rb
  app/forms/support_interface/application_forms/edit_other_qualification_grade_form.rb
  app/views/support_interface/application_forms/other_qualifications/edit_award_year.html.erb
  app/views/support_interface/application_forms/other_qualifications/edit_grade.html.erb
  config/locales/support_interface/support_interface.yml
  config/routes/support.rb
  spec/forms/support_interface/application_forms/edit_other_qualification_award_year_form_spec.rb
  spec/forms/support_interface/application_forms/edit_other_qualification_grade_form_spec.rb
  spec/system/support_interface/editing_other_qualification_spec.rb
Labels: deploy_v2

#8102 [227] Refactor Azure backing services
  Makefile
  terraform/aks/.terraform.lock.hcl
  terraform/aks/data.tf
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/dv_review_aks.tfvars.json
  terraform/aks/workspace_variables/loadtest_aks.tfvars.json
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/pt_review_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/review_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
  terraform/modules/kubernetes/aks_postgres.tf
  terraform/modules/kubernetes/aks_redis.tf
  terraform/modules/kubernetes/azure_postgres.tf
  terraform/modules/kubernetes/azure_redis.tf
  terraform/modules/kubernetes/data.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps, DO NOT MERGE

#8101 Increase timeout for konduit restores
  .github/actions/backup_and_restore/action.yml
Labels: DevOps, terraform

#8111 Tune front door alert thresholds
  docs/aks-alerting.md
  terraform/custom_domains/environment_domains/variables.tf
  terraform/custom_domains/environment_domains/workspace_variables/apply_staging.tfvars.json
Labels: DevOps
