Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2023-08, with the labels that each got.

#8411 Continuous applications course selection
  app/components/candidate_interface/application_dashboard_component.html.erb
  app/components/candidate_interface/applications_left_message_component.html.erb
  app/components/candidate_interface/applications_left_message_component.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/base_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/course_site_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/course_study_mode_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/do_you_know_which_course_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/go_to_find_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/provider_selection_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/review_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/which_course_are_you_applying_to_controller.rb
  app/forms/candidate_interface/continuous_applications/concerns/course_selection_step_helper.rb
  app/forms/candidate_interface/continuous_applications/course_review_step.rb
  app/forms/candidate_interface/continuous_applications/course_selection_wizard.rb
  app/forms/candidate_interface/continuous_applications/course_site_step.rb
  app/forms/candidate_interface/continuous_applications/course_study_mode_step.rb
  app/forms/candidate_interface/continuous_applications/do_you_know_the_course_step.rb
  app/forms/candidate_interface/continuous_applications/go_to_find_explanation_step.rb
  app/forms/candidate_interface/continuous_applications/provider_selection_step.rb
  app/forms/candidate_interface/continuous_applications/which_course_are_you_applying_to_step.rb
  app/frontend/packs/autocompletes/candidate/__snapshots__/candidate-autocomplete-inputs.spec.js.snap
  app/frontend/packs/autocompletes/candidate/candidate-autocomplete-inputs.js
  app/lib/dfe/wizard.rb
  app/lib/dfe/wizard_step.rb
  app/lib/dfe/wizard_store.rb
  app/models/application_form.rb
  app/queries/get_available_courses_for_provider.rb
  app/queries/get_available_providers.rb
  app/services/application_state_change.rb
  app/services/candidate_interface/continuous_applications/course_selection_store.rb
  app/views/candidate_interface/continuous_applications/course_choices/course_site/new.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/course_study_mode/new.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/do_you_know_which_course/new.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/go_to_find/new.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/provider_selection/new.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/review/show.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/which_course_are_you_applying_to/new.html.erb
  app/views/candidate_interface/continuous_applications_choices/index.html.erb
  config/locales/candidate_interface/applications_left_message.yml
  config/locales/candidate_interface/course_selection_wizard.yml
  config/locales/en.yml
  config/routes/candidate.rb
  spec/components/candidate_interface/applications_left_message_component_spec.rb
  spec/forms/candidate_interface/continuous_applications/course_selection_wizard_spec.rb
  spec/forms/candidate_interface/continuous_applications/course_site_step_spec.rb
  spec/forms/candidate_interface/continuous_applications/course_study_mode_step_spec.rb
  spec/forms/candidate_interface/continuous_applications/do_you_know_the_course_step_spec.rb
  spec/forms/candidate_interface/continuous_applications/provider_selection_step_spec.rb
  spec/forms/candidate_interface/continuous_applications/which_course_are_you_applying_to_step_spec.rb
  spec/lib/dfe/wizard_spec.rb
  spec/lib/dfe/wizard_step_spec.rb
  spec/lib/dfe/wizard_store_spec.rb
  spec/models/application_form_spec.rb
  spec/services/candidate_interface/continuous_applications/course_selection_store_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_study_mode_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_with_multiple_sites_spec.rb
Labels: deploy_v2

#8429 `current_year` respects cycle switcher
  app/models/recruitment_cycle.rb
  app/models/support_interface/applications_filter.rb
  app/services/cycle_timetable.rb
  app/views/support_interface/settings/cycles.html.erb
  app/views/support_interface/tasks/index.html.erb
  config/locales/support_interface/cycles.yml
  spec/services/cycle_timetable_spec.rb
  spec/system/candidate_interface/carry_over/candidate_can_submit_in_next_cycle_when_cycle_switched_spec.rb
  spec/system/support_interface/disable_generate_applications_cycle_switcher_spec.rb
Labels: deploy_v2

#8446 Add withdraw to continuous applications
  app/components/candidate_interface/continuous_applications/application_summary_component.html.erb
  app/controllers/candidate_interface/decisions_controller.rb
  app/views/candidate_interface/continuous_applications_choices/index.html.erb
  spec/system/candidate_interface/continuous_applications/withdraws/candidate_withdraws_spec.rb
  spec/system/candidate_interface/continuous_applications/withdraws/candidate_withdraws_with_upcoming_interviews_spec.rb
Labels: deploy_v2

#8452 Submit application on continuous applications
  app/components/candidate_interface/continuous_applications/application_submit_component.html.erb
  app/components/candidate_interface/continuous_applications/application_submit_component.rb
  app/controllers/candidate_interface/continuous_applications/application_choices_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/review_controller.rb
  app/forms/candidate_interface/continuous_applications/submit_application_form.rb
  app/validators/course_availability_validator.rb
  app/validators/cycle_verification_validator.rb
  app/validators/open_for_applications_validator.rb
  app/validators/submission_availability_validator.rb
  app/validators/your_details_completion_validator.rb
  app/views/candidate_interface/continuous_applications/course_choices/review/show.html.erb
  config/locales/candidate_interface/courses.yml
  config/locales/candidate_interface/submit_application.yml
  config/routes/candidate.rb
  spec/forms/candidate_interface/continuous_applications/submit_application_form_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_submitting_application_spec.rb
Labels: deploy_v2

#8458 Fix bug where the error summary is presented on application review
  app/components/candidate_interface/continuous_applications/application_submit_component.rb
  app/controllers/candidate_interface/continuous_applications/application_choices_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/review_controller.rb
  app/forms/candidate_interface/continuous_applications/submit_application_form.rb
  app/services/candidate_interface/continuous_applications/application_choice_submission.rb
  app/validators/cycle_verification_validator.rb
  app/views/candidate_interface/continuous_applications/course_choices/review/show.html.erb
  config/locales/candidate_interface/submit_application.yml
  spec/components/candidate_interface/continuous_applications/application_submit_component_spec.rb
  spec/forms/candidate_interface/continuous_applications/submit_application_form_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
Labels: Ruby, deploy_v2, Continuous applications

#8451 New personal statement journey
  app/components/provider_interface/choice_personal_statement_component.html.erb
  app/components/provider_interface/choice_personal_statement_component.rb
  app/controllers/candidate_interface/personal_statement_controller.rb
  app/forms/candidate_interface/becoming_a_teacher_form.rb
  app/forms/support_interface/application_forms/edit_becoming_a_teacher_form.rb
  app/presenters/vendor_api/application_presenter.rb
  app/services/candidate_interface/continuous_applications/submit_application_choice.rb
  app/views/provider_interface/application_choices/show.html.erb
  spec/components/provider_interface/choice_personal_statement_component_spec.rb
  spec/forms/candidate_interface/becoming_a_teacher_form_spec.rb
  spec/forms/support_interface/application_forms/edit_becoming_a_teacher_form_spec.rb
  spec/presenters/vendor_api/v1.0/application_presenter_spec.rb
  spec/requests/candidate_interface/personal_statement_spec.rb
  spec/services/candidate_interface/continuous_applications/submit_application_choice_spec.rb
Labels: Ruby, deploy_v2, Continuous applications

#8464 [567] Reduce apply memory footprint
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: DevOps, deploy_v2

#8471 Backlinks updated for continuous applications
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/contact_details/address_type_controller.rb
  app/controllers/candidate_interface/english_foreign_language/ielts_controller.rb
  app/controllers/candidate_interface/english_foreign_language/review_controller.rb
  app/controllers/candidate_interface/english_foreign_language/toefl_controller.rb
  app/controllers/candidate_interface/english_foreign_language/type_controller.rb
  app/controllers/candidate_interface/guidance_controller.rb
  app/controllers/candidate_interface/restructured_work_history/review_controller.rb
  app/controllers/concerns/back_links.rb
  app/helpers/view_helper.rb
  app/views/candidate_interface/application_choices/review.html.erb
  app/views/candidate_interface/application_form/review_previous_application.html.erb
  app/views/candidate_interface/contact_details/address/edit.html.erb
  app/views/candidate_interface/contact_details/phone_number/new.html.erb
  app/views/candidate_interface/contact_details/review/show.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/review/show.html.erb
  app/views/candidate_interface/course_choices/add_another_course/ask.html.erb
  app/views/candidate_interface/decisions/withdraw.html.erb
  app/views/candidate_interface/degrees/review/show.html.erb
  app/views/candidate_interface/english_foreign_language/start/new.html.erb
  app/views/candidate_interface/equality_and_diversity/edit_sex.html.erb
  app/views/candidate_interface/equality_and_diversity/review.html.erb
  app/views/candidate_interface/feedback_form/new.html.erb
  app/views/candidate_interface/gcse/review/show.html.erb
  app/views/candidate_interface/gcse/type/new.html.erb
  app/views/candidate_interface/guidance/index.html.erb
  app/views/candidate_interface/interview_availability/new.html.erb
  app/views/candidate_interface/interview_availability/show.html.erb
  app/views/candidate_interface/other_qualifications/review/show.html.erb
  app/views/candidate_interface/other_qualifications/type/new.html.erb
  app/views/candidate_interface/personal_details/name_and_dob/new.html.erb
  app/views/candidate_interface/personal_details/review/show.html.erb
  app/views/candidate_interface/personal_statement/new.html.erb
  app/views/candidate_interface/personal_statement/show.html.erb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/restructured_work_history/start/choice.html.erb
  app/views/candidate_interface/safeguarding/new.html.erb
  app/views/candidate_interface/safeguarding/show.html.erb
  app/views/candidate_interface/subject_knowledge/new.html.erb
  app/views/candidate_interface/subject_knowledge/show.html.erb
  app/views/candidate_interface/training_with_a_disability/new.html.erb
  app/views/candidate_interface/training_with_a_disability/show.html.erb
  app/views/candidate_interface/unsubmitted_application_form/review.html.erb
  app/views/candidate_interface/volunteering/review/show.html.erb
  app/views/candidate_interface/volunteering/start/show.html.erb
  spec/controllers/concerns/back_links_spec.rb
  spec/helpers/view_helper_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/backlinks_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_with_multiple_sites_spec.rb
  spec/system/candidate_interface/references/candidate_add_references_spec.rb
Labels: deploy_v2, Continuous applications

#8475 Pluralise Your applications title
  app/helpers/navigation_items.rb
  app/views/candidate_interface/continuous_applications_choices/index.html.erb
  app/views/layouts/_header.html.erb
  config/locales/en.yml
  spec/helpers/navigation_items_spec.rb
Labels: deploy_v2

#8476 Users without session can visit the guidance page
  app/controllers/candidate_interface/guidance_controller.rb
  spec/system/candidate_interface/guidance/public_user_spec.rb
Labels: deploy_v2

#8469 Correctly redirect the users on continuous applications
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/base_controller.rb
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  spec/system/candidate_interface/continuous_applications/carry_over/candidate_carries_over_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/redirect_to_your_applications_spec.rb
Labels: deploy_v2

#8477 Highlight the primary navigation items based on controller path
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/helpers/navigation_items.rb
  spec/helpers/navigation_items_spec.rb
  spec/system/candidate_interface/navigation_tabs_spec.rb
Labels: deploy_v2

#8482 Add content message about your details are incomplete
  app/components/candidate_interface/applications_left_message_component.rb
  app/forms/candidate_interface/completed_application_form.rb
  config/locales/candidate_interface/applications_left_message.yml
  spec/components/candidate_interface/applications_left_message_component_spec.rb
  spec/forms/candidate_interface/completed_application_form_spec.rb
Labels: deploy_v2

#8499 [450] Reduce production pods cpu_min requests to 0.8
  terraform/aks/variables.tf
Labels: DevOps

#8500 Show Previous application heading if submitted
  app/models/application_form.rb
  spec/system/candidate_interface/continuous_applications/carry_over/candidate_carries_over_spec.rb
Labels: deploy_v2

#8501 cycle_strings should return years in ascending order
  app/models/recruitment_cycle.rb
  spec/models/recruitment_cycle_spec.rb
Labels: deploy_v2

#8502 The ‘Continue’ button should navigate back to the ‘Your details’ page
  app/controllers/candidate_interface/candidate_interface_controller.rb
  spec/system/candidate_interface/continuous_applications/entering_details/candidate_marking_section_complete_or_incomplete_spec.rb
Labels: deploy_v2
