Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2023-01, with the labels that each got.

#7794 [1027] Add some generic conditions copy for unconditional offers
  app/components/candidate_interface/application_dashboard_course_choices_component.rb
  spec/components/candidate_interface/application_dashboard_course_choices_component_spec.rb
  spec/factories/application_choice.rb
  spec/factories/offer.rb
  spec/factories/provider.rb
  spec/services/save_offer_conditions_from_params_spec.rb
  spec/support/statistics_test_helper.rb
Labels: deploy

#7819 Update content with links to Get Into Teaching
  app/views/candidate_mailer/new_cycle_has_started.erb
  app/views/content/complaints.html.erb
Labels: deploy

#7817 Update the doc link for SP secret renewal
  .github/workflows/check_sp.yml
Labels: DevOps, Notifications, deploy

#7821 Updated content and links to GIT
  app/components/candidate_interface/application_dashboard_guidance_component.html.erb
  app/components/candidate_interface/degree_empty_component.html.erb
  app/components/candidate_interface/degree_empty_component.rb
  app/views/candidate_interface/course_choices/course_decision/go_to_find.html.erb
  app/views/candidate_interface/gcse/missing_qualification/_form.html.erb
  app/views/candidate_interface/subject_knowledge/_form.html.erb
  config/locales/en.yml
Labels: deploy

#7825 Fix the reasons for rejections report
  app/components/support_interface/reason_for_rejection_dashboard_section_component.html.erb
  app/components/support_interface/reason_for_rejection_dashboard_section_component.rb
  app/components/support_interface/reasons_for_rejection_dashboard_component.html.erb
  app/components/support_interface/reasons_for_rejection_search_breadcrumb_component.rb
  app/components/support_interface/reasons_for_rejection_search_results_component.rb
  app/components/support_interface/sub_reasons_for_rejection_table_component.rb
  app/controllers/support_interface/performance_controller.rb
  app/queries/reasons_for_rejection_applications_query.rb
  app/queries/reasons_for_rejection_count_query.rb
  app/views/support_interface/performance/index.html.erb
  spec/components/support_interface/reasons_for_rejection_dashboard_component_spec.rb
  spec/components/support_interface/reasons_for_rejection_search_breadcrumb_component_spec.rb
  spec/components/support_interface/reasons_for_rejection_search_results_component_spec.rb
  spec/components/support_interface/sub_reasons_for_rejection_table_component_spec.rb
  spec/queries/reasons_for_rejection_applications_query_spec.rb
  spec/queries/reasons_for_rejection_count_query_spec.rb
  spec/requests/support_interface/performance_spec.rb
  spec/system/support_interface/reasons_for_rejection_dashboard_spec.rb
Labels: deploy

#7827 Tweak content for reasons for rejection report
  app/components/support_interface/reasons_for_rejection_search_breadcrumb_component.rb
  app/views/support_interface/performance/index.html.erb
  app/views/support_interface/performance/reasons_for_rejection_dashboard.html.erb
  spec/system/support_interface/reasons_for_rejection_dashboard_spec.rb
Labels: deploy

#7840 Refactor Candidate API query
  app/services/candidate_api/serializers/v1_2.rb
  spec/requests/candidate_api/get_candidates_v1_2_spec.rb
Labels: deploy

#7835 Terraform domain configuration
  Makefile
  dns/readme.md
  dns/records/.terraform.lock.hcl
  dns/records/data.tf
  dns/records/resources.tf
  dns/records/terraform.tf
  dns/records/variables.tf
  dns/records/workspace-variables/apply_pentest.tfvars.json
  dns/records/workspace-variables/apply_production.tfvars.json
  dns/records/workspace-variables/apply_qa.tfvars.json
  dns/records/workspace-variables/apply_sandbox.tfvars.json
  dns/records/workspace-variables/apply_staging.tfvars.json
  dns/records/workspace-variables/backend_apply_pentest.tfvars
  dns/records/workspace-variables/backend_apply_production.tfvars
  dns/records/workspace-variables/backend_apply_qa.tfvars
  dns/records/workspace-variables/backend_apply_sandbox.tfvars
  dns/records/workspace-variables/backend_apply_staging.tfvars
  dns/zones/.terraform.lock.hcl
  dns/zones/resources.tf
  dns/zones/terraform.tf
  dns/zones/variables.tf
  dns/zones/workspace-variables/apply-zone.tfvars.json
  dns/zones/workspace-variables/backend_apply.tfvars
Labels: DevOps, deploy, terraform

#7849 Fix a spacing bug
  app/components/candidate_interface/offer_review_component.rb
Labels: deploy

#7839 Update content in candidate mailers about deferrals
  app/components/candidate_interface/application_status_tag_component.html.erb
  app/views/candidate_mailer/conditions_met.text.erb
  app/views/candidate_mailer/new_offer/decisions_pending.text.erb
  app/views/candidate_mailer/new_offer/multiple_offers.text.erb
  app/views/candidate_mailer/new_offer/single_offer.text.erb
  app/views/candidate_mailer/offer_accepted.text.erb
  app/views/candidate_mailer/unconditional_offer_accepted.text.erb
  spec/components/candidate_interface/application_dashboard_course_choices_component_spec.rb
  spec/components/candidate_interface/application_status_tag_component_spec.rb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
Labels: deploy

#7858 Update TTL values pre-migration
  dns/records/workspace-variables/apply_pentest.tfvars.json
  dns/records/workspace-variables/apply_production.tfvars.json
  dns/records/workspace-variables/apply_qa.tfvars.json
  dns/records/workspace-variables/apply_sandbox.tfvars.json
  dns/records/workspace-variables/apply_staging.tfvars.json
Labels: DevOps

#7826 Allow support to change gcse grade
  app/components/shared/gcse_qualification_cards_component.html.erb
  app/controllers/support_interface/application_forms/gcses_controller.rb
  app/decorators/application_choice_export_decorator.rb
  app/decorators/application_qualification_decorator.rb
  app/forms/support_interface/application_forms/edit_gcse_award_year_form.rb
  app/forms/support_interface/application_forms/edit_gcse_grade_form.rb
  app/views/support_interface/application_forms/gcses/edit.html.erb
  app/views/support_interface/application_forms/gcses/edit_award_year.html.erb
  app/views/support_interface/application_forms/gcses/edit_grade.html.erb
  config/locales/support_interface/support_interface.yml
  config/routes.rb
  spec/components/utility/gcse_qualification_cards_component_spec.rb
  spec/decorators/application_qualification_decorator_spec.rb
  spec/factories/application_qualification.rb
  spec/system/support_interface/editing_gcse_award_year_spec.rb
  spec/system/support_interface/editing_gcse_constituent_grade_spec.rb
  spec/system/support_interface/editing_gcse_grade_spec.rb
Labels: deploy

#7875 reset SNYK default app scan setting
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
Labels: DevOps

#7863 Add service.gov.uk zone and records
  Makefile
  dns/records/workspace-variables/apply_pentest.tfvars.json
  dns/records/workspace-variables/apply_production.tfvars.json
  dns/records/workspace-variables/apply_qa.tfvars.json
  dns/records/workspace-variables/apply_sandbox.tfvars.json
  dns/records/workspace-variables/apply_staging.tfvars.json
  dns/zones/workspace-variables/apply-zone.tfvars.json
Labels: DevOps

#7872 [1064] Mark reference section complete on apply-again forms
  app/services/duplicate_application.rb
  spec/services/duplicate_application_spec.rb
  spec/system/candidate_interface/references/candidate_apply_again_spec.rb
Labels: deploy

#7874 Remove `intersex` from the monthly reports
  app/models/publications/monthly_statistics/by_sex.rb
  app/services/data_migrations/remove_intersex_from_reports.rb
  lib/tasks/data.rake
  spec/models/publications/monthly_statistics/by_sex_spec.rb
  spec/services/data_migrations/remove_intersex_from_reports_spec.rb
Labels: deploy

#7878 404 instead of 500 for malformed monthly stats year/month string
  app/controllers/publications/monthly_statistics_controller.rb
  spec/requests/publications/monthly_statistics_spec.rb
Labels: deploy

#7888 Load test changes
  jmeter/.terraform.lock.hcl
  jmeter/plans/provider_codes.txt
  jmeter/workspace_variables/apply.tfvars
  jmeter/workspace_variables/manage.tfvars
  jmeter/workspace_variables/vendor.tfvars
Labels: deploy_v2

#7886 Add clock to AKS deployment
  terraform/modules/kubernetes/main.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps, deploy_v2

#7889 [77] Separate AKS deployment from main Terraform code
  .github/actions/deploy/action.yml
  .github/actions/deploy_v2/action.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-nocache.yml
  .github/workflows/database-backup.yml
  .github/workflows/delete-review-app.yml
  .github/workflows/delete-v2-review-app.yml
  .github/workflows/restore-production-snapshot.yml
  .gitignore
  Makefile
  global_config/review_aks.sh
  terraform/aks/.terraform.lock.hcl
  terraform/aks/data.tf
  terraform/aks/provider.tf
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/review_aks.tfvars.json
  terraform/aks/workspace_variables/review_aks_backend.tfvars
  terraform/paas/.terraform.lock.hcl
  terraform/paas/data.tf
  terraform/paas/provider.tf
  terraform/paas/terraform.tf
  terraform/paas/variables.tf
  terraform/paas/workspace_variables/loadtest.tfvars.json
  terraform/paas/workspace_variables/loadtest_backend.tfvars
  terraform/paas/workspace_variables/production.tfvars.json
  terraform/paas/workspace_variables/production_backend.tfvars
  terraform/paas/workspace_variables/qa.tfvars.json
  terraform/paas/workspace_variables/qa_backend.tfvars
  terraform/paas/workspace_variables/review.tfvars.json
  terraform/paas/workspace_variables/review_backend.tfvars
  terraform/paas/workspace_variables/sandbox.tfvars.json
  terraform/paas/workspace_variables/sandbox_backend.tfvars
  terraform/paas/workspace_variables/staging.tfvars.json
  terraform/paas/workspace_variables/staging_backend.tfvars
Labels: deploy, deploy_v2

#7890 [1094] Populate the new section-completed-at fields
  app/models/application_form.rb
  app/queries/get_incomplete_reference_applications_ready_to_nudge.rb
  app/queries/get_unsubmitted_applications_ready_to_nudge.rb
  app/services/data_migrations/populate_section_completed_ats.rb
  config/analytics.yml
  config/analytics_blocklist.yml
  config/brakeman.ignore
  lib/tasks/data.rake
  spec/models/application_form_spec.rb
  spec/services/data_migrations/populate_section_completed_ats_spec.rb
Labels: deploy

#7894 Remove dead DB migration content
  db/migrate/20200723160935_give_make_decisions_and_manage_users_to_provider_users.rb
Labels: deploy
