Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2023-09, with the labels that each got.

#8511 Secure Continuous Applications endpoints from legacy applications
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/course_choices/course_decision_controller.rb
  app/controllers/candidate_interface/course_choices/course_selection_controller.rb
  app/controllers/candidate_interface/course_choices/provider_selection_controller.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  spec/requests/candidate_interface/continuous_applications_choose_course_spec.rb
  spec/requests/candidate_interface/continuous_applications_reject_legacy_submits_spec.rb
Labels: deploy_v2

#8491 Edit 'Find and Apply' has opened emails and 1 sign in email (continuous applications)
  app/views/authentication_mailer/sign_in_email.text.erb
  app/views/candidate_mailer/find_has_opened.erb
  app/views/candidate_mailer/new_cycle_has_started.erb
  config/locales/candidate_interface/authentication.yml
  spec/mailers/candidate_mailer_spec.rb
Labels: deploy_v2

#8481 Add new test data for continuous applications generation
  app/helpers/cycle_timetable_helper.rb
  app/models/support_interface/applications_filter.rb
  app/workers/generate_test_applications.rb
  spec/components/candidate_interface/carry_over_inset_text_component_spec.rb
  spec/models/application_form_spec.rb
  spec/rails_helper.rb
  spec/services/carry_over_application_spec.rb
  spec/support/cycles.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_and_reviews_rejection_reasons_from_previous_applications_spec.rb
  spec/system/candidate_interface/apply_again/candidate_applies_again_and_views_redesigned_rejection_reasons_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_and_needs_to_select_course_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsuccessful_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/references/candidate_apply_again_spec.rb
  spec/system/candidate_interface/references/candidate_carries_over_unsuccessful_application_to_new_cycle_spec.rb
  spec/system/provider_interface/provider_views_application_submitted_in_new_cycle_feature_flag_disabled_spec.rb
  spec/system/provider_interface/provider_views_the_references_tab_on_manage_spec.rb
  spec/workers/cancel_previous_cycle_unsubmitted_applications_worker_spec.rb
  spec/workers/cancel_unsubmitted_applications_worker_spec.rb
  spec/workers/generate_test_applications_spec.rb
Labels: deploy_v2

#8522 Fix bug on Teacher training Advisor
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/unsubmitted_application_form_controller.rb
  spec/system/candidate_interface/continuous_applications/adviser_sign_up/candidate_signs_up_for_an_adviser_spec.rb
Labels: deploy_v2

#8523 Manage: updated dates and deadlines guidance page
  app/views/content/dates_and_deadlines.md
Labels: deploy_v2

#8531 Bump sentry-sidekiq, dfe-analytics, dfe-autocomplete, dfe-reference-data, get_into_teaching_api_client_faraday, rspec-retry and sentry-rails
  Gemfile.lock
Labels: deploy_v2

#8535 Only write to submitted_at on the first application choice submission
  app/models/application_form.rb
  app/services/candidate_interface/continuous_applications/submit_application_choice.rb
  spec/services/candidate_interface/continuous_applications/submit_application_choice_spec.rb
Labels: Continuous applications

#8533 Introduce course selection limit for continuous applications
  app/components/candidate_interface/applications_left_message_component.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/base_controller.rb
  app/models/application_form.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/services/application_state_change.rb
  app/services/candidate_interface/continuous_applications/application_choice_submission.rb
  app/validators/can_add_more_choices_validator.rb
  app/views/candidate_interface/continuous_applications_choices/index.html.erb
  config/locales/candidate_interface/applications_left_message.yml
  spec/components/candidate_interface/applications_left_message_component_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_submitting_application_spec.rb
  spec/workers/detect_invariants_daily_check_spec.rb
Labels: deploy_v2, Continuous applications

#8539 Update Terms of Use to add a line on working with children
  app/views/content/terms_candidate.html.erb
Labels: deploy_v2

#8536 Ensure our 'go to find' page is up to date
  app/controllers/candidate_interface/continuous_applications/course_choices/go_to_find_controller.rb
  app/views/candidate_interface/continuous_applications/course_choices/go_to_find/new.html.erb
Labels: deploy_v2

#8537 [487] Disable provider RBD automated emails
  app/services/send_reject_by_default_email_to_provider.rb
  spec/services/send_reject_by_default_email_to_provider_spec.rb
Labels: deploy_v2

#8526 Validate science GCSE
  app/components/candidate_interface/continuous_applications/application_submit_component.html.erb
  app/models/application_choice.rb
  app/models/application_form.rb
  app/presenters/candidate_interface/application_form_sections.rb
  app/validators/your_details_completion_validator.rb
  config/locales/candidate_interface/submit_application.yml
  spec/components/candidate_interface/continuous_applications/application_submit_component_spec.rb
  spec/models/application_choice_spec.rb
  spec/presenters/candidate_interface/application_form_sections_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_submitting_application_spec.rb
Labels: deploy_v2

#8549 [487] Disable DBD and provider chaser emails
  app/services/decline_offer_by_default.rb
  app/services/send_chase_email_to_provider.rb
  spec/services/decline_offer_by_default_spec.rb
  spec/services/send_chase_email_to_provider_spec.rb
  spec/system/decline_by_default_spec.rb
  spec/system/decline_by_default_with_continuous_applications_disabled_spec.rb
Labels: deploy_v2

#8552 When user answers no we should redirect to your applications tab
  app/forms/candidate_interface/continuous_applications/find_course_selection_step.rb
  app/lib/dfe/wizard.rb
  app/views/candidate_interface/continuous_applications/course_choices/find_course_selection/new.html.erb
  config/locales/candidate_interface/course_selection_wizard.yml
  spec/lib/dfe/wizard_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_arrives_from_find_and_says_no_to_course_choice_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_arrives_from_find_not_signed_in_spec.rb
Labels: deploy_v2

#8562 [651] Update content under `Your details` tab
  app/helpers/application_details_helper.rb
  app/views/candidate_interface/shared/_details.html.erb
  spec/system/candidate_interface/continuous_applications/entering_details/candidate_marking_section_complete_or_incomplete_spec.rb
  spec/system/candidate_interface/navigation_tabs_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_views_guidance_from_unsubmitted_application_spec.rb
Labels: deploy_v2

#8559 Handle course becoming full warning and actions
  app/components/candidate_interface/application_status_tag_component.html.erb
  app/components/candidate_interface/continuous_applications/application_summary_component.html.erb
  app/components/candidate_interface/continuous_applications/application_summary_component.rb
  app/components/candidate_interface/course_choices_review_component.html.erb
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/utility/unavailable_component.html.erb
  app/components/utility/unavailable_component.rb
  app/models/application_choice.rb
  config/locales/candidate_interface/submit_application.yml
  spec/components/candidate_interface/application_status_tag_component_spec.rb
  spec/components/candidate_interface/continuous_applications/application_summary_component_spec.rb
  spec/factories/course.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_spec.rb
Labels: deploy_v2

#8567 [570] Update content under `Your applications` tab between the apply1 deadline and Find reopening
  app/services/cycle_timetable.rb
  app/views/candidate_interface/continuous_applications_choices/index.html.erb
  config/initializers/date_formats.rb
  spec/config/initializers/date_formats_spec.rb
  spec/services/cycle_timetable_spec.rb
  spec/system/candidate_interface/continuous_applications/carry_over/candidate_carries_over_spec.rb
Labels: deploy_v2

#8571 Edit content for candidate and provider application submitted emails
  app/views/candidate_mailer/application_submitted.text.erb
  app/views/provider_mailer/application_submitted.text.erb
  app/views/provider_mailer/application_submitted_with_safeguarding_issues.text.erb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/provider_mailer_spec.rb
Labels: deploy_v2

#8569 Introduce the 20 unsuccessful application cap
  app/controllers/candidate_interface/after_sign_in_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/base_controller.rb
  app/models/application_form.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/validators/can_add_more_choices_validator.rb
  app/views/candidate_interface/continuous_applications_choices/index.html.erb
  app/workers/detect_invariants_daily_check.rb
  config/locales/en.yml
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_tries_to_submit_after_exceeding_the_maximum_amount_of_unsuccessful_choices_spec.rb
  spec/system/candidate_interface/course_selection/candidate_arrives_from_find_with_the_maximum_amount_of_unsuccessful_choices_spec.rb
  spec/workers/detect_invariants_daily_check_spec.rb
Labels: deploy_v2, Continuous applications

#8575 Do not process interviewing apps to inactive
  app/queries/get_stale_application_choices.rb
  spec/services/process_stale_applications_spec.rb
Labels: Continuous applications

#8574 Edit content for offer changed emails
  app/views/candidate_mailer/changed_offer.text.erb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
Labels: deploy_v2

#8563 Add spring gem to speed up rails and rspec
  Gemfile
  Gemfile.lock
  bin/rails
  bin/rake
  bin/rspec
  bin/spring
  config/environments/development.rb
  config/environments/test.rb
  config/spring.rb
Labels: deploy_v2

#8576 Edit content for candidate withdrawal mailer
  app/views/candidate_mailer/_still_interested_content.text.erb
  app/views/candidate_mailer/withdraw_last_application_choice.text.erb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/system/decline_by_default_with_continuous_applications_disabled_spec.rb
Labels: deploy_v2

#8579 Add post offer dashboard behaviour to candidate interface
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/continuous_applications_choices_controller.rb
  app/helpers/navigation_items.rb
  app/views/candidate_interface/application_form/_review.html.erb
  app/views/candidate_interface/decisions/withdraw.html.erb
  app/views/layouts/_header.html.erb
  spec/helpers/navigation_items_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_spec.rb
Labels: deploy_v2

#8587 Add status, applied at and personal statement to application review page
  app/components/candidate_interface/application_status_tag_component.html.erb
  app/components/candidate_interface/application_status_tag_component.rb
  app/components/candidate_interface/continuous_applications/application_review_component.html.erb
  app/components/candidate_interface/continuous_applications/application_review_component.rb
  app/components/candidate_interface/continuous_applications/application_summary_component.html.erb
  spec/components/candidate_interface/continuous_applications/application_summary_component_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_submitting_application_spec.rb
Labels: deploy_v2

#8584 Amend copy for days since submission
  app/components/candidate_interface/application_status_tag_component.html.erb
  spec/components/candidate_interface/application_status_tag_component_spec.rb
Labels: deploy_v2, Continuous applications

#8578 New rejection emails
  app/mailers/candidate_mailer.rb
  app/services/send_candidate_rejection_email.rb
  app/views/candidate_mailer/_reasons_for_rejection_intro.text.erb
  app/views/candidate_mailer/application_rejected.text.erb
  app/views/layouts/candidate_email_with_support_footer.text.erb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/send_candidate_rejection_email_spec.rb
  spec/system/candidate_interface/continuous_applications/rejections/candidate_receives_rejection_email_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_receives_rejection_email_spec.rb
  spec/system/support_interface/docs_spec.rb
Labels: deploy_v2

#8577 [480] Repuprose withdrawn emails in line with continuous applications
  app/mailers/candidate_mailer.rb
  app/services/provider_interface/send_candidate_withdrawn_on_request_email.rb
  app/views/candidate_mailer/application_withdrawn_on_request.text.erb
  config/locales/application_states.yml
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/provider_interface/send_candidate_withdrawn_on_request_email_spec.rb
  spec/services/provider_interface/send_candidate_withdrawn_on_request_email_with_continuous_applications_flow_inactive_spec.rb
  spec/system/provider_interface/withdraw_an_application_at_candidates_request_spec.rb
Labels: deploy_v2

#8566 Course selection journey for duplicate course selection
  app/controllers/candidate_interface/continuous_applications/course_choices/base_controller.rb
  app/controllers/candidate_interface/continuous_applications/course_choices/duplicate_course_selection_controller.rb
  app/forms/candidate_interface/continuous_applications/course_selection_wizard.rb
  app/forms/candidate_interface/continuous_applications/duplicate_course_selection_step.rb
  app/forms/candidate_interface/continuous_applications/which_course_are_you_applying_to_step.rb
  app/services/candidate_interface/continuous_applications/course_selection_store.rb
  app/validators/candidate_interface/continuous_applications/course_selection_validator.rb
  app/views/candidate_interface/continuous_applications/course_choices/duplicate_course_selection/new.html.erb
  config/locales/en.yml
  config/routes/candidate.rb
  spec/forms/candidate_interface/continuous_applications/which_course_are_you_applying_to_step_spec.rb
  spec/forms/provider_interface/confirm_conditions_wizard_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_duplicate_course_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_duplicate_course_when_editing_spec.rb
Labels: deploy_v2, Continuous applications

#8590 Updated conditions not met CA mailer
  app/views/candidate_mailer/conditions_not_met.text.erb
  app/views/candidate_mailer/decline_last_application_choice.text.erb
  spec/mailers/candidate_mailer_offers_and_rejections_spec.rb
  spec/mailers/candidate_mailer_spec.rb
Labels: deploy_v2

#8593 Remove full stops
  config/locales/candidate_interface/submit_application.yml
  spec/components/candidate_interface/continuous_applications/application_submit_component_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
Labels: deploy_v2

#8583 Editable sections
  app/components/candidate_interface/add_new_reference_component.html.erb
  app/components/candidate_interface/add_new_reference_component.rb
  app/components/candidate_interface/complete_section_component.html.erb
  app/components/candidate_interface/complete_section_component.rb
  app/components/candidate_interface/editable_section_warning.html.erb
  app/components/candidate_interface/editable_section_warning.rb
  app/components/candidate_interface/other_qualifications_review_component.html.erb
  app/components/candidate_interface/personal_details_review_component.rb
  app/controllers/candidate_interface/application_choices_controller.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/contact_details/review_controller.rb
  app/controllers/candidate_interface/degrees/base_controller.rb
  app/controllers/candidate_interface/english_foreign_language/review_controller.rb
  app/controllers/candidate_interface/equality_and_diversity_controller.rb
  app/controllers/candidate_interface/gcse/base_controller.rb
  app/controllers/candidate_interface/interview_availability_controller.rb
  app/controllers/candidate_interface/other_qualifications/base_controller.rb
  app/controllers/candidate_interface/personal_details/review_controller.rb
  app/controllers/candidate_interface/personal_statement_controller.rb
  app/controllers/candidate_interface/references/base_controller.rb
  app/controllers/candidate_interface/restructured_work_history/base_controller.rb
  app/controllers/candidate_interface/safeguarding_controller.rb
  app/controllers/candidate_interface/section_controller.rb
  app/controllers/candidate_interface/subject_knowledge_controller.rb
  app/controllers/candidate_interface/training_with_a_disability_controller.rb
  app/controllers/candidate_interface/volunteering/base_controller.rb
  app/controllers/candidate_interface/volunteering/review_controller.rb
  app/controllers/concerns/accept_offer_confirm_references.rb
  app/services/candidate_interface/section.rb
  app/services/candidate_interface/section_policy.rb
  app/views/candidate_interface/application_choices/review.html.erb
  app/views/candidate_interface/contact_details/review/show.html.erb
  app/views/candidate_interface/degrees/review/show.html.erb
  app/views/candidate_interface/english_foreign_language/review/show.html.erb
  app/views/candidate_interface/equality_and_diversity/review.html.erb
  app/views/candidate_interface/gcse/review/show.html.erb
  app/views/candidate_interface/interview_availability/show.html.erb
  app/views/candidate_interface/other_qualifications/review/show.html.erb
  app/views/candidate_interface/personal_details/review/show.html.erb
  app/views/candidate_interface/personal_statement/show.html.erb
  app/views/candidate_interface/references/review/show.html.erb
  app/views/candidate_interface/restructured_work_history/review/show.html.erb
  app/views/candidate_interface/safeguarding/show.html.erb
  app/views/candidate_interface/subject_knowledge/show.html.erb
  app/views/candidate_interface/training_with_a_disability/show.html.erb
  app/views/candidate_interface/volunteering/review/show.html.erb
  docs/editable_sections.md
  spec/components/candidate_interface/complete_section_component_spec.rb
  spec/components/candidate_interface/editable_section_warning_spec.rb
  spec/components/candidate_interface/other_qualifications_review_component_spec.rb
  spec/services/candidate_interface/section_policy_spec.rb
  spec/system/candidate_interface/continuous_applications/entering_details/candidate_can_edit_some_sections_after_first_submission_spec.rb
  spec/system/candidate_interface/continuous_applications/entering_details/candidate_can_not_edit_some_sections_after_first_submission_spec.rb
  spec/views/degrees/show.html.erb_spec.rb
Labels: deploy_v2, Continuous applications

#8594 Update full stop issue
  app/validators/cycle_verification_validator.rb
  spec/components/candidate_interface/continuous_applications/application_submit_component_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
Labels: deploy_v2

#8609 Update error messages in course selection flow
  config/locales/candidate_interface/course_selection_wizard.yml
  config/locales/candidate_interface/courses.yml
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_with_multiple_sites_spec.rb
Labels: deploy_v2

#8599 Add course selection journey for courses with no vacancies
  app/controllers/candidate_interface/continuous_applications/course_choices/full_course_selection_controller.rb
  app/forms/candidate_interface/continuous_applications/course_selection_wizard.rb
  app/forms/candidate_interface/continuous_applications/full_course_selection_step.rb
  app/forms/candidate_interface/continuous_applications/which_course_are_you_applying_to_step.rb
  app/forms/candidate_interface/pick_course_form.rb
  app/views/candidate_interface/continuous_applications/course_choices/full_course_selection/new.html.erb
  app/views/candidate_interface/continuous_applications/course_choices/which_course_are_you_applying_to/_form_fields.html.erb
  app/views/candidate_interface/course_choices/course_selection/_form_fields.html.erb
  app/views/candidate_interface/course_choices/course_selection/full.html.erb
  config/locales/en.yml
  config/routes/candidate.rb
  spec/forms/candidate_interface/continuous_applications/which_course_are_you_applying_to_step_spec.rb
  spec/forms/candidate_interface/pick_course_form_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_that_is_full_spec.rb
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_that_is_full_spec.rb
Labels: deploy_v2
