Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2024-10, with the labels that each got.

#9877 [2315] part 3, Ignore redundant decline_by_default columns
  app/components/candidate_interface/offers_call_to_action_component.rb
  app/models/application_choice.rb
  app/services/candidate_interface/sort_application_choices.rb
  app/services/data_migrations/set_decline_by_default_at_and_decline_by_default_days_to_nil.rb
  app/services/provider_interface/sort_application_choices.rb
  config/analytics.yml
  config/analytics_blocklist.yml
  lib/tasks/data.rake
  spec/components/candidate_interface/offers_call_to_action_component_spec.rb
  spec/forms/support_interface/application_forms/reinstate_declined_offer_form_spec.rb
  spec/services/data_migrations/set_decline_by_default_at_and_decline_by_default_days_to_nil_spec.rb
  spec/services/provider_interface/sort_application_choices_spec.rb
  spec/services/reinstate_declined_offer_spec.rb
Labels: deploy_v2

#9881 [2367] Scale pods for start of cycle MERGE ON 4 OCT
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: DO NOT MERGE

#9889 Updated API documentation
  config/vendor_api/v1.1.yml
Labels: deploy_v2

#9887 Add spec to guarantee empty degrees is returned from TDA courses
  spec/support/test_helpers/candidate_helper.rb
  spec/system/register_api/register_receives_application_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: deploy_v2

#9905 Automatically selected location is appearing to candidate on a submitted application
  app/components/candidate_interface/offer_review_component.rb
  app/components/provider_interface/offer_summary_component.rb
  app/controllers/candidate_interface/decisions_controller.rb
  app/helpers/summary_list_rows_helper.rb
  spec/components/candidate_interface/offer_review_component_spec.rb
  spec/components/provider_interface/offer_summary_component_spec.rb
Labels: deploy_v2

#9907 Show the right data when seeing undergraduate courses in provider interface
  app/helpers/qualification_value_helper.rb
  spec/components/provider_interface/application_course_summary_component_spec.rb
Labels: deploy_v2

#9913 Remove teacher degree apprenticeship feature flag code
  app/components/candidate_interface/degree_empty_component.html.erb
  app/components/candidate_interface/other_qualifications_review_component.html.erb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/degrees/destroy_controller.rb
  app/models/application_form.rb
  app/models/provider_interface/provider_applications_filter.rb
  app/presenters/candidate_interface/application_form_presenter.rb
  app/services/feature_flag.rb
  app/services/sample_applications_factory.rb
  app/validators/incomplete_postgraduate_course_details_validator.rb
  app/views/candidate_interface/degrees/degree/new_country.html.erb
  app/views/candidate_interface/degrees/review/show.html.erb
  app/views/candidate_interface/other_qualifications/type/_shared_form.html.erb
  app/views/candidate_mailer/tailored_rejection_advice/_no_degree_tailored_advice.text.erb
  config/locales/candidate_interface/degree.yml
  spec/components/candidate_interface/degree_empty_component_spec.rb
  spec/components/candidate_interface/other_qualifications_review_component_spec.rb
  spec/factories/application_form.rb
  spec/models/application_form_spec.rb
  spec/models/provider_interface/provider_applications_filter_spec.rb
  spec/presenters/candidate_interface/application_form_presenter_spec.rb
  spec/services/candidate_interface/application_choice_submission_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/entering_details/candidate_entering_other_qualification_no_qualification_option_choice_spec.rb
  spec/system/candidate_interface/entering_details/degrees/backlinks_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_adding_unknown_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_delete_and_replace_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_editing_international_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_international_degree_without_a_grade_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_international_degree_without_an_enic_reason_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_international_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_masters_degree_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_phd_degree_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_university_degree_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_and_prefills_application_in_sandbox_spec.rb
  spec/system/candidate_interface/submitting/candidate_tries_submit_to_undergraduate_course_without_a_levels_spec.rb
  spec/system/candidate_interface/submitting/candidate_tries_to_submit_postgraduate_course_without_degrees_spec.rb
  spec/system/provider_interface/provider_applications_filter_spec.rb
  spec/system/provider_interface/provider_views_a_teacher_degree_apprenticeship_application_spec.rb
  spec/system/register_api/register_receives_application_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
  spec/views/degrees/show.html.erb_spec.rb
Labels: deploy_v2

#9903 Add A level reasons for rejection for undergraduate applications *only*
  app/components/candidate_interface/rejection_reasons/rejection_reasons_component.html.erb
  app/components/shared/rejection_reasons/rejection_reasons_component.html.erb
  app/forms/provider_interface/rejections_wizard.rb
  app/models/rejection_reasons/reason.rb
  app/presenters/rejection_reasons/rejection_reasons_presenter.rb
  app/views/candidate_mailer/application_rejected.text.erb
  app/views/provider_interface/rejections/check.html.erb
  app/views/provider_interface/rejections/new.html.erb
  config/locales/provider_interface/rejections.yml
  config/rejection_reasons.yml
  spec/components/candidate_interface/rejection_reasons/rejection_reasons_component_spec.rb
  spec/components/shared/rejection_reasons/rejection_reasons_component_spec.rb
  spec/factories/application_choice.rb
  spec/forms/provider_interface/rejections_wizard_spec.rb
  spec/mailers/candidate_mailer_application_rejected_tailored_advice_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/models/rejection_reasons/reason_spec.rb
  spec/presenters/rejection_reasons/rejection_reasons_presenter_spec.rb
  spec/system/provider_interface/reject_an_application_spec.rb
Labels: deploy_v2

#9915 1427 changing a science gcse grade on support console doesnt always work
  app/forms/concerns/science_gcse_helper.rb
  app/forms/support_interface/science_gcse_form.rb
  spec/factories/application_qualification.rb
  spec/forms/candidate_interface/science_gcse_grade_form_spec.rb
  spec/system/support_interface/change_science_gcse_spec.rb
  spec/system/support_interface/change_uk_to_not_uk_science_gcse_spec.rb
Labels: deploy_v2

#9933 Add rejection reasons for providers
  app/presenters/rejection_reasons/rejection_reasons_presenter.rb
  config/rejection_reason_codes.yml
  config/rejection_reasons.yml
  config/vendor_api/v1.2.yml
  spec/forms/provider_interface/rejections_wizard_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/system/provider_interface/reject_an_application_spec.rb
Labels: deploy_v2

#9940 Add missing translations for new rejection errors
  config/locales/provider_interface/rejections.yml
Labels: deploy_v2

#9932 [21] Monthly Statistics Pause the monthly generation & publication for October 2024
  app/services/monthly_statistics_timetable.rb
  spec/factories/monthly_statistics_reports.rb
  spec/services/monthly_statistics_timetable_spec.rb
  spec/workers/generate_monthly_statistics_spec.rb
Labels: deploy_v2

#9941 Change content on placement locations page
  app/views/candidate_interface/course_choices/course_site/_form_fields.html.erb
  config/locales/candidate_interface/course_choices/course_site.yml
Labels: deploy_v2

#9924 [17] Revert start-of-cycle scaling
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: deploy_v2

#9947 Format worker logs in production
  config/environments/production.rb
Labels: deploy_v2

#9959 [341] Update service information banner text and to support interface
  app/views/support_interface/candidates/_candidates_navigation.html.erb
  config/locales/service_information_banner.yml
Labels: deploy_v2

#9953 Upgraded to Ruby version 3.3.5
  .devcontainer/devcontainer.json
  .ruby-version
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
Labels: deploy_v2

#9958 Fix incorrect candidate bachelor degree equivalency
  app/components/candidate_interface/degree_review_component.rb
  app/lib/hesa/degree_type.rb
  spec/components/candidate_interface/degree_review_component_spec.rb
  spec/lib/hesa/degree_type_spec.rb
Labels: deploy_v2

#9961 Allow Support Users to change Course to previous Recruitment Cycles
  app/controllers/support_interface/application_forms/courses_controller.rb
  app/forms/support_interface/application_forms/change_course_choice_form.rb
  app/services/support_interface/change_application_choice_course_option.rb
  app/views/support_interface/application_forms/courses/edit.html.erb
  spec/forms/support_interface/application_forms/change_course_choice_form_spec.rb
  spec/services/support_interface/change_application_choice_course_option_spec.rb
  spec/system/support_interface/change_course_to_different_year_spec.rb
Labels: deploy_v2

#9963 [344] Surface last login date for support users
  app/controllers/support_interface/support_users_controller.rb
  app/views/support_interface/support_users/index.html.erb
  spec/system/support_interface/managing_support_users_spec.rb
Labels: deploy_v2

#9901 Set maxlength and inputmode html attribute for all year inputs
  app/views/candidate_interface/degrees/degree/new_award_year.erb
  app/views/candidate_interface/degrees/degree/new_start_year.html.erb
  app/views/candidate_interface/english_foreign_language/ielts/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/other_efl_qualification/_form_fields.html.erb
  app/views/candidate_interface/english_foreign_language/toefl/_form_fields.html.erb
  app/views/candidate_interface/gcse/year/_form.html.erb
  app/views/candidate_interface/other_qualifications/details/_form.html.erb
  app/views/support_interface/application_forms/degrees/edit.html.erb
  app/views/support_interface/application_forms/other_qualifications/edit.html.erb
  app/views/support_interface/english_gcse_forms/_english_gcse_form.html.erb
  app/views/support_interface/math_gcse_forms/_math_gcse_form.html.erb
  app/views/support_interface/science_gcse_forms/_science_gcse_form.html.erb
Labels: deploy_v2

#9964 Extract config from application.rb to initializers
  config/application.rb
  config/environments/production.rb
  config/initializers/action_dispatch.rb
  config/initializers/action_mailer.rb
  config/initializers/action_view.rb
  config/initializers/active_job.rb
  config/initializers/application_controller.rb
  config/initializers/cache_store.rb
  config/initializers/dfe_analytics.rb
  config/initializers/exceptions.rb
  config/initializers/grover.rb
  config/initializers/i18n.rb
  config/initializers/inflections.rb
  config/initializers/middleware.rb
  config/initializers/sections.rb
  config/initializers/skylight.rb
  config/initializers/view_component.rb
  lib/modules/aws_ip_ranges.rb
  spec/lib/modules/aws_ip_ranges_spec.rb
Labels: deploy_v2

#9973 Bring the journey uk and non uk degree in line
  app/forms/candidate_interface/degree_wizard.rb
  spec/forms/candidate_interface/degree_wizard_spec.rb
  spec/system/candidate_interface/entering_details/degrees/backlinks_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_editing_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_editing_international_degrees_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_international_degree_without_a_grade_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_international_degree_without_an_enic_reason_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_entering_international_degrees_spec.rb
  spec/system/temporarily_editable_sections_spec.rb
Labels: deploy_v2

#9972 Fix hesa ethnicity for 2023/2024 application forms
  app/services/data_migrations/correct_hesa_ethnicity.rb
  spec/services/data_migrations/correct_hesa_ethnicity_spec.rb
Labels: deploy_v2

#9960 [341] Reverts DB changes
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: DO NOT MERGE, deploy_v2

#9980 Fix degree form when changing countries and backing off
  app/forms/candidate_interface/degree_wizard.rb
  spec/forms/candidate_interface/degree_wizard_spec.rb
Labels: deploy_v2

#9978 Remove hidden country field on degree#coutry
  app/views/candidate_interface/degrees/degree/new_country.html.erb
Labels: deploy_v2

#9987 Updated wording for "QTS with PGDE" qualifications
  app/models/course.rb
  spec/models/course_spec.rb
Labels: deploy_v2

#9969 [112] Update values for structured reasons for withdrawal
  config/withdrawal_reasons.yml
  spec/factories/application_choice.rb
  spec/services/provider_interface/candidate_withdrawal_data_by_provider_spec.rb
Labels: DO NOT MERGE, deploy_v2

#9991 Add new fields to tad report
  app/exports/tad_export.yml
  app/services/data_api/tad_application_export.rb
  spec/services/data_api/tad_application_export_spec.rb
Labels: deploy_v2

#9970 [112 pt 2] Migration for updating the withdrawal reasons
  app/services/data_migrations/backfill_withdrawal_reasons.rb
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_withdrawal_reasons_spec.rb
Labels: deploy_v2
