Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2024-08, with the labels that each got.

#9609 Backfilling week 42 data on performance reports
  app/services/data_migrations/backfill_week42_performance_report_data.rb
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_week42_performance_report_data_spec.rb
Labels: deploy_v2

#9407 Send test cluster container logs to logit.io
  terraform/aks/application.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/review_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: deploy_v2

#9614 Added Candidate Detail endpoint to CandidateAPI
  app/controllers/candidate_api/candidates_controller.rb
  app/services/candidate_api/serializers/base.rb
  app/services/candidate_api/serializers/v1_1.rb
  app/services/candidate_api/serializers/v1_2.rb
  app/services/candidate_api/serializers/v1_3.rb
  config/candidate_api/v1.1.yml
  config/candidate_api/v1.2.yml
  config/candidate_api/v1.3.yml
  config/routes/api/candidate.rb
  spec/requests/candidate_api/get_candidate_spec.rb
Labels: deploy_v2

#9641 Attempt to fix Grover
  config/initializers/grover.rb
Labels: deploy_v2

#9629 Ignore ApplicationQualification#equivalency_details
  app/decorators/application_choice_export_decorator.rb
  app/decorators/degree_export_decorator.rb
  app/models/application_qualification.rb
  config/analytics.yml
  docs/support_playbook.md
  spec/decorators/application_choice_export_decorator_spec.rb
  spec/decorators/degree_export_decorator_spec.rb
  spec/factories/application_qualification.rb
  spec/models/application_qualification_spec.rb
  spec/presenters/concerns/qualification_api_data_spec.rb
  spec/presenters/register_api/single_application_presenter_spec.rb
  spec/services/provider_interface/application_data_export_spec.rb
Labels: deploy_v2

#9648 Drop ApplicationQualifications#equivalency-details
  db/migrate/20240806133548_drop_equivalency_details.rb
  db/schema.rb
  docs/domain-model.png
Labels: deploy_v2

#9639 Move field from pii to hidden pii
  config/analytics_hidden_pii.yml
  config/analytics_pii.yml
Labels: deploy_v2

#9640 [2109] Reinstate reject and decline by default jobs for end of cycle only
  app/helpers/cycle_timetable_helper.rb
  app/services/application_state_change.rb
  app/services/cycle_timetable.rb
  app/services/end_of_cycle/decline_by_default_service.rb
  app/services/end_of_cycle/reject_by_default_service.rb
  app/workers/cancel_unsubmitted_applications_worker.rb
  app/workers/end_of_cycle/decline_by_default_worker.rb
  app/workers/end_of_cycle/reject_by_default_worker.rb
  config/clock.rb
  config/locales/application_states.yml
  spec/services/cycle_timetable_spec.rb
  spec/services/end_of_cycle/reject_by_default_service_spec.rb
  spec/workers/cancel_unsubmitted_applications_worker_spec.rb
  spec/workers/end_of_cycle/decline_by_default_worker_spec.rb
  spec/workers/end_of_cycle/reject_by_default_worker_spec.rb
Labels: deploy_v2

#9660 [1909] Ship sandbox and production logs to Logit.io
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
Labels: DevOps

#9664 [2072] Add a distinct second end-of-cycle chaser email
  app/components/shared/end_of_cycle_emails_component.rb
  app/mailers/candidate_mailer.rb
  app/models/chaser_sent.rb
  app/queries/get_applications_to_send_deadline_reminders_to.rb
  app/services/cycle_timetable.rb
  app/services/send_eoc_deadline_reminder_email_to_candidate.rb
  app/views/candidate_mailer/eoc_first_deadline_reminder.erb
  app/views/candidate_mailer/eoc_second_deadline_reminder.erb
  app/workers/send_eoc_deadline_reminder_email_to_candidates_batch_worker.rb
  app/workers/send_eoc_deadline_reminder_email_to_candidates_worker.rb
  config/locales/emails/candidate_mailer.yml
  config/locales/en.yml
  spec/components/shared/end_of_cycle_emails_component_spec.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/cycle_timetable_spec.rb
  spec/services/send_eoc_deadline_reminder_email_to_candidate_spec.rb
  spec/system/support_interface/docs_spec.rb
  spec/workers/send_eoc_deadline_reminder_email_to_candidates_batch_worker_spec.rb
  spec/workers/send_eoc_deadline_reminder_email_to_candidates_worker_spec.rb
Labels: deploy_v2

#9671 Backfill ApplicationExperience#experienceable
  app/services/data_migrations/backfill_experienceable_for_application_forms.rb
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_experienceable_for_application_forms_spec.rb
Labels: deploy_v2

#9675 Make sure references from old cycles are editable in support
  app/forms/support_interface/application_forms/edit_reference_details_form.rb
  app/forms/support_interface/application_forms/edit_reference_feedback_form.rb
  spec/forms/support_interface/application_forms/edit_reference_details_form_spec.rb
  spec/forms/support_interface/application_forms/edit_reference_feedback_form_spec.rb
Labels: deploy_v2

#9678 [1884] Add 2026 cycle dates to codebase
  app/services/cycle_timetable.rb
  config/initializers/cycle_timetables.rb
  spec/services/cycle_timetable_spec.rb
Labels: deploy_v2

#9686 [2155] Part 1 UX changes for between cycles
  app/components/candidate_interface/carry_over_interstitial_component.html.erb
  app/components/candidate_interface/carry_over_interstitial_component.rb
  app/models/application_form.rb
  app/services/application_state_change.rb
  app/views/candidate_interface/continuous_applications_choices/index.html.erb
  spec/models/application_form_spec.rb
  spec/requests/candidate_interface/cycle_redirects_spec.rb
  spec/requests/candidate_interface/personal_statement_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_after_rejecting_offer_between_cycles_spec.rb
  spec/system/candidate_interface/carry_over/candidate_has_application_rejected_by_default_spec.rb
  spec/system/candidate_interface/carry_over/candidate_receives_offer_betwen_cycles_spec.rb
Labels: deploy_v2

#9690 Use ApplicationExperience#experienceable
  app/models/application_experience.rb
  app/models/application_form.rb
  spec/models/application_experience_spec.rb
  spec/models/application_form_spec.rb
Labels: deploy_v2

#9697 Remove application_form from ApplicationExperience
  app/models/application_experience.rb
  app/models/application_volunteering_experience.rb
  app/models/application_work_experience.rb
  spec/components/candidate_interface/volunteering_review_component_spec.rb
  spec/forms/support_interface/application_forms/job_form_spec.rb
  spec/forms/support_interface/application_forms/volunteering_role_form_spec.rb
  spec/models/application_experience_spec.rb
  spec/models/application_form_spec.rb
  spec/models/application_volunteering_experience_spec.rb
  spec/models/application_work_experience_spec.rb
  spec/models/candidate_spec.rb
  spec/models/last_updated_at_spec.rb
  spec/services/data_migrations/backfill_experienceable_for_application_forms_spec.rb
  spec/services/data_migrations/cleanup_application_experiences_experienceable_spec.rb
  spec/services/support_interface/work_history_break_export_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsuccessful_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/entering_details/candidate_edits_or_deletes_volunteering_section_after_competing_the_section_spec.rb
  spec/system/candidate_interface/entering_details/candidate_edits_or_deletes_volunteering_section_with_restructured_work_history_active_spec.rb
  spec/system/provider_interface/see_individual_application_personal_statement_spec.rb
  spec/system/support_interface/change_job_spec.rb
  spec/system/support_interface/change_volunteering_role_spec.rb
Labels: deploy_v2

#9704 [1986] Remove front door alerting
  terraform/custom_domains/environment_domains/.terraform.lock.hcl
  terraform/custom_domains/environment_domains/terraform.tf
  terraform/custom_domains/environment_domains/workspace_variables/apply_production.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_qa.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_sandbox.tfvars.json
  terraform/custom_domains/environment_domains/workspace_variables/apply_staging.tfvars.json
  terraform/custom_domains/infrastructure/.terraform.lock.hcl
  terraform/custom_domains/infrastructure/terraform.tf
  terraform/custom_domains/infrastructure/workspace_variables/apply.tfvars.json
Labels: DevOps

#9674 Ignore ApplicationExperience#application_form_id
  app/models/application_experience.rb
  app/models/candidate.rb
  app/services/data_migrations/backfill_experienceable_for_application_forms.rb
  app/services/data_migrations/cleanup_application_experiences_experienceable.rb
  app/workers/delete_test_applications.rb
  config/analytics.yml
  lib/tasks/data.rake
  spec/forms/candidate_interface/restructured_work_history/job_form_spec.rb
  spec/forms/candidate_interface/volunteering_role_form_spec.rb
  spec/forms/support_interface/application_forms/job_form_spec.rb
  spec/services/data_migrations/backfill_experienceable_for_application_forms_spec.rb
  spec/services/data_migrations/cleanup_application_experiences_experienceable_spec.rb
Labels: deploy_v2

#9689 Add Workload Identity Federation
  .env.development
  .env.example
  .env.test
  config/initializers/workload_identity_federation.rb
  docs/development/workload-identity-federation-diagram.png
  docs/development/workload_identity_federation.md
  lib/workload_identity_federation.rb
  lib/workload_identity_federation/azure_access_token.rb
  lib/workload_identity_federation/google_access_token.rb
  lib/workload_identity_federation/google_token_exchange.rb
  lib/workload_identity_federation/user_credentials.rb
  spec/lib/workload_identity_federation/azure_access_token_spec.rb
  spec/lib/workload_identity_federation/google_access_token_spec.rb
  spec/lib/workload_identity_federation/google_token_exchange_spec.rb
  spec/lib/workload_identity_federation/user_credentials_spec.rb
  spec/rails_helper.rb
  spec/support/workload_identity_federation_stubs.rb
Labels: deploy_v2

#9713 Write to ApplicationWorkHistoryBreak#breakable
  app/models/application_work_history_break.rb
  spec/forms/candidate_interface/restructured_work_history/work_history_break_form_spec.rb
  spec/models/application_work_history_break_spec.rb
Labels: deploy_v2

#9715 Backfill ApplicationWorkHistoryBreak#breakable
  app/services/data_migrations/backfill_application_work_history_breaks.rb
  lib/tasks/data.rake
  spec/services/data_migrations/backfill_application_work_history_breaks_spec.rb
Labels: deploy_v2

#9708 Fix errors that mobile users are experiencing on apply
  app/controllers/application_controller.rb
  config/application.rb
Labels: deploy_v2

#9723 Use ApplicationWorkHistoryBreak#breakable column
  app/models/application_form.rb
  app/models/application_work_history_break.rb
  spec/models/application_work_history_break_spec.rb
Labels: deploy_v2

#9722 Update terraform providers
  terraform/aks/.terraform.lock.hcl
  terraform/aks/provider.tf
  terraform/modules/statuscake/main.tf
Labels: DevOps, deploy_v2

#9729 Remove WorkHistoryBreak#application_form_id
  app/models/application_work_history_break.rb
  app/services/data_migrations/backfill_application_work_history_breaks.rb
  lib/tasks/data.rake
  spec/forms/candidate_interface/restructured_work_history/work_history_break_form_spec.rb
  spec/models/application_work_history_break_spec.rb
  spec/models/last_updated_at_spec.rb
  spec/services/data_migrations/backfill_application_work_history_breaks_spec.rb
  spec/services/support_interface/work_history_break_export_spec.rb
  spec/system/provider_interface/see_individual_application_personal_statement_spec.rb
Labels: deploy_v2

#9718 Reports use Workload Identity Federation and Bigqueryv2 API
  app/lib/dfe/bigquery.rb
  app/lib/dfe/bigquery/application_metrics.rb
  app/lib/dfe/bigquery/application_metrics_by_provider.rb
  app/lib/dfe/bigquery/relation.rb
  app/lib/dfe/bigquery/table.rb
  app/lib/dfe/bigquery/test_helper.rb
  app/models/publications/monthly_statistics/statistics_data_processor.rb
  config/initializers/dfe_bigquery.rb
  docs/development/bigquery_and_reports.md
  spec/lib/dfe/bigquery/application_metrics_by_provider_spec.rb
  spec/lib/dfe/bigquery/application_metrics_spec.rb
  spec/lib/dfe/bigquery/table_spec.rb
  spec/lib/dfe/bigquery_spec.rb
  spec/models/publications/itt_monthly_report_generator_spec.rb
  spec/models/publications/national_recruitment_performance_report_generator_spec.rb
  spec/models/publications/provider_recruitment_performance_report_generator_spec.rb
  spec/support/bigquery_stubs.rb
  spec/support/test_helper.rb
Labels: deploy_v2

#9734 Drop ApplicationWorkHistoryBreak#application_form_id
  db/migrate/20240819153526_drop_application_form_id_from_application_work_history_break.rb
  db/schema.rb
  docs/domain-model.png
Labels: deploy_v2

#9735 Use application_choice polymorphic associations
  app/components/shared/work_history_and_unpaid_experience_component.rb
  app/models/application_choice.rb
  app/presenters/concerns/work_experience_api_data.rb
  app/services/work_history_with_breaks.rb
  app/views/provider_interface/application_choices/show.html.erb
  spec/models/application_choice_spec.rb
  spec/services/work_history_with_breaks_spec.rb
Labels: deploy_v2

#9745 Fix for primary navigation highlighting
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/services/candidate_interface/choices_controller_matcher.rb
  spec/helpers/navigation_items_spec.rb
  spec/services/candidate_interface/choices_controller_matcher_spec.rb
  spec/system/candidate_interface/navigation_tabs_spec.rb
Labels: deploy_v2

#9739 Dup work experiences and histories on choice
  app/models/application_experience.rb
  app/models/application_work_history_break.rb
  app/services/candidate_interface/submit_application_choice.rb
  spec/models/last_updated_at_spec.rb
  spec/services/candidate_interface/submit_application_choice_spec.rb
  spec/system/vendor_api/vendor_receives_application_spec.rb
Labels: deploy_v2

#9709 [2171] Render different carry over content between cycles
  app/components/candidate_interface/after_deadline_content_component.html.erb
  app/components/candidate_interface/after_deadline_content_component.rb
  app/components/candidate_interface/carried_over_content_component.html.erb
  app/components/candidate_interface/carried_over_content_component.rb
  app/components/candidate_interface/carry_over_between_cycles_component.html.erb
  app/components/candidate_interface/carry_over_between_cycles_component.rb
  app/components/candidate_interface/carry_over_interstitial_component.rb
  app/components/candidate_interface/carry_over_mid_cycle_component.html.erb
  app/components/candidate_interface/carry_over_mid_cycle_component.rb
  app/components/candidate_interface/mid_cycle_content_component.html.erb
  app/components/candidate_interface/mid_cycle_content_component.rb
  app/helpers/navigation_items.rb
  app/views/candidate_interface/carry_over/not_submitted/start.html.erb
  app/views/candidate_interface/continuous_applications_choices/index.html.erb
  app/views/layouts/_header.html.erb
  config/locales/candidate_interface/carry_over_after_deadline_component.yml
  config/locales/components/candidate_interface/after_deadline_content_component.yml
  config/locales/components/candidate_interface/carried_over_content_component.yml
  config/locales/components/candidate_interface/mid_cycle_content_component.yml
  config/locales/en.yml
  spec/components/candidate_interface/carry_over_between_cycles_component_spec.rb
  spec/components/candidate_interface/carry_over_interstitial_component_spec.rb
  spec/components/candidate_interface/carry_over_mid_cycle_component_spec.rb
  spec/helpers/navigation_items_spec.rb
  spec/system/candidate_interface/carry_over/candidate_can_submit_in_next_cycle_when_cycle_switched_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_after_rejecting_offer_between_cycles_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_before_apply_opens_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_with_a_course_to_new_cycle_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsuccessful_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/carry_over/candidate_does_not_act_on_offer_spec.rb
  spec/system/candidate_interface/carry_over/candidate_has_application_rejected_by_default_spec.rb
  spec/system/candidate_interface/carry_over/candidate_receives_offer_betwen_cycles_spec.rb
  spec/system/candidate_interface/carry_over/candidate_views_and_withdraws_after_apply_deadline_spec.rb
  spec/system/candidate_interface/continuous_applications/carry_over/candidate_carries_over_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_attempts_to_add_course_from_find_to_application_from_previous_cycle_spec.rb
Labels: deploy_v2

#9749 Fix provider audit logs
  app/views/provider_interface/activity_log/index.html.erb
  spec/factories/audit.rb
  spec/system/provider_interface/see_activity_log_spec.rb
Labels: deploy_v2

#9750 Add scenario that syncs TDA courses to the teacher training API
  spec/factories/course.rb
  spec/system/teacher_training_public_api/sync_courses_spec.rb
Labels: deploy_v2

#9753 Exclude work experiences from provider audits
  app/queries/get_activity_log_events.rb
  app/views/provider_interface/activity_log/index.html.erb
  config/brakeman.ignore
  spec/queries/get_activity_log_events_spec.rb
Labels: deploy_v2

#9761 Update reopen banner with new content
  app/components/candidate_interface/reopen_banner_component.html.erb
  app/components/candidate_interface/reopen_banner_component.rb
  config/locales/components/candidate_interface/reopen_banner_component.yml
  spec/components/candidate_interface/reopen_banner_component_spec.rb
  spec/components/previews/candidate_interface/reopen_banner_alert_preview.rb
Labels: deploy_v2

#9755 [2153] Candidate email deadline passed unsubmitted applications
  app/components/shared/end_of_cycle_emails_component.rb
  app/helpers/cycle_timetable_helper.rb
  app/mailers/candidate_mailer.rb
  app/queries/get_applications_to_send_deadline_reminders_to.rb
  app/services/cycle_timetable.rb
  app/services/email_timetable.rb
  app/views/candidate_mailer/application_deadline_has_passed.text.erb
  app/workers/end_of_cycle/send_application_deadline_has_passed_email_to_candidates_worker.rb
  app/workers/end_of_cycle/send_reject_by_default_reminder_to_providers_worker.rb
  app/workers/send_eoc_deadline_reminder_email_to_candidates_worker.rb
  app/workers/send_find_has_opened_email_to_candidates_worker.rb
  app/workers/send_new_cycle_has_started_email_to_candidates_worker.rb
  config/clock.rb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/services/cycle_timetable_spec.rb
  spec/services/email_timetable_spec.rb
  spec/system/support_interface/docs_spec.rb
  spec/workers/end_of_cycle/send_application_deadline_has_passed_email_to_candidates_batch_worker_spec.rb
  spec/workers/end_of_cycle/send_application_deadline_has_passed_email_to_candidates_worker_spec.rb
  spec/workers/send_eoc_deadline_reminder_email_to_candidates_worker_spec.rb
  spec/workers/send_find_has_opened_email_to_candidates_worker_spec.rb
  spec/workers/send_new_cycle_has_started_email_to_candidates_worker_spec.rb
Labels: deploy_v2
