Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2024-05, with the labels that each got.

#9331 1561 recruitment performance reports data presentation
  app/components/provider_interface/recruitment_performance_report/proportion_candidates_with_offers_table_component.rb
  app/components/provider_interface/recruitment_performance_report/subject_table_component.html.erb
  app/components/provider_interface/recruitment_performance_report/subject_table_component.rb
  app/components/provider_interface/recruitment_performance_report/submitted_applications_table_component.rb
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_recruitment_performance_report.scss
  app/services/provider_interface/reports/subject_rows_builder_service.rb
  app/views/provider_interface/reports/recruitment_performance_reports/show.html.erb
  config/locales/components/provider_interface/recruitment_performance_report/en.yml
  spec/components/previews/provider_interface/subject_table_component_preview.rb
  spec/components/provider_interface/recruitment_performance_report/proportion_candidates_with_offers_table_component_spec.rb
  spec/components/provider_interface/recruitment_performance_report/submitted_applications_table_component_spec.rb
  spec/factories/national_recruitment_performance_report.rb
  spec/factories/provider_recruitment_performance_report.rb
  spec/services/provider_interface/reports/subject_rows_builder_service_spec.rb
  spec/system/provider_interface/reports/view_provider_recruitment_performance_report_spec.rb
Labels: deploy_v2

#9340 Recruitment performance generator and worker
  app/lib/dfe/bigquery/application_metrics_by_provider.rb
  app/lib/dfe/bigquery/test_helper.rb
  app/models/application_choice.rb
  app/models/publications/national_recruitment_performance_report_generator.rb
  app/models/publications/provider_recruitment_performance_report_generator.rb
  app/models/publications/recruitment_performance_report_scheduler.rb
  app/queries/providers_for_recruitment_performance_report_query.rb
  app/services/cycle_timetable.rb
  app/services/recruitment_performance_report_timetable.rb
  app/workers/publications/national_recruitment_performance_report_worker.rb
  app/workers/publications/provider_recruitment_performance_report_worker.rb
  config/clock.rb
  spec/lib/dfe/bigquery/application_metrics_by_provider_spec.rb
  spec/models/application_choice_spec.rb
  spec/models/publications/national_recruitment_performance_report_generator_spec.rb
  spec/models/publications/provider_recruitment_performance_report_generator_spec.rb
  spec/models/publications/recruitment_performance_report_scheduler_spec.rb
  spec/queries/providers_for_recruitment_performance_report_query_spec.rb
  spec/support_specs/clockwork_spec.rb
  spec/workers/publications/national_recruitment_performance_report_worker_spec.rb
  spec/workers/publications/provider_recruitment_performance_report_worker_spec.rb
Labels: deploy_v2

#9339 HESA reports shouldn't error when no degrees on applications
  app/decorators/degree_export_decorator.rb
  app/services/provider_interface/hesa_data_export.rb
  spec/decorators/degree_export_decorator_spec.rb
  spec/services/provider_interface/hesa_data_export_spec.rb
  spec/system/provider_interface/export_applications_in_hesa_format_spec.rb
Labels: deploy_v2

#9361 [1712] Maintenance page - Cleanup
  maintenance_page/manifests/review_aks/ingress_external_to_main.yml
  maintenance_page/manifests/review_aks/ingress_external_to_maintenance.yml
  maintenance_page/manifests/review_aks/ingress_internal_to_main.yml
  maintenance_page/manifests/review_aks/ingress_internal_to_maintenance.yml
  maintenance_page/manifests/review_aks/ingress_maintenance.yml
  maintenance_page/manifests/review_aks/ingress_temp_to_main.yml
  terraform/aks/workspace_variables/production_aks_Terrafile
  terraform/aks/workspace_variables/qa_aks_Terrafile
  terraform/aks/workspace_variables/review_aks_Terrafile
  terraform/aks/workspace_variables/sandbox_aks_Terrafile
  terraform/aks/workspace_variables/staging_aks_Terrafile
Labels: DevOps

#9359 Update Providers Reports index
  app/controllers/provider_interface/reports_controller.rb
  app/models/provider.rb
  app/models/publications/provider_recruitment_performance_report.rb
  app/services/cycle_timetable.rb
  app/views/provider_interface/reports/index.html.erb
  config/locales/provider_interface/reports.yml
  spec/models/publications/provider_recruitment_performance_report_spec.rb
  spec/services/cycle_timetable_spec.rb
  spec/system/provider_interface/provider_reports_page_spec.rb
  spec/system/provider_interface/reports/index_provider_user_one_provider_spec.rb
  spec/system/provider_interface/reports/index_provider_user_two_providers_spec.rb
  spec/system/provider_interface/reports/index_provider_user_two_providers_with_performance_report_spec.rb
Labels: deploy_v2

#9372 [1669] Update production database URL
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: DevOps

#9373 [1669] Remove database rename feature flag
  terraform/aks/application.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/review_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
Labels: DevOps, deploy_v2

#9369 [1823] Fix maintenance workflows
  .github/workflows/disable-maintenance.yml
  .github/workflows/enable-maintenance.yml
Labels: DevOps

#9386 Run Mailer Previews monkey patch after full initialization
  config/initializers/mailer_previews.rb
Labels: deploy_v2

#9365 [1670] table style changes for recruitment report
  app/components/provider_interface/recruitment_performance_report/deferrals_table_component.html.erb
  app/components/provider_interface/recruitment_performance_report/proportion_with_inactive_applications_table_component.html.erb
  app/components/provider_interface/recruitment_performance_report/subject_table_component.html.erb
  app/frontend/styles/provider/_recruitment_performance_report.scss
Labels: deploy_v2

#9396 [1717] Report data to seeds
  lib/tasks/local_dev.rake
Labels: deploy_v2

#9410 Fix for mailer previews
  config/initializers/mailer_previews.rb
Labels: deploy_v2
