Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2024-02, with the labels that each got.

#9049 Introduce Provider#phone_number and #email_address
  app/services/teacher_training_public_api/sync_provider.rb
  app/views/support_interface/providers/show.html.erb
  spec/examples/teacher_training_api/provider_list_response.json
  spec/examples/teacher_training_api/single_provider_response.json
  spec/factories/provider.rb
Labels: deploy_v2

#9062 [1203] Update content on the blocked submission page
  app/controllers/candidate_interface/continuous_applications/course_choices/blocked_submissions_controller.rb
  app/views/candidate_interface/continuous_applications/course_choices/blocked_submissions/show.html.erb
  config/locales/en.yml
  spec/system/candidate_interface/submitting/candidate_submits_a_duplicate_application_spec.rb
Labels: deploy_v2

#9063 ApplicationChoice updates: What happens next
  app/components/candidate_interface/continuous_applications/application_review_component.html.erb
  app/components/candidate_interface/continuous_applications/application_review_component.rb
  config/locales/en.yml
  spec/components/candidate_interface/continuous_applications/application_review_component_spec.rb
Labels: deploy_v2

#9074 concurrency added for DB backup jobs to avoid mutiple run's
  .github/workflows/database-backup-aks.yml
Labels: DevOps

#9077 Fix 5.1.1 version for DfE sign in API works
  Gemfile
  Gemfile.lock
Labels: deploy_v2

#9083 Add CandidateInterface::ApplicationChoiceItemComponent
  app/components/candidate_interface/application_choice_item_component.html.erb
  app/components/candidate_interface/application_choice_item_component.rb
  app/frontend/styles/_application-item.scss
  app/frontend/styles/application.scss
  spec/components/candidate_interface/application_choice_item_component_spec.rb
  spec/components/previews/candidate_interface/application_choice_item_component_preview.rb
Labels: deploy_v2

#9064 Add Contact training provider to ApplicationReviewComponent
  app/components/candidate_interface/continuous_applications/application_review_component.html.erb
  app/components/candidate_interface/continuous_applications/application_review_component.rb
  app/components/candidate_interface/provider_contact_information_component.html.erb
  app/components/candidate_interface/provider_contact_information_component.rb
  app/controllers/candidate_interface/offer_dashboard_controller.rb
  app/views/candidate_interface/offer_dashboard/_offer_deferred.html.erb
  app/views/candidate_interface/offer_dashboard/_pending_conditions.html.erb
  app/views/candidate_interface/offer_dashboard/_recruited.html.erb
  app/views/candidate_interface/offer_dashboard/_references_and_conditions.html.erb
  app/views/candidate_interface/offer_dashboard/show.html.erb
  spec/components/candidate_interface/continuous_applications/application_review_component_spec.rb
  spec/components/candidate_interface/provider_contact_information_component_spec.rb
  spec/components/previews/candidate_interface/provider_contact_information_component_preview.rb
  spec/system/candidate_interface/post_offer/offer_deferred_spec.rb
  spec/system/candidate_interface/post_offer/pending_conditions_spec.rb
  spec/system/candidate_interface/post_offer/post_offer_helper.rb
  spec/system/candidate_interface/post_offer/recruited_spec.rb
  spec/system/candidate_interface/references/candidate_views_their_references_on_the_post_offer_dashboard_continuous_applications_spec.rb
Labels: deploy_v2

#9088 Show sent provider at in manage report
  app/services/provider_interface/application_data_export.rb
  spec/services/provider_interface/application_data_export_spec.rb
Labels: deploy_v2

#9075 ApplicationChoiceSubmission Validation needs attention
  app/services/candidate_interface/continuous_applications/application_choice_submission.rb
  app/validators/incomplete_including_primary_course_details_validator.rb
  app/validators/incomplete_primary_course_details_validator.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/applications_closed_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/course_unavailable_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/immigration_status_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/incomplete_form_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/incomplete_including_primary_course_form_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission/incomplete_primary_course_form_spec.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/support/test_helpers/sign_in_helper.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_can_not_submit_with_incomplete_details_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_tries_to_submit_an_application_for_a_course_with_closed_application_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_tries_to_submit_an_application_for_course_unavailable_spec.rb
Labels: deploy_v2

#9096 Update continuous application check to use v23 notation
  app/controllers/candidate_interface/after_sign_in_controller.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/continuous_applications_controller.rb
  app/controllers/candidate_interface/decisions_controller.rb
  app/controllers/candidate_interface/section_controller.rb
  app/filters/already_carried_over_filter.rb
  app/filters/unsuccessful_carry_over_filter.rb
  app/models/application_choice.rb
  app/models/application_dates.rb
  app/models/application_form.rb
  app/views/layouts/_header.html.erb
  app/views/provider_interface/application_choices/show.html.erb
  spec/models/application_form_spec.rb
  spec/services/interview_workflow_constraints_spec.rb
Labels: deploy_v2

#9095 Redesign the application choices page - Add grouped tabs under "Your applications"
  app/components/candidate_interface/application_choice_item_component.html.erb
  app/components/candidate_interface/application_choice_item_component.rb
  app/components/candidate_interface/continuous_applications/application_choice_list_component.html.erb
  app/components/candidate_interface/continuous_applications/application_choice_list_component.rb
  app/components/candidate_interface/continuous_applications/application_review_component.html.erb
  app/components/candidate_interface/continuous_applications/application_review_component.rb
  app/components/candidate_interface/continuous_applications/application_status_tag_component.rb
  app/components/candidate_interface/continuous_applications/application_summary_component.html.erb
  app/components/candidate_interface/continuous_applications/application_summary_component.rb
  app/components/candidate_interface/continuous_applications/dashboard_component.html.erb
  app/components/candidate_interface/continuous_applications/dashboard_component.rb
  app/components/candidate_interface/tabs_component.html.erb
  app/components/candidate_interface/tabs_component.rb
  app/controllers/candidate_interface/continuous_applications_choices_controller.rb
  app/frontend/styles/_application-item.scss
  app/frontend/styles/application-candidate.scss
  app/frontend/styles/components/_tabs.scss
  app/services/candidate_interface/sort_application_choices.rb
  app/views/candidate_interface/continuous_applications_choices/index.html.erb
  config/locales/candidate_interface/application_choice_list.yml
  config/locales/candidate_interface/sort_application_choices.yml
  config/routes/candidate.rb
  spec/components/candidate_interface/continuous_applications/application_choice_list_component_spec.rb
  spec/components/candidate_interface/continuous_applications/application_review_component_spec.rb
  spec/components/candidate_interface/continuous_applications/application_summary_component_spec.rb
  spec/components/candidate_interface/continuous_applications/dashboard_component_spec.rb
  spec/components/candidate_interface/tabs_component_spec.rb
  spec/services/candidate_interface/sort_application_choices_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/application_choices_page/rejected_applications/reasons_for_rejection_spec.rb
  spec/system/candidate_interface/application_choices_page/rejected_applications/rejection_reason_spec.rb
  spec/system/candidate_interface/application_choices_page/rejected_applications/rejection_reasons_spec.rb
  spec/system/candidate_interface/candidate_viewing_booked_interviews_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_deletes_application_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_edits_course_choices_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_duplicate_course_when_editing_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_has_an_application_become_inactive_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_submitting_application_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_tries_to_submit_after_exceeding_the_maximum_amount_of_unsuccessful_choices_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_tries_to_submit_an_application_for_course_unavailable_spec.rb
  spec/system/candidate_interface/continuous_applications/viewing-application-choices/candidate_sees_all_their_applications_spec.rb
  spec/system/candidate_interface/continuous_applications/withdraws/candidate_withdraws_spec.rb
  spec/system/candidate_interface/continuous_applications/withdraws/candidate_withdraws_with_upcoming_interviews_spec.rb
  spec/system/candidate_interface/entering_details/candidate_viewing_a_science_gcse_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_continuous_applications_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_declines_offer_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_and_prefills_application_in_sandbox_spec.rb
Labels: deploy_v2

#9117 [1609] Migrate to terraform modules #1 - Postgres
  .gitignore
  Makefile
  terraform/aks/.terraform.lock.hcl
  terraform/aks/cluster_data.tf
  terraform/aks/database.tf
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/dv_review_aks_Terrafile
  terraform/aks/workspace_variables/loadtest_aks_Terrafile
  terraform/aks/workspace_variables/production_aks_Terrafile
  terraform/aks/workspace_variables/pt_review_aks_Terrafile
  terraform/aks/workspace_variables/qa_aks_Terrafile
  terraform/aks/workspace_variables/review_aks_Terrafile
  terraform/aks/workspace_variables/sandbox_aks_Terrafile
  terraform/aks/workspace_variables/staging_aks_Terrafile
  terraform/modules/kubernetes/aks_postgres.tf
  terraform/modules/kubernetes/azure_postgres.tf
  terraform/modules/kubernetes/monitoring.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps

#9122 Migrate application_status onto Course model
  config/analytics.yml
  db/migrate/20240221154303_add_application_status_column_to_course.rb
  db/schema.rb
  docs/domain-model.png
Labels: deploy_v2

#9128 [1609] Migrate redis to terraform module
  terraform/aks/redis.tf
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
  terraform/modules/kubernetes/aks_redis.tf
  terraform/modules/kubernetes/azure_redis.tf
  terraform/modules/kubernetes/data.tf
  terraform/modules/kubernetes/monitoring.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps, DO NOT MERGE

#9092 [1238] Bump govuk frontend to 5.0
  Gemfile
  Gemfile.lock
  app/components/candidate_interface/accept_offer_add_new_reference_component.html.erb
  app/components/candidate_interface/accept_offer_add_new_reference_component.rb
  app/components/candidate_interface/add_new_reference_component.html.erb
  app/components/candidate_interface/continuous_applications/application_review_component.rb
  app/components/shared/add_new_reference_helpers.rb
  app/frontend/packs/application-api-docs.js
  app/frontend/packs/application-candidate.js
  app/frontend/packs/application-provider.js
  app/frontend/packs/application-publications.js
  app/frontend/packs/application-support.js
  app/frontend/packs/application.js
  app/frontend/styles/_application-card.scss
  app/frontend/styles/application.scss
  app/helpers/utm_link_helper.rb
  app/helpers/view_helper.rb
  app/services/candidate_interface/continuous_applications/application_choice_submission.rb
  app/validators/course_unavailable_validator.rb
  app/validators/immigration_status_validator.rb
  app/validators/incomplete_details_validator.rb
  app/validators/incomplete_primary_course_details_validator.rb
  app/views/layouts/base.html.erb
  app/views/layouts/error.html.erb
  babel.config.js
  config/initializers/assets.rb
  config/webpacker.yml
  package.json
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
  spec/system/candidate_interface/entering_details/degrees/candidate_adding_unknown_degrees_spec.rb
  yarn.lock
Labels: deploy_v2

#9111 Show more show less on long personal statements when viewing the application
  app/components/candidate_interface/continuous_applications/application_review_component.rb
  app/components/candidate_interface/continuous_applications/personal_statement_summary_component.html.erb
  app/components/candidate_interface/continuous_applications/personal_statement_summary_component.rb
  app/frontend/packs/application-candidate.js
  app/frontend/packs/components/show-more-show-less.js
  app/frontend/styles/application-candidate.scss
  app/frontend/styles/components/_show_more_show_less.scss
  spec/components/candidate_interface/continuous_applications/application_review_component_spec.rb
  spec/components/candidate_interface/continuous_applications/personal_statement_summary_component_spec.rb
  spec/system/candidate_interface/continuous_applications/viewing-application-choices/candidate_views_personal_statement_js_disabled_spec.rb
  spec/system/candidate_interface/continuous_applications/viewing-application-choices/candidate_views_personal_statement_spec.rb
Labels: JavaScript, Accessibility, deploy_v2

#9142 Remove max-width property from status tags
  app/frontend/styles/_tag.scss
Labels: deploy_v2

#9136 Increase postgres prod alert window to 15m
  terraform/aks/database.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: DevOps

#9141 Fix issue Provider can't make offers if candidate has other applications with conditions_not_met
  app/services/offer_validations.rb
  spec/services/offer_validations_spec.rb
Labels: deploy_v2

#9153 [1357] Apply fee visibility
  app/components/candidate_interface/continuous_applications/application_review_component.rb
  app/components/candidate_interface/continuous_applications/course_fee_row_helper.rb
  app/components/candidate_interface/continuous_applications/course_review_component.rb
  config/locales/components/course_fee_row_helper.yml
  config/locales/en.yml
  spec/components/candidate_interface/continuous_applications/application_review_component_spec.rb
  spec/components/candidate_interface/continuous_applications/course_review_component_spec.rb
Labels: deploy_v2

#9151 [1609] Migrate code to application terraform module
  .tool-versions
  Makefile
  bin/restore-nightly-backup
  docs/disaster-recovery.md
  docs/environment-variables.md
  docs/maintenance-mode.md
  docs/manual-deployment.md
  docs/support_playbook.md
  terraform/aks/.terraform.lock.hcl
  terraform/aks/application.tf
  terraform/aks/data.tf
  terraform/aks/outputs.tf
  terraform/aks/provider.tf
  terraform/aks/terraform.tf
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/dv_review_aks.tfvars.json
  terraform/aks/workspace_variables/loadtest_aks.tfvars.json
  terraform/aks/workspace_variables/production_aks.tfvars.json
  terraform/aks/workspace_variables/pt_review_aks.tfvars.json
  terraform/aks/workspace_variables/qa_aks.tfvars.json
  terraform/aks/workspace_variables/review_aks.tfvars.json
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
  terraform/aks/workspace_variables/staging_aks.tfvars.json
  terraform/modules/kubernetes/availability.tf
  terraform/modules/kubernetes/main.tf
  terraform/modules/kubernetes/outputs.tf
  terraform/modules/kubernetes/variables.tf
Labels: DevOps, deploy_v2

#9157 [1609] Fix database URL
  Makefile
  terraform/aks/application.tf
  terraform/aks/variables.tf
Labels: DevOps
