Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2024-11, with the labels that each got.

#9979 [343] steps toward updating notifications ruby client dependancy
  app/mailers/application_mailer.rb
  lib/email_log_interceptor.rb
  lib/sandbox_interceptor.rb
  spec/lib/email_log_interceptor_spec.rb
  spec/lib/sandbox_interceptor_spec.rb
  spec/services/cancel_interview_spec.rb
  spec/services/create_interview_spec.rb
  spec/services/decline_offer_spec.rb
  spec/services/provider_interface/save_condition_statuses_spec.rb
  spec/services/send_new_application_email_to_provider_spec.rb
  spec/services/update_interview_spec.rb
  spec/services/withdraw_application_spec.rb
  spec/workers/send_apply_to_another_course_when_inactive_email_to_candidates_batch_worker_spec.rb
  spec/workers/send_apply_to_another_course_when_inactive_email_to_candidates_worker_spec.rb
  spec/workers/send_apply_to_multiple_courses_when_inactive_email_to_candidates_batch_worker_spec.rb
  spec/workers/send_apply_to_multiple_courses_when_inactive_email_to_candidates_worker_spec.rb
Labels: deploy_v2

#10017 [372] Remove feedback for RBD section
  app/helpers/task_view_helper.rb
  app/services/provider_interface/sort_application_choices.rb
  spec/services/provider_interface/sort_application_choices_spec.rb
Labels: deploy_v2

#10022 Add rescue step to degree form
  app/forms/candidate_interface/degree_wizard.rb
  spec/forms/candidate_interface/degree_wizard_spec.rb
Labels: deploy_v2

#10014 Bundler dependabots update
  Gemfile.lock
Labels: deploy_v2

#10015 Javascript dependabots update
  package.json
  yarn.lock
Labels: deploy_v2

#10013 Add DR workflows for db backup and restore
  .github/workflows/backup-db.yml
  .github/workflows/database-backup-aks.yml
  .github/workflows/postgres-ptr.yml
  .github/workflows/postgres-restore.yml
Labels: DevOps

#10021 [370] implement a flight check for personal email addresses used for referees
  app/components/candidate_interface/application_review_and_submit_component.rb
  app/controllers/candidate_interface/course_choices/review_references_interruption_controller.rb
  app/controllers/candidate_interface/references/accept_offer/email_address_controller.rb
  app/controllers/candidate_interface/references/accept_offer/references_interruptions_controller.rb
  app/controllers/candidate_interface/references/base_controller.rb
  app/controllers/candidate_interface/references/email_address_controller.rb
  app/controllers/candidate_interface/references/interruptions_controller.rb
  app/controllers/candidate_interface/references/request_reference/email_address_controller.rb
  app/controllers/candidate_interface/references/request_reference/references_interruptions_controller.rb
  app/forms/candidate_interface/reference/referee_email_address_form.rb
  app/models/application_form.rb
  app/services/email_checker.rb
  app/views/candidate_interface/course_choices/review_references_interruption/show.html.erb
  app/views/candidate_interface/references/interruptions/show.html.erb
  config/initializers/personal_email_address_domains.rb
  config/locales/candidate_interface/interruption.yml
  config/locales/candidate_interface/references.yml
  config/locales/candidate_interface/references_interruption.yml
  config/locales/en.yml
  config/routes/candidate.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_from_previous_cycle_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_updates_referee_email_addresses_when_accepting_offer_spec.rb
  spec/system/candidate_interface/references/candidate_adds_reference_with_personal_email_address_post_offer_spec.rb
  spec/system/candidate_interface/references/candidate_adds_reference_with_personal_email_address_spec.rb
  spec/system/candidate_interface/references/candidate_edits_reference_email_address_spec.rb
  spec/system/candidate_interface/references/candidate_request_references_spec.rb
  spec/system/candidate_interface/submitting/candidate_is_interrupted_because_references_have_personal_email_addresses_spec.rb
Labels: deploy_v2

#10002 Added migration to delete all Audits before 4 October 2022
  app/services/data_migrations/delete_all_old_audits.rb
  app/workers/delete_all_old_audits_in_batches.rb
  lib/tasks/data.rake
  spec/factories/audit.rb
  spec/services/data_migrations/delete_all_old_audits_spec.rb
  spec/workers/delete_all_old_audits_in_batches_spec.rb
Labels: DO NOT MERGE

#10028 DR workflow fixes
  .github/workflows/backup-db.yml
  .github/workflows/postgres-ptr.yml
  .github/workflows/postgres-restore.yml
Labels: DevOps

#9839 Delete unwanted audits
  app/services/data_migrations/delete_work_history_audits.rb
  app/workers/delete_audits_worker.rb
  lib/tasks/data.rake
  spec/factories/audit.rb
  spec/services/data_migrations/delete_work_history_audits_spec.rb
  spec/workers/delete_audits_worker_spec.rb
Labels: DO NOT MERGE

#10040 [412] Fix rejection email formatting
  app/views/candidate_mailer/tailored_rejection_advice/_personal_statement_tailored_advice.text.erb
  app/views/candidate_mailer/tailored_rejection_advice/_qualifications_tailored_advice.text.erb
  spec/mailers/previews/candidate_mailer_preview.rb
Labels: deploy_v2

#10042 [349] Make cycle dates dynamic in performance report page
  app/views/provider_interface/reports/recruitment_performance_reports/_about_this_data_section.html.erb
  app/views/provider_interface/reports/recruitment_performance_reports/_report_description.html.erb
  app/views/provider_interface/reports/recruitment_performance_reports/show.html.erb
  config/locales/provider_interface/recruitment_performance_reports.yml
  spec/system/provider_interface/reports/view_provider_recruitment_performance_report_spec.rb
Labels: deploy_v2

#10052 Dependabots updates
  Gemfile
  Gemfile.lock
Labels: deploy_v2

#10053 Add logit logs for slow provider Activity page request
  app/controllers/provider_interface/activity_log_controller.rb
Labels: deploy_v2

#10062 Bundler dependabots
  Gemfile
  Gemfile.lock
Labels: deploy_v2

#10055 Improve activity page monitoring
  app/controllers/provider_interface/activity_log_controller.rb
Labels: deploy_v2

#10063 [140] Add unsubscribe message to relevant emails
  app/mailers/candidate_mailer.rb
  app/queries/offers_to_chase_query.rb
  app/views/candidate_mailer/_get_help_teacher_training_adviser.text.erb
  app/views/candidate_mailer/_unsubscribe_from_emails_like_this.text.erb
  app/views/candidate_mailer/application_choice_submitted.text.erb
  app/views/candidate_mailer/apply_to_another_course_after_30_working_days.text.erb
  app/views/candidate_mailer/apply_to_multiple_courses_after_30_working_days.text.erb
  app/views/candidate_mailer/change_course.text.erb
  app/views/candidate_mailer/changed_offer.text.erb
  app/views/candidate_mailer/chase_reference.text.erb
  app/views/candidate_mailer/chase_reference_again.text.erb
  app/views/candidate_mailer/conditions_met.text.erb
  app/views/candidate_mailer/conditions_not_met.text.erb
  app/views/candidate_mailer/conditions_statuses_changed.text.erb
  app/views/candidate_mailer/decline_last_application_choice.text.erb
  app/views/candidate_mailer/deferred_offer.text.erb
  app/views/candidate_mailer/deferred_offer_reminder.text.erb
  app/views/candidate_mailer/eoc_first_deadline_reminder.text.erb
  app/views/candidate_mailer/eoc_second_deadline_reminder.text.erb
  app/views/candidate_mailer/feedback_received_for_application_rejected_by_default.text.erb
  app/views/candidate_mailer/find_has_opened.text.erb
  app/views/candidate_mailer/interview_cancelled.text.erb
  app/views/candidate_mailer/interview_updated.text.erb
  app/views/candidate_mailer/new_cycle_has_started.text.erb
  app/views/candidate_mailer/new_interview.text.erb
  app/views/candidate_mailer/new_offer_made.text.erb
  app/views/candidate_mailer/new_referee_request.text.erb
  app/views/candidate_mailer/nudge_unsubmitted.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_courses.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_personal_statement.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_references/no_references.text.erb
  app/views/candidate_mailer/offer_10_day.text.erb
  app/views/candidate_mailer/offer_20_day.text.erb
  app/views/candidate_mailer/offer_30_day.text.erb
  app/views/candidate_mailer/offer_40_day.text.erb
  app/views/candidate_mailer/offer_50_day.text.erb
  app/views/candidate_mailer/offer_accepted.text.erb
  app/views/candidate_mailer/offer_withdrawn.text.erb
  app/views/candidate_mailer/reference_received.text.erb
  app/views/candidate_mailer/reinstated_offer.text.erb
  app/views/candidate_mailer/unconditional_offer_accepted.text.erb
  app/views/candidate_mailer/withdraw_last_application_choice.text.erb
  spec/mailers/candidate_mailer/candidate_mailer_eoc_first_deadline_reminder_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_eoc_second_deadline_reminder_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_find_has_opened_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_new_cycle_has_started_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_nudge_unsubmitted_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_nudge_unsubmitted_with_incomplete_courses_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_nudge_unsubmitted_with_incomplete_references_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_offer_x_day_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/queries/offers_to_chase_query_spec.rb
  spec/support/shared_examples/mailers.rb
Labels: deploy_v2

#10068 [403] Add realistic job preview text to relevant emails
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/_gain_insights_into_life_as_a_teacher.text.erb
  app/views/candidate_mailer/_understand_your_professional_strengths.text.erb
  app/views/candidate_mailer/application_rejected.text.erb
  app/views/candidate_mailer/apply_to_another_course_after_30_working_days.text.erb
  app/views/candidate_mailer/apply_to_multiple_courses_after_30_working_days.text.erb
  app/views/candidate_mailer/eoc_first_deadline_reminder.text.erb
  app/views/candidate_mailer/eoc_second_deadline_reminder.text.erb
  app/views/candidate_mailer/find_has_opened.text.erb
  app/views/candidate_mailer/nudge_unsubmitted.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_courses.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_personal_statement.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_references.text.erb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/candidate_mailer/candidate_mailer_application_rejected_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_apply_to_another_course_after_30_working_days_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_apply_to_multiple_courses_after_30_working_days_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_eoc_first_deadline_reminder_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_eoc_second_deadline_reminder_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_find_has_opened_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_nudge_unsubmitted_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_nudge_unsubmitted_with_incomplete_courses_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_nudge_unsubmitted_with_incomplete_references_spec.rb
  spec/workers/nudge_candidates_worker_spec.rb
Labels: deploy_v2

#10069 [339] update rejection emails to include advice for new reasons
  app/presenters/rejection_reasons/rejection_reasons_presenter.rb
  app/views/candidate_mailer/_application_rejected_get_help.text.erb
  app/views/candidate_mailer/tailored_rejection_advice/_already_qualified_tailored_advice.text.erb
  app/views/candidate_mailer/tailored_rejection_advice/_english_below_standard_tailored_advice.text.erb
  app/views/candidate_mailer/tailored_rejection_advice/_placements_other_tailored_advice.text.erb
  app/views/candidate_mailer/tailored_rejection_advice/_school_placement_tailored_advice.text.erb
  app/views/candidate_mailer/tailored_rejection_advice/_unsuitable_degree_subject_tailored_advice.text.erb
  config/locales/en.yml
  spec/mailers/candidate_mailer/candidate_mailer_application_rejected_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/presenters/rejection_reasons/rejection_reasons_presenter_spec.rb
Labels: deploy_v2

#10072 [422] Bug error handling when selecting a provider
  app/forms/candidate_interface/course_choices/provider_selection_step.rb
  app/views/candidate_interface/course_choices/provider_selection/new.html.erb
Labels: deploy_v2

#10075 Change the closed course message
  config/locales/en.yml
  spec/system/candidate_interface/course_selection/candidate_selecting_a_course_that_is_closed_spec.rb
Labels: deploy_v2

#10054 Rails 8 upgrade
  Gemfile
  Gemfile.lock
  app/forms/concerns/wizard.rb
  app/forms/provider_interface/course_wizard.rb
  app/forms/provider_interface/interview_wizard.rb
  app/forms/provider_interface/offer_wizard.rb
  app/forms/provider_interface/reconfirm_deferred_offer_wizard.rb
  app/forms/shared/job_form.rb
  app/forms/shared/volunteering_role_form.rb
  app/views/candidate_interface/decisions/decline_offer.html.erb
  app/views/support_interface/tasks/confirm_cancel_applications_at_end_of_cycle.html.erb
  app/views/support_interface/tasks/confirm_delete_test_applications.html.erb
  bin/dev
  bin/rubocop
  config/application.rb
  config/candidate_api/v1.1.yml
  config/candidate_api/v1.2.yml
  config/candidate_api/v1.3.yml
  config/data-api.yml
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/puma.rb
  config/register-api.yml
  config/vendor_api/v1.0.yml
  spec/forms/candidate_interface/restructured_work_history/job_form_spec.rb
  spec/forms/candidate_interface/volunteering_role_form_spec.rb
  spec/rails_helper.rb
  spec/requests/register_api/get_multiple_applications_spec.rb
  spec/requests/vendor_api/v1.0/get_multiple_applications_spec.rb
  spec/requests/vendor_api/v1.1/create_notes_spec.rb
  spec/requests/vendor_api/v1.1/post_cancel_interview_spec.rb
  spec/requests/vendor_api/v1.1/post_confirm_deferred_offer_spec.rb
  spec/requests/vendor_api/v1.1/post_create_interview_spec.rb
  spec/requests/vendor_api/v1.1/post_update_interview_spec.rb
  spec/support/shared_examples/a_candidate_api_endpoint.rb
  spec/support/shared_examples/an_api_endpoint_requiring_a_date_param.rb
Labels: deploy_v2

#10081 [171] Migration to add `is_confidential` column to `Reference` table
  config/analytics.yml
  db/migrate/20241121144711_add_confidential_to_references.rb
  db/schema.rb
  docs/domain-model.png
Labels: deploy_v2

#10080 [440] Part 1 Remove full sync error
  app/services/concerns/full_sync_error_handler.rb
  app/services/teacher_training_public_api/full_sync_update_error.rb
  app/services/teacher_training_public_api/sync_all_providers_and_courses.rb
  app/services/teacher_training_public_api/sync_courses.rb
  app/services/teacher_training_public_api/sync_provider.rb
  app/services/teacher_training_public_api/sync_sites.rb
  app/workers/teacher_training_public_api/sync_all_providers_and_courses_worker.rb
  spec/services/teacher_training_public_api/sync_all_providers_and_courses_spec.rb
  spec/services/teacher_training_public_api/sync_provider_spec.rb
  spec/services/teacher_training_public_api/sync_sites_spec.rb
  spec/workers/teacher_training_public_api/sync_all_providers_and_courses_worker_spec.rb
Labels: deploy_v2

#10090 Fixes for Monthly Statistics
  app/presenters/publications/v2/monthly_statistics_presenter.rb
  app/views/publications/monthly_statistics/v2/show.html.erb
  spec/presenters/publications/v2/monthly_statistics_presenter_spec.rb
Labels: deploy_v2

#10106 [431] update content in nudge emails to improve submission rates
  app/views/candidate_mailer/_gain_insights_into_life_as_a_teacher.text.erb
  app/views/candidate_mailer/_understand_your_professional_strengths.text.erb
  app/views/candidate_mailer/nudge_unsubmitted.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_courses.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_personal_statement.text.erb
  app/views/candidate_mailer/nudge_unsubmitted_with_incomplete_references.text.erb
  config/locales/en.yml
  spec/mailers/candidate_mailer/candidate_mailer_nudge_unsubmitted_with_incomplete_personal_statement_spec.rb
Labels: deploy_v2

#10103 Scaffold for Course Recommendation link
  app/components/support_interface/application_choice_component.rb
  app/models/application_form.rb
  app/models/candidate.rb
  app/services/candidate_courses_recommender.rb
  app/views/support_interface/application_forms/show.html.erb
  spec/components/support_interface/application_choice_component_spec.rb
  spec/models/application_form_spec.rb
  spec/models/candidate_spec.rb
  spec/services/candidate_courses_recommender_spec.rb
Labels: deploy_v2

#10116 Fix Makefile target conflict
  Makefile
Labels: deploy_v2

#10120 Bug Fix: clicking on option divs always selected first option when e
  app/views/candidate_interface/decisions/withdrawal_feedback.html.erb
  app/views/candidate_interface/degrees/degree/new_enic.html.erb
  app/views/candidate_interface/gcse/enic/_form.html.erb
  app/views/provider_interface/application_data_export/new.html.erb
  app/views/provider_interface/rejections/new.html.erb
  app/views/support_interface/english_gcse_forms/_english_gcse_form.html.erb
  app/views/support_interface/math_gcse_forms/_math_gcse_form.html.erb
  app/views/support_interface/science_gcse_forms/_science_gcse_form.html.erb
  config/locales/provider_interface/rejections.yml
  spec/models/rejection_reasons_spec.rb
Labels: deploy_v2

#10126 Remove check service principal job
  .github/workflows/check_sp.yml
Labels: DevOps
