Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2024-04, with the labels that each got.

#9230 Remove references to international relocation payment information
  app/mailers/provider_mailer.rb
  app/services/is_eligible_for_international_relocation_payment.rb
  app/views/provider_mailer/application_submitted.text.erb
  app/views/provider_mailer/application_submitted_with_safeguarding_issues.text.erb
  spec/mailers/provider_mailer_spec.rb
  spec/services/is_eligible_for_international_relocation_payment_spec.rb
Labels: deploy_v2

#9253 Update our logging format output
  Gemfile
  config/environments/production.rb
  config/initializers/semantic_logger.rb
Labels: deploy_v2

#9260 Fix for the wrong clearance of the semantic logger
  .env.example
  config/initializers/semantic_logger.rb
Labels: deploy_v2

#9267 Add Redis probe to Skylight
  config/application.rb
Labels: deploy_v2

#9239 1487 reflect the ske policy changes in our services
  app/components/provider_interface/ske_conditions_component.rb
  app/forms/provider_interface/offer_wizard.rb
  app/forms/support_interface/conditions_form.rb
  app/models/ske_condition.rb
  app/models/subject.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
  spec/forms/support_interface/conditions_form_spec.rb
  spec/models/ske_condition_spec.rb
  spec/system/provider_interface/change_existing_offer_ske_standard_flow_spec.rb
  spec/system/provider_interface/make_offer_ske_standard_flow_spec.rb
  spec/system/support_interface/change_offer_ske_conditions_spec.rb
Labels: DO NOT MERGE, deploy_v2

#9272 Drop open_on_apply and opened_on_apply_at from courses table
  app/models/course.rb
  db/migrate/20240409134457_drop_open_on_apply_columns_from_course.rb
  db/schema.rb
  docs/domain-model.png
Labels: deploy_v2

#9280 Update API documentation to reflect continuous applications
  app/components/shared/state_explanation_component.html.erb
  app/views/api_docs/vendor_api_docs/reference/reference.html.erb
Labels: deploy_v2

#9284 Don't reset the course option id when store course is blank
  app/forms/provider_interface/offer_wizard.rb
  spec/forms/provider_interface/offer_wizard_spec.rb
Labels: deploy_v2

#9290 Handle gracefully when client disconnects during streaming
  app/controllers/concerns/streamable_data_export.rb
  spec/system/provider_interface/provider_user_exports_applications_to_csv_spec.rb
Labels: deploy_v2

#9271 Replace 'PGCE with QTS' with 'QTS with PGCE'
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/offer_review_component.rb
  app/components/support_interface/course_details_component.rb
  app/forms/candidate_interface/pick_course_form.rb
  app/helpers/qualification_value_helper.rb
  app/models/course.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
  spec/components/provider_interface/completed_offer_summary_component_spec.rb
  spec/components/provider_interface/course_details_component_spec.rb
  spec/components/provider_interface/course_summary_component_spec.rb
  spec/components/provider_interface/offer_summary_component_spec.rb
  spec/components/provider_interface/read_only_completed_offer_summary_component_spec.rb
  spec/forms/candidate_interface/pick_course_form_spec.rb
  spec/helpers/qualification_value_helper_spec.rb
  spec/models/course_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_changes_course_and_reaches_limit_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_reaching_reapplication_limit_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_reapplying_to_a_course_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_that_is_full_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_duplicate_course_spec.rb
Labels: deploy_v2

#9273 [1472] Update visa immigration options for EEA candidates
  app/components/support_interface/personal_information_component.rb
  app/forms/candidate_interface/immigration_status_form.rb
  app/forms/support_interface/application_forms/immigration_status_form.rb
  app/presenters/candidate_interface/personal_details_review_presenter.rb
  app/views/candidate_interface/personal_details/immigration_status/_shared_form.html.erb
  app/views/candidate_interface/personal_details/immigration_status/edit.html.erb
  app/views/candidate_interface/personal_details/immigration_status/new.html.erb
  app/views/support_interface/application_forms/immigration_status/edit.html.erb
  config/locales/candidate_interface/personal_details.yml
  config/locales/support_interface/support_interface.yml
  spec/components/support_interface/personal_information_component_spec.rb
  spec/presenters/candidate_interface/personal_details_review_presenter_spec.rb
  spec/system/candidate_interface/entering_details/candidate_choosing_visa_or_immigration_status_non_eu_spec.rb
  spec/system/candidate_interface/entering_details/candidate_entering_personal_details_when_requiring_visa_2022_spec.rb
  spec/system/support_interface/editing_visa_or_immigration_status_eu_spec.rb
  spec/system/support_interface/editing_visa_or_immigration_status_non_eu_spec.rb
  spec/system/support_interface/immigration_status_spec.rb
Labels: deploy_v2

#9293 [1530] Update enic guidance
  app/views/candidate_interface/degrees/degree/new_enic.html.erb
  app/views/candidate_interface/gcse/enic/_form.html.erb
  config/locales/en.yml
Labels: deploy_v2

#9294 [1654] Add infra team statuscake contact group
  terraform/aks/workspace_variables/production_aks.tfvars.json
Labels: DevOps

#9296 Allow candidates to submit when they have free slot & conditions not met
  app/services/application_state_change.rb
  spec/services/candidate_interface/continuous_applications/application_choice_submission_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_tries_to_submit_after_exceeding_the_maximum_amount_of_choices_spec.rb
Labels: deploy_v2

#9295 Added Realistic Job Preview Links to emails with tracking
  adr/0022-realistic-job-preview-link-tracking.md
  app/mailers/candidate_mailer.rb
  app/models/candidate.rb
  app/views/candidate_mailer/_still_interested_content.text.erb
  app/views/candidate_mailer/application_rejected.text.erb
  app/views/candidate_mailer/application_withdrawn_on_request.text.erb
  app/views/candidate_mailer/declined_by_default.text.erb
  config/routes.rb
  spec/mailers/candidate_mailer_spec.rb
  spec/models/candidate_spec.rb
Labels: deploy_v2

#9286 Prevent candidate applying to closed course
  app/components/candidate_interface/continuous_applications/application_review_and_submit_component.html.erb
  app/controllers/candidate_interface/continuous_applications/course_choices/closed_course_selection_controller.rb
  app/forms/candidate_interface/continuous_applications/closed_course_selection_step.rb
  app/forms/candidate_interface/continuous_applications/course_review_step.rb
  app/forms/candidate_interface/continuous_applications/course_selection_wizard.rb
  app/forms/candidate_interface/continuous_applications/which_course_are_you_applying_to_step.rb
  app/validators/candidate_interface/continuous_applications/course_selection_validator.rb
  app/validators/course_unavailable_validator.rb
  app/views/candidate_interface/continuous_applications/course_choices/closed_course_selection/new.html.erb
  config/locales/candidate_interface/submit_application.yml
  config/locales/en.yml
  config/routes/candidate.rb
  spec/forms/candidate_interface/continuous_applications/which_course_are_you_applying_to_step_spec.rb
  spec/services/candidate_interface/continuous_applications/course_selection_store_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_spec.rb
  spec/system/candidate_interface/continuous_applications/course_selection/candidate_selecting_a_course_that_is_closed_spec.rb
  spec/system/candidate_interface/continuous_applications/submitting/candidate_tries_to_submit_an_application_for_course_unavailable_spec.rb
  spec/system/candidate_interface/submitting/candidate_reviews_completed_application_and_updates_personal_details_section_spec.rb
Labels: deploy_v2

#9297 [1669] Rename database for review apps
  terraform/aks/.terraform.lock.hcl
  terraform/aks/variables.tf
  terraform/aks/workspace_variables/review_aks.tfvars.json
Labels: DevOps, deploy_v2

#9322 Recruitment performance report bigquery
  app/lib/dfe/bigquery.rb
  app/lib/dfe/bigquery/application_metrics.rb
  app/lib/dfe/bigquery/application_metrics_by_provider.rb
  app/lib/dfe/bigquery/relation.rb
  app/lib/dfe/bigquery/table.rb
  app/models/publications/itt_monthly_report_generator.rb
  app/models/publications/monthly_statistics/report_sections.rb
  spec/lib/dfe/bigquery/application_metrics_by_provider_spec.rb
  spec/lib/dfe/bigquery/application_metrics_spec.rb
  spec/lib/dfe/bigquery/table_spec.rb
  spec/models/publications/itt_monthly_report_generator_spec.rb
Labels: deploy_v2

#9328 [9328] Rename database in Sandbox
  terraform/aks/workspace_variables/sandbox_aks.tfvars.json
Labels: DevOps
