Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2025-01, with the labels that each got.

#10193 Redirect to sign_in page for magic link pages if one-login enabled
  app/controllers/candidate_interface/sign_in_controller.rb
  app/controllers/candidate_interface/sign_up_controller.rb
Labels: deploy_v2

#10194 Don't send request to one login when signing out after impersonation
  app/controllers/one_login_controller.rb
  spec/requests/one_login_controller_spec.rb
Labels: deploy_v2

#10210 [543] only warn on onsaved changes for large text fields
  app/frontend/packs/warn-on-unsaved-changes.js
Labels: deploy_v2

#10200 [541] remove unused application complete path
  app/components/candidate_interface/application_dashboard_component.html.erb
  app/components/candidate_interface/application_dashboard_component.rb
  app/controllers/candidate_interface/after_sign_in_controller.rb
  app/controllers/candidate_interface/candidate_interface_controller.rb
  app/controllers/candidate_interface/feedback_form_controller.rb
  app/controllers/candidate_interface/rejection_feedback_survey_controller.rb
  app/controllers/candidate_interface/submitted_application_form_controller.rb
  app/filters/unsuccessful_carry_over_filter.rb
  app/views/candidate_interface/decisions/offer.html.erb
  app/views/candidate_interface/submitted_application_form/complete.html.erb
  config/routes/candidate.rb
  spec/components/candidate_interface/application_dashboard_component_spec.rb
  spec/requests/candidate_interface/cycle_redirects_spec.rb
  spec/requests/candidate_interface/request_references_spec.rb
  spec/support/test_helpers/candidate_helper.rb
  spec/system/candidate_interface/carry_over/candidate_can_submit_in_next_cycle_when_cycle_switched_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_different_application_states_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsubmitted_application_spec.rb
  spec/system/candidate_interface/carry_over/candidate_carries_over_unsuccessful_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_and_is_redirected_when_tries_to_access_some_pages_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_from_previous_cycle_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_accepts_offer_spec.rb
  spec/system/candidate_interface/offers_and_withdrawals/candidate_defers_offer_and_is_redirected_when_tries_to_access_some_pages_spec.rb
  spec/system/candidate_interface/post_offer/post_offer_helper.rb
  spec/system/candidate_interface/references/candidate_carries_over_unsuccessful_application_to_new_cycle_spec.rb
  spec/system/candidate_interface/references/candidate_request_references_spec.rb
  spec/system/candidate_interface/references/candidate_views_their_references_on_the_post_offer_dashboard_from_previous_cycle_spec.rb
  spec/system/candidate_interface/references/candidate_views_their_references_on_the_post_offer_dashboard_spec.rb
  spec/system/candidate_interface/submitting/candidate_is_redirected_away_from_complete_page_spec.rb
Labels: deploy_v2

#10201 426 Part 1 New withdrawal reasons, migrations and tables
  app/models/application_choice.rb
  app/models/withdrawal_reason.rb
  config/analytics.yml
  config/candidate_withdrawal_reasons.yml
  db/migrate/20241209145628_create_withdrawal_reasons.rb
  db/schema.rb
  docs/domain-model.png
  spec/models/application_choice_spec.rb
  spec/models/withdrawal_reason_spec.rb
Labels: deploy_v2

#10212 Add DB backed session tables
  app/models/candidate.rb
  app/models/session.rb
  app/models/session_error.rb
  config/analytics_blocklist.yml
  db/migrate/20250103094553_create_sessions.rb
  db/migrate/20250103094646_create_session_errors.rb
  db/schema.rb
  db/scripts/sanitise.sql
  docs/domain-model.png
  spec/models/candidate_spec.rb
  spec/models/session_error_spec.rb
  spec/models/session_spec.rb
Labels: deploy_v2

#10216 Ruby dependabots
  Gemfile.lock
Labels: deploy_v2

#10191 [426] candidate withdrawal reasons list refinement and mandatory
  app/components/candidate_interface/application_review_component.html.erb
  app/components/candidate_interface/application_review_component.rb
  app/components/candidate_interface/course_choices_review_component.html.erb
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/course_choices_summary_card_action_component.html.erb
  app/components/candidate_interface/course_choices_summary_card_action_component.rb
  app/components/candidate_interface/withdrawal_reasons/level_one_reason_review_component.html.erb
  app/components/candidate_interface/withdrawal_reasons/level_one_reason_review_component.rb
  app/components/candidate_interface/withdrawal_reasons/level_two_reasons_review_component.html.erb
  app/components/candidate_interface/withdrawal_reasons/level_two_reasons_review_component.rb
  app/controllers/candidate_interface/withdrawal_reasons/level_one_reasons_controller.rb
  app/controllers/candidate_interface/withdrawal_reasons/level_two_reasons_controller.rb
  app/controllers/candidate_interface/withdrawal_reasons/withdrawals_controller.rb
  app/forms/candidate_interface/withdrawal_reasons/level_one_reasons_form.rb
  app/forms/candidate_interface/withdrawal_reasons/level_two_reasons_builder.rb
  app/forms/candidate_interface/withdrawal_reasons/level_two_reasons_form.rb
  app/models/withdrawal_reason.rb
  app/services/candidate_interface/choices_controller_matcher.rb
  app/services/feature_flag.rb
  app/services/withdraw_application.rb
  app/views/candidate_interface/offer_dashboard/_sidebar.html.erb
  app/views/candidate_interface/withdrawal_reasons/level_one_reasons/_form.html.erb
  app/views/candidate_interface/withdrawal_reasons/level_one_reasons/edit.html.erb
  app/views/candidate_interface/withdrawal_reasons/level_one_reasons/new.html.erb
  app/views/candidate_interface/withdrawal_reasons/level_one_reasons/show.html.erb
  app/views/candidate_interface/withdrawal_reasons/level_two_reasons/_form.html.erb
  app/views/candidate_interface/withdrawal_reasons/level_two_reasons/new.html.erb
  app/views/candidate_interface/withdrawal_reasons/level_two_reasons/show.html.erb
  config/locales/candidate_interface/withdrawal_reasons.yml
  config/locales/components/candidate_interface/withdrawal_reasons/level_one_reason_review_component.yml
  config/locales/components/candidate_interface/withdrawal_reasons/secondary_reasons_review_component.yml
  config/routes/candidate.rb
  db/scripts/sanitise.sql
  spec/components/candidate_interface/application_dashboard_course_choices_component_spec.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
  spec/factories/withdrawal_reason.rb
  spec/forms/candidate_interface/withdrawal_reasons/level_one_reasons_form_spec.rb
  spec/forms/candidate_interface/withdrawal_reasons/level_two_reasons_builder_spec.rb
  spec/forms/candidate_interface/withdrawal_reasons/level_two_reasons_form_spec.rb
  spec/models/withdrawal_reason_spec.rb
  spec/support/test_helpers/withdrawal_reasons_test_helpers.rb
  spec/system/candidate_interface/carry_over/candidate_views_and_withdraws_after_apply_deadline_spec.rb
  spec/system/candidate_interface/withdrawal_reasons/candidate_selects_level_one_reason_only_spec.rb
  spec/system/candidate_interface/withdrawal_reasons/candidate_selects_level_two_withdrawal_reasons_spec.rb
  spec/system/candidate_interface/withdrawal_reasons/candidate_withdraws_application_choice_spec.rb
  spec/system/candidate_interface/withdraws/candidate_withdraws_spec.rb
  spec/system/candidate_interface/withdraws/candidate_withdraws_with_upcoming_interviews_spec.rb
Labels: deploy_v2

#10217 [537] Ensure production logs are in JSON format
  config/environments/production.rb
  config/initializers/semantic_logger.rb
Labels: deploy_v2

#10224 Rename Account Recovery Request Code
  config/analytics_blocklist.yml
  db/migrate/20250108120414_rename_account_recovery_request_code_column.rb
  db/schema.rb
Labels: deploy_v2

#10220 [506] update provider report to reflect new withdrawal reasons
  app/components/candidate_interface/withdrawal_reasons/level_two_reasons_review_component.rb
  app/controllers/provider_interface/reports/withdrawal_reasons_reports_controller.rb
  app/controllers/provider_interface/reports/withdrawal_reports_controller.rb
  app/forms/candidate_interface/withdrawal_reasons/level_two_reasons_builder.rb
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_withdrawal_reasons_report.scss
  app/helpers/navigation_items.rb
  app/models/application_choice.rb
  app/models/withdrawal_reason.rb
  app/services/provider_interface/candidate_withdrawal_reasons_data_by_provider.rb
  app/views/provider_interface/reports/index.html.erb
  app/views/provider_interface/reports/withdrawal_reasons_reports/show.html.erb
  app/views/provider_interface/reports/withdrawal_reports/index.html.erb
  app/views/provider_interface/reports/withdrawal_reports/show.html.erb
  config/locales/en.yml
  config/locales/provider_interface/reports.yml
  config/routes/provider.rb
  spec/models/application_choice_spec.rb
  spec/models/withdrawal_reason_spec.rb
  spec/services/provider_interface/candidate_withdrawal_reasons_data_by_provider_spec.rb
  spec/system/provider_interface/reports/index_provider_user_one_provider_spec.rb
  spec/system/provider_interface/reports/index_provider_user_two_providers_spec.rb
  spec/system/provider_interface/reports/index_provider_user_two_providers_with_performance_report_spec.rb
  spec/system/provider_interface/reports/provider_views_withdrawal_reasons_report_spec.rb
Labels: deploy_v2

#10228 Bulk unsubscribe Candidates in Support
  .erb_lint.yml
  app/controllers/support_interface/candidates/bulk_unsubscribes_controller.rb
  app/forms/support_interface/candidates/bulk_unsubscribe_form.rb
  app/services/support_interface/candidates/bulk_unsubscribe.rb
  app/views/support_interface/candidates/_candidates_navigation.html.erb
  app/views/support_interface/candidates/bulk_unsubscribes/new.html.erb
  app/workers/support/candidates/bulk_unsubscribe_worker.rb
  config/routes/support.rb
  spec/forms/support_interface/candidates/bulk_unsubscribe_form_spec.rb
  spec/services/support_interface/candidates/bulk_unsubscribe_spec.rb
  spec/system/support_interface/bulk_unsubscribe_candidates_spec.rb
  spec/workers/support/candidates/bulk_unsubscribe_worker_spec.rb
Labels: deploy_v2

#10250 [564] Support interface - delete withdrawal reasons when reverting withdrawal
  app/forms/support_interface/application_forms/revert_withdrawal_form.rb
  spec/forms/support_interface/application_forms/revert_withdrawal_form_spec.rb
Labels: deploy_v2

#10234 [556] Set model level default for `confidential` on `Reference`
  app/models/application_reference.rb
  spec/models/application_reference_spec.rb
Labels: deploy_v2

#10235 [556] Migration `RemoveDefaultAndNotNullConstraintsFromConfidential`
  db/migrate/20250109085508_remove_default_and_not_null_constraints_from_confidential.rb
  db/schema.rb
  docs/domain-model.png
  spec/presenters/vendor_api/v1.6/reference_presenter_spec.rb
Labels: deploy_v2

#10236 [556] Update confidential form to handle `nil` values
  app/forms/referee_interface/confidentiality_form.rb
  app/models/application_reference.rb
  spec/forms/referee_interface/confidentiality_form_spec.rb
  spec/models/application_reference_spec.rb
Labels: deploy_v2

#10232 [545] Remove feature flag uses throughout
  app/components/candidate_interface/application_review_component.html.erb
  app/components/candidate_interface/application_review_component.rb
  app/components/candidate_interface/course_choices_review_component.html.erb
  app/components/candidate_interface/course_choices_review_component.rb
  app/components/candidate_interface/course_choices_summary_card_action_component.html.erb
  app/components/candidate_interface/course_choices_summary_card_action_component.rb
  app/controllers/candidate_interface/decisions_controller.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/decisions/withdraw.html.erb
  app/views/candidate_interface/decisions/withdrawal_feedback.html.erb
  app/views/candidate_interface/offer_dashboard/_sidebar.html.erb
  app/views/provider_interface/reports/index.html.erb
  config/routes/candidate.rb
  spec/components/candidate_interface/application_dashboard_course_choices_component_spec.rb
  spec/components/candidate_interface/course_choices_review_component_spec.rb
  spec/controllers/concerns/back_links_spec.rb
  spec/support/test_helpers/withdrawal_reasons_test_helpers.rb
  spec/system/candidate_interface/carry_over/candidate_views_and_withdraws_after_apply_deadline_spec.rb
  spec/system/candidate_interface/withdrawal_reasons/candidate_selects_level_one_reason_only_spec.rb
  spec/system/candidate_interface/withdrawal_reasons/candidate_selects_level_two_withdrawal_reasons_spec.rb
  spec/system/candidate_interface/withdrawal_reasons/candidate_withdraws_application_choice_spec.rb
  spec/system/candidate_interface/withdrawal_reasons/candidate_withdraws_spec.rb
  spec/system/candidate_interface/withdrawal_reasons/candidate_withdraws_with_upcoming_interviews_spec.rb
  spec/system/candidate_interface/withdraws/candidate_withdraws_spec.rb
  spec/system/provider_interface/reports/index_provider_user_one_provider_spec.rb
  spec/system/provider_interface/reports/index_provider_user_two_providers_spec.rb
  spec/system/provider_interface/reports/index_provider_user_two_providers_with_performance_report_spec.rb
  spec/system/provider_interface/reports/provider_views_withdrawal_reasons_report_spec.rb
Labels: deploy_v2

#10241 [545] part 2 remove feature flag from database
  app/services/data_migrations/remove_new_withdrawal_reasons_feature_flag.rb
  lib/tasks/data.rake
  spec/services/data_migrations/remove_new_withdrawal_reasons_feature_flag_spec.rb
Labels: deploy_v2

#10272 [560 & 562] One login pre-release banners
  app/components/candidate_interface/one_login_pre_release_logged_in_banner_component.html.erb
  app/components/candidate_interface/one_login_pre_release_logged_in_banner_component.rb
  app/components/candidate_interface/one_login_pre_release_sign_in_banner_component.html.erb
  app/components/candidate_interface/one_login_pre_release_sign_in_banner_component.rb
  app/services/feature_flag.rb
  app/views/candidate_interface/application_choices/index.html.erb
  app/views/candidate_interface/shared/_details.html.erb
  app/views/candidate_interface/sign_in/new.html.erb
  app/views/candidate_interface/start_page/create_account_or_sign_in.html.erb
  config/locales/components/candidate_interface/one_login_pre_release_logged_in_banner_component.yml
  config/locales/components/candidate_interface/one_login_pre_release_sign_in_banner_component.yml
  spec/components/candidate_interface/one_login_pre_release_logged_in_banner_component_spec.rb
  spec/components/candidate_interface/one_login_pre_release_sign_in_banner_component_spec.rb
  spec/components/previews/candidate_interface/one_login_pre_release_banners_preview.rb
Labels: DO NOT MERGE, deploy_v2

#10259 [558] Add email to candidates about login changes
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/one_login_is_coming.text.erb
  app/workers/send_candidate_one_login_is_coming_email_worker.rb
  config/clock.rb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/system/support_interface/docs_spec.rb
  spec/workers/send_candidate_one_login_is_coming_email_worker_spec.rb
  spec/workers/send_one_login_is_coming_email_batch_worker_spec.rb
Labels: deploy_v2

#10287 Implement post-release one login email
  app/mailers/candidate_mailer.rb
  app/views/candidate_mailer/one_login_has_arrived.text.erb
  app/workers/send_candidate_one_login_has_arrived_email_worker.rb
  config/clock.rb
  config/locales/emails/candidate_mailer.yml
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/system/support_interface/docs_spec.rb
  spec/workers/send_candidate_one_login_has_arrived_email_worker_spec.rb
  spec/workers/send_one_login_has_arrived_email_batch_worker_spec.rb
Labels: deploy_v2

#10290 Implement post-release one login banner for sign in page
  app/components/candidate_interface/one_login_post_release_sign_in_banner_component.html.erb
  app/components/candidate_interface/one_login_post_release_sign_in_banner_component.rb
  app/views/candidate_interface/start_page/create_account_or_sign_in.html.erb
  config/locales/components/candidate_interface/one_login_post_release_sign_in_banner_component.yml
  spec/components/candidate_interface/one_login_post_release_sign_in_banner_component_spec.rb
  spec/components/previews/candidate_interface/one_login_pre_release_banners_preview.rb
Labels: deploy_v2

#10282 OneLogin Fallback Flow
  app/controllers/candidate_interface/sign_in_controller.rb
  app/controllers/candidate_interface/sign_up_controller.rb
  app/mailers/authentication_mailer.rb
  app/models/candidate.rb
  app/services/candidate_interface/request_magic_link.rb
  app/services/candidate_interface/sign_in_candidate.rb
  app/services/encryptor.rb
  app/views/candidate_interface/sign_in/expired.html.erb
  app/views/candidate_interface/sign_in/new.html.erb
  spec/mailers/authentication_mailer_spec.rb
  spec/mailers/previews/authentication_mailer_preview.rb
  spec/models/candidate_spec.rb
  spec/services/encryptor_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_clicking_on_expired_magic_link_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_using_legacy_email_link_with_u_param_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_in_with_an_authentication_token_with_a_path_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_signs_up_using_magic_link_with_an_invalid_token_spec.rb
  spec/system/candidate_interface/signup_and_signin/candidate_tries_to_reuse_magic_link_spec.rb
  spec/system/candidate_interface/signup_and_signin/fallback_flow/candidate_signs_in_spec.rb
  spec/system/candidate_interface/signup_and_signin/fallback_flow/candidate_signs_up_spec.rb
  spec/system/candidate_interface/signup_and_signin/fallback_flow/candidate_uses_start_page_spec.rb
Labels: deploy_v2

#10291 [445] Update referee emails to include confidentiality statement
  app/mailers/referee_mailer.rb
  app/views/referee_mailer/reference_request_email.text.erb
  spec/mailers/referee_mailer_spec.rb
Labels: deploy_v2

#10295 [594] Surface whether candidate has a one login account on support
  app/components/support_interface/application_summary_component.rb
  app/models/candidate.rb
  spec/components/support_interface/application_summary_component_spec.rb
  spec/models/candidate_spec.rb
Labels: deploy_v2

#10294 Add Api tokens counters to support api token index page
  app/controllers/support_interface/api_tokens_controller.rb
  app/models/vendor_api_token.rb
  app/views/support_interface/api_tokens/index.html.erb
  spec/system/support_interface/api_tokens/view_tokens_spec.rb
Labels: deploy_v2

#10299 Redirect the candidate to the correct error page
  app/controllers/one_login_controller.rb
  app/models/session_error.rb
  spec/requests/one_login_controller_spec.rb
Labels: deploy_v2

#10302 Filter and export support vendor api page
  app/controllers/support_interface/api_tokens_controller.rb
  app/models/support_interface/vendor_api_token_filter.rb
  app/services/support_interface/vendor_api_tokens_csv_export.rb
  app/views/support_interface/api_tokens/index.html.erb
  spec/models/support_interface/vendor_api_token_filter_spec.rb
  spec/services/support_interface/vendor_api_tokens_csv_export_spec.rb
  spec/system/support_interface/api_tokens/view_tokens_spec.rb
Labels: deploy_v2

#10321 Add one login email address to what support users can see about a candidate
  app/components/support_interface/application_summary_component.rb
  spec/components/support_interface/application_summary_component_spec.rb
Labels: deploy_v2

#10322 feat: Fixing apex domain redirect for AFTT
  terraform/custom_domains/environment_domains/workspace_variables/apply_production.tfvars.json
Labels: DevOps

#10323 [593] Edit email subscription status (support functionality)
  app/components/support_interface/application_summary_component.rb
  app/controllers/support_interface/application_forms/email_subscription_controller.rb
  app/forms/support_interface/email_subscription_form.rb
  app/models/candidate.rb
  app/views/support_interface/application_forms/email_subscription/edit.html.erb
  config/locales/en.yml
  config/locales/support_interface/support_interface.yml
  config/routes/support.rb
  spec/forms/support_interface/email_subscription_form_spec.rb
  spec/system/support_interface/editing_email_subscription_status_spec.rb
Labels: deploy_v2
