Repository DFE-Digital/apply-for-teacher-training, pull requests merged in 2025-05, with the labels that each got.

#10668 Updated location filtering on FAC
  app/models/candidate.rb
  app/models/candidate_location_preference.rb
  app/models/pool/candidates.rb
Labels: deploy_v2

#10675 [890] Bug: fix wrong application form associations being returned
  app/controllers/provider_interface/candidate_pool/candidates_controller.rb
  app/models/pool/candidates.rb
  spec/models/pool/candidates_spec.rb
Labels: deploy_v2

#10666 [788] Find a candidate new designs for application page
  app/components/provider_interface/find_candidates/application_choices_component.html.erb
  app/components/provider_interface/find_candidates/application_choices_component.rb
  app/components/provider_interface/find_candidates/degrees_table_component.html.erb
  app/components/provider_interface/find_candidates/degrees_table_component.rb
  app/components/provider_interface/find_candidates/efl_qualification_card_component.html.erb
  app/components/provider_interface/find_candidates/efl_qualification_card_component.rb
  app/components/provider_interface/find_candidates/experience_details_component.html.erb
  app/components/provider_interface/find_candidates/experience_details_component.rb
  app/components/provider_interface/find_candidates/gcse_qualifications_table_component.html.erb
  app/components/provider_interface/find_candidates/gcse_qualifications_table_component.rb
  app/components/provider_interface/find_candidates/other_qualifications_component.html.erb
  app/components/provider_interface/find_candidates/other_qualifications_component.rb
  app/components/provider_interface/find_candidates/personal_statement_component.html.erb
  app/components/provider_interface/find_candidates/personal_statement_component.rb
  app/components/provider_interface/find_candidates/right_to_work_component.html.erb
  app/components/provider_interface/find_candidates/safeguarding_component.html.erb
  app/components/provider_interface/find_candidates/work_history_summary_component.html.erb
  app/components/provider_interface/find_candidates/work_history_summary_component.rb
  app/components/shared/work_history_and_unpaid_experience_component.html.erb
  app/components/shared/work_history_and_unpaid_experience_component.rb
  app/frontend/packs/application-provider.js
  app/frontend/packs/components/show-more-show-less.js
  app/frontend/styles/_previews.scss
  app/frontend/styles/application.scss
  app/frontend/styles/provider/_all.scss
  app/frontend/styles/provider/_qualifications-table.scss
  app/views/provider_interface/candidate_pool/candidates/show.html.erb
  config/locales/components/provider_interface/find_candidates/en.yml
  config/locales/provider_interface/candidate_pool_invites.yml
  spec/components/previews/provider_interface/find_candidates/degrees_table_component_preview.rb
  spec/components/previews/provider_interface/find_candidates/gcse_qualifications_table_component_preview.rb
  spec/components/provider_interface/find_candidates/application_choices_component_spec.rb
  spec/components/provider_interface/find_candidates/degrees_table_component_spec.rb
  spec/components/provider_interface/find_candidates/efl_qualification_card_component_spec.rb
  spec/components/provider_interface/find_candidates/gcse_qualifications_table_component_spec.rb
  spec/components/provider_interface/find_candidates/safeguarding_component_spec.rb
  spec/factories/application_qualification.rb
  spec/forms/candidate_interface/degree_wizard_spec.rb
  spec/system/provider_interface/candidate_pool/provider_views_a_candidate_on_candidate_pool_spec.rb
Labels: deploy_v2

#10723 Ruby dependabots
  Gemfile.lock
Labels: deploy_v2

#10715 [861] Allow support users to add ENIC reference to degrees
  app/controllers/support_interface/application_forms/degrees_controller.rb
  app/forms/support_interface/application_forms/edit_degree_form.rb
  app/views/support_interface/application_forms/degrees/edit.html.erb
  config/locales/support_interface/application_forms/degrees.yml
  config/locales/support_interface/support_interface.yml
  docs/support_playbook.md
  spec/system/support_interface/editing_international_degree_spec.rb
  spec/system/support_interface/editing_uk_degree_spec.rb
Labels: deploy_v2

#10716 Create new EFL summary component for review and submit course choice page
  app/components/candidate_interface/english_foreign_language/summary_review_component.rb
  app/views/candidate_interface/application_form/_review_unsubmitted.html.erb
  config/locales/candidate_interface/english_foreign_language.yml
  spec/components/candidate_interface/english_foreign_language/summary_review_component_spec.rb
  spec/components/previews/candidate_interface/english_foreign_language/summary_review_component_preview.rb
Labels: deploy_v2

#10697 Adding default EXCLUDE_TABLES for sanitise workflow
  .github/workflows/backup-db-sanitise.yml
Labels: DevOps

#10731 [729] Bug: personal email flight check not shown if personal statement flight check shown
  app/components/candidate_interface/application_review_and_submit_component.rb
  app/components/candidate_interface/continue_without_editing.rb
  app/controllers/candidate_interface/course_choices/review_enic_interruption_controller.rb
  app/controllers/candidate_interface/course_choices/review_interruption_controller.rb
  app/controllers/candidate_interface/course_choices/review_references_interruption_controller.rb
  app/controllers/candidate_interface/course_choices/review_undergraduate_interruption_controller.rb
  app/services/candidate_interface/review_interruption_path_decider.rb
  app/views/candidate_interface/course_choices/review_enic_interruption/_not_needed.html.erb
  app/views/candidate_interface/course_choices/review_enic_interruption/_waiting_maybe.html.erb
  app/views/candidate_interface/course_choices/review_interruption/show.html.erb
  app/views/candidate_interface/course_choices/review_references_interruption/show.html.erb
  app/views/candidate_interface/course_choices/review_undergraduate_interruption/show.html.erb
  spec/components/candidate_interface/continue_without_editing_spec.rb
  spec/factories/course.rb
  spec/services/candidate_interface/review_interruption_path_decider_spec.rb
Labels: deploy_v2

#10730 Simplifies Audit Log creation for previews
  spec/components/previews/provider_interface/activity_log_event_component_preview.rb
  spec/factories/application_choice.rb
  spec/factories/application_choice_audit.rb
Labels: deploy_v2

#10712 Daily summary invite emails
  app/controllers/provider_interface/candidate_pool/publish_invites_controller.rb
  app/mailers/candidate_mailer.rb
  app/models/pool/invite.rb
  app/services/feature_flag.rb
  app/views/candidate_mailer/candidate_invites.text.erb
  app/views/candidate_mailer/course_invite.text.erb
  app/workers/find_a_candidate/send_invite_emails_worker.rb
  config/clock.rb
  config/locales/emails/candidate_mailer.yml
  spec/factories/pool_dismissal.rb
  spec/factories/pool_invite.rb
  spec/mailers/candidate_mailer/candidate_mailer_course_invite_spec.rb
  spec/mailers/candidate_mailer/candidate_mailer_grouped_invite_spec.rb
  spec/mailers/previews/candidate_mailer_preview.rb
  spec/models/pool/invite_spec.rb
  spec/requests/provider_interface/candidate_pool/publish_invites_controller_spec.rb
  spec/system/support_interface/docs_spec.rb
  spec/workers/find_a_candidate/send_invite_emails_worker_spec.rb
Labels: deploy_v2

#10738 [895] Add opt out reason field to candidate preferences form
  app/controllers/candidate_interface/pool_opt_ins_controller.rb
  app/forms/candidate_interface/pool_opt_ins_form.rb
  app/views/candidate_interface/pool_opt_ins/_form.html.erb
  config/locales/candidate_interface/preferences.yml
  spec/forms/candidate_interface/pool_opt_ins_form_spec.rb
  spec/system/candidate_interface/preferences/candidate_adds_preferences_spec.rb
  spec/system/candidate_interface/preferences/candidate_edits_published_preference_spec.rb
Labels: deploy_v2

#10713 Add FAC identifiers in support
  app/components/support_interface/application_summary_component.rb
  app/controllers/candidate_interface/draft_preferences_controller.rb
  app/controllers/candidate_interface/location_preferences_controller.rb
  app/controllers/candidate_interface/publish_preferences_controller.rb
  app/decorators/location_preference_decorator.rb
  app/models/pool/candidates.rb
  config/locales/support_interface/application_summary_component.yml
  spec/components/support_interface/application_summary_component_spec.rb
  spec/decorators/candidate_interface/location_preference_decorator_spec.rb
Labels: deploy_v2

#10751 Refactor the Pool::Candidate methods
  app/components/support_interface/application_summary_component.rb
  app/controllers/provider_interface/candidate_pool/candidates_controller.rb
  app/controllers/provider_interface/candidate_pool/draft_invites_controller.rb
  app/controllers/provider_interface/candidate_pool/publish_invites_controller.rb
  app/controllers/support_interface/find_candidates_controller.rb
  app/models/pool/candidates.rb
  app/workers/candidate/pool_eligible_application_form_worker.rb
  spec/components/support_interface/application_summary_component_spec.rb
  spec/factories/candidate_pool_applications.rb
  spec/models/pool/candidates_spec.rb
  spec/requests/provider_interface/candidate_pool/publish_invites_controller_spec.rb
  spec/system/provider_interface/candidate_pool/provider_cannot_send_invites_spec.rb
  spec/system/provider_interface/candidate_pool/provider_invites_candidate_to_apply_spec.rb
  spec/system/provider_interface/candidate_pool/provider_views_a_candidate_on_candidate_pool_spec.rb
  spec/system/provider_interface/candidate_pool/provider_views_candidate_pool_list_spec.rb
  spec/system/support_interface/find_a_candidate_spec.rb
Labels: deploy_v2

#10733 Lb/933 re instate public roadmap page
  app/controllers/provider_interface/content_controller.rb
  app/views/content/roadmap.md
  app/views/layouts/_footer_meta_provider.html.erb
  app/views/provider_interface/content/roadmap.html.erb
  config/locales/en.yml
  config/locales/provider_interface/content/roadmap.yml
Labels: DO NOT MERGE, deploy_v2

#10763 Ensure references are marked incomplete when adding
  app/controllers/candidate_interface/references/review_controller.rb
  app/forms/candidate_interface/reference/referee_name_form.rb
  spec/system/candidate_interface/references/candidate_adds_references_after_completing_section_spec.rb
Labels: deploy_v2

#10762 feat(1975): convert att to use latest version of delete review app workflow
  .github/workflows/delete-v2-review-app.yml
  Makefile
  global_config/review.sh
Labels: DevOps

#10769 Ensure all TTA sign up opportunities are behind feature flag
  app/controllers/candidate_interface/adviser_sign_ups/interruptions_controller.rb
  app/controllers/candidate_interface/adviser_sign_ups_controller.rb
  app/views/candidate_interface/course_choices/go_to_find/new.html.erb
  app/views/candidate_interface/details/_adviser_call_to_action.html.erb
  app/views/candidate_interface/gcse/missing_qualification/_form.html.erb
  app/views/candidate_interface/personal_statement/_form.html.erb
  spec/system/candidate_interface/adviser_sign_up/candidate_becomes_eligible_for_adviser_spec.rb
Labels: deploy_v2

#10764 Add FAC opt in status filters to Support index
  app/models/application_form.rb
  app/models/support_interface/applications_filter.rb
  spec/models/application_form_spec.rb
  spec/models/support_interface/applications_filter_spec.rb
Labels: deploy_v2
